### ISSUE TITLE
Investigate linting for static Drupal Functions

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1002]
Smart developers are using "\Drupal::" to access services instead of using Dependency Injection in the scope of classes.   This could be caught during commit hooks so that we enforce best practices.  

D8 best practices is typically to use dependency injection rather than using drupal:: e.g

The following from inside a class is bad:
`$menu_tree = \Drupal::menuTree();`

Instead one should inject the service like: 
````
 * {@inheritdoc}
    */
    public function __construct(array $configuration, $plugin_id, $plugin_definition, MenuLinkTreeInterface $menu_tree) {
        parent::__construct($configuration, $plugin_id, $plugin_definition);
        $this->menuTree = $menu_tree;
    }

   /**
    * {@inheritdoc}
    */
    public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
        return new static(
        $configuration,
        $plugin_id,
        $plugin_definition,
        $container->get('menu.link_tree')
    );
  }
````

**Comment by grasmash** [comment]
This is something that should be handled by the coder module. Once the coding standards are updated, BLT will automatically receive the update and perform this check.
