### ISSUE TITLE
Make the cm.core.config-dir property configurable

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#1013]
Ok, so I thought I could deal with this, but every time I'm prompted for a config directory when I do a config import or export I die a little inside :)

Here's the main issue where I brought this up: https://github.com/acquia/blt/issues/678

Basically, Drupal wants there to be a config directory labeled 'sync' (it complains if it doesn't exist), but [BLT wants there to be one labeled 'vcs'](https://github.com/acquia/blt/blob/c6b27ddf0b16b49bbc1632a56fb7c11f946a8201/phing/tasks/deploy.xml#L224).

My site only uses one actual config directory. As a result I have this snippet at the very bottom of my site's settings.php file:

```
$config_dir = dirname(DRUPAL_ROOT) . "/config/$site_dir";
$config_directories['sync'] = $config_dir;
$config_directories['vcs'] = $config_dir;
```

That way they are both defined and BLT and Drupal are happy.

But because of that, whenever I do a config export or config import, I'm prompted to chose one of those, even though they are the same.

What I suggest doing here is changing [this line](https://github.com/acquia/blt/blob/c6b27ddf0b16b49bbc1632a56fb7c11f946a8201/phing/tasks/deploy.xml#L224) so that it accepts a parameter instead of hardcoding "vcs". Then I could configure it on my project.yml file.

**Comment by bkosborne** [comment]
OK, so after further inspection, Acquia Cloud's settings.php file, which BLT includes, includes, actually does set both 'vcs' and 'sync' directories:

```
$config_directories['sync'] = $app_root . '/' . $site_path . '/files/config_123ABC/sync';
if (!drupal_installation_attempted()) {
  $config_directories['vcs'] = $app_root . '/../config/' . basename($site_path);
  ...
}
```

How frustrating.

So I would have to _unset_ it's definition in my settings.php overrides, which execute after the inclusion of Acquia's files:

```
$config_dir = dirname(DRUPAL_ROOT) . "/config/$site_dir";
$config_directories['sync'] = $config_dir;
// Unset config directory that Acquia defines. We just use the main 'sync' directory above.
unset($config_directories['sync']);
```

So still, I need to be able to tell BLT to not try and import configuration from the 'vcs' config directory.

**Comment by grasmash** [comment]
@bkosborne The simplest solution for you may be to disable the setup:config-import task, or replace it with your own custom task.

**Comment by bkosborne** [comment]
Interestingly enough, it looks like there is a already a default variable defined for "cm.core.config-dir" here: https://github.com/acquia/blt/blob/8.x/phing/build.yml#L39

But the value of the var is not being used.

**Comment by bkosborne** [comment]
Ok, created a PR just to remove the override of the config sync directory in the deploy task. There's already a var defined for that directory, the deploy task was overriding it to use "vcs" instead.

Would def need a change log notice if accepted.

In the mean time, for my project, I just overwrote the deploy:update target and removed the property override entirely.

**Comment by bkosborne** [comment]
For future reference, I think I now understand why Acquia has two config directories, "vcs" and the default "sync" one that Drupal needs.

If you take the approach I take and just use the ../config/default/ as the only config directory, and set Drupal's "sync" config directory to this path, then you will not be able to export active config in Drupal's UI because ../config/default is not writeable by the web server.

I'm OK with that, since I can use drush to export the active config and specify the --destination parameter to specify a writeable directory elsewhere on the server, then copy the files down.

**Comment by grasmash** [comment]
`cm.core.config-dir` is now configurable as of #1080

**Comment by bkosborne** [comment]
See https://support.acquia.com/hc/en-us/articles/360005216614-Acquia-vcs-config-directory-vs-Drupal-8-sync-directory for more info
