### ISSUE TITLE
Allow custom Twig lint paths

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1016]
Feature request: Allow setting of custom paths to execute twig linting against. My thought/hope is that, similar to the way you can set custom paths for PHPCS to execute against, allow this for Twig linting as well.

**Comment by grasmash** [comment]
Currently, we just scan `${docroot}/modules/custom` and `${docroot}/themes/custom` [here](https://github.com/acquia/blt/blob/8.x/phing/tasks/validate.xml#L98). 

We could:

- [ ] Introduced a new `twig.filesets` variable like [phpcs.filesets](https://github.com/acquia/blt/blob/8.x/phing/build.yml#L108)
- [ ] Set default value of `twig.filesets` to `[ files.frontend.custom.themes ]`. We may need to introduce a `files.frontend.custom.themes.twig` if that doesn't work.
- [ ] Create `validate:twig:fileset` set target designed to validate a single fileset, modeled from [validate:phpcs:fileset](https://github.com/acquia/blt/blob/8.x/phing/tasks/validate.xml#L82)
- [ ] Modify `validate:twig` to iterate over each `twig.filesets` in a `<foreach>`, modeled off of [validate:phpcs](https://github.com/acquia/blt/blob/8.x/phing/tasks/validate.xml#L77)
- [ ]

**Comment by malikkotob** [comment]
I intend to work this issue, but will port the validate suite of targets over to Robo first.

**Comment by grasmash** [comment]
This was completed when the `validate:twig` target was ported to Robo.

**Comment by dpagini** [comment]
Awesome, thanks @grasmash!
