### ISSUE TITLE
blt > deploy:composer:install: results in travis-ci ssh protocol error on git clone of package

### ISSUE THREAD

**Issue by mariagwyn** [acquia/blt#1026]
My system information:
* Operating system type: [Mac]
* Operating system version: [OSX]
* BLT version: [8.6.11]

When TRAVIS-CI runs this command as a part of its build:
```
blt > deploy:composer:install:
```

The following error results
```
  - Installing enyo/dropzone (4.2.0) Cloning origin/master
                                                                                                             
  [RuntimeException]                                                                                         
  Failed to clone https://github.com/enyo/dropzone via https, ssh protocols, aborting.                       
  - https://github.com/enyo/dropzone                                                                         
    Cloning into 'docroot/libraries/dropzone'...                                                             
    fatal: repository 'https://github.com/enyo/dropzone/' not found                                          
  - git@github.com:enyo/dropzone                                                                             
    Cloning into 'docroot/libraries/dropzone'...                                                             
    Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.  
    Permission denied (publickey).                                                                           
    fatal: Could not read from remote repository.                                                            
                                                                                                             
    Please make sure you have the correct access rights                                                      
    and the repository exists.                                                                               
```
See https://travis-ci.org/mariagwyn/eemmcdowell/builds/197472588#L1385.

And I expected this it to work like it did here: https://travis-ci.org/mariagwyn/eemmcdowell/builds/197472588#L544 where travis was running 
```
composer install
```

The [composer.json](https://github.com/mariagwyn/eemmcdowell/blob/master/composer.json) includes packages that are both of the type 'git' and 'zip'. BLT does not appear to have a problem with .zip as the masonry package works just fine.

**Comment by grasmash** [comment]
@mariagwyn I don't believe that BLT is involved in this error. 

The issue is with Composer. I would expect a modification to your composer.json to be necessary.

Feel free to ping me directly in chat if you'd like help debugging your composer configuration.

**Comment by mariagwyn** [comment]
In case anyone comes looking, the problem is that dropzone in particular does not play well with Travis when SSH is used.

So this fails:
`        "3": {
          "type": "package",
          "package": {
              "name": "enyo/dropzone",
              "version": "4.2.0",
              "type": "drupal-library",
              "source": {
                  "url": "https://github.com/enyo/dropzone",
                  "type": "git",
                  "reference": "origin/master"
                }
            }
        },
`

but this does not:

`        "3": {
          "type": "package",
          "package": {
              "name": "enyo/dropzone",
              "version": "4.2.0",
              "type": "drupal-library",
              "dist": {
                  "url": "https://github.com/enyo/dropzone/archive/v4.2.0.zip",
                  "type": "zip"
                }
            }
        },
`

A better solutions for adding custom drupal libraries is to utilize https://github.com/oomphinc/composer-installers-extender.

**Comment by mariagwyn** [comment]
https://github.com/acquia/blt/pull/1064 solves the problem in part by adding composer-installers-extender to blt by default.
