### ISSUE TITLE
Multisite setup improvements

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1028]
Just capturing some of the friction points I encountered while setting up multisite.

1. I've documented the basic setup process in #1027, but I think a lot of these steps could be automated with a simple multisite setup command. This could copy directories and settings files, create aliases, and set $site_dir to start with (see next).
2. Right now `$site_dir` needs to be manually set and is used to set a bunch of other configs (such as public files path). It seems like it would be pretty easy to set this automatically. #1086 
3. Right now all settings files are duplicated between every site in the codebase. This makes updating these files non trivial and very error prone. It would be better if generic settings could go into `sites/all` or get symlinked to a master copy in `sites/default` or something along those lines. EDIT: actually the BLT settings.php includes are hardcoded to pull from sites/default/settings/*. Which I guess sort of solves this problem, it just wasn't what I was expecting.

**Comment by grasmash** [comment]
@danepowell Can you point me to the code that you're referencing here?

> Actually the BLT settings.php includes are hardcoded to pull from sites/default/settings/*. Which I guess sort of solves this problem, it just wasn't what I was expecting.

Can we consider the third point complete?

**Comment by danepowell** [comment]
Yeah, I wasn't even really referring to BLT... each project can decide how they want to pull in any other settings files. I don't think BLT needs to worry about it.

**Comment by grasmash** [comment]
Cool. Other issues addressed!
