### ISSUE TITLE
Cannot Write Settings.php 

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#103]
When using the drupalvm approach to setting up my *AMP stack, everything installed and worked as i expexcted, but when i tried to run the final command from on vm, to install lightning, i get a file permissions issue. ergo it cant write it. Also, when i tried to run the command on my mac locally, it couldnt access the database. 

given the issue, i am wondering where to run ./blt.sh local:setup so it will work, or what must i do to get this working.

**Comment by grasmash** [comment]
The Drupal VM documentation was lacking, it's been updated in #104. Please try new instructions and see if it resolves your issue.

**Comment by haynescw** [comment]
I get the same output when i run the ./blt.sh local:setup command. Where should that command be ran when doing the drupalvm *AMP stack.

Also, im wondering is we need to change up one directory when trying to sun the site install drush command so it can find the @self drush alias.

**Comment by haynescw** [comment]
I feel this may be related to line 4.Updating project.yml so that drush.default_alias is set to your Drupal VM alias in the readme, Can you elaborate more on what needs to be done?
