### ISSUE TITLE
 jakoch/phantomjs-installer 2.1.1-p08 requires ext-bz2 * -> the requested PHP extension bz2 is missing from your system.

### ISSUE THREAD

**Issue by jayakrishnanj** [acquia/blt#1033]
Update BLT and make sure VM settings and Composer are up to date.
On latest version of BLT project, running blt local:refresh, the build fails with the following issue:

  Problem 1
    - jakoch/phantomjs-installer 2.1.1-p08 requires ext-bz2 * -> the requested PHP extension bz2 is missing from your system.
    - jakoch/phantomjs-installer 2.1.1-p08 requires ext-bz2 * -> the requested PHP extension bz2 is missing from your system.
    - Installation request for jakoch/phantomjs-installer 2.1.1-p08 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p08].
It seems like composer needs some updates and possible the config.yml for the vm.

**Comment by jayakrishnanj** [comment]
`vagrant@vm:/var/www/vm/projectname$ blt local:setup
blt > local:setup:
blt > setup:git-hooks:
   [delete] Deleting: /var/www/vm/projectname/.git/hooks/pre-commit
   [delete] Deleting: /var/www/vm/projectname/.git/hooks/commit-msg
     [echo] Symlinking /var/www/vm/projectname/.git/hooks/pre-commit to /var/www/vm/tateandlyle/vendor/acquia/blt/scripts/git-hooks/pre-commit
     [exec] 'pre-commit' -> '/var/www/vm/projectname/vendor/acquia/blt/scripts/git-hooks/pre-commit'
     [exec] 'commit-msg' -> '/var/www/vm/projectname/vendor/acquia/blt/scripts/git-hooks/commit-msg'
blt > setup:composer:install:
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jakoch/phantomjs-installer 2.1.1-p08 requires ext-bz2 * -> the requested PHP extension bz2 is missing from your system.
    - jakoch/phantomjs-installer 2.1.1-p08 requires ext-bz2 * -> the requested PHP extension bz2 is missing from your system.
    - Installation request for jakoch/phantomjs-installer 2.1.1-p08 -> satisfiable by jakoch/phantomjs-installer[2.1.1-p08].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/15-xml.ini
    - /etc/php/7.0/cli/conf.d/20-apcu.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-dom.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gd.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-imap.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mbstring.ini
    - /etc/php/7.0/cli/conf.d/20-mcrypt.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_sqlite.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-simplexml.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sqlite3.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.0/cli/conf.d/20-wddx.ini
    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.0/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.0/cli/conf.d/20-xsl.ini
    - /etc/php/7.0/cli/conf.d/20-yaml.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
[phingcall] /var/www/vm/projectname/vendor/acquia/blt/phing/tasks/setup.xml:56:200: Task exited with code 2

BUILD FAILED/var/www/vm/projectname/vendor/acquia/blt/phing/tasks/local-sync.xml:12:30: Execution of the target buildfile failed. Aborting.
; 5.6574 seconds`

**Comment by geerlingguy** [comment]
@jayakrishnanj - See: https://github.com/acquia/blt/pull/1018

This fix is merged, but not yet in a release (as of this writing).

**Comment by jayakrishnanj** [comment]
Running the command `sudo apt-get install -y php5.6-bz2` inside VM solved the issue.

**Comment by huuvinh2019** [comment]
I install it for php7.3 like this: apt-get install -y php7.3-bz2
No message error but didn't see this extension, anyone have another solution?

**Comment by tohqjvit** [comment]
I install it for php7.3 like this: apt-get install -y php7.3-bz2
No message error but didn't see this extension, anyone have another solution?

**Comment by robert-duplock-adg** [comment]
In Ubuntu 20.04 I simply used `sudo apt install php-bz2`
