### ISSUE TITLE
Travis MySQL errors

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1036]
This isn't a bug with BLT per se, but since many BLT projects rely heavily on Travis it's worth implementing a workaround.

Ever since moving to container-based builds, we frequently see builds failing with this error:

> ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

According to Travis support, this could be due to MySQL not being fully initialized before we attempt to connect to it, and they suggest adding a sleep statement, i.e.:

```yaml
before_install:
  # Allow MySQL to finish starting.
  - sleep 3
```

I'm testing this on a few projects but since it's such an intermittent error it would be good to get more eyes on this so we can verify the workaround and incorporate it into BLT.

**Comment by danepowell** [comment]
This seems to be working on our projects, so I opened a PR.

Here's the community issue on this: https://github.com/travis-ci/travis-ci/issues/6842

**Comment by geerlingguy** [comment]
Still getting this problem even with the `sleep 3` in the latest 8.6.13 release...

Only happens in maybe 1/4 builds, requires a 'restart job' click to get things going.

**Comment by danepowell** [comment]
@geerlingguy Travis support indicated that the only way to fix this for now is to move away from containerized builds. Hence this PR: https://github.com/acquia/blt/pull/1122

So I guess we can consider this "fixed" for now, but ultimately it would be nice to move back to containerized builds (or off of Travis altogether...)

**Comment by geerlingguy** [comment]
@danepowell - I guess it was good while it lasted... :)
