### ISSUE TITLE
Unable to Download and install phantomJS

### ISSUE THREAD

**Issue by charliemurphy07** [acquia/blt#1044]
My system information:
* Operating system type: Mac OSX 
* Operating system version: 10.11.6 El Capitan
* BLT version: 8.6.10

When I run this command:
```
 composer install
```

I get the following output:
```
PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (2.1.1)
    Downloading: Failed       
The "https://api.bitbucket.org/2.0/repositories/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip" file could not be downloaded: failed to open stream: Operation timed out
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

```

And I expected this to happen:
Successful download and install of phantomJS

**Comment by grasmash** [comment]
This is a known issue with PhantomJS installer. See.:
* https://github.com/jakoch/phantomjs-installer/issues/35
* https://github.com/jakoch/phantomjs-installer/issues/34

Also https://github.com/acquia/blt/issues/223

BLT now defaults to using Selenium, which does not encounter this issue. I would suggest using Selenium instead.
