### ISSUE TITLE
Allow PHPUnit Tests to Bootstrap Drupal

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1048]
Currently PHPUnit doesn't include any references to Drupal (specifically, no bootstrap, and no reference to the Drupal config file at ${docroot}/core/phpunit.xml.dist).

It would be ideal if BLT had some method of allowing PHPUnit tests to include this parameter, as it is possible to have tests that are perfectly valid WITH this parameter that will FAIL without.

Note that I have attempted to modify the phing call https://github.com/acquia/blt/blob/8.x/phing/tasks/tests.xml#L243 per the parameters specific at https://www.phing.info/docs/guide/trunk/PHPUnitTask.html (see configuration) but it doesn't seem to actually load that configuration file. 

`<phpunit configuration="${docroot}/core/phpunit.xml.dist" printsummary="true" failureproperty="phpunit.failures" errorproperty="phpunit.errors">`

Unclear if this is a bug in phing itself or something wrong with BLT. I have attempted this with the file renamed to just be .xml (no luck). I've also attempted to pass a bootstrap parameter (instead of the configuration parameter) and that also appears to be non-functional.

**Comment by mikemadison13** [comment]
I have temporarily solved this issue by adding a custom phing target to my project, and executing the tests (in the module directory) with a custom exec script inside of the phpunit target.

`<exec dir="${repo.root}" command="vendor/bin/phpunit docroot/modules/custom/<module>/tests -c docroot/core/phpunit.xml.dist" logoutput="true" checkreturn="true"/>`

**Comment by mikemadison13** [comment]
This ticket is related to, but not identical to https://github.com/acquia/blt/issues/1047

**Comment by mikemadison13** [comment]
Note that my work around for this no longer works (above) as the phing target for phpunit tests is no longer present in BLT 8.8.x

**Comment by grasmash** [comment]
Resolved by #1047
