### ISSUE TITLE
Mysql missing "drupal" user causing installation to fail

### ISSUE THREAD

**Issue by aangelinsf** [acquia/blt#1050]
My system information:
* Operating system type: MacOS 
* Operating system version: 10.12.2
* BLT version: Phing 2.15.2  (this was the result of 'blt -version'; seems weird)

After using composer to bring down the Lightning distro, I added the project to Dev Desktop per the instructions.

Continuing with the installation I then ran this command:
```
blt local:setup
```

I got the following output:
```
Failed to create database: ERROR 1044 (42000) at line 1: Access denied for user 'drupal'@'localhost' to database 'drupal'                                               [error]
[phingcall] /Users/andreangelantoni/Sites/devdesktop/<clientname>/./vendor/acquia/blt/phing/tasks/setup.xml:176:34: Drush exited with code 1
```

And I expected this to happen:
```
Starting Drupal installation. This takes a while.
```

== Solution ==

The phing command is a simple:
```
    <echo>Installing Drupal...</echo>
    <drush command="site-install">
      <option name="site-name">"${project.human_name}"</option>
      <option name="site-mail">"${drupal.account.mail}"</option>
      <option name="account-name">"${drupal.account.name}"</option>
      <option name="account-pass">"${drupal.account.password}"</option>
      <option name="account-mail">"${drupal.account.mail}"</option>
      <param>"${project.profile.name}"</param>
      <param>"install_configure_form.update_status_module='array(FALSE,FALSE)'"</param>
    </drush>
```

And the ``loc_<clientname>_dd.inc`` was using 'drupaluser' for the username and '' for the password.

I checked with:
```
select * from mysql.user;
```

and saw only 'drupaluser' – but BLT wants 'drupal'.

In ``loc_<clientname>_dd.inc`` I changed the credentials to 'drupal' and 'drupal' (since that seems to be what BLT wants) then created that user on mysql:
```
GRANT ALL PRIVILEGES ON *.* to 'drupal'@'localhost' IDENTIFIED BY 'drupal';
```

I restarted Dev Desktop, ran `blt local:setup` and it was able to complete the installation.

I was running Sep 5 2016 of DevDesktop then upgraded to Feb 1, 2017 and that made no difference (which makes sense because I didn't kill the previous mysql install so all prior users were still there and there was no opportunity to create new ones).

== Bottom Line ==
There is a possible mismatch in what Dev Desktop creates for the mysql user (user:drupaluser pwd:'') and what BLT wants ('drupal'/'drupal');

However, since I didn't create a new mysql instance with the Feb 1, 2017 version of Dev Desktop, I don't know for sure if there is a mismatch.

**Comment by grasmash** [comment]
You just need to modify your SQL credentials in `local.settings.php`. Change the credentials to match your local SQL server.

**Comment by aangelinsf** [comment]
I realize that's the workaround. What I'm pointing out is that it isn't a smooth installation because it appears that the credentials aren't the same. The message doesn't tell me that that's the problem so I'm posting here to alert others and in case there is an issue you folks want to look at.

**Comment by grasmash** [comment]
@aangelinsf Good point. We should point out the issue.

There is a large initiative underway to port BLT from Phing to Robo PHP, which will allow us to provide more informative error messages when underlying tools encounter errors.
