### ISSUE TITLE
Add blt setup:toggle-modules to post-db-copy hook

### ISSUE THREAD

**Issue by snize** [acquia/blt#1051]
In most case copying database, Dev to Stage or Stage to Dev needed to run `blt setup:toggle-modules` on Acquia cloud.
Because each environment has environment specific module like devel,  shield, views_ui.

Is there any suggestions for disabling devel module after copy database with drag&drop Dev to Stage.
Am I going the wrong way?

**Comment by grasmash** [comment]
@snize You can use an Acquia Cloud hook to run the `blt setup:toggle-modules` command. 

* Create a bash script in hooks/common/post-db-copy
* Make the script executable
* Add code _like_:

```
#!/bin/sh
#
# Cloud Hook: post-db-copy
#
# The post-db-copy hook is run whenever you use the Workflow page to copy a
# database from one environment to another. See ../README.md for
# details.
#
# Usage: post-db-copy site target-env db-name source-env

site="$1"
target_env="$2"
db_name="$3"
source_env="$4"

echo "$site.$target_env: Received copy of database $db_name from $source_env."
blt setup:toggle-module -Denvironment=$target_env
```
