### ISSUE TITLE
It's not possible to disable targets via project.local.yml

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#1052]
In `build.xml`, support for disabling specific targets is added like so:

```
  <!-- Disable targets defined in the disable-targets array in project.yml. -->
  <!-- This must be executed after all targets are defined. -->
  <disabletargets file="${blt.config-files.project}" property="disable-targets"/>
```

The problem is that it's only considering the main project yml file, and not the project.local.yml file.

Could this be solved by modifying the `DisableTargetsTask` to just accept the list of targets, instead of a file that lists them? Then you could do something like this:

```
<if>
  <isset property="disable-targets"/>
  <then>
    <disabletargets targets="${disable-targets}">
  </then>
</if>
```

**Comment by bkosborne** [comment]
I was working on a PR for this but I'm getting stuck.

When using this `<disabletargets targets="${disable-targets}">` in build.xml, the value that gets sent to the target class is literally the string "${disable-targets}" instead of the array of data from the project.yml file.

What do I need to do here to get it to pass the actual value?

**Comment by grasmash** [comment]
Would it work to just add a second line to load from project.local.yml?

```
 <!-- Disable targets defined in the disable-targets array in project.yml. -->
  <!-- This must be executed after all targets are defined. -->
  <disabletargets file="${blt.config-files.project}" property="disable-targets"/>
  <disabletargets file="${blt.config-files.local}" property="disable-targets"/>
```

**Comment by bkosborne** [comment]
Yup, confirmed that works.
