### ISSUE TITLE
Unprocessed replacement in default.local.drushrc.php

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#1057]
After creation of a fresh BLT site, my `default.local.drushrc.php` has the following contents:

```php
<?php
/**
 * #file
 * Local drush configuration for this project.
 */

$options['uri'] = '${project.local.uri}';
```

Since it's in a string literal, I assume that `${project.local.uri}` is a Phing token or something that was supposed to be replaced?

**Comment by grasmash** [comment]
It will not be replaced until you execute "blt setup" or "blt local:setup". default.local.drushrc.php will be copied to local.drushrc.php, at which point it will be replaced. default.local.drushrc.php should never actually be interpreted by PHP.

**Comment by TravisCarden** [comment]
Ah! That makes sense. Thanks.

**Comment by grasmash** [comment]
Maybe we should add a comment to the file to clarify this for others.
