### ISSUE TITLE
Exclude patches from merge?

### ISSUE THREAD

**Issue by timwood** [acquia/blt#1074]
Is it possible to exclude patches from composer merge like how you can exclude dependencies as documented in http://blt.readthedocs.io/en/8.x/readme/updating-blt/#modifying-update-behavior ?

My system information:
* Operating system type: Mac OS
* Operating system version: 10.11.6
* BLT version: 8.6.11

When I run this command:
```
blt update
```

composer.json gets updated with the following patch even though I've added acquia/lightning to  composer-exclude-merge.
```
+            "acquia/lightning": {
+                "New LightningExtension subcontexts do not autoload": "https://www.drupal.org/files/issues/2836258-3-lightning-extension-autoload.patch"
+            }
```

Should patches be added for a project that is excluded and if so, is there any harm in BLT adding them and leaving them there?

Related to #613

**Comment by grasmash** [comment]
I've just merged an update that will use the https://github.com/wikimedia/composer-merge-plugin to manage pulling in default values from BLT's templated composer.json. You should be able to define your own patches array to override BLT's now. You could also optionally disable the merging of the _extra_ section and instead define your own values.
