### ISSUE TITLE
Connects to #1028: Auto-discovery of $site_dir

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1086]
Currently, `$site_dir` must be manually set in each `settings.php` in a multisite codebase:
https://github.com/acquia/blt/blob/8.x/settings/blt.settings.php#L8
https://github.com/acquia/blt/blob/8.x/readme/multisite.md#blt-setup

However, it seems like it would be pretty trivial to automatically determine the site directory name using simple PHP functions, rather than forcing the end user to set this manually.

**Comment by grasmash** [comment]
- [ ] Modify [blt.settings.php](https://github.com/acquia/blt/blob/8.x/settings/blt.settings.php#L8) such that $site_dir automatically refers to the multisite directory for the active site
- [ ] Remove [documentation referring to manual setting](https://github.com/acquia/blt/blob/8.x/readme/multisite.md#blt-setup) of `$site_dir`

Pretty sure you can use [DrupalKernel::getSitePath](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21DrupalKernel.php/function/DrupalKernel%3A%3AgetSitePath/8.3.x) for this.
