### ISSUE TITLE
Create's output 'next instructions' are out of date

### ISSUE THREAD

**Issue by CashWilliams** [acquia/blt#109]
The initial `./blt.sh create` outputs some instructions which need to be updated. https://github.com/acquia/blt/blob/8.x/build/phing/build.xml#L139 says to run `./blt.sh setup` in the project directory, however the INSTALL.md file has the https://github.com/acquia/blt/blob/8.x/INSTALL.md#modifying-project-files section, and then says to run `./blt.sh local:setup`.

**Comment by CashWilliams** [comment]
I don't feel like that commit is enough to fully address the issue.

There should be some other references around setting up the *AMP stack and double checking that the following pieces of information are still correct:

Local site URL: $options[‘uri’] in docroot/sites/default/local.drushrc.php
Local site DB credentials: $databases in docroot/sites/default/settings/local.settings.php

**Comment by grasmash** [comment]
@CashWilliams how about #126 ?

**Comment by CashWilliams** [comment]
Looks good! Thanks
