### ISSUE TITLE
.travis.yml attempts to run scripts that are not yet installed via composer.

### ISSUE THREAD

**Issue by mariagwyn** [acquia/blt#1094]
My system information:
* ON Travis-ci
* BLT version: 8.6.12
* Re-initialized .travis.yml, it is an entirely unmodified file except for #1090.

When I push branch to travis (https://travis-ci.org/mariagwyn/eemmcdowell/builds/201655490):
```
0.02s$ source $BLT_DIR/scripts/travis/before_install
/home/travis/build.sh: line 59: /home/travis/build/mariagwyn/eemmcdowell/vendor/acquia/blt/scripts/travis/before_install: No such file or directory
The command "source $BLT_DIR/scripts/travis/before_install" failed and exited with 1 during .
```

If I understand the logic of .travis.yml, it runs `before_install` BEFORE building the vendor directory. Vendor files are not installed until the next command, 
`install:
  - source $BLT_DIR/scripts/travis/install
`

The problem is, none of these files actually exist until composer builds acq/blt. So, failure.

**Comment by grasmash** [comment]
@mariagwyn I'm rolling back 8.6.12. Will address in 8.x.
