### ISSUE TITLE
PHPUnit Git tests shouldn't create actual commits

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#11]
Right now the Git tests attempt to create real live Git commits: https://github.com/acquia/bolt/blob/8.x/template/tests/phpunit/GitTest.php

This means that if you run unit tests on a local machine, you're unknowingly left with a contaminated Git history.

I'm not sure I see the value in running these tests at all on a continuous basis in a deployed Bolt installation... they seem more valuable for testing the initial Bolt setup. Assuming we need to keep them, think about using `--dry-run` or some other process to avoid creating permanent commits.

**Comment by grasmash** [comment]
This has been resolved (as best I could) by resetting HEAD after a commit has been made.
