### ISSUE TITLE
Git pre-commit hook is slow

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#1104]
The Git `pre-commit` hooks is *very* slow. I was prepared to tolerate it for ordinary commits, but when I saw that it fires for every commit on a rebase I realized it was unacceptable. Looking at [the file](https://github.com/acquia/blt/blob/8.6.11/scripts/git-hooks/pre-commit) I see we're linting custom Twig files and validating the composer.json file whether or not those files have been changed. We should at least make those steps conditional. Perhaps there's a way to optimize phpcs, as well.

**Comment by grasmash** [comment]
- [ ] Execute `validate:twig` only if `*twig` files are listed in `$LIST`
- [ ] Execute `composer validate` only if `composer.*` files are listed in `$LIST`

**Comment by TravisCarden** [comment]
Yay! Thanks, @grasmash and @malikkotob!
