### ISSUE TITLE
Access to production databases

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1109]
By default, when developers run `local:refresh` BLT pulls a sanitized database from the test environment. This works fairly well, but isn't ideal. Content on stage is more variable than what's on prod, more prone to being broken, and is "ahead" of production in terms of schema and config versions. Problems with schema or configuration changes can be (and have been) masked by pulling dbs from stage rather than prod.

Ideally then, `local:refresh` would pull a sanitized db from prod. The problem is that Acquia Cloud permissions currently require a developer to have SSH access in order to retrieve database dumps. Additionally, there might be situations where prod has especially sensitive content that shouldn't be accessible at all in its raw form.

The solution that I'm currently considering is to spin up a production "clone" environment that I update after every production deploy to run the same code as prod and a sanitized copy of the db. I expect this will work, but it would be nice to have a more standardized / less manual solution.

**Comment by grasmash** [comment]
@danepowell How do you envision BLT solving this problem?

**Comment by danepowell** [comment]
I don't :)

In retrospect, this isn't really a BLT issue. The only way this is possible is if Cloud exposes a dedicated function (with its own permission) for downloading databases from production.
