### ISSUE TITLE
Exclude node_modules from validate:twig

### ISSUE THREAD

**Issue by dreamfony** [acquia/blt#1110]
Some node_modules contain invalid .twig files.
Eg. https://www.screencast.com/t/PD9wgcozJ

twig-lint  has --exclude option that can take regex path.
Maybe it would be good idea to completely exclude linting anything inside node_modules
Im not sure how to target that with regex.

**Comment by aweingarten** [comment]
Related PR: https://github.com/acquia/blt/pull/1143
