### ISSUE TITLE
Add vagrant_ip to Drupal VM config.yml when running 'blt vm'

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1112]
This is a feature request.

Now that a _lot_ of BLT projects are using Drupal VM, I'm noticing that, since we don't set a project-specific IP address in `config.yml`, all the VMs tend to use the default, `192.168.88.88`. This isn't a huge deal if you bring up one VM and halt the other...

But if you (like me) need to work on multiple BLT-built projects with Drupal VM, and you bring up two that use the same IP address, weird things start happening (and it's not immediately apparent that they're weird because of the IP being the same...).

I'd propose we do one of the following:

  1. _At a minimum_, add `vagrant_ip: 192.168.25.8` (258 == 'blt' on a phone ;) and then maybe a comment above saying you should customize the IP for your project.
  2. Use some 1-255 integer randomizing function when converting the `config.yml` template and sticking it in the box directory, so you get `192.168.25.[random_number]` for the IP address.

I'll try to file a PR soon, but I don't have time currently to do this.

**Comment by thom8** [comment]
@geerlingguy perhaps you could install https://github.com/oscar-stack/vagrant-auto_network
during the VM init and not set a static IP?

This seems to work quite well even cross platform.

Another option is Avahi /w DHCP - https://github.com/pwelch/ansible-avahi but it doesn't support windows.

**Comment by geerlingguy** [comment]
I hesitate to add in auto_network since there are a dozen tiny things that can get a little flakey using it (e.g. some other assumptions/generated things like aliases, console aliases, and anything else that isn't always done or possible using the hostname).

Additionally, auto_network would have to be another manually-installed option.

I think just adding the IP for now might be best. Then randomizing (1-255) the last part of the address.

I definitely wouldn't go down the Avahi route by default, though. Too many caveats there.

**Comment by geerlingguy** [comment]
See: https://github.com/acquia/blt/pull/1130
