### ISSUE TITLE
Add beetbox support

### ISSUE THREAD

**Issue by thom8** [acquia/blt#1128]
Wanted to start an issue before any PR but would you consider adding  [`beetbox`](https://packagist.org/packages/beet/box) as a secondary option for VM.

This could be added as a option `vm:bb:init` where DVM is the default vm.

The project was originally started to replicate an Acquia environment and is currently pinned to PHP 5.6 / ubuntu 14.04.

It makes use of the same ansible roles as DVM however is all pre-provisioned so the build/rebuild time is greatly reduced.

Plus leveraging linked clones the per project size is much smaller as each instance only has a differential disk of the base box.

We can also manage a blt profile from within the project by adding a profile - for example https://github.com/thom8/beetbox/blob/blt_profile/provisioning/ansible/config/profiles/acquia/blt.config.yml

**Comment by grasmash** [comment]
@thom8 are you interested in pursuing this further? I'm willing to merge the feature, but it needs documentation and testing. If not, I'd like to close the issue.

**Comment by grasmash** [comment]
Closing this and #1133 due to inactivity. I'd be happy to merge the feature, but it will require some documentation and automated testing.
