### ISSUE TITLE
Draft BLT page for docs.acquia.com

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#1131]

**Comment by mariagwyn** [comment]
@grasmash: ideally, this should be done by the end of Q1. Any updates or progress?

**Comment by grasmash** [comment]
LOL, I thought you were working on it!

**Comment by mariagwyn** [comment]
Nope, this was all you.

**Comment by danepowell** [comment]
In #2312, @lcatlett mentions that after this docs page is created, we should update https://docs.acquia.com/lightning/install to reference it and BLT as the preferred install method for Lightning.

**Comment by mikemadison13** [comment]
drafting in progress, starting to share with some people for feedback.

**Comment by mikemadison13** [comment]
closing this as other tickets have been opened for moving this forward.
