### ISSUE TITLE
Adjust BLT's Config Split workflow for new Config Filter approach

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1138]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.3
* BLT version: 8.6.14

Feature request:

It looks like [Config Split](https://www.drupal.org/project/config_split) has been slightly rearchitected to depend on the new [Config Filter](https://www.drupal.org/project/config_filter) module. See this post: [Introducing Config Filter](http://nuvole.org/blog/2017/feb/27/introducing-config-filter).

Because the way this swaps out configuration backends is a bit more seamless, the core Drush commands (at least as of 8.1.10—we might need to make sure we get that version or later) `drush cim` and `drush cex` can still be used (instead of the Config Split commands `csex` and `csim` (yay for not having to sometimes run `drush cc drush` to pick up the extra commands after a `local:refresh`!).

I'm still getting around to testing the update path (and will document it here), but it seems we can simplify the overrides that were added earlier to support the Config Split workflow.

**Comment by geerlingguy** [comment]
Linking: https://github.com/acquia/blt/pull/1102

**Comment by danepowell** [comment]
I'm going to try to review this and the corresponding PR tomorrow. Thanks @geerlingguy !

**Comment by grasmash** [comment]
Addressed in #1102.
