### ISSUE TITLE
Deploy updates not applied to multisites

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1141]
As part of #1092, I thought we had `deploy:update` running on multisite installs on ACE, but this turned out to be something of a red herring. Using the `@sites` alias was a good start, but because we also specify drush.uri (https://github.com/acquia/blt/blob/8.x/phing/build.yml#L73), updates only  applied to the default site. We need to remove the `drush.uri` property for this to work.

**Comment by bobbygryzynger** [comment]
@danepowell - just throwing this out there. Would it suffice to override `drush.uri` during `update:deploy`:
```xml
<property name="drush.uri" value=""/>
```

**Comment by danepowell** [comment]
Yeah actually it might be that simple. I'll open a PR. Thanks!

**Comment by grasmash** [comment]
Fixed in #1146
