### ISSUE TITLE
Running `blt vm` without input from user

### ISSUE THREAD

**Issue by chrowe** [acquia/blt#1145]
When I run this command:
```
blt vm
```

I get the following output:
```
...
Would you like to boot your VM now? [y]
...
Password:
...
```

And I expected this to happen:
`NULL`

It would be nice if there was a way to answer these questions when the script first starts.
1. Ask for the user's password in the beginning or run with sudo?
2. Accept a `--yes` flag to automatically answer any questions with yes.

**Comment by grasmash** [comment]
@chrowe you can run `blt vm -Dvm.boot='false'` to remove the user interaction requirement.
