### ISSUE TITLE
Automated tag deployments on Travis CI fail with 'src refspec matches more than one`

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1150]
```
$ blt version
blt > version:
     [echo] BLT version is 8.6.14
```

When I create a tag in the source repository, and Travis CI builds that tag, I get the following output and a build failure in Travis CI:

```
     [exec] Executing command: 'git' 'commit' '--quiet' '-m' 'Automated commit by Travis CI for Build 1.5.1'
     [exec] Executing command: cat /home/travis/build/acquia-pso/projectname/blt/.schema_version 2>&1
     [exec] Executing command: composer info acquia/blt --no-ansi 2> /dev/null | grep versions | awk '{print $4}' 2>&1
blt > deploy:tag:
     [exec] Executing command: git tag -a 1.5.1-build -m 'Automated commit by Travis CI for Build 1.5.1'
     [exec] Executing command: cat /home/travis/build/acquia-pso/projectname/blt/.schema_version 2>&1
     [exec] Executing command: composer info acquia/blt --no-ansi 2> /dev/null | grep versions | awk '{print $4}' 2>&1
blt > deploy:push-all:
     [exec] Executing command: cat /home/travis/build/acquia-pso/projectname/blt/.schema_version 2>&1
     [exec] Executing command: composer info acquia/blt --no-ansi 2> /dev/null | grep versions | awk '{print $4}' 2>&1
blt > deploy:push-remote:
     [exec] Executing command: git push b2897977cba189c4e34f1e5699d47dfb 1.5.1-build 2>&1
     [exec] error: src refspec 1.5.1-build matches more than one.
     [exec] error: failed to push some refs to 'projectname@svn-12345.prod.hosting.acquia.com:projectname.git'
```

Normal PR merge builds succeed in pushing artifacts to the `master-build` branch.

**Comment by geerlingguy** [comment]
It looks like during the `git:pull` operation, a branch is created with the exact same name:

```
blt > deploy:remote:pull:
     [exec] Executing command: git fetch b2897977cba189c4e34f1e5699d47dfb 1.5.1-build
Warning: Permanently added the RSA host key for IP address '54.81.8.61' to the list of known hosts.
fatal: Couldn't find remote ref 1.5.1-build
fatal: The remote end hung up unexpectedly
     [exec] Executing command: git checkout -b 1.5.1-build
Switched to a new branch '1.5.1-build'
merge: b2897977cba189c4e34f1e5699d47dfb/1.5.1-build - not something we can merge
```

And thus the git error message during `deploy:push-remote` makes sense.

**Comment by grasmash** [comment]
So, we need default names for:
1. The branch source repo
1. The tag on the source repo
1. The branch used for building the artifact
1. The tag for the artifact

I'd suggest:
1. master
1. 1.0.0
1. 1.0.0-build-branch
1. 1.0.0-build

Currently 3 and 4 are conflated.

@geerlingguy thoughts?

**Comment by geerlingguy** [comment]
@grasmash - I like:

Source: `1.0.0`
Build branch: `1.0.0-build-branch`
Build tag: `1.0.0-build`

**Comment by danepowell** [comment]
I guess I'm not clear on how you ended up with a branch and tag that have the same names.

We use the following naming convention to avoid any chance of this:
* Code gets merged to `master` in Github, and deployed to `master-build`.
* We cut release branches from `master` and name them like `release-3.1.x` (that would be Sprint 3, release 1, with the 'x' indicating the possibility of a hotfix)
* We tag releases on those branches (in this example, `3.1.0` would be the initial  release. If we have to hotfix it, the hotfix would be `3.1.1`).

We've also tweaked the Travis deploy step to support this:
`-Ddeploy.branch="release-$(echo $TRAVIS_TAG | cut -d. -f1).$(echo $TRAVIS_TAG | cut -d. -f2).x"`

I'm open to other standards, but note that this is part of our technical architecture document template so we'd want to coordinate on a change.

**Comment by geerlingguy** [comment]
@danepowell - In the case of the two projects I'm on, for releases we just tag master, and the tagging standard isn't really the same between projects as far as I can tell... sometimes it's `[major initiative].[sprint].[release-number]`, other times it's [sprint].[release].[whatever-someone-decides]`...

But anyways, the tags for many projects are cut straight from master (then for hotfixes, a branch is created from that tag).

**Comment by grasmash** [comment]
Maybe the right answer is to simply never push the "build branch" when a tag is being cut.

**Comment by geerlingguy** [comment]
Looks great!

**Comment by danepowell** [comment]
I was wary of this at first, but I guess as long as we can continue to have tagged release branches on the source repo that's okay. Ideally the build repo is just a place to push code snapshots, and not someplace you actually do development, so you _shouldn't_ need branches...

**Comment by grasmash** [comment]
@geerlingguy Actually, this doesn't work because on the travis worker we're still using the same name for the branch and tag. So, we need a new naming convention.

**Comment by grasmash** [comment]
Submitted #1171
