### ISSUE TITLE
Add ability to save screenshot and/or dump of html for failed behat tests.

### ISSUE THREAD

**Issue by lahoosascoots** [acquia/blt#1152]
This would help to understand why a test is failing as behat may be seeing things _slightly_ different compared to your browser.

See:
https://github.com/Behat/Behat/issues/649
https://blogs.library.ucsf.edu/ckm/2014/05/14/see-your-failures-taking-screenshots-with-phantomjs-running-behat-tests/

**Comment by geerlingguy** [comment]
This is _crazy_ helpful.

Here's how I did it (kinda messy, but hey, it works!): You need to add a few things to your `FeatureContext` (in `tests/behat/features/bootstrap/Drupal/FeatureContext.php`):

```php
# Alongside the other `use` statements.
use Behat\Behat\Hook\Scope\AfterStepScope;

...

class FeatureContext extends RawDrupalContext implements SnippetAcceptingContext {

  ...

  /**
   * @AfterStep
   */
  public function takeScreenshotAfterFailedStep(AfterStepScope $scope) {
    if ($scope->getTestResult()->getResultCode() == 99) {
      $this->takeScreenshot();
    }
  }

  /**
   * Store a screenshot.
   */
  private function takeScreenshot() {
    $screenshot = $this->getSession()->getDriver()->getScreenshot();
    $path = '/var/www/projectname/' . date('d-m-y') . '-' . uniqid() . '.png';

    file_put_contents($path, $screenshot);
    print 'Screenshot at: ' . $path;
  }

  ...

}
```

**Comment by geerlingguy** [comment]
Another option: https://packagist.org/packages/bex/behat-screenshot — that's just a Behat Extension that doesn't require any additional FeatureContext code.

**Comment by geerlingguy** [comment]
PR posted ^^

**Comment by grasmash** [comment]
@geerlingguy Thanks for the contribution! Any change you can add some docs to http://blt.readthedocs.io/en/8.x/readme/testing/#configuration ?

**Comment by geerlingguy** [comment]
@grasmash - Will do—I'll add some screenshot config docs.

**Comment by geerlingguy** [comment]
PR https://github.com/acquia/blt/pull/1164
