### ISSUE TITLE
Add ability to selectively run Behat scenarios and/or Feature files

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1153]
It would be awesome if I had some easy way to tell BLT to just run one Feature file or Scenario (instead of either running everything, or using the `behat` CLI tool directly).

See:

  - http://docs.behat.org/en/v2.5/guides/6.cli.html
  - http://stackoverflow.com/a/36195269

Or is there a way to do something like this using tags already?

**Comment by grasmash** [comment]
@geerlingguy see http://blt.readthedocs.io/en/8.x/readme/testing/#executing-tests :

To execute a single feature (with Phing):

    blt tests:behat -Dbehat.paths=${PWD}/tests/behat/features/Examples.feature

To execute a single scenario (with Phing):

    blt tests:behat -Dbehat.paths=${PWD}/tests/behat/features/Examples.feature:4

Where "4" is the line number of the scenario in the feature file.

To execute the tests directly (without Phing) see the following examples:

* `./vendor/bin/behat -c tests/behat/local.yml tests/behat/features/Examples.feature -p local`
* `./vendor/bin/phpunit tests/phpunit/BLTTest.php`

**Comment by geerlingguy** [comment]
Ah, thanks!
