### ISSUE TITLE
Drush aliases file not correctly generated on blt vm if nuked before

### ISSUE THREAD

**Issue by mirsoftacquia** [acquia/blt#1155]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.3
* BLT version: 8.6.14

How to reproduce:

1. Create a new project from the scratch, follow these instructions up to point 3: http://blt.readthedocs.io/en/8.x/readme/creating-new-project/
2  Execute `blt vm` to initialize Drupal VM. 
3. Destroy vm using `blt vm:nuke`
4. Initialize vm again using `blt vm`
5. After the process finished, open the file drush/site-aliases/aliases.drush.rc

The file `drush/site-aliases/aliases.drush.rc` is missing `<?php` at the beginning. This results in an interpretation as a plain text file later which results in failed build process with a couple of confusing errors e.g. on `blt local:setup`.

It happens because the file `drush/site-aliases/aliases.drush.rc` is deleted completely during `blt vm:nuke` process and only a snippet with aliases is appended during a next `blt vm` execution. 

Expected behavior would be that this file is not deleted on `blt vm:nuke` - it should be replaced by a previous (or default) version of aliases.drush.rc.

**Comment by chrowe** [comment]
Not sure if this is what was happening for me but I definitely have run into an issue where the alias no longer shows up when running `drush sa` and there was not a clear way to generate it again.

**Comment by grasmash** [comment]
I think the symptom would be an incorrect alias rather than a missing alias. @chrowe I'd check your drush version and ensure that you're running the command from the docroot.
