### ISSUE TITLE
Speed up builds by conditionally "returning early"?

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#1159]
One of the biggest drawbacks to running builds against pull requests is the time it adds to changes that don't actually need to be tested, like documentation edits, for example. I wonder if we could introduce some kind of white list concept whereby we "return early" if only files matching a given path pattern are changed. For example, if a pull requests only contains changes to Markdown files, there's probably no need to run automated tests or even generate a new build artifact. On most teams, that would be an instant savings of 10-30 minutes. Seems like we could probably come up with some sensible defaults for a white list easily enough to make for pretty good savings by default for most projects.

**Comment by grasmash** [comment]
Sounds like a great idea!

**Comment by geerlingguy** [comment]
One quick note—for things like docs changes et all, you can add `[ci skip]` or `[skip ci]` to the commit message itself. This isn't automatic (the developer needs to know to do this), but it does save a ton of time for docs-only or other changes that don't need to be run through the BLT gauntlet.

See: https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build

**Comment by grasmash** [comment]
@TravisCarden does using [ci skip] sound like a reasonable solution?

**Comment by TravisCarden** [comment]
@grasmash, I think it's a good tool to have at our disposal, but I don't think it renders the feature suggestion less valuable. I won't be encouraging my developers to selectively bypass testing because I think that invites accidents and abuse. But an agreed-upon, deterministic rule for when tests can be safely bypasses is different. "Doesn't require incidental judgment" is a good CI attribute. Given good defaults or a well-chosen project standard, people don't even have to know about it to benefit from it, either, which is also good. Honestly, I don't expect to have time to contribute the feature myself for a while, but I think it's a feature worth having, and therefore worth remembering. My two cents. 😃

**Comment by grasmash** [comment]
Finding inspiration here: https://github.com/facebook/react/issues/1768

**Comment by TravisCarden** [comment]
Update: I realized today that if you cut a release from a commit with `[skip ci]` in the commit message, BLT won't generate a build artifact. @grasmash, I haven't looked too closely at your solution here (thanks for the work, by the way!), so I just wanted to surface this to make sure your approach isn't similarly affected.
