### ISSUE TITLE
BLT incorrectly sets file_private_path for Site Factory

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#1160]
My system information:
* Operating system type: ubuntu
* Operating system version: precise
* BLT version: 8.6.14

When BLT sets the private-files directory, it is setting this in a non-standard location. From [the settings.php include](https://github.com/acquia/blt/blob/8.x/settings/filesystem.settings.php#L13):

```
if ($is_acsf) {
  $settings['file_public_path'] = "sites/g/files/$acsf_db_name/files";
  $settings['file_private_path'] = "/mnt/gfs/$ah_group.$ah_env/files-private/$acsf_db_name";
}
```

From talking with Site Factory engineering, the location should actually be:

```
$settings['file_private_path'] = "/mnt/files/$ah_group.$ah_env/sites/g/files-private/$acsf_db_name";
```

So the fix is complex, as it will involve:

* changing the variable
* migrating the files to the new location

Original issue (from git blame) https://github.com/acquia/blt/issues/211

**Comment by jstanton617** [comment]
@seanhamlin - I used this to do the migration when I had to do it before

```
#!/bin/bash

for site in `ls /mnt/gfs/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/files-private`
do
  mkdir -p /mnt/files/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/sites/g/files-private/$site
  rsync -avh /mnt/gfs/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/files-private/$site/* /mnt/files/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/sites/g/files-private/$site/
done;
```
