### ISSUE TITLE
BLT should never alter settings.php and should *only* use pre-settings-php hooks

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#1180]
My system information:
* Operating system type: ubuntu
* Operating system version: precise
* BLT version: 8.6.15

I noticed that BLT likes to inject it's settings at the very end of the `docroot/sites/g/settings.php` file:

```
$ tail docroot/sites/g/settings.php

// Include custom settings.php code from factory-hooks/post-settings-php.
if (function_exists('acsf_hooks_includes')) {
  foreach (acsf_hooks_includes('post-settings-php') as $post_hook) {
    include $post_hook;
  }
}
require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";
```

I believe it would be nicer if BLT was to stick to using just the pre-settings-php hook. Unsure why modifying this file was done, but it clearly is in error. Site Factory checks the integrity of these files, and will fail if modified.

**Comment by grasmash** [comment]
@seanhamlin my understanding is that ACSF no longer restricts modifications to settings.php. I worked with @nikgregory to effect this change. Are you encountering an error? If so, what version of the ACSF module are you using?

**Comment by grasmash** [comment]
Also, you're free to use the include however you'd like. If you don't want it, just comment it out.

**Comment by seanhamlin** [comment]
From talking with Site Factory engineering, the file `docroot/sites/g/settings.php` is wholey owned by ACSF, any modifications will result in Site Factory being unhappy. Modifications to `docroot/sites/default/settings.php` are fine though.

**Comment by seanhamlin** [comment]
Thanks @grasmash !
