### ISSUE TITLE
Should salt.txt be committed?

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1191]
Should the generated salt.txt file be committed in a BLT controlled project? Just a general question, I couldn't find much information on this and I feel like it has been generated a few times as I have been trying different commands (nuke, setup, refresh) on a fresh build before I really get started.

**Comment by danepowell** [comment]
Yes, best practice would be to commit salt.txt. This is functionally equivalent to setting `$settings['hash_salt']` in settings.php, which would ordinarily be committed. But setting it via a file outside the docroot (i.e. salt.txt) is more secure.

**Comment by grahl** [comment]
Hi there

Sorry for reopening a closed topic. Could you please elaborate a little bit more on the reasoning why you would consider this to be a best practice?

I understand that the placement in salt.txt outside the docroot is more secure but I was under the impression (and most other recommendations regarding settings.php seem to confirm this), that one should not commit secrets such as credentials, keys and salts to the repository.

**Comment by geerlingguy** [comment]
Follow-up question—if you were considering open sourcing a codebase built with BLT, wouldn't it be best practice to _not_ commit `salt.txt`?

**Comment by thom8** [comment]
I guess, if you don't have a canonical database you don't need a `salt.txt` in the repo but it'll still need to be created before install.

**Comment by geerlingguy** [comment]
Someone had mentioned that if you don't commit `salt.txt`, I _think_ BLT will generate it when it does all it's deploy steps?

**Comment by malikkotob** [comment]
@geerlingguy, @thom8, yeah, I went ahead and deleted `salt.txt` and added it to `.gitignore`. BLT generated a new `salt.txt` when I ran `blt deploy`. It's not committed to the repo (good), and is present in the build artifact (also good).

**Comment by wayne-weibel** [comment]
BLT does regenerate `salt.txt`, but I hit an issue trying to do some local dev.   If salt.txt is not committed (or generated) before doing a cache-rebuild, it will fail - BLT overrides the `$settings['hash_salt']` to point at the file.  

So, I would say it is a coin flip; CI/CD should not need salt.txt to exist (since you do a BLT build), but shared dev would benefit from it being committed.
