### ISSUE TITLE
Config Split upgrade to Beta 4 could be tricky

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1199]
When I run this command:
```
blt local:refresh
```

I get the following output:
```
blt > local:update:
blt > setup:update:
The following directory will be used to merge config into the active storage:
../config/local
Import the configuration? (y/n): y
exception 'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException' with message 'You have      [error]
requested a non-existent service "config_split.cli".' in
/var/www/project/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php:157
Stack trace:
#0 /var/www/project/docroot/core/lib/Drupal.php(158):
Drupal\Component\DependencyInjection\Container->get('config_split.cl...')
#1 /var/www/project/docroot/modules/contrib/config_split/config_split.drush.inc(123):
Drupal::service('config_split.cl...')
#2 [internal function]: drush_config_split_import('local')
#3 /var/www/project/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_config_sp...',
...
```

Basically, I have a site that's been using Config Split to manage configuration between environments. I'm trying to upgrade BLT, and as part of the final step (`composer update`), Config Split is upgraded to the `beta4` release, which includes a new dependency on Config Filter.

This is all well and good, but it seems there's an issue with Drush 8.1.10 and Config Split, possibly (or maybe something else, not sure yet). We might need to update the docs and code slightly, too, to support the new structure. I'm still investigating, will keep posting notes here.

**Comment by geerlingguy** [comment]
Ah, looks like a bug in the module (but it says it was fixed...): [Dependancy on non-existent service](https://www.drupal.org/node/2859628).

**Comment by geerlingguy** [comment]
Locally, after I run `blt local:refresh` and let it fail, if I then run:

```
drush @beagov.local en -y config_filter
drush @beagov.local csim -y local
```

...then it works. So it seems it could be an order of operations issue—I did enable the module and stick it in my core config... but it looks like I _might_ need to make sure `updb` is run prior to `csim`?

**Comment by geerlingguy** [comment]
It looks like that was the issue—I changed the order in my overridden `setup:update` command so it runs `updb` first, then `config-split-import`. This seems to work okay.

**Comment by geerlingguy** [comment]
This definitely impacts https://github.com/acquia/blt/pull/1102, though—Config Split now uses commands like `csim [split]` instead of `csim --split=[split]`.

**Comment by grasmash** [comment]
Thanks @geerlingguy. Will take this into consideration for #1102.

**Comment by geerlingguy** [comment]
I also ran into [Split no longer merges from default](https://www.drupal.org/node/2861266).

**Comment by arknoll** [comment]
@geerlingguy @grasmash See a PR where I got the new version of config_split/config_filter working with Canary. Specifically:

https://github.com/acquia-pso/canary/pull/25/files#diff-e56cbd5daab22087fd0e4849dc38055dR14

https://github.com/acquia-pso/canary/pull/25/files#diff-2737999ec8b2368b193b40b46c5679c2R758
