### ISSUE TITLE
PHPUnit Drush test should use the actual local URL

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#12]
DrushTest currently looks for a hardcoded local URL, 127.0.0.1:8888: https://github.com/acquia/bolt/blob/8.x/template/tests/phpunit/DrushTest.php

Seems like it should be looking for the project-specific URL or something else entirely. This fails on our project.

**Comment by geerlingguy** [comment]
Agreed; this will break when using Drupal VM too.

**Comment by ba66e77** [comment]
The behat uses a local url variable to (I believe) identify the url that should be used.  Seems like that should also work for the Drush test.

**Comment by danepowell** [comment]
I'm pretty sure this was fixed by #122, if not please re-open.
