### ISSUE TITLE
Intermittent Behat failures with PhantomJS

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1201]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.3
* BLT version: 8.6.15

When I run this command:

* Run CI tests on Travis CI (including `tests:behat`).

I get the following output:

```
[...]
blt > tests:phantomjs:kill:
     [echo] Killing any PhantomJS processes that are already running.
 [property] Loading /home/travis/build/acquia-pso/project/blt/project.yml
 [property] Loading /home/travis/build/acquia-pso/project/blt/project.local.yml
blt > tests:phantomjs:configure:
blt > tests:phantomjs:launch:
     [echo] Launching PhantomJS GhostDriver.
 [property] Loading /home/travis/build/acquia-pso/project/blt/project.yml
 [property] Loading /home/travis/build/acquia-pso/project/blt/project.local.yml
blt > tests:phantomjs:kill:
     [echo] Killing any PhantomJS processes that are already running.
     [echo] Waiting 10 seconds for PhantomJS (http://127.0.0.1:4444) to become available.
Possible malformed URL: http://127.0.0.1:4444/wd/hub
 [property] Loading /home/travis/build/acquia-pso/project/blt/project.yml
 [property] Loading /home/travis/build/acquia-pso/project/blt/project.local.yml
blt > tests:behat:execute:
     [exec] /home/travis/build/acquia-pso/project/tests/behat/features/Examples.feature
[...]
@lightning @api @workflow
Feature: Scheduled updates to content
  @javascript
  Scenario: Publishing a node that is scheduled to be published in the past # features/Scheduler.feature:5

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

It used to be one in maybe 3 or 4 builds, but both on the legacy infrastructure and the Travis CI containerized infrastructure, I get a test failure during Selenium tests maybe 50% of the time or more. Annoying enough that I've finally thought it appropriate to post an issue for this, especially since Chromedriver has been painful on its own merits (see #1126).

Every single time there's this timeout/hang, it's on a Scenario that has the `@javascript` tag, which means PhantomJS is getting invoked, but for some reason it's just hanging.

_Most_ of the time (but definitely not always), it happens on the first time a `@javascript`-tagged scenario is run. The rest of the time it's on a later `@javascript` scenario.

At this point, only about 1/4 builds actually succeeds. So I'm babysitting all our builds on Travis CI, and I've gone from immediately assigning tickets to QA once I've merged them (since I was reasonably confident the build would pass within ~10 minutes and the code would be on Acquia Cloud), to now holding onto tickets for a long period of time until I can finally get a build to succeed.

It's enough to make me strongly consider disabling tests for now—and that's a _very scary_ thought indeed. Once you disable automated tests, that's usually the end for any semblance of testing on a project. I really don't want to push that button, but it's seriously impeding velocity on this particular project.

### Notes

  * I notice that phantomjs is actually killed _twice_ by the `tests:behat` script—once in the general test setup, then again inside `tests:phantomjs:launch`. Maybe Phantom is just really angry that we just killed it twice, so it refuses to work reliably?
  * I've tried switching between the legacy infrastructure (`sudo: required`) and the container based infrastructure (`sudo: false`), and neither seems to be better than the other...).
  * PhantomJS tests (`blt tests:behat`) run perfectly, locally, every time I try. I haven't ever experienced a hang like I have on Travis.
  * Could we get things set up so we could run PhantomJS locally and Chromedriver on CI? That would just be punting the nuclear bomb (💥) of a Chrome version upgrade down the road a bit (again, see #1126), but it would at least give me breathing room.

**Comment by geerlingguy** [comment]
Strange... if I set things back to use Chromedriver, I'm now getting the following, and PhantomJS is still being used:

```
  @javascript
  Scenario: Ensure that the WYSIWYG editor is present.         # features/Content.feature:20
[INFO  - 2017-03-16T03:25:46.148Z] GhostDriver - Main - running on port 9700
[INFO  - 2017-03-16T03:25:46.513Z] Session [3e9c9cc0-09f8-11e7-a2dc-1b057a957093] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2017-03-16T03:25:46.514Z] Session [3e9c9cc0-09f8-11e7-a2dc-1b057a957093] - page.customHeaders:  - {}
[INFO  - 2017-03-16T03:25:46.514Z] Session [3e9c9cc0-09f8-11e7-a2dc-1b057a957093] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2017-03-16T03:25:46.515Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 3e9c9cc0-09f8-11e7-a2dc-1b057a957093
```

(And it's at this point where the job just stops.)

**Comment by geerlingguy** [comment]
And it just kept hanging with:

```
[INFO  - 2017-03-16T03:30:46.149Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2017-03-16T03:35:46.151Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2017-03-16T03:40:46.153Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2017-03-16T03:45:46.155Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
[INFO  - 2017-03-16T03:50:46.155Z] SessionManagerReqHand - _cleanupWindowlessSessions - Asynchronous Sessions clean-up phase starting NOW
```

**Comment by geerlingguy** [comment]
Overriding `tests:phantomjs:launch` and killing phantomjs only once didn't seem to help.

**Comment by geerlingguy** [comment]
The following did work to set Chromedriver on Travis CI and PhantomJS locally:

In `blt/project.yml`:

```yaml
```

In `blt/local.project.yml`:

```yaml
```

Note, however, that during each of the `@javascript` tests, I got the following AJAX error—maybe this is causing the main issue? Missing JS file or something?

```
Drupal\DrupalExtension\Context\MinkContext::assertAtPath()
[ERROR - 2017-03-16T04:22:50.760Z] Session [1d350060-0a00-11e7-938a-6792394fe387] - page.onError - msg: AjaxError: 
An AJAX HTTP request terminated abnormally.
Debugging information follows.
Path: /quickedit/attachments
StatusText: error
ResponseText: 
ReadyState: 0
  :262 in error
[ERROR - 2017-03-16T04:22:50.760Z] Session [1d350060-0a00-11e7-938a-6792394fe387] - page.onError - stack:
  error (http://127.0.0.1:8888/core/misc/ajax.js?v=8.2.7:965)
  complete (http://127.0.0.1:8888/core/misc/ajax.js?v=8.2.7:510)
  i (http://127.0.0.1:8888/core/assets/vendor/jquery/jquery.min.js?v=2.2.3:2)
  fireWith (http://127.0.0.1:8888/core/assets/vendor/jquery/jquery.min.js?v=2.2.3:2)
  z (http://127.0.0.1:8888/core/assets/vendor/jquery/jquery.min.js?v=2.2.3:4)
  (anonymous function) (http://127.0.0.1:8888/core/assets/vendor/jquery/jquery.min.js?v=2.2.3:4)
  dispatchEvent (:0)
  U (phantomjs://webpage.evaluate():119)
  $ (phantomjs://webpage.evaluate():108)
  $ (phantomjs://webpage.evaluate():101)
  gh (phantomjs://webpage.evaluate():141)
  sh (phantomjs://webpage.evaluate():152)
  (anonymous function) (phantomjs://webpage.evaluate():152)
  (anonymous function) (phantomjs://webpage.evaluate():152)
  (anonymous function) (phantomjs://webpage.evaluate():153)
  :262 in error
```

The following are Drupal 7 Quick Edit issues, but I wonder if the Drupal 8 version in core is hitting one of them?

  - [AJAX error when nonexistent editor passed to edit/attachments (and: multiple in-place editor attachment requests)](https://www.drupal.org/node/2191281)
  - [Quick Edit making redundent AJAX calls on every page](https://www.drupal.org/node/2333067)

...then again, maybe it's some JS error caused by our theme. But it's quite suspicious, considering the JS tests are the only ones that fail consistently, and they show strange behavior on both Chromedriver and PhantomJS...

**Comment by geerlingguy** [comment]
I'm getting this on Pipelines builds now, too:

```
blt > setup:behat:
     [copy] example.local.yml omitted, is up to date
blt > test:behat:check:
 [property] Loading /mnt/tmp/local.prod/source/tests/behat/local.yml
     [echo] 
     [echo] One or more values in tests/behat/local.yml reference file paths that do not exist on this system.
     [echo] This is typically related to using a virtual machine.
     [echo] 
     [echo] Try one of the following solution:
     [echo] 1) Execute the tests on the correct system.
     [echo] 2) Correct the value(s).
     [echo] 3) Remove tests/behat/local.yml so that it can be regenerated automatically from example.local.yml.
     [echo] 
     [echo] Values are:
     [echo] drupal_root: /Users/jeff.geerling/Sites/acquia/eejgeerling/docroot"
     [echo] features:    /Users/jeff.geerling/Sites/acquia/eejgeerling"
     [echo] bootstrap:   /Users/jeff.geerling/Sites/acquia/eejgeerling/tests/behat/features/bootstrap
     [echo] 

Do you want to re-generate Behat configuration? [y/n] [y] ?     [delete] Deleting: /mnt/tmp/local.prod/source/tests/behat/local.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.local.yml
blt > setup:behat:
     [copy] Copying 1 file to /mnt/tmp/local.prod/source/tests/behat
     [copy] From /mnt/tmp/local.prod/source/tests/behat/example.local.yml to /mnt/tmp/local.prod/source/tests/behat/local.yml
     [echo] Executing Behat tests with configuratoin:
     [echo] drupal_root: /Users/jeff.geerling/Sites/acquia/eejgeerling/docroot"
     [echo] base_url: http://local.eejgeerling.com"
blt > tests:run-server:
     [echo] Using 'drush runserver' for tests.
     [echo] Running server at http://127.0.0.1:8888
 [property] Loading /mnt/tmp/local.prod/source/blt/project.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.local.yml
blt > tests:run-server:kill:
     [echo] Waiting 10 seconds for http://127.0.0.1:8888 to become available.
Possible malformed URL: http://127.0.0.1:8888
blt > tests:behat:
 [property] Loading /mnt/tmp/local.prod/source/blt/project.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.local.yml
blt > tests:selenium:kill:
     [echo] Killing any selenium processes that are already running.
sh: 1: lsof: not found
 [property] Loading /mnt/tmp/local.prod/source/blt/project.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.local.yml
blt > tests:phantomjs:kill:
     [echo] Killing any PhantomJS processes that are already running.
sh: 1: lsof: not found
 [property] Loading /mnt/tmp/local.prod/source/blt/project.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.local.yml
blt > tests:phantomjs:configure:
> rm -rf vendor/bin/phantomjs
> PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (2.1.1): Downloading (100%)
blt > tests:phantomjs:launch:
     [echo] Launching PhantomJS GhostDriver.
 [property] Loading /mnt/tmp/local.prod/source/blt/project.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.local.yml
blt > tests:phantomjs:kill:
     [echo] Killing any PhantomJS processes that are already running.
sh: 1: lsof: not found
     [echo] Waiting 10 seconds for PhantomJS (http://127.0.0.1:4444) to become available.
Possible malformed URL: http://127.0.0.1:4444/wd/hub
 [property] Loading /mnt/tmp/local.prod/source/blt/project.yml
 [property] Loading /mnt/tmp/local.prod/source/blt/project.local.yml
blt > tests:behat:execute:
     [exec] /mnt/tmp/local.prod/source/tests/behat/features/Examples.feature
    [behat] Running '/mnt/tmp/local.prod/source/vendor/bin/behat /mnt/tmp/local.prod/source/tests/behat --config=/mnt/tmp/local.prod/source/tests/behat/local.yml --tags="~experimental" --format=pretty --format=junit  --out=std --out=/mnt/tmp/local.prod/source/reports  --profile=local --strict --verbose --colors --stop-on-failure'
@example
Feature: Web drivers
  In order to verify that web drivers are working
  As a user
  I should be able to load the homepage
  With and without Javascript

  @javascript
  Scenario: Load a page with Javascript # features/Examples.feature:9
```

**Comment by cosmicdreams** [comment]
Hi @geerlingguy :  You know I tend to follow Chrome's latest developments, well I think that's paid off in relation to this issue.

1. Headless Chrome is going to be a thing in about 6 - 12 weeks: 
https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

2. Some signals point to Phantomjs shutting down as a result & it looks like Headless Chrome will pick up where phantomjs drops off.
https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE

**Comment by cosmicdreams** [comment]
Technically Headless Chrome is a thing now, if you're using the dev version of Chrome.

**Comment by grasmash** [comment]
I would definitely like to switch to use headless Chrome. Has it been tested with Behat by any other projects?

**Comment by geerlingguy** [comment]
I haven't tested it yet—currently it would require installing a newer release of Chrome than is available in system packages, meaning it would require some extra/custom work to try to install it in Drupal VM and/or Travis CI. And then on top of that, I'm not even sure if it would be installable at this point inside Pipelines...

Here's some more documentation: https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md

To my knowledge, I haven't seen anyone start using the official headless versions with any Drupal / Behat projects.

**Comment by geerlingguy** [comment]
See related: [Running Selenium with the new Headless Chrome](https://intoli.com/blog/running-selenium-with-headless-chrome/)

**Comment by grasmash** [comment]
Basically, this is a shortcoming of PhantomJS that can't be addressed in BLT. As a solution, I have added headless chrome support to BLT. You can now use `behat.web-driver: chrome` rather than Selenium or PhantomJS. I'm sure this will come with its own issues, but we need to move away from Phantom now that its maintainer is stepping down.

See #1705
