### ISSUE TITLE
Projects can't define post_provision_tasks_dir

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1215]
When creating a `box/config.yml` file, if a project wishes to define a [`post_provision_tasks_dir`](https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/config.yml#L77) they will overwrite BLT's Drupal VM post-provisioning tasks. 

I'm not sure if this is a BLT issue specifically (paging @geerlingguy), but it does force projects to choose between retaining BLT's customizations (and not being allowed their own customizations) or foregoing BLT's customizations in order to define their own.

**Comment by grasmash** [comment]
I think you can just overwrite BLT's default dir, and in your custom bash script, just call BLT's bash script in `vendor/acquia/blt/acquia/blt/scripts/drupal-vm/post-provision.sh`.

**Comment by bobbygryzynger** [comment]
It seems like that wouldn't be sufficient, because BLT's [`post-provision.sh`](https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/post-provision.sh) doesn't call or make reference to the post-provisioning `yml`file that BLT ships.

**Comment by grasmash** [comment]
Hm. Maybe we could just move the Pipelines download from https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/post-provision.yml to the post-provision.sh script.
