### ISSUE TITLE
Update acsf-setup.md with subprofile guidance instead of lightning.extend.yml

### ISSUE THREAD

**Issue by vbouchet31** [acquia/blt#1218]
https://github.com/acquia/blt/blob/8.x/readme/acsf-setup.md

https://docs.acquia.com/lightning/subprofile

**Comment by vbouchet31** [comment]
Previous:
- Execute blt acsf:init from the project root.
- Create a custom module in docroot/modules/custom that will be used in lieu of a custom profile.
- Add acsf as a dependency for your custom module.
- If using lightning, create a custom lightning.extend.yml and add it to sites/default
- Deploy to Cloud using blt deploy
- Use ACSF's "update code" feature to push the artifact out to sites.
- When creating a new site, select "Lightning" as the profile.

Suggested new:
- Execute blt acsf:init from the project root.
- Create a custom subprofile as described [here](https://docs.acquia.com/lightning/subprofile).
- Add acsf as a dependency for your custom subprofile.
- Deploy to Cloud using blt deploy
- Use ACSF's "update code" feature to push the artifact out to sites.
- When creating a new site, select your custom subprofile as the profile.

**Comment by vbouchet31** [comment]
Probably need a step to edit the blt/project.yml to use the custom profile instead but it is not specific to ACSF.

**Comment by lcatlett** [comment]
Might want to add to this that code can be deployed via cloud hooks and that the above process will not work for updating existing acsf sites using lightning.

**Comment by grasmash** [comment]
@vbouchet31 Seems like you have a good idea of what needs to be done, could you submit a PR with your suggestions?

**Comment by malikkotob** [comment]
@vbouchet31, @lcatlett, mind taking a look at the PR? https://github.com/acquia/blt/pull/1271

Feel free to leave suggestions/comments
