### ISSUE TITLE
Windows VM provision fails on post-provision.sh script

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1220]
My system information:
* Operating system type: Windows
* Operating system version: 7
* BLT version: 8.6.15

When I run this command:
```
vagrant provision
```

I get the following output:
```
TASK [Run configured post-provision shell scripts.] ****************************
failed: [project] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.sh) => {"changed": true, "failed": true, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.sh", "rc": 127, "stderr": "/usr/bin/env: bash\r: No such file or directory\n", "stdout": "", "stdout_lines": []}
changed: [project] => (item=../../../../box/scripts/npm-setup.sh)
```

And I expected this to happen:

* Provisioning should complete normally.

**Comment by geerlingguy** [comment]
Granted, this is Windows 7... but if you're building the VM within Cmder or PowerShell, I wonder if the same problem might crop up...

Note that in my own shell scripts, where the user's environment customizations might not matter quite as much, I use the following instead of `/usr/bin/env bash`:

```
#!/bin/bash
```

I'm testing whether the blt post provision script works with just that single change.

**Comment by geerlingguy** [comment]
That didn't work, now I'm getting:

```
TASK [Run configured post-provision shell scripts.] ****************************
failed: [project] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.sh) => {"changed": true, "failed": true, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.sh", "rc": 127, "stderr": "/bin/sh: 1: /home/vagrant/.ansible/tmp/ansible-tmp-1490035932.16-140918060801729/post-provision.sh: not found\n", "stdout": "", "stdout_lines": []}
changed: [project] => (item=../../../../box/scripts/npm-setup.sh)
```

**Comment by geerlingguy** [comment]
For now, I'll just leave out that script and have devs manually add in the 'blt' alias. And this might be 'closed, won't fix' just because I've only encountered it on Windows 7/8, and those aren't really supported by BLT at this time.

**Comment by grasmash** [comment]
Yeah Windows 10+ only support :)

Glad to have it documented here though.

**Comment by mxr576** [comment]
It can be fixed by adding a .gitattributes to repo which enforces proper line-endings on Windows when a repo's content is checked out.

I've used Drupal's .gitattributes as template: https://raw.githubusercontent.com/drupal/drupal/8.4.x/.gitattributes

**Comment by geerlingguy** [comment]
I'm also trying to work entirely within Drupal VM (kind of an outside-in approach), which is SUPER fast on Windows (and heck, Mac/Linux as well), but now I'm hitting:

```
vagrant@local:/var/www/beagov$ ./vendor/acquia/blt/scripts/drupal-vm/post-provision.sh
grep: /vagrant/box/config.yml: No such file or directory
./vendor/acquia/blt/scripts/drupal-vm/post-provision.sh: line 9: temp: Permission denied
```

I'm going to see if we can make `post-provision.sh` a little less error-prone.

**Comment by geerlingguy** [comment]
For now I'm going to just direct people to run [this command](https://github.com/acquia/blt/blob/8.6.15/scripts/drupal-vm/post-provision.sh#L9) inside the VM instead of running the script.

**Comment by geerlingguy** [comment]
See: https://github.com/acquia/blt/issues/1264
