### ISSUE TITLE
Scripts called from BLT's hooks don't have access to internal variables

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1232]
When calling a script via BLT's hooks, scripts don't have access to BLT's internal variables. While this is something that currently works as designed, I think it would be a useful feature if target hooks within BLT were supplied with relevant variables - possibly via sourcing them prior to calling the target script. 

For instance, `pre-config-import` could have a variable `site_name` sourced before execution of the target script and have this variable set to `${multisite.name}` locally and `${deploy.site.name}` remotely (or at least during deployments).

For this feature to work well, each target hook would need a well-documented set of variables that are available during each hook and what one should expect their values to represent.

**Comment by grasmash** [comment]
I would suggest that you simply pass in the desired variables as arguments to your script when you call it.  BLT will have access to the variable values at that time.

**Comment by bobbygryzynger** [comment]
@grasmash - unfortunately, this doesn't work as easily as one might expect.

Take for instance if one wanted to know what site a config import was about to take place on during `pre-config-import`. Here they would need to pass `${multisite.name}` to their script locally but `${deploy.site.name}` when the import is taking place during a deployment. You can't simply write a script that has both values as arguments because, outside of a deployment, `${deploy.site.name}` is not defined, which causes a `bad substitution` error when phing attempts to expand the undefined property.

So, perhaps this is simply an issue with inconsistent variable naming and usage, but the hooks do lack a common interface to BLT's variables and passing in a variable as an argument isn't always a viable option - unless you have an idea as to how the issue outlined above can be overcome.

**Comment by bobbygryzynger** [comment]
@grasmash I wonder if you might consider re-opening this issue given what I've brought up above?
