### ISSUE TITLE
When Upgrading Existing Codebase to 8.7.0-beta1

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1245]
When I update my codebase to 8.7 my composer.json isn't upgraded or cleaned up.  It still had all the legacy BLT cruft.

I had to take a clean fresh 8.7 project, use that composer.json, and then manually add back my customizations.

**Comment by grasmash** [comment]
There is an update hook for this. I will test your repo locally and see if I can reproduce the failure to execute the update.

**Comment by aweingarten** [comment]
I could not reproduce again. My guess is that I had an older version of composer before I attempted the update.  After I had updated my global dependencies.
