### ISSUE TITLE
Default project.yml of blt suggests to work with devel module that is not present in the file system

### ISSUE THREAD

**Issue by mirsoftacquia** [acquia/blt#1258]
My system information:

Operating system type: macOS
Operating system version: 10.12.3
BLT version: 8.6.15

How to reproduce:

- Create a new project from the scratch (http://blt.readthedocs.io/en/8.x/readme/creating-new-project/ ) and deploy it to Acquia Cloud test or prod environment
- Check Recent Log messages in Drupal: you will see PHP warnings that devel module is missing from the file system 

Reason:

In default blt/project.yml , it's suggested to uninstall devel on test and prod environments. However, devel dependency is inserted in the require-dev section of composer.json, that means the devel module is completely ignored from deployment to AC.

Drupal then tries to uninstall module that doesn't exist in the file system which results to the errors above.

It could be either resolved by moving drupal/devel from require-dev to require (in that case it perhaps makes sense to enable devel on dev AC environment by default) , or by removing references to devel completely for test and prod environments in blt/project.yml.

EDIT: I found another similar inconsistency: suggested uninstall of views_ui in project.yml causes inconsistencies too when uninstalled on test and prod. Namely, views_ui is listed as a dependency for Lightning (check ligning.info.yml). As BLT allows uninstalling this module even if this dependency exists, that gets the system into inconsistent state, causing following PHP notices when accessing status report 

_Notice: Undefined index: name in system_requirements() (line 46 of core/modules/system/system.install). 
Notice: Undefined index: version in system_requirements() (line 48 of core/modules/system/system.install)._

Even it may seem these notices are unrelated to this problem at first sight, deep debugging showed that  the subprofile (based on lightning) was not enabled in Drupal . And it was not enabled because the dependency of parent lightning profile (enabled views_ui) was not fulfilled. 

EDIT of EDIT: I cannot reproduce the second inconsistency anymore, however, the uninstalling of views_ui still fails because of issue with drush pm-uninstall described [here](https://github.com/acquia/lightning/issues/308#issuecomment-288838410)

**Comment by grasmash** [comment]
I'd suggest that we move devel to require. We will invariably *sometimes& want it in a deployment artifact when we need to debug ACE envs.
