### ISSUE TITLE
New project and onboarding (existing project setup) scripts

### ISSUE THREAD

**Issue by captaindav** [acquia/blt#1269]
My system information:
* Operating system type: OSX
* Operating system version: El Capitan
* BLT version: 8.6.15

I have created two scripts aimed at automating some common BLT steps, one for creating a new BLT managed project, and another for on-boarding (setting up local dev environment) for a new developer for an existing BLT managed project.  The script contents are displayed at the end of this post.

I was hoping other developers might try running these scripts or have ideas on how they might be improved.

Notes/Questions:

1) The blt_project_onboard script may be useful for testing/verification on a specific machine, in a case where a BLT installation has failed or has issues.  If you place a copy of the onboard script (using the curl command in the script header) on your local, and then execute the script, it will use the https://github.com/captaindav/blt-example repo as its project repo, and should install the complete project code in a directory called “My_Project”, and create a working VM, with a working site at local.myproj.com.  If the script is proven to work on most machines, a failure may indicate that there is something wrong with a specific machine. Often the issue is that some software needs upgraded, e.g.  VirtualBox, Vagrant, Drupal VM base box, VB Guest Additions, PHP, Composer, Ansible, etc.

2) It would be ideal to check the local software versions in an automated way, and make sure they are reasonably up to date.  Perhaps the BLT project.yml file could have “minimum version level requirements” for software like  VirtualBox, Vagrant, Drupal VM base box, VB Guest Additions, PHP, Composer, Ansible, etc.  Then a Phing task could be created that verifies the machine’s local software meets those minimum requirements.  Another nice feature would be for the script to offer to update any software not meeting the minimum requirement.

3) I have pondered how new project and onboarding functionality might be built into BLT, perhaps create tasks like setup:new_project and setup:onboard?  Or provide template scripts included with BLT?

4) It would be ideal for the new project script to have parameters for the BLT version, machine name, prefix, and human name, currently these have to be manually entered in the middle of the new project script execution.

# Here are the scripts:

# blt_project_new.sh:

```

#!/usr/bin/env bash
#
# BLT PROJECT CREATION
#
# This script may be downloaded using the command:
# curl https://raw.githubusercontent.com/captaindav/blt-example/develop/scripts/blt_project_new.sh > blt_project_new.sh
#
# Prerequisites:
#
# 1. This script requires an OS X machine installed with the latest versions of
#    Virtual Box, Vagrant, Ansible, DrupalVM base box, Composer, and PHP 5.6 or greater.
# 2. The latest versions of the following Vagrant plugins are required:
#    -  Host Updater (vagrant plugin install vagrant-hostsupdater)
#    -  Auto Network (vagrant plugin install vagrant-auto_network)
#    -  VB Guest     (vagrant plugin install vagrant-vbguest)
# 3. Set the OSX PHP CLI memory_limit to 2G in php.ini.
# 4. Reboot your machine before running this script.
# 5. No Vagrant VM's may be running, otherwise this script may fail.
#
# Running the script:
#
# 1. Enter a value for PROJECT_ROOT at the begging of this script.
# 2. Place and execute this script in the project root's parent directory. For example, if
#    you want your project to live in /Users/MyUser/Sites/My_Project, then
#    set PROJECT_ROOT='My_Project', place the script in /Users/MyUser/Sites, and execute
#    with ./blt_project_new.sh. It is best to have no spaces in the project root
#    directory name, as it may causes issues with this script.
# 3. Once the script is executed, a vi session will be launched in which you may set the 
#    appropriate BLT project.yml values. Typically these values are set something like:
#      machine_name: myproj
#      prefix: MYPROJ
#      human_name: 'My Project'
#    Note that the machine_name defaults to the value of PROJECT_ROOT, this should be 
#    changed to an all lower case/no spaces/letters-numbers only string, e.g. myproj.
# 4. Once the script completes:
#    -  review the output for errors, especially the output of the
#       "blt doctor" and "blt validate" commands.
#    -  verify the site comes up at local.<machine_name>.com.
# 5. If you would like to wipe your current project code and VM to start fresh, go to your
#    project root directory and issue the command "vagrant destory", then delete the project
#    root directory and re-run this script.
#

# Enter Project Specific Value:
PROJECT_ROOT='My_Project'

# Composer create project
composer clear-cache
export COMPOSER_PROCESS_TIMEOUT=2000
composer create-project --no-interaction acquia/blt-project "${PROJECT_ROOT}"
cd "${PROJECT_ROOT}"

# Create BLT bash alias in .bash_profile
composer run-script blt-alias
source ~/.bash_profile

# Create the BLT Project
vi blt/project.yml
blt vm:project:init
blt vm:local:init
blt vm:up
blt local:setup

# Status reports
composer validate
blt doctor
blt validate
git status

```

# blt_project_onboard.sh

```

#!/usr/bin/env bash
#
# BLT PROJECT ONBOARDING
#
# This script may be downloaded using the command:
# curl https://raw.githubusercontent.com/captaindav/blt-example/develop/scripts/blt_project_onboard.sh > blt_project_onboard.sh
#
# Prerequisites:
#
# 1. This script requires an OS X machine installed with the latest versions of
#    Virtual Box, Vagrant, Ansible, DrupalVM base box, Composer, and PHP 5.6 or greater.
# 2. The latest versions of the following Vagrant plugins are required:
#    -  Host Updater (vagrant plugin install vagrant-hostsupdater)
#    -  Auto Network (vagrant plugin install vagrant-auto_network)
#    -  VB Guest     (vagrant plugin install vagrant-vbguest)
# 3. Set the OSX PHP CLI memory_limit to 2G in php.ini.
# 4. Reboot your machine before running this script. 
# 5. No Vagrant VM's may be running, otherwise this script may fail.
#
# Running the script:
#
# 1. Enter values for GIT_REPO, GIT_BRANCH, PROJECT_ROOT, and MACHINE_NAME at the beginning
#    of this script.
# 2. Place and execute this script in the project root's parent directory. For example, if
#    you want your project to live in /Users/MyUser/Sites/My_Project, then
#    set PROJECT_ROOT='My_Project', place the script in /Users/MyUser/Sites, and execute
#    with ./blt_project_onboard.sh. It is best to have no spaces in the project root
#    directory name, as it may causes issues with this script.
# 3. Once the script completes:
#    -  review the output for errors, especially the output of the
#       "blt doctor" and "blt validate" commands.
#    -  verify the site comes up at local.<machine_name>.com.
# 4. If you would like to wipe your current project code and VM to start fresh, go to your
#    project root directory and issue the command "vagrant destory", then delete the project
#    root directory and re-run this script.
#

# Enter Project Specific Values:
GIT_REPO='git@github.com:captaindav/blt-example.git'
GIT_BRANCH='develop'
PROJECT_ROOT='My_Project'
MACHINE_NAME='myproj'

# Set alias and dump file names
DRUSH_ALIAS=${MACHINE_NAME}.local
DATABASE_DUMP=${MACHINE_NAME}.sql

# Clone project from Git
git clone ${GIT_REPO} -b ${GIT_BRANCH} ${PROJECT_ROOT}

# Install Composer dependencies
# @TODO Prompt yes/no 'BLT defaults to doing a "composer install" for your project,
#  would you like to do a "composer update" instead?'
cd ${PROJECT_ROOT}
composer clear-cache
export COMPOSER_PROCESS_TIMEOUT=2000
composer install

# Create BLT bash alias in .bash-profile  
composer run-script blt-alias
source ~/.bash_profile

# VM
blt vm:local:init
blt vm:up

# Refresh database and files directory
# @TODO Once Acquia hosting is in place, this will refresh from the hosted "master database" instance
# and the Drush sql-cli command will no longer be necessary.  Perhaps we should provide a prompt that 
# offers the choice of either importing a dump file or refreshing the local database from a remote database?
#blt local:refresh
drush @${DRUSH_ALIAS} sql-cli < database/${DATABASE_DUMP}

# Run database updates and import configuration
blt setup:update

# Create tests local.yml
blt setup:behat

# Status reports
composer validate
blt doctor
blt validate
git status

```

**Comment by grasmash** [comment]
These scripts are useful, but I prefer not to commit something to BLT that acts as a standalone script.  However, I think that some ideas from this script would be useful if implemented in BLTs on application logic.

1. I would like to create a wizard that,  during initial project creation, will walk the user through setting up things like a virtual machine, behat, Etc.

2. As for on boarding, the setup command is really intended to be the catch all on boarding commands.  Based on your script here, it looks like we may want to set up command to check to see if a virtual machine has been initialized for the project, and if so, boot that machine.

3. I've also considered the idea of having BLT assist you with installing system requirements. However, I think that may be a can of worms.  As a compromise, I would be willing to at least validate that minimum versions of various libraries are installed. We already do this for most of the virtual machine requirements.

I am going to close this issue. However, if you are interested in any of the three items that I listed, these open a corresponding feature request.
