### ISSUE TITLE
Deploy can be run with uncommitted changes

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1276]
In version `8.6.14` I am able to run `blt deploy` with uncommitted changes and these changes will be included in my deploy. This is a potentially dangerous capability as it could cause a lot of unintentional changes to end up on a remote environment. 

Ideally, BLT would check the working tree and enforce that it is clean before allowing a deploy to proceed.

**Comment by grasmash** [comment]
@bobbygryzynger I had to revert the PR for this. It caused: #1308, as well as an issue with the deploy_tag script.

**Comment by bobbygryzynger** [comment]
@grasmash - are there some flag values that could be checked before inspecting the working tree? It seems like #1308 could be overcome by ensuring that `${environment} != ci`. I don't know if something similar could be used to ensure there are no conflicts with the `deploy_tag` script.

**Comment by bobbygryzynger** [comment]
Another thought: a `git.failOnDirty: true` property could be added to `build.yml` which could be checked in `deploy` and overridden where need be.

**Comment by grasmash** [comment]
@bobbygryzynger Yeah I think git.failOnDirty would be fine. We could default it to TRUE and then set it to FALSE during CI.
