### ISSUE TITLE
Silence git output when it may output fatal errors

### ISSUE THREAD

**Issue by scor** [acquia/blt#1286]
My system information:
* Operating system type: Mac OS X
* Operating system version: 10.10.5
* BLT version: 8.6.15

When I run this command:
```
blt deploy
```

I get the following output:
```
blt > deploy:remote:pull:
fatal: Couldn't find remote ref deploy-build-1
Switched to a new branch 'deploy-build-1'
merge: 281ce531ae6fed2b8dbbca60d0ee5237/deploy-build-1 - not something we can merge
fatal: The remote end hung up unexpectedly
```

The build works, and I suspect the output above is just a side effect of blt trying different commands to see if the branch already exist, but regardless, the 2 fatal errors in the output above can be misleading, especially in situation where the build fails, which happened to me earlier. If one is familiar with blt and knows that this is something to expect, then fine, but IMO this is not very user friendly, and would deserve to be not displayed if it's not meaningful to the end user. just my 2 cts.

**Comment by grasmash** [comment]
Agreed this makes sense.
