### ISSUE TITLE
Handle entity updates

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1297]
Occasionally after changing field and entity definitions, even via the core configuration system (using a full config-export / import), Drupal reports that there are pending entity updates. This typically manifests itself as an error like this on the status report page:

> Mismatched entity and/or field definitions: The following changes were detected in the entity type and field definitions.

It's not clear exactly what produces these mismatched definitions. Some types of changes to a field configuration will definitely produce them (such as changing an image to a decimal), but other changes won't (such as changing cardinality).

It's also not clear what the effects of this are, besides an error on the status report page. For all practical purposes, the configuration changes do seem to take effect in most cases and the changed field or entity works fine.

Finally, it's not clear what's the best way to resolve this error. Simply adding a step to `setup:update` that runs `drush entity-updates` would be a simple solution (this should run after the configuration import step). But folks have pointed out that this is not a preferred method (see #1014), and this command is only for "development purposes". Again, it's not clear what the implications of this are, or what the preferred alternative would be.

We should try to get clarity on these questions.

**Comment by bkosborne** [comment]
Here's a good blog post about this very issue: https://www.agoradesign.at/blog/why-running-drupalentitydefinitionupdatemanager-applyupdates-update-hooks-bad - it goes into a real world issue caused by running entity updates automatically (not via drush, but via an API function that the drush command runs)

**Comment by danepowell** [comment]
The blog indicates that the primary risk is data loss, but I think core throws an exception if there's any existing data that would be deleted. So I'm still not clear on what the risk is.

**Comment by danepowell** [comment]
I think I've found clarity on this.

Just for context... configuration can store things like entity and field storage definitions (among other things). When these change, the changes also need to be applied to the db schema. This can also apply to aspects of the storage definition not directly related to the schema, such as UUID.... these still need to be "applied" on import.

Running a simple config-import does apply most schema changes, such as changing the length of a text field, no problem. Obviously if there is existing content, this import will fail with an exception to prevent data loss.

However, changing the uuid of a field storage is a unique case. For whatever reason, Drupal isn't able to change the uuid as part of the config import process. Follow-up intervention is required (i.e. running `drush entity-updates`). Note that Drupal won't detect that these updates are necessary, however, until after a cron run. In my opinion, this is a bug, and I've opened an upstream issue: https://www.drupal.org/node/2876795

Incidentally, this explains why some entity updates need to be applied after a fresh install, because uuids of default fields provided by modules (e.g. Lightning) are going to be changed. 

Note that in this case, applying entity updates can be destructive. It will delete any existing content in the changed field without warning.

I was not able to find any other scenario where changing a field or entity configuration and running the usual config import would result in entity updates needing to manually be applied. So I think that once that core issue is fixed, we should be able to close this.

**Comment by bkosborne** [comment]
Out of curiosity, what is the use case for changing a field storage definition's UUID?

**Comment by danepowell** [comment]
It can happen at install time if a module creates a field as part of its default configuration that subsequently gets synced from the site's configuration (this means entity updates can be pending even after a fresh install, which I find particularly annoying). It can also happen if a developer has to delete and recreate a field for some reason. Finally, it can happen as a result of trying to work around other bugs in the configuration system.

In an ideal world, I agree that it would be a rare occurrence. But in practice, we see it all the time, especially in the early stages of development.

**Comment by grasmash** [comment]
> So I think that once that core issue is fixed, we should be able to close this

Hm. So this will never be closed?

**Comment by danepowell** [comment]
Was that a joke? 😄 

So far, no traction on that core issue. Maybe we could get the Lightning team interested in it, since Lightning updates can produce this problem as well, and it happens on fresh Lightning installs?

**Comment by danepowell** [comment]
I created a Lightning issue for this as well, since it affects the DX of folks developing with Lightning: #387

**Comment by danepowell** [comment]
This may be a non-issue once this and is upstream Drupal/Lightning counterparts are merged: https://github.com/acquia/blt/issues/2026

**Comment by grasmash** [comment]
@danepowell Since the lighting issue has been closed, can we close this as well?

**Comment by danepowell** [comment]
The related Lightning issues for this are still open and active:
- https://github.com/acquia/lightning/issues/387
- https://www.drupal.org/node/2908097

However, I'm not sure that there's any more action required on the BLT side, so I'll close this.
