### ISSUE TITLE
$BLT_DIR/scripts/travis/deploy_branch running on TravisCI results in error

### ISSUE THREAD

**Issue by arknoll** [acquia/blt#1308]
My system information:
* Operating system type: OSX
* Operating system version: Sierra
* BLT version: 8.7.0-beta3

When I merge into a branch that has a deploy step:
```
   - provider: script
     script: "$BLT_DIR/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: experimental
       php: 5.6
```

I get the following output:
"There are uncommitted changes, commit or stash these changes before deploying."

And I expected this to happen:
deploy phing task to execute normally

Additional info:
It appears there are changes to the project.yml file in the working dir. This command was run right before the deploy step.
```
travis@testing-gce-12a7d536-80ef-411a-811e-dfc2aa90172e:~/build/acquia-pso/canary$ git status
HEAD detached at ae36707
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   blt/project.yml

no changes added to commit (use "git add" and/or "git commit -a")
travis@testing-gce-12a7d536-80ef-411a-811e-dfc2aa90172e:~/build/acquia-pso/canary$ git diff
diff --git a/blt/project.yml b/blt/project.yml
index 964a8e2..3ab6cc2 100644
--- a/blt/project.yml
+++ b/blt/project.yml
@@ -6,7 +6,7 @@ project:
     name: canary
   local:
     protocol: http
-    hostname: 'local.${project.machine_name}.com'
+    hostname: '127.0.0.1:8888'
 git:
   default_branch: master
   remotes:
@@ -60,4 +60,3 @@ behat:
   launch-phantomjs: true
 cm:
   strategy: config-split
-
```

**Comment by arknoll** [comment]
This looks to be due to this new addition: https://github.com/acquia/blt/blob/8.x/scripts/travis/run_tests#L6

**Comment by grasmash** [comment]
This was resolved by this revert commit: https://github.com/acquia/blt/commit/d1cef2f25849da3020fb83aa0bed74450141d04f
