### ISSUE TITLE
Support CDEs for config splits

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#1311]
When a new CDE is created on ACE, config.settings.php should activate a corresponding config split. All CDEs should probably use the same split. E.g., 'ci' or 'cde'.

**Comment by grasmash** [comment]
@arknoll @geerlingguy Let me know if you think this makes sense.

**Comment by arknoll** [comment]
Yeah, this is the same sort of problem I was mentioning with Acquia Search on CDEs. I think the most logical would be to force it into the dev split. If a team wants to override it they can just adjust their settings.php below blt's config include.

**Comment by geerlingguy** [comment]
I would default to `dev`. Failing that, `cde`. It's definitely going to be different than the typical `ci` environment, if devs can log into sites running on them and use them like they would one of the normal cloud environments.

**Comment by grasmash** [comment]
I've created an ah_other split to handle both RA envs and CDEs. #1331
