### ISSUE TITLE
Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#132]
When using the most recent version of blt and drupal vm, i get to the point where i am running ./blt.sh local:setup. during this process it errors but doenst give a good error msg so i ran the command manually to see what was happening, the result was "Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command." I think this command is being ran form the roject root when it should be ran from the docroot of th drupal site.

**Comment by grasmash** [comment]
Running the same command manually may give you a different result because running a target via blt.sh may actually execute the command in a different directory than your current working directory. What command did you run? If it's a drush command, you likely need to execute it from the docroot. Otherwise drush can't find Drupal.

**Comment by haynescw** [comment]
Its it the drush install site command. Im running it again to get the error output from that for you.

**Comment by haynescw** [comment]
project > setup:drupal:install:

    [drush] Executing '/Users/XXXXX/Documents/Clients/XXXXXX/dev/blted8/vendor/bin/drush @blted8.local --site-name="BLTed 8" --site-mail="no-reply@acquia.com" --account-name="admin" --account-pass="admin" --account-mail="no-reply@acquia.com" --l="default" --nocolor --yes --verbose site-install "lightning" "install_configure_form.update_status_module='array(FALSE,FALSE)'"'...
Loaded alias @blted8.local from file /Users/XXXXX/Documents/Clients/XXXXXX/dev/blted8/drush/site-aliases/drupal-vm.aliases.drushrc.php                                                                                                                                  [notice]
Begin redispatch via drush_invoke_process().                                                                                                                                                                                                                            [notice]
Calling proc_open(ssh -o PasswordAuthentication=no -i /Users/XXXXX/.vagrant.d/insecure_private_key vagrant@blted8.localhost 'env COLUMNS=272 drush  --local --alias-path=/Users/XXXXX/Documents/Clients/XXXXXX/dev/blted8/drush/site-aliases --nocolor --yes --verbose --uri=default --root=/var/www/blted8/docroot  site-install lightning '\''install_configure_form.update_status_module='\''\'\'''\''array(FALSE,FALSE)'\''\'\'''\'''\''   --site-name='\''BLTed 8'\'' --site-mail='\''no-reply@acquia.com'\'' --account-name=admin --account-pass=admin --account-mail='\''no-reply@acquia.com'\'' 2>&1' 2>&1);
End redispatch via drush_invoke_process().                                                                                                                                                                                                                              [notice]
    [drush]  [error]  Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.
    [drush]  [error]  The drush command 'site-install lightning install_configure_form.update_status_module='array(FALSE,FALSE)'' could not be executed.
[phingcall] /Users/XXXXX/Documents/Clients/XXXXXX/dev/blted8/build/core/phing/tasks/setup.xml:73:85: Drush exited with code 1

BUILD FAILED
/Users/XXXXX/Documents/Clients/XXXXXX/dev/blted8/build/core/phing/tasks/local-sync.xml:12:30: Execution of the target buildfile failed. Aborting.

Total time: 42.5293 seconds

**Comment by CashWilliams** [comment]
Are you running this from the host or from inside the VM?

I have a feeling this is an issue with the drush alias files, as they are not fully ironed out for the VM workflow.

**Comment by haynescw** [comment]
I am running this from my mac not drupal vm.

**Comment by grasmash** [comment]
Dumb question, but is the VM running? If you run `drush @blted8.local ssh` can you login to it?

**Comment by haynescw** [comment]
An error 1 occurred while running the command `ssh -o PasswordAuthentication=no -i /Users/37332/.vagrant.d/insecure_private_key -t vagrant@blted8.localhost 'cd /var/www/blted8/docroot && bash  [error]
-l'

**Comment by haynescw** [comment]
I found the generate config file is wrong, in the section

# Provide the path to the project root to Vagrant.
vagrant_synced_folders:
  # Set the local_path for the first synced folder to `../`.
  - local_path: .
    # Set the destination to the Acquia Cloud subscription machine name.
    destination: /var/www/blted8
    type: nfs

local path needs to be set to ../

**Comment by haynescw** [comment]
after updating that line, i can ssh with the drush command like you wanted

**Comment by haynescw** [comment]
Nice, that . to a ../ fixed my issue and it completed the setup task. Thanks @grasmash for thinking of logging in with drush. Really made the difference.

**Comment by haynescw** [comment]
Dont forget to update that line

**Comment by grasmash** [comment]
Hm. I've just run the vagrant up command with it set to `.` and it worked.  Changing to `../` causes the same error for me that you described. Strange. I assume that you used `blt vm:init` to do the initial configuration?

**Comment by haynescw** [comment]
Yes, I started my entire build from scratch and used all the new changes to the Readme's, which included `blt vm:init`

**Comment by grasmash** [comment]
My best guess is that you may have an older version of Vagrant. I've found the default config to work on Vagrant 1.8.1, `vagrant -v`.

**Comment by haynescw** [comment]
This was resolved by one of your commits, when i ran the command again,
after starting all over, fresh pull on everything, and changing my nfs
share to ../ ended up with everything working. If that makes sense.

**Comment by grasmash** [comment]
The part that confuses me is that you shouldn't need to change the nfs share value.

**Comment by geerlingguy** [comment]
With the latest everything, it should work with `.`... but maybe @haynescw has an older/not-8.x-latest copy of Bolt/BLT that has some patches applied but others not. Also, Drupal VM had some changes between 2.5.1 -> 3.0.0 -> 3.1.0 that could require some differences with setup.

Note that the way Drupal VM is installed/added on has changed recently too, and the old way required `../` but the current way `.`.

**Comment by grasmash** [comment]
I'm pretty sure he generated his project with the most recent version of BLT, which pins Drupal VM to ~3.1 and Drupal ~8.1. So, the only think that I can think of that would be different is Vagrant or Virtual Box.

**Comment by haynescw** [comment]
To clarify, when i submit my issues, i do my best to start from scratch. Fresh clone of blt and drupalvm. So if I do get an issue on a build, I do a get pull on blt and see if there are changes. if there is I start completely from scratch to abstract myself for old, outdated code.

**Comment by kevinquillen** [comment]
I also just ran into this very same error.

Are we to run ./blt.sh local:setup from _inside_ the VM, or the hostmachine?

**Comment by grasmash** [comment]
@kevinquillen Try removing the `-r ${DIR}/docroot` from drush.wrapper and let me know if that helps.

**Comment by grasmash** [comment]
If not, open a new issue and share your log output and configuration.

**Comment by kevinquillen** [comment]
Running.... that worked. What was the issue there?

On Thu, Jul 21, 2016 at 11:37 AM, Matthew Grasmick <notifications@github.com

**Comment by grasmash** [comment]
The -r argument tells drush where the docroot is, but that script is using the host machine's filesystem to set the argument value. Within the VM that causes issues. We should remove it from BLT until we find a more dynamic solution.

**Comment by sodacrackers** [comment]
For anyone else, drush worked for me by using site aliases:  `drush @mysite.local en some_module -t`
