### ISSUE TITLE
Examples.feature changes overwritten whenever BLT is updated

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1322]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.4
* BLT version: 8.7.0

When I update BLT, the `tests/behat/features/Examples.feature` file is reverted to BLT's default example feature file:

```
diff --git a/tests/behat/features/Examples.feature b/tests/behat/features/Examples.feature
index d81895d..c3a0795 100644
--- a/tests/behat/features/Examples.feature
+++ b/tests/behat/features/Examples.feature
@@ -8,8 +8,8 @@ Feature: Web drivers
   @javascript
   Scenario: Load a page with Javascript
     Given I am on "/"
-    Then I should see the text "Something on my site"
+    Then I should see the text "Log in"
 
   Scenario: Load a page without Javascript
     Given I am on "/"
-    Then I should see the text "Something on my site"
+    Then I should see the text "Log in"
```

I would rather that file be left alone. Our site doesn't have the text "Log in" on the home page, so every time I update BLT, I am reminded by our CI environment that I have to go back in and revert the changes to that file so tests pass.

**Comment by geerlingguy** [comment]
I can, of course, run `git checkout -- tests/behat/features/Examples.feature` after every update, but after doing this about 8 times I figured I'd finally open an issue.

**Comment by grasmash** [comment]
Well, we can prevent this file from being overwritten, but do you really need to modify the example file?

**Comment by geerlingguy** [comment]
@grasmash - If I don't change it, it causes tests to fail; we put all our feature files in that directory and tell behat to run all those tests. We disabled the 'Log in' link block on our site since it shouldn't display any login links anywhere.
