### ISSUE TITLE
What to do if using Config Split with the RA environment?

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1324]
Since 8.7.0 now includes `config-split` support (which seems to work well in most cases), and our site has an `ra` (Remote Administration) environment, what's the best way to handle an `ra` split?

One option might be to just not create and `ra` split at all... I haven't yet tested this, but it could work.

Another option would be to add to the site's `settings.php` at the bottom:

```php
require DRUPAL_ROOT . "/sites/default/settings/config_split.settings.php";
```

Then add this in that `config_split` settings file:

```php
<?php

/**
 * @file
 * Config Split custom settings for BEA.
 */

// RA Environment settings.
$is_ah_ra_env = ($ah_env == 'ra');
$config['config_split.config_split.ra']['status'] = FALSE;
if ($is_ah_ra_env) {
  $split = 'ra';
  if (file_exists("$split_filepath_prefix.$split.yml")) {
    $config["$split_filename_prefix.$split"]['status'] = TRUE;
  }
}
```

We don't particularly use the RA environment, so I'm wondering if maybe the best practice would just be "don't add a split for RA"?

**Comment by grasmash** [comment]
Not adding an RA split should cause all default config to be imported. That seems fine. Does it meet your reqs?

**Comment by geerlingguy** [comment]
Yep! I'll likely take that approach, since we have nothing special in the config.

Another follow-up, though—suppose we're using CD Environments... and we want them to behave more-or-less like Dev. Is there a simple way we could flag the 'dev' split to be active by default in any Cloudy environment that doesn't have another split defined?

**Comment by grasmash** [comment]
Yeah there's another issue open to deal with they question. I was thinking we'd have a split just for CDEs, but we could instead have an Acquia Cloud "other" split that would be more broad. 

preference?

**Comment by geerlingguy** [comment]
I'd maybe slightly prefer an 'other' split... there are other situations besides just CD and RA.
