### ISSUE TITLE
Permission Denied on blt bash alias creation

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#133]
Create a bash alias now? (y/n) [y] ?  y
./install-alias.sh: line 19: /Users/XXXXX/.bashrc: Permission denied
Added alias for blt to /Users/XXXXX/.bashrc
Restart your terminal session to use the new command.

**Comment by grasmash** [comment]
You'll need to set more liberal permissions on `~/.bashrc`, then run `./blt.sh bolt:alias`.

**Comment by grasmash** [comment]
I've updated the install-alias.sh script to inform you of failure properly.
