### ISSUE TITLE
Drupal 8.3.0 and Lightning 2.1.0 with subprofiles causes issues in CI

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1330]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.4
* BLT version: 8.7.0

When I run this command:

* Travis CI or Acquia Pipelines builds my project from my existing configuration (using core config import or `config-split`).

I get the following output:

```
    core.entity_view_mode.contact_message.token                                 Undefined variable: install_profile ConfigImportSubscriber.php:119      [notice]
Drupal\Core\Config\ConfigImporterException: There were errors        [error]
validating the config synchronization. in
Drupal\Core\Config\ConfigImporter->validate() (line 728 of
/home/travis/build/acquia-pso/projectname/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
The import failed due for the following reasons:                     [error]
Unable to install the <em class="placeholder">projectname_profile</em>
module since it does not exist.
Cannot change the install profile from <em
class="placeholder">projectname_profile</em> to <em
class="placeholder"></em> once Drupal is installed.
Command dispatch complete                                               [notice]
Command dispatch complete                                               [notice]
```

And I expected this to happen:

* The site's configuration should be imported correctly, and integration tests succeed.

**Comment by geerlingguy** [comment]
I'm mostly posting this for the SEO... because I'm sure someone else will run into this.

Basically, here's what caused this to happen:

  * This project excludes some of Lightning's features.
  * Pre-Lightning 2.0.5, this was done using `lightning.excludes.yml`
  * Lightning 2.0.5+ requires this to be done using a sub-profile (see [docs](https://github.com/acquia/lightning/blob/8.x-2.x/UPDATE.md#204-to-205))
  * I upgraded BLT and Lightning, and created the new sub-profile using Lightning's script.
  * Locally everything runs fine (`blt local:refresh`)
  * In the CI environment, I hit some errors during the config import (In CI, the site installs fresh every time.)
  * I decided to then upgrade to Drupal 8.3.0 and Lightning 2.1.0.

**Comment by geerlingguy** [comment]
I'm wondering if maybe I'm hitting one of the following issues (or something related):

  * [When installing a profile module it incorrectly gets added to the module list with type module](https://www.drupal.org/node/2595663)
  * [Profiles are causing a problem whilst installing modules](https://www.drupal.org/node/2512700)

**Comment by geerlingguy** [comment]
Also, I have:

```php
$settings['install_profile'] = 'projectname_profile';
```

Inside `docroot/sites/default/settings.php`. Maybe this needs to be set somewhere else for the CI environment to see it?

I'm still getting:

```
Import the listed configuration changes? (y/n): y
Undefined variable: install_profile ConfigImportSubscriber.php:119      [notice]
Drupal\Core\Config\ConfigImporterException: There were errors        [error]
validating the config synchronization. in
Drupal\Core\Config\ConfigImporter->validate() (line 728 of
/home/travis/build/acquia-pso/projectname/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php).
The import failed due for the following reasons:                     [error]
Cannot change the install profile from <em
class="placeholder">projectname_profile</em> to <em
class="placeholder"></em> once Drupal is installed.
```

**Comment by geerlingguy** [comment]
Ah, just realized that when you change install profiles for a BLT project, you should probably also change the profile inside the `blt/project.yml` settings:

```yaml
project:
  machine_name: projectname
[...]
  profile:
    name: projectname_profile
```

Trying that now.

**Comment by geerlingguy** [comment]
Well... in addition to the above change, I _also_ had to make sure the `projectname_profile` was in the list of `modules` inside `core.extension.yml`.

**Comment by swichers** [comment]
The syntax is  `profile: profile_name` instead of

```
profile:
  profile_name: 0
```

Like the rest of the settings in the file.

**Comment by Mramir-hs2** [comment]
profile_name did not work for me. I used
`profile: standard`
as a base key

**Comment by swichers** [comment]
"profile_name" is meant to be the name of your profile.
