### ISSUE TITLE
Travis email error starting with Drupal 8.3.0 and Lightning 2.1.0

### ISSUE THREAD

**Issue by damontgomery** [acquia/blt#1336]
I have a fix listed at the end. I'm mostly leaving this here in case someone gets a similar issue.

My system information:
* Operating system type: Travis CI
* Operating system version: unknown
* BLT version: 8.6.15

Drupal 8.3.0 and Lightning 2.1.0. I could not update one without the other. Previous versions of Drupal / Lightning did not share this issue.

When I run this command:
```
Travis CI:
blt ci:setup (install drupal)
```

I get the following output:
```
Installation complete.  User name: admin  User password: admin       [ok]
Unable to send email. Contact the site administrator if the problem  [error]
persists.
Existing files must be classified according to the currently defined [status]
```

And I expected this to happen:

The BLT target supposedly tells drush to install without sending notices, but that doesn't happen.

Fix:

Copying the following from Lightning into the `travis.yml` seems to have fixed it by configuring PHP to use a dummy service for mail.

```
# Tweak PHP configuration.
  # Copied from Lightning.
  # We were getting an error where drush si is trying to send mail even though the flag to prevent that was set.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash
```

**Comment by grasmash** [comment]
Hm. Seems like a drush or Drupal core bug right? I can implement this workaround in the mean time.
