### ISSUE TITLE
Add 'exclude' config split and structure it for configs like webforms or contact forms

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1339]
Basically, the last of the main features many of us building single Drupal sites with core CMI have wanted is the ability to allow certain configurations to be ignored/not touched in a production environment (or any environments).

Such would be the case for things like Webforms and core Contact forms.

According to [this blog post](https://blog.liip.ch/archive/2017/04/07/advanced-drupal-8-cmi-workflows.html), this could easily be achieved by using an `exclude` config split.

From that blog post, it looks like the workflow would be:

  1. Create the split.
  2. In settings, `$config['config_split.config_split.exclude']['status'] = TRUE;` on environments it needs to be active.
  3. Don't make `exclude` active on the local environment (so you could still create and push new configs from local _to_ prod, just not vice-versa).
  4. During deployments (in cloud hooks), add in a `drush config-split-export -y exclude` _just before_ the `config-import`, so that the configuration persists on prod.

I haven't personally tested this yet, but it sounds like a reasonable solution, and as long as the `csex exclude` is part of the automated build process (cloud hooks), there is little risk of accidentally blowing away excluded configs on prod.

**Comment by arknoll** [comment]
@geerlingguy Why wouldn't you just use config ignore and set up a rule like '*custom_contact_form*' and instruct the client to just ensure that any form they create must have "custom_contact_form" in the name for it to get ignored.

**Comment by geerlingguy** [comment]
@arknoll - That's another option, but it adds another required dependency, and also requires admins to do something a specific way... but it's definitely a valid approach.

In a sense, it's 6 of one, half dozen the other, but it would be good to test both methods and see which one causes the least friction (and has the fewest surprises). I haven't had time yet to test either.

**Comment by arknoll** [comment]
@geerlingguy I think one big benefit of using config ignore is that it works better in a multisite environment where you don't know all of the config that should not be lost. With the exclude split you need to specifically add every item that you want excluded. Once you get over one or two sites this will be very difficult to manage.

Alternatively, on a 3, 5,20 or 3000 site platform if you just tell the individual site builders to prefix everything with a specific string then the individual sites can keep their "snowflake" config without the platform needing to know what it is.

**Comment by geerlingguy** [comment]
True; that would allows us to not add an exclude split. And worst case, if someone does want to go the exclude split route, they can still define it in their own settings.php files.
