### ISSUE TITLE
Split git config user email and name and document it

### ISSUE THREAD

**Issue by marvil07** [acquia/blt#1340]
As a follow-up for #1323 I think the configuration is independent between `git.user.name` and `git.user.email`, so it should not be required to have both.

Also, I do not know the right place to document that, but I think it should.

PR will follow.

**Comment by grasmash** [comment]
Can you tell me the value of your variables_order setting in php.ini?

**Comment by marvil07** [comment]
@grasmash Here the value. I have not changed that from default.
```
$ php -r 'echo ini_get("variables_order");'
GPCS
```
I do not really see how is that related, but maybe I am just lost. The patch at PR #1341 is about letting set only one of email or name git override, instead of requiring both at the same time.

**Comment by grasmash** [comment]
@marvil07 I believe that BLT may already support git environmental variables, but your local PHP installation does not have environmental variables enabled. You should change your `variables_order` value in php.ini to include an E. E.g., `GPCSE`.

This problem should have been diagnosed by `blt doctor`. Can you verify that BLT doctor correctly reports this issue?

**Comment by grasmash** [comment]
@marvil07 have you had a chance to test this?

**Comment by grasmash** [comment]
Closing this issue do to inactivity. I believe it is resolved. Please re-open is suggested solution does not work.
