### ISSUE TITLE
post-db-copy no longer working after 8.7.0 upgrade

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1342]
When I run this command:

* Copy a database to a cloud environment (triggering the `post-db-copy` cloud hook).

I get the following output:
```
[2017-04-07 22:04:50] Executing: /mnt/users/project/test.shell /var/www/html/project.test/hooks/common/post-db-copy/post-db-copy.sh project test project prod < /dev/null (as project.test@staging-21390})
/var/www/html/project.test/hooks/common/post-db-copy/post-db-copy.sh: 21: /var/www/html/project.test/vendor/acquia/blt/scripts/cloud-hooks/functions.sh: 
Syntax error: "(" unexpected (expecting "}")
```

And I expected this to happen:

* The cloud hook should execute the correct function inside `functions.sh`.

Notes:

* The code deploy hook works fine.

Here's the contents of post-db-copy.sh:

```bash
site="$1"
target_env="$2"
db_name="$3"
source_env="$4"
drush_alias=${site}'.'${target_env}

acsf_file="/mnt/files/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/files-private/sites.json"
if [ ! -f $acsf_file ]; then
  . /var/www/html/$site.$target_env/vendor/acquia/blt/scripts/cloud-hooks/functions.sh
  deploy_updates
  exit $status
fi
```

And compare to the contents of post-code-deploy.sh, which works fine:

```bash
site="$1"
target_env="$2"
source_branch="$3"
deployed_tag="$4"
repo_url="$5"
repo_type="$6"

acsf_file="/mnt/files/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/files-private/sites.json"
if [ ! -f $acsf_file ]; then
  . /var/www/html/$site.$target_env/vendor/acquia/blt/scripts/cloud-hooks/functions.sh
  deploy_updates
  # Send notifications to Slack, if configured. See readme/deploy.md for setup instructions.
  . `dirname $0`/../slack.sh
  exit $status
fi
```

**Comment by geerlingguy** [comment]
The actual commands/critical vars are identical between the two, and the only difference is that line with slack notifications (which this project doesn't use).

**Comment by grasmash** [comment]
There is no `post-db-copy.sh` script in BLT.

It seems like your script is somehow triggering the acsf_deploy method. Frankly I don't quite understand the case logic in...

```
deploy_updates() {

  case $target_env in
    [01]*)
      acsf_deploy
      ;;
    *)
      ace_deploy
      ;;
    esac
}
```

@lcatlett do you have any thoughts?

**Comment by geerlingguy** [comment]
Sorry, forgot to mention—I basically copied over the method from `post-code-deploy.sh` because the way we do deploys to prod is:

  - Deploy to prod
  - Verify prod
  - Pull database back to all other environments

For that third step, if we don't have the cloud hook, that means I would need to pull the database back and redeploy the same tag (two manual steps instead of one!), or I would need to pull the database back and manually run some drush commands (ick!).

**Comment by geerlingguy** [comment]
@grasmash - For the time being, I just pasted the actual commands into `post-db-copy.sh`, since I don't need to worry about the acsf stuff. It's a little more annoying in that this means there's a few more lines of code to maintain in my project, but it works well and since a post-db-copy hook isn't included by default anyways, we would have to maintain some custom code regardless.

Here's what I ended up putting into `post-db-copy.sh` (basically just the contents of the ace command in the BLT `functions.sh` script):

```bash
#!/bin/sh
#
# Cloud Hook: post-db-copy
#
# The post-db-copy hook is run whenever you use the Workflow page to copy a
# database from one environment to another. See ../README.md for
# details.
#
# Usage: post-db-copy site target-env db-name source-env

site="$1"
target_env="$2"
db_name="$3"
source_env="$4"
drush_alias=${site}'.'${target_env}

status=0
echo "Running updates for environment: $target_env"

# Prep for BLT commands.
repo_root="/var/www/html/$site.$target_env"
export PATH=$repo_root/vendor/bin:$PATH
cd $repo_root

blt deploy:update -Denvironment=$target_env -Dblt.verbose=true
if [ $? -ne 0 ]; then
    echo "Update errored."
    exit 1
fi

echo "Finished updates for environment: $target_env"
exit $status
```
