### ISSUE TITLE
Running composer with argument --ignore-platform-reqs

### ISSUE THREAD

**Issue by leonk** [acquia/blt#1367]
In our project, we need to run composer with the `--ignore-platform-reqs` flag.  As we are running this from our host (and actually all our requirements are on the VM).

Currently we are unable to run `blt local:setup`, and have to run composer manually, and then run blt from inside the VM.

It would be nice if there was a way to pass arguments through to composer.  Either from the CLI or via project.yml

**Comment by grasmash** [comment]
#1394 Will allow you to add a string to the end of the `composer install` command by defining `composer.extra`. You may define it either in project.local.yml, project.yml, or via CLI with `-Dcomposer.extra='--ignore-platform-reqs'`
