### ISSUE TITLE
BLT upgrade deletes docroot/sites/default/settings/includes.settings.php

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1374]
I'm not sure what to do with this one, so I'll explain the problem, and guess at a fix.

When I upgrade BLT (in this case, 8.6.14 to 8.8.1), my project `docroot/sites/default/settings/includes.settings.php` file gets removed. This is due to an entry in `scripts/blt/remove-deprecated.sh` added in #445. Since that PR was merged, I had contributed another PR #927 to the project, which looks for an optional file in BLT settings loads, and loads it if it's available. The unfortunate part is the naming. I believe a file was removed a long time ago, and then I'm re-adding the same file name for a different purpose.
If I simply remove the line from remove-deprecated.sh, then someone theoretically upgrading from a very old version of BLT may have this file still included. If it stays there, everytime I (or anyone using this option) upgrades, it gets deleted.

Any thoughts on direction here? I'm leaning towards removing that line from "remove-deprecated.sh", but I wanted to present the other ramifications.

**Comment by grasmash** [comment]
@dpagini I'm fine with removing it from remove-deprecated.sh.

**Comment by dpagini** [comment]
thanks @grasmash!
