### ISSUE TITLE
No `$ composer drupal-scaffold` available.

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1386]
My system information:
* Operating system type: Mac
* Operating system version: MacOS Sierra
* BLT version: 8.8.1

When I run this command:
```
$ composer drupal-scaffold
```

I get the following output:
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "drupal-scaffold" is not defined.
```

Ok, so I have a complex issue here. I found this due to a failed CI test. I use a `docroot/sites/all` folder for some common settings (I believe this is a common Drupal approach?) in my multisite install. I also do not specify my "multisite" values and let BLT generate them for me. In doing so, BLT comes back with "all,default,_etc._" for my multisite values. "all" is not actually a site. My error is coming up in the `setup:drupal:settings:site` step, where it's looking for `default.settings.php` file in my site (all) folder, can't find it, and then runs `$ composer drupal-scaffold` to try and create that file.

I can do a few things here. I can 1) set my multisite variable manually, 2) place "default.settings.php" into the `docroot/sites/all` folder, or 3) go forward with some below proposed fixes...

So I'm wondering if I'm seeing this "composer drupal-scaffold" problem just because of my setup, and no one else has seen the error because their project is set up differently...? Can anyone try to run `$ composer drupal-scaffold` from their project root and see if it's available? If not, this might be due to the wikimedia/composer-merge-plugin that was recently added to BLT... maybe?

Second, I'm wondering what the thought is to allow an "all" folder in `docroot/sites` and then ignore that in the multisite properties assignment?
I've gotten this to work locally by changing `phing/tasks/properties.xml` line 70 from:
```
<exec command="find ${docroot}/sites/* -maxdepth 0 -type d | grep -v -e '${docroot}/sites/g$' | sed -e 's%${docroot}/sites/%%g' -e '2,$s%^%,%' | tr -d '\n'"
 outputProperty="multisite.name" logoutput="true" checkreturn="true"/>
```
to:
```
<exec command="find ${docroot}/sites/* -maxdepth 0 -type d | grep -v -e '${docroot}/sites/g$' -e '${docroot}/sites/all$' | sed -e 's%${docroot}/sites/%%g' -e '2,$s%^%,%' | tr -d '\n'"
  outputProperty="multisite.name" logoutput="true" checkreturn="true"/>
```

**Comment by grasmash** [comment]
I think you need to run `composer run-script drupal-scaffold`

**Comment by dpagini** [comment]
Ah, that does work for me...[

Then, should [this line](https://github.com/acquia/blt/blob/8.x/phing/tasks/setup.xml#L80) change to that syntax?

**Comment by grasmash** [comment]
Oops, yes!

**Comment by dpagini** [comment]
Thanks @grasmash - just added a PR to fix. Any thoughts on the `docroot/sites/all` setup? Would it be OK to exclude that folder from the multisite variable assignment? I'll put up a PR to propose that change until I hear back from you. Thanks!

**Comment by grasmash** [comment]
I think that we should change properties.xml as you suggested.
