### ISSUE TITLE
BLT Doctor checkUri reports incorrect uri

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1408]
My system information:
* Operating system type: MacOS
* Operating system version: MacOS Sierra 10.12.3
* BLT version: 8.8.2

Output of `blt doctor`:
```
blt > doctor:
Changed current directory to /home/vagrant/.composer
+----------------------+----------------------------------------------------------------------------------+
| Property             | Value                                                                            |
+----------------------+----------------------------------------------------------------------------------+
| %paths               |                                                                                  |
|  - %root             | /var/www/blt-site/docroot                                                        |
|  - %site             | sites/default                                                                    |
|  - %modules          | modules                                                                          |
|  - %themes           | themes                                                                           |
|  - %config-sync      | /var/www/blt-site/config/default                                                 |
|  - %files            | sites/default/files                                                              |
|  - %private          | /var/www/blt-site/files-private                                                  |
|  - %temp             | /tmp                                                                             |
| admin-theme          | seven                                                                            |
| blt-version          | 8.8.2                                                                            |
| bootstrap            | Successful                                                                       |
| config-sync          | /var/www/blt-site/config/default                                                 |
| db-driver            | mysql                                                                            |
| db-hostname          | localhost                                                                        |
| db-name              | drupal                                                                           |
| db-password          | drupal                                                                           |
| db-port              | 3306                                                                             |
| db-status            | Connected                                                                        |
| db-username          | drupal                                                                           |
| drupal-settings-file | sites/default/settings.php                                                       |
| drupal-version       | 8.3.0                                                                            |
| drush-alias-files    | /var/www/blt-site/docroot/../drush/site-aliases/aliases.drushrc.php              |
|                      | /var/www/blt-site/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php |
|                      | /var/www/blt-site/docroot/../drush/site-aliases/example.local.aliases.drushrc.ph |
|                      | p                                                                                |
| drush-conf           | /var/www/blt-site/drush/drushrc.php                                              |
| drush-script         | /var/www/blt-site/vendor/drush/drush/drush.php                                   |
| drush-temp           | /tmp                                                                             |
| drush-version        | 8.1.10                                                                           |
| files                | sites/default/files                                                              |
| install-profile      | lightning                                                                        |
| local-drushrc        | /var/www/blt-site/docroot/sites/default/local.drushrc.php                        |
| local-settings       | /var/www/blt-site/docroot/sites/default/settings/local.settings.php              |
| modules              | modules                                                                          |
| php-bin              | /usr/bin/php                                                                     |
| php-conf             | /etc/php/5.6/cli/php.ini                                                         |
| php-os               | Linux                                                                            |
| private              | /var/www/blt-site/files-private                                                  |
| root                 | /var/www/blt-site/docroot                                                        |
| site                 | sites/default                                                                    |
| temp                 | /tmp                                                                             |
| theme                | bartik                                                                           |
| themes               | themes                                                                           |
| uri                  | default                                                                          |
| user                 |                                                                                  |
+----------------------+----------------------------------------------------------------------------------+
+--------------------------+---------------------------------------------------------------------------------+
| Check                    | Outcome                                                                         |
+--------------------------+---------------------------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                                  |
| checkCoreExists          | Drupal core exists                                                              |
| checkSettingsFile        | BLT settings are included in settings file.                                     |
| checkLocalSettingsFile   | Found your local settings file.                                                 |
| checkLocalDrushFile      | Found your local drush settings file.                                           |
| checkUri                 | Site URI is not set                                                             |
|                          |                                                                                 |
|                          | Is $options['uri'] set correctly in                                             |
|                          | /var/www/blt-site/docroot/sites/default/local.drushrc.php?                      |
|                          |                                                                                 |
| checkFileSystem:%files   | Public files directory is writable.                                             |
| checkFileSystem:%private | Private files directory is writable.                                            |
| checkFileSystem:%temp    | Temporary files directory is writable.                                          |
| checkDbConnection        | Connected to database.                                                          |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                  |
| checkDrupalInstalled     | Drupal is installed.                                                            |
| checkCaching:page        | Drupal cache is disabled.                                                       |
| checkCaching:css         | CSS preprocessing is disabled.                                                  |
| checkCaching:js          | JS preprocessing is disabled.                                                   |
| checkNvmExists           | NVM does not exist.                                                             |
|                          |                                                                                 |
|                          | It is recommended that you use NVM to manage multiple versions of NodeJS on one |
|                          | machine.                                                                        |
|                          | Instructions for installing NVM can be found at:                                |
|                          |   https://github.com/creationix/nvm#installation                                |
| checkComposer:require    | acquia/blt is in composer.json's require object.                                |
| checkComposer:plugins    | hirak/prestissimo plugin for composer is installed.                             |
| checkBehat:exists        | Behat local settings file exists.                                               |
| checkBehat:uri           | base_url in tests/behat/local.yml does not match the site URI.                  |
|                          |   Behat base_url is set to "http://local.blt-site.com".                         |
|                          |   Drush site URI is set to default.                                             |
| checkProjectYml:keys     | project.yml has no deprecated keys.                                             |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                                  |
+--------------------------+---------------------------------------------------------------------------------+

BUILD FINISHED; 7.2113 seconds
```

And I expected this to happen:
This is clearly pretty low priority b/c I don't think (or know of) this affecting anything, but I just cannot figure out how to get `$ blt doctor` to report the correct "checkUri" and "checkBehat:uri" checks. `checkUri()` tells me to set the `$options['uri']`in `docroot/sites/default/local.drushrc.php`, but it is set.
I think I did a really simple test in following the [Create a new project](https://blt.readthedocs.io/en/stable/readme/creating-new-project/) instructions for a project from scratch, and using Drupal VM. 

As usual, happy to help fix this one, but could use some direction/ideation. I see that "drush_core_status()" function is returning "default" for the site uri, even though `$ drush status` on the command line returns the correct uri. To be honest, I'm not even sure I can figure out where the "drush_core_status()" function is defined?

**Comment by dman-coders** [comment]
This issue may be marked fixed, but I got similar to the dupe referenced in https://github.com/acquia/blt/issues/859

The `blt doctor` was NOT reporting any error with variables_order (though I updated my /Applications/DevDesktop/php7_0/bin/php.ini to the recommended values anyway, to try).

My /private/var/www/d8-blt/docroot/sites/default/local.drushrc.php was set correctly, and *normal* drush (such as drush uli) was recognising this enough to work as expected. Only blt doctor seemed to think there was any problem.

I was running with a composer.json requiring
        "acquia/blt": "^8.3",
... though was built by following instructions earlier in the year.

To fix, I ran
`composer update acquia/blt`
But nope. I was on 8.8.3 from 2017-04-19 and there was no fix produced.

.. .. ..

So yep, Manually choosing a new better version constraint seems to be the thing here
But internal conflicts abounded (and this was a vanilla blt site that had nothing special added to it!)

After a further 16 composer-mandated coffee-breaks, I eventually achieved success with

`composer require 'acquia/blt:^8.9@dev' 'consolidation/robo:dev-master' 'wikimedia/composer-merge-plugin:dev-master'

At this point, `blt doctor` stopped being unhappy.

I think this means that the 'fixed' repair indicated by grasmash above is fixed only in 8.9.? dev unstable for now.

Apologies if this is obvious to everyone else who knows composer inside and out, but I thought I'd add my troubleshooting note here, as this issue was the search result when I gave up blaming myself and went looking for answers in the issue queue...

blt 8.8.3 (last stable) still has this problem. Upgrading from that to 8.9.x is not a clean process.

I imagine there is an easier way.

I re-tried a clean install from scratch following the still-current https://github.com/acquia/blt/blob/8.x/readme/creating-new-project.md instructions, and still got 8.8.3, and still have the same issue with dev desktop.

So - the fix is not yet in the stable recommended release. Glad to see the end of phing however (way too many build toolsets in my life already), so looking forwards to an upgrade tagged release.

**Comment by simesy** [comment]
I've had the same issue, which I think is biting me now that I'm trying to implement multisite. I've tried a variety of means to get BLT to write the correct local.drushrc.php - all sites get a default, even if i use site.yml and `drush sa` is reporting correctly.

**Comment by gabe-connolly** [comment]
I am having this issue as well running BLT 8.8.5.  This is causing problems for me with trying to get my Behat tests up and running.  When I run `blt tests:behat` I get the following:

```
[warning] behat.run-server is enabled, but the server URL does not match Drupal's base URL.
[warning] project.local.uri = http://local.mysite.com
[warning] behat.server-url = http://127.0.0.1:8888
[warning] local.extensions.Behat\MinkExtension.base_url = http://local.mysite.com
[warning] Behat is not configured properly.
[warning] behat.run-server is enabled, but the server URL does not match Drupal's base URL.
[warning] project.local.uri = http://local.mysite.com
[warning] behat.server-url = http://127.0.0.1:8888
[warning] local.extensions.Behat\MinkExtension.base_url = http://local.mysite.com
[error]  Behat is not properly configured properly. Please run `blt doctor` to diagnose the issue. 
```

When I run `blt doctor` I see errors for `checkUri`, `checkDbConnection`, and `checkBehat:uri`.  I have verified that $options['uri'] exists and is set correctly in `/var/www/mysite/docroot/sites/default/local.drushrc.php` and running `drush sqlc` shows I have a successful database connection, so I am not sure why `blt doctor` is reporting those items as errors.

**Comment by laichimirum** [comment]
Hi guys, any update on this? I have the same issue

**Comment by pcsukardi** [comment]
Good day all, i am currently having an issue to get a proper working mutisite configuration using BLT 9 and i can see im not the only one. I have added the vhosts and the databases and users to `box/config.yml` ran `vagrant provision` to make the changes. I now ran `blt recipes:mutisite:init` and entered the information into the wizard. This creates a mutisite directory structure in `docroot/sites/example`. When i run `blt setup --define site=example` it is *not* installing into the secondary database i have created in DrupalVM but instead uses the default 'drupal' database. I have tried many different things based on what i have read from the online documentation but cannot seem to get a functioning multisite install with it's own proper drush alias linked to the second database. Am i missing something? Any help would be greatly appreciated, thank you.

**Comment by rickkowal** [comment]
Having same issue with BLT not reading the appropriate /[site]/settings.php file for db connection and sync directory location.   It always reads default/settings.php.    This happens for an existing (working) multisite setup as well as a newly created multisite with using the recipes:multisite:init command.    I've updated to the latest 9.x dev branch for BLT, but BLT just doesn't recognize multisite at all.

**Comment by lcatlett** [comment]
@rickkowal and @pcsukardi - the multisite command was refactored in #2997. After updating BLT, destroy your current VM and its config files with `blt recipes:drupalvm:destroy`  and then re-generate them with `blt vm`. Once you've started the new vm, run `blt recipes:multisite:init` and after installing drupal `blt setup --site=[sitename]`, the needed site directory, drush aliases, sites.php, and settings.php configuration will be dynamically generated. We have updated the docs accordingly
