### ISSUE TITLE
Example Behat test constantly overridden

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1409]
BLT provides an example Behat test that expects to see a log in link on the homepage: https://github.com/acquia/blt/blob/8.x/template/tests/behat/features/Examples.feature

However, many (most?) enterprise sites probably don't have a log in link on the homepage, so projects either have to modify or remove this test. Then every time such a project updates BLT, it gets overwritten with the stock version, which is annoying.

Seems like BLT should either make the example test more generic so it doesn't need to be modified/removed, or include it in such a way that it won't get overwritten on updates.

**Comment by grasmash** [comment]
Pretty sure we addressed this recently in #1322. Please re-open if that's not the case.

**Comment by danepowell** [comment]
I understand what's happening now, that file will not be overwritten by BLT if it currently exists, but it will be added if it doesn't exist.

In our case, we removed it completely (seems kinda weird to keep an "example" test around anyway), and that's why it was being constantly re-added.

We can probably just modify it instead of removing it though.
