### ISSUE TITLE
Behat 'pretty' colored output is eaten by BLT/Robo

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1420]
BLT version 8.8.2

When I run this command:
```
blt tests:all -y
```

I get the following output:

<img width="904" alt="screen shot 2017-04-21 at 4 05 19 pm" src="https://cloud.githubusercontent.com/assets/481677/25296160/824a4dd4-26ac-11e7-9146-5db7173d436c.png">

And I expected this to happen:

The output should be colored/tty, and the verbose output should be darker, and red/green/etc. colors should come through in the test scenarios and failures/passes.

I ran into this while testing changes for #1366 (in a container using `docker exec`), but it looks like even if I run the commands locally, or they're run inside Travis CI, all output is white, and it's really jarring, especially if there was a test failure, since it's difficult to visually identify what's an error vs. what's normal output.

**Comment by geerlingguy** [comment]
If I run the `behat` command that BLT spits out directly, then I get coloration correctly:

<img width="1122" alt="screen shot 2017-04-21 at 4 09 40 pm" src="https://cloud.githubusercontent.com/assets/481677/25296254/f7c73536-26ac-11e7-8e43-0ee9853c99c8.png">

**Comment by geerlingguy** [comment]
According to @grasmash there's already a fix for this (not sure if in 8.8.3 or 8.x right now).

**Comment by grasmash** [comment]
Yes, I believe this is resolved in 8.x
