### ISSUE TITLE
Multisite property suggestions and default/site.yml

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1423]
Alright, I tend to be long winded.. so here's my goal/request: _I would like to have BLT attempt to load (if it exists) `docroot/sites/default/site.yml` by default._

I have maybe a unique situation that lead me down the path of looking into more detail around the multisite property in BLT. I found myself just a little confused about how multisite is working. By default, `multisite.name` has a blank value when BLT starts to run. Some commands, you can set this to a single value at run time, such as "site1.example.com" and run BLT commands against JUST that site. There is also the logic that sets this property to an array of the folders in the `docroot/sites/` directory and runs commands for each site you have. I guess some of my confusion is that the property can be a mixed value.. string or array (although I know that's not all that uncommon).

Anyway any thoughts for/against moving the `multisite` property to look like:
```yml
multisite:
  target: "" # string/null, specific site or null for all
  sites: [] # array, list of sites
```

`multisite.target` defaults to blank, so command work like they do today and run against all sites. `multisite.sites` defaults to reading in sites from `docroot/sites/*` folders, but that gets set earlier and can be overridden in properties.

I don't know, maybe I need to take a step back and am thinking about this too much and suggesting too big of a change. Alternatively, could `blt.config-files.multisite` default to the `sites/default.yml` file, and only get set to the current value if `${multisite.name}` is set?

**Comment by grasmash** [comment]
I've been thinking along the same lines. I don't like `multisite.name` being mixed. I'd prefer to separate variables.

I actually recently changed this to be `multisites`, though it hasn't been released yet: https://github.com/acquia/blt/blob/8.x/src/Robo/Config/DefaultConfig.php#L23
