### ISSUE TITLE
"tests" commands suppress color output

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#1429]
Behat and PHPUnit emit red/green colored output that makes errors super easy to spot, even when skimming a long backscroll. Unfortunately, BLT swallows the color codes and reduces their output to undifferentiated white. Can we modify to preserve colored output?

**Comment by grasmash** [comment]
I believe this is already fixed in 8.x.

**Comment by grasmash** [comment]
Duplicate of #1420
