### ISSUE TITLE
project.prefix including single quotes when validating commit message

### ISSUE THREAD

**Issue by aguasingas** [acquia/blt#1438]
My system information:
* Operating system type: MacOS
* Operating system version: Sierra 10.12.4
* BLT version: 8.8.3

When I run this command:
```
g cim 'NO-0: Fixed JIRA prefix.'
```

I get the following output:
```
Error: invalid commit message! Commit messages must:
* Contain the project prefix followed by a hyphen
* Contain a ticket number followed by a colon and a space
* Be at least 15 characters long and end with a period.
Valid example: 'NO'-135: Added the new picture field to the article feature.
```
As you can see, the prefix is surrounded by single quotes. This is the value in `project.yml > project.prefix`:
```
  prefix: 'NO'
```

But I get the same result with double quotes, or no quotes at all.

**Comment by grasmash** [comment]
Please try 8.x-dev to see if #1442 has resolved the issue.
