### ISSUE TITLE
Stop creating a tests/behat/features/Examples.feature file

### ISSUE THREAD

**Issue by leonk** [acquia/blt#1441]
Is there a way to stop the creation of this file?
This test fails on our site, so every time it's added back by composer we have to manually remove it again.

Maybe we could make the file more generic to ensure it should pass on every Drupal install (our theme has removed the "Log in" line).

**Comment by grasmash** [comment]
You can just remove the content from it as a workaround.

**Comment by grasmash** [comment]
@leonk Is this workaround sufficient?

**Comment by leonk** [comment]
Not really, as the file will keep re-appearing on composer updates (we've already seen it coming back into our project repo are few times now).

If it's necessary to be there can we change it to be something more generic (e.g. just checking for a 200 response)?

**Comment by leonk** [comment]
Actually another alternative would be place this file in gitignore.

**Comment by grasmash** [comment]
Good idea!

Also, just to clarify, I was suggesting to you make it a blank file. Then `composer update` should not re-create it. But, I think your `.gitignore` solution is better.

In terms of BLT changes, I like the idea of making it a more generic test. I'd like an example test to ship with BLT.
