### ISSUE TITLE
blt setup:update:features-override-check is dependent on console window size

### ISSUE THREAD

**Issue by AMDAndy** [acquia/blt#1443]
My system information:
* Operating system type: Ubuntu 
* Operating system version: 16.10
* BLT version: 8.8.1

Output of `blt doctor`:
```
Omitted. I can provide if needed.
```

When I run this command:
```
blt setup:update:features-override-check
```

I get the following output:
```
BUILD FINISHED; 11.8506 seconds 
```

And I expected this to happen:
```
BUILD FAILED/home/andy/web/amd/./vendor/acquia/blt/phing/tasks/setup.xml:354:8: /home/andy/web/amd/./vendor/acquia/blt/phing/tasks/setup.xml:357:14: A feature in the ${bundle} bundle is overridden. You must re-export this feature to incorporate the changes.
; 11.7752 seconds
```

The features-override-check gives me a false negative but fails on Travis. If I widen my console window the test passes.
Drush is trying to fit the word "Changed" into the last column and breaking it across multiple lines. The above test tries to use grep to find the word "changed" but is failing due to this.

**Comment by grasmash** [comment]
Great catch. Will roll a fix for this issue this week.
