### ISSUE TITLE
How to configure PHPCS?

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1456]
What is the easiest way to limit PHPCS to running only on custom module or custom theme directories?

**Comment by grasmash** [comment]
Please see http://blt.readthedocs.io/en/8.x/readme/extending-blt/#validatephpcs

**Comment by grasmash** [comment]
```
To modify the behavior of the validate:phpcs target, you may override BLT's `phpcs` configuration:

        phpcs:
          filesets:
            - files.php.custom.modules
            - files.php.tests
            - files.frontend.custom.themes

The phpcs.filesets array contains references to Phing `<fileset>`s. You can remove or add your own custom filesets to the phpcs.filesets array.

The default filesets are defined in [filesets.xml](https://github.com/acquia/blt/blob/8.x/phing/tasks/filesets.xml).
```

**Comment by grasmash** [comment]
Note that with the move to Robo, you will need to refactor this approach in 8.9.

**Comment by kevinquillen** [comment]
Oh nice, that was exactly what I was after. Works now.

**Comment by justclint** [comment]
Hi, this issue seems to be along the lines of what Im trying to do. I just need to exclude a directory from phpcs and from what I can tell Id need to override one of the filesets but when viewing the docs at http://blt.readthedocs.io/en/8.x/readme/extending-blt/#adding-overriding-filesets it still a todo item.

Is there any direction you might be able to provide at this time on doing this? In case it helps, what Im specifically trying to do is add (exclude) our pattern-lab directory to files.frontend

```
  <patternset id="files.frontend">
    <exclude name="**/pattern-lab/**/*"/>
  </patternset>
```
Thanks!

**Comment by danielnitschelc** [comment]
I think this is how you do it:

In blt/project.yml, add this:

```
import: '${repo.root}/build-custom.xml'
```

And this (from https://github.com/acquia/blt/blob/8.x-release/phing/build.yml#L116):
```
phpcs:
  filesets:
    - files.php.custom.modules
    - files.php.tests
    - files.php.custom.themes
    - files.frontend.custom.themes
  haltonerror: true
  haltonwarning: true
```

Then, find the fileset that is giving you the problem (let's say its `files.php.custom.modules`) then add this to your `build-custom.xml`:
```
<project name="filesets" default="build">
  <fileset dir="${docroot}/modules/custom" id="files.php.custom.modules.myfileset">
    <patternset refid="files.php"/>
    <exclude name="**/tests/*/**" />
  </fileset>
</project>
```

Then, update your `blt/project.yml` file again, and rename `files.php.custom.modules` to `files.php.custom.modules.myfileset`.

That should be it :)

**Comment by danielnitschelc** [comment]
PS. git precommit hooks still won't work, because they use a different target and work per file. I've just skipped the per-file check, and stuck this in the `build-custom.xml`:
```
<target name="validate:phpcs:files" description="" hidden="true" depends="validate:phpcs" />
```

**Comment by justclint** [comment]
Thanks so much @danielnitschelc! That seemed to do the trick. I did find some documentation at docroot/vendor/acquia/blt/readme/extending-blt.md which did have some additional information not listed on the readthedocs site but your specific details got this working for me.

Thanks!

**Comment by brooke-heaton** [comment]
Odd - is there a reason yml and xml are intermixed in BLT - can it not process yml files?
