### ISSUE TITLE
Simplify front end file inclusion

### ISSUE THREAD

**Issue by sarahjean** [acquia/blt#146]
In filesets.xml, could we do something like this:

```
  <patternset id="files.frontend">
    <include name="js/**/*.js"/>
    <exclude name="**/vendor/**/*"/>
  </patternset>
```

So that we are going more specifically for theme js files and not ones that might exist in other folders?

**Comment by grasmash** [comment]
@sarahjean Could you be more specific? The current patternset for files.frontend is:

```
  <patternset id="files.frontend">
    <include name="**/*.js"/>
    <!-- Ignore CSS. SASS usage is expected. CSS should be compiled. -->
    <exclude name="**/*.css"/>
    <exclude name="**/bower_components/**/*"/>
    <exclude name="**/css/**"/>
    <exclude name="**/dist/**/*"/>
    <exclude name="**/lib/**/*"/>
    <exclude name="**/node_modules/**/*"/>
    <exclude name="**/styleguide/**"/>
    <exclude name="**/vendor/**/*"/>
    <exclude name="**/gulpfile.js"/>
  </patternset>
```

This is including JS and is excluding a number of common third party directories. What is your goal? What should be excluded or included and why?

**Comment by sarahjean** [comment]
@grasmash Yes, current'y it grabs any and all JS, I am suggesting that it specifically look at JS provided by the theme, in a /js or /scripts folder, that way this doesn't need to be modified to exclude JS that might be in locations other than that which might not need to conform to Drupal Coder conventions (third party libraries, additional gulp or grunt files, code in node_modules, etc...)
A specific case that came up is in addition to `<exclude name="**/gulpfile.js"/>`, there was a sub directory with gulp tasks being imported which needed to be added on. Since Drupal themes typical include a /js, /scripts, or similar folder if we specifically target that we won't need to do as many one-off excludes.

**Comment by sarahjean** [comment]
@grasmash A slightly better version:

```
  <patternset id="files.frontend">
    <include name="**/js/**/*.js"/>
    <include name="**/js/**/*.min.js"/>
    <exclude name="**/node_modules/**/*"/>
    <exclude name="**/vendor/**/*"/>
  </patternset>
```
Not excluding node_modules caused some local performance issues when trying to run `validate:phpcs`

**Comment by grasmash** [comment]
@sarahjean excluding node_modules caused issues rather than improving performance?

**Comment by grasmash** [comment]
It seems odd that we should need to exclude node_modules. Was your node_modules dir nested under a js dir?

**Comment by sarahjean** [comment]
@grasmash No, actually. I'm not sure what was happening there.

 I think bigger picture it'd be good if this list could be updated via project.yml.
