### ISSUE TITLE
Travis build fails, because it needs to import config twice, yet fails the first time around.

### ISSUE THREAD

**Issue by cosmicdreams** [acquia/blt#1470]
My system information:
Using Travis
* BLT version: 8.8.3

When I run this command:
```
drush si
drush cim
```

I get the following output:
```
workbench_moderation.moderation_state_transition.published_published.
Synchronized configuration: update core.extension.                                     [ok]
Synchronized configuration: update core.menu.static_menu_link_overrides.               [ok]
Synchronized configuration: update system.cron.                                        [ok]
Synchronized configuration: update system.site.                                        [ok]
Synchronized configuration: update system.theme.                                       [ok]
Synchronized configuration: update views.settings.                                     [ok]
Synchronized configuration: update views.view.frontpage.                               [ok]
Synchronized configuration: update lightning_roles.settings.                           [ok]
Finalizing configuration synchronization.                                              [ok]
The import failed due for the following reasons:                                    [error]
Unexpected error during import with operation delete for node.type.landing_page:
Attempt to create a field field_moderation_state that does not exist on entity
type scheduled_update.
Unexpected error during import with operation delete for node.type.page: Attempt
to create a field field_moderation_state that does not exist on entity type
scheduled_update.
Unexpected error during import with operation delete for
media_entity.bundle.video: Attempt to create a field field_moderation_state that
does not exist on entity type scheduled_update.
Unexpected error during import with operation delete for
scheduled_updates.scheduled_update_type.node_embargo: Attempt to create a field
field_moderation_state that does not exist on entity type scheduled_update.
Unexpected error during import with operation delete for
scheduled_updates.scheduled_update_type.multiple_node_embargo: Attempt to create
a field field_moderation_state that does not exist on entity type
scheduled_update.
Unexpected error during import with operation delete for
media_entity.bundle.tweet: Attempt to create a field panelizer that does not
exist on entity type node.
Unexpected error during import with operation delete for
media_entity.bundle.instagram: Attempt to create a field panelizer that does not
exist on entity type node.
Unexpected error during import with operation delete for
media_entity.bundle.image: Attempt to create a field panelizer that does not
exist on entity type node.
Unexpected error during import with operation delete for
media_entity.bundle.document: Attempt to create a field panelizer that does not
exist on entity type node.
Unexpected error during import with operation delete for contact.form.sitewide:
Attempt to create a field panelizer that does not exist on entity type node.
Unexpected error during import with operation delete for contact.form.personal:
Attempt to create a field panelizer that does not exist on entity type node.
Unexpected error during import with operation delete for
block_content.type.basic: Attempt to create a field panelizer that does not
exist on entity type node.
Unexpected error during import with operation delete for
field.field.scheduled_update.multiple_node_embargo.field_moderation_state:
Attempt to create a field field_moderation_state that does not exist on entity
type scheduled_update.
Unexpected error during import with operation delete for
field.field.node.page.panelizer: Attempt to create a field panelizer that does
not exist on entity type node.
Deleted and replaced configuration entity
"field.field.media.document.field_media_in_library"
Unexpected error during import with operation create for
field.field.media.document.field_media_in_library: Attempt to create a field
field_media_in_library that does not exist on entity type media.
Unexpected error during import with operation create for
media_entity.bundle.image: Attempt to create a field field_media_in_library that
does not exist on entity type media.
Unexpected error during import with operation create for
field.field.media.image.field_media_in_library: Attempt to create a field
field_media_in_library that does not exist on entity type media.
Unexpected error during import with operation create for
media_entity.bundle.instagram: Attempt to create a field field_media_in_library
that does not exist on entity type media.
Unexpected error during import with operation create for
field.field.media.instagram.field_media_in_library: Attempt to create a field
field_media_in_library that does not exist on entity type media.
Unexpected error during import with operation create for
media_entity.bundle.tweet: Attempt to create a field field_media_in_library that
does not exist on entity type media.
Unexpected error during import with operation create for
field.field.media.tweet.field_media_in_library: Attempt to create a field
field_media_in_library that does not exist on entity type media.
Deleted and replaced configuration entity "user.role.alert_creator"
Deleted and replaced configuration entity "user.role.alert_reviewer"
Deleted and replaced configuration entity "user.role.faq_page_creator"
Deleted and replaced configuration entity "user.role.faq_page_reviewer"
Deleted and replaced configuration entity "user.role.vendor_creator"
Deleted and replaced configuration entity "user.role.vendor_reviewer"
Unexpected error during import with operation create for
media_entity.bundle.video: Attempt to create a field field_media_in_library that
does not exist on entity type media.
Unexpected error during import with operation create for
field.field.media.video.field_media_in_library: Attempt to create a field
field_media_in_library that does not exist on entity type media.
Deleted and replaced configuration entity
"field.field.node.page.scheduled_update"
Unexpected error during import with operation create for
field.field.node.page.scheduled_update: Attempt to create a field
scheduled_update that does not exist on entity type node.
Deleted and replaced configuration entity
"core.entity_form_display.node.page.default"
Deleted and replaced configuration entity
"core.entity_form_display.media.document.default"
```

And I expected this to happen:
Import properly.

NOW, since this is travis it is also going to start with a raw database and try to use drush cim to import all the things.  Research into the blt issue queue uncovered : https://github.com/acquia/blt/pull/1398 which claims that I need to run the import twice.

But because of this error it never gets the chance.  

When I run the import twice locally (after trying to reproduce these conditions) it works for me.

**Comment by grasmash** [comment]
Are you actually running
```
drush si
drush cim
```
?

If so, then you are not using BLT's standard .travis.yml file. Running `blt travis:ci:init` will generate a default .travis.yml file for you which will properly run config import tasks. 

If you _are_ using the .travis.yml provided by BLT, then you should attempt to run the same commands locally as those that are run on Travis. This is likely `blt setup`.

**Comment by cosmicdreams** [comment]
I'm doing the drush commands locally in order to reproduce the conditions that Travis is operating under.  blt local:refresh pulls a db from dev so I only saw the problem when I sent it to travis to build.

I do have a local .travis.yml file.  I'll give blt setup a try.

**Comment by grasmash** [comment]
If I had to guess, I would say that your configuration is invalid in some way.

I might be able to help diagnose if you share the full output. However, Drupal 8 config is (in my opinion) still very problematic, and these things often require a serious deep dive.

**Comment by cosmicdreams** [comment]
I hear from my lead dev that we've already run `blt travis:ci:init`

Isn't it odd that one solution is to run the import twice?  #1398 seems to indicate that this is not an uncommon solution.  It's just a solution I'm not able to use in travis since it errors out too soon.

**Comment by cosmicdreams** [comment]
My console seems to be unableto get the full output of a blt setup to appear without cutting off a significant portion of my history.

**Comment by puglyfe** [comment]
we had a previous .travis.yml that worked without issue. in upgrading to 8.8.3, our build was failing due to the removal of the `ci:build:validate:test` task. so i regenerated the travis config with `blt travis:ci:init` and made only the minimum changes (acquia repo url, slack integration, etc).

i can confirm that running `blt setup` results in the same error we are seeing in travis, and then running a `drush cim` afterwards fixes it. but we don't have that option in travis.

here is the complete log - https://pastebin.com/LFTkQX7z

**Comment by grasmash** [comment]
@cosmicdreams The change from #1398 is present in 8.8.3. @danepowell can correct me if I'm wrong, but I believe that, even if you need to run config import twice, the first time should not produce an error. This seems to be the issue that you're encountering.

The salient difference between `local:refresh` and `setup` in this instance is that `setup` is calling `drush si` and importing config during the installation process rather than importing configuration into an existing database. It's not uncommon for these two commands to produce different results. It suggests that your configuration is invalid, it's just that BLT 8.8.3 and `blt setup` are surfacing the issue in a way that prior versions did not.

In the pull request that is failing, are you _only_ updating BLT, or are you also updating Lightning? 

@balsama Since this config import is failing on a Lightning component, can you shed any light onto the possible cause? 

Another question... what is your value for `cm.strategy`, and is it correct for your implementation?

**Comment by cosmicdreams** [comment]
I don't see cm.strategy defined.  

In the pull request that is failing we have updated both BLT / Drupal (to 8.3) / and Lightning.

**Comment by grasmash** [comment]
I'd suggest two things:

1. Update _only_ BLT or _only_ Lightning in the PR if possible. It would be best to isolate which update is causing the problem.
2. Set cm.strategy in project.yml. The fact that it isn't set is concerning and indicates that something may have gone wrong during the update process. Possible values: core-only, config-split, features, none.

**Comment by puglyfe** [comment]
in debugging this issue, i've set the `cm.strategy` to both 'config-split' and 'core-only' with no difference in the result. at this point, our config is the same across all environments, so 'core-only' probably best represents our actual strategy at this point.

i'll try to separate the updates into separate PRs and see if it makes a difference.

**Comment by danepowell** [comment]
Based on the initial description, this sounds like a corrupt configuration export.

This also looks very similar to a core bug that I discovered where Drupal refuses to delete a field if its parent storage doesn't exist. It's crazy I know; you'd think you'd be able to delete a field no matter what, but apparently Drupal is picky that way :man_shrugging:

Anyway, without a complete dump of the configuration before and after the change, it's hard to say for sure.

Since you mentioned it can be reproduced by simply running drush si / drush cim, I'm not sure how BLT would be involved. Note, however, that you might have actually had a corrupt configuration for a while now and it was only just revealed because of this Drush patch that properly catches errors during imports: https://github.com/drush-ops/drush/pull/2713

**Comment by puglyfe** [comment]
after re-reading @grasmash's earlier comment, my guess is he's spot on about skipping one (or more) of the manual steps needed to upgrade lightning. specifically, the `2.0.2 -> 2.0.3` update seems to be in the same domain as the errors we're seeing.

this is going to be sticky to untangle, but i'll start there. thanks @grasmash and @danepowell for your help.

**Comment by grasmash** [comment]
No problem! Good luck.

**Comment by balsama** [comment]
Nothing jumps out at me as a possible cause. I kind of doubt it's a skipped manual update step though. Lightning tends not to make assumptions about config after it's initial install (hence manual update steps). But it's worth a try (you'll likely want those changes anyway).

If you suspect that, and you haven't deviated too much from the config that Lightning provides, you can automate the manual update steps by enabling the hidden module `lightning_dev`.  I obviously wouldn't recommend doing so as a permanent solution, but it might be useful for troubleshooting.

You could also test Dane's theory about drush by pinning to 8.1.10 (I think #2713 was included in 8.1.11).

**Comment by puglyfe** [comment]
> You could also test Dane's theory about drush by pinning to 8.1.10 (I think #2713 was included in 8.1.11).

That was the winner! Pinning to 8.1.10 allowed the config to import "successfully".

I'm unsure how to proceed, though. Obviously that patch points out genuine configuration issues, so now I need to zero in on what the actual problem is. Any advice on where to start?

**Comment by cosmicdreams** [comment]
Most of the errors refer to scheduled updates  for various entities.  Perhaps we need to modify and save these to reset the config?  If the config were trying to push is corrupt / causing the first pass to blow up, then let's fix the config

**Comment by gabe-connolly** [comment]
@cosmicdreams were you able to find a stable way to track down the corrupt configuration settings?  Having a similar issue with `blt local:refresh` working fine, but `blt setup` or `blt local:setup` both failing on configuration import errors.

**Comment by danepowell** [comment]
I think the root cause here is https://github.com/acquia/lightning/issues/343, which is fixed by https://github.com/acquia/lightning/pull/360

Downgrading drush really only covers up the problem and isn't the best solution.

**Comment by danepowell** [comment]
Also... seems like it can be caused by a bug with Lightning config file names that was fixed in https://github.com/acquia/lightning/commit/791520feafc97ab3da60eb672887cf2b83fa458c
