### ISSUE TITLE
Execute Tests inside the VM where possible

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1472]
The recent updates to the dev branch allowing front-end and doctor to run inside the VM are spectacular!  Need it for behat too!

**Comment by grasmash** [comment]
It's kind of already there. At least, if you have DVM and try to execute tests outside of the VM, an informative exception is thrown.

**Comment by grasmash** [comment]
I'm actually considering reverting the changes to the frontend commands and taking the same approach there. I think I'd rather just emit "Please execute this command inside of Drupal VM" rather than owning the process of SSHing in and executing. 

Opinions? @aweingarten @geerlingguy

**Comment by aweingarten** [comment]
I would keep the front-end approach you introduced. It will significantly simplify training.  We can simply tell users go run `blt` to see all your commands and pick the one you need.
