### ISSUE TITLE
BLT project creation issue

### ISSUE THREAD

**Issue by avulashiva** [acquia/blt#1484]
Hi all,

While creating the project i am getting this error.

acquia/blt suggests installing hirak/prestissimo (^0.3)
Writing lock file
Generating autoload files
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
Creating BLT templated files...
 > D:/drupalvm/vendor/acquia/blt/bin/blt create-project
'D:/drupalvm/vendor/acquia/blt/bin/blt' is not recognized as an internal or external command,
operable program or batch file.

Please help me.

Thanks,
Shiva.

**Comment by grasmash** [comment]
@avulashiva It looks like you're using Windows. Have you followed the Windows-specific instructions?

http://blt.readthedocs.io/en/8.x/readme/windows-install

You can either use the Windows Subsystem for Linux on Windows 10, or else use Drupal VM by following [these instructions](http://blt.readthedocs.io/en/8.x/readme/windows-install/#using-drupal-vm). Please note that _you cannot use the standard Windows shell_:

> Use a separate PowerShell or other command line environment to manage the VM via vagrant commands.

**Comment by grasmash** [comment]
Closing due to lack of response.
