### ISSUE TITLE
Frontend linting via git commit hooks

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1486]
Currently we run PHPCS on all code committed, but we don't do anything similar for frontend code.  We have coding standards for JS, and SCSS.  We should come up with a way to easily add them to the git commit hooks.

One idea would be to add a custom hook to project.yml that can be invoked by the git commit hooks.

**Comment by grasmash** [comment]
This is already present. You can use the frontend-test target hook:
https://github.com/acquia/blt/blob/8.x/template/blt/project.yml#L49

**Comment by aweingarten** [comment]
@grasmash, it doesn't look like this is executed by the git commit hooks:
https://github.com/acquia/blt/blob/8.x/scripts/git-hooks/pre-commit

We also might want to separate the concept of linting from testing.  We do the same for the backend.  We have targets for validation and other targets for executing behat.

**Comment by nikunjkotecha** [comment]
@grasmash I've seen it working when phing was used, not able to see any code/reference of this in 8.9.x where we are using robo. This is really required to have all code validated before pushing. Can we have this back?

Note: Even the link you shared above now points to acquia_connector

**Comment by nikunjkotecha** [comment]
I tried and used the pre-commit hook in blt/project.yml, it will be nice to have something within BLT

```
target-hooks:
  pre-commit:
    dir: '${repo.root}/blt/scripts'
    command: 'bash frontend-validate.sh ${docroot}'
```

**Comment by nikunjkotecha** [comment]
Worked on a getting a proper working solution as frontend commands are now executed inside Drupal VM, see https://github.com/acquia/blt/pull/2571 for more details.
