### ISSUE TITLE
Documentation for "Automated testing using live content" referencing outdated target

### ISSUE THREAD

**Issue by aguasingas** [acquia/blt#1504]
In http://blt.readthedocs.io/en/8.x/readme/ci/#setting-up-travis-ci-for-automated-deployments we can read 

> Follow the steps in extending BLT to override the default ci:build:validate:test target:

But that target is nowhere to be found. It's not defined, and it's not called in any Travis scripts. 

I can see that it got removed from `scripts/travis/run_tests` in bef25c11d77cd3df6d46b7fb9df10f024397b542 and broken down into `validate:all`, `ci:setup` and `tests:all`

Any recommendations on how to proceed from now on? Thanks!

**Comment by grasmash** [comment]
That documentation needs to be updated. You can still override the target, but you'll need to call any `tests:*` commands with an `<exec>` task, since those targets have been ported to Robo.

```
 <!-- Override the core ci:build:validate:test target to include a local refresh-->
  <target name="ci:build:validate:test" description="Builds, validates, tests, and deploys an artifact."
    depends="validate:all, ci:setup, local:sync, local:update" />
 <exec dir="${repo.root}" command="blt tests:all" logoutput="true" passthru="true" checkreturn="true"/>
```

**Comment by grasmash** [comment]
Documentation has been updated.
