### ISSUE TITLE
Pipelines builds hang

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1511]
BLT version: 8.x head

When I attempt to run a pipelines build the build hangs on "Killing background jobs" and ultimately times out.  Removing the automated test portion of the build solves the issue.   It seems like blt is starting some process that is keeping the container open.   

Works with BLT 8.7.x

**Comment by grasmash** [comment]
@aweingarten Did you manage to find a way to kill the process in your tinkering?

**Comment by aweingarten** [comment]
@grasmash 

This seemed to work: https://linux.die.net/man/1/pkill

**Comment by grasmash** [comment]
This should be addressed by #1518.
