### ISSUE TITLE
Hi I am getting the issue while creating the BLT project 

### ISSUE THREAD

**Issue by avulashiva** [acquia/blt#1513]
Hi 
I am getting following error while installing drupal BLT. 
drupaldev: Waiting for machine to boot. This may take a few minutes...
    drupaldev: SSH address: 127.0.0.1:2222
    drupaldev: SSH username: vagrant
    drupaldev: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

Thanks
Shiva.

**Comment by grasmash** [comment]
Hi Shiva,

It appears that this is a Drupal VM issue. Your  VM is failing to boot. You'd get the most help by posting in issue in the [Drupal VM issue queue] (https://github.com/geerlingguy/drupal-vm/issues).

@geerlingguy may be able to shed light on potential causes.

**Comment by geerlingguy** [comment]
@avulashiva - I noticed the box name is `drupaldev`—did you generate a VM instance with the `blt vm` command, or did you get a VM running in some other way?

Basically, what commands led to the condition you posted in the issue summary?

**Comment by avulashiva** [comment]
Hi @geerlingguy 

I am using vagrant up to run the drupal VM.
I genrated the ssh key using putty and generated the ppk file using pagent. after i stated ssh agent. then i used vagrant up command.
https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development

Thanks,
Shiva.

**Comment by geerlingguy** [comment]
@avulashiva - Okay, in that case, can you walk me through exactly what you did that resulted in this error? E.g. did you use Cmder or some other terminal emulator? And did you download Drupal VM from GitHub directly, then expand the directory in your Windows filesystem, then create a config.yml file? And if you created a config.yml, what are the contents of that file?

**Comment by grasmash** [comment]
Closing after 2 weeks inactivity. Looks like the underlying cause is likely not BLT.
