### ISSUE TITLE
I have a generic question here.

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#1514]
After updating to the most recent version of blt, should we be ignoring the new blt/ directory in our project. My assumption is that composer will rebuild it if it doesnt exist on a composer install or composer update, but i figured I would ask you guys first before just relying on intuition.

**Comment by grasmash** [comment]
You should commit the blt directory. It will contain your project specific configuration and customizations for BLT.

**Comment by haynescw** [comment]
wait, i see what happened. The update changed my .gitignore and removed some fed folders that have tons of files in them.

**Comment by haynescw** [comment]
LOL, i should just finish my coffee and start my day over.
