### ISSUE TITLE
Possible to disable core patching?

### ISSUE THREAD

**Issue by lpeabody** [acquia/blt#1530]
This is more of a support ticket, but I'm wondering if it's possible to stop patches being applied to drupal/core during the `create-project` or `composer require` steps for integrating BLT?

**Comment by grasmash** [comment]
I think you're looking for the `patches-ignore` feature of https://github.com/cweagans/composer-patches.

**Comment by lpeabody** [comment]
@grasmash I applied the following in the project's composer.json:

```
    "patches-ignore": {
      "drupal/lightning": {
        "drupal/core": {
          "We don't want image formatters to support SVG": "https://www.drupal.org/files/issues/2652138-41.patch"
        }
      }
    }
  }
```

And ran `composer update` and core was still patched. Seems like it's bugged or I'm doing something wrong. As far as I can tell though it's accurate.
