### ISSUE TITLE
BLT Split settings missing for ODE 

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1554]
Currently BLT doesn't know which split to activate for Acquia CD's.
https://github.com/acquia/blt/blob/8.x/settings/config.settings.php#L8

The AH_SITE_ENVIRONMENT for an ODE looks like so:
```
echo $AH_SITE_ENVIRONMENT
ode9
```

Probably want to add an is_ODE which looks for odeXXX  here 
https://github.com/acquia/blt/blob/8.x/settings/blt.settings.php#L43

Guessing that ODE split should just be DEV.

**Comment by grasmash** [comment]
This is basically what the `ah_other` split is for. Any reason not to use that?
