### ISSUE TITLE
Execute the front-end tests target while the Drush Webserver is active

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1564]
As a front-end developer I want to be able to run tests against the drush webserver as part of a pipelines build.    Right now the webserver is being initiated as part of the behat task and then terminated immediately after the behat tests are run.  It can't be leveraged for front-end tasks like visual regression tests, or WCAGAA testing.  

Ideally the web-server should be left open for the front-end tests target.

**Comment by grasmash** [comment]
Eh, I'm not sure I want to do this for everyone.

What we could do is introduce a command like `blt tests:run-server` and `blt tests:kill-server` so that you can launch and kill it yourself during frontend testing. 

How's that sound?

**Comment by aweingarten** [comment]
yeah, I agree this gets messy.  How do you see tests:run-server and tests:kill-server getting invoked? Would one override the front-end tests command to add those calls?  Or did you imagine something else

**Comment by grasmash** [comment]
The front end tests command just calls a target hook. You can use that target hook to invoke a script. E.g.,

```
blt tests:run-server
# something else
blt tests:kill-server
```
