### ISSUE TITLE
Use deployment identifier to prevent problems with ApcClassLoader cache

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1568]
Drupal core uses the [Symfony ApcClassCloader](https://github.com/symfony/class-loader/blob/master/ApcClassLoader.php) (when APCu cache is available) to cache class file locations. This can create fatal errors when classes are moved or deleted, as when updating contributed modules.

For instance, I recently upgraded Config Filter from 1.0-beta3 to 1.0-rc1 by simply running `composer update drupal/config_filter` on my local install. Turns out Config Filter [removed a class file](http://cgit.drupalcode.org/config_filter/commit/?h=8.x-1.x&id=1149cfcb37d3b51311521b1451cc74dc212b0167) in this update, and the file location was still cached in my DrupalVM APCu cache, which caused the entire site to be unstable until I restarted the VM. Subsequently, the problem also occurred after deploying the update to Acquia Cloud, which required manually restarting PHP-FPM.

Fortunately, Drupal uses the deployment identifier to seed the APCu cache. Simply changing the deployment identifier when updating modules will prevent this problem. Accordingly, I propose the following changes to BLT:

1. For local installs, BLT should parse the file hash from `composer.lock` and set this as the deployment identifier. Currently, the deployment identifier isn't set at all locally.
2. For deployments, BLT should set the deployment identifier to a random value or hash on every commit. Currently, BLT only updates the deployment identifier when creating a tag.

@grasmash I'm happy to take a crack at a PR if you think this is a valid and worthwhile solution.

**Comment by grasmash** [comment]
> For local installs, BLT should parse the file hash from composer.lock and set this as the deployment identifier. 

Is it feasible that the file has will be the same if no composer dependencies have changes? E.g., what if a class is moved in a custom module. I assume that will not cause a composer hash change.

**Comment by danepowell** [comment]
If you moved a class in a custom module, then other local installs on your team would be liable to hit the APC error when they updated their code (although only if they updated while their VM was running). It's not ideal, but I'm not sure of a better way to track any arbitrary change to the codebase.

**Comment by grasmash** [comment]
@danepowell Why not simply use the commit id as the deployment identifier?

**Comment by danepowell** [comment]
I'm not sure how you could use the commit id. I hope I'm not making this more complicated than it needs to be, but this is actually a quite complex issue. Thinking both about remote deployments and local installs separately:

**For deployments**
You'd presumably want to write the deployment_identifier to disk as part of the deploy.

If you want to store it in VCS, you'd need to commit your changes, get the commit hash, then write the deployment identifier and commit _that_, which produces yet another commit. Or maybe you could amend the last commit, but I'm pretty sure that changes the hash. It's a chicken and egg problem.

I suppose you could also write it to a temporary file somewhere with a cloud hook. But simply using a random value seems more reliable.

**For local installs**
You probably _don't_ want to put the deployment identifier in the source repository, since it's going to change frequently and I could see merge conflicts being a nightmare (the same way that the composer hash is now).

Dynamically reading the last commit hash also doesn't help the situation I described, where simply running `composer update` when a contributed class file has moved can wreck your site unless you also restart apache. I guess you could dynamically read and combine the last commit hash and composer hash, and using the combination of these to form the deployment_identifier. This is probably most reliable, but it sounds awfully slow.

**Comment by wimleers** [comment]
Just wanted to say 👏  for working on `deployment_identifier` support.
