### ISSUE TITLE
Failing Behat Test Hangs Pipelines Build

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1572]
If I have a behat test that fails on pipelines it exists from BLT before terminiating the webserver and phantom which hangs the entire build.  IF behat returns a non-0 code need to handle the exception terminate the webserver, and phantom before exiting BLT.

Something like this should do the trick:
https://github.com/acquia/blt/pull/1570/files#diff-a240de0034a3c5a228b0531256268671R300

**Comment by lpeabody** [comment]
@grasmash do you know what release this fix is going to make it into? If it's not soon, do you have a recommendation for mitigating this via a custom hook?
