### ISSUE TITLE
8.9.x: How do I copy the DB into BLT for "Automated testing using live content"

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1573]
The read the docs still mention how to do this for phing.  How would I do this with ROBO?
http://blt.readthedocs.io/en/8.x/readme/ci/#automated-testing-using-live-content

**Comment by grasmash** [comment]
This is a planned feature. I'd like you to be able to choose between sync/re-install behavior by setting a value in project.yml.

**Comment by grasmash** [comment]
This is a duplicate of #1004
