### ISSUE TITLE
default/settings.php and default/settings/default.local.settings.php wiped out by update

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1577]
My system information:

Operating system type: macOS
Operating system version: 10.12.5
BLT version: 8.x-dev
Output of blt doctor:
```
$ blt doctor
Attempting to run doctor on host machine...
[Acquia\Blt\Robo\Tasks\DrushTask]  The drush command 'blt-doctor' could not be found.  Run `drush           [error]
cache-clear drush` to clear the commandfile cache if you have
installed new extensions. 
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1 
[warning] Unable to run the doctor using alias '@<site>.default.local'. Trying with '@self'...
[warning] Unable to run the doctor using alias '@self'. Trying without alias...
[error]  The drush command 'blt-doctor' could not be found.  Run `drush           [error]
cache-clear drush` to clear the commandfile cache if you have
installed new extensions. 
```

When I updated from `8.7.0-beta1` to` 8.x-dev` (`8.9.x`) my `default/settings.php` was completely replaced.

And I expected that BLT would make any required updates more delicately.

**Comment by bobbygryzynger** [comment]
I'm also seeing that this is the case with `default/settings/default.local.settings.php`.

**Comment by bobbygryzynger** [comment]
I'm seeing also that this issue cascades through all my multisites.

**Comment by grasmash** [comment]
I find that if I customize `docroot/default/settings.php` and then execute `blt setup:settings`, but settings are not overridden. Can you provide instructions to reproduce?

**Comment by bobbygryzynger** [comment]
Closing. I'm not able to reproduce this now. If it comes up again in a way that I'm able to reproduce I'll re-open.

**Comment by grasmash** [comment]
@bobbygryzynger Thanks for testing out 8.x-dev this week and filing these issues. Definitely very helpful!

**Comment by bobbygryzynger** [comment]
@grasmash no problem!
