### ISSUE TITLE
Connects to #1582: @executeInDrupalVm not respected during invokeCommand

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1589]
Connects to #1582.

BLT version: `8.9.x`

When I run:
```
blt hello:world
```
```php
class MyCommand extends BltTasks {

  /**
   * @command hello:world
   */
  public function myFunc() {
    $this->invokeCommand('hello:dvm');
  }

  /**
   * @command hello:dvm
   *
   * @executeInDrupalVm
   */
  public function dvmFunc() {
    $this->say('hello DrupalVM');
  }
  
}
```
The invoked command doesn't run within the virtual machine.

And I expected that invoking a command with the `@executeInDrupalVm` annotation would be respected no matter how the command is called.

It seems like something along these lines could be added to `invokeCommand`
```php
if ($command->getAnnotationData()->has('executeInDrupalVm')) {
  $returnCode = $this->executeCommandInDrupalVm("vendor/bin/blt $command_name");
}
else {
  $returnCode = $command->run($input, $this->output());
}
```

**Comment by grasmash** [comment]
Yeah good catch. `invokeCommand()` is currently invoking the Symfony command directly, which bypasses annotated-command.
