### ISSUE TITLE
blt to install foundational node dependencies

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#1591]
Since every project now requires node.js tooling, and node tools are a part of Drupal core development, we need a way for BLT to detect if node/npm is installed locally and also takes a list of  global node packages and installs them.

We should default project.yml to including yarn and gulp for global packages.

We should add node to blt doctor as well

**Comment by grasmash** [comment]
I'm not sure about this. I don't really like the idea of adding node dependencies to a composer package. 

What nodejs requirements are there for core? Why can't these simply be included in the theme?

**Comment by aweingarten** [comment]
Core now ships with 
- http://cgit.drupalcode.org/drupal/tree/core/package.json

Core front-end code is transpiled from .es6.js
https://www.drupal.org/node/2818825

So people will need node.js tooling for any js core development on 8.4.x and higher.  It's not in core's theme.  So that seems to take the issue outside the domain of the theme.   Ultimately node tools aren't just a concern of the theme the tools are becoming more pervasive.   There is a lot of linting for example that depends on it. We can delegate the specifics to the theme but ensuring that there is a runtime for those tests seems like a cog task.

Making sure that they actually are installed and are working is a task best accomplished with a robo command.  We could potentially add robo to cog but that seems wrong as well.  

The code that led me to this conclusion was the following in project.yml
```
 target-hooks:
   pre-commit:
    dir: '${docroot}/themes/custom/freerange'
    command: 'drush @wfm8.local ssh pwd && npm run lint
```
As well intentioned as this code is, this command would block many developers from ever merging code.  What if the VM isn't on?  What if they aren't using a VM but NPM isn't properly installed?  

Node dependencies have been one of the single biggest issues with local development.  Nearly every developer has problems with node dependencies on their machines.

**Comment by grasmash** [comment]
> people will need node.js tooling for any js core development on 8.4.x and higher

This isn't very compelling to me. If someone is already working on Drupal core front end tools, then they likely already have npm installed.

> yarn and gulp

Why these packages? It doesn't seem like BLT should force a package manager preference (npm vs yarn) or choose a front end build tool that it doesn't use (gulp).

In response to the code snippet, I'd say that the move to Robo has fixed your raised concern. We can use the `@executeInDrupalVm` tag rather than relying on a string like `drush @wfm8.local ssh pwd &&`. 

> Node dependencies have been one of the single biggest issues with local development.

Understood. However, BLT doesn't have a single node based command. Why shouldn't the tool with the node commands provide the node dependencies?

**Comment by grasmash** [comment]
@aweingarten I'm closing this issue. If you still feel strongly about it, feel free to open a new issue requesting the addition of a specific NPM package. Then we can discuss the merits of the change on a more granular level.

The current issue is too general.
