### ISSUE TITLE
Unexpected NULL results from getOutputData

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1593]
My system information:
* Operating system type: maxOS
* Operating system version: 10.12.5
* BLT version: 8.9.x

Several commands that make a call to `getOutputData` are returning `NULL` unexpectedly.
It seems that either `getMessage` should be called directly in most cases or additional setters need to be called when calling `getOutputData` as this function checks a couple of extra values before retuning the command output.

[From Robo HEAD](https://github.com/consolidation/Robo/blob/bfd2db6efabb64b03950b10f3381fbaed9c990e7/src/ResultData.php#L72):

```php
/**
 * @return null|string
 */
public function getOutputData()
{
  if (!empty($this->message) && !isset($this['already-printed']) && isset($this['provide-outputdata'])) {
    return $this->message;
  }
}
```

**Comment by grasmash** [comment]
This is due to an upstream change in Robo, and has broken many BLT things.
