### ISSUE TITLE
Drupal VM Build Failure when using deafult box/config.yml

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#161]
When I initially setup my latest dev environment using blt and drupalvm. I also, updated the box/config.yml file to include https://github.com/geerlingguy/drupal-vm/blob/master/examples/acquia/acquia.config.ym. I inserted the contents of the file to the top of my box/config.yml file. When i ran vagrant up, it fails to find php-bz2. After reviewing some google pages, i found that the extra package for ubuntu 12.04 is names bzip2 (http://www.ehow.com/how_8639332_install-bzip2-ubuntu.html). Is this the extra package that is required by phantomJS, or it there a different package that I need to install for Ubuntu 12.04 so PhantomJS will be fine?

**Comment by grasmash** [comment]
What version of PHP are you using? It is package for PHP7, which should be the default:
 http://packages.ubuntu.com/xenial/php-bz2

**Comment by haynescw** [comment]
5.6

**Comment by haynescw** [comment]
Plus the link you have there is for Ubuntu 16.04. That package doesn't exist in 12.04.

My goal is to get this working for a client that would be using the Acquia Cloud. Is there anything that we should be adding to your readme note in the section of setting up the *AMP stack for Acqui? https://github.com/acquia/blt/blob/8.x/template/readme/local-development.md#using-drupal-vm-for-blt-generated-projects
In the link above you mention "There are also other changes you can make if you choose to match the Acquia Cloud server configuration more closely" I'm trying to figure out what changes we need to make besides what is documented in DrupalVM.

**Comment by grasmash** [comment]
For 5.6, you should not include php-bz2. We can document that. However, if you'd like to use Drupal VM with the "drupal" driver for the Drupal Extension (behat), you'll need PHP to be compiled with bz2 support. Otherwise, you can simply use the 'drush' driver. 

The only additional changes that I'm aware of that would help make the VM more similar to Acquia Cloud are those listed in Drupal VM's instructions.

**Comment by haynescw** [comment]
Would making sure bz2 is compiled with php somthing is hsould be talking to @geerlingguy about with added extra to php? Or, do you have first hand experience to help me?
