### ISSUE TITLE
An alternative default.local.settings.php

### ISSUE THREAD

**Issue by simesy** [acquia/blt#1610]
BLT is clobbering the desired `docroot/sites/*/settings/local.settings.php` for my multisites whenever `blt setup:settings` runs.
https://github.com/acquia/blt/blob/8.x/src/Robo/Commands/Setup/SettingsCommand.php#L50

I want to put some localised multisite logic in the template, so I'm looking for options to do this.

Running on (8.x) HEAD 4cd3ac4730b9de359cc752e965111051f48bb8b4

**Comment by bobbygryzynger** [comment]
@simesy I was seeing this issue in #1577 but wasn't able to find a way to reproduce it. For me at least, simply running `blt setup:settings` wasn't enough to make it occur _every time_, it was more sporadic. Are you seeing it occur every time this task runs and do you have a series of steps that can reproduce it?

**Comment by grasmash** [comment]
I've reproduced it. The behavior depends on the modification date of the files being overwritten.

**Comment by simesy** [comment]
It's unfortunate that I can't specify my own template if one doesn't already exist.
