### ISSUE TITLE
 Execution of the target buildfile failed. (BLT)

### ISSUE THREAD

**Issue by jestinijames** [acquia/blt#1623]
My system information:
* Operating system type: Windows
* Operating system version: 10 (Enterprise)
* BLT version: Phing 2.15.2

Output of `blt doctor`:
```
| Check                    | Outcome                                                                         |
+--------------------------+---------------------------------------------------------------------------------+
| checkDocrootExists       | Found docroot.                                                                  |
| checkCoreExists          | Drupal core exists                                                              |
| checkSettingsFile        | BLT settings are included in settings file.                                     |
| checkLocalSettingsFile   | Found your local settings file.                                                 |
| checkLocalDrushFile      | Found your local drush settings file.                                           |
| checkUri                 | Site URI is not set                                                             |
|                          |                                                                                 |
|                          | Is $options['uri'] set correctly in                                             |
|                          | /var/www/cgi/docroot/sites/default/local.drushrc.php?                           |
|                          |                                                                                 |
| checkFileSystem:%files   | Public files directory is writable.                                             |
| checkFileSystem:%private | Private files directory is writable.                                            |
| checkFileSystem:%temp    | Temporary files directory is writable.                                          |
| checkDbConnection        | Connected to database.                                                          |
| checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                  |
| checkDrupalInstalled     | Drupal is installed.                                                            |
| checkCaching:page        | Drupal cache is disabled.                                                       |
| checkCaching:css         | CSS preprocessing is disabled.                                                  |
| checkCaching:js          | JS preprocessing is disabled.                                                   |
| checkNvmExists           | NVM does not exist.                                                             |
|                          |                                                                                 |
|                          | It is recommended that you use NVM to manage multiple versions of NodeJS on one |
|                          | machine.                                                                        |
|                          | Instructions for installing NVM can be found at:                                |
|                          |   https://github.com/creationix/nvm#installation                                |
| checkComposer:require    | acquia/blt is in composer.json's require object.                                |
| checkComposer:plugins    | hirak/prestissimo plugin for composer is installed.                             |
| checkBehat:exists        | Behat local settings file exists.                                               |
| checkBehat:uri           | base_url in tests/behat/local.yml does not match the site URI.                  |
|                          |   Behat base_url is set to "http://local.cgi.com".                              |
|                          |   Drush site URI is set to default.                                             |
| checkProjectYml:keys     | project.yml has no deprecated keys.                                             |
| checkPhpDateTimezone     | PHP setting for date.timezone is correctly set                                  |
+--------------------------+------------------------------------------------------
```

When I run this command:
```
blt local:setup
```

I get the following output:
```
Finalizing configuration synchronization.
     [ok]
The import failed due for the following reasons:
     [error]
Unexpected error during import with operation create for search_api.index.content: Field field_domain_access is unknown.
Error while sending QUERY packet. PID=12115 Statement.php:59
     [warning]
[phingcall] /var/www/cgi/./vendor/acquia/blt/phing/tasks/drupal.xml:15:10: /var/www/cgi/./vendor/acquia/blt/phing/tasks/drupal.xml:32:44: Drush exited with code 1

BUILD FAILED/var/www/cgi/./vendor/acquia/blt/phing/tasks/local-sync.xml:12:30: Execution of the target buildfile failed. Aborting.
```

And I expected this to happen:
The configuration to complete

**Comment by grasmash** [comment]
Can you please post your BLT version? You can run:

`composer info acquia/blt` to find out.

**Comment by grasmash** [comment]
It looks like the error is caused by an issue with your application. Your configuration is failing to import because your configuration is invalid. BLT is correctly failing your build.

It's tough to diagnose from without actually looking at your application, but the output suggests that the configuration for `field_domain_access` has not been properly exported.

**Comment by jestinijames** [comment]
@grasmash  composer info acquia/blt returns:
λ composer info acquia/blt
name     : acquia/blt
descrip. : BLT
keywords : automation, deployment, drupal, template, testing
versions : * 8.8.3
type     : composer-plugin
license  : GNU General Public License v2.0 only (GPL-2.0) (OSI approved) https://spdx.org/licenses/GPL-2.0.html#licenseText
source   : [git] https://github.com/acquia/blt.git bff7207e31645fe6f77e57d7b5661a732711e2d1
dist     : [zip] https://api.github.com/repos/acquia/blt/zipball/bff7207e31645fe6f77e57d7b5661a732711e2d1 bff7207e31645fe6f77e57d7b5661a732711e2d1
names    : acquia/blt

autoload
psr-4
Acquia\Blt\ => src/
Acquia\Blt\Tests\ => tests/phpunit/src/
Acquia\Blt\Tests\Robo\ => tests/phpunit/Robo/

requires
asm89/twig-lint ^1.0.2
composer-plugin-api ^1.0.0
composer/installers ^1.2.0
consolidation/robo ^1.0.6
dflydev/dot-access-data ^1.1.0
doctrine/common ^2.5
drupal/coder ^8.2.8
drush/drush ^8.1.10
grasmash/drupal-security-warning ^1.0.0
grasmash/yaml-cli ^1.0.0
grasmash/yaml-expander ^1.0.5
oomphinc/composer-installers-extender ^1.1
phing/phing ^2.15.0
php >=5.6
phpunit/phpunit ^4.8
squizlabs/php_codesniffer ^2.7
symfony/console ^2.8.11
symfony/yaml ^2.8.11
wikimedia/composer-merge-plugin ^1.3

requires (dev)
guzzlehttp/guzzle ^6.2

suggests
hirak/prestissimo ^0.3

conflicts
drupal/core 7.*


So what do you suggest I can do?

**Comment by jestinijames** [comment]
Also pasting the output when I type 'blt local:refresh' as that too outputs an error.

vagrant@local:/var/www/cgi$ blt local:refresh
blt > setup:git-hooks:
   [delete] Deleting: /var/www/cgi/.git/hooks/pre-commit
   [delete] Deleting: /var/www/cgi/.git/hooks/commit-msg
     [echo] Symlinking /var/www/cgi/.git/hooks/pre-commit to /var/www/cgi/vendor/acquia/blt/scripts/git-hooks/pre-commit
     [exec] 'pre-commit' -> '/var/www/cgi/vendor/acquia/blt/scripts/git-hooks/pre-commit'
     [exec] 'commit-msg' -> '/var/www/cgi/vendor/acquia/blt/scripts/git-hooks/commit-msg'
blt > setup:composer:install:
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
blt > setup:drupal:settings:
blt > setup:drupal:settings:site:
     [echo] Making /var/www/cgi/docroot/sites/default writable
    [chmod] Changed file mode on '/var/www/cgi/docroot/sites/default' to 755
     [echo] Making /var/www/cgi/docroot/sites/default/settings.php writable
    [chmod] Changed file mode on '/var/www/cgi/docroot/sites/default/settings.php' to 644
     [echo] Ensuring that blt.settings.php is required by settings.php
     [exec] require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";
     [echo] Generating local settings files
blt > setup:behat:
     [copy] example.local.yml omitted, is up to date
blt > frontend:setup:
blt > target-hook:invoke:
     [echo] Executing command in /var/www/cgi/docroot:
     [exec] Executing command: echo 'No frontend-setup configured.'
No frontend-setup configured.
blt > frontend:build:
blt > target-hook:invoke:
     [echo] Executing command in /var/www/cgi/docroot:
     [exec] Executing command: echo 'No frontend-build configured.'
No frontend-build configured.
blt > frontend:
blt > setup:build:
blt > target-hook:invoke:
     [echo] Executing command in /var/www/cgi/docroot:
     [exec] Executing command: echo 'No post-setup build configured.'
No post-setup build configured.
blt > local:sync:
blt > setup:drupal:settings:
blt > setup:drupal:settings:site:
     [echo] Making /var/www/cgi/docroot/sites/default writable
    [chmod] Changed file mode on '/var/www/cgi/docroot/sites/default' to 755
     [echo] Making /var/www/cgi/docroot/sites/default/settings.php writable
    [chmod] Changed file mode on '/var/www/cgi/docroot/sites/default/settings.php' to 644
     [echo] Ensuring that blt.settings.php is required by settings.php
     [exec] require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";
     [echo] Generating local settings files
blt > local:sync:db:
'drush' cache was cleared.                                                                                     [success]
Do you really want to drop all tables in the database drupal? (y/n): y
You will destroy data in drupal and replace with data from drupal.
Do you really want to continue? (y/n): y
Starting to create database on Destination.                                                                    [ok]
Creating database drupal. Any possible existing database will be dropped!
Do you really want to continue? (y/n): y
Starting to dump database on Source.                                                                           [ok]
Database dump saved to /home/vagrant/drush-backups/drupal/20170609083109/drupal_20170609_083110.sql.gz         [success]
Starting to import dump file onto Destination database.                                                        [ok]

 Starting to sanitize target database on Destination.                                                           [ok]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal.key_value' doesn't exist: SELECT 1 AS expression
FROM
{key_value} key_value
WHERE (name = :db_condition_placeholder_0) AND (collection = :db_condition_placeholder_1); Array
(
    [:db_condition_placeholder_0] => system.theme.files
    [:db_condition_placeholder_1] => state
)

'drush' cache was cleared.                                                                                     [success]
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal.key_value' doesn't exist in    [error]
/var/www/cgi/docroot/core/lib/Drupal/Core/Database/Statement.php:59
Stack trace:
#0 /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Statement.php(59): PDOStatement->execute(Array)
#1 /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Connection.php(624):
Drupal\Core\Database\Statement->execute(Array, Array)
#2 /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87):
Drupal\Core\Database\Connection->query('DELETE FROM {ke...', Array, Array)
#3 /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Query/Delete.php(55):
Drupal\Core\Database\Driver\mysql\Connection->query('DELETE FROM {ke...', Array, Array)
#4 /var/www/cgi/docroot/core/lib/Drupal/Core/KeyValueStore/DatabaseStorage.php(155):
Drupal\Core\Database\Query\Delete->execute()
#5 /var/www/cgi/docroot/core/lib/Drupal/Core/State/State.php(99):
Drupal\Core\KeyValueStore\DatabaseStorage->deleteMultiple(Array)
#6 /var/www/cgi/docroot/core/lib/Drupal/Core/State/State.php(89):
Drupal\Core\State\State->deleteMultiple(Array)
#7 /var/www/cgi/docroot/core/lib/Drupal/Core/Asset/CssCollectionOptimizer.php(176):
Drupal\Core\State\State->delete('drupal_css_cach...')
#8 /var/www/cgi/docroot/core/includes/common.inc(1092): Drupal\Core\Asset\CssCollectionOptimizer->deleteAll()
#9 /var/www/cgi/docroot/core/includes/utility.inc(52): drupal_flush_all_caches()
#10 /var/www/cgi/vendor/drush/drush/commands/core/cache.drush.inc(300):
drupal_rebuild(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\HttpFoundation\Request))
#11 /var/www/cgi/vendor/drush/drush/includes/command.inc(422): drush_cache_rebuild()
#12 /var/www/cgi/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#13 /var/www/cgi/vendor/drush/drush/includes/command.inc(199): drush_command()
#14 /var/www/cgi/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#15 /var/www/cgi/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#16 /var/www/cgi/vendor/drush/drush/drush.php(12): drush_main()
#17 {main}

Next Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table
'drupal.key_value' doesn't exist: DELETE FROM {key_value}
WHERE (name IN (:db_condition_placeholder_0)) AND (collection = :db_condition_placeholder_1); Array
(
    [:db_condition_placeholder_0] => drupal_css_cache_files
    [:db_condition_placeholder_1] => state
)
 in /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Connection.php:685
Stack trace:
#0 /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Connection.php(649):
Drupal\Core\Database\Connection->handleQueryException(Object(PDOException), 'DELETE FROM {ke...', Array, Array)
#1 /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87):
Drupal\Core\Database\Connection->query('DELETE FROM {ke...', Array, Array)
#2 /var/www/cgi/docroot/core/lib/Drupal/Core/Database/Query/Delete.php(55):
Drupal\Core\Database\Driver\mysql\Connection->query('DELETE FROM {ke...', Array, Array)
#3 /var/www/cgi/docroot/core/lib/Drupal/Core/KeyValueStore/DatabaseStorage.php(155):
Drupal\Core\Database\Query\Delete->execute()
#4 /var/www/cgi/docroot/core/lib/Drupal/Core/State/State.php(99):
Drupal\Core\KeyValueStore\DatabaseStorage->deleteMultiple(Array)
#5 /var/www/cgi/docroot/core/lib/Drupal/Core/State/State.php(89):
Drupal\Core\State\State->deleteMultiple(Array)
#6 /var/www/cgi/docroot/core/lib/Drupal/Core/Asset/CssCollectionOptimizer.php(176):
Drupal\Core\State\State->delete('drupal_css_cach...')
#7 /var/www/cgi/docroot/core/includes/common.inc(1092): Drupal\Core\Asset\CssCollectionOptimizer->deleteAll()
#8 /var/www/cgi/docroot/core/includes/utility.inc(52): drupal_flush_all_caches()
#9 /var/www/cgi/vendor/drush/drush/commands/core/cache.drush.inc(300):
drupal_rebuild(Object(Composer\Autoload\ClassLoader), Object(Symfony\Component\HttpFoundation\Request))
#10 /var/www/cgi/vendor/drush/drush/includes/command.inc(422): drush_cache_rebuild()
#11 /var/www/cgi/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#12 /var/www/cgi/vendor/drush/drush/includes/command.inc(199): drush_command()
#13 /var/www/cgi/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#14 /var/www/cgi/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 /var/www/cgi/vendor/drush/drush/drush.php(12): drush_main()
#16 {main}
[phingcall] /var/www/cgi/./vendor/acquia/blt/phing/tasks/local-sync.xml:78:67: Drush exited with code 1

BUILD FAILED/var/www/cgi/./vendor/acquia/blt/phing/tasks/local-sync.xml:20:38: Execution of the target buildfile failed. Aborting.
; 2 minutes  39.45 seconds
