### ISSUE TITLE
PHP Memory Limit Errors During Travis Builds

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1629]
During Travis builds today we started experiencing Fatal Memory errors during the Drupal installation process. 

```
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 16777216 bytes) in /home/travis/build/acquia/blt-project/vendor/symfony/dependency-injection/Compiler/ServiceReferenceGraph.php on line 92
```

This appears to be related to either a Drupal 8.3.3 update or a Drush 8.1.2 update (both of which occurred leading up to this build / failure). 

This can be worked around by upping the PHP memory limit (as outlined in this blog post: http://blog.simplytestable.com/setting-the-php-memory-limit-for-travis-ci/) 

In .travis.yml in the before_install section, add:
```
# Increase Memory Limit
  - phpenv config-add travis.php.ini
```

Then create a new file in the repo root called travis.php.ini which contains:
```
memory_limit = 1024M
```

Per @grasmash 512M may be sufficient vs. 1024M.

**Comment by cosmicdreams** [comment]
I have repetitively run into this problem.  I've attempted to increase the memory I'm telling Travis to use, but it still fails at :
PHP Fatal error:  Allowed memory size of 201326592 bytes exhausted 

Typically during config-import.

**Comment by danepowell** [comment]
@cosmicdreams what is your .travis.yml?

If the allowed memory size is 201326592 (201MB), clearly the line we added here isn't taking effect for you, or is missing. It's worked very well on our Travis instances, maybe your plan is different? Or Travis changed something.

**Comment by dpagini** [comment]
I've run into this issue too and went with a similar solution as the OP. It always seemed a bit hacky to me though...

**Comment by cosmicdreams** [comment]
@danepowell my travis file is:
`# Note that the example .travis.yml file for child projects lives in /install.
sudo: required
language: php
dist: xenial

php:
  - 5.6

matrix:
  fast_finish: true

env:
  global:
    - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
    - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
    - BUILD_DIR=$TRAVIS_BUILD_DIR

jdk:
  - oraclejdk8

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"
  - "$HOME/.nvm"
  - "vendor"
  # Cache front end dependecies to dramatically improve build time.
  # - "docroot/themes/custom/mytheme/node_modules"
  # - "docroot/themes/custom/mytheme/bower_components"

addons:
  ssh_known_hosts:
   - ded-17755.prod.hosting.acquia.com
   - svn-17778.prod.hosting.acquia.com
  chrome: stable

# @see https://docs.travis-ci.com/user/notifications
notifications:
# - hipchat: [api token]@[room id or name]
# - slack: '<account>:<token>#[channel]'

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer validate --no-check-all --ansi
  - composer install
  - npm install -g gulp
  # Exit build early if only documentation was changed in a Pull Request.
  - source ${BLT_DIR}/scripts/travis/exit_early

install:
  - source ${BLT_DIR}/scripts/travis/setup_environment
  - source ${BLT_DIR}/scripts/travis/setup_project
  - phpenv config-add travis.php.ini
  - php -ini | grep memory_limit

script:
  - source ${BLT_DIR}/scripts/travis/run_tests

# don't build feature branch unless it's tied to a PR.
branches:
  except:
    /^feature\/.*$/

deploy:
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: develop
       php: 5.6
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_branch"
     skip_cleanup: true
     on:
       branch: release/*
       php: 5.6
   - provider: script
     script: "${BLT_DIR}/scripts/travis/deploy_tag"
     skip_cleanup: true
     on:
       tags: true
       php: 5.6
`

and my travis.php.ini file is:
`memory_limit = -1`

You may note that I asking travis to output what php sets the memory limit as and it dutifully reports that the memory limit is set to -1

But I still get the error.

Also note that I've tried various ways of setting the memory limit or setting the memory limit to 2G

**Comment by danepowell** [comment]
As you've noted, it looks like your Travis file is working as expected and setting the memory limit correctly, but something else is reverting or overriding your change. I'm not sure what that would be. There's certainly nothing in BLT that sets the memory limit except for the setup_environment Travis script.

You could sprinkle a few more `php -ini | grep memory_limit` lines throughout your Travis file or test scripts to try to narrow down what's restricting your memory limit.

If this persists and you think it's caused by BLT, it would probably be better to open a new issue rather than continuing to work on a closed one. Thanks!

**Comment by cosmicdreams** [comment]
Cool, thanks @danepowell
