### ISSUE TITLE
Connects to #1528: BLT's merged dependencies not installed during deploy

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1634]
My system information:
* Operating system type: macOS
* Operating system version: `10.12.5`
* BLT version: `8.8.4`

This issue is following-up on #1528. 

I've seen this occur now with `drupal/config_split` - although it's difficult to reproduce. The basic outlines of the issue are that it seems _sometimes_ if you don't declare one of BLT's [required composer dependencies](https://github.com/acquia/blt/blob/8.8.4/composer.required.json) in your own `composer.json` that dependency doesn't get built into your deployment artifact. 

These are the `merge-plugin` settings from my project's composer.json:
```json
  "merge-plugin": {
    "require": [
      "vendor/acquia/blt/composer.required.json"
    ],
    "merge-extra": true,
    "merge-extra-deep": true,
    "merge-scripts": true,
    "include": [
      "blt/composer.overrides.json"
    ],
    "replace": true
  }
```

This is occurring despite the dependency appearing in the both `composer.lock` and `deploy/composer.lock`. 

The only workaround I have found that appears to work consistently is adding all dependencies my project depends on to my project's own `composer.json` - regardless of whether or not they appear in BLT's [composer.required.json](https://github.com/acquia/blt/blob/8.8.4/composer.required.json).

In general, I'm seeing inconsistent behavior from the plugin. At what point should merges occur? During every `composer require`? Only during `blt update`? Is there a way to trigger the merge behavior manually?

The [project's documentation](https://github.com/wikimedia/composer-merge-plugin) says:
> When Composer is run it will parse these files and merge their configuration settings into the base configuration.

But it's not quite clear on if this means all composer commands or only specific ones.

**Comment by bobbygryzynger** [comment]
Some other odd behavior I was seeing is that if I go to install a new module: `composer require drupal/module_name` I will get errors related to it not being able to be found on `packagist.org`. 

The only way I was able to resolve this was by adding the following to my own project's `composer.json` (despite this also appearing in `composer.required.json`):
```json
  "repositories": {
    "drupal": {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
    }
  }
```

**Comment by greylabel** [comment]
I think `repositories` definitions need to be in the root composer.json. I have run into a similar thing with other private repo definitions.

**Comment by bobbygryzynger** [comment]
@greylabel actually the project's documentation states this is one of the keys it is supposed to be able to merge. 

> The following sections of the found configuration files will be merged into the Composer root package configuration as though they were directly included in the top-level composer.json file:

autoload
autoload-dev (optional, see merge-dev below)
conflict
provide
replace
repositories
require
require-dev (optional, see merge-dev below)
suggest
extra (optional, see merge-extra below)
scripts (optional, see merge-scripts below)

**Comment by grasmash** [comment]
Can you post steps to reproduce this?

**Comment by bobbygryzynger** [comment]
@grasmash the issue with the `repositories` key brought up above (while not the original issue) is pretty easy to reproduce.

If I remove the `repositories` key from my project's `composer.json` and then run `composer run-script nuke`, composer will fail on the reinstall with messages like:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/acquia_connector could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package drupal/components could not be found in any version, there may be a typo in the package name.
...
```

Since the `repositories` key isn't even part of `composer.lock`, I would have thought that the merge plugin would be handling this behind the scenes and would be using the `repositories` entry from `composer.required.json`.

The issue with packages not being installed is apparently more subtle and at this point I don't have a set of reproducible steps that will always make it occur.

**Comment by bobbygryzynger** [comment]
@grasmash I'm struggling to come up with steps to reproduce this. If this is a real issue at all, then it doesn't appear consistently insofar as I can tell. I'm going to close this for now. I'll open another issue if I see this again and can come up with some reproducible steps.
