### ISSUE TITLE
Git PHPUnit tests take a reeeeally long time

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#166]
I'm seeing the `GitTasksTest`, especially `GitTasksTest::testGitHookCommitMsg`, take up to 6 minutes to run on Travis. It seems to especially hang on or after this line:

`Executing "git commit --amend -m 'ABC-123: This is a bad commit' 2>&1"`

(where ABC is my project abbreviation)

This is happening pretty consistently as of late. Not sure why that would be.

**Comment by grasmash** [comment]
No idea.

I've tried refactoring our approach here to use `--dry-run`, but that doesn't actually run validation. We could stage files and then manually run them through the `commit-msg` script, but I've avoided that because it seems clunky.

**Comment by grasmash** [comment]
Actually manually calling `commit-msg` might be pretty easy. It only seems to take one argument: the commit message. So we could execute `.git/hooks/commit-msg $commit_msg` I suppose.
