### ISSUE TITLE
Document ACSF Project Configuration and Deployment

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#1666]
The acsf setup documentation should be expanded to cover other common ACSF BLT project setup tasks such as using features for config mangement, deployment, and an overview of cloud hooks / factory hooks.

**Comment by danepowell** [comment]
Configuration management using Features: https://github.com/acquia/blt/blob/8.x/readme/configuration-management.md#features-based-workflow

Although I think even for ACSF a lot of us would like to ditch Features, especially after [this announcement](https://www.phase2technology.com/blog/stop-using-features-guide-drupal-8-configuration-management).

ACSF general setup and deployment: https://github.com/acquia/blt/blob/8.x/readme/acsf-setup.md

I'm not aware of any special considerations around deploying code to ACSF.

Obviously how to use Cloud Hooks and Factory Hooks needs to be better documented, although we should make sure that the appropriate documentation lives on Acquia.com before adding any supplementary materials to BLT.

**Comment by grasmash** [comment]
@lcatlett What additional docs are needed?

**Comment by grasmash** [comment]
@lcatlett should this issue remain open?

**Comment by grasmash** [comment]
Closing this due to a lack of clear requirements.
