### ISSUE TITLE
Travis times out with large database

### ISSUE THREAD

**Issue by AMDAndy** [acquia/blt#1673]
My system information:
* Operating system type: Ubuntu Linux
* Operating system version: 16.4
* BLT version:  8.8.1

When I run this command:
```
Travis runs "travis_wait blt ci:setup -Dcreate_alias=false"
```

I get the following output:
```
Still running (20 of 20): blt ci:setup -Dcreate_alias=false
Timeout (20 minutes) reached. Terminating "blt ci:setup -Dcreate_alias=false"
```

And I expected this to happen:
Build does not time out and completes successfully.

Note: Our database is about a gigabyte currently. The database dump and import is what is taking a long time. We already increased the timeout with travis_wait and it is now failing again.

**Comment by grasmash** [comment]
BLT does not currently have an option to dump and import during a build. Are you using a custom task?

If the root cause is the size of the DB, then I'd recommend trimming your db. Do you really need that much data? Can you truncate some of the db tables, like caches, form submissions, user fields, etc?

**Comment by AMDAndy** [comment]
I believe under all that BLT is running anything custom. The above command triggers blt local:sync:db which is what's taking a very long time.

The database is so large because the paragraph revisions table (paragraph_revision__field_paragraph_text) is 397MB (which is a whole different problem.)

**Comment by aweingarten** [comment]
@AMDAndy you might try adding some cloudhooks to trim the DB when you pull it from prod to say stage, or another acquia ENV.  Then you can pull a lean trimmed copy of the DB from there for your CI needs.

**Comment by AMDAndy** [comment]
That's funny, we were just talking about doing something like that and mulling what the problems could be with ditching Paragraph revisions.

**Comment by grasmash** [comment]
Even better than that, I'd suggest using drush's `structure-tables-key` to actually prevent the syncing of data from specific tables. That will be faster than syncing the full db and then truncating.

**Comment by grasmash** [comment]
I'm pretty sure that `ci:setup` should not trigger `local:sync:db`. That seems like a customization.

**Comment by AMDAndy** [comment]
Would you people please get out of my head?
`  'source-command-specific' => array(
    'sql-dump' => array(
      'structure-tables-key' => 'common',
      'structure-tables' => array(
        // You can add more tables which contain data to be ignored by the database dump
        'common' => array('cache*', 'history', 'sessions', 'watchdog', 'paragraph_revision*', 'node_revision__field_paragraph_container'),
      ),
    ),
  ),
`

**Comment by AMDAndy** [comment]
BTW, thanks for the pointers even if I got there like, two seconds before you posted them. It's still very helpful to know I'm heading in the right direction. Excluding these revisions table reduces the database to 10% of the normal size.
