### ISSUE TITLE
setup commands not using multisite param

### ISSUE THREAD

**Issue by simesy** [acquia/blt#1676]
As a dev I want to use the -Dsite=blah switch to run commands.

When I run some commands like `blt setup -Dsite=foo` and `blt setup:drupal:install -Dsite=foo` I'm seeing `--uri=default` in the drush commands.

Looking here it seems to get the multisite config value, and then ignore it.
https://github.com/acquia/blt/blob/8.x/src/Robo/Commands/Setup/BuildCommand.php#L23-L29

**Comment by grasmash** [comment]
The correct syntax would be 

`blt setup -Dsite=foo`. With Robo, you need a space after the `-D`.

**Comment by grasmash** [comment]
You'll need to pass drush.uri as well.

**Comment by grasmash** [comment]
I believe this is resolved in 8.x via #1691

**Comment by simesy** [comment]
Confirmed fixed, thanks
