### ISSUE TITLE
Behat Tests Fail

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1681]
My system information:
* Operating system type: Mac OS
* Operating system version: 10.11.6
* BLT version: 8.9.x dev

When I run this command:
```
blt tests:all
blt tests:behat
```

I get the following output:
```
Executing command blt tests:behat  --define drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
[Testing\Behat] Running behat  --format pretty /vagrant/tests/behat --colors --no-interaction --stop-on-failure --strict --config /vagrant/tests/behat/local.yml --profile local --tags '~ajax&&~experimental&&~lightningextension' -v

PHP Fatal error:  Cannot redeclare composerRequire50aaad88ede7074a839163f1fb337cad() (previously declared in /vagrant/vendor/composer/autoload_real.php:63) in /var/www/<project>/vendor/composer/autoload_real.php on line 70

Fatal error: Cannot redeclare composerRequire50aaad88ede7074a839163f1fb337cad() (previously declared in /vagrant/vendor/composer/autoload_real.php:63) in /var/www/<project>/vendor/composer/autoload_real.php on line 70
[Testing\Behat]  Exit code 255 
[error]  Behat tests failed! 
```

And I expected this to happen:

**Comment by mikemadison13** [comment]
@geerlingguy FYI this seems to be an issue with an interaction between BLT and Vagrant... what @grasmash and I are seeing is that the tests work fine "inside" the VM but when attempting to run outside for some reason things are looking in /vagrant (and when I do a vagrant exec pwd it also points at /vagrant instead of my repo root inside the vm).

I just re-provisioned with a ssh_home variable in box/config.yml... any thoughts on what else might be going on here?

**Comment by typhonius** [comment]
The documentation here: http://docs.drupalvm.com/en/latest/extras/drupal-console/#remote-command-execution-using-vagrant-exec works when I manually create a Vagrantfile.local. With this in mind, should BLT create a Vagrantfile.local with this config during one of the settings phases?

**Comment by grasmash** [comment]
@geerlingguy Would you consider adding such setting to Drupal VM?

**Comment by geerlingguy** [comment]
I would rather go the route @typhonius recommends — see my notes in upstream PR https://github.com/geerlingguy/drupal-vm/pull/1435

**Comment by geerlingguy** [comment]
Wouldn't it just be a matter of using the path `/var/www/${project.machine_name}` since that's what's hardcoded and set by BLT here? https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/config.yml#L15-L20

Also, you may be able to set the values in the already-existing https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/Vagrantfile (instead of having to also write a Vagrantfile.local).

**Comment by geerlingguy** [comment]
See PR https://github.com/acquia/blt/pull/1688 — needs work, and I didn't test it, but I think that should be how it's set up in BLT.
