### ISSUE TITLE
Bolt should allow deployment of tags not just branches

### ISSUE THREAD

**Issue by kylebrowning** [acquia/blt#17]
When working with ACSF, and not ACE, its difficult to tell if the branch you just pushed got the latest changes, or a hot fix was actually supplied. 

It would be awesome if Bolt could deploy tags to circumvent this issue.

**Comment by grasmash** [comment]
like so `./bolt.sh deploy:artifact -Ddeploy.tag=1.023.43t -Ddeploy.commitMsg='Kyles testing ACSF.'`

**Comment by grasmash** [comment]
This is likely going to be refactored such that it does not do any git operations at all. I will attempt to leave legacy functionality in place for Travis users, but when we switch to use Acquia Pipelines the git operations will be handled for us.

**Comment by grasmash** [comment]
Closing in favor of #830, which includes a plan for implementation.
