### ISSUE TITLE
Database synchronization should not execute cache-clear

### ISSUE THREAD

**Issue by amcgowanca** [acquia/blt#1701]
I've encountered a scenario which may be a one-off case, but I doubt it. Currently, when the command `blt local:sync:db` is executed the cache-rebuild is invoked _after_ the database sync occurs. This may potentially result in errors for hooks that are executed on rebuilds that utilize not yet enabled modules and their respective implementations. I believe this particular scenario would _only_ happen a site is in fact under active development.

In my particular case, a `common` module that is used to contain all common functionality of the site has had local changes that are not yet deployed that take effect on a cache clear - such as a new implementation of `hook_entity_type_alter()`. In particular, the issue that arises is when my implementation `hook_entity_type_alter()` attempts to set new storage handler classes for various entities but the providing module of the storage handling classes is not yet enabled which would traditionally be done through a database update. The only way to currently mitigate the errors that are presented as a result of the cache rebuild is to check if the module exists.

**Comment by grasmash** [comment]
Hm, yeah. The cache rebuild should probably be in a higher level command, like local:refresh, but not in local:sync:db itself. That would allow you to circumvent errors in this edge case.
