### ISSUE TITLE
Support for other Composer packages wanting to add their own Robo BLT commands?

### ISSUE THREAD

**Issue by lpeabody** [acquia/blt#1706]
Just wondering if there is a way for BLT to support custom Robo commands supplied by other Composer packages? If there isn't a way currently, do you have a suggested way?

For example, I'm putting together a build system and would like to leverage BLT to do so. We're building a Composer package which serves as the mechanism for providing build capabilities on a per-project basis. Some of these would include running custom Robo commands to aid in the build process, and the idea is to go through BLT so you get access to all of the configuration stored in project.yml and project.local.yml.

**Comment by grasmash** [comment]
I believe that you can do this with core Robo functionality, see [Extending Robo](http://robo.li/extending/).

**Comment by lpeabody** [comment]
@grasmash I'm just getting back around to this. The idea would be to run something along the lines of:

```
blt clientnamespace:pre-deploy
blt clientnamespace:post-deploy
```

So, the commands would be run through the `blt` command. Right now, Acquia\Blt\Robo\Blt.php looks like it only searches in very specific places for command files. I need to essentially add in my own discovery locations to your list, but it's not obvious to me how to achieve this with the Extending Robo link you dropped in above.
