### ISSUE TITLE
BLT @executeInDrupalVm needs repo root.

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1709]
I think this is a valid bug...?

So `Acquia\Blt\Robo\Commands\Blt\DoctorCommand` is working correctly for me and running inside my VM. I believe this is because line ~72-81 build a command that `cd`'s into the repo root, and runs a drush command.

`$ blt tests:all` does not seem to be working for me locally as it is running a command in the vm... the command looks to be "blt tests [...]", but it is failing. It's wrapped in `$ vagrant exec --tty 'blt tests [...]` and I'm getting back "bash: blt: command not found". If I simply run `$ vagrant exec --tty 'pwd'` I can see that vagrant exec is running these commands in my home folder, not my project root, so it makes sense BLT is not found.

I think a fix here is to ensure that all commands that run inside the VM get run from the project root, maybe in the same way the BLT doctor command is building that command...?

Also, line ~44 of `blt/CommandEventHook.php` calls the command with `drush.alias=self` but shouldn't this somehow still be configurable? What if you have a multisite? I guess maybe most of the commands calling this may not be site specific, so maybe it's less of a big deal....

**Comment by grasmash** [comment]
You shouldn't need to be in the project root in order to find the blt command. The DVM post provision script should make the blt alias available in the VM:
https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/config.yml#L80

Additionally, BLT's default Vagrantfile does ensure that `vagrant exec` executes commands in the project root:

https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/Vagrantfile#L18

It seems like you may need to execute `blt vm:config` to pull in new default configuration.

**Comment by grasmash** [comment]
I've opened #1713, which will display information regarding manual update steps. This will inform other users that `blt vm:config` needs to be executed to pull in some new default VM configuration.

**Comment by dpagini** [comment]
Great thanks... yeah, I definitely missed the `Vagrantfile` update. That fixed half my issue. My command is now correctly running in my repo root, but **blt** it says is not found. If I simply `$ vagrant ssh` and run `$ blt` it runs successfully, but not from the "vagrant exec" command.

From the host:
```ssh
$ vagrant exec 'pwd;blt'
/var/www/platform
bash: blt: command not found
```

**Comment by grasmash** [comment]
Do you have the post provision script in your config.yml? You may need to re-provision. 

Can you check the user in the VM via `whoami`? Should check both `vagrant ssh` and `vagrant exec` contexts.

**Comment by dpagini** [comment]
> Can you check the user in the VM via whoami? Should check both vagrant ssh and vagrant exec contexts.

both return "vagrant"

**Comment by dpagini** [comment]
For posterity sake...
I blew up my VM and rebuilt, and the `vagrant exec` command is working as intended now. That was definitely odd behavior and I'm not sure what would have happened...?

Thanks again @grasmash for your suggestions...
