### ISSUE TITLE
Potential problem with "--define" syntax?

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1711]
Scenario...

I'm looking at the `blt/scripts/travis/run_tests` file to try and debug some of my Travis issues, and have honed in just a little bit on the `$ blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --yes -v` line.

Should I be able to run this locally? It seems to me like the "${drush.aliases.ci}" piece is getting ignored completely. My setting for `drush.aliases.ci` is "self" currently. 
Here is my attempt to run two commands locally:
```sh
$ blt setup:toggle-modules --define drush.alias='${drush.aliases.ci}'
[Acquia\Blt\Robo\Tasks\DrushTask] Running /Users/dpagini/Projects/Websites/platform/vendor/bin/drush @platform.vm pm-enable --skip dblog devel field_ui features_ui page_manager_ui seckit stage_file_proxy views_ui webform_ui --uri=default --yes
```

```sh
$ blt setup:toggle-modules --define drush.alias=self
[Acquia\Blt\Robo\Tasks\DrushTask] Running /Users/dpagini/Projects/Websites/platform/vendor/bin/drush @self pm-enable --skip dblog devel field_ui features_ui page_manager_ui seckit stage_file_proxy views_ui webform_ui --uri=default --ye
```

Should that first command pickup the value of `drush.aliases.ci`? Is there any reason Travis would be able to get that value, but I wouldn't get it locally?

_Note: I only chose "setup:toggle-modules" b/c it was a command that ran fast that I knew used the value of `drush.alias`._

**Comment by grasmash** [comment]
Hm. I cannot reproduce your issue. When I set drush.aliases.ci to `dpagini` and run `blt setup:toggle-modules --define drush.alias='${drush.aliases.ci}'`
I see:

```
Running /Users/matthew.grasmick/Sites/acquia/blted8/vendor/bin/drush @dpagini pm-enable --skip dblog devel seckit views_ui --uri=default --yes in /Users/matthew.grasmick/Sites/acquia/blted8/docroot
```

**Comment by grasmash** [comment]
What is your PHP version and what shell are you running?

**Comment by dpagini** [comment]
Hmm... odd. Ok, I will keep debugging myself then. 

```
$ php -v
PHP 5.6.21 (cli) (built: May 24 2016 23:20:56) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

bash? MacOSX Terminal. 

When I `$ vagrant ssh` into my Drupal-VM (running PHP7) and run that command, I get the same output... using the default drush.alias and not the calculated one. Odd.

**Comment by grasmash** [comment]
Hm. Yeah bash on OSX is what I'm running too.

I downgraded to PHP 5.6.28 and it's still working for me so I don't think that's it either.

**Comment by grasmash** [comment]
I've opened #1714 to help you debug this problem. It introduces the `config:get` and `config:dump` commands which you can use to check the value of `drush.aliases.ci`.

**Comment by dpagini** [comment]
Ugh, FML. Sorry. `blt/project.local.yml` strikes again. I don't know why `drush.aliases.ci` on there was set to my VM alias, but that was my problem. Thanks for your help!
