### ISSUE TITLE
Robo feature request: total "setup" time

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1719]
I think Phing had this... at the end of a `$ blt local:setup` you would see the amount of time it took to build the project.

Obviously low priority, but I really liked seeing that just as a benchmark. I know Robo now tells you how long each step takes, but it would be cool to see the aggregate at the end.

**Comment by grasmash** [comment]
Would you be ok adding this only in verbose output?

**Comment by dpagini** [comment]
Little late to the game here... I honestly don't have a strong opinion either way. That works for me. It was just something I noticed was missing from the move to Robo, so I added the bug. Thanks for humoring my request.  =)
