### ISSUE TITLE
Help Requested: Travis chrome behat setup

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1722]
My system information:
* Environment: Travis
* BLT version: 8.9.0-beta5

Attempting to switch to Travis chrome behat testing. I tried comparing my build output to the default Travis output of this repo's travis testing, and it seems to differ and I can't figure out why. I see the code is calling `blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --yes -v` via the `run_tests` script, and that `tests.run-server: true` flag is used in the `@launchWebServer` hook and `launchWebServer()` method. Any ideas/guesses at why my webserver isnt starting and getting a response? Is it configured properly with that port? Any debugging hints I can try in anyone's experiences? Any help appreciated!

<img width="859" alt="screen shot 2017-06-23 at 9 43 26 am" src="https://user-images.githubusercontent.com/1724163/27484772-78731674-57f8-11e7-9035-f6acf345a586.png">

**Comment by simesy** [comment]
Not sure if it is helpful, but behat tests in beta5 are broken for me as well. I think the shift to chrome driver has some loose ends.

**Comment by grasmash** [comment]
Try this:

```
rm tests/behat/local.yml
rm tests/behat/example.local.yml
blt update
blt tests:behat
```

This should re-generated your Behat config files. 

I'd like to somehow add this process to the upgrade path, but I seems like it could be unintentionally destructive. Some people may not want these files re-generated for them.

**Comment by dpagini** [comment]
Hmm... no luck for me, I'm still getting the exact same output as the screen above. I deleted my old `tests/behat/behat.yml` file as well, and copied over the one from the BLT template directory. It regenerated both my local files. Everything runs for me locally, but on Travis it just doesn't seem to want to start this server.

**Comment by grasmash** [comment]
@dpagini Did you re-generate your .travis.yml too?

**Comment by dpagini** [comment]
Yes, I have the most up-to-date `.travis.yml` file as well.  =/

**Comment by grasmash** [comment]
Actually, this doesn't look Chrome related. It's not ever getting a response from the server.

**Comment by dpagini** [comment]
Yeah, that makes sense to me... I guess it's part of my update to this chrome behat testing. I'm upgrading from 8.6.14. Is there an easy way to turn on more debugging in Travis? Should `$ drush runserver` be returning any values at all?

**Comment by simesy** [comment]
@dpagini there's a "run build in debug mode" in travis, you can then ssh in, and then run subsequent build steps until you hit the problem. I find Travis kicks me out before I get to that point, haven't had time to check why.

**Comment by grasmash** [comment]
I've reverted the default web driver to chrome so that this issue doesn't block the 8.9.0 release. I'm considering Chrome integration experimental for the time being. See #1729

**Comment by dpagini** [comment]
The "web driver" is not related to this though, right? This is still just trying to stand up a local web server? 
I've had the same experiences as @simesy with debugging. I'll give it a try later though and report my results.

**Comment by dpagini** [comment]
Hmmm... OK.
@simesy I think I figured out the exit thing. Anytime `set -e` is run on Travis, it exits the build completely when an exit code is received. You want to make sure you run `$ set +e`, and also make sure you don't run any BLT file's that have the "set -e" command in them (such as "run_tests" script).

Anyways, I think the issue I'm running into is below...
WebServerHook.php
```
      /** @var \Acquia\Blt\Robo\Common\Executor $executor */
      $executor = $this->getContainer()->get('executor');
      $result = $executor
        ->drush("runserver $this->serverUrl &> $log_file")
        ->background(TRUE)
        ->run();
```

I am able to get past the stuck webserver by removing the "&> $log_file" line. Why? Not 100% sure at this point in time... Maybe there's some file permission issues going on? In fact, if I skip (comment out) the file system block immediately above this line, and just print to the log file at `/tmp/runserver.log`, my webserver will start up. If I use the file system block and use this "$log_file" then I get the timeout.

@grasmash any ideas what could be going on here? I should also point out that no matter where I set the output to go to, my file ends up completely empty.

**Comment by simesy** [comment]
@dpagini thanks for the -e tip!

FYI in theory beta6 should just roll you back to the previous solution where you don't need to do the runserver thing.

**Comment by dpagini** [comment]
I'm still confused on the "runserver" thing though... isnt that just to set up a webserver on Travis? I would need that no matter which web driver I am using, no?

**Comment by grasmash** [comment]
@dpagini You are correct. This is not related to the web driver. That was my incorrect assumption.

**Comment by dpagini** [comment]
Thanks. Do you think this `$log_file` thing might be a bug, or am I the only one this is happening to?

**Comment by grasmash** [comment]
@dpagini It seems like for some reason, the command syntax may work on OSX but not on Travis' Linux containers. We should play around with it a bit.

**Comment by grasmash** [comment]
Something like this: #1736

**Comment by dpagini** [comment]
Woohoo!
Ok, that patch helped me get past the timeout. I'm getting a PHP error now though, and I realized it's b/c my `frontend:build` is not taking place.
Any reason that is [commented out](https://github.com/acquia/blt/blob/8.x/src/Robo/Commands/Setup/BuildCommand.php#L101) currently @grasmash?

**Comment by grasmash** [comment]
Hm. That might just be an oversight.
