### ISSUE TITLE
Update config split docs

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#1755]
I followed these docs myself and found a few gaps.

* We should indicate that each split needs to be created via the Config Split UI. E.g., let's walk a user through creating the "local" config split, setting the correct directory, etc.
* It was my understanding that only overridden config would be exported to a split, but following the directions leads to all config being exported to a local split. Maybe I'm doing it wrong, or maybe we should set expectations around this.
* Does blacklisting a module automatically blacklist all of its config, or does specific config need to be blacklisted also? The example of "Stage File Proxy" suggests that you need both.
* On my local machine, the local config split reads "inactive (overwritten)" under status. Is this to be expected?

**Comment by grasmash** [comment]
To create the local split:

1. Create a split with name "local"
1. Set dir to "../config/local"
1. Execute `drush config-export`
1. Modify split, define blacklists
1. Export split `drush csex local`

**Comment by snize** [comment]
1. Create a split with name "local"
2. Set dir to "../config/local"
3. Untick `Active` in `/admin/config/development/configuration/config-split/local/edit`. Those are defined in  `/vendor/acquia/blt/settings/config.settings.php`
4. Execute `drush config-export` to export the config for the split itself
5. Modify split, define blacklists
6. Export split with `drush config-export`. No longer to use `drush csex local`

This is a config-split demo repository using blt. https://github.com/snize/demo-config-split/commits/master
The commit message corresponds to the commit content. I hope this helps.
