### ISSUE TITLE
unable to create blt new project

### ISSUE THREAD

**Issue by sjayanths** [acquia/blt#1772]
My system information:
* Operating system type: Mac
* Operating system version: 10.12.5
* BLT version: I don't know

I ran the following command to create a new project.
composer create-project --no-interaction acquia/blt-project drupal

Part of the follwing output is this.

Installing guzzlehttp/guzzle (6.3.0): Loading from cache
 ```
 - Installing egulias/email-validator (1.2.14): Loading from cache
  - Installing easyrdf/easyrdf (0.9.1): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing asm89/stack-cors (1.1.0): Loading from cache
  - Installing symfony/validator (v2.8.24): Loading from cache
  - Installing symfony/serializer (v2.8.24): Loading from cache
  - Updating symfony/process (v3.3.4 => v2.8.24): Loading from cache
  - Installing symfony/dependency-injection (v2.8.24): Loading from cache
  - Installing symfony/polyfill-apcu (v1.4.0): Loading from cache
  - Installing symfony/class-loader (v2.8.24): Loading from cache
  - Installing drupal/core (8.3.5): Loading from cache
```
But it stopped here and showing time out error.

**Comment by sjayanths** [comment]
how to restart this, in case of any issue in the middle?

**Comment by grasmash** [comment]
Seems like this is just an issue with Composer timing out. Maybe you should increase your timeout?  Is there an error message? 


As [documented](http://blt.readthedocs.io/en/8.x/readme/creating-new-project/), you can increase the Composer timeout:

```
export COMPOSER_PROCESS_TIMEOUT=2000
```

**Comment by grasmash** [comment]
Please re-open if these do not address your issue.

**Comment by sjayanths** [comment]
i set the time out to 1,20,000, but it seems it is not taking that setting. still getting time out errors.
<img width="581" alt="screen shot 2017-07-07 at 9 47 21 pm" src="https://user-images.githubusercontent.com/5356459/27966741-ff740a1e-635d-11e7-91be-865ca6681832.png">

**Comment by sjayanths** [comment]
i set using 
export COMPOSER_PROCESS_TIMEOUT=120000

**Comment by sjayanths** [comment]
can you please reopen the issue?

**Comment by grasmash** [comment]
I think all I can do for you is increase the timeout. BLT can't affect the download speed of your composer packages.
