### ISSUE TITLE
Cannot install BLT 8.9.0 with Reservoir

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1792]
I'm using BLT with a [Reservoir](https://github.com/acquia/reservoir)-based project.

Reservoir requires `webflo/drupal-core-strict`, which in turn pins `wikimedia/composer-merge-plugin` to v1.4.0: https://github.com/webflo/drupal-core-strict/blob/8.3.5/composer.json#L48

BLT 8.9.0, however, requires `wikimedia/composer-merge-plugin` version dev-master: https://github.com/acquia/blt/blob/8.x/composer.json#L33

I'm not sure what the best way (or any way) to resolve this conflict. It seems to me that using `webflo/drupal-core-strict` is a one-way ticket to dependency hell, and Reservoir might want to consider dropping it. But I'm wondering what other folks think, or if there's a way to solve this from the BLT side.

**Comment by grasmash** [comment]
The fastest solution is to use a Composer version constraint alias. e.g, "dev-master as 1.4.0".

**Comment by grasmash** [comment]
Also, `webflo/drupal-core-strict` probably shouldn't be pinning to an exact version. I'd submit a PR there to change it to `^1.4.0`.

**Comment by grasmash** [comment]
I filed https://github.com/wikimedia/composer-merge-plugin/issues/153 also

**Comment by grasmash** [comment]
Well that worked... 1.4.1 released :)

**Comment by grasmash** [comment]
@danepowell does the alias solution address your issue?

**Comment by danepowell** [comment]
I will try today and let you know

**Comment by danepowell** [comment]
Yep, adding this to my root composer.json `require` array worked:
`"wikimedia/composer-merge-plugin": "dev-master as 1.4.0"`

I think the whole point of webflo/drupal-core-strict is to lock dependencies to the exact versions in the core composer.lock file, so I don't think a pull request asking them to relax the dependency would be well received. But we might be able to get Reservoir to drop the dependency on drupal-core-strict.

Also, now that v1.4.1 is out, if BLT switches from dev-master to ^1.4.1, then this will all resolve itself after the next core release.

**Comment by grasmash** [comment]
Done in #1795
