### ISSUE TITLE
Evaluate the inclusion of acquia_cli tool

### ISSUE THREAD

**Issue by typhonius** [acquia/blt#1800]
At Deloitte, we've been using and contributing to https://github.com/typhonius/acquia_cli as part of our deployment process.

Typically, our deployment process is roughly:
```
RELEASE='release-0.1'
# Prepare the repo with dependencies so a deployment can be run
composer install
composer run-script blt-alias

# Cut a tag and deploy
blt deploy --commit-msg "Tagged release $RELEASE" --tag "$RELEASE" --ignore-dirty -v

# Run the Acquia Cli command to deploy the release tag to a specific environment (in this case alpha)
./vendor/bin/acquiacli preprod:deploy prod:sitename dev tags/$RELEASE
```

Would this be a viable addition to BLT for more complete deployment to Acquia?

**Comment by grasmash** [comment]
@typhonius  What capabilities does this library have that are not included in the Acquia we trust commands provided by cloud?

```
$ drush | grep ac-
 ac-api-login          Store Acquia Cloud API credentials and configuration information.
 ac-code-deploy        Deploy code from one site environment to another.
 ac-code-path-deploy   Deploy a specific branch or tag in an environment.
 ac-database-add       Add a database.
 ac-database-copy      Copy a database from one site environment to another.
 ac-database-delete    Delete a database.
 ac-database-info      Show information about a site database.
 ac-database-instance  Create a database instance backup.
 ac-database-instance  Delete a database instance backup.
 ac-database-instance  Download a site environment database instance backup.
 ac-database-instance  Show information about a site environment's database instance backup.
 ac-database-instance  List a site environment's database instance backups.
 ac-database-instance  Restore a database instance backup.
 ac-database-instance  Show information about a site environment's database instance.
 ac-database-instance  List a site environment's database instances.
 ac-database-list      List a site's databases.
 ac-domain-add         Add a domain name to an environment.
 ac-domain-delete      Delete a domain name from an environment.
 ac-domain-info        Show information about a site domain.
 ac-domain-list        List a site's domains.
 ac-domain-move        Move a domain from one site environment to another.
 ac-domain-purge       Purge a domain from the Varnish cache.
 ac-environment-info   Show information about a site environment.
 ac-environment-insta  Install a Drupal distribution from a pre-selected list, URL, or Drush Makefile.
 ac-environment-list   List a site's environments.
 ac-environment-lived  Configure Live Development on a site environment.
 ac-files-copy         Copy user-uploaded files from one site environment to another.
 ac-server-info        Show information about a server.
 ac-server-list        List servers for a site and environment.
 ac-server-php-procs   Calculate the php max procs value based on possible memory limits and apc shm settings.
 ac-site-info          Show information about a site.
 ac-site-list          List all sites available to the current user.
 ac-sshkey-add         Add an SSH key to a site.
 ac-sshkey-delete      Delete an SSH key from a site.
 ac-sshkey-info        Show information about a site SSH key.
 ac-sshkey-list        List a site's SSH keys.
 ac-svnuser-add        Add an SVN user to a site.
 ac-svnuser-delete     Delete an SVN user from a site.
 ac-svnuser-info       Show information about a site SVN user.
 ac-svnuser-list       List a site's SVN users.
 ac-task-info          Show information about a site task.
 ac-task-list          List a site's tasks.
```

**Comment by typhonius** [comment]
Part of the purpose of this library is to codify around Robo, like BLT, deployment processes and provide commands which give the user a safe and atomic way of running deployments etc.

While the Drush commands mirror pretty much all of the functionality of CloudAPI, the difference is more around waiting for tasks to complete e.g. the `prod:deploy` command will run the following:

- DB backup for all dbs in the prod environment
- Wait until the DBs have been backed up
- Deploy specified branch/tag to the prod environment
- Wait until the code has deployed
- Run cr, updb, cim, cr

I'd also be happy for blt to include this package as a suggestion so people can include it on their own if they so desire.

One point I will have to note is that the Acquia CloudAPI PHP SDK that this library relies on needs some love and ownership from Acquia. There are PRs that would go a long way towards fixing things like the severely out of date guzzle, but I'm not sure who should take responsibility. Your help here would also be appreciated.

**Comment by typhonius** [comment]
As an additional note, I don't think this library should be included until the Acquia SDK has been updated.

**Comment by grasmash** [comment]
> the Acquia CloudAPI PHP SDK that this library relies on needs some love and ownership from Acquia

Ah,  yes this is a strong reason for not adding the package as a dependency for BLT. I would accept a pull request introducing it as a suggestion for the time being.

> Your help here would also be appreciated.

I have made the case for updating this library a few times in the past. I'll try my hand at it again, but apart from taking it on myself, I may have limited success.
