### ISSUE TITLE
Default Behat tests fail on Travis

### ISSUE THREAD

**Issue by justclint** [acquia/blt#1803]
My system information:
* Operating system type: OSX
* Operating system version: 10.12.5
* BLT version: 8.8.7

Just set up travis with no custom config, just out of the box. The Drupal build seems to complete successfully but then it fails once it tries to run the default behat tests. I dont have any custom test yet so this is just the BLT defaults. Heres my .travis.yml file and the error from travis below it.

<details>
<summary>Output of blt doctor:</summary>

        | Property             | Value                                                                            |
        +----------------------+----------------------------------------------------------------------------------+
        | %paths               |                                                                                  |
        |  - %root             | /var/www/padiblt/docroot                                                         |
        |  - %site             | sites/default                                                                    |
        |  - %modules          | modules                                                                          |
        |  - %themes           | themes                                                                           |
        |  - %config-sync      | /var/www/padiblt/config/default                                                  |
        |  - %files            | sites/default/files                                                              |
        |  - %private          | /var/www/padiblt/files-private                                                   |
        |  - %temp             | /tmp                                                                             |
        | admin-theme          | seven                                                                            |
        | blt-version          | 8.8.7                                                                            |
        | bootstrap            | Successful                                                                       |
        | config-sync          | /var/www/padiblt/config/default                                                  |
        | db-driver            | mysql                                                                            |
        | db-hostname          | localhost                                                                        |
        | db-name              | drupal                                                                           |
        | db-password          | drupal                                                                           |
        | db-port              | 3306                                                                             |
        | db-status            | Connected                                                                        |
        | db-username          | drupal                                                                           |
        | drupal-settings-file | sites/default/settings.php                                                       |
        | drupal-version       | 8.3.4                                                                            |
        | drush-alias-files    | /var/www/padiblt/docroot/../drush/site-aliases/aliases.drushrc.php               |
        |                      | /var/www/padiblt/docroot/../drush/site-aliases/example.acsf.aliases.drushrc.php  |
        |                      | /var/www/padiblt/docroot/../drush/site-aliases/example.local.aliases.drushrc.php |
        | drush-conf           | /var/www/padiblt/drush/drushrc.php                                               |
        | drush-script         | /var/www/padiblt/vendor/drush/drush/drush.php                                    |
        | drush-temp           | /tmp                                                                             |
        | drush-version        | 8.1.12                                                                           |
        | files                | sites/default/files                                                              |
        | install-profile      | lightning                                                                        |
        | local-drushrc        | /var/www/padiblt/docroot/sites/default/local.drushrc.php                         |
        | local-settings       | /var/www/padiblt/docroot/sites/default/settings/local.settings.php               |
        | modules              | modules                                                                          |
        | php-bin              | /usr/bin/php                                                                     |
        | php-conf             | /etc/php/5.6/cli/php.ini                                                         |
        | php-os               | Linux                                                                            |
        | private              | /var/www/padiblt/files-private                                                   |
        | root                 | /var/www/padiblt/docroot                                                         |
        | site                 | sites/default                                                                    |
        | temp                 | /tmp                                                                             |
        | theme                | bootstrap_padi                                                                   |
        | themes               | themes                                                                           |
        | uri                  | default                                                                          |
        | user                 |                                                                                  |
        +----------------------+----------------------------------------------------------------------------------+
        +--------------------------+---------------------------------------------------------------------------------+
        | Check                    | Outcome                                                                         |
        +--------------------------+---------------------------------------------------------------------------------+
        | checkDocrootExists       | Found docroot.                                                                  |
        | checkCoreExists          | Drupal core exists                                                              |
        | checkSettingsFile        | BLT settings are included in settings file.                                     |
        | checkLocalSettingsFile   | Found your local settings file.                                                 |
        | checkLocalDrushFile      | Found your local drush settings file.                                           |
        | checkUri                 | Site URI is not set                                                             |
        |                          |                                                                                 |
        |                          | Is $options['uri'] set correctly in                                             |
        |                          | /var/www/padiblt/docroot/sites/default/local.drushrc.php?                       |
        |                          |                                                                                 |
        | checkFileSystem:%files   | Public files directory is writable.                                             |
        | checkFileSystem:%private | Private files directory is writable.                                            |
        | checkFileSystem:%temp    | Temporary files directory is writable.                                          |
        | checkDbConnection        | Connected to database.                                                          |
        | checkDrupalBootstrapped  | Bootstrapped Drupal via drush.                                                  |
        | checkDrupalInstalled     | Drupal is installed.                                                            |
        | checkCaching:page        | Drupal cache is disabled.                                                       |
        | checkCaching:css         | CSS preprocessing is disabled.                                                  |
        | checkCaching:js          | JS preprocessing is disabled.                                                   |
        | checkNvmExists           | NVM does not exist.                                                             |
        |                          |                                                                                 |
        |                          | It is recommended that you use NVM to manage multiple versions of NodeJS on one |
        |                          | machine.                                                                        |
        |                          | Instructions for installing NVM can be found at:                                |
        |                          |   https://github.com/creationix/nvm#installation                                |
        | checkCiConfig            | Git remotes are set in project.yml.                                             |
        | checkComposer:require    | acquia/blt is in composer.json's require object.                                |
        | checkComposer:plugins    | hirak/prestissimo plugin for composer is installed.                             |
        | checkBehat:exists        | Behat local settings file exists.                                               |
        | checkBehat:uri           | base_url in tests/behat/local.yml does not match the site URI.                  |
        |                          |   Behat base_url is set to "http://local.padiblt.com".                          |
        |                          |   Drush site URI is set to default.                                             |
        | checkProjectYml:keys     | project.yml has no deprecated keys.                                             |
        | checkPhpDateTimezone     | PHP setting for date.timezone is correctly set   

</details>

<details>
<summary>.travis.yml file</summary>

        # Note that the example .travis.yml file for child projects lives in /install.
        # Temporarily use legacy infrastructure until Travis resolves MySQL issues with their containerized infrastructure.
        # @see https://github.com/travis-ci/travis-ci/issues/6842
        sudo: required
        language: php
        dist: trusty

        php:
          - 5.6

        matrix:
          fast_finish: true

        env:
          global:
            - COMPOSER_BIN=$TRAVIS_BUILD_DIR/vendor/bin
            - BLT_DIR=$TRAVIS_BUILD_DIR/vendor/acquia/blt
            - BUILD_DIR=$TRAVIS_BUILD_DIR

        jdk:
          - oraclejdk8

        cache:
          bundler: true
          apt: true
          directories:
          - "$HOME/.composer/cache"
          - "$HOME/.drush/cache"
          - "$HOME/.npm"
          - "$HOME/.nvm"
          - "vendor"
          # Cache front end dependecies to dramatically improve build time.
          # - "docroot/themes/custom/mytheme/node_modules"
          # - "docroot/themes/custom/mytheme/bower_components"

        addons:
          ssh_known_hosts:
           - svn-*****.prod.hosting.acquia.com

        # @see https://docs.travis-ci.com/user/notifications
        notifications:
        # - hipchat: [api token]@[room id or name]
        # - slack: '<account>:<token>#[channel]'

        before_install:
          # Disable xdebug.
          - phpenv config-rm xdebug.ini
          - composer self-update
          - composer validate --no-check-all --ansi
          - composer install

        install:
          - source ${BLT_DIR}/scripts/travis/setup_environment
          - source $BLT_DIR/scripts/travis/setup_project

        script:
          - source $BLT_DIR/scripts/travis/run_tests

        deploy:
           - provider: script
             script: "$BLT_DIR/scripts/travis/deploy_branch"
             skip_cleanup: true
             on:
               branch: develop
               php: 5.6
           - provider: script
             script: "$BLT_DIR/scripts/travis/deploy_branch"
             skip_cleanup: true
             on:
               branch: master
               php: 5.6
           - provider: script
             script: "$BLT_DIR/scripts/travis/deploy_tag"
             skip_cleanup: true
             on:
               tags: true
               php: 5.6

</details>

<details>
<summary>Travis Behat Error</summary>

        BUILD FINISHED; 6 minutes  7.14 seconds
        blt tests:all --define behat.run-server=true --yes -v
        tests:behat >
        [Filesystem\FilesystemStack] mkdir ["/home/travis/build/****/reports"]
        [info] Killing all processing containing string 'runserver'
        PHP Notice:  Undefined property: Acquia\Blt\Robo\Commands\Tests\BehatCommand::$serverPort in /home/travis/build/PadiWW/padi-blt/vendor/acquia/blt/src/Robo/Commands/Tests/BehatCommand.php on line 122
        Notice: Undefined property: Acquia\Blt\Robo\Commands\Tests\BehatCommand::$serverPort in /home/travis/build/PadiWW/padi-blt/vendor/acquia/blt/src/Robo/Commands/Tests/BehatCommand.php on line 122
        [info] Killing all processes on port
        lsof: unacceptable port specification in: -i tcp:
        lsof 4.86
        latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
        latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
        latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
        usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
        [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
        [+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
        Use the ``-h'' option to get more help information.
        Launching PHP's internal web server via drush.
        [info] Running server at http://127.0.0.1:8888
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [info] Waiting for response from http://127.0.0.1:8888...
        [error]  Timed out
        
</details>

**Comment by grasmash** [comment]
There's a good chance that this is failing due to an application issue, but the verbosity level isn't high enough to bubble the app error to the logs. Fixing that in PR.

**Comment by grasmash** [comment]
Please test your build with the commit in https://github.com/acquia/blt/issues/1803, and ping me on this issue if it does not illuminate an underlying application issue.

Use 8.8.x-dev to pull in the commit.

**Comment by justclint** [comment]
thanks @grasmash! 

Just gave this a try with 8.8.x-dev however still get a similar timeout:

```
BUILD FINISHED; 6 minutes  18.06 seconds
blt tests:all --define behat.run-server=true --yes -v
tests:behat >
[Filesystem\FilesystemStack] mkdir ["/home/travis/build/***/reports"]
[info] Killing all processing containing string 'runserver'
[info] Killing all processes on port 4444
Launching PHP's internal web server via drush.
[info] Running server at http://127.0.0.1:8888
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[error]  Timed out 
```

**Comment by justclint** [comment]
@grasmash Ive tested this on my local and the test finish fine but still timeout on Travis.

Heres my results from `blt tests:all` on local:

```
vagrant@local: $ blt tests:all
tests:behat >
Launching PhantomJS GhostDriver.
[Testing\Behat] Running behat  --format pretty /var/www/padiblt/docroot/../tests/behat --colors --no-interaction --stop-on-failure --strict --config /var/www/padiblt/docroot/../tests/behat/local.yml --profile local --tags '~ajax&&~experimental&&~lightningextension'
@example
Feature: Web drivers
  In order to verify that web drivers are working
  As a user
  I should be able to load the homepage
  With and without Javascript

  @javascript
  Scenario: Load a page with Javascript # features/Examples.feature:9
    Given I am on "/"                   # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then I should see the text "Log in" # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()

  Scenario: Load a page without Javascript # features/Examples.feature:13
    Given I am on "/"                      # Drupal\DrupalExtension\Context\MinkContext::visit()
    Then I should see the text "Log in"    # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()

2 scenarios (2 passed)
4 steps (4 passed)
0m7.91s (34.21Mb)

tests:phpunit >
[Testing\PHPUnit] Running PHPUnit  --log-junit /var/www/padiblt/docroot/../reports/phpunit/results.xml .
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

.

Time: 407 ms, Memory: 6.00MB

OK (1 test, 1 assertion)

tests:security-updates >
<success>There are no outstanding security updates.</success>
```

But on travis after the build completes when `blt tests:all` executes I get:

```
BUILD FINISHED; 6 minutes  43.81 seconds
blt tests:all --define behat.run-server=true --yes -v
tests:behat >
[Filesystem\FilesystemStack] mkdir ["/home/travis/build/PadiWW/padi-blt/reports"]
[info] Killing all processing containing string 'runserver'
[info] Killing all processes on port 4444
Launching PHP's internal web server via drush.
[info] Running server at http://127.0.0.1:8888
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[info] Waiting for response from http://127.0.0.1:8888...
[error]  Timed out 
```
I am using the 8.8.x-dev version. Any idea what might be causing this on travis?

Thanks!

**Comment by brooke-heaton** [comment]
Getting the same timeout issue.

**Comment by loopy3025** [comment]
This might be unrelated to the OP's use case, but this is a top result for searching this issue.

I had this issue when running `source ${BLT_DIR}/scripts/pipelines/tests` on a big, nasty site. The issue only occured for me because I was trying to use the script in a non-standard way; we are calling it during setup-env. The following patch to blt stops the wait, but that also means you may want to add a timer before running your tests. 

```
diff --git a/vendor/acquia/blt/src/Robo/Common/Executor.php b/vendor/acquia/blt/src/Robo/Common/Executor.php
--- a/vendor/acquia/blt/src/Robo/Common/Executor.php
+++ b/vendor/acquia/blt/src/Robo/Common/Executor.php
@@ -181,7 +181,7 @@ public function killProcessByName($name) {
    *   The URL to wait for.
    */
   public function waitForUrlAvailable($url) {
-    $this->wait([$this, 'checkUrl'], [$url], "Waiting for non-50x response from $url...");
+    // $this->wait([$this, 'checkUrl'], [$url], "Waiting for non-50x response from $url...");
   }
 
   /**
```
