### ISSUE TITLE
phpdocumentor bug may be affecting blt

### ISSUE THREAD

**Issue by greg-1-anderson** [acquia/blt#1808]
See https://github.com/pantheon-systems/terminus/pull/1740 for workaround.

Have not tried to reproduce in blt. New version of annotated commands will fix in future.

**Comment by grasmash** [comment]
Thanks for posting @greg-1-anderson. Is it correct that this would only affect us if we are using the `@usage` tag?

**Comment by greg-1-anderson** [comment]
Yeah, probably.

**Comment by grasmash** [comment]
Thanks!

**Comment by greg-1-anderson** [comment]
FYI this was a false alarm. There is no issue with `@usage`; the problem is actually that phpdocumentor 3.2.0 and later now rejects annotations in the form `@foo: description`. This was previously accepted, but no longer is; you must use `@foo description` now (which was always the preferred form).
