### ISSUE TITLE
site.yml config and commands such as setup:settings

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1838]
BLT v8.9.0

I'm seeing an issue with a multisite implementation. I have two sites, `docroot/sites/siteA` and `docroot/sites/siteB` and they both have a `site.yml` config file.

Each `site.yml` has `project.local.hostname` set.

When I run `$ blt setup:settings`, the command copies files such as `default.local.drushrc.php` which has a substitution string `${project.local.uri}`. The problem is, the uri is set based on `project.yml` and not an override in `site.yml`, and the respective `site.yml` is not loaded at that time.

Not sure of the best way to fix this, or if it should even be fixed... maybe my "siteA" file shouldn't use the substitution string, and instead be hardcoded...? That's likely my interim fix. Is this something to address? I have a feeling there might be more commands that are impacted, but this was a good start to give an example.

**Comment by grasmash** [comment]
I wouldn't expect the multisite specific values to be loaded during `setup:settings` as each file is copied, only in subsequent commands if `-D site=siteA` were passed.

**Comment by grasmash** [comment]
@dpagini I feel that I may be misunderstanding the issue that you filed.

What behavior are you expecting exactly? Do you need placeholders to be replaced in site.yml files directly after they are copied?

**Comment by dpagini** [comment]
Sorry, I hadn't had a chance to get back to this issue yet...

I think what I'm a little confused about is that only certain commands load the `site.yml` and I don't know which commands those are, actually.

If I want to run multisite, and I create a new folder at `docroot/sites/siteB`, BLT will come along and import, for example, the `settings/default.local.drushrc.php` which has a substitution string in it. Then BLT will take that default, and create `docroot/sites/sitesB/local.drushrc.php` but use the URL for the main site (which is defined in `blt/project.yml`) instead of the multisite URL when substituting the config value, which would be defined/overridden in `..siteB/site.yml` but is ignored b/c that is not loaded.

Maybe the problem is the "setup:settings" command runs for all multisites instead of just one site at a time? Even then though, if I pass `-D site=siteB` at run time, this command still runs for all sites and does not load the site.yml file, right? I guess I'm not sure about that part.
