### ISSUE TITLE
Inconsistent strategy for .gitignore and deploy-exclude.txt files

### ISSUE THREAD

**Issue by remydenton** [acquia/blt#1839]
It's unclear to me what type of lines belongs in each of these two files:

- [deploy-exclude.txt](https://github.com/acquia/blt/blob/8.x/template/.gitignore) (and its custom version, deploy-exclude-additions.txt)
- [The build artifact .gitignore file](https://github.com/acquia/blt/blob/8.x/scripts/blt/deploy/.gitignore) (or a customized version).

From the looks of it, they both lack a clear strategy.  For example:

1. Both include a slightly different line for the IDE-related `.idea`: the version in `deploy-exclude.txt` is [prefixed with a slash](https://github.com/acquia/blt/blob/8.x/scripts/blt/deploy/deploy-exclude.txt#L4), whereas in gitignore it's instead [suffixed with a slash](https://github.com/acquia/blt/blob/8.x/scripts/blt/deploy/.gitignore#L76).  The implication is that we should not rsync an `.idea` directory or file from the source root directory, but we should if it's anywhere else; we shouldn't commit an `.idea` directory that finds its way into the deploy files, but a file named `.idea` that appears anywhere should be committed.
2. The .gitignore file includes [two lines for `nbproject`](https://github.com/acquia/blt/blob/8.x/scripts/blt/deploy/.gitignore#L86-L87) (which are redundant), but the `deploy-exclude.txt` file doesn't have any similar reference.  The implication is that it's desirable to rsync a `nbproject` file or directory to a build directory, but not to commit it.  It's the same kind of IDE-related file as in `1`, but a different (and equally incoherent) set of rules.
3. deploy-exclude.txt includes two lines that [exclude specific local settings files](https://github.com/acquia/blt/blob/8.x/scripts/blt/deploy/deploy-exclude.txt#L30-L31), but the build .gitignore file goes a step further and excludes any file that [starts or ends with local](https://github.com/acquia/blt/blob/8.x/scripts/blt/deploy/.gitignore#L2-L3).  The implication is that you would want a local.something file to be rsynced, but wouldn't want it committed in a build artifact.

Suggestions for improvement:
- Rules should probably exist in either one file or the other, not both.  If the documentation for deploy-exclude is correct (i.e. "If these files already exist in the upstream artifact, they will be removed."), my approach would be to put all of the various IDE-related rules there to prevent these files from ever getting copied to a build in the first place.  I would then suggest only putting rules in the .gitignore that are needed for files that get added during the build process (e.g. vendor, or anything from within a composer project).
- If there's a good reason for rules to exist in both files, they should at least match between the two (and the the rules should appear in the same order in both files for better maintainability).
- Regardless of the strategy, it should be documented clearly at the top of both files. (Side note, there's an error in the line of documentation at the top of the gitignore file: it says, "This file will be copied into the docroot of the build artifact.", when in fact it will be copied to the project root, not the docroot).

Finally, there's actually a third file that should be included in this cleanup, namely [the .gitignore file for source repositories](https://github.com/acquia/blt/blob/8.x/template/.gitignore).  Just one example, it includes lines for [*.gz, *.sql, and *.zip files](https://github.com/acquia/blt/blob/8.x/template/.gitignore#L121-L123)—sensible rules, except that they don't appear in the other two files I mentioned!  That means if you had such a file (say, a database dump...) it would be ignored in your source repo but copied over and committed to your build repo.

**Comment by remydenton** [comment]
In cleaning up these two files for a project I'm working on, I came up with the following rules of thumb for what belongs in each.  Grouping the rules by these categories definitely helped clarify why any given rule is included, and I think would be particularly beneficial for maintainability within blt itself.

**Use .gitignore for:**
  1. Files generated during the build process (e.g. if you don't want to commit the readme files from contributed modules).
  2. Files that are used to create a build, but aren't necessary in the build itself (e.g. linting configuration, gulp files, etc).
  3. Files that are added by the filesystem, IDEs, etc that might either be copied over (if not included in deploy-exclude) or spontaneously created after a build is created. (e.g. IDE configuration like an .idea directory, MacOS system files like .DS_store, etc.).  Because they can spontaneously appear, the safest place to handle these is in .gitignore.

**Use deploy-exclude.txt for:**
  1. Files that you intend to commit to the build but that will be rebuilt as part of the build process (e.g. composer projects).
  2. Files that you don't intend to commit to the build and would never appear spontaneously if not copied over (e.g. a directory with various project documentation; project-x files configuration files).
  3. Files that you don't intend to commit to the build and _could_ reappear spontaneously, but that you still want to avoid copying over to avoid confusion or performance issues (e.g. uploaded files directory, IDE config such as an .idea directory which could confuse PHP Storm, etc).  These files should _also_ have a matching entry in the build's .gitignore file.

Can someone familiar with the existing ignore/exclude files review these for accuracy?  I could then potentially put together a PR that at least organizes and documents those files a bit better.

**Comment by grasmash** [comment]
Thanks for thinking through this question and proposing a set of rules. I think that your suggestion sounds good.

Just one wrinkle to add.  Consider that, during the artifact generation process, BLT will pull code down from the upstream repository. There may be files pulled from upstream that you are not expecting. For instance, project documentation may have been inadvertently committed at some previous point. If that is the case, it would be helpful to have a "belt and suspenders" approach and add lines for all file types to both files. It is duplicative, but it also prevents the edge case.

Anyway, I don't have strong feelings about this edge case. Feel free to consider it and submit a pull request based on your own sensibilities.

**Comment by remydenton** [comment]
Hmm, good point.  I actually suspect a file that's already committed to the artifact repository actually wouldn't be removed if it were _both_ ignored and excluded: being in the deploy-exclude file would indeed remove it from the artifact directory during rsync, but that removal wouldn't be committed to the artifact repository... because the file is ignored.  Haven't tested that, but if true it's a bit of a catch 22.

In any case, I'll try to get to a PR in the next week or two (famous last words I'll probably regret...).

**Comment by ba66e77** [comment]
Over a year with no update here. I'm going to close this out.
