### ISSUE TITLE
SAML configuration copying fails during the deploy task

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#1843]
My system information:
* Operating system type: MacOS
* Operating system version: 10.12.5
* BLT version: 8.9.0

When I run this command:
```
blt depoy:build -vvv
```

I get the following output:
```
Generating simplesamlphp configuration...
[ExecStack] blt simplesamlphp:deploy:config
[ExecStack] Running blt simplesamlphp:deploy:config in /Users/rg173/Sites/<site>
sh: blt: command not found
[ExecStack]  Exit code 127  Time 0.006s
Executing post-deploy-build target hook...
[post-deploy-build commands]
The deployment artifact was generated at /Users/rg173/Sites/4k-nyunursing/deploy.
01:22 total time elapsed.
```

And I expected that my SAML configuration would be copied as expected or, if this was unsuccessful, the build would fail (which it did not).

**Comment by typhonius** [comment]
Same thing occurred at our end - PR works, should be an easy fix/close issue.
