### ISSUE TITLE
Scaffold  composer files required by merge plugin.

### ISSUE THREAD

**Issue by thom8** [acquia/blt#1849]
Merging a [`composer.json`](https://github.com/acquia/blt/blob/8.x/blt-project/composer.json#L42-L43) file from composer dependency breaks composers' idempotency and makes upgrading difficult -- https://blt.readthedocs.io/en/stable/readme/updating-blt/

issue -- `rm -rf vendor/acquia/blt && composer install`

Would you consider scaffolding these files to a known location such as `blt/composer.required.json`, git ignored by default.

This could be implemented as a composer plugin to sync these files triggered on `PRE_INSTALL_CMD` & `PRE_UPDATE_CMD`

https://getcomposer.org/apidoc/1.3.2/Composer/Script/ScriptEvents.html

This way a project could choose to track these dependencies and part of the update process would be to manage update to these files.

**Comment by grasmash** [comment]
@thom8 I was actually aware of this issue already. I agree that it needs to be resolved.

Your solution sounds like the best one. I would love it if you could work on a pull request to introduce these changes.

A word of caution, this particular aspect of BLT can be fairly complex and difficult to debug. I also find that it often comes with a lot of edge cases. So, this approach will need very thorough testing. 

The current approach is not ideal, but its limitations are at least known and not too inconvenient.  That is why I have been hesitant to make any changes.
