### ISSUE TITLE
Document that SimpleSAML on PHP 7 should only use database session storage

### ISSUE THREAD

**Issue by typhonius** [acquia/blt#1857]
As discovered here: https://github.com/simplesamlphp/simplesamlphp/pull/395 the SimpleSAMLphp library doesn't integrate well with memcache on PHP7.

The reason for this is that it assumes the existance of the Memcache class. Memcache is totally not ready for showtime on PHP7, whereas its sister Memcache**d** is. Currently, Memcache**d** is not supported by SimpleSAMLphp.

Acquia does not have the Memcache class, which causes fatal errors if memcache is selected as a session storage when using PHP > 7.

Are we best to default to database in the simplesaml template or keep the defaults and write some documentation on the simplesaml page to ensure unwitting teams don't get caught short?

**Comment by greylabel** [comment]
Just ran into this issue as well updating our ACE environments to PHP7  -- _default to database in the simplesaml template_ seems reasonable.

**Comment by grasmash** [comment]
You could even detect PHP version and set accordingly. Otherwise, "default to database in the simplesaml template seems reasonable" to me too.

**Comment by grasmash** [comment]
@typhonius Would you mind submitting PR?
