### ISSUE TITLE
Add ACSF-Tools package require in acsf:init

### ISSUE THREAD

**Issue by msherron** [acquia/blt#1868]
My system information:
* Operating system type: OS X
* Operating system version: Sierra
* BLT version: 8.9

We need to alter the acsf:init command to require the `acquia/acsf-tools` package in addition to the acsf contrib module. This is a drush contrib module that provides a CLI to the [ACSF Rest API](https://docs.acquia.com/site-factory/rest-api). It also allows you to manage updating your drush site aliases locally without a code deploy.

Additionally, @grasmash mentioned he'd like a way for all commands to run a composer require (and include retry without dependencies capability) without copypasta.

**Comment by grasmash** [comment]
#1869
