### ISSUE TITLE
blt sync:files rsync images to files/files/

### ISSUE THREAD

**Issue by ericchenshine** [acquia/blt#1886]
My system information:
* BLT version: 8.9.0

When I use `blt sync:files`, all synced files go to the docroot/sites/default/files/files.

This is caused by wrong file directory in `sync:files` command.

**Comment by ericchenshine** [comment]
Here is the PR: https://github.com/acquia/blt/pull/1887

**Comment by bobbygryzynger** [comment]
@ericchenshine this is fixed in #1845.
