### ISSUE TITLE
phpcs: haltonwarning no longer available

### ISSUE THREAD

**Issue by grahl** [acquia/blt#1889]
My system information:
* Operating system type / version: macOS Sierra, Centos 7.x
* BLT version: 8.9.0

When I run this command:
```
blt validate:phpcs
```

I get the following output:
```
[error]  Executing `'/.../vendor/bin/phpcs' --standard='/.../vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml' '%s'` against fileset(s) files.php.custom.modules returned a non-zero exit code.` 
```

And I expected this to happen:
Since I set haltonwarning: false in project.yml under phpcs i expected the validation to return a zero error code. This variable is still documented under build.yml but the removal of the validate.xml with the parameters below means that this is no longer passed to phpcs:
``` <phpcodesniffer
        file="${file}"
        standard="${phpcs.ruleset}"
        showSniffs="false"
        showWarnings="true"
        haltonerror="true"
        haltonwarning="true"
        verbosity="${blt.verbose}"/>
```

Workaround:
I can manually set vendor/bin/phpcs --config-set ignore_warnings_on_exit 1 to successfully validate.

**Comment by grasmash** [comment]
That is correct. This is a documentation oversight.

You can still prevent halt on error, but you must do it by setting PHPCS configuration directly.  The recommended way to store that configuration is in a phpcs.xml.

**Comment by dpagini** [comment]
Just updated to BLT 8.9.1 and ran into a similar problem. I had _way too many_ warnings to fix at once with what I think is a different standard. Maybe I had an out of date file, I'm not sure... 

Anyways, I added the following line to `/phpcs.xml` (a copy of `/phpcs.xml.dist`):
```
<config name="ignore_warnings_on_exit" value="1" />
```

This fails on errors, but lets me proceed with warnings. Maybe that helps? If not you, maybe someone who comes and looks at this thread..?
