### ISSUE TITLE
Config split ignored during config-import on Acquia cloud

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1891]
My system information:
* BLT version: 8.9.0

When I deploy code for BLT 8.9.0 sites to Acquia Cloud, it imports configuration as part of Cloud post-deploy/post-update hooks. Normally this config import applies config splits as well, but as of 8.9.0 this is no longer the case.

BLT is essentially running this command:
`/var/www/html/foo.dev/vendor/bin/drush config-import vcs`

When I run that command manually, I can verify that it does _not_ properly include config splits.

If I simply change that to use the `sync` key instead of `vcs`, it _does_ take into account config splits:
`/var/www/html/foo.dev/vendor/bin/drush config-import sync`

This makes sense, since Config Split (or Config Filter really) only supports using the default `sync` directory: https://www.drupal.org/node/2865912#comment-12020955

The only thing that doesn't quite make sense to me is why this only changed recently. I'm assuming BLT versions prior to 8.9 used the `sync` directory during deployments.

**Comment by grasmash** [comment]
@danepowell A bug was recently fixed in BLT, it formerly caused the `sync`  key to be used everywhere.  Ironically, that bug appears to have been responsible for making config split work.

**Comment by pixlkat** [comment]
This was the problem I had when I updated to 8.9.0 -- I worked around it by adding these lines in the cm section of my /blt/project.yml file
```
cm:
  strategy: config-split
  core:
    deploy-key: sync
```

**Comment by danepowell** [comment]
That commit worked, thanks!

**Comment by alex-moreno** [comment]
I was having the same issue in Acquia Cloud. deploy-key: sync trick fixed the issue
