### ISSUE TITLE
Couldn't create a new project with blt

### ISSUE THREAD

**Issue by harsha49970** [acquia/blt#1896]
My system information:
* Operating system type: MAC OS Sierra
* Operating system version: 10.12.5
* BLT version: 8.9.0

Hey guys I am trying to create a new project with blt but I got stuck by a PHP Fatal error. Please see the screenshot.

![screen shot 2017-08-08 at 1 50 42 pm 2](https://user-images.githubusercontent.com/6428665/29086686-678310a4-7c41-11e7-9076-cb02eaab57f1.png)

**Comment by grasmash** [comment]
This is related to your local machine's PHP configuration. It appears that the function 'posix_getpwuid()',  which is native to PHP, is not available on your system.

 Is there anything unusual about your local PHP set up?

**Comment by harsha49970** [comment]
Nope, the version I am using for PHP is 5.6.30

**Comment by harsha49970** [comment]
Got it I just updated the php to 7.0.21 it is working now!!!
