### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1900]
Trying to kick off a new project with BLT. The repo homepage says the latest version is 8.9.x, however when I [run through the create commands](http://blt.readthedocs.io/en/stable/readme/creating-new-project/), when I run composer create-project, it says this in the console:

```
Installing acquia/blt-project (8.0.4)
  - Installing acquia/blt-project (8.0.4): Loading from cache
```

I have cleared composer cache a couple of times. Should it say 8.0.4?

**Comment by grasmash** [comment]
acquia/blt-project != acquia/blt

See https://github.com/acquia/blt-project
