### ISSUE TITLE
BLT Validate & PHPCS Coder Standards Failing in BLT 8.9.1

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#1905]
BLT Version: 8.9.1

When I run this command:
```
blt validate
```

I get the following output:
```
FILE: ...cc/docroot/modules/custom/<project>_data/tests/ProviderTest.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 8 WARNINGS AFFECTING 8 LINES
----------------------------------------------------------------------
  14 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
  50 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
  68 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
  82 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
  96 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
 110 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
 124 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
 138 | WARNING | Class name must be prefixed with the project name
     |         | "<project>Data.info"
----------------------------------------------------------------------

```

And I expected this to happen:
I understand based on the new Drupal Coder standards that the classes should be prefixed with the project name. That does make sense to me. HOWEVER naming something <module>.info<class> isn't valid either.

I've posted on the Coder forums on D.O (https://www.drupal.org/node/2896257) but not gotten traction on this issue. Is anyone else running into this or have any thoughts on how we could fix it? A simple regex in the coder logic to strip the .info from the file name seems to work, but I'm worried about what else that might effect...

**Comment by grasmash** [comment]
You can ignore specific rules in `phpcs.xml`. E.g., https://github.com/acquia/blt/blob/8.x/phpcs.xml.dist#L16

**Comment by mikemadison13** [comment]
After reviewing the code in this case, these are happening only on files that are missing an explicit namespace declaration. I believe that @grasmash has proposed a change in the Coder issue above that not only removes the .info from the name of the class suggestion, but provides a hint about the missing namespace.

No action required on the BLT side.
