### ISSUE TITLE
Overriding "vendor/acquia/blt/composer.required.json" versions

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1906]
> If you'd like to override the default version constraint for a package provided by BLT, you may simply define the desired version in your root composer.json file.

Just clarifying (I am coming from a much older release of BLT), if I wanted to lock the Drupal version, I would add this to my root composer.json:

`"drupal/core": "8.3.6"`

and run `composer update`?

**Comment by grasmash** [comment]
As long as you have:

```
    "merge-plugin": {
        "replace": false,
        "ignore-duplicates": true
    }
```

**Comment by grasmash** [comment]
Docs updated to clarify.

http://blt.readthedocs.io/en/8.x/readme/dependency-management/#modifying-blts-default-composer-values
