### ISSUE TITLE
Lightning upgrade script fails in BLT

### ISSUE THREAD

**Issue by thom8** [acquia/blt#1931]
The [lightning update script](http://lightning.acquia.com/blog/round-your-front-end-javascript-libraries-composer) `composer run enable-asset-packagist` fails in BLT as it makes a fair assumption to look for a root `composer.json` which has a dependency of lightning -- https://github.com/acquia/lightning/blob/8.x-2.x/src/Composer/AssetPackagist.php#L33

This fails on BLT as the lightning dependency it actually in [composer.suggested.json](https://github.com/acquia/blt/blob/8.x/composer.suggested.json#L3)

I'm not sure of the background behind `composer.suggested.json` but is it necessary?

I've moved these dependencies into the root of my project as a workaround however after running the update there's a warning as follows >>

```
Warning: The value for extras.installer-paths in composer.json differs from BLT's recommended values.
See https://github.com/acquia/blt/blob/8.x/template/composer.json
```

**Comment by grasmash** [comment]
Resolved by #1923.
