### ISSUE TITLE
Robo deploy and untracked files

### ISSUE THREAD

**Issue by willthemoor** [acquia/blt#1934]
Very minor thing... I don't think `deploy` should bail if there are untracked files in the current folder tree.

```bash
$ blt deploy --commit-msg "blah blah blah" --branch "develop-build" --no-interaction
```
exits with "There are uncommitted changes, commit or stash these changes before deploying." if there are _untracked_ files in the working directory. 

I think [`DeployCommand::checkDirty()`](https://github.com/acquia/blt/blob/bb8baaee8238a9ed7b8fd396f4eccca5f5b5edf0/src/Robo/Commands/Deploy/DeployCommand.php#L74) is really looking for _unstaged_ changes to tracked files but the way the function works it is including untracked files as dirty. If you have untracked files in the working directory (and all tracked-file changes committed), `git status --porcelain` will return `?? untracked file` for each file so `$dirty` will not be empty.

I don't know the inner workings of the rest of the BLT build process but presumably it doesn't care about untracked files. If it does, please close this issue right out!

I realize I can use `--ignore-dirty` (and thanks to the thoughtful person who included that) but I'd rather keep that off because I do not want the deploy to ignore unstaged changes to tracked files.

BLT 8.9.2 on OSX 10.11.6

**Comment by thom8** [comment]
@willthemoor the main issue here is files are copied from the source repo into artifact --
https://github.com/acquia/blt/blob/8.x/src/Robo/Commands/Deploy/DeployCommand.php#L339

There might be historic reasons for this but I'd prefer the deploy task to do a clean build of all project dependencies. NPM 5 now include lock file support and worst case you can track your FED dependencies in the source repo.

If this behaviour was changed or configurable it wouldn't matter if the source repo was dirty.

**Comment by thom8** [comment]
A solution here could be to do a local clone, either directly to the deploy directory or a temp directory in which you use as the source for copying.

```php
    // Clone to build directory.
    $this->taskGitStack()
      ->cloneRepo($this->getConfigValue('repo.root'), $this->getConfigValue('deploy.dir'))
      ->run();
```

**Comment by willthemoor** [comment]
@thom8 Thanks for pointing that method out. Since it's doing an `rsync` from the repo.root, it all makes more sense now. I agree that creating a new/fresh/clean clone might be the best solution eventually but so long as we're using rsync, `checkDirty()` should probably continue to include untracked files.

And 'thanks for the link' reason number two: I hadn't yet discovered the exclude files. :) Those will solve part of what I was running into for sure. 

Please feel free to close this one out.
