### ISSUE TITLE
BLT's composer requirements

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#1949]
My system information:
* BLT version: 8.9.2

I wanted to raise 3 contentions with BLT's composer handling to get some background, provide some context for anyone having the same issues, and potentially pose some solutions.

1. I'm not sure I agree with BLT **requiring** `drupal/devel` in `composer.required.json`. Based on my research of #1258, this was added b/c `template/blt/project.yml` has an enable/uninstall reference to that package. That seems a bit heavy-handed to me, and based on some of the other modules (seckit, acquia_connector) being enabled/uninstalled, devel belongs alongside the other modules in `composer.suggested.json`. _We should also update the requirement of DEV to remove the alpha1 reference, even though it isn't hurting anything._
1. `drupal/config_split` I have a similar feeling about. I am using features for config management, so I don't even need that module in my code base, but BLT is requiring it. ~~I think this should be in suggested as well. If I decide to use features, I have to manually add it myself, so I'm just wondering if features belongs with config_split as well in suggested... I could see if `config_split` is the default, or suggested, why having that one makes sense, but to put that package as BLT `composer.required.json` seems like an overstep to me.~~ _Edit: I'm seeing now features is a required package. I think I still have a similar opinion, but I dont feel as strongly. Leaving where it is now, but my patch updates the version constraint._
1. The BLT `drupal/core` patch. I believe this patch is to help out sites hosted at Acquia, is that close to accurate? I was looking over this d.o issue queue, ~~and there are several newer patches available,~~ and the issue is still in needs work status. Shouldn't a patch like that be in `composer.suggested.json` as well? If I'm hosting my own site, there's really no reason I need that patch (or maybe there is), but I just think I should be able to decide if I want to include that patch or not, or even to provide a newer version of it if BLT doesn't have the latest.

I'd like to put up a PR with these proposed changes for discussion. I hope to get to it tonight/tomorrow.

**Comment by grasmash** [comment]
> I'm not sure I agree with BLT requiring drupal/devel in composer.required.json.

This is reasonable. I think that we can move it.

> drupal/config_split I have a similar feeling about.

Some of BLT's commands rely on the existence of this module.  So, I would prefer to leave it in. It doesn't need to be enabled for sites that are not using it.

> The BLT drupal/core patch.

This patch is required for any host that uses multiple webheads.  I would prefer to leave it as required since it addresses a fairly common and significant issue in Drupal core. Is this causing some sort of issue for you on your host?

**Comment by dpagini** [comment]
> Is this causing some sort of issue for you on your host?

No, I think I just commented on it while I was looking into these composer issues. I was thinking of the concept that BLT is not Acquia specific, but yeah, I don't feel strongly about the patch.

The `config_split` and `features` make much sense to bring in and just not enable if you don't use it. The `devel` one is just an example, and does fit along with the treatment of `acquia_connector` and `seckit` and some other modules.

I can update the patch later today.

**Comment by dpagini** [comment]
K, updated PR.
