### ISSUE TITLE
blacklist files in sync:settings

### ISSUE THREAD

**Issue by simesy** [acquia/blt#1951]
We have 20 multisites, and don't need to keep 20 default.local.settings.php files, actually they are just useless noise. Is there a way to prevent BLT from creating these files in `blt setup:settings`? The way that you can do with drupal-scaffold?

**Comment by grasmash** [comment]
There is no way to prevent these files from being generated, however you could try one of the following two solutions:

* Use .gitignore to prevent the files from being committed
* Use a post command took to delete the files after they are generated.

**Comment by simesy** [comment]
Thanks for the tips!
