### ISSUE TITLE
How can I export blacklisting modules and configuration on Acquia Cloud

### ISSUE THREAD

**Issue by snize** [acquia/blt#1954]
The [Document](http://blt.readthedocs.io/en/stable/readme/configuration-management/#blacklisting-modules-and-configuration) describes how to blacklisting modules and configuration on local env. But how can I do this for remote env?

Currently I'm doing this for each env (e.g. for prod)

1. `drush @myapp.local sql-sync `
2. Blacklist modules  for prod env `/admin/config/development/configuration/config-split/prod/edit` on local VM.
2. `drush @myapp.local csex prod`
3. `drush @myapp.local cex`
4. Then commit to git by hand-picking .yml which I needed.  

Please let me know if you know of any better way than the mentioned above.

**Comment by grasmash** [comment]
As far as I know, this is the only way. I'm working on more extensive docs here:
https://gist.github.com/grasmash/debe7a2af4ea45cc222c890a8aaffe86#exporting-to-a-split-that-is-not-active
