### ISSUE TITLE
Blt:validate should check for deprecated Drupal core functions in custom code 

### ISSUE THREAD

**Issue by saitanay** [acquia/blt#1956]
Based on http://dri.es/making-drupal-upgrades-easy-forever , keeping module code updated replacing any usage of deprecated functions will theoretically keep your website Drupal 9 ready. 

Should be great if blt allows checking for deprecated function usages in the codebase (especially in the custom code) via blt validate command.

**Comment by grasmash** [comment]
Best tool I could find: https://packagist.org/packages/sensiolabs-de/deprecation-detector
