### ISSUE TITLE
blt setup does not generate target-hooks

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#1957]
Just started a new BLT project when I noticed there are no target hooks in the project.yml file like there was on my previous project.

Where are these located now? Do we have to manually add them to the project.yml file?

**Comment by arknoll** [comment]
@kevinquillen I am assuming your previous projects were using a version of BLT older than 8.9.0. Starting with 8.9.0 BLT uses Robo. Robo offers a much more robust way to hook in and extend the build process. You will find the new way of extending/overriding BLT here http://blt.readthedocs.io/en/stable/readme/extending-blt/

**Comment by kevinquillen** [comment]
Yes. Previously all I had to do was enter a path to a script file which called other bash scripts (in project.yml).

**Comment by grasmash** [comment]
Yes, here is an example:
http://blt.readthedocs.io/en/8.x/readme/frontend/#build

**Comment by grasmash** [comment]
And here is a list of all hooks:
https://github.com/acquia/blt/blob/8.x/config/build.yml#L146

**Comment by kevinquillen** [comment]
Thanks!

**Comment by arun9989** [comment]
@grasmash the given links in above comments are broken:

http://blt.readthedocs.io/en/8.x/readme/frontend/#build
https://github.com/acquia/blt/blob/8.x/config/build.yml#L146
