### ISSUE TITLE
Support for update hooks that depend on configuration changes

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#1977]
Currently, BLT runs update hooks prior to importing configuration changes as part of setups, refreshes, and deploys.

This is problematic for some projects that wish to fulfill a use case like this:

1. Add a new taxonomy vocabulary via config management (i.e. config split)
2. Populate that vocabulary with default terms via an update hook

Back in the era of Features (as far back as D7 even), we had some very good reasons for running update hooks prior to config imports (i.e. features imports), although I'm sure I can't remember all of them. To accomplish a use case like this, we recommended manually importing requisite Feature config as part of the update hook. This was mildly irritating as a developer, but worked fine.

I'm not sure what the best solution is now that we are transitioning to config split, and I'm open to suggestions. A few options:

1. Run update hooks _after_ config imports, just for folks using config split as a CM strategy. This is easy enough to implement, but I worry that there are a few (very rare) cases where you would legitimately want to run updates before anything else in order to fix corrupt config.
2. Provide or document a helper function that developers can place in their update hook to import necessary config as part of the update hook.
3. Recommend that projects handle this in two steps... deploy the configuration change, then deploy the update hook (the current workaround)

cc @scottreese

**Comment by grasmash** [comment]
> Provide or document a helper function that developers can place in their update hook to import necessary config as part of the update hook

This seems like a simple, low risk solution. Would in need to import a single config entity?

**Comment by danepowell** [comment]
We've already documented how to read individual config files here: https://github.com/acquia/blt/blob/8.x/readme/configuration-management.md#updating-custom-fields-and-schema

Maybe we just need to add a version of that that reads from the default config directory rather than from a Feature.
