### ISSUE TITLE
Namespace problem when running blt vm

### ISSUE THREAD

**Issue by adriadrop** [acquia/blt#1980]
Just following this instructions here
https://blt.readthedocs.io/en/stable/readme/creating-new-project/

I didnt even change the 
composer create-project --no-interaction acquia/blt-project MY_PROJECT

and I used MY_PROJECT as it is for testing. I got this below (when I changed this to test1, works properly.

```
Bringing machine 'MY_PROJECT' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The hostname set for the VM should only contain letters, numbers,
hyphens or dots. It cannot start with a hyphen or dot.


[Exec]  Exit code 1  Time 2.02s
[error]  Drupal VM failed to boot. Read Drupal VM's previous output for more information. 
```

**Comment by thom8** [comment]
Underscores aren't supported in the hostname.

see - https://github.com/mitchellh/vagrant/blob/34addec79667ecba353e1f6b48101c77e8f759d8/templates/locales/en.yml#L1633

**Comment by adriadrop** [comment]
Yes, and I see message says the same if you read it carefully. Probably documentation example of using "MY_PROJECT" as name isn't best way to make an example as people would go and call it some name with underscore.

**Comment by thom8** [comment]
Yeah, something like `my-project` would be a safer option.
