### ISSUE TITLE
Cannot upgrade to Drupal 8.4 with a released version of BLT because of drush version

### ISSUE THREAD

**Issue by benjifisher** [acquia/blt#1985]
My system information:
* Operating system type: OS X
* Operating system version: 10.12.6
* BLT version: 8.8.7

Sorry for not following the standard format, but I do not think it will be helpful here.

According to the "Current status" section of https://www.drupal.org/node/2874827, Drupal 8.4 is not compatible with a local drush 8.

I think the problem is that they require different versions of some symfony components.  Drupal 8.4 is compatible with a globally installed drush 8.1.12 or higher, but that does not help.

BLT already updated to drush 9 in ce65adc (although the commit message does not mention this).  So I think I can update to Drupal 8.4.0-rc1 if I also update to BLT 8.x-dev.  I would be happier if BLT 8.9.4 were released ASAP, including that commit, so that I could update to a released version instead of a dev version.

**Comment by grasmash** [comment]
I will merge Drush 9 support into 8.9.x. In the meantime, you can use `"drush/drush": "9.0.0-beta4 as 8.1.13"`
