### ISSUE TITLE
Speed up VM builds with beetbox

### ISSUE THREAD

**Issue by thom8** [acquia/blt#1986]
[beetbox](https://github.com/beetboxvm/beetbox) now offers feature parity with BLT so the preprovisioned base box can be used with Drupal VM.

I've been using it successfully for the last couple of months without any issues and the build times have gone from ~25 mins to ~3 mins.

A new base box is automatically built by [Atlas](https://app.vagrantup.com/beet) every [2 weeks](https://github.com/beetboxvm/beetbox/releases) & build scripts are available in the [project](https://github.com/beetboxvm/beetbox/blob/master/provisioning/ubuntu-16.04.json) if you'd prefer to build your own.

To make use the project base box just create the file -- `box/local.config.yml` with the following:

```yaml
---
vagrant_box: beet/box
workspace: "/beetbox/workspace/{{ php_version }}"
installed_extras: []
```

* `workspace` is optional but it's the beetbox default so won't redownload packages that are already available.
* `installed_extras` is only required if you're installing anything in addition to the defaults as everything else is preprovisioned.

**Comment by grasmash** [comment]
@geerlingguy Any opinions on using this?

**Comment by geerlingguy** [comment]
Beetbox has been well-maintained and I have no problems using it—the only thing I'd want to make sure of is that projects upgrading / switching to it from the other base boxes don't run into any strange side effects.

**Comment by thom8** [comment]
I've found it to be far more stable when doing frequent builds as it doesn't depend on a whole bunch of 3rd party services being available (& working) during the VM builds.

Also if we're able to get linked clones working again -- https://github.com/geerlingguy/drupal-vm/pull/1528 (I'm using a patch atm) each project only requires a very small amount of disk as it clones from the prebuilt base image.

**Comment by thom8** [comment]
As a bonus, it's also smaller than the default base box 

`737 MB` - https://app.vagrantup.com/beet/boxes/box
`760 MB` - https://app.vagrantup.com/geerlingguy/boxes/ubuntu1604
