### ISSUE TITLE
Support for automatically running module phpunit tests if present

### ISSUE THREAD

**Issue by terescode** [acquia/blt#1992]
My system information:
* Operating system type: drupalvm (ubuntu)
* Operating system version: 14.04
* BLT version: 8.7.5

Is there a way to have module level phpunit tests (in a `custom/modules/tests` sub-dir) *automatically* run, if present, during tests:phpunit or any other target?

If not on our current version of BLT (8.7.5) then on later versions or possibly with the new Robo enhancements?

Thanks.

**Comment by greylabel** [comment]
@terescode Yes. Better support for running unit tests was just added in the `8.x` branch so it should be in a future release. https://github.com/acquia/blt/pull/1960/files

@grasmash Should we consider pulling these into `8.9.x` as well?

**Comment by terescode** [comment]
@greylabel yup, saw that new feature in 8.9.x and that is a great step forward.  My only concern there was getting folks that may add new modules to "remember" to go add it to the `project.yml`. Granted that is a small concern.  Still would be awesome if it would just check existence for any `docroot/modules/custom/*/tests` dir.  Could potentially have a blacklist to make it faster or skip things where you see .feature.info if folks are using features etc.

**Comment by grasmash** [comment]
8.x please! We can backport to 8.9.x.

**Comment by greylabel** [comment]
@terescode Would the `group` option be suitable option for your use case?

**Comment by grasmash** [comment]
@greylabel How would the group option allow auto-detection of tests?

**Comment by greylabel** [comment]
@grasmash It wouldn't, but would provide a way to bundle the custom tests you wanted to run, if you only wanted a subset.

@terescode With the code in the PR I linked about you should be able to add something like the below to `project.yml`. If you need a DB connection, copy `phpunit.xml.dist` to `phpunit.xml`, fill in your details, and use that as your `config`. (Note: I have only really tested this running inside the VM.)

```
phpunit:
  -
    config: ${docroot}/core/phpunit.xml.dist
    path: '${docroot}/modules/custom'
```

**Comment by greylabel** [comment]
@terescode Did you try this approach?

**Comment by greylabel** [comment]
I think this can be closed. Further improvements will be made in #1787.

**Comment by lcatlett** [comment]
closing in favor of #1787
