### ISSUE TITLE
Phing tasks, how are they replaced

### ISSUE THREAD

**Issue by adriadrop** [acquia/blt#2000]
I see Phing has been replaced all together with Robo, which is nice so those nasty xml are done with.  I am struggling to find out how Phing tasks have been replaced. We had those big xmls like setup.xml which would determine what will be done on blt setup command. How can this be views now and altered?

**Comment by grasmash** [comment]
Phing has been replaced with Robo. You can create a custom Robo command or hook as documented here: 
http://blt.readthedocs.io/en/8.x/readme/extending-blt/#adding-a-custom-robo-command
