### ISSUE TITLE
Replace post-code-deploy ACSF hook with db update Factory Hook

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#2003]
Currently ACSF BLT code deploy updates are run via a post-code-deploy hook which runs after the ACSF code update has completed. This was a workaround until a db-update factory hook was created in ACSF which will allow for customizing the current ACSF code update process on the update environments rather than the live environments. Replacing the post-code-deploy blt invocation with the db-update Factory Hook will allow for running BLT commands on the update environment and switching the DNS after completion rather than running them directly on the live environments which may present challenges with scalability. Internal ticket: DG-17926

**Comment by hoff331** [comment]
See ticket https://backlog.acquia.com/browse/CSPF-646

**Comment by danepowell** [comment]
https://kbv2.acquia.com/site-factory/tiers/paas/workflow/hooks/dbupdate
