### ISSUE TITLE
Couldn't install blt on ubuntu 16.04 machine

### ISSUE THREAD

**Issue by evgeniy85** [acquia/blt#2030]
My system information:
* Operating system type: DrupalVM
* Operating system version: Ubuntu 16.04
* BLT version: 8.x

Output of `blt doctor`:
Drush could not find the docroot.

I want to install blt on my Ubuntu machine, I am follwoing the instructions here:
http://blt.readthedocs.io/en/8.8.x/readme/creating-new-project/

When I run this command:
```
composer run-script blt-alias
```

I get the following output:
```
[InvalidArgumentException]                         
  Script "blt-alias" is not defined in this package
```

if I go further and want to install drupal vm with
```
blt vm 
```

I get the following output:
```
[Exec]  Exit code 2  Time 28.123s
[error]  Unable to install geerlingguy/drupal-vm package. 
[error]  Command `composer:require 'geerlingguy/drupal-vm' '~4.3'` exited with code 1. 
```

And I expected this to happen:
Could you point what should I do to run proper installation?

**Comment by grasmash** [comment]
A few questions for you:

- You listed your BLT version is 8.X, but if you follow the instructions at http://blt.readthedocs.io/en/8.8.x/readme/creating-new-project/, then you would be using 8.9.5.  Are you sure that you're 8.x?
-  What directory are you executing the commands from? Can you share the output of `ls`?

**Comment by evgeniy85** [comment]
Actually I didn't find the version within my folders, so when I created a project I used this command:
```
composer create-project --no-interaction acquia/blt-project test
```

from my folder 'test' I ran the commands from the initial message, but when I do ```ls``` I got:
```
blt  composer.json  composer.lock  config  docroot  drush  drush.wrapper  patches  phpcs.xml.dist  README.md  tests  vendor

```

**Comment by grasmash** [comment]
Okay, a few more suggestions:

-  Update to the latest version of composer
-  Please share the full output for the commands that are problematic,  and include the `-vvv` flag for maximum verbosity. For instance, what is the full output of the command `blt vm -vvv`?  That should provide some helpful hints.

**Comment by evgeniy85** [comment]
update composer to latest version and I was need to install ```sudo apt-get install php-bz2```. 
It is almost working exept ```blt vm``` ended with this:
```
BLT has created default configuration for your Drupal VM!
 * The configuration file is /var/www/acquia/test/box/config.yml.
 * To customize the VM, follow the Quick Start Guide in Drupal VM's README:
   https://github.com/geerlingguy/drupal-vm#quick-start-guide
 * To run drush commands against the VM, use the @test.local alias.
 * From now on, please use vagrant commands to manage your virtual machine.

> setup:settings
PHP Fatal error:  Uncaught Error: Undefined class constant 'DUMP_OBJECT_AS_MAP' in /var/www/acquia/test/vendor/symfony/yaml/Dumper.php:88
Stack trace:
#0 /var/www/acquia/test/vendor/symfony/yaml/Yaml.php(98): Symfony\Component\Yaml\Dumper->dump(Array, 3, 0, 0, false)
#1 /var/www/acquia/test/vendor/acquia/blt/src/Robo/Commands/Vm/VmCommand.php(188): Symfony\Component\Yaml\Yaml::dump(Array, 3, 2)
#2 /var/www/acquia/test/vendor/acquia/blt/src/Robo/Commands/Vm/VmCommand.php(71): Acquia\Blt\Robo\Commands\Vm\VmCommand->localInitialize()
#3 [internal function]: Acquia\Blt\Robo\Commands\Vm\VmCommand->vm(Array)
#4 /var/www/acquia/test/vendor/consolidation/annotated-command/src/CommandProcessor.php(235): call_user_func_array(Array, Array)
#5 /var/www/acquia/test/vendor/consolidation/annotated-command/src/CommandProcessor.php(181): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/acquia/test/vendor/consolidation/annotated-command/src/CommandProcesso in /var/www/acquia/test/vendor/symfony/yaml/Dumper.php on line 88```

if I run  ``` blt vm -vvv```
it shows

```blt -vvv
[Robo\Common\ProcessExecutor] Running vagrant status --machine-readable in /var/www/acquia/test
[debug] vagrant test.metadata = provider
[debug] vagrant test.provider-name = virtualbox
[debug] vagrant test.state = not_created
[debug] vagrant test.state-human-short = not created
[debug] vagrant test.state-human-long = The environment has not yet been created. Run `vagrant up` to\ncreate the environment. If a machine is not created%!(VAGRANT_COMMA) only the\ndefault provider will be shown. So if a provider is not listed%!(VAGRANT_COMMA)\nthen the machine is not created for that environment.
[debug] vagrant .ui = info
[error]  Drupal VM config has been initialized, but the VM has not been created. Please re-run `blt vm`. 
[debug] Drupal VM is not initialized.
BLT 8.9.2

Usage:
  command [options] [arguments]
 ```

**Comment by grasmash** [comment]
The following combination of packages has been known to work:

`sudo apt-get install -y php5.6-cli php5.6-curl php5.6-xml php5.6-mbstring php5.6-bz2 php5.6-gd php5.6-mysql mysql-client unzip git`

**Comment by evgeniy85** [comment]
Thank you! I got it installed, there are few notes though:

- I have changed profile from lightening to standard but it still installed me lightening
- Drupal vm by default installed php 5.6 so doctrine thrown me an fatal error, so I was need to do provisioning to install 7.1
But after that it works ok now.

If you could point me is it possible to have this working with github(gitlab, pantheon) ? Is there documentation ?
