### ISSUE TITLE
Remove architecture.md

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#204]
Our team encounters several problems with [architecture.md](https://github.com/acquia/blt/blob/8.x/template/readme/architecture.md) on a daily basis.

1. **Clobbered by updates**: Running `blt blt:update` overwrites this file with the upstream version every time it is run. architecture.md seems like an odd duck, as it's the only readme document provided by BLT that is _intended_ to be modified for each project. We could modify the update script to exclude it, but just read on for now...
2. **Difficult to author**: Don't get me wrong, I absolutely love Markdown, but I don't think it's the best choice of format for a document that we might want to encourage developers to collaboratively edit. Opening a Google Doc and simply collaborating in place is objectively easier than writing Markdown, previewing / compiling it, submitting a pull request, etc...
3. **Difficult to share**: We frequently get requests from non-technical stakeholders to view the architecture document. Since these folks don't have access to the Github repo and probably won't know how to view Markdown anyway, this means we currently have to export the doc to PDF and manually distribute it to stakeholders, and repeat this on a regular basis as the document is updated.

I doubt these challenges are specific to our project (I don't think I've actually seen another Acquia project using this template, which supports this assumption) Furthermore, I think the architecture document is much more closely aligned with Acquia's delivery practice than with the rest of the BLT framework. So it seems like the best solution would be to remove it from BLT and convert it to a Google Doc.

We would just want to make sure that this template still gets into the hands of TAs on new projects (I think we have an internal project for that).

Totally open to discussion / counter opinions.

**Comment by janaksingh** [comment]
> So it seems like the best solution would be to remove it from BLT and convert it to a Google Doc.

Completely agree. 

If everyone is onboard with this proposal. I can help getting the various .MD files into Google Docs and format them accordingly - ready to be cloned into projects.

**Comment by haynescw** [comment]
My opinions is to leave the readme's as they are. If you are using git, you can just checkout the version that BLT over wrote, as a temp fix, but there should be an issue to fix BLT overwriting the readme files in the update process. I think the reasoning behind updating it is to keep it current with changes to the read me's that pertain to BLT specific things, but you should be able to do a diff on those files and merge them accordingly.  Moving the documentation outside of the project seems to be a person/company specific change. Convention would be to keep the documentation for the project with the project.

**Comment by geerlingguy** [comment]
We never popped it into a Google Doc, though, to my knowledge. It was a good template/jumping-off point for project Architecture documents, and made sure I didn't forget certain things (I could delete what I didn't need). Did anyone work on this, or should I do it on my own?

**Comment by danepowell** [comment]
@geerlingguy I maintain the Google doc and will ping you about it separately.
