### ISSUE TITLE
Assert existence of .nvmrc or .node-version

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#2040]
In keeping with best practices, BLT doctor should assert existence of .nvmrc or .node-version in the repository root. If one of these is not present, a warning should be logged.

- [ ]  add a check to BLT doctor that verifies the existence of .nvmrc or .node-version in the repository root.
- [ ]  add a check to BLT doctor that verifies the existence of .nvmrc or .node-version in theme dir, if that theme contains package.json
- [ ] add default .nvmrc to template dir
- [ ] add entries for  .nvmrc and .node-version to https://github.com/acquia/blt/blob/8.x/scripts/blt/ignore-existing.txt

**Comment by wu-edward** [comment]
PR #2042
