### ISSUE TITLE
Local patch installs locally but fails to install in CI environment

### ISSUE THREAD

**Issue by amytackett** [acquia/blt#2045]
My system information:
* Operating system type: debian
* Operating system version: jessie
* BLT version: 8.9.5

When I run this command:
```
blt setup --define drush.alias='${drush.aliases.ci}' --define environment=ci --no-interaction --yes -v
```
which runs
```
setup:composer:install
```

I get the following output:
```
Could not apply patch! Skipping. The error was: The "./patches/AddButtonStylesToLinkit.patch" file could not be downloaded: failed to open stream: No such file or directory
```

And I expected this to happen:
The patch to be applied.

When I run
```
blt setup
```
locally, the patch installs fine. The patch is committed to the patches directory and has been pushed to my repo. 

Wondering if you have seen this before and / or if you have any ideas why the local patch would be picked up locally but fail in our CI environment.

**Comment by grasmash** [comment]
Yeah, that is a strange one.

How certain are you that the patch has been committed?  Can you view the file on GitHub?

**Comment by amytackett** [comment]
We are using Bitbucket, and I have checked at least 3 times to ensure that I can see the code in the develop branch of my fork.

**Comment by grasmash** [comment]
Ah, if you're a using bit bucket then you must be using your own CI script.  I would be interested in seeing it.

One thought, does your script execute commands from the repository root?  I wonder if the working directory could have something to do with it. Also, if there is a possibility of a difference in file structure, like symbolic links.

**Comment by amytackett** [comment]
Yes, we are using Bamboo with Docker for CI. We basically stole the CI scripts from Travis and then just modified as needed to get them running in our environment.

The issue has been resolved. It was caused by case sensitivity. The patch file had an uppercase I in the name on the file system, but a lowercase i in the name in composer.json. It's a little odd to me that this didn't cause an issue for me on OS X, but in any case, it is resolved now. 

Thanks for taking the time to take a look!

**Comment by grasmash** [comment]
@amytackett would you be willing to contribute the Bamboo script?

**Comment by amytackett** [comment]
Yes, definitely. We are also planning on contributing the dockerfile that is necessary to get things to run in Bamboo. We just have some cleanup work to do before it is ready for that. We have stories in our backlog to get the cleanup work done :)

**Comment by cosmicdreams** [comment]
Came here because I found the cross-section of blt and bamboo.  Did this init script ever get rolled into a patch?
