### ISSUE TITLE
Add additional settings file include options

### ISSUE THREAD

**Issue by greylabel** [acquia/blt#2054]
While BLT provides a lot of boilerplate config through its `*.settings.php` files, it would be nice to have some additional options to extend these with project customizations.

- [ ] Add support for including multiple global settings files.
- [ ] Add support for including a local global settings file.
- [ ] Add support for site-specific secrets files.

**Comment by greylabel** [comment]
Probably needs some docs updates too.

**Comment by dpagini** [comment]
@greylabel I had added [this section](https://github.com/acquia/blt/blob/8.x/settings/blt.settings.php#L214-L216) a while back to the project... this loads a file from individual site directories called `includes.settings.php` where you could then include a global include file (which is what we use it for), or include site specific includes. Not sure if that helps you with the first/second bullets?

**Comment by greylabel** [comment]
@dpagini, thanks for pointing that out. I added [this section](https://github.com/acquia/blt/pull/2055/files#diff-3f01be0f15533ad5bd0f496e6bec3e74R194) for two reasons; it doesn't use `$site_dir` so it is more multisite friendly and it uses `glob` so you can include multiple files, e.g. `cdn.settings.php, `fast404.settings.php`, etc.
