### ISSUE TITLE
Document how to ignore an upstream patch

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#2056]
My system information:
* Operating system type: OSX
* Operating system version: Sierra
* BLT version: 8.9.2

I am looking to ignore an upstream patch (in this case a patch to `simple_oauth` provided by Acquia Lightning 2.17. I believe in the docs, there used to be an example on how to ignore an upstream patch (I know because I copied this example verbatim from it perhaps last year):

```json
"patches-ignore": {
  "drupal/lightning": {
    "drupal/panelizer": {
      "This patch has known conflicts with our Quick Edit integration": "https://www.drupal.org/files/issues/2664682-49.patch"
    }
  }
}
```

The above code does not work as intended today. And I also do not see reference on how to do this in the latest version of the docs http://blt.readthedocs.io/en/latest/template/patches/README/

Is this still achievable in BLT 8.9.x?

**Comment by grasmash** [comment]
This is not actually a feature of BLT, it is a feature provided by [composer patches](https://github.com/cweagans/composer-patches).

You can find the relevant documentation [here](https://github.com/cweagans/composer-patches#ignoring-patches) on that project.

 If it is not working as expected, please file an issue in that issue queue.
