### ISSUE TITLE
BLT Continues to Use Config Default Directory During Installation

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2071]
My system information:
* Operating system type: Mac OS 
* Operating system version: 10.11.6
* BLT version: 8.x-dev commit: cfe62bd

Output of `blt doctor`:
```
blt doctor
[error]  Invalid drush alias '@project.local'. 
[error]  Invalid drush alias '@project.local'. 
```

When I run this command:
```
blt setup
```

I get the following output:
```
Running /var/www/<project>/vendor/bin/drush site-install lightning install_configure_form.update_status_module='array(FALSE,FALSE)' install_configure_form.enable_update_status_module=NULL --site-name='Project' --site-mail=no-reply@acquia.com --account-name=cnJqTKkXac --account-mail=no-reply@acquia.com --locale=en --config-dir=../config/default --uri=default --yes --verbose in /var/www/<project>/docroot
```

And I expected this to happen:
I have followed the steps on https://github.com/acquia/blt/wiki/Drupal-8.3-to-8.4-upgrade-guidance to set my project.yml so that:

```
setup:
  drupal:
    install: { import-config: 'false' }
```

however, during the blt setup process i am still getting a config-dir parameter in the install, and as a result the installation profile is being changed to minimal instead of lightning.

**Comment by grasmash** [comment]
False should not be a string. Looks like the yaml-cli command is not properly setting boolean values.

**Comment by mikemadison13** [comment]
yeah i just came to the same conclusion.

**Comment by grasmash** [comment]
The documentation for the upgrade guidance just needs to be updated.  You can file an issue for the yaml CLI package if you'd like.
