### ISSUE TITLE
BLT / Features Incompatibility

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2072]
My system information:
* Operating system type: Mac OS
* Operating system version: 10.11.6
* BLT version: 8.x-dev cfe62bd53f800e5c2dcb39045fbf23a24b99192a

When I run this command:
```
blt setup
```

I get the following output:
```
Checking for features overrides...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/<project>/vendor/bin/drush fl --bundle=<project> --uri=default in /var/www/<project>/docroot
PHP Fatal error:  Call to undefined function drush_hide_output_fields() in /var/www/<project>/docroot/modules/contrib/features/drush/features.drush.inc on line 218

Fatal error: Call to undefined function drush_hide_output_fields() in /var/www/<project>/docroot/modules/contrib/features/drush/features.drush.inc on line 218
 [error]  Drush command terminated abnormally due to an unrecoverable error.
Error: Call to undefined function drush_hide_output_fields() in /var/www/<project>/docroot/modules/contrib/features/drush/features.drush.inc, line 218 
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 255  Time 3.967s
[error]  Unable to determine if features in bundle <project> are overridden. 
[error]  Command `setup:config-import ` exited with code 1. 
Connection to 127.0.0.1 closed.
macbookpro-mikemadison:<project> mike.madison$ drush @<project>.local features-list-packages --format=json --bundle=<project>
 [error]  Unknown option: --format.  See `drush help features-list-packages` for available options. To suppress this error, add the option --strict=0. 
Connection to local.<project>.com closed.
 [error]  Unknown option: --format.  See `drush help features-list-packages` for available options. To suppress this error, add the option --strict=0. 
```

And I expected this to happen:

It would appear that Features is not compatible with Drush 9. I have bugged this issue here: https://www.drupal.org/node/2913651

In the meantime, the thing that is exploding is the final step where we check for features overrides because the features-list-packages code has a function that isn't supported in Drush 9. We could potentially remove this portion of the features import process and bypass the incompatibility.

**Comment by danepowell** [comment]
As a temporary workaround, I think you can disable the Features overrides check by setting `cm.features.no-overrides = false` in project.yml.

**Comment by mikemadison13** [comment]
this override DID work.

should we comment out the features overrides check for the time being in BLT so not everyone has to do this?

**Comment by grasmash** [comment]
Yes.

**Comment by mikemadison13** [comment]
i'll get a PR going for that @grasmash
