### ISSUE TITLE
Behat Headless Chrome

### ISSUE THREAD

**Issue by amytackett** [acquia/blt#2083]
My system information:
* Operating system type: Debian
* Operating system version: Jessie
* BLT version: 8.9.6

When I run this command:
```
blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --define behat.web-driver=chrome --yes -v
```

I get the following output:
```
[info] Waiting for response from localhost:9222...
...
[info] Waiting for response from localhost:9222...
[info] Killing running google-chrome processes...
[info] Killing all processes on port '9222'...
[info] Killing all processing containing string 'runserver'...
[info] Killing all processes on port '8888'...
[error]  Timed out. 
```

And I expected this to happen:
Headless chrome to work.

I am trying to get my tests running in Bamboo on my Docker container using headless chrome, unsuccessfully. I found this issue that indicates that support for phantomJs is being phased out and chrome is being phased in. I'm wondering if headless chrome has been tested successfully? If so, I'm wondering if perhaps there is another setting I need to pass into the blt tests:all command? Or, perhaps more likely, the issue is with my docker container.

I will continue down the path of investigating my docker container, but I would appreciate any other insights that you may have as to what might be the cause of this issue.

**Comment by danepowell** [comment]
We have seen issues in the past where security permissions on containers prevent headless chrome from running. If you do some googling you'll probably run across similar reports.

In at least one case that I saw, downgrading Docker to version 1.12.6 from 17.03.1-ce solved the timeouts.

If that works please let us know so we can document it.

**Comment by amytackett** [comment]
I have resolved this issue. It turns out the docker container was the root cause of the problem. To resolve the issue, I had to pass the following argument to the docker run command: --cap-add=SYS_ADMIN

Perhaps this was the issue in the other cases you have seen. This solution worked for me with docker version 17.09.0-ce.

**Comment by danepowell** [comment]
Glad that lead you to a solution. I also documented this for posterity.

**Comment by vingov** [comment]
I am using bitbucket pipelines to run my builds, they are not supporting root privileges for containers, Is there any other way to execute chrome headless without the ```  --cap-add=SYS_ADMIN``` flag? Its not recommended to run containers with root privileges.
