### ISSUE TITLE
Attempt to automatically fix bad config exports

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2092]
The test for config overrides is probably broken right now, because the command we were using (`drush cex -n`) is no longer supported in Drush 9: https://github.com/drush-ops/drush/issues/3014

However, I've opened a PR to replace that with a new cleaner command: `drush config:status`
https://github.com/drush-ops/drush/pull/3020

It should be fairly straightforward to use this new command instead. We either have to patch Drush or wait for a new release though.

**Comment by grasmash** [comment]
I love that PR.

**Comment by grasmash** [comment]
The command is not currently broken, this line is the issue: https://github.com/acquia/blt/commit/651f97cbc87bb15e606e7200c85f17e5c236b1fb#diff-84e39e3348365c899001469c1fdaf292R272

However, using that new command would be preferable to our current approach.

**Comment by danepowell** [comment]
Yeah actually I think you're right, this does still work, but now it also writes the configuration to disk as part of the test (since `yes` is the default response for `cex`). Which... may or may not be a problem. It could actually be a feature, since re-exporting config is the recommended solution to this test failing!

**Comment by grasmash** [comment]
It looks like your work was merged and released today!

**Comment by danepowell** [comment]
I think the current behavior is actually desired (since BLT will basically attempt to automatically fix a bad config export). We just need to update the copy of the error message to indicate this.

**Comment by danepowell** [comment]
Since this is really just a documentation update for Drush 9, I backported it to 9.x
