### ISSUE TITLE
Fix usage of drush assume (--yes / --no)

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2093]
If my understanding is correct, there is no difference between `--yes` and `--no-interaction` in Drush 9. Both simply use whatever the "default response" is for any prompts. Source: https://github.com/drush-ops/drush/issues/3014#issuecomment-334316826

There's no way to force either yes or no.

So I think we should just remove the "assume" option completely, and pass `--no-interaction` for all commands. Unless you want to have interactive commands as an option.

**Comment by grasmash** [comment]
We should probably replace `assume()` with `interactive()`.  In some cases we do want to drush to be interactive.
