### ISSUE TITLE
Undeprecate `acsf:drush:init`

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#2094]
https://github.com/acquia/blt/pull/2089/files#diff-221d1f6c31394f10b3ffb65d17150cc6R49

This depends on a new release of the acsf module that supports drush 9.

backlog: DG-17922

**Comment by danepowell** [comment]
The new ACSF module release is blocked on https://github.com/drush-ops/drush/pull/3110

**Comment by grasmash** [comment]
This will be unblocked by https://github.com/drush-ops/drush/pull/3235.

**Comment by danepowell** [comment]
https://github.com/drush-ops/drush/pull/3235 was merged, woot. So we just need to wait on Drush 9.0.0-rc2 and a patched ACSF module.
