### ISSUE TITLE
BLT doesn't define file system storage intelligently

### ISSUE THREAD

**Issue by bhasselbeck** [acquia/blt#211]
Steps to reproduce: 
1. Export a BLT project using this repository
2. Setup the project
3. Deploy code to Acquia Cloud
./blt.sh deploy -Ddeploy.branch=<branch> -Ddeploy.commitMsg='<commit>'
4. SSH into Acquia Cloud or use Aliases to install Lighting, or a standard profile
5. Note that the filesystem seems to not be configured properly

Also, note that settings.php doesn't define file storage paths:

- https://github.com/acquia/blt/blob/8.x/template/docroot/sites/default/settings.php#L517
- https://github.com/acquia/blt/blob/8.x/template/docroot/sites/default/settings.php#L502

We need to set standards for the filesystem based off of
1. Acquia Cloud
2. Local Development
3. ACSF

**Comment by pixlkat** [comment]
Questions:

1. Should we be enabling private file system by default?
2. I am unsure of what the standards for ACSF are for filesystem paths.  

For now, I have created a PR which adds a filesystem-specific settings file with some generic AC settings.
