### ISSUE TITLE
Prompt users for information after project creation

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#2115]
Prompt the user with a series of questions  after the `internal:create-project` and `internal:add-to-project` commands. 

The answers to these questions should be used to pre-populate configuration in `project.yml` and to prompt the automatic execution of commands like `blt vm`  and `blt ci:travis:init`.

Some example questions:
* What is the project name?
* Enter your git deployment remote?
* Would you like to generate a Cog-based something?
* Would you like to create a virtual machine? 
* Would you like to initialize configuration for a continuous integration solution?

Ideally, we will also have some way for the user to specify a yaml file which contains the answers to all these questions. This would permit developers to quickly spin up new projects using a predefined set of configuration.

**Comment by patrickcate** [comment]
This would be a great feature.

Some additional questions I could think of:
* What install profile would you like to use?
* What cm strategy would you like to use?

**Comment by grasmash** [comment]
> What cm strategy would you like to use?

Added.

> What install profile would you like to use?

I'd prefer not to do this unless we limit the options that are verifiably valid, like "minimal, standard, lightning."

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2469
https://github.com/acquia/blt/pull/2487
