### ISSUE TITLE
Fix failing blted8 build

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#2118]
https://github.com/acquia/blt/pull/1885 has introduced a regression causes the blted builds to fail: https://travis-ci.org/acquia-pso/blted8/builds/283942518.

>   [Wikimedia\Composer\Merge\MissingFileException]                       
  merge-plugin: No files matched required 'blt/composer.required.json'  

This is a bit strange because it occurs after the second `composer self-update` call. The first one completes successfully.

I wouldn't expect the Wikimedia merge plug-in to even be executing during this command.

We may be able to fix this by simply removing one of the calls to that command, but I wonder if this will affect other projects as well or if it is an extreme edge case.

**Comment by danielnitschelc** [comment]
@grasmash just a hunch, but have you tried clearing the travis cache? I've had that issue before when altering certain composer settings/paths.

**Comment by grasmash** [comment]
@danielnitschelc well that did fix it! Perhaps we should stop caching those dirs, at least for blted8.
