### ISSUE TITLE
Illegal string offset 'drush-version'

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2123]
My system information:
* Operating system type: Mac OS
* Operating system version: 10.11.6
* BLT version: 8.9.8

When I run this command:
```
blt sync:db
```

I get the following output:
```
> sync:db
Executing command blt sync:db --define drush.alias=self inside of Drupal VM...
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> setup:settings
PHP Warning:  Illegal string offset 'drush-version' in /var/www/<project>/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 262

Warning: Illegal string offset 'drush-version' in /var/www/<project>/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 262
```

And I expected this to happen:
This doesn't seem to stop anything from working, but I noticed it in the output.

**Comment by sherakama** [comment]
I'm getting the same on just about any sync:* command

`PHP Warning:  Illegal string offset 'drush-version' in /httpdocs/se3_blt/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 262
PHP Stack trace:
PHP   1. {main}() /httpdocs/se3_blt/vendor/acquia/blt/bin/blt:0
PHP   2. require_once() /httpdocs/se3_blt/vendor/acquia/blt/bin/blt:11
PHP   3. require_once() /httpdocs/se3_blt/vendor/acquia/blt/bin/blt-robo.php:14
PHP   4. Acquia\Blt\Robo\Blt->run() /httpdocs/se3_blt/vendor/acquia/blt/bin/blt-robo-run.php:42
PHP   5. Robo\Runner->run() /httpdocs/se3_blt/vendor/acquia/blt/src/Robo/Blt.php:235
PHP   6. Symfony\Component\Console\Application->run() /httpdocs/se3_blt/vendor/consolidation/robo/src/Runner.php:175
PHP   7. Symfony\Component\Console\Application->doRun() /httpdocs/se3_blt/vendor/symfony/console/Application.php:120
PHP   8. Acquia\Blt\Robo\Application->doRunCommand() /httpdocs/se3_blt/vendor/symfony/console/Application.php:202
PHP   9. Symfony\Component\Console\Application->doRunCommand() /httpdocs/se3_blt/vendor/acquia/blt/src/Robo/Application.php:29
PHP  10. Symfony\Component\Console\Command\Command->run() /httpdocs/se3_blt/vendor/symfony/console/Application.php:891
PHP  11. Consolidation\AnnotatedCommand\AnnotatedCommand->execute() /httpdocs/se3_blt/vendor/symfony/console/Command/Command.php:264
PHP  12. Consolidation\AnnotatedCommand\CommandProcessor->process() /httpdocs/se3_blt/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
PHP  13. Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() /httpdocs/se3_blt/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
PHP  14. Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() /httpdocs/se3_blt/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
PHP  15. call_user_func_array:{/httpdocs/se3_blt/vendor/consolidation/annotated-command/src/CommandProcessor.php:235}() /httpdocs/se3_blt/vendor/consolidation/annotated-command/src/CommandProcessor.php:235`
