### ISSUE TITLE
BLT fails during setup with "blt setup" command

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#2125]
My system information:
* Operating system type: macOS
* Operating system version: High Sierra
* BLT version: 8.9.8

When I run this command:
```
blt setup
```

I get the following output:
```
> setup:toggle-modules
Executing command blt setup:toggle-modules --define drush.alias=self inside of Drupal VM...
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/module-dev/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50

```

And I expected this to happen:
 
The command to execute successfully.

I think this is related to now needing Drush 9 for 8.4. It looks like 8.1.15 is installed.

I get this error both on the command line and when I visit the local site.

**Comment by grasmash** [comment]
What is the BLT version?

**Comment by kevinquillen** [comment]
```
> blt --version
BLT 8.9.8
```

**Comment by alex-moreno** [comment]
Not sure if related,but you get the da be error when upgrading to drupal
8.4, because it needs php7

**Comment by kevinquillen** [comment]
Okay. I forgot to change the PHP version in config.yml.

**Comment by kevinquillen** [comment]
Now that I have specified PHP 7.1, I get this error when running `blt setup`:

```
Warning: Illegal string offset 'drush-version' in /var/www/module-dev/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 262
```

**Comment by kevinquillen** [comment]
Well, despite the warning, it succeeded. The issue was OOTB blt specifies PHP 5.6 in the config.yml, I forgot to change that to 7.x.

**Comment by grasmash** [comment]
We will be defaulting to PHP 7.1 in BLT9+.

**Comment by damontgomery** [comment]
@grasmash, I know this is closed, but I hit this issue today. I am on BLT `9.0.0-alpha2` and the version of `config.yml` for DrupalVM uses 5.6.

**Comment by alozie** [comment]
FWIW...ran into this issue w/BLT `8.9.11` (default verion of PHP set to `5.6`). Corrected as follows:
- changed PHP version in `config.yml` (using `7.1`)
- destroyed and rebuilt vagrant instance (`vagrant destroy` followed by `vagrant up`)
- reran `blt setup`
