### ISSUE TITLE
When using VM built with vm:init, NFS synced folder doesn't always mount correctly

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#214]
## Steps to Reproduce

  1. Build new BLT project
  2. Run `vm:init`
  3. `vagrant up` the new Drupal VM
  4. `vagrant ssh` into the VM
  5. `cd` into the synced folder dir (e.g. `/var/www/[project]`) and run `ls`

## Expected Results

  - Folder contains the [project] files as on the host machine.
  - Running `sudo mount` inside VM returns a result like `172.16.101.1:/Users/geerlingguy/Desktop/project on /var/www/project type nfs (rw,vers=3,udp,addr=172.16.101.1)`

## Actual Results

  - Folder is empty.
  - Running `sudo mount` inside VM doesn't return a mount for the `/var/www/[project]` folder.

I'm digging deeper into this now, and making sure it's not something that's fixed/working in BLT master vs. a slightly older version that might've had a problem with the default config.

**Comment by geerlingguy** [comment]
Note that some developers have reported that simply reverting to Vagrant 1.8.1 resolves the issue; this could be related to https://github.com/mitchellh/vagrant/issues/7443 (PR with fix here: https://github.com/mitchellh/vagrant/pull/7492).

**Comment by webkenny** [comment]
Wonder if this is somehow related to #241

**Comment by grasmash** [comment]
@geerlingguy Reading https://github.com/geerlingguy/drupal-vm/issues/783 suggests to me that this is not a BLT issue. Closing issue here--workarounds documented in https://github.com/geerlingguy/drupal-vm/issues/783

**Comment by geerlingguy** [comment]
Yep!
