### ISSUE TITLE
Add Factory Hooks required for ACSF site installs and updates

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#2159]
New Factory hooks are available which will allow hooking into BLT tasks for install, update, and deploy. Additionally, there are number of hooks needed on most ACSF projects that should be provided as suggestions. (suggestions may be commented as needed) The following should be provided:

- [x] db-pupdate #2003
- [x] post-install #2440
- [ ] post-settings-php
- [ ] post-sites-php
- [ ] post-theme-deploy
- [ ] pre-settings-pjhp
- [ ] pre-sites-php

Legacy cloud hooks should be removed where possible in favor of the above factory hooks

**Comment by danepowell** [comment]
One specific task I'll work on is replacing our current post-code-deploy/update hooks with factory-hooks/db-update: https://kbv2.acquia.com/site-factory/tiers/paas/workflow/hooks/dbupdate

**Comment by damontgomery** [comment]
@lcatlett, based on your work in #2440, should we mark off the post-theme-deploy hook?

Do the other hooks just need templates so that there is broad understanding that they exist? If so, I can add those. If we need other recommended hooks, do you have examples I can look through?

Thanks.

**Comment by lcatlett** [comment]
this can be closed with #2440 , #2227
