### ISSUE TITLE
Setup fails due to missing ACSF module

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2164]
My system information:
* BLT version: 9.x-dev (9.0.x)

BLT tries to uninstall `acsf` on local installs by default:
https://github.com/acquia/blt/blob/d6185828f7e272cb08e4061a3c5a163f7d024b39/template/blt/project.yml#L48

However, the ACSF module obviously doesn't exist unless you've specifically added it to your codebase, so `blt setup` subsequently fails with the error for any non-ACSF project:
> [error]  A specified extension does not exist: acsf
[error]  Could not toggle modules listed in modules.local.uninstall.

Note that this error is specific to Drush 9 (earlier versions return code 0)

To reproduce, simple set up a fresh 9.0.x install and add DrupalVM:
`composer create-project acquia/blt-project:9.x-dev --no-interaction blted9`
`blt vm`
`blt setup`

**Comment by lcatlett** [comment]
I think the acsf:init test was disabled intentionally because the acsf module is still being ported to Drush 9 - https://github.com/acquia/blt/pull/2089/files#diff-221d1f6c31394f10b3ffb65d17150cc6R49

**Comment by danepowell** [comment]
I don't think this has anything to do with acsf init though. In fact, I'd that command was running prior to setup in the tests it would conceal this bug.

**Comment by grasmash** [comment]
It doesn't fail on CI because the ACSF module is not in modules.ci.uninstall: https://github.com/acquia/blt/blob/9.1.x/template/blt/project.yml#L53

**Comment by grasmash** [comment]
We should add `acsf` to `modules.local.uninstall` during `blt acsf:init` rather than putting it there by default.
