### ISSUE TITLE
Multiple installation profiles and TravisCI

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#2166]
My system information:
* Operating system type: TravisCI
* Operating system version: Trusty
* BLT version: 8.9.6

We are looking to be able to test multiple installation profiles during TravisCI's tests. At the moment only a single install profile test is possible.

Is there an easy way to configure this?

**Comment by grasmash** [comment]
I'd suggest using Travis' matrix feature:

```
env:
  - PROFILE=lightning
  - PROFILE=custom
```

Then add a step to the `install` step:
```
install:
  - touch blt/project.local.yml
  -  ./vendor/bin/yaml-cli update:value blt/project.local.yml project.profile.name $PROFILE
```

**Comment by seanhamlin** [comment]
Thanks @grasmash!
