### ISSUE TITLE
sql-sync not availabe in drush

### ISSUE THREAD

**Issue by alex-moreno** [acquia/blt#2173]
so, I think there is a bug in blt because of an “incompatibility” in Drush. Drush does not support --uri in sql-sync, but blt tries to execute this:

``` /vendor/bin/drush sql-sync @bayerphweb.01live @bayerphweb.local --structure-tables-key=lightweight --create-db --sanitize --uri='http://phdebetaferon.bayerphweb.acsitefactory.com' --yes ```

Instead, using acsf tools properly configured, blt should try to execute this drush command:

```drush sql-sync @phdebetaferon.01live @bayerphweb.local```

When I run this command:
```
blt sync -D site=SITENAME
```

I get the following output:
```
Allways pulls the default database
```

And I expected this to happen:
```
It should pull the database for SITENAME
```

**Comment by danepowell** [comment]
@alex-moreno please make sure to include the version of BLT you are using in support requests

At any rate, I don't think there's support right now for multisite db syncs on ACSF in any version of BLT. That's coming in https://github.com/acquia/blt/pull/2154

In other words, you can define a default "remote" site to sync from in `project.yml` or `project.local.yml`, but you can't override this on-the-fly by passing a different site name to the sync command

@grasmash correct me if I'm wrong.

**Comment by alex-moreno** [comment]
I am happy to give a hand on this issue
