### ISSUE TITLE
Tests for ci setup strategy

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2185]
Apparently we aren't testing the CI setup strategies (sync, import, install), which led to #2178 (looks like this was probably broken for a few months :scream: )

We should add tests for this.

**Comment by grasmash** [comment]
https://github.com/acquia/blt/issues/2185

**Comment by grasmash** [comment]
https://github.com/acquia/blt/blob/9.1.x/tests/phpunit/BltProject/SetupCommandTest.php#L27
