### ISSUE TITLE
Cannot commit to git per PHPCS, despite matching reported format requirements.

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#2190]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.6
* BLT version: 8.9.9

When I run this command:
```
git commit -m "HUHLR-000: Initial commit of project under BLT."
```

I get the following output:
```
Your local code has passed git pre-commit validation.
Executing .git/hooks/commit-msg...
Validating commit message syntax...
[error]  Invalid commit message! 
Commit messages must:
* Contain the project prefix followed by a hyphen
* Contain a ticket number followed by a colon and a space
* Be at least 15 characters long and end with a period.
Valid example: BLT-135: Added the new picture field to the article feature.
```

And I expected this to happen:

The code to be committed.

**Comment by danepowell** [comment]
@kevinquillen it looks like your `project.prefix` in `blt/project.yml` is set to `BLT`, can you confirm? You should change this to HUHLR if that's the prefix you want to use.

**Comment by kevinquillen** [comment]
Huh, I thought I had set that, but I guess I had not.
