### ISSUE TITLE
Generating a deployment artifact for ACE is slow

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#22]
@kylebrowning

Ways to improve performance:
* Rather than using `git fetch` for every build, allow `deploy/.git` to persist and use `git rev-list --right-only 8.x...origin/8.x` to check for upstream commits before fetching.

**Comment by danepowell** [comment]
#75 should have improved this somewhat by only fetching the upstream branch. Is this still an issue? I haven't seen any performance issues around `deploy:build`.

**Comment by grasmash** [comment]
Closing. #75 and #162 should both have improved the identified performance bottlenecks.
