### ISSUE TITLE
Document lightning requirement for npm

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#220]
We must note that if you are using lightning, the system requirements include NPM.

**Comment by aweingarten** [comment]
@grasmash, @sarahjean
Does it make sense to maybe add a task or a target-hook to install node?   This is a recurring headache every-time we spin up a new codebase.    Would be nice if it just worked.

**Comment by grasmash** [comment]
@aweingarten I've explored that, but found that thar be dragons. Much better to have this handled on a per machine basis. Feel free to submit a PR if you'd like to tackle it.
