### ISSUE TITLE
composer install giving an error ' failed to open stream: Is a directory'

### ISSUE THREAD

**Issue by saitanay** [acquia/blt#2205]
My system information:
* Operating system:  OsX 10.11.6

When I run this command:
composer install

(The project was setup via blt on another machine by running composer create-project command. The codebase was checked in, and on another machine, the codebase was cloned. And ran "composer install"

I get the following output:
```
[ErrorException]
  ZipArchive::extractTo(/Users/tanaysai/dev/tetley/vendor/composer/dd7c43cb/acquia-lightning-52c4b8f/modules/upload_bundles_test):
  failed to open stream: Is a directory
```

Using BLT 8.9.10
Composer.json - https://gist.github.com/saitanay/4bde0c1c36066290d5cb2defdb61f383

Screenshot - https://www.evernote.com/l/ASm0nojCSZRDVJWYp2k-2BwHTm4pLyZ8XoQ

**Comment by danepowell** [comment]
This seems like a corrupt composer cache, not anything wrong with BLT. Did you previously interrupt a composer install or update (such as with ctrl+c or a network disconnect)?

Try running `composer run-script nuke`, which will clear your composer cache, vendor directory, and lock file, then `composer update`.

**Comment by markSbrandt** [comment]
@danepowell  I am having the same issue and the run-script nuke does not work ... it returns with the same error:
`
  [ErrorException]
  ZipArchive::extractTo(/Users/mark/drupalSite/vendor/composer/1121d5d1/acquia-lightning-52c4b8f/modules/upload_bundles_test): failed to open stream: Is a directory


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

Script @composer install --ansi handling the nuke event returned with error code 1
`
any other suggestions?

**Comment by danepowell** [comment]
@markSbrandt what operating system and composer version are you using?

@saitanay what composer version are you using?

Since both of you are having problems downloading Lightning, it might be better to open an issue in the Lightning queue. Although I suspect this is a problem with Composer or your local environment (file permissions or something).

**Comment by markSbrandt** [comment]
hah that was it! i was on composer 1.3.1 (the latest from homebrew)  upgraded to 1.5.2 manually via running "composer self-update" ... and after the zip error it now attempts to dl the acquia blt package and build from source see below output ... 

- Installing acquia/lightning (2.2.1): Downloading (100%)
    Failed to execute unzip -qq  'docroot/profiles/contrib/lightning/6d10651ab2d121bc26ed7aff89308a3a' -d '/Users/mark/drupalSite/vendor/composer/edff0aeb'

replace /Users/mark/drupalSite/vendor/composer/edff0aeb/acquia-lightning-52c4b8f/modules/lightning_features/lightning_media/modules/lightning_media_document/src/Plugin/media/source/File.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
    Failed to download acquia/lightning from dist: The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(/Users/mark/drupalSite/vendor/composer/edff0aeb/acquia-lightning-52c4b8f/modules/upload_bundles_test): failed to open stream: Is a directory
    Now trying to download from source
  - Installing acquia/lightning (2.2.1): Cloning 52c4b8f6bb from cache


I'm actually going to try and reinstall one more time but not use the blt recommended --no-intereaction flag and pass a "y" to the replace prompt for fear something along the line might not be correct even though i eventually got a successful install message

**Comment by markSbrandt** [comment]
https://github.com/acquia/lightning/issues/500

**Comment by danepowell** [comment]
Confirmed that this is a Lightning problem: https://github.com/acquia/lightning/issues/502

**Comment by balsama** [comment]
I just tagged Lightning 2.2.2-alpha1 which I think should resolve this. Our CI system is down (Travis) so I'm hesitant to tag the full release, but will as soon as it's back up and I have confirmation from someone that this problem and some other issues with hook_requirements are resolved.
