### ISSUE TITLE
Error on blt vm run.

### ISSUE THREAD

**Issue by AdrianCocorev** [acquia/blt#2206]
My system information:
* Operating system type: OS X
* Operating system version: 10.13.0
* BLT version: 8.9.2

When I run this command:

> blt vm

I get the following output:

> TASK [geerlingguy.drush : Install Drush.] **************************************
> fatal: [acquia]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for github-production-release-asset-2e65be.s3.amazonaws.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]) or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 6] _ssl.c:510: TLS/SSL connection has been closed."}
> 	to retry, use: --limit @/Users/admin/Sites/www/acom/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry
> 

And I expected this to happen: Start my virtual machine.

Can anyone suggest what should I do in order to fix this error?

**Comment by danepowell** [comment]
This looks like a transient network problem, I would wait and try again later. It's also possible you are on a network doing something funky with SSL certificates.

At any rate, this doesn't appear to be BLT-related. If the issue persists you should try posting an issue for DrupalVM: https://github.com/geerlingguy/drupal-vm

**Comment by danepowell** [comment]
Here are related issues for DrupalVM:
#896
#844
