### ISSUE TITLE
BLT & drupal console - help!

### ISSUE THREAD

**Issue by obbsoftware** [acquia/blt#2226]
My system information:
* Operating system type: osx
* Operating system version: drupal vm 
* BLT version: latest 

I have a MULTISITE setup 

I executed 
```
composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages
```

I installed 
```
curl https://drupalconsole.com/installer -L -o drupal.phar
```
when executing outside docroot drupal command it does not have GENERATE commands 
when executing inside  docroot drupal command is says 

```
 must execute the following composer commands:
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
```

What is wrong ?!

**Comment by danepowell** [comment]
This sounds like a problem with Console, not BLT. You might want to open an issue with Console.

If you are using DrupalVM, note that you'd probably have to execute console commands within the VM, or pass some sort of argument to Console so it knows to SSH into the VM (no idea if Console supports aliases like Drush)

**Comment by obbsoftware** [comment]
fixed, if you install just 
,,,
curl https://drupalconsole.com/installer -L -o drupal.phar
,,, 
it works 

if I update with composer, stops working

**Comment by RakeshJamesAccess** [comment]
Please use the following commands and it worked for me, 

1.  composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages
2. curl https://drupalconsole.com/installer -L -o drupal.phar
3.  php drupal.phar

Sometimes you need to down grade couple of packages 
1. composer require symfony/dom-crawler:~3.0
2. composer require symfony/debug:~3.0
