### ISSUE TITLE
PhantomJS installation fails 403 Issue.

### ISSUE THREAD

**Issue by janaksingh** [acquia/blt#223]
```
> PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (1.9.8)
    Downloading: Connecting...Script PhantomInstaller\Installer::installPhantomJS handling the post-update-cmd event terminated with an exception
                                                                               
  [Composer\Downloader\TransportException]                                     
  The 'https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-  
  x86_64.tar.bz2' URL could not be accessed: HTTP/1.1 403 Forbidden          
```  

https://travis-ci.org/acquia/blt/builds/144947471#L1050

**Comment by janaksingh** [comment]
the download link generated by the installer seems to be correct:
https://github.com/jakoch/phantomjs-installer/blob/master/src/PhantomInstaller/Installer.php#L407

When accessing the link directly, it seems to work fine:
https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2

However, in the log, it appears there is a space in the URL like so:

https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux- **[weird space]** x86_64.tar.bz2

Not sure if this is simply the log display or the actual URL that is getting passed in!

**Comment by japerry** [comment]
I also am running into this issue, I'm getting redirected to the oauth handler for bitbucket. It prompted to add a consumer, which I did, and now it just 403s.

Odd since this isn't a private repo.

Generating autoload files
> post-install-cmd: PhantomInstaller\Installer::installPhantomJS
  - Installing phantomjs (1.9.8)
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
    Downloading: Connecting...Downloading https://bitbucket.org/site/oauth2/access_token
    Download failed, retrying...
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
    Downloading: Connecting...Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
    Downloading: Connecting...
Failed: [Composer\Downloader\TransportException] 401: Could not authenticate against bitbucket.org

**Comment by grasmash** [comment]
I believe this has to do with bitbucket's cdn being intermittently unavailable. Rerunning typically fixes this issue. Not sure what we can do about it.

**Comment by mdeltito** [comment]
I've also seen this issue sporadically. It may be the case that the oauth redirect only occurs when you get rate limited against the public cdn.

**Comment by grasmash** [comment]
Closing. @japerry determined that this was a local config issue. Please post any details if you have them--for posterity.

**Comment by sarahjean** [comment]
@grasmash @japerry What is the local config issue? They definitely have/had a CDN issue https://github.com/ariya/phantomjs/issues/13953

**Comment by japerry** [comment]
The issues I ran into appears to be the stock php version with OSX. The PHP version that ships with OSX El Capitan has something wrong with its curl functionality. When I use DD or MAMP Pro's included php binary to run composer install, it works without a problem.

It doesn't appear to be a problem with curl on the system. Both environments had the exactly the same versions an extensions installed.

**Comment by sarahjean** [comment]
Here's the alternate CDN fix from another project https://github.com/less/less.js/pull/2905/files#diff-354f30a63fb0907d4ad57269548329e3R12

**Comment by sarahjean** [comment]
Tested this out, phantomjs-installer doesn't seem to use the variable, so I think we need to wait on their solution on https://github.com/jakoch/phantomjs-installer/issues/34

**Comment by mickaelperrin** [comment]
Struggling with this problem since yesterday, 

- setting a Bitbucket OAuth token didn't work: https://github.com/composer/composer/issues/5584
- changing the CDN for GitHub didn't work either: https://github.com/composer/composer/issues/5583
