### ISSUE TITLE
Update Read the Docs branches

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2245]
Currently, both the stable and latest branches on Read the Docs appear to point to 8.x, which is actually getting quite stale at this point.

I think "stable" should be 8.9.x, and "latest" should be 9.1.x.

Unfortunately I don't have administrative access to RtD, so @grasmash will have to do this when he's available.

**Comment by grasmash** [comment]
@danepowell You’re an admin now!

**Comment by danepowell** [comment]
Thanks! It took me a while to figure out RtD's versioning strategy, but I think it's sorted now.
