### ISSUE TITLE
Remove markdown and (more) text files from the artefact

### ISSUE THREAD

**Issue by typhonius** [acquia/blt#2255]
I've been auditing a client Drupal site (not using BLT) that inadvertently includes sensitive developer information from custom modules in markdown files in the built artefact.

We already remove *.txt from docroot/core in the deployment artefact here https://github.com/acquia/blt/blob/9.1.x/src/Robo/Commands/Deploy/DeployCommand.php#L436-L439

- Would the extension of this current functionality to include more directories (modules/themes/libraries etc) and more file types (md) be a worthwhile default for BLT?
- Is there a situation where a production site would require txt or md files to be available for users to view?

**Comment by seanhamlin** [comment]
> Is there a situation where a production site would require txt or md files to be available for users to view?

It seems fairly common for modules (at least in D7) to implement `hook_help()` which is only a proxy for reading the contents of the README.txt (or .md) file. Unsure how common this is in D8.

Personally I am a fan of removing any and all .txt, .md etc files from the artefact. At the moment I do this in BLT with a `post-deploy-build` hook:

```
  post-deploy-build:
    dir: '${repo.root}'
    command: './post-deploy-build.sh ${deploy.dir}'
```

**Comment by greylabel** [comment]
This might be more reliably handled at the web server. BLT could include a example patch for .htacess to be optionally applied.

**Comment by danepowell** [comment]
I think it would be a bit greedy for BLT to remove _any_ txt or md file in the codebase. The only reason we do that for Drupal Core is because it's a pretty stable and well-known set of files that we're removing. I can imagine all sorts of scenarios for custom and contributed modules where this would cause problems though.

**Comment by danepowell** [comment]
I'm happy to hear more arguments for this, but for now I'm going to close as won't fix. Thanks for the suggestion though.
