### ISSUE TITLE
Verbose logging for CI scripts

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2261]
BLT has consolidated CI scripts for setting up, installing, and testing an application, which is very helpful but makes debugging in these environments harder, because you have to copy and modify the entire script in order to get verbose output from sub-commands.

Ideally these scripts would accept an option for debug/verbose output that would be passed to sub-commands.

**Comment by grasmash** [comment]
Can you provide an example of the CI scripts that need this?

**Comment by danepowell** [comment]
I think when I created this issue I was specifically trying to debug setup_app on Pipelines: https://github.com/acquia/blt/blob/9.1.x/scripts/pipelines/setup_app

**Comment by grasmash** [comment]
We should just hardcode -v to all commands run via ci. We already do this with Travis.
