### ISSUE TITLE
Best Practices for environment specific settings

### ISSUE THREAD

**Issue by amytackett** [acquia/blt#2267]
Does the BLT project currently have a best practices recommendation on how to manage environment-specific settings? 

This comment exists in blt.settings.php:
 * Use local.settings.php to override variables on secondary (staging,
 * development, etc) installations of this site. Typically used to disable
 * caching, JavaScript/CSS compression, re-routing of outgoing emails, and
 * other things that should not happen on development and testing sites.

However, this code executes inside an if block that only includes the file if $is_local_env is true, so these settings won't get picked up for development or staging sites. Accordingly, what would be the best practice for managing these types of settings for dev / stage?

We also have some settings that we want to be shared across all local development environments. By default, local.settings.php is ignored in git, so we currently have to include documentation for each development to manually add these settings. Is there a best practice recommendation for sharing local settings?

**Comment by danepowell** [comment]
The preferred method in most cases is to store environment-specific settings (actually configuration, to be precise) via config split:
https://github.com/acquia/blt/blob/9.1.x/readme/configuration-management.md
https://github.com/acquia/blt/blob/9.1.x/readme/config-split.md

The idea being that you have a split for each environment (local/dev/stage...), and BLT automatically detects which environment it is running in and imports the appropriate config split.

There are situations where it might be better to enforce settings via `*settings.php`. In this case you can simply create your own settings.php includes on your project. For instance, you could create a file `docroot/sites/default/settings/caching.settings.php` and `require` that from `docroot/sites/default/settings.php` (_after_ the require statement for blt.settings.php). BLT doesn't really get involved here, but it does provide some convenience variables to help you along, such as `$is_ah_stage_env`, `$is_ah_prod_env`, etc.., that you can use to build conditionals in your settings file: https://github.com/acquia/blt/blob/4b9f6525a6e0761568b60ae6f2bf0fd7e11afecd/settings/blt.settings.php#L50

Finally, for super-sensitive settings like API keys, you can store these in a server-side include:
https://github.com/acquia/blt/blob/4b9f6525a6e0761568b60ae6f2bf0fd7e11afecd/settings/blt.settings.php#L160

**Comment by amytackett** [comment]
Thank you for this information. We are indeed using config split for environment-specific configuration settings. We have been discussing our strategy for the items that are better suited to settings.php, so we will proceed as you have described for those items. Many Thanks!

**Comment by danepowell** [comment]
No problem. I'm going to go ahead and close this, feel free to re-open if necessary.
