### ISSUE TITLE
Force certain directories when deploying to Acquia Cloud

### ISSUE THREAD

**Issue by webkenny** [acquia/blt#227]
## Problem
Some developers will have a global Git ignore file that will exclude directories such as `/vendor` or other required directories to be pushed to ACE in `develop-build`. This causes dependency issues.

## Solution
Pull Request incoming but we want to, at minimum, force `/vendor` to be committed.

**Comment by webkenny** [comment]
See https://github.com/acquia/blt/pull/228

**Comment by CashWilliams** [comment]
I ran into this with something other then /vendor as well.

My global git ignore had something relating to icon files in it, and so some images named '*icon*' from http://cgit.drupalcode.org/drupal/tree/core/themes/seven/images?h=8.1.x were not getting added to the deploy commit.

**Comment by grasmash** [comment]
Merged.
