### ISSUE TITLE
SimpleSAMLphp autoloading 

### ISSUE THREAD

**Issue by sodacrackers** [acquia/blt#2275]
My system information:
* Operating system type: Aquia Cloud 
* Operating system version: 
* BLT version: 8.9.10

Output of `blt doctor`:
 ```
 blt-version          | 8.9.10                                                                         |
| bootstrap            | Successful                                                                     |
| drupal-version       | 8.4.2                                                                          |
| drupal-vm-enabled    | true                                                                           |
| drush-version        | 8.1.15                                                                         |
| drush-script         | /var/www/uwmed/vendor/drush/drush/drush.php                                    |
| install-profile      | lightning                                                                      |
| php-conf             | /etc/php/5.6/cli/php.ini           

```

Installing SimpleSAMLphp library manually causes an error when BTL settings autoloads. It seems to sets an incorrect `$settings['simplesamlphp_dir']` path.  

Can anyone provide suggestions? 

We're having difficulty running SimpleSAMLphp and the simplesamlphp_auth module as custom installations. Our installation has _SimpleSAMLphp_ installed and configured in the application root, and the _simplesamlphp_auth_ module in docroot/modules/custom folder. This is working however not without frizing `simplesamlphp.settings.php`. 

Do you see issues with the patch attached? It has simplesamlphp.settings.php check for a vendor path rather than just symlink. 

For background, we have a custom installation because of early trouble with `blt simplesamlphp:init` and separate issues where `composer install drupal/simplesamlphp_auth` didn't include default config or metadata.  Eventually we'll try `blt simplesamlphp:init` again.  

I get the following output:
```
Fatal error. Missing.... vendor.... 
```

**Comment by sodacrackers** [comment]
**/patches/blt/blt-simplesamlphp-path.patch**
```

diff --git a/settings/simplesamlphp.settings.php b/settings/simplesamlphp.settings.php
index 4b78eb3..d9db5fc 100644
--- a/settings/simplesamlphp.settings.php
+++ b/settings/simplesamlphp.settings.php
@@ -19,7 +19,8 @@
 }
 else {
   // Local SAML path.
-  if (is_dir(DRUPAL_ROOT . '/../simplesamlphp')) {
+  if (is_dir(DRUPAL_ROOT . '/../simplesamlphp') && 
+    is_dir(DRUPAL_ROOT . '/../vendor/simplesamlphp/simplesamlphp')) {
     $settings['simplesamlphp_dir'] = DRUPAL_ROOT . '/../vendor/simplesamlphp/simplesamlphp';
   }
 }


```

**Comment by danepowell** [comment]
Can you please review your original post? I think the formatting got screwed up. Please clarify exactly what command you are trying to run, and what error it is generating. Thanks.

**Comment by sodacrackers** [comment]
Done. Thanks

**Comment by danepowell** [comment]
> Our installation has SimpleSAMLphp installed and configured in the application root, and the simplesamlphp_auth module in docroot/modules/custom folder

If you have simplesamlphp installed in the app root, then why would your patch check if it exists in /vendor? I guess I'm still not clear on what you are trying to accomplish.

If there's something wrong with the `simplesamlphp:init` command that we can fix please let us know. If you'd prefer not to use that, then you should probably just manage your simplesamlphp settings independently.

**Comment by sodacrackers** [comment]
The problem we were seeing is with `vendor/acquia/blt/settings/simplesamlphp.settings.php`

You'll note this line (#19)  
`if (is_dir(DRUPAL_ROOT . '/../simplesamlphp') {` 

It checks if simplesamlphp in the application root and if so, incorrectly sets a path to `DRUPAL_ROOT . '/../vendor/simplesamlphp/simplesamlphp'`  

Our patch checks the path more carefully. Am I reading that wrong?

**Comment by danepowell** [comment]
Thanks for clarifying, I see your point now. Regardless of whatever else is going on, we shouldn't be telling simplesamlphp to include a directory without first verifying that it exists.
