### ISSUE TITLE
checkBehat method in BltDoctorCommand does not include default config

### ISSUE THREAD

**Issue by swichers** [acquia/blt#2288]
I am in the process of modifying a site's Behat configuration to better work with ACSF. As part of this modification I was moving shared configuration out of the local.yml and into the default.yml. I ran into a problem in troubleshooting where the checkBehat method does not also include the default configuration. It is simply looking for keys explicitly defined in the local yml.

As a user I would expect `blt doctor` to check the Behat configuration for validity instead of checking if a specific file contains the variable.

**Comment by grasmash** [comment]
Addressed in https://github.com/acquia/blt/pull/2400. Specifically, https://github.com/acquia/blt/pull/2400/files#diff-a7b201b1eebee47775ba6f5f5fff80d2R546
