### ISSUE TITLE
Creating a new project with BLT - instructions not clear for usage with Drupal VM

### ISSUE THREAD

**Issue by therobyouknow** [acquia/blt#2302]
On https://blt.readthedocs.io/en/stable/readme/creating-new-project/#creating-a-new-project-with-blt

I followed steps 1-3 OK, inside the Drupal VM I already have. 

Questions: 
- Do I need to do step 4?
- Should steps 1-3 be run on the host machine, i.e. in my case MacOS ?

My system information:
* Operating system type: Mac OS Sierra
* Operating system version: Sierra
* BLT version: as per 27 Nov

Output of `blt doctor`:
```
If you provide a link in your template as to a guide as to how to use this tool then I will read about it to be able to use it to give you the output you need.
```

When I run this command:
```
 blt vm
```

I get the following output:
```
vagrant@redwebbase:/var/www/drupalvm/html/docroot$ blt vm
No command 'blt' found, did you mean:
 Command 'btt' from package 'blktrace' (universe)
 Command 'llt' from package 'storebackup' (universe)
 Command 'lbt' from package 'lbt' (universe)
 Command 'slt' from package 'slt' (universe)
 Command 'bls' from package 'bareos-tools' (universe)
 Command 'bls' from package 'bacula-sd' (universe)
 Command 'bat' from package 'bareos-bat' (universe)
 Command 'bat' from package 'bacula-console-qt' (universe)
 Command 'lt' from package 'looptools' (universe)
 Command 'bld' from package 'bld' (universe)
blt: command not found
```

And I expected this to happen: 
I don't know - your instructions aren't clear

**Comment by danepowell** [comment]
Maybe there's some confusion here about how BLT works in relation to a VM.

BLT only supports running commands on a host machine (not inside of a VM). When using BLT, a VM should really only be used to hold your LAMP stack. When you execute BLT commands on the host machine, BLT dynamically determines whether individual commands need to be proxied into the VM.

This doesn't mean you _can't_ run BLT entirely within a VM (this is a workaround used by some Windows developers), but it's not supported.

It sounds like you are trying to install and run BLT entirely within a VM, is that correct? If so, you should instead run the commands in the readme on the host machine. If you can suggest a change to the docs that would clarify this, it would be welcome.

**Comment by therobyouknow** [comment]
Thanks Dane, I would suggest a visual symbol/prefix or similar before each command in the docs to specify where it should be run. E.g. "on your host, in your blt folder" run this command etc.

**Comment by grasmash** [comment]
> I would suggest a visual symbol/prefix or similar before each command in the docs to specify where it should be run.

Every single BLT command is designed to be run on the host machine, although frankly they are designed to work inside and outside of the virtual machine. So, a visual symbol should not be necessary.

The fact that the BLT command was not available inside of your virtual machine indicates that there was an issue provisioning it. [This script](https://github.com/acquia/blt/blob/9.1.x/scripts/drupal-vm/post-provision.php) is responsible for installing the command alias, and is executed by Drupal VM [here](https://github.com/acquia/blt/blob/9.1.x/scripts/drupal-vm/config.yml#L101). 

Did your machine provision successfully? Do you have this configuration in your box/config.yml file?

**Comment by grasmash** [comment]
Executing `blt vm` will now output `All blt commands executed on your host machine will be executed against this VM.`
