### ISSUE TITLE
Patches not applied on deployments

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2303]
### Summary
BLT 8.9.x will not apply patches when deploying code in some scenarios. It applies patches fine when building sites locally, but not when deploying.

### Scope
As far as I know, this is only a problem for projects that use BLT 8.9.x but do _not_ include Lightning in their codebase.

### Workaround
Projects encountering this bug should manually add composer-patches as a dependency to their own project until a new version of BLT is released: `composer require "cweagans/composer-patches":"^1.6.2"`

### Details
What's happening is that BLT requires composer-patches as a dev dependency in composer.required.json. This means it will be used locally, but it won't be used when building the codebase for deployments (with the --no-dev parameter for composer install).

Fortunately, Lightning also requires composer-patches as a production dependency. So as long as you include Lightning in your codebase you are unaffected. Note that BLT includes Lightning by default (via composer.suggested.json).

This was fixed in 9.1.x: https://github.com/acquia/blt/pull/2050

This bug was introduced to 8.9.x here: https://github.com/acquia/blt/pull/1226

We should see what the "strange autoloading bug" was so we don't reintroduce it in a fix.

**Comment by dpagini** [comment]
Just a random comment... this issue caught my eye and I was wondering why I wasn't seeing the same issue (on 8.9, we don't require lightning), but I realized I have the `cweagans/composer-patches` in the require section. I know that doesn't help much, but maybe some supporting evidence...
