### ISSUE TITLE
"b" and duplicate "core" folder appears after composer operations

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#2309]
My system information:
* Operating system type: macOS 
* Operating system version: 10.12.6
* BLT version: 8.9.10

Whenever I run a composer require or update command, two strange directories appear in my core folder. I am not sure where they come from, pic attached. I have deleted them before, but they usually re-appear when using Composer. Anyone know why? Composer is latest stable, Drupal 8.4.2.

![screen shot 2017-11-28 at 9 58 45 am](https://user-images.githubusercontent.com/362176/33326585-5ba815b0-d423-11e7-8804-7a54a9f73134.png)

**Comment by greylabel** [comment]
This is related to https://github.com/acquia/blt/issues/2251

**Comment by danepowell** [comment]
@greylabel thanks so much for finding that d.o issue, I never would have, although I did figure that this was somehow related to #2251 and https://github.com/cweagans/composer-patches/issues/148

I've used both Git 2.14 and 2.15 and never seen this problem. I suspect that like #148, it's tied to your GNU Patch version as well.

@kevinquillen can you try updating GNU Patch to 2.7.5 and see if that fixes this? Instructions for Mac are here: https://docs.acquia.com/article/fixing-failing-composer-patches-updating-gnu-patch

If this holds true, then we should update that KB article to note this as a possible symptom, and consider where else this needs to be documented.

**Comment by greylabel** [comment]
Fixing this on local environment is not enough. Build artifacts created on Travis will contain these issues if we don't address this more generally.

**Comment by danepowell** [comment]
@greylabel while I agree that we should fix this as broadly as possible, it might not be possible to do outside of composer-patches.

My understanding is that tools that use Linux-based build environments (including Travis CI and Pipelines) won't be affected by this bug, because Linux provides the latest version of patch out of the box. This would only be a problem for environments using older versions of patch, i.e. Mac OS-based builds.

Can you confirm whether you've actually seen examples of this bug in the wild on Linux environments (i.e. TravisCI)?

**Comment by grasmash** [comment]
https://github.com/cweagans/composer-patches/issues/148#issuecomment-350014281

**Comment by danepowell** [comment]
Can anyone verify if this is fixed with the latest release of composer-patches? (1.6.4, which is required by BLT 8.9.11)

**Comment by grasmash** [comment]
> Installing gpatch on OS X 10.12.5 didn't fix this for me, I had to upgrade to High Sierra (10.13.2).

So, apparently even verifying the system's version of gpatch would be insufficient to resolve this issue in BLT.

My gut reaction is to say that this is not within the scope of BLT, and to refer to the work being done in composer-patches.

At best, I can imagine BLT implementing a very hacky workaround in which we add the `docroot/core/b` to the default `.gitignore` but I do not like a solution at all.
