### ISSUE TITLE
[error]  in task Robo\Task\Base\ExecStack  You must add at least one command - how do I add one? 

### ISSUE THREAD

**Issue by therobyouknow** [acquia/blt#2323]
Please can there be a guide in https://blt.readthedocs.io

My system information:
* Operating system type: Mac OS X
* Operating system version: 10.12.6
* BLT version: BLT 8.9.10

Output of `blt doctor`:
```
lt-15-25:basebuildacquia robdavis$ blt doctor
Drupal VM was detected. Running blt doctor inside of VM...
Executing command cd /var/www/basebuildacquia/docroot/.. && /var/www/basebuildacquia/docroot/../vendor/bin/drush cc drush && /var/www/basebuildacquia/docroot/../vendor/bin/drush --include=/var/www/basebuildacquia/docroot/../vendor/acquia/blt/drush blt-doctor -r /var/www/basebuildacquia/docroot/../docroot inside of Drupal VM...
bash: line 0: cd: /var/www/basebuildacquia: No such file or directory
bash: line 0: cd: /var/www/basebuildacquia/docroot/..: No such file or directory
Connection to 127.0.0.1 closed.
Attempting to run doctor on host machine...
[warning] Unable to run the doctor using alias '@basebuildacquia.local'. Trying with '@self'...
[warning] Unable to run the doctor using alias '@self'. Trying without alias...
[error]  Unable to execute the `blt doctor` command. 
lt-15-25:basebuildacquia robdavis$ 
```

When I run this command:
```
blt deploy
```

I get the following output:
```
Pushing artifact to git.remotes...
PHP Warning:  Invalid argument supplied for foreach() in /Users/robdavis/sites/basebuildacquia/vendor/acquia/blt/src/Robo/Commands/Deploy/DeployCommand.php on line 520

Warning: Invalid argument supplied for foreach() in /Users/robdavis/sites/basebuildacquia/vendor/acquia/blt/src/Robo/Commands/Deploy/DeployCommand.php on line 520
[error]    in task Robo\Task\Base\ExecStack 

  You must add at least one command 

```

And I expected this to happen:
- I need someone to explain how I "add at least one command"

**Comment by therobyouknow** [comment]
Why do I need to create "at least one Robo command" if I just want to deploy to the remote target?

And exactly what Robo command would I need to create?

**Comment by therobyouknow** [comment]
I can see a guide here: https://blt.readthedocs.io/en/stable/readme/extending-blt/

But I don't why BLT insists that I have a Robo command to do a deploy.

I want to deploy the code and database on my local VM to the acquia cloud specified as a target in the project.yml as required.

**Comment by danepowell** [comment]
A good first step in debugging any error is to check the line in question. Did you look at what's on line 520 of DeployCommand.php as indicated in the error message?

https://github.com/acquia/blt/blob/a27976392aac68b350ea1a5878a7346fc2f1e42c/src/Robo/Commands/Deploy/DeployCommand.php#L520

The argument to the foreach is `git.remotes`. Have you set a value for `git.remotes` in `blt/project.yml`?

This is documented here: https://github.com/acquia/blt/blob/9.1.x/readme/deploy.md#first-time-setup

> Ensure your Acquia Cloud remote is listed in project.yml under git:remotes.

**Comment by therobyouknow** [comment]
> The argument to the foreach is git.remotes. Have you set a value for git.remotes in blt/project.yml?

Yes I had, but I used the remote name know to git rather than the full git URL, I will try the full URL as instructed - in this ticket:

https://github.com/acquia/blt/issues/2330#issuecomment-349589063

**Comment by grasmash** [comment]
It appears that your project is not using the required directory structure for BLT. This is likely the root cause of all of your issues.

In the interest of centralizing these issues, I'd like to address the directory structure and project configuration questions in #2337.

As you mentioned, the git.remotes configuration issue is being discussed in #2330.
