### ISSUE TITLE
Cloud hook permissions are not being passed to the deployed artifact.

### ISSUE THREAD

**Issue by msherron** [acquia/blt#233]
I was experiencing an issue where after setting the execute bit on an Acquia Cloud hook script in /hooks/common/post-code-deploy and committing it to my project repo, that bit was not being set in the version of the script that's being included in the deploy artifact. 

The issue is the '--no-p' option that's being passed to rsync in the deploy:copy phing task. Removing that option fixed the issue.

**Comment by grasmash** [comment]
Addressed by #234
