### ISSUE TITLE
Why does DeployCommand.php md5 hash the git remote name for git push? Seems to cause invalid error.

### ISSUE THREAD

**Issue by therobyouknow** [acquia/blt#2330]
Looking at lines 518-520 in /Users/robdavis/sites/basebuildacquia/vendor/acquia/blt/src/Robo/Commands/Deploy/DeployCommand.php

```
    foreach ($this->getConfigValue('git.remotes') as $remote) {
      $remote_name = md5($remote);
      $task->exec("git push $remote_name $identifier");

```

I can see that a md5 hash is generated the git remote and this hash is used to refer to the remote when pushing? But why? Why not just use the original git remote name? Surely the hash is invalid and not recognised by git?

This seems to cause an error:

```
PHP Warning:  Invalid argument supplied for foreach() in /Users/robdavis/sites/basebuildacquia/vendor/acquia/blt/src/Robo/Commands/Deploy/DeployCommand.php on line 520

Warning: Invalid argument supplied for foreach() in /Users/robdavis/sites/basebuildacquia/vendor/acquia/blt/src/Robo/Commands/Deploy/DeployCommand.php on line 520
[error]    in task Robo\Task\Base\ExecStack 
```

My system information:
* Operating system type: Mac OS X
* Operating system version: 10.12.6
* BLT version: BLT 8.9.10

Output of `blt doctor`:
```
n/a
```

When I run this command:
```
n/a
```

I get the following output:
```
n/a
```

And I expected this to happen:
n/a

**Comment by dpagini** [comment]
Do you have a "git" entry in your `blt/project.yml` file? 

For example, my `project.yml` has:
```yml
git:
  default_branch: master
  remotes:
    - 'mysiteid@example.com:myrepo.git'
```

**Comment by danepowell** [comment]
No, the hash does not typically cause any problems, we use it thousands of time every day :smile: 

Obviously it requires that the remote be assigned the hash as a name. When BLT initializes the deploy directory, it assigns each remote a name based on the md5 hash: https://github.com/acquia/blt/blob/52fcdc46a9fc926e79881d8389473166acf18191/src/Robo/Commands/Deploy/DeployCommand.php#L245

As @dpagini described, you should define the remote(s) as Git URL(s) in project.yml.

A hash is simply the easiest way to map from the human-readable git URL to something that we can actually pass as a parameter for git commands.

**Comment by therobyouknow** [comment]
@dpagini @danepowell I have defined my git remote as follows:

```
git:
  default_branch: master
  remotes:
    acquiadev
```

where acquiadev is the remote _name_ as seen when `git remote -v` is issued:
```
mymac:blt robdavis$ git remote -v
acquiadev	myuser@svn-6634.devcloud.hosting.acquia.com:myrepo.git (fetch)
acquiadev	myuser@svn-6634.devcloud.hosting.acquia.com:myrepo.git (push)
```

But yes I now understand from what @dpagini says that the full git URL needs to be used i.e. instead of the remote name even though the remote name would be available to the script that uses the project.yml Though I think that being able to use the remote name means that the definition can be centralised in git rather than redefined in the project.yml file.

**Comment by dpagini** [comment]
Also, just by way of explanation, if I remember correctly, the hash is a _separate_ git repo inside the `deploy/` folder. So you might have the remote alias "acquiadev" in your project root, but that's not the same remote name used in the deploy folder.

**Comment by danepowell** [comment]
Yeah it sounds like you might not understand the deployment workflow / repo architecture. Especially this part from the deploy readme:

> The most important thing to remember about this workflow is that the Github and Acquia Cloud repos are not clones of one another. Github only stores the source code, and Acquia Cloud only stores the production code (i.e. the build artifacts).

In other words, if you use the `blt deploy` command, you will actually have two repos locally.

At the top level, you will have your "source" project repository (typically linked to Github or Bitbucket). This will contain your composer.json as well as subdirectories such as docroot, vendor, etc...

When you run `blt deploy`, BLT creates a new `deploy` subdirectory and initializes it as a Git repository (using the git remotes you define in project.yml). It builds a separate copy of the site in that sub-repository and pushes it to your Git remotes.

**Comment by grasmash** [comment]
@therobyouknow Your project.yml file contains yaml syntax.

```
git:
  default_branch: master
  remotes:
    acquiadev
```

Should be:

```
git:
  default_branch: master
  remotes:
    - myuser@svn-6634.devcloud.hosting.acquia.com:myrepo.git
```

Another reason we do not use the remote names is that they are machine specific. Different developers may assign different names to the same remote URL. Git is intentionally decentralized 
in this way by design.
