### ISSUE TITLE
BLT Error

### ISSUE THREAD

**Issue by debdattasarkar** [acquia/blt#2335]
My system information:
* Operating system type: mac OS High Sierra
* Operating system version: 10.13.1
* BLT version: [replace]

Output of `blt doctor`:
```
[error]  The value of drupal_core_path in /Users/debdattasarkar/sites/sitename/box/config.yml contains an unresolved Ansible variable. 
[error]  Do not use Ansible variable placeholders for drupal_core_path. 
[error]  drupal_core_path is currently '{{ drupal_composer_install_dir }}/docroot/..'. Please correct it. 
[error]  Unparsable value in /Users/debdattasarkar/sites/sitename/box/config.yml. 
```
Am new to BLT. Please help. @acquia-github-bot @geerlingguy

**Comment by danepowell** [comment]
@debdattasarkar what version of BLT are you using? How did you generate the vm? That placeholder should not exist, it should be replaced by an absolute path.

Assuming you are using BLT 8.9.10, try `blt vm:nuke` followed by `blt vm` (this will destroy and re-initialize your VM using BLT's default template).

**Comment by grasmash** [comment]
@danepowell's suggestion will certainly address the issue. 

However, if you would like to attempt a more granular fix, please follow the advice of the error message by opening `/Users/debdattasarkar/sites/sitename/box/config.yml` and replacing the string `{{ drupal_composer_install_dir }}`  with the actual value of the `drupal_composer_install_dir` variable.

As the error indicates you should "not use Ansible variable placeholders for drupal_core_path".

**Comment by debdattasarkar** [comment]
BLT version 8.9.6.  blt vm:nuke command removed the above error. Thanks a lot for your support.
