### ISSUE TITLE
Docs: 2 places document setting up for existing/new project (not clear on which to use)

### ISSUE THREAD

**Issue by therobyouknow** [acquia/blt#2336]
2 places:
- https://blt.readthedocs.io/en/latest/readme/creating-new-project/ or https://blt.readthedocs.io/en/latest/readme/adding-to-project/
- https://blt.readthedocs.io/en/latest/readme/onboarding/

Not clear whether one should:
- do both (that's what I'm guessing), any order of steps needed? (doing one before the other)
- do one of them only

**Comment by danepowell** [comment]
Creating new project / adding to project is exactly what it sounds like: to be used only once at the start of any project.

Onboarding is to be used whenever you are setting up a new local development environment, i.e. onboarding a new developer. You don't need to do it if you've already set up the project on your machine.

@therobyouknow it seems like you've overcome a lot of challenges in setting up BLT for yourself, if you'd like to share anything that you've learned or help improve the documentation for future travelers, PRs would be welcome

**Comment by therobyouknow** [comment]
Thank you @danepowell I will revisit the new project and onboarding section of the docs with your comment above in mind.

Yes, I think I might be able to contribute enhancements to the Developer Experience (DX) of using BLT via PRs. When I started using Vagrant years ago, I got frustrated with the incompleteness and ambiguity of the various guides, so I ended up writing my own: https://stackoverflow.com/questions/14608875/getting-a-lamp-stack-running-on-a-vagrant-vm-under-windows-7-host-full-instru/15067918#15067918

**Comment by grasmash** [comment]
Closing issue. Please feel free to submit PRs with suggested changes.
