### ISSUE TITLE
Can't create new project: "The provided cwd does not exist"

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2383]
My system information:
* OS: Ubuntu 17.10 as well as Mac OS High Sierra
* BLT version: 8.9.11

When I run this command:
```
composer create-project --no-interaction acquia/blt-project decoupled
```

I get the following output:
```
[snip]
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
Downloading (100%)Downloading (100%)PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
Updating BLT templated files...
 > blt update --ansi -y
Copying files from BLT's template into your project...
Merging BLT's project.yml template with your project's blt/project.yml...
Removing deprecated files and directories...
> install-alias
The BLT alias is already installed and up to date.
[ExecStack] Done in 44.044s
> examples:init
Example commands and hooks were copied to your repository root.
[ExecStack] git init && git add -A && git commit -m 'Initial commit.'
[error]  The provided cwd does not exist. 
```

That final error that prevents the setup from continuing ("The provided cwd...") comes from the Symfony Process component.

The version of Symfony Process being installed is 3.2.14, which is over a month old, so it seems unlikely that a change in Symfony caused this.

I've reproduced this on both an Ubuntu and Mac machine.

**Comment by dooleymatt** [comment]
@danepowell I saw this today too. I noticed that in the output the `cwd` was 1 level up from where the site was actually being installed. 

For example if I were installing the site at `~/Sites/my_site` the error output said it couldn't find the directory at `~/my_site`.

**Comment by grasmash** [comment]
Weird, `git blame` indicates that this bug is 7 month old. I must be missing something else too.
