### ISSUE TITLE
Add support for Atlassian Bitbucket Pipelines CI

### ISSUE THREAD

**Issue by patrickcate** [acquia/blt#2392]
It would be great if BLT had support for [Atlassian's Bitbucket Pipelines CI](https://bitbucket.org/product/features/pipelines) the same way it has for Travis and Acquia Pipelines.

**Comment by grasmash** [comment]
I agree. I'd be happy to accept a PR for BitBucket support, but I don't believe this will find it's way into the road map given that we support both Travis and Acquia Pipelines out of the box. Closing the issue.

**Comment by b-sharpe** [comment]
Added PR for this: https://github.com/acquia/blt/pull/3347
