### ISSUE TITLE
VM Initialization (./blt.sh vm:init) freezes in terminal when copying drush aliases

### ISSUE THREAD

**Issue by webkenny** [acquia/blt#241]
I thought this was just me but then @web247 hit the same issue. When running `./blt.sh vm:init` it freezes on the following:

```[copy] Copying 1 file to /my/local/path/iheartacsfmaster/drush/site-aliases```

I'm going to dig into this a bit and see what's what/submit a PR.

**Comment by grasmash** [comment]
Closing, see resolution in #214
