### ISSUE TITLE
Inspector::getCliConfigFile() not discovering my active shell is zsh

### ISSUE THREAD

**Issue by nathandentzau** [acquia/blt#2413]
My system information:
* Operating system type: masOS
* Operating system version: 10.13.2
* BLT version: 8.9.11
* PHP version: 7.1.12
* Shell: zsh

When running `blt install-alias` the `Inspector::getCliConfigFile()` method returned `.bash_profile` as my CLI config file instead of `.zshrc`. Upon further inspection the `$_ENV` superglobal is empty. The superglobal was empty due to my php.ini settings not including `$_ENV` to be populated in the `variables_order` setting.

My php.ini settings are default when installing php with homebrew.

This can be solved by using `getenv()` in favor of accessing the superglobal `$_ENV`.

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2419

**Comment by nathandentzau** [comment]
@grasmash why would my PR be closed and you create a new one taking credit for the fix? Doesn’t encourage people to contribute to this project if your team takes the credit.
