### ISSUE TITLE
Document how to run a partial set of tests

### ISSUE THREAD

**Issue by rhuffstedtler** [acquia/blt#243]
As we are adding tests, it takes an increasingly long time for the entire test suite to run. When making a change to a specific module, I would like to be able to pass an optiont to blt.sh tests:behat that would only run a particular feature. If there is a means of doing so, it is not obvious to me, so I've fallen back to dropping a shell script in each module's tests dir with this as its contents:

`../../../../../vendor/bin/behat --config=../../../../../tests/behat/local.yml --tags=~ajax --format=pretty --format=junit features/ --profile=local`

If there is a better way, it would be great to get that in the docs.

**Comment by ChuChuNaKu** [comment]
Hello @rhuffstedtler. To execute tests directly (without Phing) you can run something like:
`./vendor/bin/behat -c tests/behat/local.yml tests/behat/features/Examples.feature` You could also use [gherkin filters](http://docs.behat.org/en/v2.5/guides/6.cli.html#gherkin-filters) to categorize and run a group of features. Addtional testing documentation can be found at `/tests/README.md`

**Comment by grasmash** [comment]
You can also pass the value of behat.tags to blt, e.g., `blt tests:behat -Dbehat.tags='@mytag'`
