### ISSUE TITLE
"VM has not been created" warning

### ISSUE THREAD

**Issue by Sanjib-Dutta** [acquia/blt#2438]
My system information:
* Operating system type: OSX
* Operating system version: 10.13.2
* BLT version: 8.9.11

<img width="841" alt="screen shot 2018-01-11 at 12 02 33 pm" src="https://user-images.githubusercontent.com/27665813/34811634-c92f819c-f6c7-11e7-8b79-45d2c8fbdd7e.png">

Unable to setup application due to the error attached above in the file. Tried many time the same but no luck. Please do needful to resolve the as I am new to Drupal vm. 
@geerlingguy 
Thanks,
Sanjib

**Comment by jayakrishnanj** [comment]
1. You need to install vagrant and virtual box to run **blt vm**, if you have already installed it, make sure its the latest version.
2. After checking the version, try running the blt vm and post the output of that command.

**Comment by grasmash** [comment]
Even better run `blt vm:nuke && blt vm` to regenerate the VM from scratch. Please report back so we can resolve the issue.

**Comment by grasmash** [comment]
Actually, I was assuming that you wanted to use a VM. Maybe you don't want to?

There isn't really an error in that screen shot. The alias is already installed. You're just seeing a warning. It looks like your project has some VM config, but you aren't using a VM. You can ignore the warning if you want to use a different LAMP stack.

**Comment by grasmash** [comment]
Is this issue resolved for you?
