### ISSUE TITLE
Issues with installing  phing

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/blt#244]
- Installing phing/phing (dev-master 0ef30e5)
    Cloning 0ef30e55bb5871cb38903cc0ee9d76074118a22c
    Failed to download phing/phing from source: The process "git clone --no-checkout 'https://github.com/phingofficial/phing.git' '/Applications/MAMP/htdocs/www/waterwheel/vendor/phing/phing' && cd '/Applications/MAMP/htdocs/www/waterwheel/vendor/phing/phing' && git remote add composer 'https://github.com/phingofficial/phing.git' && git fetch composer" exceeded the timeout of 300 seconds.
    Now trying to download from dist
  - Installing phing/phing (dev-master 0ef30e5)
    Downloading: 100%    

But after complete local setup, It posted the issue :

**./blt.sh: line 23: /Applications/MAMP/htdocs/www/waterwheel/vendor/bin/phing: No such file or directory**

**Comment by naveenvalecha** [comment]
I reupdate the composer update phing/phing for me to make it workable. 
Didn't find the exact cause of this issue.

**Comment by grasmash** [comment]
Seems like there was a temporary network issue connecting to GitHub.
