### ISSUE TITLE
Issue updating BLT

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#245]
When I attempted to run ./blt.sh blt:update i got this error. 

svn: E170000: URL 'https://github.com/acquia/blt/branches/8.x/template/scripts/drupal' doesn't exist

**Comment by grasmash** [comment]
Yes, sorry about that. The whole update process will soon be revamped. In the meantime, please just replace your `scripts/blt/updated-scaffold` script with the upstream one and run again.
