### ISSUE TITLE
Update 9000000 fails

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2453]
My system information:
* Operating system type: Ubuntu
* BLT version: 9.1.x

When I update BLT, it tries to run this new schema update:
> update_9000000: Convert Drush 8 files to Drush 9.

Unfortunately, this fails:
> Failed to remove file "/home/dane/sites/blted91/docroot/sites/default/local.drushrc.php": unlink(/home/dane/sites/blted91/docroot/sites/default/local.drushrc.php): Permission denied.

The problem is that docroot/sites/default does not have write permissions. This actually causes problems in a lot of scenarios (when updating via Git after settings.php is modified, for instance). I'm not sure why it's read-only, I suspect that comes from Drupal core or Drupal scaffold.

We could fix this by just temporarily chmodding that directory as part of the update process, but maybe a better long-term solution is to find a way for write permissions to persist whenever local commands are run. I don't think there'd be security concerns with allowing the owner to write, since Git won't preserve the write bit anyway.

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2468
