### ISSUE TITLE
Sanitizing Leaves Unmodified Email In Cache

### ISSUE THREAD

**Issue by milsyobtaf** [acquia/blt#2454]
We are spinning up an internal D8 site using BLT 8.9.11 as the build tool. When I sync the database from Cloud, the sanitize script runs and modifies the `mail` column of the `users_field_data` as expected, however the un-sanitized email address for all users is still available in the `cache_entity` table. This allows the display of the un-sanitized email address directly in the database as well as on individual user pages, until a `drush cache-rebuild` is run.

Looking at https://github.com/acquia/blt/blob/8.9.x/src/Robo/Commands/Sync/DbCommand.php#L73, it appears that `drush` is only being invoked to clear the `drush` cache - would this be a good place to insert a cache rebuild? I don't see an easy way to directly clear the user or entity cache with `drush`, although I could be overlooking it.

**Comment by grasmash** [comment]
Yes that looks like the right place. I would just `drush sqlq "TRUNCATE cache_entity"`. Though, this should probably be done it drush.
