### ISSUE TITLE
How do i deploy to Acquia Dev Cloud 

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#246]
Im looking for insight on how to deploy to our acquia dev cloud. Is there some setup that i need to do in order to get the command to deploy to our dev cloud or, is everything setup to have our dev cloud use what our dev env uses for users, password, databases, etc...

**Comment by grasmash** [comment]
Please take a look at https://github.com/acquia/blt/blob/8.x/template/readme/deploy.md

**Comment by haynescw** [comment]
I have read through that. What im looking for is the recommended jenkins deployment process, and or the recommended travic-ci deployment process.

Have you gotten that far yet?

**Comment by grasmash** [comment]
@haynescw The docs for travis ci deployment are here: http://blt.readthedocs.io/en/latest/readme/ci/#setting-up-travis-ci-for-automated-deployments

Does that cover the information you're looking for?

**Comment by haynescw** [comment]
I will look that over, but that url looks familiar. I Caan always dbl check some more


Sent via the Samsung Galaxy Note5, an AT&T 4G LTE smartphone
-------- Original message --------From: Matthew Grasmick <notifications@github.com> Date: 8/9/16  4:28 PM  (GMT-06:00) To: acquia/blt <blt@noreply.github.com> Cc: Chris Haynes <haynes.cw@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [acquia/blt] How do i deploy to Acquia Dev Cloud (#246) 
@haynescw The docs for travis ci deployment are here: http://blt.readthedocs.io/en/latest/readme/ci/#setting-up-travis-ci-for-automated-deployments

Does that cover the information you're looking for?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/acquia/blt","title":"acquia/blt","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/acquia/blt"}},"updates":{"snippets":[{"icon":"PERSON","message":"@grasmash in #246: @haynescw The docs for travis ci deployment are here: http://blt.readthedocs.io/en/latest/readme/ci/#setting-up-travis-ci-for-automated-deployments\r\n\r\nDoes that cover the information you're looking for?"}],"action":{"name":"View Issue","url":"https://github.com/acquia/blt/issues/246#issuecomment-238697494"}}}

**Comment by grasmash** [comment]
Closing, 3wks with no update.
