### ISSUE TITLE
Running BLT VM did not generate Drush Alias File After Drush 9 Update

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2466]
My system information:
* Operating system type: Mac OS
* Operating system version: 10.11.6
* BLT version: 9.0.0-alpha2

Output of `blt doctor`:
```
blt doctor
Drupal VM was detected. Running blt doctor inside of VM...
Executing command cd /var/www/<project>/docroot/.. && /var/www/<project>/docroot/../vendor/bin/drush cc drush && /var/www/<project>/docroot/../vendor/bin/drush --include=/var/www/<project>/docroot/../vendor/acquia/blt/drush blt-doctor -r /var/www/<project>/docroot/../docroot inside of Drupal VM...
 [success] 'drush' cache was cleared.

                     
  [Exception]        
  Bootstrap failed.  
                     

blt:doctor [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify] [--xh-link XH-LINK] [--] <command>

Connection to 127.0.0.1 closed.
Attempting to run doctor on host machine...

```

When I run this command:
```
blt vm
```

And I expected this to happen:
I expected that the Drush 9 alias file would be generated for the new local / vm, but it was not.

**Comment by mikemadison13** [comment]
digging into this, i believe the issue is that I had drush_server_home() in my old site alias file. 

I think we need to expand our documentation in drush/sites/README.md to help people troubleshoot this. It is unclear to me if BLT VM was necessary in this instance, or if blt update should have addressed this (re: https://github.com/acquia/blt/issues/2437). However, as far as I can tell, I had to manually remove drush_server_home() from the alias file, then move the file, then run the drush command to get a local alias.

see: https://github.com/acquia/blt/pull/2241/files

**Comment by mikemadison13** [comment]
note that once i have the valid alias file, i am not getting:
`Permission denied (publickey,password).`

This may be related to https://github.com/geerlingguy/drupal-vm/issues/1595 ?

**Comment by grasmash** [comment]
The upgrade hook should have actually created new Drush alias files in a Yaml format. Did that happen?

**Comment by mikemadison13** [comment]
no, i had to manually run the drush command, and that didn't generate anything for the local. the documentation sounds like running drupal vm will (and that didn't either)

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2471

**Comment by grasmash** [comment]
Needs real world testing, but should address issue.

**Comment by mikemadison13** [comment]
@grasmash i'll re-run the upgrade and see what happens. will report back.

**Comment by mikemadison13** [comment]
@grasmash good news, the update ran. bad news, the alias files were still not generated automatically. the legacy file was created though. Here are the additional steps I had to take...

1. chmod my legacy file (it failed)
`blt update
Copying files from BLT's template into your project...
Merging BLT's project.yml template with your project's blt/project.yml...
The following BLT updates are outstanding:
 - update_9000000: Convert Drush 8 files to Drush 9.

 Would you like to perform the listed updates? (y/n) y
Executing updates...
-> update_9000000: Convert Drush 8 files to Drush 9.
[error]  Failed to chmod file "legacy.aliases.drushrc.php". 
Removing deprecated files and directories...
> install-alias
[warning] Your BLT schema is out of date.`

2. manually re-run blt update (this didn't error out, but it also didn't crate my drush aliases)

3. manually run drush site:alias-convert (it failed)
`Error: Call to undefined function drush_server_home() in <project>/drush/site-aliases/legacy.aliases.drushrc.php on line 373`

4. manually remove drush_server_home in favor of $HOME

5. manually run drush site:alias-convert (it succeeded)

shall i push some documentation that covers these steps? or do we need to open a new issue and further refine the automated update?

**Comment by mikemadison13** [comment]
it would appear that the root cause of this issue is the drush_server_home() variable in the legacy file. I'm going to push a PR that strips this inline during the update.
