### ISSUE TITLE
The local:refresh task overwrites local.settings.php

### ISSUE THREAD

**Issue by sarahjean** [acquia/blt#248]
local.* files are usually meant to override what is set up in version control. Running local:refresh currently overwrites what is in local.settings.php with the contents of default.local.settings.php so any local overrides will be lost. It seemed to me that the purpose of local:refresh was to be run frequently during development to enable testing pull requests against an up to date local site that matches test. I think any copying from default.local.settings.php should be confined to an initial setup task and not something that is meant to be rerun again to avoid frustrating developers who might lose local settings unexpectedly.

**Comment by grasmash** [comment]
This has been addressed by #210

**Comment by sarahjean** [comment]
👍
