### ISSUE TITLE
Reprovision VM automatically when changes are detected

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2483]
Currently, if someone on a BLT-based project makes changes to the DrupalVM configuration (i.e. box/config.yml), they have to communicate the fact that changes were made out-of-channel, and developers each have to manually reprovision their VM.

This is an ungainly process that tends to not work so well in practice. Most often, a TA forgets to communicate the change or a developer forgets to reprovision, and the problem isn't noticed until some time later when weird conflicts start showing up due to the inconsistent environments.

 It would be awesome if there were some mechanism for BLT or DrupalVM to detect changes to `box/config.yml` and prompt developers to reprovision.

Ideally, maybe this is something Vagrant would support. But that seems like an unlikely prospect.

It seems like the best way to do this with BLT would be with a tiny local schema/hash file (ignored by Git) that simply stores a hash of the config.yml file. BLT would verify the hash any time you run a setup command, and if a change is detected, prompt you to reprovision the VM and update the hash.

Or maybe we could do something similar with a vagrant plugin? Then we could actually hook into vagrant and only perform this check when running vagrant up, which would be a little more elegant.

**Comment by danepowell** [comment]
cc @geerlingguy

**Comment by grasmash** [comment]
> Or maybe we could do something similar with a vagrant plugin?

That would be much preferred.

**Comment by geerlingguy** [comment]
I don't think there's anything in Vagrant that would support this—it would have to track it per-provisioner, and there are like 10+ provisioners which could have infinite variations in how the provisioning data is tracked (e.g. what determines a change—anything in any ansible role, variable file, include file, playbook, task include, etc.?).

This would only really be trackable in an upstream tool, e.g. something in BLT that generates a hash of the main shared config file, something like that.

I am definitely not considering adding such a tool to Drupal VM, as outside of BLT's use case I've never really noticed people mention this (Drupal VM is primarily used by individual developers or on teams where the configuration is not necessarily centrally managed (e.g. by a tool like BLT)).

**Comment by grasmash** [comment]
I'm not comfortable adding any additional features that wrap Drupal VM because the features would not be testable. We've learned that the maintenance and support cost of such features is very high.
