### ISSUE TITLE
Cannot install blt due to Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found

### ISSUE THREAD

**Issue by uenrico** [acquia/blt#2496]
I just tried 9.1.x-dev and is not working. I tried 8.9.12 and I got the same error:

My system information:
* Operating system type: Ubuntu [VM]
* Operating system version: 16.04
* BLT version: 9.1.x-dev

When I run this command:
```
composer create-project acquia/blt-project:9.1.x-dev --no-interaction my-project
```

I get the following output:
```
PHP Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /var/www/zzz/my-project/vendor/symfony/console/Application.php:129
Stack trace:
#0 /var/www/zzz/my-project/vendor/consolidation/robo/src/Runner.php(175): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/zzz/my-project/vendor/acquia/blt/src/Robo/Blt.php(236): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#2 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt-robo-run.php(33): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/var/www/glbdru...')
#4 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt in /var/www/zzz/my-project/vendor/symfony/console/Application.php on line 129
```

**Comment by grasmash** [comment]
Sorry about that, 9.1.x was merged into 9.x and removed. Please try 9.x.

**Comment by grasmash** [comment]
Also, please know that 9.x is in alpha in 8.9.x is the stable version.

**Comment by uenrico** [comment]
I tried 8.9.12 and I got the same error

**Comment by uenrico** [comment]
composer create-project acquia/blt-project:9.x-dev --no-interaction my-project throw the same error:

PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /var/www/zzz/my-project/vendor/symfony/console/Application.php:129

**Comment by grasmash** [comment]
Can you try to update composer `composer self-update` ?

**Comment by uenrico** [comment]
composer self-update

> You are already using composer version 1.6.2 (stable channel).

**Comment by grasmash** [comment]
What is your PHP version?

**Comment by uenrico** [comment]
PHP 7.1.13

**Comment by grasmash** [comment]
Ack! Well that's a mystery. I've just executed

```
composer create-project acquia/blt-project:9.x-dev --no-interaction my-project
```

With Composer 1.6.2 and PHP 7.1.12 without issue. 

For some reason composer is resolving your dependencies differently. Perhaps `composer clear-cache` would help? I'll do my best to reproduce your issue.

**Comment by uenrico** [comment]
hmmm I tried composer clear-cache, without results :(

**Comment by grasmash** [comment]
Can you share the full command output?

**Comment by uenrico** [comment]
1/7:        http://packagist.org/p/provider-latest$7f666be1445cc99b4f698ff933fb19f5fe1f6542304b193ed074c60200159ffc.json
    2/7:        http://packagist.org/p/provider-2017$cad060e4c879cbb83215ad34f3cec1c11049efaeb2443aa421ac6dd4e22d5859.json
    3/7:        http://packagist.org/p/provider-2017-07$82c397c5d65bb452a373dcabebf7f8ac985e9c128dc1c6a90a172804f6729517.json
    4/7:        http://packagist.org/p/provider-2017-10$6bf2fcf74b60ae80f6921edc402d4dcc2dacfbc7a05c3ca19fb5633e1a5995a6.json
    5/7:        http://packagist.org/p/provider-2016$a5508f152c19d2a078096eaab9c46ad4ff69d971e2ea6049f31b492bcc55cc61.json
    6/7:        http://packagist.org/p/provider-2018-01$0016626e91b9833f1f18b753b2d64e158c799685733bc49a58c53ffca42b0c4a.json
    7/7:        http://packagist.org/p/provider-2017-04$018c6dd47714e46214c7501969c8e1af170bf722df4a730f062304e8d869e70f.json
    Finished: success: 7, skipped: 0, failure: 0, total: 7


Installing acquia/blt-project (9.x-dev 18e4a48d60941059f5589be243941535d47f0c5b)
  - Installing acquia/blt-project (9.x-dev 18e4a48): Cloning 18e4a48d60 from cache
Created project in my-project
    1/2:        http://packagist.org/p/provider-2017-10$d4c7490ee847389283aabb4a5830ca671de3bbc841a5654827dbc62c65af761e.json
    2/2:        http://packagist.org/p/provider-latest$be4911c849e351761fe77d1ac24ebc5ec22dc498e556ff954617f5f4e405de63.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:        https://codeload.github.com/acquia/blt/legacy.zip/08dd840bc7f40e090d600bc083b1f7683555b002
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Package operations: 78 installs, 0 updates, 0 removals
  - Installing wikimedia/composer-merge-plugin (v1.4.1): Loading from cache
  - Installing composer/installers (v1.5.0): Loading from cache
  - Installing grasmash/drupal-security-warning (1.1.1): Loading from cache
  - Installing cweagans/composer-patches (1.6.4): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing sarciszewski/php-future (0.4.2): Loading from cache
  - Installing acquia/http-hmac-php (3.3.0): Loading from cache
  - Installing typhonius/acquia-php-sdk-v2 (1.0.2): Loading from cache
  - Installing tivie/php-os-detector (1.1.0): Loading from cache
  - Installing symfony/yaml (v3.2.14): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing twig/twig (v1.35.0): Loading from cache
  - Installing symfony/twig-bridge (v3.3.15): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.4.3): Loading from cache
  - Installing symfony/console (v3.2.14): Loading from cache
  - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
  - Installing sebastian/version (1.0.6): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (1.0.5): Loading from cache
  - Installing sebastian/exporter (1.2.2): Loading from cache
  - Installing sebastian/environment (1.3.8): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (2.3.8): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-token-stream (1.4.12): Loading from cache
  - Installing phpunit/php-code-coverage (2.2.4): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.2.0): Loading from cache
  - Installing phpspec/prophecy (1.7.3): Loading from cache
  - Installing phpunit/phpunit (4.8.36): Loading from cache
  - Installing oomphinc/composer-installers-extender (v1.1.2): Loading from cache
  - Installing dflydev/dot-access-data (v1.1.0): Loading from cache
  - Installing grasmash/yaml-expander (1.4.0): Loading from cache
  - Installing symfony/filesystem (v3.4.3): Loading from cache
  - Installing grasmash/yaml-cli (1.0.3): Loading from cache
  - Installing symfony/config (v3.4.3): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.3): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing webflo/drupal-finder (1.1.0): Loading from cache
  - Installing symfony/var-dumper (v3.4.3): Loading from cache
  - Installing symfony/process (v3.4.3): Loading from cache
  - Installing symfony/finder (v3.4.3): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing nikic/php-parser (v3.1.3): Loading from cache
  - Installing psy/psysh (v0.8.17): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing league/container (2.4.1): Loading from cache
  - Installing consolidation/output-formatters (3.1.13): Loading from cache
  - Installing consolidation/log (1.0.5): Loading from cache
  - Installing consolidation/annotated-command (2.8.2): Loading from cache
  - Installing grasmash/expander (1.0.0): Loading from cache
  - Installing consolidation/config (1.0.9): Loading from cache
  - Installing consolidation/robo (1.2.1): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing chi-teck/drupal-code-generator (1.22.0): Loading from cache
  - Installing drush/drush (dev-master 5d457e2): Cloning 5d457e230b from cache
  - Installing drupal/coder (8.2.12): Cloning 984c54a7b1 from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.4.4): Loading from cache
  - Installing acquia/blt (9.x-dev 08dd840): Cloning 08dd840bc7 from cache
acquia/http-hmac-php suggests installing silex/silex (~1.3.0)
acquia/http-hmac-php suggests installing symfony/psr-http-message-bridge (~0.1.0)
acquia/http-hmac-php suggests installing symfony/security (~3.0.0)
acquia/http-hmac-php suggests installing zendframework/zend-diactoros (~1.3.5)
symfony/twig-bridge suggests installing symfony/asset (For using the AssetExtension)
symfony/twig-bridge suggests installing symfony/expression-language (For using the ExpressionExtension)
symfony/twig-bridge suggests installing symfony/form (For using the FormExtension)
symfony/twig-bridge suggests installing symfony/http-kernel (For using the HttpKernelExtension)
symfony/twig-bridge suggests installing symfony/routing (For using the RoutingExtension)
symfony/twig-bridge suggests installing symfony/security (For using the SecurityExtension)
symfony/twig-bridge suggests installing symfony/stopwatch (For using the StopwatchExtension)
symfony/twig-bridge suggests installing symfony/templating (For using the TwigEngine)
symfony/twig-bridge suggests installing symfony/translation (For using the TranslationExtension)
symfony/twig-bridge suggests installing symfony/web-link (For using the WebLinkExtension)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
dealerdirect/phpcodesniffer-composer-installer suggests installing dealerdirect/qa-tools (All the PHP QA tools you'll need)

acquia/blt suggests installing hirak/prestissimo (^0.3)
acquia/blt suggests installing typhonius/acquia_cli (^0.0.7)
acquia/blt suggests installing davereid/drush-acquia-hook-invoke (dev-master)
Writing lock file
Generating autoload files
Copying /var/www/zzz/my-project/vendor/acquia/blt/composer.required.json to /var/www/zzz/my-project/blt/composer.required.json
Copying /var/www/zzz/my-project/vendor/acquia/blt/composer.suggested.json to /var/www/zzz/my-project/blt/composer.suggested.json
    1/4:        http://packagist.org/p/provider-latest$dd1df99747ed0f2cb3440db12cd086d5ca6a9fd0e8fe3a19a997fd57a8706d33.json
    2/4:        http://packagist.org/p/provider-2017-10$bd7747b126712bc073e8a94f1816abbab34ebfa7b7023f30aa69fe0f5714a30a.json
    3/4:        http://packagist.org/p/provider-2018-01$9ca03210b77ed6bf6149f2fc794f88cfb652f29cb22e168132f93d88130c7cb9.json
    4/4:        http://packagist.org/p/provider-2017-07$a230419950dc318eb3e05a6873c9eb1b751da9c54fd074056a0fa85e37997d01.json
    Finished: success: 4, skipped: 0, failure: 0, total: 4
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
Creating BLT templated files...
 > /var/www/zzz/my-project/vendor/acquia/blt/bin/blt internal:create-project --ansi
[warning] The xDebug extension is loaded. This will significantly decrease performance.
Copying files from BLT's template into your project...
Merging default configuration into composer.json...
Merging BLT's blt.yml template with your project's blt/blt.yml...
Installing new Composer dependencies provided by BLT. This make take a while...
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /var/www/zzz/my-project/vendor/symfony/console/Application.php:129
Stack trace:
#0 /var/www/zzz/my-project/vendor/consolidation/robo/src/Runner.php(175): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/zzz/my-project/vendor/acquia/blt/src/Robo/Blt.php(236): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#2 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt-robo-run.php(33): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/var/www/glbdru...')
#4 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt in /var/www/zzz/my-project/vendor/symfony/console/Application.php on line 129

Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in /var/www/zzz/my-project/vendor/symfony/console/Application.php:129
Stack trace:
#0 /var/www/zzz/my-project/vendor/consolidation/robo/src/Runner.php(175): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/zzz/my-project/vendor/acquia/blt/src/Robo/Blt.php(236): Robo\Runner->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Acquia\Blt\Robo\Application), Array)
#2 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt-robo-run.php(33): Acquia\Blt\Robo\Blt->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/var/www/glbdru...')
#4 /var/www/zzz/my-project/vendor/acquia/blt/bin/blt in /var/www/zzz/my-project/vendor/symfony/console/Application.php on line 129
BLT installation failed! Please execute /var/www/zzz/my-project/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.
An error occurred while removing the VCS metadata: Could not delete /var/www/zzz/my-project/.git/objects/pack/pack-ed06fc9c4ba82b107caa8919c5f67603e238d17e.idx:
Could not scan for classes inside "/var/www/zzz/my-project/vendor/sebastian/global-state/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/phpunit/php-timer/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/webflo/drupal-finder/src/DrupalFinder.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/sebastian/comparator/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/sebastian/diff/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/phpunit/phpunit-mock-objects/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/phpunit/php-code-coverage/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/phpunit/php-token-stream/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/sebastian/environment/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/sebastian/exporter/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/sebastian/recursion-context/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Exception.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Fixer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Report.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Reporting.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Sniff.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Tokens.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Reports/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Tokenizers/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/DocGenerators/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/AbstractPatternSniff.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/AbstractScopeSniff.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/AbstractVariableSniff.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/IncorrectPatternException.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Generic/Sniffs/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/MySource/Sniffs/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PEAR/Sniffs/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PSR1/Sniffs/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/PSR2/Sniffs/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Squiz/Sniffs/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Zend/Sniffs/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/phpunit/phpunit/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/phpunit/php-file-iterator/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/phpunit/php-text-template/src/" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/zzz/my-project/vendor/sebastian/version/src/" which does not appear to be a file nor a folder
> blt internal:create-project:init-repo
PHP Warning:  require(/var/www/zzz/my-project/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /var/www/zzz/my-project/vendor/composer/autoload_real.php on line 66

Warning: require(/var/www/zzz/my-project/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php): failed to open stream: No such file or directory in /var/www/zzz/my-project/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/zzz/my-project/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/zzz/my-project/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/zzz/my-project/vendor/composer/../symfony/polyfill-mbstring/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/zzz/my-project/vendor/composer/autoload_real.php on line 66
Script blt internal:create-project:init-repo handling the post-create-project-cmd event returned with error code 255

**Comment by grasmash** [comment]
Do you happen to have some global composer packages installed, like phpcs, that may be interfering with the instal process?

**Comment by uenrico** [comment]
I'm running this inside a default installed geerlingguy/ubuntu1604 VM. No phpcs installed

**Comment by grasmash** [comment]
Well luckily that sounds very reproducible. 


However, I should mention that typically the create project command is run on the host machine. A vm is then created via “blt vm.” 

Even so, what you are doing should work.

**Comment by uenrico** [comment]
you are right, your approach is the typical, however I was using this way and works fine with version 8.9.2

**Comment by grasmash** [comment]
Feature branches ` issue-2496-fatal-error` created on blt-project and blt to debug issue.

`composer create-project acquia/blt-project:dev- issue-2496-fatal-error --no-interaction my-project`

**Comment by grasmash** [comment]
This is successful for me:
```
git clone https://github.com/geerlingguy/drupal-vm.git
cd drupal-vm
cp default.config.yml config.yml
echo '' >> config.yml
echo 'php_packages_extra:' >> config.yml
echo '  - "php{{ php_version }}-bz2"' >> config.yml
vagrant ssh
cd ../..
composer create-project acquia/blt-project:9.x-dev --no-interaction my-project
```

**Comment by grasmash** [comment]
Try `composer create-project acquia/blt-project:dev-issue-2496-fatal-error --no-interaction my-project` and see if it makes a difference.

**Comment by uenrico** [comment]
composer create-project acquia/blt-project:dev-issue-2496-fatal-error --no-interaction my-project

works fine, ends without errors

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2497
