### ISSUE TITLE
Update Docs to Include Drush Launcher

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2498]
We should include https://github.com/drush-ops/drush-launcher as a Host Operating System System Requirement. It seems logical to me to include this at the same level as PHP / Composer / Git. However, I notice that Drush itself is NOT a system requirement... so maybe not?

It's also unclear to me if there is a corollary Windows requirement / alternative that we should document.

I'm open to suggestions as to where we should put this in the docs, but right now it isn't there and I believe it should be.

@grasmash / @danepowell thoughts or opinions?

**Comment by grasmash** [comment]
It's not actually a requirement, though it would be suggested for general Drupal development.

**Comment by grasmash** [comment]
Already there:

> Note that the recommended installation method for Drush has changed recently. Drush should only be installed as a dependency of individual projects, rather than being installed system-wide. BLT will manage this dependency for you on projects, but in order for you to run Drush commands independently of BLT commands you'll want to install the Drush Launcher as above.

http://blt.readthedocs.io/en/9.x/INSTALL/
