### ISSUE TITLE
Schema File Validation

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2511]
I am getting a codesniffer error on the schema file for BLT. @grasmash and I have discussed but this is still a problem in 9 Beta 2.

**Comment by mikemadison13** [comment]
This seems to specifically be failing during the git hook not the normal BLT validate. I've tried making changes to vendor/acquia/blt/phpcs.xml.dist but that doesn't seem to be helping.

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2534
