### ISSUE TITLE
Question: BLT and non-VM Local LAMP Linux Box

### ISSUE THREAD

**Issue by deeplfo** [acquia/blt#2519]
Hi, 

So, I am able to build a local dev sandbox using BLT and a VM (drupal-vm), however I am trying to find the correct set of steps, and any configurations, required to build and deploy on a Linux box with a local LAMP stack.  Our project is already a BLT-based one, so given that I would not be using a VM of any kind, what would be the sequence of commands I would execute to build and deploy to the local LAMP Linux box?  

Might this be an example of the steps:
- composer install
- modify/create entries in blt/project.local.yml
- blt setup
- blt sync

Questions: 
1) I am assuming somehow I have to let BLT know that I am not using a VM and building for the local LAMP environment, which I guess would be "@self" alias?  So, where do I tell BLT that info, and do I need to touch/create a file for that purpose, perhaps blt/project.local.yml?

2) for sync do I need to run "blt sync" or is it "blt sync:refresh" that I need.  I guess this is one question that I have for a while, i.e. after a "blt setup" what's the "proper" sync command to run?

Thanks,
Mohsen

**Comment by grasmash** [comment]
You should be able to follow the onboarding doc:

http://blt.readthedocs.io/en/8.x/readme/onboarding/

That has the info you're looking for.

> I am assuming somehow I have to let BLT know that I am not using a VM and building for the local LAMP environment, which I guess would be "@self" alias? 

@self is the default. It's overridden on machines where `blt vm` has been run to create or boot a vm.

> for sync do I need to run "blt sync" or is it "blt sync:refresh" that I need.

`blt sync` will copy the db from upstream, but will perform no operations against it. 
`blt sync:refresh` will copy the db AND also execute db updates, import config, and clear caches.
