### ISSUE TITLE
Recommendation for setting different DB host in Gitlab CI docker environment

### ISSUE THREAD

**Issue by timwood** [acquia/blt#2543]
My system information:
* Operating system type: Gitlab/Docker
* Operating system version: php:7.1-fpm docker image with mysql:5.6 service
* BLT version: 8.9.11

When attempting to setup Gitlab CI using a docker runner, I need to set the Drupal database host to "mysql" rather than "localhost" because we are using mysql as a Docker service. How would it be best to go about doing this, without messing up the local DrupalVM-based environment, and when/what step/stage should this be done?

I tried setting "host" to "mysql" in docroot/sites/default/settings/default.local.settings.php, which works in the CI environment (when BLT copies this file to local.settings.php), but causes local DrupalVM-based environment to fail because it wants "host" to be "localhost".

I also tried running the following in one of the scripts called from Gitlab CI, but I think because local.settings.php takes precedent, it does nothing:
```
echo 'require DRUPAL_ROOT . "/../ci/gitlab.settings.php";' > docroot/sites/default/settings.php
```
Contents of ci/gitlab.settings.php (with host => mysql):
```
<?php

$databases = array(
  'default' => array(
    'default' => array(
      'database' => 'drupal',
      'username' => 'drupal',
      'password' => 'drupal',
      'host' => 'mysql',
      'port' => '3306',
      'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
```

Thanks!

**Comment by grasmash** [comment]
Is there an environmental variable in the GitLab env that we can check for in order to conditionally load these setting?

**Comment by grasmash** [comment]
This should do it:
https://github.com/acquia/blt/pull/2544

**Comment by grasmash** [comment]
In future, you can create an `includes.settings.php` file:
https://github.com/acquia/blt/blob/9.x/settings/blt.settings.php#L293

**Comment by timwood** [comment]
WOW! Thanks for the super fast reply. I'll test out the patch shortly.

**Comment by timwood** [comment]
Wouldn't `includes.settings.php` still be overridden by local.settings.php?

**Comment by timwood** [comment]
As we are using 8.9.11, the patch didn't apply cleanly. :-(

**Comment by grasmash** [comment]
> Wouldn't includes.settings.php still be overridden by local.settings.php?

Not after this change: https://github.com/acquia/blt/pull/2544/files#diff-3f01be0f15533ad5bd0f496e6bec3e74R82

**Comment by timwood** [comment]
Ah, gotcha.

**Comment by timwood** [comment]
This seems to have worked for our environment using BLT 8.9.x. Please let me know if you see any issues with this code and whether I should provide it as a PR for the 8.9.x branch.

```
diff --git a/settings/blt.settings.php b/settings/blt.settings.php
index a4980a4..2d06b2a 100644
--- a/settings/blt.settings.php
+++ b/settings/blt.settings.php
@@ -178,4 +178,8 @@
   elseif (getenv('PROBO_ENVIRONMENT') && file_exists(__DIR__ . '/probo.settings.php')) {
     require __DIR__ . '/probo.settings.php';
   }
+  // Load Gitlab settings.
+  elseif (getenv('GITLAB_CI') && file_exists(__DIR__ . '/gitlab.settings.php')) {
+    require __DIR__ . '/gitlab.settings.php';
+  }
 }
diff --git a/settings/gitlab.settings.php b/settings/gitlab.settings.php
new file mode 100644
index 0000000..8c3e213
--- /dev/null
+++ b/settings/gitlab.settings.php
@@ -0,0 +1,21 @@
+<?php
+
+/**
+ * @file
+ * GitLab environment specific settings.
+ */
+
+$databases = array(
+  'default' => array(
+    'default' => array(
+      'database' => 'drupal',
+      'username' => 'drupal',
+      'password' => 'drupal',
+      'host' => 'mysql',
+      'port' => '3306',
+      'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
+      'driver' => 'mysql',
+      'prefix' => '',
+    ),
+  ),
+);
```

**Comment by grasmash** [comment]
I'd accept as a PR to 8.9.x, thanks.
