### ISSUE TITLE
Slack Cloud Hook notifications never report failure

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2548]
My system information:
* BLT version: 8.9.x/9.x

BLT includes a script in cloud hooks that is supposed to send slack notifications of deployment successes and failures:
https://github.com/acquia/blt/blob/9.x/scripts/cloud-hooks/hooks/common/post-code-update/post-code-update.sh
https://github.com/acquia/blt/blob/9.x/scripts/cloud-hooks/hooks/common/slack.sh

The `slack.sh` script relies on the `$status` variable to be set in the preceding script (`functions.sh`) to determine whether the deploy was successful or not:
https://github.com/acquia/blt/blob/9.x/scripts/cloud-hooks/functions.sh

Unfortunately, that variable was removed in this PR, and in fact the script exits before slack is ever called, so BLT / Cloud Hooks will never report a failed deploy to Slack: https://github.com/acquia/blt/pull/1312

This bug is especially confusing on ACSF, because subsequent Cloud Hook calls in the update environments actually report success, even though they basically do nothing. We should not be calling slack at all in update environments.

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2552
