### ISSUE TITLE
Rogue local.yml file following upgrade

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2550]
I upgraded from 8.9.12 to 9.0.0-beta2. After the upgrade, I'm seeing a new file `blt/local.yml`. I don't know exactly what this is, but I'm pretty sure this shouldn't exist. Or if it should, it should be gitignored.

It looks sort of like a duplicate of `local.blt.yml`, except that `local.blt.yml` appears to be basically stock and doesn't have the customizations of `local.yml`.

**Comment by grasmash** [comment]
This may already be resolved in 9.x-dev:
https://github.com/acquia/blt/compare/9.0.0-beta2...9.x#diff-44e9a653e1dda2c509c8ccb1679dde05R490

**Comment by grasmash** [comment]
Referenced code released in 9.0.0-beta3.

**Comment by danepowell** [comment]
Sorry, I don't think this is fixed. I just tried upgrading from 8.9 to 9.0-beta3 and I'm still seeing this file show up.
