### ISSUE TITLE
BLT 9.0.0-beta3 showing error 'MySql is not available.' on drupal:install on Pipelines

### ISSUE THREAD

**Issue by jose-oliveira** [acquia/blt#2555]
My system information:
* Pipelines, default yml generated by BLT
* BLT version: 9.0.0-beta3

Output of `blt doctor`:
```

```

When I run this command(on Pipelines, local works fine):
```
drupal:install
```

I get the following output:
```
[error]  MySql is not available. Please run `blt doctor` to diagnose the issue. 
[error]  Command `drupal:install ` exited with code 1. 
6.994s total time elapsed.

pipelines_kill_background_processes

pstree -p $$  grep -E -o '([0-9]+)'  grep -v "^$$\$"  sort -k2 -rn
```

And I expected this to happen: Pipelines build to work.

**Note:** I tested the build with BLT 8.9.11 and it worked fine.

**Comment by geerlingguy** [comment]
@grasmash could this be related to https://github.com/acquia/blt/issues/2594 ?

**Comment by grasmash** [comment]
I think this issue has been addressed here: https://github.com/acquia/blt/pull/2602/files#diff-3f01be0f15533ad5bd0f496e6bec3e74R82
