### ISSUE TITLE
Your BLT schema is out of date

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#2557]
My system information:

* BLT version: 8.9.11

I have Travis integration with BLT.

After executing all the scripts from .travis.yml file at the end it's asking for input to update BLT schema, but I can't give input on https://travis-ci.com/.

Basically I had the following script in .travis.yml file.
**script:
  - blt -Dbehat.run-server=true -Dcreate_alias=false -Dbehat.launch-phantom=true ci:build:validate:test -Dblt.verbose=true**

but it was throwing the below error & build was failing.

**[Symfony\Component\Console\Exception\CommandNotFoundException]       
  There are no commands defined in the "ci:build:validate" namespace.  
                                                                       
  Did you mean this?                                                   
      simplesamlphp:build**

To get rid of this I removed the "ci:build:validate" from script: and see the below issue.

I get the following output:

[warning] Your BLT schema is out of date.
 Would you like to run outstanding updates? (y/n) 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated

Build should have happened successfully. Please help me to fix this issue.

**Comment by grasmash** [comment]
It looks like your BLT schema is out of date. You should run `blt update` locally to perform updates, commit, and push.

Are you committing your `composer.json`?

**Comment by sandipsmarty** [comment]
Yes I am commiting my composer.json & in this file the blt version mentioned is
 "acquia/blt": "^8.3",

**Comment by sandipsmarty** [comment]
After running **blt update** the "BLT schema is out of date" issue got resolved. 

In my .travis.yml file the following line is there.

script:
  - blt -Dbehat.run-server=true -Dcreate_alias=false -Dbehat.launch-phantom=true ci:build:validate -Dblt.verbose=true

Now its throwing the below error & Travis build is getting failed. 

[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ci:build" namespace.      
                                                                  
  Did you mean one of these?                                      
      simplesamlphp:build                                         
      ci:gitlab                                                   
      ci:probo                                                    
      ci:travis                                                   
      ci:pipelines                                                
      ci             

Seems updated BLT version doesn't have the command "ci:build:validate" available. Not sure what could be the alternative.

**Comment by grasmash** [comment]
All of these issues seem to indicate an improper update. 

When updating BLT (e.g., and update from 8.9.5 to 8.9.12), you will need to follow the update instructions for the relevant releases, which can be found here on the release page. Note that instructions are not provided for alpha, beta, etc. releases.

In this case you likely need to run `blt ci:travis:init`.

The 8.9.0 release instructions include:

- [Use Composer to update BLT](http://blt.readthedocs.io/en/8.x/readme/updating-blt/), as usual. `composer require acquia/blt:^8.9.0 --no-update && composer update`
- Manually execute `blt update` to execute scripted updates.
- Re-initialize default Drupal VM configuration via `blt vm:nuke && blt vm:config` (if applicable).
- Re-initialize default Travis CI configuration via `blt ci:travis:init` (if applicable).
- Re-initialize default Acquia Pipelines configuration via `blt ci:pipelines:init` (if applicable).
- Re-initialize local Behat config via `rm tests/behat/local.yml tests/behat/behat.yml tests/behat/example.local.yml && blt setup:behat`
- Port custom Phing commands to Robo. __All Phing commands are now obsolete__. See [extending BLT]( http://blt.readthedocs.io/en/8.x/readme/extending-blt/) to learn how you can write custom commands and hooks with Robo. (if applicable).
- View the full list of commands via `blt list`. __BLT commands have changed__.
- Run `blt doctor` to inspect and verify your configuration.

**Comment by sandipsmarty** [comment]
In my pull request now the above mentioned issues are resolved & Travis passed successfully, but when I merged the PR I see the following error at the end.

I get the following output & build failed.
"There are uncommitted changes, commit or stash these changes before deploying." This is weird.

**Comment by grasmash** [comment]
It seems like your build process is adding or modifying files. Can you add a `git diff` line at the end of the build script to check for changes?

**Comment by sandipsmarty** [comment]
@grasmash : As of now for my project I resolved this issue by not upgrading BLT, I will look into this more when I will plan to upgrade Drupal core along with BLT & other dependency packages. 

Thanks for your help anyway. I will open a new ticket in future if required.
