### ISSUE TITLE
PHPCS should not sniff .schema_version

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2558]
I just upgraded from 8.9.12 to 9.0.0-beta3. When I tried to commit the resulting changes (including the updated schema version), PHPCS failed the commit:

> Executing .git/hooks/pre-commit...
[warning] Drupal VM is locally initialized, but is not running.
[warning] The xDebug extension is loaded. This will significantly decrease performance.
> tests:phpcs:sniff:files
Sniffing directories containing changed files...
[File\Write] Writing to /home/dane/sites/foo/tmp/phpcs-fileset.
[ExecStack] '/home/dane/sites/foo/vendor/bin/phpcs' --file-list='/home/dane/sites/foo/tmp/phpcs-fileset' --bootstrap='/home/dane/sites/foo/vendor/acquia/blt/src/Robo/Commands/Validate/phpcs-validate-files-bootstrap.php' -l
.E
FILE: /home/dane/sites/foo/blt/.schema_version
FOUND 1 ERROR AFFECTING 1 LINE
 1 | ERROR | [x] Expected 1 newline at end of file; 0 found
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

**Comment by mikemadison13** [comment]
this is related to #2511 btw @danepowell. I _thought_ it was fixed, but perhaps not

**Comment by danepowell** [comment]
Just spitballing here since I've already deleted my test site and can't verify empirically... maybe since phpcs.xml.dist exists in the project template, it's not getting updated, and thus PHPCS is still using the old version from 8.9.x that doesn't have the fix from #2511

**Comment by grasmash** [comment]
Yeah I think that's it.

**Comment by grasmash** [comment]
This should do it: https://github.com/acquia/blt/pull/2562
