### ISSUE TITLE
Strategy for differently named docroot

### ISSUE THREAD

**Issue by dnotes** [acquia/blt#2567]
It seems (and the documentation says) that BLT is hard-coded to use a nested web root folder named "docroot", but most hosting providers and systems with which I am familiar use other names for that folder, notably "web" in the cases of Pantheon and Platform.sh. As a BLT user, how would I deal with this? Is there a reason why the name of the web root folder is not configurable, as it is with other local development tools like Lando?

**Comment by dpagini** [comment]
Just a suggestion... you could use a `post-deploy-build` hook to move the `deploy/docroot` folder to `deploy/web` in your artifact. There would maybe be some fallout with that though... I mean, my _first_ thought is your deployed code might not run BLT commands...? It would probably take some testing out...

**Comment by greylabel** [comment]
Any reason we couldn't just make the _webroot directory_ configurable?

**Comment by grasmash** [comment]
I know that for pantheon in particular, you can change the location of the web directory to something else. You just have to set a value in a configuration file. 

I have not tried platform.sh, but I’d try creating a symlink.

If that doesn’t work, I am open to investigating this as a feature. However, I think that it would be more difficult than a simple find replace operation. There are some static files where it is hardcoded, like .gitignore. Not sure how we would handle that.

**Comment by grasmash** [comment]
There are simple known solutions for naming docroot something else, as outlined above. I'm going to close this for now. If the workarounds are insufficient, please open a new issue and indicate the problems with the workarounds as well as the desired behavior.

**Comment by davidgil** [comment]
https://pantheon.io/docs/nested-docroot/

**Comment by snufkin** [comment]
In case some else also ends up on this thread: you can change the name of the docroot on platform.sh in the .platform.app.yaml file, so that should not be an issue with BLT.

**Comment by jigarius** [comment]
Also, Drupal's recommended docroot name seems to be `web`? Because if you follow the Drupal installation instructions using composer, you get a docroot named `web`. So, I guess, `docroot` is the non-conventional name and `web` is more conventional these days.

**Comment by backlineint** [comment]
I know this is long since closed, but I'll second @jigarius that docroot seems to be the non-standard home for Drupal these days. If the desire with BLT 12 is to allow BLT to be added to an existing project rather than requiring a specific starter project, making the webroot configurable would allow BLT to be added more easily to more projects.
