### ISSUE TITLE
BLT is not compatible with SQLite

### ISSUE THREAD

**Issue by CashWilliams** [acquia/blt#2572]
The [mysql validation hook](https://github.com/acquia/blt/blob/9.x/src/Robo/Hooks/ValidateHook.php#L102) causes fatal errors when using SQLite as the database for local development.

**Comment by tenken** [comment]
In all fairness, the docs explicitly say to use MySQL as the DBMS. I don't know if all the contrib/vendor modules/libraries all support sqlite fully. I attempted an sqlite install just yesterday when examining BLT for D8 development workflows.

An additional issue I can see in BLT being a generic build tool is that by default the setup automation last step of `git init && git commit` will commit all of the Lightning required modules to the git repo. If one modifies blt.yml to use the `Standard` profile, removes or provides a custom composer.*.suggested.yml, and does a `blt setup` for a site installation ... the 1st git commit will still have all of the Lightning dependencies in the commit history prior to Standard drupal being installed. This would seem to be leaving a messy git history for non Lightning based projects. I see no way around this currently. But, I haven't looked very deeply.

**Comment by geerlingguy** [comment]
It looks like with a fresh new setup, this can sometimes happen too (it seemed to happen in 8.x stable here: https://github.com/acquia/blt/issues/2594 (cc @cajuclc) and also seems to have plagued someone else on BLT 9.x...

**Comment by ba66e77** [comment]
Seems to me this issue falls under the category of BLT being opinionated on tooling and not trying to cover all the possible configurations. Given that, I'm calling this a won't fix.
