### ISSUE TITLE
[InvalidArgumentException] Script "blt-alias" is not defined in this package 

### ISSUE THREAD

**Issue by tarun-axelerant** [acquia/blt#2573]
My system information:
* Operating system type: [Ubuntu]
* Operating system version: [16]
* BLT version: [replace]

Output of `blt doctor`:
```

```

When I run this command:
```
[composer run-script blt-alias]
```

I get the following output:
```
[pt blt-alias
Cannot create cache directory /home/tarun/.composer/cache/repo/https---packages.drupal.org-8/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/tarun/.composer/cache/repo/https---asset-packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/tarun/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/tarun/.composer/cache/files/, or directory is not writable. Proceeding without cache

                                                     
  [InvalidArgumentException]                         
  Script "blt-alias" is not defined in this package  
                                                     

run-script [--timeout TIMEOUT] [--dev] [--no-dev] [-l|--list] [--] [<script>] [<args>]...
]
```

And I expected this to happen:

**Comment by grasmash** [comment]
Can you please indicate your version of BLT? Are your composer dependencies installed?

**Comment by tarun-axelerant** [comment]
@grasmash 

Issue has been resolved. Following things I did:

1. PHP version was old 7.0 and for project it was needed 7.1.
2. I executed few commands with sudo and few without it that's why cache issue was there. 
3. executed sudo apt-get install php7.1 php7.1-xml
4. pull the composer.lock from git after deleting existing
5. executed composer install command again

**Comment by grasmash** [comment]
Thank you for updating the issue.
