### ISSUE TITLE
Any reason why`drupal/devel` is at the `require` section of the `composer.suggested.json` file.

### ISSUE THREAD

**Issue by jmolivas** [acquia/blt#2576]
My system information:
* Operating system type: [OSX]
* Operating system version: [Sierra 10.12.6]
* BLT version: [any]

Any reason why `drupal/devel` is at the `require` section of the `composer. suggested.json` file.

https://github.com/acquia/blt/blob/9.x/composer.suggested.json#L13

Not sure you want to end up with that dependency on your production server when deploying.

I can confirm after executing.
```
composer install --no-dev
```
The `drupal/devel` dependency is not removed.

**Comment by jmolivas** [comment]
I can take care of sending a PR if this change is accepted?

**Comment by dpagini** [comment]
@jmolivas you are linking to the `composer.suggested.json` file, not the required. I only comment b/c I had almost the same feedback in #1949, and it looks like I might get the "git blame" for that being in the suggested file... when I removed from required and added to suggested. I personally don't use the suggested file at all and just bring in the dependencies I want 1 by 1, but I would probably have the same feedback if I were using it.
I would sort of agree though, it seems like that module would make more sense in the `require-dev` section of that `composer.suggested.json` file, and also just preach "best practices".

**Comment by CashWilliams** [comment]
The purpose of having devel in the `composer.suggested.json` file is to ensure devel is available on remote artifact deployed development and staging environments if needed (since artifacts are built with --no-dev).

If you do not need this functionality, you can remove the `composer.suggested.json` file from your `composer.json` file and copy the dependencies you do need. See http://blt.readthedocs.io/en/latest/readme/dependency-management/#modifying-blts-default-composer-values for more info.

**Comment by tenken** [comment]
@CashWilliams is directly modifying `composer.suggested.json` and `composer.required.json` safe for non Lightning projects? And is it BLT upgrade safe? I ended up taking the following approach in attempting to use BLT without Lightning:

```json
    "merge-plugin": {
        "require": [
            "vendor/acquia/blt/composer.MYORG.required.json",
            "vendor/acquia/blt/composer.MYORG.suggested.json"
        ],
        "include": [
            "blt/composer.overrides.json"
        ],
        "merge-extra": true,
        "merge-extra-deep": true,
        "merge-scripts": true,
        "replace": false,
        "ignore-duplicates": true
    },
```
and copying the default composer file(s) contents into the MYORG files and then removing the Lightning dependencies from my project. Is this a suitable approach for non-Lightning projects. I fear that updating BLT would overwrite or create conflicts with the default composer files in the long run by modifying them directly.

**Comment by grasmash** [comment]
You should not modify `composer.suggested.json` or `composer.required.json`. You can remove `composer.suggested.json`, though.

If you don't like something in `composer.required.json`, you can simply override it in your root `composer.json`.
