### ISSUE TITLE
Use strict variable interpolation in git-hooks pre-commit

### ISSUE THREAD

**Issue by gdeni** [acquia/blt#2587]
My system information:
* BLT version: 8.x

When I run this command:
```
git commit
```
We have a custom robo task which runs a shell command: `git diff ...` and it exits with an error:
> Not a git repository

But I'm quite sure I'm in the right directory.
I don't know why, but this modification fixed the problem:
File name: scripts/git-hooks/pre-commit
```bash
"${ROOT_DIR}"/vendor/bin/blt git:pre-commit "${LIST}"
```

Note the curly brackets around the LIST variable.

**Comment by grasmash** [comment]
I'm don't fully understand the issue from your description, but if the indicated change fixes it, I'm fine with using curly braces on the $LIST variable.
