### ISSUE TITLE
blt vm:nuke overwrites php_memory_limit

### ISSUE THREAD

**Issue by deeplfo** [acquia/blt#2593]
My system information:
* Operating system type: macOS Sierra
* Operating system version: 10.12.26
* BLT version: [replace]

This is an issue with executing `blt vm:nuke`.  The `box/config.yml` file committed to our source repository has a `php_memory_limit = 1024K` setting .  However, when executing `blt vm:nuke`, in addition to replacing the Ansible placeholder parameters, `blt` is also overwriting the memory limit settings back to a default value of `php_memory_limit = 512K` value.  I would expect that `blt` not overwrite that variable.

**Comment by grasmash** [comment]
The intended behavior is to completely destroy all custom configuration and give you default config. This is working as intended.

**Comment by deeplfo** [comment]
OK, I guess we would need to revert the custom settings if we run `blt vm:nuke`.  One other question: the following parameters didn't seem to get replaced after `blt vm`:
```
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"
...
php_packages_extra:
  - "php{{ php_version }}-bz2"
```

Is that also expected behavior?

Thanks,
mohsen

**Comment by grasmash** [comment]
That is expected. Those are not BLT variables, those are Ansible variables. They should be evaluated during VM provisioning.

**Comment by deeplfo** [comment]
Right, but I asked since a couple of other Ansible variables were replaced during VM provisioning, but not those, so was curious if that's intentional?  For example this one was replaced:
```
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
```

thx
