### ISSUE TITLE
How to relax coding standards check to prevent "Warning" from stopping a commit?

### ISSUE THREAD

**Issue by kevinquillen** [acquia/blt#2599]
The git precommit hook is stopping on a line of code throwing:

`WARNING | Possible useless method overriding detected`

In this case, it is:

```
  /**
   * {@inheritdoc}
   */
  public function query() {}
```

Which seems to be required for certain kinds of Views fields when you don't want anything to happen here.

How can I relax this rule so it does not stop the commit on a warning?

**Comment by grasmash** [comment]
You'll have to modify your phpcs.xml. Look at https://github.com/acquia/blt/blob/9.x/template/phpcs.xml.dist#L10 to see how you can ignore all warnings or https://github.com/acquia/blt/blob/9.x/template/phpcs.xml.dist#L26 to see how you con exclude a specific rule.

**Comment by kevinquillen** [comment]
Thanks, that was quick. Now it works.
