### ISSUE TITLE
Support for Drupal 8.5.x in BLT 8.9.x

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2603]
The BLT readme currently states that BLT 8.9.x only supports up to Drupal core 8.4, and that 8.5 and above will require BLT 9.x.

I think we should revisit this policy, given that:

1. There is currently no stable release of BLT 9.x
2. Drupal 8.4 is end-of-life tomorrow, when Drupal 8.5.0 drops
3. It would require minimal effort for BLT 8.9.x to support Drupal 8.5.0. As far as I know the only problem is a dependency conflict (described below). I'm also checking on Drush 8 compatibility: https://github.com/drush-ops/drush/issues/3440

The dependency conflict is that BLT and Drupal 8.5 require different versions of symfony/yaml:
https://cgit.drupalcode.org/drupal/tree/core/composer.json#n33
https://github.com/acquia/blt/blob/8.9.x/composer.json#L33

**Comment by grasmash** [comment]
8.1.13 addresses this.

**Comment by dpagini** [comment]
`8.1.13` meaning `8.9.13`?

**Comment by danepowell** [comment]
yep 8.9.13 fixes it
