### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by justinlevi** [acquia/blt#261]
I'd love to see all of the documentation come out of the readme files and moved into a single more cohesive location. The Drupal-VM documentation is a lot more useful and easier to navigate and find IMHO. 

I find myself doing a site-wide code search for keywords to find things in the docs which seems a little inefficient and inaccessible to new users.

**Comment by grasmash** [comment]
Are you suggesting creating a site like this?

http://docs.drupalvm.com/en/latest/

**Comment by grasmash** [comment]
Docs have been moved to readthedocs.org
