### ISSUE TITLE
External git projects for local development

### ISSUE THREAD

**Issue by japerry** [acquia/blt#2620]
As a Drupal contrib developer, I want to use BLT as my basis to provide an environment in which I can develop my module. 

This currently can be done on a per-project basis by doing the following:
1) create a folder outside the docroot. (I call it dev-modules)
2) Create a hook that replaces the composer installed version of a module with the local copy via a symlink (but only if the local version exists)
3) Run blt setup:composer:install
4) Profit!

I've done this for three different projects thus far, so perhaps is useful for others?

**Comment by grasmash** [comment]
How would you like to see this supported by BLT?

**Comment by mikemadison13** [comment]
@japerry ping

**Comment by grasmash** [comment]
I'm going to close this issue due to inactivity. It's not clear what feature is desired.
