### ISSUE TITLE
CI Environment: How to deal with composer.required.json and composer.suggested.json

### ISSUE THREAD

**Issue by timwood** [acquia/blt#2645]
Now that composer.required.json and composer.suggested.json are copied from the BLT vendor directory into the `blt/` folder and referenced from there in the root composer.json, but also git ignored, how is a CI environment supposed to reconcile the merge-plugin? Having the CI run `composer install --ansi` fails with:
```
[Wikimedia\Composer\Merge\MissingFileException]                       
merge-plugin: No files matched required 'blt/composer.required.json'  
```

Our CI does a fresh `git clone` from inside a docker container, so there is no vendor dir to copy these files from.

Should we remove the .gitignore and commit these two files inside the `blt/` directory?

**Comment by timwood** [comment]
Not sure why `composer install --ansi` was working before, when the merge-plugin section in `composer.json` was referencing the files inside the BLT vendor directory...

**Comment by grasmash** [comment]
I think you may need to clear your CI cache, it should work even when they are not initially present.

**Comment by timwood** [comment]
That was it. Clearing the Gitlab runner cache fixed it! Thanks for the suggestion.

**Comment by timwood** [comment]
Clear cache only fixed it for one job in the pipeline. Second job failed again with same issue. Would there be any harm in committing `composer.required.json` and `composer.suggested.json`?

**Comment by grasmash** [comment]
No there should be no harm it that.

**Comment by timwood** [comment]
I tried disabling caching of the vendor dir, but that has other negative effects which I've been trying to debug. Arg! Change is hard.
