### ISSUE TITLE
Fix git pre-commit hook to work with SourceTree

### ISSUE THREAD

**Issue by timwood** [acquia/blt#2647]
My system information:
* Operating system type: Mac OS
* Operating system version: Sierra
* BLT version: 8.9.x or 9.x

When my colleagues attempt to commit via SourceTree, they get the following output:
```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/z0/y9rsydq953q9skd7hqxtrf54001mwx/T/SourceTreeTemp.W7FRdx 
Executing .git/hooks/pre-commit...

Parse error: parse error, expecting `';'' or `'{'' in /Users/USERNAME/Sites/PROJECTNAME/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50
Completed with errors, see above
```

And I expected this to happen:
The commit to work.

I believe this is happening because there are multiple versions of PHP installed in the system and when the git pre-commit hook is run from SourceTree, it is using an older version of PHP (5.6), because it isn't getting a properly/fully initialized shell.

Reference with suggestions:
https://community.atlassian.com/t5/Bitbucket-questions/SourceTree-Hook-failing-because-paths-don-t-seem-to-be-set/qaq-p/274792

**Comment by grasmash** [comment]
PHP 7.1 is the minimum requirement for BLT 9.x. Can you update the version of PHP that SourceTree uses? That seems like the best option. We're not able to support PHP 5.6.

**Comment by mikemadison13** [comment]
@timwood I really think this is something will have to be fixed in the SourceTree app, I don't see how BLT can "fix" this, given that we have moved beyond PHP 5.6 (and it seems that SourceTree is stuck there).

**Comment by timwood** [comment]
I think SourceTree just needs to be told where to find the brew-installed PHP 7.1. Or this will resolve itself once we are able to upgrade to High Sierra.
