### ISSUE TITLE
Acquia cloud hook db-scrub.sh not working

### ISSUE THREAD

**Issue by timwood** [acquia/blt#2658]
My system information:
* Operating system type: Acquia environment
* Operating system version: Acquia
* BLT version: 9.0.4

When I run this command:
```
[2018-03-20 19:41:32] [2018-03-20 19:41:31] Starting hook: post-db-copy
[2018-03-20 19:41:31] Executing: /mnt/users/mfgov/dev.shell /var/www/html/mfgov.dev/hooks/common/post-db-copy/1-db-scrub.sh mfgov dev mfgov prod < /dev/null (as mfgov.dev@staging-11739})

```

I get the following output:
```
site="$1"
target_env="$2"
db_name="$3"
source_env="$4"

acsf_file="/mnt/files/$AH_SITE_GROUP.$AH_SITE_ENVIRONMENT/files-private/sites.json"
if [ ! -f $acsf_file ]; then
  echo "$site.$target_env: Scrubbing database $db_name"
  drush @$site.$target_env sql-sanitize --sanitize-password="$(openssl rand -base64 32)" --yes
  drush @$site.$target_env cache-rebuild
fi
mfgov.dev: Scrubbing database mfgov
ArgumentCountError: Too few arguments to function Drush\Sql\SqlBase::__construct(), 1 passed and exactly 2 expected in Drush\Sql\SqlBase->__construct() (line 34 of /mnt/www/html/mfgovdev/vendor/drush/drush/src/Sql/SqlBase.php).
Drush command terminated abnormally due to an unrecoverable error.       [error]
[2018-03-20 19:41:32] Finished hook: post-db-copy

[2018-03-20 19:41:32] Not sending webhook hook: 'post-db-copy' revision: ''
[2018-03-20 19:41:32] WARN: Command returned exit code 1: /mnt/users/mfgov/dev.shell /var/www/html/mfgov.dev/hooks/common/post-db-copy/1-db-scrub.sh mfgov dev mfgov prod executing hook post-db-copy
zlib(finalizer): the stream was freed prematurely.
```

And I expected this to happen:
The hook to run correctly.

**Comment by mikemadison13** [comment]
@timwood I found a comment over on the Drush issue queue related to this where drush 9 is installed via composer, but drush 8 is actually executing the commands (and I'm wondering if that is the case here, since that is a cloud hook i think?)

https://github.com/drush-ops/drush/issues/3064

**Comment by mikemadison13** [comment]
@timwood could you please ssh onto the server and run a couple of commands and report back?

from inside the docroot:
```st --debug```

```echo $_SERVER['PWD']```

The question is, can Drush bootstrap Drupal, and does the PWD super global work (we basically just need to know if it returns [PWD] or something valid).

**Comment by timwood** [comment]
```bash
st --debug
bash: st: command not found
```

```bash
echo $_SERVER['PWD']
[PWD]
```

**Comment by grasmash** [comment]
`printenv' may give you what you're looking for, or `drush ev 'print_r($_SERVER);'`

**Comment by timwood** [comment]
```
AH_CURRENT_REGION=us-east-1
XDG_SESSION_ID=257071
TERM=xterm-256color
SHELL=/bin/bash
HISTSIZE=10000000
SSH_CLIENT=IP_ADDRESS 39359 22
TMPDIR=/mnt/tmp/mfgovdev
SSH_TTY=/dev/pts/0
USER=mfgov
TEMP=/mnt/tmp/mfgovdev
AH_SITE_NAME=mfgovdev
ACQUIA_HOSTING_DRUPAL_LOG=/var/log/sites/mfgov.dev/logs/staging-11739/drupal-requests.log
AH_REALM=prod
MAIL=/var/mail/mfgov.dev
PATH=/usr/local/php7.1/bin:/usr/local/drush8:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
AH_NON_PRODUCTION=1
PWD=/var/www/html/mfgov.dev/docroot
LANG=en_US.UTF-8
AH_SITE_ENVIRONMENT=dev
DRUSH_LAUNCHER_FALLBACK=/usr/local/drush8/drush
SHLVL=3
HOME=/home/mfgov
SSH_ORIGINAL_COMMAND=cd /var/www/html/mfgov.dev/docroot && bash -l
LOGNAME=mfgov.dev
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
SSH_CONNECTION=IP_ADDRESS 39359 IP_ADDRESS 22
AH_SITE_GROUP=mfgov
XDG_RUNTIME_DIR=/run/user/36406
HISTTIMEFORMAT=%F %T 
_=/usr/bin/printenv
```

**Comment by brooke-heaton** [comment]
Hey gents - it's me again! Long time no see :) So I'm following this closely as  I'm having similar issues related to BLT 9 and a mismatch of drush 9 (required by BLT I understand?) AC's default  drush8. I noticed for instance that I have no drush 9 aliases on AC - these follow a different format and convention than drush 8. I'm currently unable to run any drush commands against the cloud using drush 9, but I understand that I can't sql-sync with different versions of drush per another issue that @mikemadison13  is on. FWIW I can ssh into the cloud and run drush8 successfully but drush9 fails and returns ZERO aliases. Sorry if this is off script/topic.

**Comment by grasmash** [comment]
You should commit drush 9 style aliases to `drush/sites`. See https://github.com/acquia/blt/blob/9.x/template/drush/sites/README.md

**Comment by mikemadison13** [comment]
@timwood did you have a chance to experiment with this?

**Comment by timwood** [comment]
@mikemadison13 I did not yet, but should have time this week. Do you want to make the changes suggested by @grasmash before I test?

**Comment by mikemadison13** [comment]
@timwood yes, i am addressing them now. thanks, i had missed those!
