### ISSUE TITLE
Update ACSF Cloud Hooks / Factory Hooks 

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#2676]
There have been a number of updates to Cloud and Factory Hook scripts / templates in BLT 9.x that would be useful in BLT 8.9.x and are now recommended since the db-update Factory Hook was recently added. These include:

- Supporting additional environment stages following the standard `0xdev` / `0xtest` / `01xlive` syntax
- Excluding non-standard update environments from all Cloud Hooks scripts
- Explicit production environment checks
- Adding the post-install, db-update, and post-theme-refresh Factory Hooks

It may also be helpful to add help text to the `recipes:acsf` tasks which document the hooks and which are supported.

**Comment by grasmash** [comment]
Addressed by https://github.com/acquia/blt/pull/2685
