### ISSUE TITLE
Correct documentation on multisite drush alias overrides in docroot/sites/[site]/blt.yml

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/blt#2677]
My system information:
* Operating system type: MacOS
* Operating system version: High Sierra 10.13.3
* BLT version: 9.0.5

Output of `blt doctor`:
```
+---------------------------+---------------------------------------------------+
| Property                  | Value                                             |
+---------------------------+---------------------------------------------------+
| %paths.%root              | /app/docroot                                      |
| %paths.%site              | sites/default                                     |
| %paths.%modules           | sites/all/modules                                 |
| %paths.%themes            | sites/all/themes                                  |
| %paths.%config-sync       | /app/config/default                               |
| %paths.%files             | sites/default/files                               |
| %paths.%temp              | /tmp                                              |
| %paths.%private           | /app/files-private                                |
| admin-theme               | seven                                             |
| alias-searchpaths.0       | /app/drush/sites                                  |
| blt-version               | 9.0.5                                             |
| bootstrap                 | Successful                                        |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17        |
| config-sync               | /app/config/default                               |
| db-driver                 | mysql                                             |
| db-hostname               | integrity                                         |
| db-name                   | database                                          |
| db-password               | password                                          |
| db-port                   | 3306                                              |
| db-status                 | Connected                                         |
| db-username               | mysql                                             |
| drupal-settings-file      | sites/default/settings.php                        |
| drupal-version            | 8.5.0                                             |
| drush-alias-files.0       | /app/drush/sites/site-aliases/naswa.site.yml      |
| drush-alias-files.1       | /app/drush/sites/site-aliases/naswa_main.site.yml |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml                 |
| drush-conf.1              | /app/drush/drush.yml                              |
| drush-conf.2              | /app/docroot/sites/default/local.drush.yml        |
| drush-script              | /app/vendor/bin/drush                             |
| drush-temp                | /tmp                                              |
| drush-version             | 9.2.1                                             |
| files                     | sites/default/files                               |
| install-profile           | standard                                          |
| modules                   | sites/all/modules                                 |
| php-bin                   | /usr/local/bin/php                                |
| php-conf.1                | false                                             |
| php-os                    | Linux                                             |
| private                   | /app/files-private                                |
| root                      | /app/docroot                                      |
| site                      | sites/default                                     |
| stacks.drupal-vm.inited   | false                                             |
| stacks.dev-desktop.inited | false                                             |
| temp                      | /tmp                                              |
| theme                     | naswa                                             |
| themes                    | sites/all/themes                                  |
| uri                       | http://local.naswa.com                            |
+---------------------------+---------------------------------------------------+
+------------------------------------------+------------------------------------------------------------+
| Check                                    | Problem                                                    |
+------------------------------------------+------------------------------------------------------------+
| BehatCheck:checkLocalConfig:exists       | tests/behat/local.yml is missing!                          |
|                                          |   Run `blt tests:behat:init:config` to generate it from    |
|                                          | example.local.yml.                                         |
| ComposerCheck:checkPrestissimo:plugins   | hirak/prestissimo plugin for composer is not installed.    |
|                                          |   Run composer global require                              |
|                                          | hirak/prestissimo to install it.                           |
|                                          |   This will improve composer install/update performance by |
|                                          | parallelizing the download of dependency information.      |
| FileSystemCheck:checkFileSystem:%private | Private files directory does not exist.                    |
|                                          |                                                            |
|                                          | Create /app/files-private.                                 |
|                                          | Installing Drupal will create this directory for you.      |
|                                          | Run `blt drupal:install` to install Drupal, or run `blt    |
|                                          | setup` to run the entire setup process.                    |
|                                          | Otherwise, run `mkdir -p /app/files-private`.              |
|                                          |                                                            |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.  |
| WebUriCheck:checkUriResponse             | Did not get a response from http://local.naswa.com         |
|                                          | Is your *AMP stack running?                                |
|                                          | Is your /etc/hosts file correctly configured?              |
|                                          | Is your web server configured to serve this URI from       |
|                                          | /app/docroot?                                              |
|                                          | Is options.uri set correctly in                            |
|                                          | /app/docroot/sites/default/local.drush.yml?                |
+------------------------------------------+------------------------------------------------------------+
```

I think the documentation on multisite blt overrides here is incorrect based on a response I received running blt sync:all

[warning] The xDebug extension is loaded. This will significantly decrease performance.
Sync operations be performed for the following drush aliases:

@naswa.test => @self
@naswa.test => @self
To modify the set of aliases for syncing, set the values for drush.aliases.local and drush.aliases.remote in docroot/sites/[site]/blt.yml
So, I don't think my aliases should be in docroot/sites/[site]/site.yml - that should be docroot/sites/[site]/site.blt

The latter works for me. The former - per the documentation - does not.

**Comment by brooke-heaton** [comment]
I think the documentation on multisite blt overrides [here](https://blt.readthedocs.io/en/latest/readme/multisite/#blt-setup) is incorrect based on I received running `blt sync:all`

[warning] The xDebug extension is loaded. This will significantly decrease performance.
Sync operations be performed for the following drush aliases:
  * @naswa.test => @self
  * @naswa.test => @self
To modify the set of aliases for syncing, set the values for drush.aliases.local and drush.aliases.remote in docroot/sites/[site]/blt.yml

So, I don't think my aliases should be in docroot/sites/[site]/site.yml - that should be  docroot/sites/[site]/site.blt 

The latter works for me. The former - per the documentation - does not.

**Comment by brooke-heaton** [comment]
Just a further question as this is not addressed in the docs:

How should a multisite setup address the default 'local' url - as there would be more than one?

```
   local:
     protocol: http
-    hostname: 'local.${project.machine_name}.com'
```

**Comment by grasmash** [comment]
Each multi site has one uri, so you can define it for each site in docroot/sites/mysite/blt.yml

**Comment by brooke-heaton** [comment]
ah understood - just like above with the drush alias info. that should have been obvious to me but I've either had too little or too much coffee. Thanks @grasmash

**Comment by grasmash** [comment]
https://github.com/acquia/blt/pull/2678

**Comment by timwood** [comment]
Sorry to piggy-back on an issue, but is it possible to use BLT with multisite, where one site is already in Acquia cloud, but the second is only local and using `setup.strategy: install`?  Regardless of differing setup.strategy, what should the `drush.aliases.local` be set to in the site-specific `blt.yml`?

**Comment by brooke-heaton** [comment]
@timwood Following - I am in the midst of building the first 'subsite' but unsure how to run the build for both sites in the cloud - maybe the inverse if your question but still relevant. I see the 'default' site is building in the cloud and config is importing on Travis on Github but the configuration for the subsite is not yet apparent. 

Currently I have this in my first 'subsite' subsite1/blt.yml (note my local is using lando). This seems to run the **local** build process just fine:

```
drush:
  aliases:
    remote: subsite1.test
    local: subsite1.local
    ci: self
local:
 protocol: http
 hostname: 'https://subsite1.lndo.site'
```

**Comment by timwood** [comment]
Thanks @brooke-heaton. Here is what I have for my additional multisite (I'm trying to retrofit into a codebase for which the first site uses the `docroot/sites/default` folder). Maybe if I remove the `project:` and move the `local:` array over it will work...

Using DrupalVM, and running the blt commands inside the VM, it fails on any Drush command for this additional multisite when `drush.aliases.local` is set to `mfgusa.local` because drush tries to connect over SSH.

```
project:
  local:
    hostname: local.manufacturingusa.test
    protocol: http
  machine_name: mfgusa
  human_name: Manufacturing USA
drush:
  aliases:
    local: mfgusa.local
    remote: mfgusa.local
setup.strategy: install
```

**Comment by timwood** [comment]
@brooke-heaton Do you have a `docroot/sites/sites.php` ?

**Comment by brooke-heaton** [comment]
@timwood Yes, I have a sites.php but it references a different sites file locally:

```
$lando_sites_file = dirname(__FILE__) . "/sites.lando.php";
if (file_exists($lando_sites_file)) {
  include $lando_sites_file;
}
$local_sites_file = dirname(__FILE__) . "/sites.local.php";
if (file_exists($local_sites_file)) {
  include $local_sites_file;
}

$sites['devnaswa.naswa.org'] = 'naswa_main';
$sites['stagenaswa.naswa.org'] = 'naswa_main';
```

So, in other words, for a local build, it does not use the cloud settings, but rather the sites.lando.php - there's likely a similar approach for DrupalVM.

The sites.lando.php simply shows my local urls for my lando sites:

```
$sites['naswa_main.lndo.site'] = 'naswa_main';
$sites['naswa.lndo.site'] = 'default';
```

Footnote to the above - My local blt setup for my subsite just failed - it appears to be grabbing the wrong config directory. I'm working on resolving it.

**Comment by timwood** [comment]
@brooke-heaton and @pcsukardi I've made a little progress in my local setup. The thing that was missing was a properly setup sites.php, especially since I use a different TLD for the local environment because of HSTS. `docroot/sites/sites.php` looks like this:
```
$sites['local.manufacturingusa.test'] = 'manufacturingusa.com';
$sites['local.manufacturing.test'] = 'default';
```
I also adjusted the site-specific blt.yml for the second site to use `self` for local Drush alias:
```
project:
  local:
    hostname: local.manufacturingusa.test
    protocol: http
  machine_name: mfgusa
  human_name: Manufacturing USA
drush:
  aliases:
    local: self
    remote: mfgusa.local
setup.strategy: install

```

Now I'm working on properly splitting my config for by site with environment support per site (which sounds like what Brooke is also working on). Docs are a little lacking here: https://blt.readthedocs.io/en/latest/readme/config-split/#creating-a-site-split. I think I need to move all my primary site's config to a domain-named one and have the config/default be really basic/shared config.

Thoughts?

**Comment by pcsukardi** [comment]
@timwood I am going to try out some things based on what you have posted and i will get back to you with my results ASAP. As for the config split, i have not made it that far as of yet lol this is my first time working with any of these tools so i am learning on the fly but from what i _have_ read the direction you are going in with the basic/shared config seems like the correct direction. I will keep an eye out however and if i do come across any pertinent information you will be the first one to know.

**Comment by brooke-heaton** [comment]
@timwood  I am also in the process of removing any 'default' semantics from my site - it's too confusing and I want machine names that are semantically specific to each subsite. I think this is a wise call. I do have config split running but only use it for DEV vs PROD config - at the moment there's no shared config between sites. 

My big stumbling block at the moment is how to run a Travis/BLT build that includes all sites - as in 1) Run composer package installs 2) Install Drupal 4) Import config on both sites - currently I only see this happening on the 'default' site and I'm sure my config needs to be adjusted. Removing 'default' should reveal the underlying issue.

@timwood regarding config split, I've found this works pretty easily. There were two steps - defining the config directory via the UI, then placing the config subfolder in my siteroot/config directory. This is loading up correctly by BLT on config import.  I am mainly using the config_split for DEV vs PROD functionality - keeping things like stage_file_proxy out of Prod but using it locally and on STAGE/DEV environments - the use is defined conditionally based the the Acquia environment. 

I think your approach to use site named config for site-specific config is right- define this in your config_split ui on your subsite, add a corresponding folder, then keep your config array in your settings.php for all your sites to 'default' and that should bring that config into both sites. 

Currently we aren't using much common config because the sites are rather disparate.

**Comment by brooke-heaton** [comment]
@timwood My current use case for config_split for PROD vs DEV config:

```
// Use development config in dev environments.
if (!empty($_ENV['AH_SITE_ENVIRONMENT']) && $_ENV['AH_SITE_ENVIRONMENT'] == "prod") {
  $config['config_split.config_split.integrity_config_dev']['status'] = FALSE;
}
else {
  $config['config_split.config_split.integrity_config_dev']['status'] = TRUE;
}
```

I should probably use shared config at some point, but thus far haven't needed to. The sites still have unique config but eventually we may need common config.

**Comment by timwood** [comment]
@brooke-heaton  So with config/default essentially empty, did you have to modify your `drush cim` / `drush cex` commands in order for it to split everything into a site-specific folder or is config split doing that for you? Does your site-specific split contain all configuration items under "Complete split" (in the Ui)?

Where is your config_split yml file for each site-specific config stored, in config/default?

**Comment by pcsukardi** [comment]
@timwood that information about the sites.php brought me further along in my efforts, thanks man!  it was atleast far enough along to get a MySQL error which pointed me to the database **not** being created by drupalvm (ftw) so _that_ i guess is where i am looking. Did you have any trouble getting the secondary database created for your project?

**Comment by timwood** [comment]
Yes @pcsukardi. I followed this documentation to setup DrupalVM for a second database and Apache host:
http://docs.drupalvm.com/en/latest/deployment/multisite/

One annoying side-effect is that DrupalVM no longer adds the dashboard.local....hostname (and others) to /etc/hosts. Only the hosts defined in the apache_vhosts.

Here is what the relevant sections of box/config.yml looks like (I enabled apache SSL too). Also note I manually configured the servername for the secondary virtualhost(s).
```yml
apache_vhosts_ssl:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "local.manufacturingusa.test"
    documentroot: "{{ drupal_core_path }}"
    certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
    certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "local.manufacturingusa.test"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

mysql_databases:
  - name: drupal
    encoding: utf8
    collation: utf8_general_ci
  - name: drupal_two
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: drupal
    host: "%"
    password: drupal
    priv: "drupal.*:ALL"
  - name: drupal-two
    host: "%"
    password: drupal-two
    priv: "drupal_two.*:ALL"
```

In addition to this, I had to configure the Drupal database connection info in `docroot/sites/[SITENAME]/settings/local.settings.php` to use the second database.

**Comment by pcsukardi** [comment]
Thank you so much man! I figured as much and that was the approach i took but when it cam down to brass tacks it failed because it stated it could not create the database ( or access it) this made me scratch my head (because i thought i had setup a second database in `box/config.yml`) so i took the steps outlined here https://github.com/acquia/blt/issues/2710 to determine if the database was created.

**Comment by brooke-heaton** [comment]
@timwood so for my configuration - each site has its own configuration 'sync' key defined in its respective settings.php

for instance for sites/default I have this in config/default/settings.php
`$config_directories['sync'] = $dir . "/config/default";`

Of course, I plan to refactor the above to use the actual site name.

As for where the config_split yml file is - this is stored in the main configuration directory - so for the default site, I have two configuration directories but the config_split yml is in `config/default`. The other configuration directory - which is defined in the former config_split is in a directory specifically for the default sites 'DEV' config. I've called is something like `default_site_config_dev` which is defined in the config_split yaml within the config/default directory. THEN this bit if code directs drush to import config only if we are NOT in production:

```
// Use development config in dev environments.
if (!empty($_ENV['AH_SITE_ENVIRONMENT']) && $_ENV['AH_SITE_ENVIRONMENT'] == "prod") {
  $config['config_split.config_split.default+site_config_dev']['status'] = FALSE;
}
else {
  $config['config_split.config_split.default_site_config_dev']['status'] = TRUE;
}
```

**Comment by brooke-heaton** [comment]
@timwood currently the only config I have split off for DEV is devel, stage_file_proxy and shield settings. I could probably make it  more nuance per environment - adding watchdog locally or to DEV but not Stage/Prod etc. Honestly I think this config split _could_ be used for all sites on each sites respective non-Prod environment, in which case it would be shared but DEV config, if that makes sense.

**Comment by timwood** [comment]
@brooke-heaton Thanks for taking the time to explain your setup. I believe I am relying on the BLT-provided blt.settings.php to do the environment detection and configuration enabling per environment. I may look at explicitly setting the $config_directories['sync'] in each settings.php.
