### ISSUE TITLE
composer.json not sorted by default on new projects

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2696]
My system information:
* BLT version: 9.0.5

The template composer.json includes the following line to sort packages by default:
https://github.com/acquia/blt/blob/3a934d15909d776dc0f9cff8e112a383c0d958dc/template/composer.json#L5

That line is not being copied into the root composer.json for new projects for some reason.

This causes package names in composer.json to not be sorted by default.

**Comment by grasmash** [comment]
`template/composer.json` is merged in to the root `composer.json` here: https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Blt/UpdateCommand.php#L359. 

This really only merges the `extra` array: https://github.com/acquia/blt/blob/9.x/src/Robo/Common/ComposerMunge.php#L53

We'd need to modify that method to also merge some of the config array.
