### ISSUE TITLE
Running on Docksal - Super Confused about blt settings

### ISSUE THREAD

**Issue by loopy3025** [acquia/blt#2703]
My system information:
* Operating system type: Windows 
* Operating system version: 10
* BLT version: 9.0.5

Output of `blt doctor`:
```
+---------------------------+--------------------------------------------+
| Property                  | Value                                      |
+---------------------------+--------------------------------------------+
| blt-version               | 9.0.5                                      |
| composer-version          | Composer version 1.5.2 2017-09-11 16:59:25 |
| root                      | /var/www/docroot                           |
| stacks.drupal-vm.inited   | false                                      |
| stacks.dev-desktop.inited | false                                      |
| uri                       | default                                    |
+---------------------------+--------------------------------------------+
+------------------------------------------+--------------------------------------------------------------+
| Check                                    | Problem                                                      |
+------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri              | base_url in tests/behat/local.yml does not match the site    |
|                                          | URI.                                                         |
|                                          |   Behat base_url is set to                                   |
|                                          | ${project.local.uri}.                                        |
|                                          |   Drush site URI is set to default.                          |
| ConfigCheck:checkGitConfig               | Git repositories are not defined in blt.yml.                 |
|                                          |   Add values for git.remotes to blt.yml to enabled automated |
|                                          | deployment.                                                  |
| DbCheck:checkRequiredKeys                | drush status is missing the 'db-hostname' key.               |
| DrupalCheck:checkDrupalBootstrapped      | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled         | Drupal is not installed.                                     |
|                                          |                                                              |
|                                          | Run `blt drupal:install` to install Drupal locally.          |
| FileSystemCheck:checkFileSystem:%files   | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp    | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUri                     | Site URI is not set                                          |
|                                          | Is options.uri set correctly in                              |
|                                          | /var/www/docroot/sites/default/local.drush.yml?              |
+------------------------------------------+--------------------------------------------------------------+
```

When I run this command:
```
fin exec -T /var/www/vendor/bin/blt "$@" test
```

I get the following output:
```
[error]  MySql is not available. Please run `blt doctor` to diagnose the issue.
[error]  Command `tests:behat:run ` exited with code 1.
```

And I expected this to happen:
Test to run properly.

Note that my site is running fine.

![image](https://user-images.githubusercontent.com/6729935/38209671-1cd0c57c-3683-11e8-912c-542f1af66b0f.png)

I have been able to get blt to recognize that Drupal is installed on a few occasions, but it involves hard-coding the uri in several locations. I don't think this is correct. And even then, the test does not run anyways. 

I'm just super confused as to which settings are made where and what to set them as.

Here is my ./drush/drush.yml
![image](https://user-images.githubusercontent.com/6729935/38209737-4cc53dee-3683-11e8-8174-6c68b37b3605.png)

Here is my ./drush/sites/local.site/yml
![image](https://user-images.githubusercontent.com/6729935/38209776-6b3915de-3683-11e8-91b2-eb57d4c85beb.png)

Here is my ./docroot/sites/default/local.drush.yml 
![image](https://user-images.githubusercontent.com/6729935/38209915-cd27ceac-3683-11e8-927e-50f77fd3fb87.png)

There's just a lot of arrows pointing in a lot of different directions and I'm not really sure whether I'm getting everything concatinating correctly.

**Comment by loopy3025** [comment]
So, when I try to run blt drupal:install, I get this... 

![image](https://user-images.githubusercontent.com/6729935/38259519-3ccfe654-3733-11e8-809e-88f88901f2c4.png)

Is there something I'm doing wrong with these aliases?

**Comment by loopy3025** [comment]
Here's my blt.yml file:

![image](https://user-images.githubusercontent.com/6729935/38259607-7688f3c2-3733-11e8-95b5-e82e4a6a1953.png)

And my local.blt.yml

![image](https://user-images.githubusercontent.com/6729935/38259642-8940d6d8-3733-11e8-9d01-2422a77ff3e6.png)

I'm trying to follow the documentation, but it doesn't seem to be indicating what to put for these settings.

**Comment by loopy3025** [comment]
Oddly, the site is still running fine when I go to it in the browser. I feel like it should be exploding right now, but it isn't.

**Comment by grasmash** [comment]
I can't provide in depth Docksal support, but it sounds like your experiencing the same issues that were discussed in https://github.com/acquia/blt/issues/2627.

> Something to keep in mind when running commands inside your project directory - you need to make sure you're running the commands through the Docksal CLI service. What does that mean? If you're in your project directory in a terminal on your machine, and you find yourself running blt doctor, that command is being executed on your host system (i.e. not Docksal). You need to make sure you're running that command through Docksal. That means you need to prepend it with fin exec. So fin exec blt doctor would be the proper command issued in your terminal to run blt through Docksal rather than your host system.

I'd suggest mimicing the settings and commands specified in https://github.com/acquia/blt/issues/2627.

**Comment by loopy3025** [comment]
I am definitely executing my commands using the fin exec preamble.
