### ISSUE TITLE
Updated BLT throwing error MySql is not available. Please run `blt doctor` to diagnose the issue.

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#2709]
I have an existing project & upgraded BLT from 8.9.10 to 9.0.5, Drupal core from 8.2.8 to 8.5.1, Acquia lightning from 2.1 to 3.1.1 & Drush 8.1.10 to 9.2.2, also I have Travis integration.

My system information:
* Operating system type: MacOs High Sierra
* Operating system version: 10.13.4
* BLT version: 9.0.5

Output of `blt doctor`:

<img width="735" alt="screen shot 2018-04-03 at 7 04 38 pm" src="https://user-images.githubusercontent.com/6311767/38252494-ef78271a-3771-11e8-843e-003a17ecb051.png">

**Travis build is failing & I get the following output:**
> source:build:frontend
> source:build:frontend-reqs
[info] Skipped frontend-reqs target hook. No hook is defined.
> source:build:frontend-assets
[info] Skipped frontend-assets target hook. No hook is defined.
[info] Skipped post-setup-build target hook. No hook is defined.
> drupal:hash-salt:init
Hash salt already exists.
> drupal:install
[error]  MySql is not available. Please run `blt doctor` to diagnose the issue. 
[error]  Command `drupal:install ` exited with code 1. 
2.154s total time elapsed.
blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --environment=ci --yes --verbose
> tests:behat:run
**[error]  MySql is not available. Please run `blt doctor` to diagnose the issue. 
[error]  Command `tests:behat:run ` exited with code 1.** 
0.373s total time elapsed.

I have re-generated drush aliases as per drush 9 standards by running `drush site:alias-convert` Please help me with the next steps.

**Comment by mikemadison13** [comment]
@sandipsmarty did you rebuild your VM after updating to BLT 9.x? It is highly recommended to do a blt vm:nuke then re-run blt vm after. You may need to tweak some of the box/config.yml values before provisioning the VM (make sure PHP version matches, keep the same IP address, etc.). 

I've run into similar issues during this upgrade and a reprovisioned VM is always a good first step.

Another issue is that BLT 9 assumes all commands are running inside the VM  (NOT outside). So this will require a vagrant ssh prior to running the blt commands, and it will require tweaking some of your default aliases in your blt.yml (previously project.yml) to be "self" instead of "<project>.local"

**Comment by sandipsmarty** [comment]
@mikemadison13: After updating to BLT 9.x I ran the following comands
`blt recipes:drupalvm:destroy && blt recipes:drupalvm:init`. Also tried `blt vm:nuke` & then `blt vm` after that. I modified box/config.yml to match things as per my previous version. Also I am running BLT commands from inside VM.

**Comment by mikemadison13** [comment]
did you try running a ```drush cc drush``` to make sure the new aliases are loaded properly?

**Comment by sandipsmarty** [comment]
Things are better now, blt doctor showing only 1 problem.

Check                                                               |                        Problem                                                   
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root

But VM dashboard not working with domain, it's working with ip, also local site url is not working. It's showing site can not be reached.

**Comment by mikemadison13** [comment]
@sandipsmarty i'm wondering, when you reprovisioned did you bring it back up with the same IP address as before? if not, you might check /etc/hosts and make sure you don't have duplicate IP addresses in the hosts file.

**Comment by sandipsmarty** [comment]
@mikemadison13: Thanks for pointing out that. Ya duplicate host entries were there in etc/hosts file & I've removed those. Now dashboard is loading fine, but seems the site is not installed, DB created for all multisites but db dump (not even for default site) isn't imported from acquia cloud dev environment. 

Not sure what else I have to change for the drush aliases as per BLT 9 & Drush 9 standards. I already converted my previous existing drush aliases by running `drush site:alias-convert`.

Following are the output of my `blt sync:refresh` & `blt doctor`.

<img width="1298" alt="screen shot 2018-04-04 at 12 53 44 pm" src="https://user-images.githubusercontent.com/6311767/38294464-8c658806-3808-11e8-8aeb-63929274df3d.png">
<img width="767" alt="screen shot 2018-04-04 at 12 54 38 pm" src="https://user-images.githubusercontent.com/6311767/38294482-995cef36-3808-11e8-960f-11eba6c48d91.png">

**Comment by mikemadison13** [comment]
@sandipsmarty have a look at https://github.com/acquia/blt/issues/2677, I know that they were having similar multi-site related issues with BLT 9. there might be something there that is useful for you?

**Comment by malikkotob** [comment]
@sandipsmarty may you please send the contents of your alias file for the environment it's failing to sync with?

**Comment by grasmash** [comment]
@sandipsmarty Is this still an issue?

**Comment by sandipsmarty** [comment]
@malikkotob : Sorry for late response. I was not available last couple of weeks. Here are the content of my alias file (icfolsonsites.site.yml). 

dev:
    host: <hostname>
    options: { ac-env: dev, ac-realm: devcloud, ac-site: icfolsonsites }
    paths: { drush-script: drush9 }
    root: /var/www/html/icfolsonsites.dev/docroot
    uri:  <uri>
    user: icfolsonsites.dev
local:
    host: icfolson.local
    options: {  }
    root: /var/www/icfolson/docroot
    uri: 'http://icfolson.local'
    user: vagrant
    ssh: { options: '-o PasswordAuthentication=no -i $HOME/.vagrant.d/insecure_private_key' }
test:
    host: <hostname>
    options: { ac-env: test, ac-realm: devcloud, ac-site: icfolsonsites }
    paths: { drush-script: drush9 }
    root: /var/www/html/icfolsonsites.test/docroot
    uri: <uri>
    user: icfolsonsites.test
prod:
    host: <hostname>
    options: { ac-env: prod, ac-realm: devcloud, ac-site: icfolsonsites }
    paths: { drush-script: drush9 }
    root: /var/www/html/icfolsonsites.test/docroot
    uri: <uri>
    user: icfolsonsites.prod

and in my blt.yml file the drush alias part defined as below.

drush:
  aliases:
    remote: icfolsonsites.dev
    local: icfolsonsites.local
    ci: self
  default_alias: self

**Comment by sandipsmarty** [comment]
@grasmash : I am still having the same issue, **mysql not available**.

**Comment by sandipsmarty** [comment]
Closing this issue, I was able to resolve it by downgrading BLT to 8.9.14 & made changes in drush aliases & in .travis.yml file.

**Comment by sodacrackers** [comment]
I seeing `blt doctor` can not connect to MySQL after upgrading BLT. I'm running "acquia/blt": "^9.1.0" "acquia/lightning": "~3.1.7" and Drush Commandline Tool 9.4.0. 

Perhaps related, I see status messages using aliases in the project but, when on the VM, `Warning: Identity file /home/vagrant/.vagrant.d/insecure_private_key not accessible: No such file or directory.
Permission denied (publickey,password).`
