### ISSUE TITLE
Behat configuration "bootstrap" setting

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#2711]
https://github.com/acquia/blt/blob/9.x/template/tests/behat/example.local.yml#L13

I am wondering if this line in the behat configuration file is known to _do something_ or if maybe this is a legacy thing that was left behind for something else...?
I know I tried removing it in my project (to see what breaks) and BLT is specifically checking for this key, but it appears I can successfully run BEHAT in the same manner without this line. Just wanted to ask if anyone knew if this was used for something, and if not, we may want to consider 86'ing this guy...

**Comment by grasmash** [comment]
I think it's just re-stating the default value, so it's not actually necessary.

**Comment by dpagini** [comment]
I couldn't even figure out, even from the documentation, what it was doing... if I put a context class in that folder, I was expecting it to get picked up automatically, but it seemed I still had to explicitly reference the class in the "extensions". 

I'll take a crack at this one when I have a few minutes... if you want to leave as is, that's fine by me too. I was more just hoping to confirm my own suspicion that this was a bit superfluous.

**Comment by grasmash** [comment]
I'm going to leave as-is and close this issue as there are no negative effects. I'd be happy to review a PR if you submit it.
