### ISSUE TITLE
Automated deployment updates not supported on ACSF

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2725]
My system information:
* BLT version: 9.0.5

Currently BLT 9 won't run automated updates (db updates, config imports) on ACSF deploys.

BLT's ACSF update hooks try to get a list of available ACSF sites for updates by calling https://github.com/acquia/acsf-tools, which doesn't work for Drush 9. There's even a todo in this file basically saying "make it work".

One solution is to get ACSF tools to work with Drush 9. This was requested in January: https://github.com/acquia/acsf-tools/issues/9

Another solution is to dump ACSF tools. It looks like there are two completely parallel update paths in BLT: `artifact:update:drupal:all-sites` vs `artifact:ac-hooks:*` That seems redundant, and only one of them relies on ACSF Tools, the other relies on the multisites array. So maybe this could be worked around by consolidating those hooks and avoiding ACSF tools altogether.

**Comment by danepowell** [comment]
I'm updating the title to reflect that this also affects the ability to install new sites (since updates need to run after the site is installed in order to import configuration). Not sure if the fix will be the same.

**Comment by grasmash** [comment]
Resolved by https://github.com/acquia/blt/pull/2787
