### ISSUE TITLE
documentation/guidance needed when running `blt recipes:aliases:init:acquia`

### ISSUE THREAD

**Issue by ba66e77** [acquia/blt#2727]
My system information:
* BLT version: 9.0.5

When I run this command:
```
blt recipes:aliases:init:acquia
```

I get the following output:
```
Please enter your Acquia Cloud application ID
```

And I expected this to happen:

Some guidance/documentation of where to find the Acquia Cloud application ID.  When logged in to Acquia Cloud, you find the application ID by going to Develop > Applications, and selecting one of your subscriptions.  Then the application ID is a UUID in the resulting URL, like: 'https://cloud.acquia.com/app/develop/applications/12xxxxfc-1xx3-a0c4-4df5-42xxxxxxx5e'. But it took some blind clicking around and guess work to determine that

**Comment by malikkotob** [comment]
The Acquia docs team is going to add official documentation to define the application ID and where to find it. Once that is done, we can update BLT documentation to point to the appropriate Acquia docs. The doc issue is 16967.
