### ISSUE TITLE
Support Drush 8 and Drush 9

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#2731]
This issue addresses various use cases and challenges faced by Drush 9 users who are encountering modules, themes, and Acquia products that do not yet support Drush 9.

I'm closing the following issues in favor of this more inclusive master issue.

- https://github.com/acquia/blt/issues/2729
- https://github.com/acquia/blt/issues/2708
- https://github.com/acquia/blt/issues/2717

Related resources:

- https://github.com/acquia/blt/wiki/Using-BLT-9-on-ACSF
- https://docs.acquia.com/site-factory/known-issues
- [Drush compatibility matrix](http://docs.drush.org/en/master/install/#drupal-compatibility). Drush 8 is not supported for Drupal 8.4+.

**Comment by lcatlett** [comment]
Proposed implementation:
[] - Install composer bin plugin and configure separate drush8 and drush9 binary executables
[] - Add drush cli aliases to override Acquia Cloud defaults
[] - Override local drush 9 redispatch in favor of vendor-bin
[] - Remove existing Drush 9 acsf-init workaround
[] - Add drush8 compatible drushrc.php to BLT9 project template
[] - Convert Acquia Cloud default Drush 8 aliases to drush 9 as part of deploy step

**Comment by grasmash** [comment]
ACSF is now compatible with Drush 9. I believe this issue is resolved? 

If you need both Drush 8 and Drush 9, I'd suggest installing Drush 8 on the system in a global location, or else using bamarni/composer-bin-plugin to install it to `drush8`.
