### ISSUE TITLE
Documentation around the blt.yml file

### ISSUE THREAD

**Issue by MichaelMallett** [acquia/blt#2765]
My system information:
* Operating system type: OSX
* Operating system version: 10.13.13
* BLT version: 9.0.5

I'm struggling to figure out best practices around BLT, particularly with setting up the blt.yml file with the correct variables in an existing site. It would be helpful to know what the available configuration variables are and what they do...I've managed to figure a couple of them out almost by trial and error, but it's a very slow process. There seems to be a lot of functionality that's available in here, but without knowing the project inside out it seems hard to expose it. Some kind of reference or example blt.yml, and how to make use of those variables would be very useful!

**Comment by pcsukardi** [comment]
Hey MichaelMallett,
Which `blt.yml` file is this? the site specific `blt.yml` or the main project `blt/blt.yml` in the root of the project?

**Comment by MichaelMallett** [comment]
Hi pcsukardi. Is the main project blt.yml not site specific? I had assumed it was, and was committed into the project, and blt.local.yml was used to override settings for developers.

**Comment by MichaelMallett** [comment]
Decided to park using BLT. Came up against far too many issues over the last 2 weeks to make it worthwhile.

**Comment by joachim-n** [comment]
Could this be reopened please? It's still relevant, at least on BLT 9.1.3.

For example:

1.

In docs/configuration-management.md it says:

> To set up a Features-based workflow, you'll need to set `cm.strategy` to `features` in `blt/blt.yml`.

However, template/blt/blt.yml doesn't have an entry showing this config item.

1.

src/Robo/Commands/Setup/ConfigCommand.php has:

```
    $cm_core_key = $this->getConfigValue('cm.core.key');
```

but again, that's not in the default blt.yml file.

**Comment by loopy3025** [comment]
Yeah. The documentation on what the settings in blt.yml are currently not entirely helpful. I have found that there are way more settings that are possible through this file than are indicated in the documentation. I often have to go hunting for example blt.yml files and copy whatever's going on in there (or, worse, extrapolate how to do what I need based on what's in there).
