### ISSUE TITLE
Request: Update PHPUnit library

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#2771]
The PHPUnit package is specified to version `^4.8`, but this is a very old version of PHPUnit. Per their [main site](https://phpunit.de/), **PHPUnit 5** was just sunsetted (support) a few months back.

I know there was a bunch discussion on this project about supporting PHP 5.6, but as these tools keep moving forward, it seems like this is going to continue being a topic of discussion. There is no longer a supported version of PHPUnit that supports PHP 5.6 or older.

I haven't tried this, but can we maybe allow for different versions of PHPUnit in composer with something like `"^4.8|^5.0|^6.0|^7.0"`? I assume that all depends on this projects' usage of PHPUnit. From what I'm reading, versions 5 & 6 shouldn't be too bad or present big problems, but maybe we can't include 7 in here.

For consideration... https://www.drupal.org/project/drupal/issues/2932606
This patch just went into 8.6.x, so as soon as 8.6 comes out in 4+ months, we'll no longer be able to run the simpletest tests in a BLT project, b/c BLT will stop us from upgrading to PHPUnit 6, but core testing won't run on PHP > 7 with anything lower than PHPUnit 6.

**Comment by nikolamitevffw** [comment]
At the current configuration the required version of PHPUnit higher than 4.8 required host machine to have PHP version from 5.4 to 5.6. But the PHPUnit requires Symfony debug v4.1 package which needs PHP version higher than 7.1.
And this prevents users to install the BLT package as they are unable to install the required PHPUnit packages. As it is suggested in the first comment setting required version for PHPUnit to  "^4.8|^5.0|^6.0|^7.0" could resolve the problem.

**Comment by nbertram** [comment]
FWIW, core/composer.json says: "phpunit/phpunit": "^4.8.35 || ^6.1",

There's special handling for this scenario in core/scripts/run_tests.sh to tell people to switch versions if they're running on 7.2+ (it actually refuses to run any tests on PHP 7.2 with PHPUnit 4)

**Comment by seanhamlin** [comment]
PR raised, I propose we use the same as what Drupal core 8.6 will be releasing very shortly.
