### ISSUE TITLE
blt setup issue

### ISSUE THREAD

**Issue by justincletus** [acquia/blt#2776]
blt local:setup no command found in blt list
if I run blt setup I am geeting this error @geerlingguy any idea 
[warning] BLT will NOT import configuration, /var/www/njpadev2/docroot/../config/default/core.extension.yml was not found.

how to fix this

**Comment by grasmash** [comment]
Please post the information requested in the issue template.

My system information:
* Operating system type: [replace]
* Operating system version: [replace]
* BLT version: [replace]

Output of `blt doctor`:
```

```

When I run this command:
```
[replace with command, add -vvv for very very verbose output.]
```

I get the following output:
```
[replace with ENTIRE command output. DO NOT enter partial output.]
```

And I expected this to happen:

**Comment by ba66e77** [comment]
There've been nearly two months with no further discussion here. Please reopen if it's still an issue.
