### ISSUE TITLE
blt sync:refresh issue

### ISSUE THREAD

**Issue by justincletus** [acquia/blt#2784]
My system information:
* Operating system type: Ubuntu
* Operating system version: 16.02
* BLT version: 9.0.5

Output of `blt doctor`:
```
 Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.
```

When I run this command:
```
[replace with command, add -vvv for very very verbose output.]
```

I get the following output:
```
[replace with ENTIRE command output. DO NOT enter partial output.]
```

And I expected this to happen:

 [error]  Error: no alias record could be found for source @bltdev.test 
[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 1.296s
[error]   
[error]  Command `drupal:sync:db ` exited with code 1.

how to fix this error. any help please

**Comment by grasmash** [comment]
Please fill out the entire issue template. Specifically:

We need to see the exact command that you ran with all of the command output.

At a glance, I would guess that you have `drush.aliases.remote` set to `bltdev.test`, but that is not a real drush alias. Replace it with a real, working drush alias pointing to the environment from which you would like to sync.

**Comment by ba66e77** [comment]
We're pushing two months with no update on this, so I'm going to close it. If this is still and issue, feel free to reopen.
