### ISSUE TITLE
Minimum Composer version

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2789]
Lately we've seen a few user reports of BLT project creation failing because Drupal Scaffold isn't running, so things like `docroot/index.php` aren't getting created.

The root cause seems to be older Composer versions (including 1.1.3 and 1.3.2) that apparently don't work with Drupal Scaffold: https://github.com/drupal-composer/drupal-scaffold/issues/72

We should at least document the minimum required Composer version (I'm not exactly sure what that is, but maybe just recommend the latest), and if possible do some sort of code-level check for the correct Composer version when creating projects.

**Comment by grasmash** [comment]
I think this is something that needs to be addressed in drupal-composer/drupal-scaffold#72 rather than in BLT. Also, it's not possible for a package to require a minimum version of Composer.
