### ISSUE TITLE
Consolidate required user interaction

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2792]
My system information:
* BLT version: 9.0.5

I often start a `blt setup` process and then leave to grab some coffee, since it takes several minutes to install and import a full db or configuration set, only to return to find that the process has hardly even kicked off, and is waiting for user input, such as:

> [warning] The active configuration is not identical to the configuration in the export directory.
[warning] This means that you have not exported all of your active configuration.
[warning] Run drush cex to export the active config to the sync directory.
[warning] Continuing will overwrite the active configuration.
 Continue? (y/n) y

... or

>  You are about to DROP all tables in your 'drupal' database. Do you want to continue? (yes/no) [yes]:

Good UX patterns dictate that when user interaction is required during a long-running process, all necessary user input should be gathered at once at the start of the process, rather than scattered throughout.

We should examine whether user input is really necessary in these cases, and if so, try to gather it all at once at the start of the setup process.

**Comment by grasmash** [comment]
Also, some of these prompt aren't even from BLT, they're from Drush. I'd argue that this is the purpose of  the `-y` or `--no-interaction` options, and this shouldn't be a high priority.
