### ISSUE TITLE
DB updates fail on ACSF, breaking deploys

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2794]
My system information:
* Operating system type: 9.x-dev

When I deploy my BLT-based project to ACSF via the management console and select the option to apply db updates as part of the deploy, the deployments always fail. The task log for each SiteUpdate task contains an error like this:
> The db-update.sh script has encountered an error... Running updates for site foo in environment 01dev.> artifact:update:drupal... The specified database connection is not defined: default

Clearly BLT _should_ be targeting the specific site specific by the `$domain` provided in the db-update hook, not `default`.

I think what's happening here is that this call to switchSiteContext() is clobbering the domain passed via the CLI: https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Artifact/FactoryHooksCommand.php#L41

**Comment by lcatlett** [comment]
This appears to be related to https://github.com/drush-ops/drush/issues/2285 so is currently blocking all ACSF and ACE multisite deploys using drush 9.2.1 or newer.  I am not clear yet on what the best path forward might be

**Comment by danepowell** [comment]
Although the error message is the same, that issue doesn't make sense to me as a root cause, because BLT isn't passing a domain or alias to Drush in the first place, so it makes sense that it would try to act on the default site.  It also doesn't explain why my PR totally unrelated to Drush would fix it.

**Comment by danepowell** [comment]
Detailed steps to reproduce this bug:

1. Start with a fairly recent BLT 9-based project where you've run `recipes:acsf:init:all`. Specifically, ensure that the factory-hooks directory exists and contains db-update.sh.
2. Use Pipelines or `blt deploy` to build the artifact and push the codebase to a branch on Acquia Cloud.
3. Log in to your ACSF management console.
4. Navigate to the "Update code" page in the administration section.
5. Select the branch you just push for deployment, and *make sure to check the box to run db updates*.
6. Click the button to deploy the code and confirm if necessary.

*Expected behavior:*
Code deploys successfully.

*Actual behavior*
Code deployment fails with the following error in the SiteUpdate task log:
> The db-update.sh script has encountered an error... Running updates for site foo in environment 01dev.> artifact:update:drupal... The specified database connection is not defined: default
