### ISSUE TITLE
Work-around added in #813/#1151 need to be reverted, because Drupal core fixed it, solutions will conflict

### ISSUE THREAD

**Issue by wimleers** [acquia/blt#2801]
#1151 fixed #813. This ensured Twig caches were invalidated across multiple web heads.

https://www.drupal.org/project/drupal/issues/2752961 landed today, in Drupal 8.6. It _may_ be cherry-picked to 8.5.

The work-around that #1151 added includes an earlier iteration of the patch in https://www.drupal.org/project/drupal/issues/2752961. The solution it settled on is different. So #1151 will fail against Drupal 8.6. But if the core patch ends up getting cherry-picked into Drupal 8.5, then BLT will start failing sooner!

It's probably best to start working on this ASAP to prevent stressful chaos later on.

**Comment by wimleers** [comment]
Paging @danepowell and @grasmash.

**Comment by danepowell** [comment]
I haven't had time to dig into this, but I just want to note that the deployment id isn't only used for remote deployments, it's also for local developers to prevent stale cached classes / services from causing problems when you update contrib modules. I'm not sure if the new core patch addresses that use case.

I discuss this specific use case in one of those issues you linked to I think, I'll try to find a reference to it.

**Comment by danepowell** [comment]
Here we go: https://github.com/acquia/blt/issues/1568

**Comment by ba66e77** [comment]
Appears this issue was resolved by the commit referenced above. If that's not the case, please reopen.
