### ISSUE TITLE
blt command breaks when bin-dir is changed from ./vendor/bin

### ISSUE THREAD

**Issue by gheydon** [acquia/blt#2805]
My system information:
* Operating system type: MacOS
* Operating system version: 10.13.4 (17E202)
* BLT version: BLT 9.0.5

When I change the composer.json to include the following in the config
```
"config": {
  "bin-dir": "bin/",
}
```

Output of `blt doctor`:
```
Warning: require_once(/vendor/autoload.php): failed to open stream: No such file or directory in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php on line 8

Fatal error: require_once(): Failed opening required '/vendor/autoload.php' (include_path='.:') in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php on line 8
```

When I run this command:
```
bin/blt -vvv
```

I get the following output:
```
Warning: require_once(/vendor/autoload.php): failed to open stream: No such file or directory in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php on line 8

Fatal error: require_once(): Failed opening required '/vendor/autoload.php' (include_path='.:') in /Users/gordon/Source/Client/Loud-And-Clear/vocus/vcms/vendor/acquia/blt/bin/blt-robo.php on line 8
```

**Comment by mikemadison13** [comment]
did you re-run a composer update after changing the bin-dir? 

also did you update your .bash_profile to point at the new bin directory so that the BLT linkages continue to work from the new location?

**Comment by gheydon** [comment]
Yes I re-ran the composer update.

At that stage I was not using the blt() but instead just calling the blt script direct ```./bin/blt``` and I was getting the issue.

I was checking further and the problem is in find_repo_root() in blt_robo.php which is searching for the root by looking for vendor/bin/blt and vendor/autoload.php to which vender/bin/blt is not there so it never finds it.

1 possible solution is to instead of searching for vendor/bin/blt is to search for vendor/acquia/blt/bin/blt and even in the blt() to also look there as well.

**Comment by mikemadison13** [comment]
@gheydon we could certainly add an enhancement for this, although i'm curious about the use case for why you might want to change the default bin directory? it seems like most of our users aren't running into this particular case (or at least it hasn't come up already) so I'd like to understand your situation a little better.

**Comment by gheydon** [comment]
Basically I always move the bin directory to the root of the repository so that it is more accessible. makes it much easier to execute commands where you can just go ./bin/xxx and you are there,

**Comment by mikemadison13** [comment]
i'm going to mark this as a potential enhancement for a future release of BLT.

**Comment by danepowell** [comment]
@gheydon moving the bin directory is not currently a supported use-case. If there was more demand, or if you can provide a PR that implements it in a way that won't impact existing users or increase maintenance overhead, then we'd be happy to reconsider.
