### ISSUE TITLE
BLT 9.0 upgrade feedback

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#2813]
I just finished upgrading my project onto BLT `9.0.5`. I saw two pain points (1 question) that I wanted to just report back if anyone is interested....

The first is that `project.local.yml`, previously the BLT local config, gets un-gitignored as part of the update, and leaves a rogue file on all our developers local environment that they need to delete manually. In addition, it would have been awesome if anyone's local settings would have been copied over to the new `local.blt.yml` file. Maybe that's a bit harder b/c there is no script running on each devs computer as part of the upgrade, but it was a small "bad DX" thing...

The second is the aliases files. It seems the upgrade copied all of the existing `*.aliases.php` from `drush/site-aliases` into `drush/sites` in addition to creating me converted Drush 9 YML files. The old files however were kept. I had some confusion around... _are these old aliases files still needed?_ Are they just moved there as a legacy thing? Is there any D8 support that still needs them there? Should I delete these files?
Maybe there was some instruction around that after the conversion happened... but I was left a little confused by this process.

Anyways, thanks for all the work on this, and feel free to close this issue if none of the feedback can be (or should be) addressed...

**Comment by mikemadison13** [comment]
re the first item, we can certainly dig into that and see if we can rename the file or at least delete it.

i'm not sure of the best practice re: the alias files, but i have noticed this as well. agreed that some documentation that explains what to do here would be useful (I also tend to rewrite all the drush alias yml files after they get generated into a slightly different format as well)

**Comment by dpagini** [comment]
Yeah, I had to basically throw away what drush generated for me.... oh well, I figured it was just my project though.
Thanks @mikemadison13!

**Comment by dpagini** [comment]
Going to go ahead and close this since it's a bit outdated at this point, and there's probably no reason to go back and address if it hasn't been done yet.
