### ISSUE TITLE
BLT 9 : Where's my public key

### ISSUE THREAD

**Issue by cosmicdreams** [acquia/blt#2822]
Now the BLT 9 operations are supposed to be run from within the VM, I have run into an artificial barrier from executing my commands and getting to productive state:  

All Acquia API requiring commands need a different SSH key than the one I've already provided.

I think what I need to do is to find the public SSH key from within my VM to proceed but I can't seem to find good documentation on the internet about where to find it.  

Can you point me in the right direction?

**Comment by mikemadison13** [comment]
@cosmicdreams the VM should automatically forward in all of the certificates from your host machine. @geerlingguy do you have any docs on this or advice on the DrupalVM side?

**Comment by geerlingguy** [comment]
@cosmicdreams the best way is to use `ssh-agent`, which is set up already with Drupal VM to forward keys into the VM when you use `vagrant ssh`. That way any keys you have in your Agent on your workstation will also be available when you do things inside the VM.

To use it:

  1. `ssh-add -i path/to/your/public-key.pub` (or just `ssh-add` to add your default key, e.g. `~/.ssh/id_rsa.pub`).
  2. `vagrant ssh`

Then it should be present in the VM. You can check what keys are available with `ssh-add -l`.

**Comment by mikemadison13** [comment]
@cosmicdreams do you have any updates here? did Jeff's suggestion take care of your issue?

**Comment by cosmicdreams** [comment]
@mikemadison13 @geerlingguy that didn't work out.  The only thing that worked was to create an ssh key from within the VM and then add that key to my Acquia account.

**Comment by ba66e77** [comment]
Since it looks like you have a viable workaround, I'm closing this issue out for now.
