### ISSUE TITLE
blt recipes:aliases:init:acquia fails

### ISSUE THREAD

**Issue by bkildow** [acquia/blt#2826]
My system information:
* Operating system type: OSX
* Operating system version: 10.11
* BLT version: 9.1.0

When I run this command:
```
blt recipes:aliases:init:acquia
```

I get the following output:
```
PHP Catchable fatal error:  Argument 1 passed to AcquiaCloudApi\CloudApi\Connector::request() must be an instance of AcquiaCloudApi\CloudApi\string, string given, called in [scrubbed]/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Client.php on line 102 and defined in [scrubbed]/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php on line 61

Catchable fatal error: Argument 1 passed to AcquiaCloudApi\CloudApi\Connector::request() must be an instance of AcquiaCloudApi\CloudApi\string, string given, called in [scrubbed]/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Client.php on line 102 and defined in [scrubbed]/vendor/typhonius/acquia-php-sdk-v2/src/CloudApi/Connector.php on line 61
```

**Comment by mikemadison13** [comment]
Hi @bkildow I just tested this using the most current 9.x-dev and after grabbing a valid UUID from the Acquia Cloud and generating a new key/secret combo, this worked fine for me (although I did get a different warning from vendor/typhonius/acquia-php-sdk-v2. 

i saw several instances of:

```
Notice: Undefined property: stdClass::$insight in vendor/typhonius/acquia-php-sdk-v2/src/Response/EnvironmentResponse.php on line 44
PHP Notice:  Undefined property: stdClass::$insight in vendor/typhonius/acquia-php-sdk-v2/src/Response/EnvironmentResponse.php on line 44
```

could you possible do the following?

```
$ composer show typhonius/acquia-php-sdk-v2
```

I am running version 1.0.2.

**Comment by bkildow** [comment]
After rebuilding some things, I was able to get it working, running the same version as you. I also noticed the PHP notices as well, but everything seemed to work correctly. Thanks!

**Comment by mikemadison13** [comment]
most welcome!
