### ISSUE TITLE
DrupalVM installs PHP 5.6 which is not compatible with some composer dependencies

### ISSUE THREAD

**Issue by sarahjean** [acquia/blt#2830]
My system information:
* Operating system type: OSX
* Operating system version: OSX High Sierra 10.13.4
* BLT version: latest 8 and 9

Output of `blt doctor`:
```
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/new/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/new/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50
```

When I run this command:
```
vagrant@local:/var/www/new$ blt setup
```

I get the following output:
```
vagrant@local:/var/www/new$ blt doctor
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/new/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /var/www/new/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50
```

And I expected this to happen:
Setup tasks to be run

------
Updating the vm to PHP 7.1  fixes the issue

**Comment by sarahjean** [comment]
This blt instance was created with this command `composer create-project acquia/blt-project:9.x-dev --no-interaction new`

**Comment by mikemadison13** [comment]
@sarahjean this is actually likely happening because of a composer issue where the host machine and VM are not running the same version of PHP.

the solution here is to add the following snippet to the composer file:

```
"config": {
      "platform": {
        "php": "5.6"
      }
    },
```

The VM should default to PHP 7.1 in BLT 9.x already, we don't necessarily need to do this for 8.x if the above step is followed.

Thoughts?

**Comment by sarahjean** [comment]
Well, if we are going to default to 5.6, would it make sense to include that configuration out of the box?

I do think we should default to 7.1, but that is a slightly different issue.
