### ISSUE TITLE
Travis-ci deleting split config files in build branch

### ISSUE THREAD

**Issue by justclint** [acquia/blt#2853]
My system information:
* Operating system type: osx
* Operating system version: 10.13.4
* BLT version: [replace]

Output of `blt doctor`:
```
+---------------------------+--------------------------------------------------------+
| Property                  | Value                                                  |
+---------------------------+--------------------------------------------------------+
| %paths.%root              | /var/www/*redacted*/docroot                               |
| %paths.%site              | sites/default                                          |
| %paths.%modules           | sites/all/modules                                      |
| %paths.%themes            | sites/all/themes                                       |
| %paths.%config-sync       | /var/www/*redacted*/config/default                        |
| %paths.%files             | sites/default/files                                    |
| %paths.%temp              | /tmp                                                   |
| %paths.%private           | /var/www/*redacted*/files-private                         |
| admin-theme               | seven                                                  |
| alias-searchpaths.0       | /var/www/*redacted*/drush/sites                           |
| blt-version               | 9.0.5                                                  |
| bootstrap                 | Successful                                             |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17             |
| config-sync               | /var/www/*redacted*/config/default                        |
| db-driver                 | mysql                                                  |
| db-hostname               | localhost                                              |
| db-name                   | drupal                                                 |
| db-password               | drupal                                                 |
| db-port                   | 3306                                                   |
| db-status                 | Connected                                              |
| db-username               | drupal                                                 |
| drupal-settings-file      | sites/default/settings.php                             |
| drupal-version            | 8.5.3                                                  |
| drush-alias-files.0       | /var/www/*redacted*/drush/sites/example.acsf.site.yml     |
| drush-alias-files.1       | /var/www/*redacted*/drush/sites/example.local.site.yml    |
| drush-alias-files.2       | /var/www/*redacted*/drush/sites/legacy.site.yml           |
| drush-alias-files.3       | /var/www/*redacted*/drush/sites/*redacted*-dev.site.yml      |
| drush-alias-files.4       | /var/www/*redacted*/drush/sites/*redacted*-prod.site.yml     |
| drush-alias-files.5       | /var/www/*redacted*/drush/sites/*redacted*-qa.site.yml       |
| drush-alias-files.6       | /var/www/*redacted*/drush/sites/*redacted*-ra.site.yml       |
| drush-alias-files.7       | /var/www/*redacted*/drush/sites/*redacted*-test.site.yml     |
| drush-alias-files.8       | /var/www/*redacted*/drush/sites/*redacted*.site.yml          |
| drush-conf.0              | /var/www/*redacted*/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/*redacted*/drush/drush.yml                       |
| drush-conf.2              | /var/www/*redacted*/docroot/drush                         |
| drush-conf.3              | /var/www/*redacted*/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/*redacted*/vendor/bin/drush                      |
| drush-temp                | /tmp                                                   |
| drush-version             | 9.2.3                                                  |
| files                     | sites/default/files                                    |
| install-profile           | lightning                                              |
| modules                   | sites/all/modules                                      |
| php-bin                   | /usr/bin/php7.1                                        |
| php-conf.0                | /etc/php/7.1/cli/php.ini                               |
| php-os                    | Linux                                                  |
| private                   | /var/www/*redacted*/files-private                         |
| root                      | /var/www/*redacted*/docroot                               |
| site                      | sites/default                                          |
| stacks.drupal-vm.inited   | true                                                   |
| stacks.dev-desktop.inited | false                                                  |
| temp                      | /tmp                                                   |
| theme                     | bootstrap_padi                                         |
| themes                    | sites/all/themes                                       |
| uri                       | http://local.*redacted*.com                               |
+---------------------------+--------------------------------------------------------+
+--------------------------------------+--------------------+
| Check                                | Problem            |
+--------------------------------------+--------------------+
| NodeCheck:checkNodeVersionFileExists | .nvmrc file exists |
+--------------------------------------+--------------------+
```

When travis-ci builds artifacts:

All of our split config files are being deleted except for the default config. For example, we have split config folders for local, dev, stage, prod and default. Ive ssh'd into our Acquia servers and the config folders for local, dev, stage and prod are completely wiped out except for the .htaccess file.

This is something we just noticed but I suspect this may of started after we did the last big update to lightning 3 and BLT 9. 

And I expected this to happen:
When travis builds the artifacts I would expect it to retain the split config files in the build branch.

If theres any additional info I can provide that may be helpful, please let me know.

Thanks!

**Comment by ba66e77** [comment]
The same does not happen locally when you run `blt deploy:build`, correct?

**Comment by ba66e77** [comment]
Well, that's unexpected. Is there any chance the branch you're building from through Travis is different from the one you're building from when you do the deploy direct from your local?

**Comment by justclint** [comment]
@ba66e77 previously I did the local deploy on a test branch but Ive just gone and done a local deploy with "develop-build" which is the same as the one travis pushes and I can confirm that all the config files are included and visibible on the Acquia server.

Then I went and reran the latest "develop-build" branch from travis and once it deployed to Acquia all the split config files are missing again.

So some how travis is not including any split config files except for the default config.

**Comment by justclint** [comment]
Im wondering if this is related to https://github.com/acquia/blt/pull/2680

Since I hadnt run `blt setup` locally in a while I went and ran it. It finds differences in the active config and then force exports the the config to the default config folder and deletes the /config/local files and also modifies the config files in /config/default.

This seems to be the same thing thats happening on travis except that its deleting all the split configs. And I do see that the travis build does export config due to finding differences in the active config.

**Comment by ba66e77** [comment]
That doesn't feel right to me, but I don't have a better explanation of the behavior you're seeing at present. You could update to the latest 9.x-dev version and test against that, or patch your current 9.0.5 version.

**Comment by justclint** [comment]
Yeah, I see what you mean. The `blt setup` task and the export config is not really related to this. 

Ive tested this over and over and every time I deploy from local all the config files get included and pushed to the acquia repo but when ever I merge a branch in github and the build gets pushed from travis it doesnt include any of the config files except for /config/default.

I went to compare the travis `blt artifact:build` vs the local `blt artifact:build` and I did notice the object count is different:

On travis
```
Merging upstream changes into local artifact...
[ExecStack] git fetch 11ba32f631c96b955b9c4e31a8a7ad9f develop-build && git merge 11ba32f631c96b955b9c4e31a8a7ad9f/develop-build
[ExecStack] Running git fetch 11ba32f631c96b955b9c4e31a8a7ad9f develop-build &&
 git merge 11ba32f631c96b955b9c4e31a8a7ad9f/develop-build in /home/travis/build/*redacted*/*redacted*/deploy
Warning: Permanently added the RSA host key for IP address '##.##.##' to the list of known hosts.
remote: Counting objects: 291516, done.
remote: Compressing objects: 100% (61687/61687), done.
remote: Total 291516 (delta 212563), reused 277663 (delta 198747)
Receiving objects: 100% (291516/291516), 227.58 MiB | 21.91 MiB/s, done.
Resolving deltas: 100% (212563/212563), done.
...
...
...
Pushing artifact to git.remotes...
[ExecStack] git push 11ba32f631c96b955b9c4e31a8a7ad9f develop-build
[ExecStack] Running git push 11ba32f631c96b955b9c4e31a8a7ad9f develop-build in /home/travis/build/*redacted*/*redacted*/deploy
Counting objects: 817, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (476/476), done.
Writing objects: 100% (817/817), 184.47 KiB | 6.36 MiB/s, done.
Total 817 (delta 645), reused 317 (delta 219)
```

On local:
```
Merging upstream changes into local artifact...
[ExecStack] git fetch 11ba32f631c96b955b9c4e31a8a7ad9f develop-build && git merge 11ba32f631c96b955b9c4e31a8a7ad9f/develop-build
[ExecStack] Running git fetch 11ba32f631c96b955b9c4e31a8a7ad9f develop-build &&
 git merge 11ba32f631c96b955b9c4e31a8a7ad9f/develop-build in /var/www/*redacted*/deploy
remote: Counting objects: 291927, done.
remote: Compressing objects: 100% (62031/62031), done.
remote: Total 291927 (delta 212924), reused 277728 (delta 198764)
Receiving objects: 100% (291927/291927), 227.62 MiB | 6.72 MiB/s, done.
Resolving deltas: 100% (212924/212924), done.
...
...
...
Pushing artifact to git.remotes...
[ExecStack] git push 11ba32f631c96b955b9c4e31a8a7ad9f develop-build
[ExecStack] Running git push 11ba32f631c96b955b9c4e31a8a7ad9f develop-build in /var/www/*redacted*/deploy
Counting objects: 853, done.
Compressing objects: 100% (581/581), done.
Writing objects: 100% (853/853), 224.74 KiB | 0 bytes/s, done.
Total 853 (delta 629), reused 357 (delta 206)
```

I would think these should have the same object count but theres definitely more when deploying from local.

**Comment by ba66e77** [comment]
What's the result if you run the build locally using the `--environment=ci` option? If there's something in the config that's causing it to drop those files, it _should_ manifest when you build using that option.

**Comment by dpagini** [comment]
Sorry to chime in... the sync strategy in this file _should_ just be an override though. If you have a sync strategy defined in your main `blt/project.yml` or `blt/blt.yml` file, that should be what's being used. I think you can use the BLT config:dump command to see what the values are set to, even after you pass in your `--environment=ci` flags as well. That may help?

**Comment by justclint** [comment]
@dpagini no worries. I appreciate the help. I see what you mean. Our blt.yml has the strategy set to "config-split". 

I tried the config:dump and also with `--environment=ci` but they're pretty much identical except for the expected hostnames. Still not really seeing why `blt setup` keeps exporting and overwriting config files instead of importing them.

**Comment by ba66e77** [comment]
@justclint try this PR #2865 and see if it resolves your issue as well.

**Comment by justclint** [comment]
@ba66e77 finally got this figured out. Seems like we never setup a config split for ci. After creating that it seems to be working as expected now. The develop-build branch now includes all the split config files in Acquia repo. Thanks again for your help on this.

**Comment by justclint** [comment]
@ba66e77 Although we got our issue resolved re: the config directories getting deleted by setting up the split config for ci, we did still experience config/default getting overrwritten during `blt setup` during the `drush @self cex` process. 

I tried out #2865  and that did solve that issue. When I run `blt setup` now I can confirm config/default is no longer getting overwritten and now when `drush @self cex` task comes up I get "The active configuration is identical to the configuration in the export directory (/var/www/*redacted*/config/default)."
