### ISSUE TITLE
Composer create project failing

### ISSUE THREAD

**Issue by gpahuja** [acquia/blt#2855]
My system information:
* Operating system type: Linux
* Operating system version: Ubuntu 16
* BLT version: latest

composer create-project --no-interaction acquia/blt-project my-project

Output:

PHP Notice:  Undefined property: Acquia\Blt\Robo\Config\DefaultConfig::$config in /var/www/html/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70
PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /var/www/html/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php:70
Stack trace:
#0 /var/www/html/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(58): Acquia\Blt\Robo\Config\DefaultConfig->setSite('default')
#1 /var/www/html/my-project/vendor/acquia/blt/src/Robo/Config/ConfigInitializer.php(84): Acquia\Blt\Robo\Config\ConfigInitializer->setSite('default')
#2 /var/www/html/my-project/vendor/acquia/blt/bin/blt-robo-run.php(29): Acquia\Blt\Robo\Config\ConfigInitializer->initialize()
#3 /var/www/html/my-project/vendor/acquia/blt/bin/blt-robo.php(14): require_once('/var/www/html/m...')
#4 /var/www/html/my-project/vendor/acquia/blt/bin/blt(11): require_once('/var/www/html/m...')
#5 {main}
  thrown in /var/www/html/my-project/vendor/acquia/blt/src/Robo/Config/DefaultConfig.php on line 70

**Comment by ba66e77** [comment]
This is a known issue we've encountered lately.  We're working on testing of a new release to fix the issue but in the meant time you can either switch to use the dev release of BLT or downgrade Robo. See https://github.com/acquia/blt/issues/2844
