### ISSUE TITLE
phpcs commands do not respect settings in phpcs.xml config file

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#2869]
I have copied `phpcs.xml.dist` to `phpcs.xml` and set:

```
<config name="ignore_warnings_on_exit" value="1" />
```

Because when my code is being scanned before a commit, I don't want warnings to prevent the commit from passing.

However it looks like the PHPCS commands don't load this config file at all: https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Validate/PhpcsCommand.php

Is this intentional? Any reason why this config file is not used?

**Comment by ba66e77** [comment]
To my read of [PHPCS's documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#using-a-default-configuration-file), it should be picking up the phpcs.xml based on the directory from with the phpcs command is executed, which, according to [sniffFileSets()](https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Validate/PhpcsCommand.php#L22), should be the repo root.

Do you see different results if you invoke phpcs manually from the repo root?

**Comment by bkosborne** [comment]
Ok, thanks for checking up on that. I think you're right, and I must have something else going on.
