### ISSUE TITLE
BLT and TravisCI and blt/composer.required.json

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#2875]
My system information:
* Operating system type: TravisCI
* BLT version: 9.1-alpha1

When I run this command:
```
TravisCI build
```

I get the following output:
```
1.09s$ composer self-update
                                                                        
  [Wikimedia\Composer\Merge\MissingFileException]                       
  merge-plugin: No files matched required 'blt/composer.required.json'  
                                                                        
The command "composer self-update" failed and exited with 1 during .
Your build has been stopped.

```

And I expected this to happen:

The build to not fail at the very beginning. It turns out that the upgrade of BLT has explicitly ignored this file:

```
$ cat blt/.gitignore
# Ignore composer includes.
composer.required.json
composer.suggested.json
```

**Comment by mikemadison13** [comment]
@seanhamlin this is a semi-common problem that happens after updating to BLT 9. there are 2 ways to fix this.

first, remove your vendor folder and re-update BLT with composer (this should cause this files to be created automatically).

the other option is to manually download the composer.required and composer.suggested files and place them in the blt folder manually (not recommended). 

the blt update process WILL create these files, but composer sometimes balks about them not existing before the blt update has a chance to run.

**Comment by seanhamlin** [comment]
OK, so I did:

```
rm -rf vendor
composer update acquia/blt
composer update --lock
```

This created the diff

```
$ git status
On branch drupal-8.5
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   docroot/.ht.router.php
	modified:   docroot/robots.txt
	modified:   docroot/sites/default/default.settings.php
	modified:   docroot/sites/example.settings.local.php
	modified:   docroot/sites/example.sites.php
```

I don't see how this would fix my issue.

If I manually edit the `blt/.gitignore` file, then I can get this to work.

**Comment by dpagini** [comment]
@seanhamlin are you trying to commit your `blt/composer.*.json` files? The idea is that they sit in that folder, gitignored, and don't get committed. You shouldn't edit them at all either, they just sit there.

**Comment by mikemadison13** [comment]
@seanhamlin are you still having issues with this?

**Comment by mikemadison13** [comment]
just a final note here, then closing from inactivity. 

sometimes in travis specifically, you need to flush the build caches to get composer to add these files.

**Comment by lubomirculen** [comment]
Just for a reference, if somebody else is facing the problem - for me the problem really was in travis caches. Namely, vendor folder cannot be between `cache.directories`. Removing that folder from cached directories solved the issue.
