### ISSUE TITLE
Failed DB updates do not trigger deployment failures

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#2876]
If a DB update fails to apply as part of the configuration import task, BLT should exit with an error code. Instead, it sometimes still returns success.

I specifically encountered this as part of updates triggered by the db-update factory hook on ACSF, but I think it would be a problem in any environment.

Interestingly, I've seen the same update hook (datetime_update_8001) fail in two different ways, and BLT reacted differently each time:
- Once it threw the following error and was _not_ caught by BLT: "Call to a member function setSetting() on null in datetime_update_8001()"
- Another time it threw the following error and _was_ caught correctly by BLT: "Cannot add field node__scheduled_transition_date.scheduled_transition_date_timezone: field already exists."

Here's the misbehaving code in BLT: https://github.com/acquia/blt/blob/0a5944f345cabb559f10a309546369a5fdf1e9e6/src/Robo/Commands/Setup/ConfigCommand.php#L68

**Comment by mikemadison13** [comment]
same issue I was hitting in https://github.com/acquia/blt/issues/2755

**Comment by danepowell** [comment]
Haven't seen this recently, and I don't have a clear way to reproduce, so closing for now.
