### ISSUE TITLE
blt: command not found

### ISSUE THREAD

**Issue by janaksingh** [acquia/blt#288]
I set up the alias as per the installation guide, here is the output of my bashrc

```
function blt() {
  if [ "'git rev-parse --show-cdup 2> /dev/null'" != "" ]; then
    GIT_ROOT=$(git rev-parse --show-cdup)
  else
    GIT_ROOT="."
  fi

  if [ -f "$GIT_ROOT/vendor/bin/blt" ]; then
    $GIT_ROOT/vendor/bin/blt "$@"
  else
    echo "You must run this command from within a BLT-generated project repository."
  fi
}
```

However, command is not found. :)

**Comment by grasmash** [comment]
* What operating system are you using? 
* Did you restart your terminal session or `source ~/.bashrc`?

**Comment by janaksingh** [comment]
I am on Mac (10.11.6) and yeah I restarted the terminal after the alias command.

**Comment by grasmash** [comment]
By default, Mac OSX does not utilize a .bashrc file. It will use .bash_profile. If you already had a .bashrc file on your system for some reason, BLT will have added its alias to it. However, if your .bash_profile does not explicitly source .bashrc, the alias will never be available. I'd recommend one of the following: 

* Remove .bashrc and rerun the alias installation. This should result in it being installed to .bash_profile. 
* Add `source $HOME/.bashrc` to your .bash_profile.

**Comment by janaksingh** [comment]
Thanks @grasmash 

That seems to have worked. I renamed my bashrc file (not sure how that got there) and re-ran the alias. All good 👯 

`BLT can automatically create a Bash alias to make it easier to run BLT tasks.
This alias may be created in .bash_profile or .bashrc depending on your system architecture.

Install alias? (y/n)y
Added alias for blt to /Users/mememe/.bash_profile
You may now use the 'blt' command from anywhere within a BLT-generated repository.

Restart your terminal session or run 'source /Users/mememe/.bash_profile' to use the new command.

BUILD FINISHED

Total time: 11.5380 seconds`

**Comment by alexsoble** [comment]
If anyone is having difficulty with the `blt` alias on their Mac in 2019 and is looking at this thread to figure things out, the contents of `function blt()` have changed:

```
function blt() {
  if [[ ! -z ${AH_SITE_ENVIRONMENT} ]]; then
    PROJECT_ROOT="/var/www/html/${AH_SITE_GROUP}.${AH_SITE_ENVIRONMENT}"
  elif [ "`git rev-parse --show-cdup 2> /dev/null`" != "" ]; then
    PROJECT_ROOT=$(git rev-parse --show-cdup)
  else
    PROJECT_ROOT="."
  fi

  if [ -f "$PROJECT_ROOT/vendor/bin/blt" ]; then
    $PROJECT_ROOT/vendor/bin/blt "$@"

  # Check for local BLT.
  elif [ -f "./vendor/bin/blt" ]; then
    ./vendor/bin/blt "$@"

  else
    echo "You must run this command from within a BLT-generated project."
    return 1
  fi
}
```

**Comment by alexsoble** [comment]
☝️ Information on how to make sure the `blt` command works locally might be good to add to the "macOS" panel under "Installing Acquia BLT":

https://docs.acquia.com/blt/install/#blt-system-requirements
