### ISSUE TITLE
BLT running issue on CENT OS

### ISSUE THREAD

**Issue by shamsher327** [acquia/blt#2898]
My system information:
* Operating system type: AWS
* Operating system version: AWS CENTOS
* BLT version: 9

Output of `blt doctor`:
```
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/1356278-408--8.5.x-real.patch


  [Exception]
  Cannot apply patch 1356276 - Allow profiles to provide a base/parent profile and load them in the correct order (https://www.drupal.org/files/issues/1356278-408--8
  .5.x-real.patch)!


```

When I run this command:
```
composer install
```

I get the following output:
```
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/1356278-408--8.5.x-real.patch


  [Exception]
  Cannot apply patch 1356276 - Allow profiles to provide a base/parent profile and load them in the correct order (https://www.drupal.org/files/issues/1356278-408--8
  .5.x-real.patch)!

```

And I expected this to happen:

**Comment by ba66e77** [comment]
@shamsher327, that error most commonly means the version of Drupal core or the distribution you're installing doesn't fit the patch that is being applied. What's the distro and core version you're installing?

It would help if you can edit the issue to include the output of `blt doctor` where requested and to indicate the full version of BLT you're using (there is a 9.0.x branch and a 9.1.x branch and they're not exactly the same).

**Comment by ba66e77** [comment]
Since there has been no further discussion on this in over a month, I'm going to assume it's resolved and close it out.
