### ISSUE TITLE
Update database array in local.settings.php when running `recipes:multisite:init`

### ISSUE THREAD

**Issue by ba66e77** [acquia/blt#2907]
When running blt recipes:multisite:init, BLT prompts for database information and uses that into to setup a database record in box/config.yml but that connection information does not populate the database array in the new site's `local.settings.php` file. As a result, without modification, the new site connects to the original database.

https://github.com/acquia/blt/blob/44785181bf2038493929d45ebd375b36ae903148/src/Robo/Commands/Generate/MultisiteCommand.php

**Comment by bschilt** [comment]
This was a frustrating issue to experience, especially when a developer is trying to set up their local dev environment for the first time. 

I was able to get around this by adding the DB info into the `sites/[sitename]/blt.yml` file like this: 

```
drupal:
  db:
    database: [sitename]
    username: [username]
    password: [password]
    host: localhost
    port: 3306
```

These creds will obviously need to match what's in the `mysql_users` array in `box/config.yml`.  Now the `blt:init:settings` command will properly create the local.settings.php file. 

I agree that the `recipes:multisite:init` command should handle the DB credentials, perhaps that command just needs to populate the site specific blt.yml file with the DB array.
