### ISSUE TITLE
Multisite Acquia Drupal and Config split

### ISSUE THREAD

**Issue by txcastilloguerra** [acquia/blt#2910]
My system information:
* Operating system type: Mac OS X
* Operating system version: 10.12.6
* BLT version: 8.9.14

Hi guys! I'm building a Drupal 8 multisite on the acquia cloud using BLT, and I'd like to know if there's any documentation on how to set it up with config split, so I can use a single configuration scheme across all sites.

Thanks!

Jose

**Comment by ba66e77** [comment]
Have you looked at http://blt.readthedocs.io/en/latest/config-split/#config-split?

**Comment by arun9989** [comment]
@ba66e77 I am facing a similar issue with config_split. https://github.com/acquia/blt/issues/2930

**Comment by ba66e77** [comment]
Since it's been three weeks since there was a response from the OP, I'm going to presume the issue is resolved.
