### ISSUE TITLE
Backport fix #2865 (redundant config import for config splits) to 8.x

### ISSUE THREAD

**Issue by mirsoftacquia** [acquia/blt#2912]
It would be great to backport PR https://github.com/acquia/blt/pull/2865 as it affects 8.x branch as well and it causes serious difficulties on `blt sync:refresh` (among others) especially if allow-overrides setting is disabled.

**Comment by mikemadison13** [comment]
great idea @mirsoftacquia ! do you want to roll a PR or do you want one of us to?

**Comment by mirsoftacquia** [comment]
Sure, here it comes :)

**Comment by ba66e77** [comment]
This was merged several days ago and is part of the 8.9.15 release.
