### ISSUE TITLE
blt recipes:acsf:init:all must include dependencies (samlauth SSO)

### ISSUE THREAD

**Issue by bhasselbeck** [acquia/blt#2919]
My system information:
* BLT version: "^9.1.0"

Output of `blt doctor`:
```
all normal
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
+--------------------------------------+-----------------------------------------------------------+
```

When I run this command:
```
blt recipes:acsf:init:all
```

And I expected this to happen:
```
the samlauth module is a dependency of acsf_sso and isn't included
```
Summary:
When the samlauth module is not included in the codebase, errors are displayed in the ACSF status log even if the acsf_sso sub-module is not enabled.

**Comment by danepowell** [comment]
The better way to architect this would be for the ACSF module to include the samlauth dependency: https://www.drupal.org/project/acsf/issues/2917870

However, if that's not going to happen, I guess BLT should handle it. Although the same arguments against including it as a dependency of the ACSF module might apply to BLT.

**Comment by bhasselbeck** [comment]
If the ACSF module includes it by default, it will be enabled on every site ~ which might not be a desirable outcome. We could use BLT to initialize it, but the issue is that even if it's "not wanted", it throws errors on the ACSF status log.

**Comment by danepowell** [comment]
Sorry, to be clear I'm just asking that the ACSF module include the _Composer_ dependency for Samlauth. So the module will be present, but not enabled. That shouldn't do any harm, and it avoids this problem for users _and_ non-users of BLT.

**Comment by ba66e77** [comment]
@bhasselbeck, so there's not doubt about which version of BLT you're on, could you edit your request to include that part? Your OS doesn't seem relevant so you can just remove those.

To summarize, when the samlauth module is not included in the codebase, errors are displayed in the ACSF status log even if the acsf_sso sub-module is not enabled. Is that correct?

**Comment by bhasselbeck** [comment]
Yes @ba66e77, I'll make the edits. thanks :)

**Comment by danepowell** [comment]
Closing this since it's an upstream issue, and will be resolved as soon as ACSF adds that dependency.
