### ISSUE TITLE
BLT Projects without Lightning?

### ISSUE THREAD

**Issue by greggmarshall** [acquia/blt#2920]
My system information:
* Operating system type: MacOS
* Operating system version: 10.13.5
* BLT version: 9.1.0-alpha1

In  #235 the instructions are to replace profile.name and profile.contrib in the project.yml file.  

I presume that project.yml has become blt.yml?

I don't have a profile.contrib setting in my blt.yml file?  What is its format?

More generally, is there documentation on all the potential blt.yml file options?

Also if I update the blt.yml file should I be running some command (blt setup???) to integrate any changes into my project?

**Comment by ba66e77** [comment]
> I presume that project.yml has become blt.yml?

Correct, project.yml is blt.yml in the 9.x branch.

> I don't have a profile.contrib setting in my blt.yml file? What is its format?

The profile.contrib setting was [deprecated a while ago](https://github.com/acquia/blt/commit/fc1c7414a73f8316b01b430419babe192264cc4f). Just setting the profile.name option will suffice.

> More generally, is there documentation on all the potential blt.yml file options?

Not formal documentation, no (but I wouldn't snub a PR adding that documentation ;) ). The [build.yml](https://github.com/acquia/blt/blob/9.x/config/build.yml) referenced in the [docs for extending/modifying BLT](http://blt.readthedocs.io/en/latest/extending-blt/#modifying-blt-configuration) lists all the expected options and their default values.

> Also if I update the blt.yml file should I be running some command (blt setup???) to integrate any changes into my project?

Mostly, no. But it really depends on what you change. For instance, if you change the project prefix you won't have to make do anything else (though your commit logs may look odd). On the other hand, if you change the project machine_name or the install profile, you'll need to destroy the VM and rebuild. This would be great to add to the documentation of the options in blt.yml.

Does that cover what you need?
