### ISSUE TITLE
How to use profile split with blt project

### ISSUE THREAD

**Issue by arun9989** [acquia/blt#2934]
How to use profile split with blt project? Could not found much more information in acquia blt configuration management documentation.

How to use profile split and a use case of it?

**Comment by ba66e77** [comment]
It might help if you could tell us what you're trying to accomplish that you think a profile split will help with. 

Other than that [profile splits use the active profile to determine what set of configuration to use](https://blt.readthedocs.io/en/latest/config-split/#profile-split), they're not any different from regular config splits.

**Comment by ba66e77** [comment]
@arun9989, since we've not heard anything further from you I'm assuming the documentation above had what you needed. If that's not the case, feel free to reopen.
