### ISSUE TITLE
Travis CI fails once using Configuration Management

### ISSUE THREAD

**Issue by haynescw** [acquia/blt#294]
After we got to a point in our development on a project and started exporting our configuration. I noticed that the travis builds were failing. In fact, even the blt builds were failing. Is there currently anything we can do to resolve this. Is anyone else running into this issue at all? Im open for any thought. Do we do a simple drush cim before we build the site locally?

**Comment by grasmash** [comment]
BLT does import configuration from`config/default` directly after drupal is installed. This happens locally and on Travis, or whenever the `setup:drupal:install` target is called.

**Comment by grasmash** [comment]
It's likely that there's an issue with your configuration itself. Can you share the log output?

**Comment by haynescw** [comment]
is there any way we can have that directory location set  as a variable. I see why our is failing now, because we save ours in /config/default/sync.

**Comment by haynescw** [comment]
I mean we could change to make sure that we are meeting BLT's convention, but it seems that since CM setup and workflow has not really been defined, and most state to define your own workflow for what fits your process. Since we arent using the staging directory, then i would assume we could meet BLT's default convention. Thoughts?

**Comment by grasmash** [comment]
@haynescw This is configurable: https://github.com/acquia/blt/blob/8.x/template/docroot/sites/default/settings/default.local.settings.php#L30

After drupal is installed, BLT simply runs `drush config-import --partial`.

**Comment by haynescw** [comment]
Correct, its is configurable to drupal. I meant make it configurable to blt, because that is what we have done, so are you saying that BLT gets its path form the local.settins.php? if so then we are good with this issue. I like that. Thanks
