### ISSUE TITLE
SimpleSAML PHP Fatal Error: Cannot redeclare ah_db_current_host

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#2950]
My system information:
* BLT version: 9.1

Issue:
Running SimpleSAML PHP and attempting to login trips:

php-error web-2585 [13-Jul-2018 17:00:58 UTC] PHP Fatal error: Cannot redeclare ah_db_current_host() (previously declared in /vendor/simplesamlphp/simplesamlphp/config/acquia_config.php:205) in /vendor/simplesamlphp/simplesamlphp/config/acquia_config.php on line 205 

Likely because we define this in our acquia config AND it's in the simplesamlphp module: https://github.com/acquia/blt/blob/9.x/scripts/simplesamlphp/acquia_config.php#L192

Proposed resolution is to remove our copy of the ah_db_current_host in the acquia config file in BLT.

**Comment by rjgwiz** [comment]
@mikemadison13 can you confirm if it made it into the latest simplesamlphp module?

I ran into this issue on our last `simplesamlphp_auth` upgrade a month or two ago, which also brought in a [simplesamlphp lib](https://github.com/simplesamlphp/simplesamlphp) update. What I found at the time from debugging was the SAML lib was loading config twice in one request, which caused this error. Me and @dpagini worked around it by wrapping it in an if function_exists:

```
if (!function_exists('ah_db_current_host')) {
  function ah_db_current_host($db_cluster_id) {
    require_once("/usr/share/php/Net/DNS2_wrapper.php");
    try {
      $resolver = new Net_DNS2_Resolver(array('nameservers' => array('127.0.0.1', 'dns-master')));
      $response = $resolver->query("cluster-{$db_cluster_id}.mysql", 'CNAME');
      $cached_id = $response->answer[0]->cname;
    } catch (Net_DNS2_Exception $e) {
      $cached_id = "";
    }
    return $cached_id;
  }
}
```

**Comment by mikemadison13** [comment]
@rjgwiz i may go that route, although @lcatlett is totally refactoring the acquia config so it may not be necessary. i have a temporary work around until we sort it out.
