### ISSUE TITLE
Incorrect url in acquia cloud blt update

### ISSUE THREAD

**Issue by marcdelay** [acquia/blt#2966]
My system information:
* Operating system type: acquia
* BLT version: 9.1.0

When using blt deploy to acquia hosted site the config update fails for reasons.
The output includes a link to find out more about what the reasons are.
"[error]  Configuration in the database does not match configuration on disk. BLT has attempted to automatically fix this by re-exporting configuration to disk. Please read https://github.com/acquia/blt/wiki/Configuration-overrides "

I think the new url is https://github.com/acquia/blt/wiki/Configuration-override-test-and-errors

**Comment by ba66e77** [comment]
Thanks for catching that, @marcdelay.

**Comment by ba66e77** [comment]
Actually, it looks like this was already fixed prior to the 9.1.0 release: https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Setup/ConfigCommand.php#L199
