### ISSUE TITLE
BLT setup on existing project

### ISSUE THREAD

**Issue by ArthurMiller** [acquia/blt#2970]
My system information:
* Operating system type: OSX
* Operating system version: 10.12.6
* BLT version: ^9.0.0

Output of `blt doctor`:
```
BLT not installing
```

When I run this command:
composer install

```

I get the following output:
```
composer install -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/Users/millera/Desktop/PartnerPortal5/partner-portal): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /Users/millera/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /Users/millera/Desktop/PartnerPortal5/partner-portal/docroot/vendor/composer/installed.json
Loading plugin Acquia\Blt\Composer\Plugin
Loading plugin Composer\Installers\Plugin
Loading plugin cweagans\Composer\Patches
Loading plugin Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin
Loading plugin DrupalComposer\DrupalScaffold\Plugin
Loading plugin grasmash\DrupalSecurityWarning\Composer\Plugin
Loading plugin OomphInc\ComposerInstallersExtender\Plugin
Loading plugin Wikimedia\Composer\MergePlugin

                                                                        
  [Wikimedia\Composer\Merge\MissingFileException]                       
  merge-plugin: No files matched required 'blt/composer.required.json'  
                                                                        

Exception trace:
 () at /Users/millera/Desktop/PartnerPortal5/partner-portal/docroot/vendor/wikimedia/composer-merge-plugin/src/MergePlugin.php:222
 Wikimedia\Composer\MergePlugin->Wikimedia\Composer\{closure}() at n/a:n/a
 array_map() at /Users/millera/Desktop/PartnerPortal5/partner-portal/docroot/vendor/wikimedia/composer-merge-plugin/src/MergePlugin.php:229
 Wikimedia\Composer\MergePlugin->mergeFiles() at /Users/millera/Desktop/PartnerPortal5/partner-portal/docroot/vendor/wikimedia/composer-merge-plugin/src/MergePlugin.php:180
 Wikimedia\Composer\MergePlugin->onInit() at n/a:n/a
 call_user_func() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:176
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:81
 Composer\EventDispatcher\EventDispatcher->dispatch() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/Factory.php:399
 Composer\Factory->createComposer() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/Factory.php:576
 Composer\Factory::create() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/Console/Application.php:338
 Composer\Console\Application->getComposer() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/Console/Application.php:451
 Composer\Console\Application->getPluginCommands() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/Console/Application.php:149
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/1.6.4/bin/composer/bin/composer:58
 require() at /usr/local/Cellar/composer/1.6.4/bin/composer:24
```

And I expected this to happen:
Installation of BLT.
The BLT specific directories do not get created within the project and BLT is not installed.
The following is the link to where I attained the documentation:
https://blt.readthedocs.io/en/latest/adding-to-project/

The following is the composer.json file I am using:
{
  "name":    "ew/portal",
  "license": "proprietary",
  "description": "EW partner portal website",
  "type":    "project",
  "repositories": [
    {
      "type": "composer",
      "url":  "https://packages.drupal.org/8"
    },
    {
        "type": "composer",
        "url": "https://asset-packagist.org"
    }
  ],
  "require": {
      "composer/installers": "^1.0.20",
      "cweagans/composer-patches": "~1.0",
      "drupal/acquia_connector": "^1",
      "drupal/acsf": "^1",
      "drupal/core": "~8",
      "acquia/lightning": "~3.1.4",    
      "drupal/memcache": "2.0.0-alpha5",
      "drupal/security_review": "1.x-dev",
      "roave/security-advisories": "dev-master",
      "drupal-composer/drupal-scaffold": "^2.0.1",
      "drupal-composer/drupal-security-advisories": "8.x-dev",
      "drupal/devel": "^1",
      "drupal/advagg": "^3.0",
      "drupal/admin_toolbar": "^1",
      "drupal/field_permissions":"^1.0@beta",
      "drupal/menu_item_extras": "^2.2",
      "drupal/smart_trim": "^1",
      "drupal/node_view_permissions": "^1",
      "drupal/autologout": "^1",
      "drupal/field_collection": "^1",
      "drupal/clamav": "^1",
      "drush/drush": "^9.0.0",
      "drupal/seckit": "^1.0@alpha",
      "drupal/layout_plugin": "^1.0@alpha",
      "drupal/fast_404": "^1.0@alpha",
      "drupal/google_tag": "1.x-dev",
      "drupal/recaptcha": "^2.2",
      "drupal/datatables": "^1.0@RC",
      "drupal/group": "1.x-dev",
      "drupal/ajax_comments": "^1.0@beta",
      "drupal/autogrow": "^1.0",
      "drupal/workflow": "^1.0", 
      "drupal/imagemagick": "^2",
      "drupal/content_access": "^1.0@alpha",
      "drupal/password_policy": "^3.0@alpha",
      "drupal/password_strength": "^2.0@alpha",
      "drupal/scheduled_updates": "^1.0",
      "drupal/workbench_moderation": "^1.3",
      "drupal/twig_extensions": "^1.1",
      "drupal/mimemail": "^1.0",
      "drupal/reroute_email": "^1.0",
      "drupal/smtp": "^1.0",
      "acquia/blt": "^9.0.0"
  },
  "minimum-stability": "dev",
  "prefer-stable":     true,
  "extra": {
    "installer-paths": {
      "docroot/core": [
          "type:drupal-core"],
      "docroot/modules/contrib/{$name}": [
          "type:drupal-module"],
      "docroot/modules/custom/{$name}": [
          "type:drupal-custom-module"],
      "docroot/profiles/contrib/{$name}": [
          "type:drupal-profile"],
      "docroot/profiles/custom/{$name}": [
          "type:drupal-custom-profile"],
      "docroot/themes/contrib/{$name}": [
          "type:drupal-theme"],
      "docroot/themes/custom/{$name}": [
          "type:drupal-custom-theme"],
      "docroot/libraries/{$name}": [
          "type:drupal-library",
          "type:bower-asset",
          "type:npm-asset"],
      "drush/contrib/{$name}": [
          "type:drupal-drush"]
    },
    "patches": {
      "drupal/core": {
        "Ignore front end vendor folders to improve directory search performance": "https://www.drupal.org/files/issues/ignore_front_end_vendor-2329453-116.patch",
        "mkdir patch in Drupal": "https://www.drupal.org/files/issues/2799635-fix_mkdir-15.patch",
        "File name Transliteration in Drupal": "https://www.drupal.org/files/issues/use_new_transliteration-2492171-51.patch",
        "Uploading a managed file results in a duplicate temporary record": "https://www.drupal.org/files/issues/2018-05-02/2884052-37.patch",
        "Views exposed filter, illegal choice fix": "https://www.drupal.org/files/issues/2877061-17-store_group_input_value.patch",
        "Output entity reference":"https://www.drupal.org/files/issues/2018-03-09/drupal-use_view_output_for_entityreference_options-2174633-206.patch"
      },
      "drupal/twig_extensions": {
        "Twig Extensions Trans Error": "https://www.drupal.org/files/issues/2018-04-24/twig_extension-trans_error-2895187-16.patch"
      },
      "drupal/password_policy": {
        "Inconsistent date format and timezone usage leads to infinite password resets.": "https://www.drupal.org/files/issues/password_policy-inconsistent-datetime-formats-2860671-13-D8.patch"
      },
      "drupal/memcache": {
        "Memcache Patch": "https://www.drupal.org/files/issues/update-readme-2934916-4.patch"
      },
      "drupal/mimemail": {
        "Fix render call for ajax submissions": "patches/mimemail-render.patch"
      },
      "acquia/lightning": {
        "Fix typo in version number": "https://www.drupal.org/files/issues/2018-05-14/fix-version-string-2972058-4.patch"
      }
    },
    "drupal-scaffold": {
      "excludes": [
        ".htaccess",
        ".ht.router.php"
       ]
     },
     "merge-plugin": {
        "require": [
        "blt/composer.required.json",
        "blt/composer.suggested.json"
      ],
        "merge-extra": true,
        "merge-extra-deep": true,
        "merge-scripts": true,
        "replace": false,
        "ignore-duplicates": true
    }
  },
  "scripts": {
    "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
  },
  "config": {
    "vendor-dir": "docroot/vendor",
    "secure-http": false
  }
}

Top-level file structure:
drwxr-xr-x  21 millera  staff      714 Jul 23 17:11 .
drwxr-xr-x   4 millera  staff      136 Apr 30 12:27 ..
-rw-r--r--@  1 millera  staff     6148 Apr 30 12:54 .DS_Store
-rw-r--r--   1 millera  staff      336 Apr 30 12:28 .dockerignore
drwxr-xr-x  14 millera  staff      476 Jul 20 12:45 .git
-rw-r--r--   1 millera  staff      796 May  3 17:56 .gitignore
drwxr-xr-x  13 millera  staff      442 Jul  2 08:43 .idea
-rw-r--r--   1 millera  staff     4160 Jun 20 16:49 Dockerfile
-rw-r--r--   1 millera  staff     7697 Apr 30 12:28 Makefile
-rw-r--r--   1 millera  staff     7350 Apr 30 12:28 README.md
-rw-r--r--   1 millera  staff     5264 Jul 24 09:45 composer.json
-rw-r--r--   1 millera  staff  1865032 Jul 23 12:26 composer.phar
drwxr-xr-x   4 millera  staff      136 Apr 30 12:28 config
-rw-r--r--   1 millera  staff      514 Apr 30 12:28 docker-compose.local.yml
-rw-r--r--   1 millera  staff      483 Jun 20 16:49 docker-compose.yml
drwxr-xr-x  23 millera  staff      782 Jul 23 09:37 docroot
drwxr-xr-x   7 millera  staff      238 Apr 30 12:29 drush
drwxr-xr-x   9 millera  staff      306 Apr 30 12:28 hooks
drwxr-xr-x   3 millera  staff      102 Jun 21 16:50 patches
-rw-r--r--   1 millera  staff  3526216 May  3 17:56 phing-latest.phar
-rw-r--r--   1 millera  staff  2784899 May  3 17:29 phpunit.phar

**Comment by lcatlett** [comment]
@ArthurMiller what commands did you execute to add BLT to your project? It looks like you are using `docroot/vendor` as your vendor directory but executing the BLT install in the standard repository root, so the root-level composer.json does not exist. You can likely remove the `vendor-dir": "docroot/vendor"` config from your composer.json and instead use the BLT default.

**Comment by ArthurMiller** [comment]
You are awesome! That did the trick.
