### ISSUE TITLE
8.9.x includes Clear Twig caches on deploys patch, but it does not apply to Drupal core 8.6

### ISSUE THREAD

**Issue by jasonawant** [acquia/blt#2980]
8.9.x includes Clear Twig caches on deploys patch, but it does not apply to Drupal core 8.6.

A fix has been committed to Drupal 8.6, see https://www.drupal.org/project/drupal/issues/2752961#comment-12601760.

in 

8.9.x [composer.required.json](https://github.com/acquia/blt/blob/8.9.x/composer.required.json#L49)

```
    "patches": {
      "drupal/core": {
        "Clear Twig caches on deploys": "https://www.drupal.org/files/issues/2752961-90.patch"
      }
    }
```

[9.x composer.required.json](https://github.com/acquia/blt/blob/9.x/composer.required.json)
```
    "patches": {
      "drupal/core": {
        "Clear Twig caches on deploys": "https://www.drupal.org/files/issues/2752961-130.patch"
      }

```

**Comment by ba66e77** [comment]
Thanks for flagging that, @jasonawant. Definitely something we'll need to watch for when we cut a version supporting core 8.6.

**Comment by mikecrittenden** [comment]
Is there any suggested way to tell BLT to skip over this patch? I see in https://github.com/acquia/blt/issues/2758 that `composer.required.json` (the file including the patch) is not meant to be modified. Can I somehow undo this patch from within the project `composer.json` perhaps (if so, I can't figure out how)?

**Comment by mikecrittenden** [comment]
Ah, I just found https://github.com/cweagans/composer-patches#ignoring-patches which I think solves that.

**Comment by jasonawant** [comment]
I have tried to use this solution to ignore the patch, but no luck.

See https://github.com/cweagans/composer-patches#ignoring-patches.

As a work-around for testing purposes to experiment with 8.6, I just deleted this from composer.required.json during the composer.install.

**Comment by ba66e77** [comment]
For working with core 8.6, see the new core86 branch. Once 8.6 is live we'll pull that branch into the 9.x branch.

**Comment by greylabel** [comment]
@ba66e77 How about pulling the changes from https://github.com/acquia/blt/pull/2937/files into 8.9.x as well?
