### ISSUE TITLE
BLT alias checks sets PROJECT_ROOT but then checks against GIT_ROOT

### ISSUE THREAD

**Issue by timwood** [acquia/blt#2981]
My system information:
* Operating system type: Mac OS
* Operating system version: Sierra
* BLT version: 9.1.0

When I run this command:
```
blt -vvv
```

I get the following output:
```
You must run this command from within a BLT-generated project.
```

And I expected this to happen:
The `blt` command to successfully run from any subdirectory of the project root, while inside the VM, not just the project root.

The BLT alias was [recently updated to support Acquia cloud](https://github.com/acquia/blt/pull/2896) where previously `GIT_ROOT` was set, now `PROJECT_ROOT` is set, however later in the function it still checks for `GIT_ROOT`. I think the fix is to change the latter check to `PROJECT_ROOT`.

https://github.com/acquia/blt/blob/9.x/scripts/blt/alias

**Comment by ba66e77** [comment]
Thanks for flagging that, @timwood.
