### ISSUE TITLE
Remove implicit definition of the multisites array

### ISSUE THREAD

**Issue by ba66e77** [acquia/blt#2995]
As a BLT user, I want the list of multisites which make up my codebase to be explicitly defined in blt.yml and not determined magically by BLT so that it's more clear where values originate.

My system information:
* BLT version: 9.1.1

In investigating #2989 , it was found that, if no `multisites` config array has been defined, BLT will assume all directories under docroot/sites are multisites (see [DefaultConfig:getSiteDirs()](https://github.com/acquia/blt/blob/6523116116f42781ab17891f719d291fdb335756/src/Robo/Config/DefaultConfig.php#L86)). This implicit handling is likely to trip us up again at some point in the future, so I propose it should be made explicit instead.

- [ ] Populate the multisites config array with `default` automatically when a new project is created.
- [ ] Update the config array on each invocation of `recipes:multisite:init`
- [ ] Provide an update hook to populate the array for anyone who doesn't have it populated already

**Comment by danepowell** [comment]
I understand the desire to avoid situations like #2989, but is that the only benefit here? If so, it doesn't really seem worth the effort and risk of changing a fairly well-established system.

We already ignore `sites/g` and `sites/settings` when detecting multisites. It's hard to imagine any other edge cases that would arise from the current approach. And it's well-documented how this works, and what the workaround is, in docs/multisite.md.

On the other hand, if we force everyone to use the multisites array, that exposes additional configuration to a lot of end users, with a corresponding increased potential to screw up that configuration.

It's not a huge win either way, so all other things being equal I'd prefer too keep the status quo.

**Comment by danepowell** [comment]
I discussed with Mike, we both agreed that it seems like this would only limit usability for traditional multisite users without very clear gain.

If you think there's any additional justification for this that I'm missing, let me know.
