### ISSUE TITLE
Automatically create sites.php

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#2996]
As a BLT user, when I create a multisite with the `blt multisite` task, sites.php should automatically be created so that sites in the docroot/sites directory are recognized by Drupal core and drush as valid multisites.

**Comment by lcatlett** [comment]
closed with #2997

**Comment by lcatlett** [comment]
Reopening due to #2997 being reverted.

**Comment by ba66e77** [comment]
As discussed in #3031, we can't do this with ACSF sites as on deploy ACSF checks to ensure the sites.php in the codebase matches that provided by the module. So whatever solution is implemented will need to take that into consideration.

**Comment by lcatlett** [comment]
@ba66e77 settings.php can be used for this, ideally in a pre-settings-php hook and the `skip-default-settings` flag can be used as well if modifying sites.php locally is an issue.

**Comment by danepowell** [comment]
Let's consolidate discussion around the management of sites.php in #3477
