### ISSUE TITLE
Prepare for Drush removing superglobals during site install

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3000]
### Background
Drush is only run from the command line. When you run scripts from the command line, certain global variables aren't available (such as `$_SERVER['HTTP_HOST']`), because Apache and other web services aren't being invoked. Drupal (and BLT) depends on some superglobals being set, so Drush currently ['fakes' them during site installs](https://github.com/drush-ops/drush/blob/22606d1a613ad15914a4e88eb2d2e1c3fe20c613/src/Commands/core/SiteInstallCommands.php#L377).

Note that Drupal used to depend on these superglobals in a lot more places, and Drush thus used to set them for _every_ request (not just site installs), but this changed when [Drupal core stopped using them](https://www.drupal.org/project/drupal/issues/1998638), so [Drush stopped setting them](https://github.com/drush-ops/drush/pull/3109/files).

### Upcoming breaking changes
In 8.6.0, Drupal core is going to [stop using superglobals during site installs](https://www.drupal.org/project/drupal/issues/2958176) as well, and in response [Drush is going to stop setting them](https://github.com/drush-ops/drush/issues/3506).

### Action items
We need to determine what impact that Drush change will have on BLT, which might be using those superglobals for various things. For instance, we currently use `$_SERVER['HTTP_HOST']` to figure out [which multisite is running locally](https://github.com/acquia/blt/blob/887c4fb571898d8df7d9a96ecee8bec15c06de32/settings/blt.settings.php#L119). Presumably, that variable will no longer be available when running Drush commands with the new Drush release.

One way to see what will break is to simply hack out `serverGlobals()` in `drush/drush/src/Commands/core/SiteInstallCommands.php`. Obviously we should also grep for the use of superglobals.

Then we need to test a fix. This won't be possible until the upstream Drush issue has an associated PR: https://github.com/drush-ops/drush/issues/3506

As a side note, I'm curious how pretty much anything at all is working right now outside of site installs. For instance, it seems like `$_SERVER['HTTP_HOST']` wouldn't be set during any Drush commands except `site-install`, so how is BLT's existing settings working during Drush calls? Or is it not?

**Comment by lcatlett** [comment]
I'm breaking this out into blocking tasks that are an immediate priority and then longer term changes for tracking purposes

**Comment by cosmicdreams** [comment]
Currently running into this issue while updating a Site Factory-enabled site to Drupal 8.6.1.  Failures everywhere.

**Comment by lcatlett** [comment]
@cosmicdreams - this is exactly what #3172 addresses
