### ISSUE TITLE
Refactor server and other globals during site install and deploy:update

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3005]
As discussed in #3000, there are critical contextual variables that Drupal, BLT, various contrib modules, and Acquia Cloud configuration depend on that are set in super globals. This was refactored in Drush 9 and remains in Drush 8, however site-install may be broken before Drupal 8.6 is released as Drush is updated on projects. 

This issue is to capture the changes that will be prioritized in BLT.

**Comment by dpagini** [comment]
Closed by #3172?
