### ISSUE TITLE
blt:update modifies blt.yml to enable shield on prod sites.

### ISSUE THREAD

**Issue by Unicycle77** [acquia/blt#3014]
My system information:
* Operating system type: Windows
* Operating system version: Windows 10 Enterprise
* BLT version: 9.1.1

**blt:update** merges \vendor\acquia\blt\template\blt\blt.yml with the project's \blt\blt.yml, adding the shield module to prod deployments. This happens even if extra.blt.update is set to false in the project's composer.json.

Expected:
- When running blt:update, I expect the shield module to not be enabled in a production environment where sites should be accessible by the public.
- If extra.blt.update is set to false in the project's composer.json, I expect that \blt\blt.yml won't be modified when running blt:update

Research:
blt:update calls mungeProjectYml(), with a comment that explicitly states "Values in the project's existing blt.yml file will be preserved and not overridden." Although mungeProjectYml() does not _remove_ items from the project's existing blt.yml file, it still _adds_ items indiscriminately. There is no apparent way in blt.yml to prevent a module from being added back by blt:update if it is intentionally removed.

**Comment by timcosgrove** [comment]
Came here to +1 this. We don't use shield, and it's a minor but pesky annoyance that BLT continues to try and insert it into our blt.yml.

**Comment by danepowell** [comment]
I don't think it any longer makes sense to automatically munge blt.yml on updates. At the very least, that should only happen when blt.yml has actually changed (only a few times in the last few years). And I think we could target those updates more precisely, the way we do when injecting new composer dependencies and such.

Additionally, that documentation is out of date, as far as I can tell `extra.blt.update` is not actually implemented anywhere.

As to why Shield is enabled in production in the first place... when you initially create a site with BLT, you'll likely want to deploy it to production with shields up before you actually go live. So it does make sense to keep that there, even though already-live projects might want to remove it.
