### ISSUE TITLE
Re-integrate multisite enhancements

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3029]
We reverted #2997 as part of a hotfix. We should re-review that PR and pull in any needed functionality that was reverted, fixing the bugs along the way. Make sure to specifically test for the regressions documented in #3026 and #3027.

**Comment by ba66e77** [comment]
As discussed in the referenced PR, we are unable to re-introduce the multisite enhancements as they were implemented without triggering the issue that lead to the reversion. Instead we'll look at implementing specific issues atomically.
