### ISSUE TITLE
ACSF Site Installs, Config Imports, Deploy Updates, and Cron Failing

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3030]
When #2997 was reverted, deploying updates to ACSF and multisite ACE projects is completely broken since critical Factory Hooks are now removed and passing --uri always returns the `default` site on ACSF rather than the mapped multisite. This is blocking creating sites, running cron against the correct site, running updates, and successfully executing tasks such as config:import which use the fixes in #2997. For customers with content hub, this may de-register webhooks if settings were dependent on site_name and site path being defined in settings.php.

**Comment by ba66e77** [comment]
Working on confirming these issues. If you have steps to trigger the issues you're seeing, that would help.
