### ISSUE TITLE
Print output from config:status in isActiveConfigIdentical

### ISSUE THREAD

**Issue by timwood** [acquia/blt#3047]
As a step at the very end of `blt setup`, BLT runs a check to make sure exported config matches the DB. I believe it used to do so with `drush cex` which would output the the config differences, giving you a clue on how to fix the mismatch. Now it looks like BLT uses `drush config:status` to check if the config differs, and doesn't display anything useful about what config is different.

Could the isActiveConfigIdentical function in `src/Robo/Inspector/Inspector.php` be updated to not clobber the output of `drush config:status`, if the config differs?

**Comment by danepowell** [comment]
Immediately prior to config:status running, BLT will have already tried to import the config twice (via `drush cim`), which should provide the same output as `drush cex` or `drush config:status`. Having the inspector print it again seems like it would be redundant, wouldn't it?

**Comment by danepowell** [comment]
Closing after 7 days of inactivity, per contribution guidelines.
