### ISSUE TITLE
DT-596: Move slow validation from Git pre-commit hook to pre-push

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#3052]
Running linters and sniffers takes a lot of time, whereas committing should be quick. It really only matters that code isn't pushed with errors and violations in it. I suggest moving BLT's `pre-commit` hook implementation to `pre-push`.

**Comment by wu-edward** [comment]
I can see the benefit in this, but if you want to keep your commit record clean, and your push includes multiple commits, you'd have to rebase to incorporate and lintings/sniffing fixes.

**Comment by ba66e77** [comment]
I think I tend to lean with @wu-edward on this. If we're going to reject something, seems like it's better to reject it early.

**Comment by TravisCarden** [comment]
It occurs to me that the desirability of one or the other approach may depend on the use case. For example, when I'm doing TDD, I may commit once per minute. Since I've internalized most of the coding standards and my automated tests catch everything a PHP lint would, sniffing and linting on commit can cumulatively waste a large portion of my day for no benefit. On the other hand, for someone who's debugging or performing other lengthy tasks between commits, the rationale is reversed. Since we already have the ability to disable arbitrary Git hooks in `blt.yml`, perhaps the thing to do is to _add_ a `pre-push` hook and let users disable what they don't want.
