### ISSUE TITLE
Remove Clear Twig caches on deploys patch to support Drupal 8.6.x

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#3056]
The following patch has landed in core and will no longer apply to `8.6.x`:
https://www.drupal.org/files/issues/2752961-130.patch

**Comment by ba66e77** [comment]
This patch was already removed from the `core86` branch where we're tracking change related to Drupal core 8.6. Thanks, though.

**Comment by timwood** [comment]
And here is a URL reference-able patch (which you can add to your project-level composer.json), that applies cleanly, from grasmash's commit back in July:

https://github.com/acquia/blt/commit/7d69890a05d3dce91b01a91339a2b1e60fb24c54.diff

**Comment by acontia** [comment]
Hi.
This doesn't work for me. Looks like Composer is trying to apply the patch provided by BLT before applying the patch added to my project-level `composer.json`.

However, I have been able to solve this issue by adding to my project-level `composer.json` the following:

```
      "patches-ignore": {
          "drupal/core": {
              "Clear Twig caches on deploys": "https://www.drupal.org/files/issues/2752961-90.patch"
          }
      }
```
as per https://github.com/acquia/blt/issues/1379#issuecomment-397929494

**Comment by acontia** [comment]
This doesn't work for me. Looks like Composer is trying to apply the patch provided by BLT before applying the patch added to my project-level `composer.json`.

However, I have been able to solve this issue by adding to my project-level `composer.json` the following:

```
      "patches-ignore": {
          "drupal/core": {
              "Clear Twig caches on deploys": "https://www.drupal.org/files/issues/2752961-90.patch"
          }
      }
```
as per https://github.com/acquia/blt/issues/1379#issuecomment-397929494
