### ISSUE TITLE
Consider using webflo/drupal-core-require-dev

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3065]
Whenever core adds a new dev dependency, BLT has to track it, like here:
* https://github.com/acquia/blt/pull/3008
* https://github.com/acquia/blt/pull/1725

This is obviously kind of a pain. I just discovered the webflo/drupal-core-require-dev package, which claims to track all of core's dev dependencies as normal (`require`) dependencies.

I _think_ if we added this to BLT's `require-dev`, we could stop tracking all of the separate core dev dependencies, which would be really nice.

**Comment by ba66e77** [comment]
I haven't dug into the package you referenced, but I can get behind it in principle.

**Comment by ba66e77** [comment]
This was merged earlier today.
