### ISSUE TITLE
MemcacheLockFactory does not have a method 'getPersistent' from BLT memcache.yml

### ISSUE THREAD

**Issue by sugaroverflow** [acquia/blt#3089]
Hello 👋 

I was facing the same issue as #3074 was watching #3076 and #3079 as memcache.settings config changes were being made. 

I just updated to acquia/blt 9.16 from 9.15 hoping that the issue would be resolved, but am seeing a new memcache error.

 My system information:
* BLT version: 9.1.6

When I run this command:
```
drush status
```
or navigate to my site (white screen of `The website encountered an unexpected error. Please try again later and the following error output in the logs)

I get the following output:
```
ArgumentCountError: Too few arguments to function Drupal\memcache\MemcacheBackend::__construct(), 3 passed in /mnt/www/html/sitename/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 101 and exactly 4 expected in Drupal\memcache\MemcacheBackend->__construct() (line 64 of /mnt/www/html/sitename/docroot/modules/contrib/memcache/src/MemcacheBackend.php).
 [error]  Drush command terminated abnormally due to an unrecoverable error.
```

And I expected this to happen:
```
[success] Cache rebuild complete.
```

I was hoping this might be related to the previous issues with the memcache settings and that someone might be able to help me move forward. Thank you!

**Comment by ba66e77** [comment]
@sugaroverflow, can you check the version of `drupal/memcache` you have? On 9.1.6, we're [pinning to the alpha7 release](https://github.com/acquia/blt/blob/9.1.6/composer.suggested.json#L16) which has a constructor for the [MemcacheBackend class that takes 3 arguments](https://cgit.drupalcode.org/memcache/tree/src/MemcacheBackend.php?h=8.x-2.x&id=f30543ba2d991e5fd068963ebfe5bb00e163c818#n53). 

Looking at memcache's commit logs, it looks like a [commit was added yesterday that adds a 4th argument](https://cgit.drupalcode.org/memcache/commit/src/MemcacheBackend.php?h=8.x-2.x&id=3b645a4849c7689d8cd454e8de46e8cf232d6561). That change is in their beta1 release, though.

**Comment by sugaroverflow** [comment]
Thanks for your help @ba66e77 ! 

I noticed that even though BLT was pinning the alpha7 release for memcache, my `composer.json` was installing the 2x-dev. I fixed that - and was able to get the site to load and access backend admin pages. 

However, if I try to navigate to config/sync or some other pages, the page crashes and my Report log has: 

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Drupal\memcache\Lock\MemcacheLockFactory' does not have a method 'getPersistent' in Drupal\Component\DependencyInjection\Container->createService() (line 248 of /mnt/www/html/unacp4f8mxzabrzq/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php) 
```
and then:
```
TypeError: Argument 4 passed to Drupal\config\Form\ConfigSync::__construct() must implement interface Drupal\Core\Lock\LockBackendInterface, instance of stdClass given, called in /mnt/www/html/unacp4f8mxzabrzq/docroot/core/modules/config/src/Form/ConfigSync.php on line 161 in Drupal\config\Form\ConfigSync->__construct() (line 132 of /mnt/www/html/unacp4f8mxzabrzq/docroot/core/modules/config/src/Form/ConfigSync.php) 
```

Is this related to 
```
  lock.persistent:
    class: Drupal\Core\Lock\LockBackendInterface
```
in `blt/settings/memcache.yml` or to removing the ` 'lock.container'` from the settings file? 

Thanks for your help on this!

**Comment by sugaroverflow** [comment]
Hi @ba66e77 :)

I noticed that even though BLT was pinning the alpha7 release for memcache, my `composer.json` was installing the 2x-dev. I fixed that - and was able to get the site to load and access backend admin pages. 

However, if I try to navigate to config/sync or some other pages, the page crashes and my Report log has: 

```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Drupal\memcache\Lock\MemcacheLockFactory' does not have a method 'getPersistent' in Drupal\Component\DependencyInjection\Container->createService() (line 248 of /mnt/www/html/sitename/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php) 
```
and then:
```
TypeError: Argument 4 passed to Drupal\config\Form\ConfigSync::__construct() must implement interface Drupal\Core\Lock\LockBackendInterface, instance of stdClass given, called in /mnt/www/html/sitename/docroot/core/modules/config/src/Form/ConfigSync.php on line 161 in Drupal\config\Form\ConfigSync->__construct() (line 132 of /mnt/www/html/sitename/docroot/core/modules/config/src/Form/ConfigSync.php) 
```

Is this related to 
```
  lock.persistent:
    class: Drupal\Core\Lock\LockBackendInterface
```
in `blt/settings/memcache.yml` or to removing the ` 'lock.container'` from the settings file? 

Thanks for your help on this!

**Comment by sugaroverflow** [comment]
Hmm, dug a little deeper and noticed that `MemcacheLockFactory` doesn't actually have a `getPersistent` method  - so the error makes sense. 

Is there a reason BLT is trying to replace the default persistent lock here? was there one in memcache before?

**Comment by ba66e77** [comment]
Yeah, I'm seeing the same, @sugaroverflow. Trying to track down the root now, but from what I understand the memcache module has removed persistent locking. It may be that we just need to take that out of the memcache.yml.

**Comment by sugaroverflow** [comment]
@ba66e77 removing/commenting out the `lock.persistent` block in `memcache.yml` seems to fix the issue - I'm not seeing the error anymore.

**Comment by ba66e77** [comment]
I'm seeing the same, @sugaroverflow. Would you like to submit a PR to make that change?

**Comment by ba66e77** [comment]
I'm hearing from one of the folks involved with the memcache updates that we should take out all the locks. So remove the whole memcache.yml and the lines in memcache.settings.php that refer to it.

**Comment by sugaroverflow** [comment]
Made an attempt for the PR & issue summary, thanks for your help on this!

**Comment by loopy3025** [comment]
I had mine set to 2.0 and was getting this error. Switching to Alpha 7 helped me. I'll try switching it back to 2.0 in the next deployment.
