### ISSUE TITLE
Exemples files that ship with BLT should keep on being managed by BLT

### ISSUE THREAD

**Issue by anavarre** [acquia/blt#3091]
In 9.2.0-alpha2, a PHPUnit breakage happened on Acquia Pipelines due to `./tests/phpunit/ExampleTest.php` which required an updated class name as per the [PHPUnit 6.0.0 changelog](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0).

This file - like other example files - is added to BLT when it's first installed. Since it'll most likely be ignored by end users, it seems like it should be on BLT to keep on updating this file on behalf of customers. Alternatively, we should provide an upgrade path in the form of a warning and how-to for customers to update their files when required.

**Comment by ba66e77** [comment]
@anavarre, @danepowell's PR was just merged and will be in the next tagged release, expected end of this week.

**Comment by anavarre** [comment]
Glad to see this in, thanks @danepowell - However the scope of this issue was for **all** files that are initially provided by BLT, not only PHPUnit's Example file. Let's try and keep this in mind for when this occurs again in a different scenario.
