### ISSUE TITLE
blt sync is overwriting sites.php in multisite setup.

### ISSUE THREAD

**Issue by prophet108** [acquia/blt#3100]
My system information:
* Operating system type: MacOS
* Operating system version: High Sierra
* BLT version: 9.1.1

When I run this command:
```
blt sync --site=[mysitename]
```

my sites.php file gets replaced with a file which only has my local aliases in the $sites array.

And I expected this to happen:

sites.php file not change and continue to list all of my (12) site aliases.

**Comment by lpeabody** [comment]
This is also happening to us. It is replacing sites.php with all of our local aliases. Our project is an ACSF project which has the local site aliases stored in a pre-sites-php factory hook.

**Comment by lpeabody** [comment]
Updating to BLT 9.1.3 resolved my issue re: sites.php getting overwritten when it was being controlled by ACSF. Not sure if upgrading to 9.1.3 fixes this issue, it might be unrelated?

**Comment by prophet108** [comment]
I updated to BLT 9.1.7 and the issue seems to be fixed.

**Comment by danepowell** [comment]
Closing due to user reports of this being resolved in newer versions.
