### ISSUE TITLE
Update default.local.settings.php to tell Drupal to skip permissions hardening

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3106]
It's very frustrating to have Drupal "harden" the sites/default directory and settings.php file in a local dev environment by removing write access.

[Drupal 8 includes a way to disable this by a setting](https://www.drupal.org/project/drupal/issues/1232572), and even [includes it in their example local settings file](https://github.com/drupal/drupal/blob/8.6.x/sites/example.settings.local.php)

But BLT doesn't use that example file. Instead if provides its own template, which is missing that line.

**Comment by mikecrittenden** [comment]
I believe #3088 is the same issue.

**Comment by bkosborne** [comment]
@mikecrittenden possibly! I think in your case you mentioned that the files actually had owner-write permissions (644). But Drupal will actually remove write permissions from *everyone*, so if that was your problem you'd see the "default" folder without any write perms and the settings.php file without any settings perms. Either way it's worth adding this setting to your local settings file to see if it makes a difference.
