### ISSUE TITLE
DOCS: docs/testing refers to JMeter tests directory, however there is no further documentation

### ISSUE THREAD

**Issue by briantully** [acquia/blt#3122]
In the docs, https://blt.readthedocs.io/en/latest/testing/#test-directory-structure refers to a jmeter subdirectory. 

Is JMeter actually supported via BLT?

There is no additional documentation on executing a JMeter test via BLT, e.g., 

`blt tests:jmeter:run`

Perhaps there was a plan to integrate jmeter but it has yet to the implemented? If so we should remove the jmeter reference from testing.md.

If there is an initiative to integrate jmeter, I would highly recommend a pivot to integrate with Taurus (https://gettaurus.org) which an open source automated testing framework developed by Blazemeter. Much like BLT, Taurus is a YAML based DSL that supports JMeter, Selenium, and many other testing tools. Coupled with the Blazemeter Chrome Extension, it can be a very powerful yet simple way to add performance testing to your development workflow.

**Comment by mikemadison13** [comment]
@briantully i THINK that jmeter is only referenced here as a suggestion of where to place your tests (example only) but it's a good idea to update the docs to make that more obvious (or just remove jmeter). let me put in a PR and tinker with it and see what you think...
