### ISSUE TITLE
Allow disabling the warnings about modified "extra.installer-paths" coming from checkInstallerPaths()

### ISSUE THREAD

**Issue by mikecrittenden** [acquia/blt#3123]
We have the following in our `composer.json`:

```json
"docroot/libraries/{$name}": [
  "harvesthq/chosen",
  "type:drupal-library",
  "type:bower-asset",
  "type:npm-asset"
],
```

This is because doing it that way allows us to avoid having to add an entire `repositories` section as specified here: https://cgit.drupalcode.org/chosen/tree/README.txt?h=8.x-2.x#n26

This works fine, but causes BLT to complain. We now get this warning whenever we run `composer install`:

> Warning: The value for extra.installer-paths in composer.json differs from BLT's recommended values.

It doesn't seem possible to turn this warning off, and that would be nice for people who do intentionally decide to modify installer paths while understanding the risks and downsides involved.

**Comment by danepowell** [comment]
I can't reproduce this in BLT 10.x. I don't think those checks run any longer during `composer install`. If you can reproduce this on a fresh build of BLT 10.x feel free to reopen.
