### ISSUE TITLE
Multisite + ACSF solution for sites.php

### ISSUE THREAD

**Issue by mikecrittenden** [acquia/blt#3130]
It seems like right now there is no good solution for this combination. ACSF requires a very specific `sites.php`, which means that we can't edit that file for local URL mappings. I see some PRs and issues mentioning moving to a `local.sites.php` file for the local URL mapping, but it seems that they have all either been closed or reverted for various reasons.

Is there a good answer here?

**Comment by mikecrittenden** [comment]
At the moment I have a local `sites.php` and then a separate `acsf.sites.php`, and this command hook which renames `acsf.sites.php` to `sites.php` before committing, when generating the artifact.

```
  post-deploy-build:
    dir: ${deploy.dir}/docroot/sites
    command: rm sites.php && cp acsf.sites.php sites.php
```

This works but it's a hack.

**Comment by lpeabody** [comment]
What works for us very nicely is if you add a pre-sites-php hook, we call ours local-sites.php, and include all of your local site mappings in there. To prevent this from going out to Acquia, we simply exclude it from the artifact. This is a line from blt/deploy-exclude-additions.txt:

```
# Remove local site mappings file.
factory-hooks/pre-sites-php/local-sites.php
```

sites.php is still invoking pre/post-sites-php hooks locally, so we take advantage of this fact while ensuring that the file just never exists when deployed to ACSF.

**Comment by danepowell** [comment]
Let's consolidate discussion around the management of sites.php in #3477
