### ISSUE TITLE
Mojave + Drupal VM NFS Timeout

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3131]
**Quick PSA.....**
It looks like Mojave doesn't just work with DrupalVM out of the box.  It will hang on connecting to NFS.  Mojave changed the security model for applications:  

**Work Around**
In System Preferences -> . Security and Privacy -> Privacy -> Full Disk Access 
you will need to add iterm or terminal.

See thread here for more information:
https://github.com/hashicorp/vagrant/issues/10234#issuecomment-424305964

cc: @lcatlett, @ba66e77

**Comment by ba66e77** [comment]
Thanks for flagging that, Adam.

**Comment by geerlingguy** [comment]
@aweingarten - Correction, it looks like this is _only_ an issue if you use iTerm. If you use Terminal, it correctly pops a permissions dialog when Vagrant attempts the exports file change. iTerm should do the same, and there's a bug report requesting as much: https://gitlab.com/gnachman/iterm2/issues/7182

So this isn't an issue if you use the stock Terminal on Mojave.

**Comment by mikemadison13** [comment]
thanks @aweingarten !

**Comment by ba66e77** [comment]
I encountered this with PHPStorm, where a dialog popped up saying PHPStorm wanted to administer the computer.
