### ISSUE TITLE
Trivial grammar fix "In future, please.."

### ISSUE THREAD

**Issue by ashabed** [acquia/blt#3149]
Just ran blt vm and noticed a typo. Figured I might as well submit a PR to fix it.

```
-      $this->say("In future, run <comment>vagrant up</comment> to boot the VM.");
+      $this->say("In the future, run <comment>vagrant up</comment> to boot the VM.");
```
and
```
-      $this->say("Drupal VM is already configured. In future, please use vagrant commands to interact directly with the VM.");
+      $this->say("Drupal VM is already configured. In the future, please use vagrant commands to interact directly with the VM.");
```

**Comment by ashabed** [comment]
https://github.com/acquia/blt/pull/3150

**Comment by grasmash** [comment]
https://www.btb.termiumplus.gc.ca/tpv2guides/guides/favart/index-eng.html?lang=eng&lettr=indx_titls&page=9VorV7jvi51w.html

**Comment by danepowell** [comment]
This isn't really a typo, but just a British / American English difference. From that link:
> in future "is British English, perhaps through direct translation of the Latin phrase in futuro or perhaps because of the British English pattern of usage without the definite article <she’s in hospital>." In contrast, Garner notes, "American English uses the definite article."

BLT already uses American English everywhere I can find (color, license, etc...), and I think it's best to be consistent. See #3150.
