### ISSUE TITLE
Best practice for adding new config splits

### ISSUE THREAD

**Issue by mikecrittenden** [acquia/blt#3162]
In my case, I need to add a `test` environment config split. 

Should I just add them to `settings.php` right after the `blt.settings.php` include? Right before? Somewhere else?

**Comment by wu-edward** [comment]
You can do your environment split logic either in any `sites/settings/*.settings.php` file or `sites/[SITE_DIR]/settings/includes.settings.php`, which are included after BLT's `config.settings.php` file.
See the `vendor/acquia/blt/settings/blt.settings.php` file for more details.

**Comment by mikemadison13** [comment]
@mikecrittenden please reopen if you have additional questions!

**Comment by mikecrittenden** [comment]
Thanks! In my case the splits were for ACSF rather than local, so I ended up putting them in `factory-hooks/post-settings-php/config.php`.
