### ISSUE TITLE
Git Caching For CI that Lacks Caching Layers

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3165]
So this is a crazy idea.  Might be a bad one.  (Shrug)

Currently BLT based builds average 8-12 minutes on Acquia pipelines. A major chunk of this time is spent downloading composer and NPM dependencies. Caching could trim significant time from that build time. Other CI/CD implement caching.
- https://docs.travis-ci.com/user/caching/
- https://circleci.com/docs/2.0/caching/

**Unfortunately Acquia Pipelines is behind competing services and does not offer caching.**   A work around might be to use git itself as a cache.  In theory git will be faster than downloading the individual dependencies 1 by 1.  

**Quick idea of how this could work:**
When the main integration branch, lets say `master` is built it can push items into the git cache.
```
- git clone git@github.com:aweingarten/my-repo.git -b composer-cache --single-branch git-build-cache
- cp -r ~/.composer ${SOURCE_DIR}/git-build-cache/.composer
- cp -r ~/.npm ${SOURCE_DIR}/git-build-cache/.npm
- cp -r ~/.nvm ${SOURCE_DIR}/git-build-cache/.nvm
```
    These might include node and composer caches.  

When feature branches are building they can check the PR and see if it touches node or composer.  If it does then the cache will be invalidated.  BTW this invalidation technique should help solve random caching issues that will arise and could be applied to services that do have caching support. If not it might do something like this:

```
- git clone git@github.com:aweingarten/my-repo.git -b composer-cache --single-branch git-build-cache
- mv ${SOURCE_DIR}/git-build-cache/.composer ~/.composer
- mv ${SOURCE_DIR}/git-build-cache/.npm ~/.npm
- mv ${SOURCE_DIR}/git-build-cache/.nvm ~/.nvm
```

thoughts?

@grasmash, @lcatlett, @danepowell, @ba66e77

**Comment by danepowell** [comment]
It's a clever idea, but I'd love to see some hard data on exactly how much time this could save before proceeding with an implementation. I'd also like to see if caching is on the feature horizon for any of these services (i.e. Pipelines).

An informal profile that I did on Pipelines:
> 1m initializing Pipelines container and environment
1m composer install
1m PHP and twig linting
2m npm install and build
5m site install
1m starting server, preparing behat tests
12m Behat tests
2m container / environment teardown

So it seems like the most time we could save is ~2m on a ~30m test. Any savings are good, but I'm not sure if it's worth the complexity if that's all we're saving.

**Comment by aweingarten** [comment]
@danepowell your profiling got me thinking what if we made our builds smarter?  Forget pipelines for a second.  What if all builds were based on what actually changed rather than doing the same thing over and over.   Right now the are pretty dumb.

When we start a build we could do something like
```
function calculate_pr_changes()
{
  $has_php_changes;
  $has_composer_changes;
  $has_fe_changes;
  $has_behat_changes;

  if(has_php_changes){
     do_php_cs();
  } 
  if(has_composer_changes){
     do_composer_stuff();
  } 
  if(has_fe_changes){
     do_fe_node_stuff();
  } 
}
```
With a little intelligence, in most builds we could shave 3 minutes with minimal risk.    We could probably also solve some of the quirks of caching across CI systems in the process.  If we did this correctly needing to manually flush a travis cache would be a thing of the pass

**Comment by danepowell** [comment]
I think at some point you will always need the ability to trigger a "clean" build and/or clear caches, and unfortunately Pipelines just doesn't have that integration right now. Anything we could do to fix that in BLT would be a workaround at best.

Closing for now but I'll put it in the parking lot in case Pipelines changes make this feasible.
