### ISSUE TITLE
On demand/Conditional blt:front-end execution on CI

### ISSUE THREAD

**Issue by naveenvalecha** [acquia/blt#3167]
There are some CI which lacks caching layers for caching the npm and composer.
This is a bit of a crazy idea. **Skip the front-end build when there is no change in themes.**

We have a customer who is using ACE with Acquia Cloud CD(Pipelines + CDE/ODE). The customer is using Domain access to power 7 of their websites with 7 different themes from a single codebase. On CI, the frontend build process(npm install, npm run build) for each theme every time when a PR gets raised. It takes >20 minutes to build the CDE environment corresponding to a pull request.

We have noticed the pull requests which doesn't have theme related changes, more than 10 minutes are going into the front end process for the themes which is not required in this case.

Technical idea:
- Extract the Changed files from the git. Verify if there are theme changes.
- if there are theme changes, perform the front end process otherwise skips it.

thoughts?
@grasmash, @lcatlett, @danepowell, @ba66e77 @jayakrishnanj

**Comment by wu-edward** [comment]
I believe that if you don't run the frontend build, compiled CSS files will be missing from the artifact.

**Comment by ba66e77** [comment]
Yeah, by default the sites/*/files directory is gitignored from the source repo.  You could take that out of .gitignore I suppose, but then you have to contend with that git diff.
