### ISSUE TITLE
500 error on loading a drupal 8 view page with all records in local BLT VM. 

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#3168]
My system information:
* Operating system type: Ubuntu VM
* Operating system version: ubuntu1604
* BLT version: 8.9.x-dev

Output of `blt doctor`:
```
No error on running `blt doctor`.
```
This is an existing VM. Seems it's kind of memory issue.

The Issue not occurring on our Acquia Dev server, it's happening on local blt drupal vm. The VM is not able to handle when there are more number of records to load, it's loading fine with 100 records.

Tried increasing vagrant memory & php_max_post_size value in `local.config.yml`.
vagrant_memory: 5036
php_post_max_size: "512M"

The above changes got reflected on running `vagrant reload --provision`

In my config.yml the php memory value is `php_memory_limit: "2G"`

Could anyone please help on this?

**Comment by ba66e77** [comment]
That certainly _sounds_ like a memory limit issue, but are you actually seeing memory limit errors thrown in the logs?

**Comment by sandipsmarty** [comment]
I am not seeing any backtrack information from dblog & apache log.

**Comment by mikemadison13** [comment]
@geerlingguy  any thoughts on what else might be needed here other than upping memory and php_post_max_size?

**Comment by mikemadison13** [comment]
@sandipsmarty have you tried upping php_max_execution_time to 300? I believe that is what is setup in the acquia cloud.

**Comment by sandipsmarty** [comment]
@mikemadison13 : Yes, I tried increasing php_max_execution_time to 300 also, but it didn't resolve the issue.

**Comment by geerlingguy** [comment]
It really depends on what's going on—is it a POST request that's failing? If there's a 500 error, there must be some information in an Apache log; inside the VM, go to `cd /var/log/apache2`, and run `tail -f *.log`, then go load the page where you get that error again. It should drop a new log entry saying something, hopefully. It's pretty rare Apache prints that error but doesn't store any log for it.

**Comment by sandipsmarty** [comment]
It's actually a GET request. I see the following log messages when loading the page. But same codebase is running on all instances of Acquia cloud without any error.

`==> error.log <==
[Tue Nov 13 06:10:08.926003 2018] [proxy_fcgi:error] [pid 7794:tid 140027535288064] [client 192.168.32.1:53686] Premature end of script headers: index.php
[Tue Nov 13 06:10:08.926048 2018] [proxy_fcgi:error] [pid 7794:tid 140027535288064] [client 192.168.32.1:53686] AH01070: Error parsing script headers
[Tue Nov 13 06:10:08.926053 2018] [proxy_fcgi:error] [pid 7794:tid 140027535288064] (22)Invalid argument: [client 192.168.32.1:53686] AH01075: Error dispatching request to : 

==> other_vhosts_access.log <==
local.belize.com:80 192.168.32.1 - - [13/Nov/2018:06:09:36 +0000] "GET /map?type=partner_accomodation HTTP/1.1" 500 218 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"`

I was suspecting if there is any issue with my codebase for this 500 error, wondering if it is so then how it's running on Acquia cloud environments. Not getting any clue for the log message `Premature end of script headers: index.php`.

**Comment by sandipsmarty** [comment]
@geerlingguy: This fix https://github.com/geerlingguy/drupal-vm/issues/1517 resolves the issue.
