### ISSUE TITLE
Add Additional ACSF Utility Commands

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3170]
There are a few utility scripts / commands in the ACSF module, some being hidden from the default `drush list` output, that will be helpful in various BLT tasks such as creating a new multisite locally and pre-commit hooks. Since some ACSF tasks need to run without bootstrapping drupal, the user must include additional arguments on the cli to use them which can be tedious. At first glance the following commands from the module would be helpful additions: 

- acsf-init-verify
- acsf-uninstall
- acsf-version-get
- acsf-info

**Comment by mikemadison13** [comment]
FYI the acsf-init-verify command has been added via https://github.com/acquia/blt/issues/3217

**Comment by danepowell** [comment]
This isn't on the roadmap, so closing for now. We can always reopen later if it becomes necessary to solve other issues.
