### ISSUE TITLE
Twig linting failing on valid syntax

### ISSUE THREAD

**Issue by mikecrittenden** [acquia/blt#3178]
Twig linting is complaining about syntax that seems perfectly fine.

Here's the error:

```
 ERROR  in /opt/atlassian/pipelines/agent/build/docroot/themes/custom/particle/apps/drupal/templates/block/block--login-form.html.twig (line 42)
      40             {{ drupal_block('user_login_block') }}
      41           {% elseif is_employer %}
  >>  42             {{ drupal_entity('block', 'particle_employersmenu', check_access=false) }}
  >> Unknown arguments "0", "1", "check_access" for function "drupal_entity()". 
      43           {% elseif is_intern %}
      44             {{ drupal_entity('block', 'particle_internsmenu', check_access=false) }}
```

That syntax is taken from here and it works fine: https://www.drupal.org/docs/8/modules/twig-tweak/rendering-blocks-with-twig-tweak#block-configuration-entity

Is this a linting bug?

**Comment by wu-edward** [comment]
Are drupal_block and drupal_entity custom or contrib Twig functions? You need to whitelist them if so. 

https://blt.readthedocs.io/en/latest/extending-blt/#teststwiglintall

**Comment by mikecrittenden** [comment]
They are whitelisted (see below). Note that the error isn't complaining about undefined functions, it just doesn't like the arguments.

```
validate:
  twig:
    filters: [rgba_string, luma, field_value, field_raw]
    functions:
      [
        drupal_block,
        drupal_field,
        drupal_view,
        drupal_block,
        drupal_region,
        drupal_entity,
        drupal_field,
        drupal_menu,
        drupal_form,
        drupal_image,
        drupal_token,
        drupal_config,
        drupal_title,
        drupal_url,
        drupal_link,
        drupal_messages,
        drupal_breadcrumb,
      ]
```

**Comment by wu-edward** [comment]
OK, I found the issue was the way BLT handled whitelisting filters and functions did not account for named arguments correctly.

**Comment by amitchell-p2** [comment]
Just to note if anyone else runs into this before it is rolled in: in twig you can provide null for arguments you want to skip using the 'none' keyword. 
In this case, calling those same functions in this form (based on function signature) will pass linting:
`{{ drupal_entity('block', 'particle_employersmenu', none, none, false) }}`

**Comment by dpagini** [comment]
This was helpful to me, thanks @amitchell-p2!!
