### ISSUE TITLE
Add checks for Deprecated Functions

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3179]
Just like we do phpcs checks and linting we should probably add a scan for deprecated Drupal functions to make sure our builds can transition to Drupal 9 smoothly:

Was thinking of maybe going with:
https://github.com/sensiolabs-de/deprecation-detector

Anyone have any other better ideas for detection approaches?

See:
https://dri.es/drupal-7-8-and-9
https://www.drupal.org/core/deprecation

**Comment by mikemadison13** [comment]
@aweingarten this is something that I know @grasmash  played with a bit back when we were starting on 9.x we'll definitely want this to be something that can be toggled so it isn't running at all times. doing a complete deprecation pass on every commit hook and blt validate call slowed down commit times to drag into the several minute range.

**Comment by aweingarten** [comment]
Sensio looks like its installed but I don't think its catching things.  Will investigate further

**Comment by aweingarten** [comment]
@mikemadison13  I gave your comment some thought we could potentially limit the deprecation scan to the files changed in a PR.

**Comment by danepowell** [comment]
There's also this tool:
http://hojtsy.hu/blog/2018-dec-17/how-automate-testing-whether-your-drupal-8-module-incompatible-drupal-9

I'm not sure how it relates to the sensiolabs one.

**Comment by danepowell** [comment]
Open PR, needs work: #3386

**Comment by danepowell** [comment]
Closing since the associated PR was closed. While this isn't on the BLT development roadmap, it still sounds like a cool feature and we'd love to have it if anyone gets around to finishing the PR. Although it might be better suited as a plugin.
