### ISSUE TITLE
Composer Security Scans

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3206]
As a site architect I want to know that my composer.lock does not have vulnerabilities.  

Considering adding a blt command to wrap something like this:
https://github.com/sensiolabs/security-checker

Anyone have better approach or solution before we start building it?

cc @CashWilliams, @grasmash, @lcatlett

**Comment by CashWilliams** [comment]
I thought this was already in use, but not seeing it - https://github.com/Roave/SecurityAdvisories

**Comment by aweingarten** [comment]
@CashWilliams 
https://github.com/Roave/SecurityAdvisories
Only kicks and screams when you add new stuff.  It doesn't help you if you have a valid lock file already.  

This does.
https://github.com/sensiolabs/security-checker 


Coincidentally they use the same data-source: https://github.com/FriendsOfPHP/security-advisories
