### ISSUE TITLE
Move location of secrets file to take advantage of acquia-files

### ISSUE THREAD

**Issue by eporama** [acquia/blt#3219]
https://github.com/acquia/blt/blob/15d06f71f8b34d23107dd705c0050991f310d866/settings/blt.settings.php#L177

This should probably be outside of the home directory. 

We should take advantage of the `../acquia-files` directory which is consistent across all environments and if dev/stage share the same server, the directory will be distinct.

**Comment by bkosborne** [comment]
I second this. The current place BLT wants you to put them is a bit strange.

**Comment by bkildow** [comment]
Reading in secrets as is seems to be broken for me. The location it's trying to include from seems to be missing the `$_ENV['AH_SITE_ENVIRONMENT']` portion of the path as seen here: https://docs.acquia.com/resource/secrets/#secrets-settings-php-file.

**Comment by bkosborne** [comment]
@bkildow Those Acquia docs are not aligned with BLT. The Acquia docs don't assume you're using BLT, so they are independent of what BLT does for loading a secrets file.

**Comment by danepowell** [comment]
The BLT method is aligned with the older recommendation, it looks like that has changed. I'll submit a PR to update it. It will only apply to 10.x since it's a breaking change.
