### ISSUE TITLE
port PR #3215 to 10.x

### ISSUE THREAD

**Issue by ba66e77** [acquia/blt#3225]
We need to port the patch applied in #3215 to the 10.x branch.

**Comment by briantully** [comment]
I don't think this patch is necessary due to the fact that the `trusted_reverse_proxy_ips` variable introduced by @lcatlett in #3172 only affected the 9.2.x branch. If #3172 gets ported to 10.x then yes we'd need to apply #3215 this as well.

**Comment by mikemadison13** [comment]
@lcatlett does this need to be done or are we good?
