### ISSUE TITLE
Git commit message validation could use better UX

### ISSUE THREAD

**Issue by briantully** [acquia/blt#3236]
My system information:
* Operating system type: Mac
* Operating system version: OS X 10.13.6
* BLT version: 9.2.x

When I run this command:
```
git commit -a -m "BLT-000: This is my commit message"
```

I get the following output:
```
Your local code has passed git pre-commit validation.
Executing .git/hooks/commit-msg...
Validating commit message syntax...
[error]  Invalid commit message!
Commit messages must conform to the regex /(^BLT-[0-9]+(: )[^ ].{15,}\.)|(Merge branch (.)+)/
[notice] To disable this command, see http://blt.rtfd.io/en/9.x/readme/extending-blt/#git-hooks
[notice] To customize git hooks, see http://blt.rtfd.io/en/9.x/readme/extending-blt/#setupgit-hooks.
```

And I expected this to happen:
Either for the commit to succeed or for the error message to have more helpful information regarding the error, perhaps a human readable description and/or an example?

**Comment by stuartabrown** [comment]
This is happening to me to and I don't get it.  I've read through https://github.com/acquia/blt/issues/2582 and have added
`git:
  hooks:
    commit-msg: false`

to build.yml but it makes no difference.  What can I do?

**Comment by mikemadison13** [comment]
@stuartabrown you may need to do line breaks to disable the commit message:

```
git:
  hooks:
    commit-msg: false
```

worst case scenario, you can manually remove the commit-msg hook from .git/hooks. 

in the example above, the period is missing (which is why the commit hook failed the commit).

**Comment by capysara** [comment]
There's a little more detail [here](https://support.acquia.com/hc/en-us/articles/360012455413-BLT-Installation-Time-saving-tips-tricks): 

Add this snippet right underneath git.remotes configurations in the blt/blt.yml file.

```
hooks:
     commit-msg: false
     pattern: false
```
And then initiate the config change: 
`blt blt:init:git-hooks`
