### ISSUE TITLE
The "deploy.build-dependencies" option does not work as expected

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3239]
My system information:
* Operating system type: OSX
* Operating system version: 10.13.6
* BLT version: 9.2.1

The [build-dependencies option](https://github.com/acquia/blt/blob/9.2.x/config/build.yml#L56) is available as a way to allow workflows where dependencies are committed to your main development repository, and as such should be copied to the build artifact along with other source files, instead of being re-built.

However, the [implementation of this option](https://github.com/acquia/blt/blob/9.2.x/src/Robo/Commands/Deploy/DeployCommand.php#L363) is not right. If you set it to true, then it won't even copy your source files to the artifact at all.

Setting this value to true shouldn't have any effect on the `buildCopy` method, but instead it should prevent `composerInstall` from doing anything.

Note that I don't personally use this option, but I was auditing the code that that's run when BLT does an artifact deploy and noticed this bug.

**Comment by danepowell** [comment]
Just to clarify, I think you meant to say that if you set the build-dependencies option to _false_ it will not copy any files at all. _true_ is the default value and will copy files and run composer install.

That aside, you're right, it looks like this is a bug from when the deploy commands were ported to Robo: #1457

If you look at the original Phing tasks, they only used this setting to bypass composer install.
