### ISSUE TITLE
BLT private files path is broken for multisite

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3242]
BLT 9.x and 10.x both [set the Acquia private files path](https://github.com/acquia/blt/blob/10.0.x/settings/filesystem.settings.php#L17) to `/mnt/files/$ah_group.$ah_env/files-private`.

This doesn't play nice with multisite, since they'd all be using the same private files path.

I think it should instead be changed to point to `/mnt/files/$ah_group.$ah_env/sites/$site_dir/files-private` - a directory that Acquia already maintains for all sites. This would obviously be a BC break for sites that let BLT configure the private files path for them already, so maybe it would have to be in 10.x only with a prominent release note.

**Comment by mikemadison13** [comment]
@lcatlett any thoughts on this?

**Comment by danepowell** [comment]
I'm going to go with the official Acquia docs on this: https://support.acquia.com/hc/en-us/articles/360005307793-Setting-the-private-file-directory-on-Acquia-Cloud
