### ISSUE TITLE
BLT Deploy dry run issues

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3243]
When I run this command:
```
blt artifact:deploy -D deploy.dryRun=true
```

I get the following output:
My site was deployed.

And I expected this to happen:
The artifact to be generated, but not deployed.

**Proposed Fixes**
It would appear that the deploy command is expecting dry-run to be set (see https://github.com/acquia/blt/blob/10.0.x/src/Robo/Commands/Deploy/DeployCommand.php#L42) and the docs are instructing users to pass dryRun. This may just be a matter of updating the docs to be correct, or the feature itself may need some additional work.

Docs here: https://github.com/acquia/blt/blob/10.0.x/docs/deploy.md#debugging-deployment-artifacts

**Comment by forrest-livengood** [comment]
This looks like it's just a documentation issue. Dry runs work with the --dry-run flag.

Under "Debugging deployment artifacts" in the docs (https://blt.readthedocs.io/en/latest/deploy/#debugging-deployment-artifacts)

This command doesn't work as expected:
blt artifact:deploy -D deploy.dryRun=true

And should be changed to this which works as a dry run:
blt artifact:deploy --dry-run
