### ISSUE TITLE
Include settings.local.php in addition to local.settings.php

### ISSUE THREAD

**Issue by timcosgrove** [acquia/blt#3246]
Drupal 8.6 changes the recommended name of the local settings file: https://cgit.drupalcode.org/drupal/tree/sites/example.settings.local.php#n10

It would probably be best to load both versions for the time being, since undoubtedly people will keep `local.settings.php` around in some cases.

Opened https://github.com/acquia/blt/pull/3244 and https://github.com/acquia/blt/pull/3245 for this.

**Comment by danepowell** [comment]
By way of historical explanation... BLT came about when the naming convention for this file was still up in the air, but it looked like it would land on `local.settings.php` in Drupal 8.0: https://www.drupal.org/node/1118520

Unfortunately it went the other way. So I don't think this is a recent change, it's just a holdover from way back. There's actually a push to get it back to `local.settings.php` but it doesn't have much traction: https://www.drupal.org/project/drupal/issues/2419213

**Comment by danepowell** [comment]
I like the idea of getting inline with core on this. The only problem is that _all_ of BLT's settings files follow the `foo.settings.php` naming pattern. For consistency, if we're going to make the switch, we should change them all to `settings.foo.php`. That's a pretty big change, so I'd like to think about it some more and let folks provide input. Seems most appropriate for a 10.x release.

**Comment by danepowell** [comment]
Actually, Drupal core itself is inconsistent here in that it has default.settings.php and settings.local.php. So most of BLT is inline with core's pattern of default.settings.php, foo.settings.php, etc. It's just settings.local.php that's an outlier in Drupal core.

I'm of the opinion that Drupal core is in the wrong here in terms of the naming of settings.local.php, and will hopefully fix this in D9 in https://www.drupal.org/project/drupal/issues/2419213

I don't want to expend a ton of effort to switch to `settings.local.php` only to have to switch _back_ for D9, so I think we should keep doing what we're doing, and optionally support core's version of the naming for people that (for whatever reason) want to use it.
