### ISSUE TITLE
On Acquia Cloud, acquia_config.php should better handle multisite

### ISSUE THREAD

**Issue by anavarre** [acquia/blt#3255]
Currently, BLT ships with `acquia_config.php` and recommends:

```
elseif (getenv('AH_SITE_ENVIRONMENT')) {
(snip)
 $config['baseurlpath'] = 'simplesaml/';
```

However, in a multisite environment with `simplesamlphp/simplesamlphp:1.16.2` and `simplesamlphp/saml2:3.2.2`, it seems we don't have a choice but to change the code to do this instead:

```
elseif (getenv('AH_SITE_ENVIRONMENT')) {
(snip)
 $config['baseurlpath'] = $protocol . $_SERVER['HTTP_HOST'] . $port . '/simplesaml/';
```

Otherwise, port **443** will be missing from the URL and give a permission denied. The [SAML Chrome Panel](https://chrome.google.com/webstore/detail/saml-chrome-panel/paijfdbeoenhembfhkhllainmocckace) extension can help with confirming this issue.

Considering we are in a multisite, was this expected? Why wouldn't the BLT config file ship with this OOTB setup, then?

cc/ @thomashowell

**Comment by lcatlett** [comment]
The configuration provided by BLT in acquia_config.php and elsewhere is already multisite aware by default: 

https://github.com/acquia/blt/blob/9.2.x/scripts/simplesamlphp/acquia_config.php#L52

There is a comment above this config which calls out that config['baseurlpath'] needs to be overridden:

```
/**
 * Support multi-site and single site installations at different base URLs.
 *
 * Override $config['baseurlpath'] = "https://{yourdomain}/simplesaml/"
 * to customize the default Acquia configuration.
 */
```

I realize this is somewhat obscure and BLT users may not be reading comments fully - do you have any suggestions on how to improve docs or default config to prevent the challenges you ran into?

**Comment by anavarre** [comment]
> The configuration provided by BLT in acquia_config.php and elsewhere is already multisite aware by default

Correct, but the thing is it's on each team to understand that the code should be added under `elseif (getenv('AH_SITE_ENVIRONMENT'))` for things to work okay. As an example, we did read this and did understand it was needed in a multi-site env. But what we didn't understand initially is it had to be moved around for the port to be passed in the URL.

Wouldn't an improvement be to enforce this line by default, where it's supposed to be?

**Comment by danepowell** [comment]
@anavarre or @lcatlett since you seem to understand what's necessary here, can you please submit a PR? I don't have access to an environment with SAML to test with so I can only rely on your judgement here.

**Comment by anavarre** [comment]
@danepowell created a PR based on what worked for us, which might not be the fix you want in BLT.
