### ISSUE TITLE
Support for drupal/memcache 2.0.0 (stable)

### ISSUE THREAD

**Issue by christopher-hopper** [acquia/blt#3257]
My system information:
* Operating system type: Ubuntu
* Operating system version: 16.04LTS
* BLT version: 9.1.x, 9.2.x

Acquia BLT does not support the current stable `drupal/memcache:^2.0.0` (8.x-2.0). This has been noted previously in #3220 with the following response:

@lcatlett said:
> BLT currently locks to the 2.0-alpha7 version of the memcache module because Acquia does not yet recommend that customers update to 2.0.

Acquia has recommended we update to `drupal/memcache:^2.0@stable` package to address issues with memcache we are seeing on the Acquia Cloud Enterprise platform. I note that some Acquia documentation has contrary advice. 

## Suggested Solution

- Provide updated BLT settings for the stable `drupal/memcache:^2.0.0` (8.x-2.0).
- Backport these settings to earlier BLT versions.
- Update BLT documentation where necessary.

**Comment by mikemadison13** [comment]
@christopher-hopper let me try and chase down some internal confirmation on memcache 2.0.

**Comment by christopher-hopper** [comment]
I guess you'll be doing it at some point in the future. The bottom line is that the services/classes/settings are now stable in memcache 2.0, so at some point you'll need to update BLT settings to match. When that day comes, the PRs above and this issue are a starting point. 

I'm using the settings above in BLT 9.1 and BLT 9.2 on two different projects in Production. So far so good.

**Comment by danepowell** [comment]
Thanks for the feedback, and for opening the PRs as a reference, they may be useful when it comes time to upgrade in the future. For now though, I am closing this set of issues since BLT is aligned with Acquia's general recommendation of using Memcache 2.0-alpha7.
