### ISSUE TITLE
10.0.x branch unusable

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#3267]
It doesn't seem to be possible to create a project with the 10.0.x branch of BLT at present:

```
$ composer create-project --stability=dev --no-interaction acquia/blt-project my-project
Installing acquia/blt-project (10.0.x-dev 20d504b785faded8579c313cb007edc1606320d4)
  - Installing acquia/blt-project (10.0.x-dev 20d504b): Cloning 20d504b785 from cache
Created project in my-project
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for acquia/blt 10.0.x-dev -> satisfiable by acquia/blt[10.0.x-dev].
    - acquia/blt 10.0.x-dev requires drupal/config_split ^1.0.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by grasmash** [comment]
This is because an update has not been pushed to acquia/blt-project. Instructions are here:

https://github.com/acquia/blt/blob/10.0.x/RELEASE.md#update-the-blt-project-repo

**Comment by greylabel** [comment]
Related: https://github.com/acquia/blt-project/issues/30

**Comment by mikemadison13** [comment]
Experimenting with this locally, it seems like if I add the following into the blt-project composer.json file, then it works fine. Could you test @TravisCarden ? 

```
"repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
}
```

Unclear why this hasn't been a problem for 9.2.x???

**Comment by mikemadison13** [comment]
Would love some feedback on https://github.com/acquia/blt-project/pull/31 to see if anyone has thoughts.

**Comment by TravisCarden** [comment]
@mikemadison13 If I'm testing it correctly, it solves the problem for me!

**Comment by mikemadison13** [comment]
@grasmash i'm not sure in this context why we would need to actually update blt-project, there is no 10.x release of BLT, just the dev version.

rather, i think what is happening here is that the lack of the composer merge plugin stuff in BLT 10.x is causing the context for the Drupal packagist to get lost. As soon as I added it into the blt-project's composer.json, things immediately began working again. @greylabel can you see if this fixes your issue? if so, i can close this issue on the BLT boards and merge the PR on the blt-project side.

**Comment by greylabel** [comment]
`composer create-project acquia/blt-project:10.0.x-dev --no-interaction my-project`

Works as expected now. Thanks.

**Comment by mikemadison13** [comment]
of course, and sorry for the delay on the other project... i apparently wasn't watching it so i missed your issue going in.

**Comment by greylabel** [comment]
No worries. I meant to fix it myself after opening the issue, but didn't get around to it.

**Comment by grasmash** [comment]
The update method that I referenced earlier would have resolve this issue in the same way. It remains a task that should be done.

10.x includes blt-project as a subtree. It’s necessary to pull in the correct dev dependencies from the blt-require-dev project, which is also a sub tree.

**Comment by grasmash** [comment]
This PR makes the required changes: https://github.com/acquia/blt-project/pull/32

**Comment by sonvir249** [comment]
@greylabel it should be `composer create-project acquia/blt-project:10.x-dev --no-interaction my-project `
