### ISSUE TITLE
Deploy .gitignore does not include managed files symlink

### ISSUE THREAD

**Issue by rumyanar** [acquia/blt#3272]
I'm currently using BLT version: 9.2.0

In Issue https://github.com/acquia/blt/issues/1839 scripts/blt/deploy/.gitignore was changed to ignore `/docroot/sites/*/files/` instead of `docroot/sites/*/files`.
Adding the trailing slash means that only the contents of the files folder are ignored, but not the folder itself. Unfortunately in production environments it's common to have a symlink to a shared files directory, instead of files folder, and the symlink shows as untracked file on the server after deploy.

I believe that should be reverted back to `docroot/sites/*/files` as in `template/.gitignore`.

The same issue applies to private files directory.

**Comment by dpagini** [comment]
I'm just reading this in passing, but you cannot commit an empty folder with git, so it would seem `files` and `files/` would essentially do the same thing... no? Maybe b/c the folder already exists in your repository or something? I could be wrong on this, but that thought just jumped in my head as I read this...

**Comment by rumyanar** [comment]
In case it is a folder, you are correct. Git does not care about folders.
However it's possible to be a symlink file to a folder, and in that case git shows it as an untracked file.
