### ISSUE TITLE
Fails at "blt Project Create"

### ISSUE THREAD

**Issue by vaibhavjain-in** [acquia/blt#329]
Hey guys,

Not sure if this is the right platform to ask queries, but I am trying to follow the instructions in Readme, and the build fails for me. Here is what it says.
```
blt > create-project:

Initialized empty Git repository in /Applications/MAMP/htdocs/meetup/.git/
     [echo] Updating composer dependencies, this make take a while...
    1/1:       	https://packagist.drupal-composer.org/p/provider-latest$e81c1472c23f34a7915fd5bc49908317172883c9c5690e01950e03a319a08ca5.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)


  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "./vendor/acquia/blt/blt.sh create-project" exceeded the timeout of 300 seconds.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

```

I am sure that Xdebug is disabled, but it still shows, Xdebug warning. Also Max execution time is set to 3000, but it says 300. I am using MAMP, and everything else on my machine works absolutely perfect. PHP Paths are correct too. I have no clue why it fails.

**Comment by grasmash** [comment]
Can you please share the output of `php -i`?

**Comment by vaibhavjain-in** [comment]
@grasmash Here you go -> http://pastebin.com/0QFj8cGU

**Comment by grasmash** [comment]
Thanks.

According to your output, you do have xdebug enabled. You need to disable it in `/Applications/MAMP/bin/php/php5.6.10/conf/php.ini`.

MAMP has a separate php.ini file for PHP CLI.

**Comment by grasmash** [comment]
@vaibhavjain-in Can you confirm this resolved the issue?

**Comment by grasmash** [comment]
you can also increase your composer timeout by running `export COMPOSER_PROCESS_TIMEOUT=2000` beforehand. This has been added to the documentation.

**Comment by vaibhavjain-in** [comment]
Hey @grasmash, Sorry for the delayed reply. I have had a chance to quickly check it, and it works good. I will check again, and post if I come up with anything.
Thanks for your response. 👍
