### ISSUE TITLE
 ! [rejected]        branch-name -> branch-name (non-fast-forward)

### ISSUE THREAD

**Issue by jonketo** [acquia/blt#3306]
My system information:
* Operating system type: macOS
* Operating system version: Mojave 10.14.2
* BLT version: 9.2.0-alpha3
* Git version: 2.15.2 (Apple Git-101.1)

I am having an issue running the same deployment over and over without pulling in new code. I expect I can run a deploy over and over without changes and the remote will be updated with the same code.

When I run this command (the first time):
```
lando blt -vvv artifact:deploy --branch=branch-name
```

I get the following output (the first time):
```
...
   54f995f..416ff28  branch-name -> branch-name
[ExecStack] Done in 3.258s
19:09 total time elapsed.
```

At this point the remote has a new branch that I can point my dev environment to. Without pulling any new code I would expect to rerun the command and update the remote again. I have needed to run in order to run the deployment again. Should this file be in my .gitignore file as well?

```
git checkout deployment_identifier
```

When I run this command (the second time):
```
lando blt -vvv artifact:deploy --branch=branch-name
```

I get the following output (the first time):
```
...
 ! [rejected]        branch-name -> branch-name (non-fast-forward)
error: failed to push some refs to '<repo>'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

And I expected this to happen:
I expected the branch to be updated again rather than rejected. The same behavior occurs when doing a git pull to merge in latest. I am uncertain whether this is a problem with not rebasing at some point or something else. I am inclined to create new repos and start over if there is not an easy solution.

Thanks

**Comment by mikemadison13** [comment]
My assumption of what is going on here is that you are pushing the same commit into the same branch, which is going to fail unless you do a -f (which BLT doesn't do). You might try cutting a new tag instead?

**Comment by jonketo** [comment]
Yes, same commit into same branch. I assumed the a commit could be redeployed to an environment with no changes without any issue, but I guess not. We are currently not using tagging, but if need be will begin to use tagging.

Thanks!
