### ISSUE TITLE
Multi-sites should not have their own "default" versions of config files

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3316]
My team is developing a multi-site distro and I'm trying to get my head around the best way to provision additional multisites.

Running `blt recipes:multisite:init` creates a bunch of files in the multisite folder that we don't need:

1. `settings/default.local.settings.php` - The default local settings file from the main "default" site should be used instead
1. `default.local.drush.yml` - Same as above, use the version from "default" site
1. `default.services.yml` - Same as above
1. `default.settings.php` - Same as above

Initially I just removed them all, but when I run `blt drupal:sync --site=mymultisitename`, a sub-command `blt:init:settings` is run, and it re-creates many of them.

I may have to overwrite some of the BLT commands to adjust this, but I would of course like to avoid that since future refactorings of BLT may break my changes.

I wonder if there's something that BLT can add that changes this behavior of creating all these defaults for each multisite?

**Comment by dpagini** [comment]
I have had these same thoughts with BLT multi-site.  👍

**Comment by danepowell** [comment]
I get the desire for a cleaner directory structure for simple multisites, but I imagine that would really limit users that need to have unique settings per site. For instance, each site may need its own trusted host patterns in `settings/default.local.settings.php`, or its own CORS definitions in `default.services.yml`.

Additionally, especially for new users, I don't think it would be at all intuitive where the local files are being generated from, if not from default files in the same directory.

Of course I could be wrong, but those are just my hunches. Unless the presence of those files is actively breaking something, or you can point to a way to do this cleanly without impacting users that need per-site customization, I'm inclined to maintain the status quo.

@mikemadison13 do you work with multisites much? Any thoughts?

**Comment by danepowell** [comment]
Since I haven't gotten any additional feedback I'm going to close this. Like I said, if there's a compelling use case I'd be happy to reconsider but I just don't see what that is, or how to do this in a way that meets everyone's needs without introducing substantial complexity.
