### ISSUE TITLE
BLT does not support syncing a remote db locally unless a local db already exists

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3317]
This is on BLT 9.2.3.

When syncing a remote database to local environment, and no local database exists yet, then the command will fail.

Command: `blt drupal:sync:db --site=registrar`:

```
> source:build:composer
Could not scan for classes inside "/var/www/html/princeton/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/html/princeton/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/html/princeton/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/html/princeton/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/html/princeton/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/html/princeton/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/html/princeton/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer/
> blt:init:settings
Hash salt already exists.
> drupal:sync:db
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/html/princeton/vendor/bin/drush cache-clear drush --uri=registrar --no-interaction --ansi &&
 /var/www/html/princeton/vendor/bin/drush sql-drop --uri=registrar --no-interaction --ansi &&
 /var/www/html/princeton/vendor/bin/drush sql-sync @registrar.prod @registrar.local --target-dump=/tmp/tmp.target.sql.gz --structure-tables-key=lightweight --create-db --uri=registrar --no-interaction --ansi &&
 /var/www/html/princeton/vendor/bin/drush sql-sanitize --uri=registrar --no-interaction --ansi &&
 /var/www/html/princeton/vendor/bin/drush cr --uri=registrar --no-interaction --ansi &&
 /var/www/html/princeton/vendor/bin/drush sqlq "TRUNCATE cache_entity" --uri=registrar --no-interaction --ansi in /var/www/html/princeton/docroot
 [success] 'drush' cache was cleared.

In SqlCommands.php line 118:

  Unable to drop database. Rerun with --debug to see any error message.


sql:drop [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--database [DATABASE]] [--target [TARGET]] [--db-url DB-URL] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command>

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 1.064s
[error]  Command `drupal:sync:db ` exited with code 1.
```

The problem is that BLT is running the drush command `sql-drop` before it runs `sql-sync`, and `sql-drop` errors out if the database you're trying to drop tables on does not exist.

I understand why BLT is performing the drop, but I think it needs some extra handling here to account for the fact that the local DB may not yet exist.

I think this is important for a multi-site dev workflow. I'd love to be able to tell our devs to just run `blt drupal:sync` without first having to worry about creating the database.

For now, I'm using a "before" hook to create the database if it doesn't already exist.

Note this is similar to the problem I ran into with `blt drupal:install`: https://github.com/acquia/blt/issues/2814

**Comment by lpeabody** [comment]
Doesn't the --create-db flag on the sql:sync make the sql:drop unnecessary?

**Comment by bkosborne** [comment]
I don't think so, because the idea is that you want a completely clean database before syncing. Otherwise some local database tables that exist locally but not remotely will stick around even after running the import.

**Comment by lpeabody** [comment]
I think it's best to just remove the sql:drop during a sync, no? This is what Drush generates for me during a `drush sql:create`, which gets invoked by `drush sql:sync` when passed --create-db:

```
DROP DATABASE IF EXISTS `commercial`; CREATE DATABASE `commercial` /*!40100 DEFAULT CHARACTER SET utf8 */;
```

So, running `sql:drop` prior to `sql:sync --create-db` is unnecessary since `sql:sync --create-db` will always drop the database first if and only if it exists. I think the logical conclusion is to remove the `sql:drop` step, yes?

**Comment by grasmash** [comment]
Yes.

**Comment by lpeabody** [comment]
@grasmash I think you're mistaking this issue for a Reddit thread ;) PR #3321  opened.

**Comment by malikkotob** [comment]
I've seen odd things happen without an explicit `sql-drop`. On occasion, I've even had to run `sql-drop` manually prior to running `blt sync` - I just haven't had a chance to investigate/explore why that is.
