### ISSUE TITLE
sample code in Acquia cloud & factory hook files should be commented out

### ISSUE THREAD

**Issue by joachim-n** [acquia/blt#3318]
I've had problems with ACSF which turned out to be because the codebase's factory hooks folder has a file in it that's identical to BLT's scripts/factory-hooks/post-settings-php/includes.php.

I'm assuming these files got automatically copied by some sort of setup process. In which case, the sample code should be commented out, so it doesn't run when copied to the live location.

**Comment by mikemadison13** [comment]
@joachim-n the factory hooks get copied out of the blt directory into your project root when running `recipes:acsf:init:hooks.` That directory does not exist by default, and should only be created if you plan on using the default factory hooks.

Was there something in particular that you felt should be commented out, or were you confused as to why the factory hooks were there and running in general?

**Comment by joachim-n** [comment]
I'd say given the number of hook files that get copied across, all of their active code should be commented out. This would at the very least save the developer time, and would prevent the situation I found on my project, where the file post-settings-php/includes.php was changing the config directory locations and thus breaking things.

**Comment by joachim-n** [comment]
The way I got this to work in the acquia/blt case was with:

```
composer update acquia/blt typhonius/acquia-php-sdk-v2
```

-- explicitly asking composer to update the problematic dependency as well. But having to specify dependencies like this sort of goes against the point of a package manager!

**Comment by lcatlett** [comment]
this config was fixed in BLT 9.2.2 in #3231. This and an [additional bugfix](https://github.com/acquia/blt/pull/3205) in BLT 9.2.2 for the BLT update hook which automatically refreshes the factory hook template files via the `blt recipes:acsf:init:hooks` command has already been backported to 9.1.9 in #3289.

**Comment by joachim-n** [comment]
I don't see the file in question being changed in https://github.com/acquia/blt/pull/3231/files.

It's also not commented-out in the latest 9.2.x.
