### ISSUE TITLE
Allow specifying the rsync "mode" option for drush rsync via config

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3320]
Running BLT 9.2.3

It would be nice if BLT had the option to provide different "mode" arguments to the [drush rsync command](https://github.com/acquia/blt/blob/10.0.x/src/Robo/Commands/Sync/SyncCommand.php#L67).

By default, drush will run rsync with the "archive" flag set, which will attempt to preserve file ownership and groups after copying the files. This caused problems for me when syncing files from Acquia into a Docker container that uses NFS. I kept getting "operation not permitted" errors when rsync attempted to `chown` the files during `blt drupal:sync:files`.

My fix was to replace the BLT command with my own:

```
  public function syncFiles() {
    $remote_alias = '@' . $this->getConfigValue('drush.aliases.remote');
    $site_dir = $this->getConfigValue('site');

    $task = $this->taskDrush()
      ->alias('')
      ->uri('')
      ->drush('rsync')
      ->arg($remote_alias . ':%files/')
      ->arg($this->getConfigValue('docroot') . "/sites/$site_dir/files")
      ->option('exclude-paths', implode(':', $this->getConfigValue('sync.exclude-paths')))
      ->option('mode', 'rzltv --no-perms --chmod=ugo=rwX');

    $result = $task->run();

    return $result;
  }
```

Would be nice if BLT just made the "modes" argument a config option.

**Comment by danepowell** [comment]
I'm not sure how broadly useful this would be, since we don't yet officially support running BLT with Docker and I've never seen a similar request before. A PR would be welcome, but right now this isn't on our roadmap to implement. Thanks for reporting it though.
