### ISSUE TITLE
Ensure $acsf_site_name is a valid machine name for config_split.

### ISSUE THREAD

**Issue by dlopez-akalam** [acquia/blt#3323]
My system information:
* Operating system type: Ubuntu (vagrant, drupal-vm)
* Operating system version: 16.04.5
* BLT version: 9.2.0

in `settings/blt/blt.settings.php` there is the following code calculating the acsf_site_name for local environment
```
if ($is_acsf_inited) {
  if ($is_local_env) {
    // When developing locally, we use the host name to determine which site
    // factory site is active. The hostname must have a corresponding entry
    // under the multisites key.
    $input = new ArgvInput($_SERVER['argv']);
    $config_initializer = new ConfigInitializer($repo_root, $input);
    $blt_config = $config_initializer->initialize();

    // The hostname must match the pattern local.[sitename].com, where
    // [sitename] is a value in the multisites array.
    $domain_fragments = explode('.', $_SERVER['HTTP_HOST']);
    $name = array_slice($domain_fragments, 1);
    $acsf_sites = $blt_config->get('multisites');
    if (in_array($name, $acsf_sites)) {
      $acsf_site_name = $name;
    }
  }
}
```
Where the sitename is token raw from the domain name. After that, the site name is used to activate a config split with this machine name, resulting in a potentially invalid machine name: local.my-site.com for example will take "my-site" as acsf_sitee_name. It should be transformed in a valid machine name like my_name.

**Comment by dlopez-akalam** [comment]
#3324

**Comment by dlopez-akalam** [comment]
Created Pull Request

**Comment by lcatlett** [comment]
@dlopez-akalam - what version of BLT are you seeing this issue on? `settings/blt/blt.settings.php` no longer uses this approach or config in both BLT 9 and 10.x, as this was addressed via the bugfixes and settings/multisite config updates in #3297 and #3231. Please try updating to BLT 9.2.2 or later to validate if this has been fixed and I will reopen this issue to investigate further.
