### ISSUE TITLE
NPM management of deployed front-end libraries

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#333]
BLT supports managing NPM dev dependencies via a theme's package.json file. You can easily define frontend hooks in project.yml that will install these dependencies during the build process. The libraries themselves (in node_modules) then get stripped before deployment (they are specifically excluded by BLT and also in the .gitignore in the deploy artifact.)

This is problematic for third-party frontend libraries that _should_ be deployed, such as select2. Right now you can still add these as non-dev dependencies to your project.yml and run npm install --no-dev as a post-deploy hook, but the gitignore will still exclude them.

**Comment by grasmash** [comment]
Let's not gitignore them then.

**Comment by danepowell** [comment]
Yeah that should do the trick.
