### ISSUE TITLE
New PHPUnit features make BLT internal tests unstable.

### ISSUE THREAD

**Issue by grasmash** [acquia/blt#3346]
@greylabel We're getting frequent failures after merging https://github.com/acquia/blt/pull/3249. 

There are two issues I see:

* The log output has become too long to to view in browser. We need to make it less verbose. 
* Test builds fail with `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` This may be an issue with the new tests failing to kill background processes, or simply taking too long.

This is a beta blocker. We'll need to either resolve it quickly or else revert and refactor.

**Comment by greylabel** [comment]
@grasmash I can look into these early next week or maybe this weekend, feel free to revert it that does not work for your timeline.

2. Can you link an example of a failing build?

**Comment by grasmash** [comment]
https://travis-ci.org/acquia/blt/builds/484043913?utm_source=github_status&utm_medium=notification

**Comment by grasmash** [comment]
Opening a PR to revert here: https://github.com/acquia/blt/pull/3348

**Comment by greylabel** [comment]
@grasmash Do you know offhand of any differences in the way travis runs on PR vs merge that could be causing the timeout issues -- I haven't seen these come up in PR runs previously?

**Comment by greylabel** [comment]
@mikemadison13 @danepowell Either of you have thoughts on my last question as well?

**Comment by greylabel** [comment]
Hm. I can't immediately spot any differences in the matrix or config for a [build that times out](https://travis-ci.org/acquia/blt/builds/482994605?utm_source=github_status&utm_medium=notification) vs [one that completes successfully](https://travis-ci.org/acquia/blt/builds/485215140?utm_source=github_status&utm_medium=notification). The only other thing I can think of is that PRs run with different security configurations when made by non-committers.

**Comment by greylabel** [comment]
Any addition insight on this would be appreciated.
