### ISSUE TITLE
Devel Update

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3355]
The devel module is pinned to version 1.x in the BLT suggested json file, and 1.x is no longer supported.

A temporary fix is to manually include drupal/devel: ^2 in your composer.json file.

BLT should fix this by upping the version constraint to ^2. see https://github.com/acquia/blt/blob/9.2.x/composer.suggested.json#L14

@wu-edward notes that the php execution has been removed from the base devel module. I personally believe that devel_php should NOT be included by default with BLT, because there is nothing stopping individual projects from including it. 

I notice that devel isn't included at all in the composer.json for BLT 10.x. (https://github.com/acquia/blt/blob/10.0.x/composer.json) Was this intended @grasmash / @danepowell ?

**Comment by mpodorov** [comment]
What about 9.2.x version of BLT?

**Comment by mikemadison13** [comment]
i'll get a backport. thanks @mpodorov !
