### ISSUE TITLE
Fatal error during cache rebuild due to registered MemcacheBackendFactory.php path

### ISSUE THREAD

**Issue by hctom** [acquia/blt#3357]
My system information:
* Operating system type: Drupal VM
* Operating system version: Debian 9
* BLT version: 9.2.3

When I run this command:
```
drush cr
```

I get the following output:
```
Failed to log error: Warning: stat(): stat failed for phar:///usr/local/bin/drush/bin/modules/contrib/memcache/src/MemcacheBackendFactory.php in TYPO3\PharStreamWrapper\PharStreamWrapper->invokeInternalStreamWrapper() (line 453 of /var/www/ghc09ev/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php).
```

The Drush launcher ist installed as PHAR inside the Drupal VM by default and since the upgrade to 8.6.6/8.6.7 it gives me this error when rebuilding caches via Drush.
Of course this is not a direct BLT bug, but it is caused by the way, BLT registers the memcache PSR4 class path in its `memcache.settings.php` file:

```php
$class_loader->addPsr4('Drupal\\memcache\\', 'modules/contrib/memcache/src');
```
I investigated this a little and found that the following would solve the issue:
```php
$class_loader->addPsr4('Drupal\\memcache\\', DRUPAL_ROOT . '/modules/contrib/memcache/src');
```
I'd appreciate to see this changed soon ;)

Thanx in advance!

**Comment by danepowell** [comment]
Upstream issue: https://www.drupal.org/project/memcache/issues/3038440
