### ISSUE TITLE
hooks/readme.md out of sync with acsf

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3389]
My system information:
* BLT version: 10.0.0 Beta 2

After updating to Beta 2 and the hooks get regenerated, the readme.md file is out of sync with blt tests:acsf:validate.

```
blt tests:acsf:validate
Validating ACSF settings...
[Acquia\Blt\Robo\Tasks\DrushTask] Running /vendor/bin/drush @self --include=modules/contrib/acsf/acsf_init acsf-init-verify --no-interaction --ansi in /docroot
 [error]  The file README.md is out of date. 

In AcsfInitCommands.php line 344:
                                                                               
  Please run drush acsf-init to correct these problems and commit the resulti  
  ng code changes.                                                             
                                                                               

acsf-init-verify [--skip-default-settings [SKIP-DEFAULT-SETTINGS]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command>

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 0.4s
[error]  Failed to verify ACSF settings. Re-run acsf-init and commit the results. 
```

we need to ensure that hooks/readme.md is updated to reflect what the acsf module will pass, as opposed to what we have in our repository.

**Comment by mikemadison13** [comment]
@lcatlett can you tell me why acsf init verify is testing a readme file in the cloud hooks directory???

**Comment by grasmash** [comment]
Can we just remove this file from BLT and allow ACSF to generate it?

**Comment by mikemadison13** [comment]
i'm open that that, although that means that there won't be a readme file there for ACE sites.

**Comment by lcatlett** [comment]
@mikemadison13 - acsf is checking for the file because it has acsf-specific documentation that is relevant to the Cloud Hooks acsf-init provides, calling out that Cloud Hooks are not supported on ACSF as they are in ACE and links to docs.acquia.com: https://cgit.drupalcode.org/acsf/tree/acsf_init/lib/cloud_hooks/README.md?h=8.x-2.x#n9. 

I believe using standard Acquia Cloud hooks also provide a readme which overwrites this file

**Comment by mikemadison13** [comment]
ok, then even more i think it makes sense for this file to go away on the BLT side so that it isn't conflicting with ACSF / ACE. any concern there @lcatlett ?
