### ISSUE TITLE
Integration of Drupal Test Traits

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/blt#3393]
While Behat has been a preferred Behavioral test suite of choice, we now have the possibility of using Moshe Weitzmann's Drupal Test Traits:

https://gitlab.com/weitzman/drupal-test-traits

Would this be a preferred approach to Behat?

**Comment by danepowell** [comment]
Drupal Test Traits certainly sound interesting, but it's not in the roadmap at this time. If there were enough demand, obviously we'd reconsider.

This might also be a good candidate for a BLT plugin, now that composer packages can provide their own commands.

**Comment by bharath-kondeti** [comment]
@danepowell , Is there any update on the Integration of Drupal Test Traits with Blt. If yes, is there any documentation present for the implementations.

**Comment by lpeabody** [comment]
@bharath-kondeti I mean, technically Drupal Test Traits are PHPUnit tests. BLT already supports PHPUnit. What specifically needs to be done to support DTT besides supporting running PHPUnit tests themselves?
