### ISSUE TITLE
Drupal Core Critical Security Release: PSA-2019-02-19

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3395]
The Drupal Security team has notified the community of a highly critical security release that will drop today -- https://www.drupal.org/psa-2019-02-19.

Once Drupal 8.6.10 is released (and Lightning 3.2.6) execute the following command to update your codebase. 

*For BLT 9.2.x and 10.x:*
```composer update webflo/drupal-core-require-dev acquia/lightning --with-all-dependencies```

*For BLT 9.x and before*
```composer update drupal/core acquia/lightning --with-all-dependencies```

**Comment by hugovk** [comment]
> _For BLT 9.2.x and 10.x:_
> `composer update webflo/drupal-core-require-dev acquia/lightning --with-all-dependencies`
> 
> _For BLT 9.x and before_
> `composer update drupal/core acquia/lightning --with-all-dependencies`

Should it be `acquia/blt` instead of `acquia/lightning`?

**Comment by mikemadison13** [comment]
@hugovk no, you don't have to update blt to apply the security update (unless you are on a SUPER old version of blt). i've suggested the lightning update above because they released a new version yesterday as well, but it's non-critical.

**Comment by hugovk** [comment]
OK, thanks for clearing it up. Was a bit confused as Lightning isn't part of BLT and we don't have it.

**Comment by mikemadison13** [comment]
@hugovk it's part of the recommended packages for blt and is the standard profile, but yeah for sure it's not required.

**Comment by aweingarten** [comment]
@mikemadison13 
1: Thank you for this PSA.  Its hugely helpful to many people.  These updates can be rough.  I think this is a first and its a great innovation.

2: Wondering if for next time if the instructions should be more granular?  So we aren't super cool and were behind lightning a bit and that update triggered a bunch of other updates.  In our case we have the test coverage and it was fine.  However, I'm thinking maybe other teams will not be so fortunate. Something like 
`composer update webflo/drupal-core-require-dev drupal/core --with-all-dependencies`

Regardless,
Well done!

**Comment by mikemadison13** [comment]
probably a good call to omit lightning explicitly!
