### ISSUE TITLE
BLT @ Drupalcon

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3396]
_Sorry, an "issue" may not be the most appropriate place for this... but wasn't sure where else to post a topic like this._

Wondering if there's any plans for BLT at Drupalcon? I know in year's past it's been part of some sessions. If there are any sessions on the tool planned for this year, it might be nice to list them out? Or if any of the contributors are doing sessions on another topic?

What about interest in a meet-up or something along those lines? I'm sure a lot of people know each other on here, but it would be great to put some faces to names. Thoughts?

**Comment by mikemadison13** [comment]
we should totally have an informal meet up if nothing else!

**Comment by mikemadison13** [comment]
@dpagini i just scheduled a BOF - https://events.drupal.org/seattle2019/bofs/acquia-blt-build-and-launch-tools-meetup

**Comment by dpagini** [comment]
That's awesome, great idea, thanks Mike!

**Comment by cosmicdreams** [comment]
I'm at that BOF now.  Good talk.

**Comment by dpagini** [comment]
Assume we can close? Thanks for organizing Mike! It was great to meet everyone.
