### ISSUE TITLE
Config Import Can not delete the default language - language.entity.en error

### ISSUE THREAD

**Issue by justinlevi** [acquia/blt#3403]
BLT 9.2.3

Working from a custom installation profile, no matter what I tried, after doing the intial `blt setup` followed by a `drush cex`, when I then ran a `blt setup` again, I'd get the following error:

```
Can not delete the default language
```

<details>
<summary>Full Error</summary>

In ConfigurableLanguage.php line 170:
                                                              
  [Drupal\language\Exception\DeleteDefaultLanguageException]  
  Can not delete the default language                         
                                                              

Exception trace:
 () at /Users/justinwinter/Sites/labor.ny.gov/docroot/core/modules/language/src/Entity/ConfigurableLanguage.php:170
 Drupal\language\Entity\ConfigurableLanguage::preDelete() at /Users/justinwinter/Sites/labor.ny.gov/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php:394
 Drupal\Core\Entity\EntityStorageBase->delete() at /Users/justinwinter/Sites/labor.ny.gov/docroot/core/lib/Drupal/Core/Entity/Entity.php:398
 Drupal\Core\Entity\Entity->delete() at /Users/justinwinter/Sites/labor.ny.gov/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php:873
 Drupal\Core\Config\ConfigImporter->checkOp() at /Users/justinwinter/Sites/labor.ny.gov/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php:591
 Drupal\Core\Config\ConfigImporter->processConfigurations() at /Users/justinwinter/Sites/labor.ny.gov/docroot/core/lib/Drupal/Core/Config/ConfigImporter.php:496
 Drupal\Core\Config\ConfigImporter->doSyncStep() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php:237
 Drush\Drupal\Commands\config\ConfigImportCommands->doImport() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/includes/drush.inc:232
 drush_call_user_func_array() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/includes/drush.inc:223
 drush_op() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php:208
 Drush\Drupal\Commands\config\ConfigImportCommands->import() at n/a:n/a
 call_user_func_array() at /Users/justinwinter/Sites/labor.ny.gov/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /Users/justinwinter/Sites/labor.ny.gov/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /Users/justinwinter/Sites/labor.ny.gov/vendor/consolidation/annotated-command/src/CommandProcessor.php:178
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /Users/justinwinter/Sites/labor.ny.gov/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:302
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /Users/justinwinter/Sites/labor.ny.gov/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /Users/justinwinter/Sites/labor.ny.gov/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /Users/justinwinter/Sites/labor.ny.gov/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /Users/justinwinter/Sites/labor.ny.gov/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/drush.php:66
 require() at /Users/justinwinter/Sites/labor.ny.gov/vendor/drush/drush/drush:4

</details>

My solution was to extend the `ConfigCommand` and set the `language.entity.en` to the uuid on disk. I tried to do this via the `pre-config-import` hook but couldn't get that to fire for some reason. 

Wondering if there is a better way to handle this and/or if anyone knows why I'm getting this issue? 

```
<?php

namespace Acquia\Blt\Custom\Commands;

use Acquia\Blt\Robo\Commands\Setup\ConfigCommand;
use Symfony\Component\Yaml\Yaml;

/**
 * Defines commands in the "setup:config*" namespace.
 */
class ConfigImportCommand extends ConfigCommand {

  /**
   * Imports configuration from the config directory according to cm.strategy.
   *
   * @hook replace-command setup:config-import
   */
  public function import() {

    $cm_core_key = $this->getConfigValue('cm.core.key');
    $exported_language_uuid = $this->getExportedLanguageUuid($cm_core_key);

    $this->say("Setting database language.entity.en uuid to what's on disk $exported_language_uuid");

    if ($exported_language_uuid) {
      $this->taskDrush()
        ->stopOnFail()
        ->drush("cset language.entity.en uuid $exported_language_uuid")->run();
    }
    parent::import();

  }

  /**
   * Returns the language UUID stored in exported configuration.
   *
   * @param string $cm_core_key
   *   The Core Key.
   *
   * @return null
   *   Return null
   */
  protected function getExportedLanguageUuid($cm_core_key) {
    $language_config_file = $this->getConfigValue('docroot') . '/' . $this->getConfigValue("cm.core.dirs.$cm_core_key.path") . '/language.entity.en.yml';
    if (file_exists($language_config_file)) {
      $language_config = Yaml::parseFile($language_config_file);
      $language_uuid = $language_config['uuid'];

      return $language_uuid;
    }

    return NULL;
  }

}

```

Previously I handled this situation with an install hook in a custom module, but that doesn't seem to trigger at the right time in this new project I'm working on. 

```
/**
 * Implements hook_install().
 *
 * Performs actions to set up the site for this profile.
 *
 * @see system_install()
 */
function [CUSTOM_MODULE]_install_install() {

    $endbanner = "\n\r============ END WEBNY INSTALL SCRIPT ============ \n\r\n\r";
    $startbanner = "\n\r============ START WEBNY INSTALL SCRIPT ============ \n\r\n\r";

    echo $startbanner;

    $sync = \Drupal::service('config.storage.sync');
    $langs = [
        'language.entity.en',
        'language.entity.und',
        'language.entity.zxx',
    ];
    foreach ($langs as $lang) {
        if ($sync_lang = $sync->read($lang)) {
            $config = \Drupal::configFactory()->getEditable($lang);
            $config->set('uuid', $sync_lang['uuid']);
            $config->save();
        }
    }

...

}
```

**Comment by mikemadison13** [comment]
have you tried allowing config overrides at the blt level?

**Comment by wu-edward** [comment]
I think what @mikemadison13 says is on track, but it's actually more of a general UUID mismatch issue with all config.

Presumably the config/install files in your custom profile do not have UUIDs. When Drupal installs the site, when the config is installed using the profile, Drupal generates a UUID for each.

After site install, blt runs a configuration sync from config/default, with config files exported from your previous install, but the UUIDs for each config are likely not going to match. This results in configuration sync process deleting the existing config and recreating config from sync.

When `language.entity.en` config is getting deleted, the error occurs.

Workarounds are either to add the UUIDs from the files in sync storage (config/default or the splits) to the UUIDs for the same configs in your custom profiles config/install. (Assuming your profile isn't a distribution).

Alternatively, you can try using a patch based on this PR: https://github.com/acquia/blt/pull/3241 so that BLT can use the functionality introduced in D8.6 to install from existing configuration.

**Comment by wu-edward** [comment]
Addendum: Another possibility is to install `config_ignore` in your profile, and have `config_ignore.settings` in the profile config/install include an entry to ignore all uuids, probably something like this:
`*:uuid`

**Comment by danepowell** [comment]
Closing due to lack of response

**Comment by laurentiu1981** [comment]
> Addendum: Another possibility is to install `config_ignore` in your profile, and have `config_ignore.settings` in the profile config/install include an entry to ignore all uuids, probably something like this:
> `*:uuid`

This does not seem to work, at least not with language.entity.en:uuid added for config_ignore
