### ISSUE TITLE
BLT Opinionated: Drupal Development Tool Selection

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3407]
BLT has been defaulted to DrupalVM for some time.  We have benefited from a single consistent stack with BLT.  Some advantages of the standard development stack:
- Standard domain to solve problems in 
- Save developer from themselves working on bare metal.  Protects team from getting into 3 day holes troubleshooting.  
- Common setup for Xhprof, XDebug.

 There are a lot of emerging solutions for local development stacks:
- DrupalVM
- Lando
- DDEV
- Docksal
- Vanilla Docker

Given that the community is aligning behind DDEV does it make sense for us to evaluate removing DrupalVM in favor of DDEV?
https://www.drupal.org/project/ideas/issues/2965681

cc: @geerlingguy, @grasmash, @unn

**Comment by aweingarten** [comment]
Please note there are some performance concerns with Docker based solutions on Mac.  Anecdotally DrupalVm seems faster than Docker on mac.

**Comment by unn** [comment]
There has been some limited work to get BLT going using DDEV.  See drud/ddev#1033

If nothing else, we know it works. As for switching the defaults, clearly not my call, but happy to help, if required.

**Comment by mikemadison13** [comment]
I don't think the plan is to switch the default in the immediate future. Drupal VM has played a pivotal role in BLT for a long time and the integration there cannot be disputed.

Having said that, obviously more teams and more people in the Drupal community are moving towards Docker based solutions and I know there is a desire to have more tightly coupled integrations between BLT and those locals. BLT can have a single preferred, or a couple of preferred integrations and people will still, largely, do whatever the heck they want :) 

I agree @aweingarten that having a single 'preferred' option makes sense and I don't want to make things more complex than needed. But if we are going to explore new options, sooner or later we have to introduce new options and and see how they function.

**Comment by geerlingguy** [comment]
Just to add a note: Drupal VM has no intention of transitioning to a Docker-based platform, and will likely remain a Vagrant/VirtualBox-based tool. There are plenty of Docker local dev tools/environments/scaffolds that are already mature enough and robust enough that I don't think it would do anyone any favors to try to pivot Drupal VM in that direction.

Drupal VM does have limited Docker support (and can be made to work okay-ish using only Docker), but it's not a first-class experience, it's nowhere near as flexible as the native Drupal VM toolset, and it's also slower in most cases.

Anyways, FWIW I have started using my own docker-compose-based local dev environments for all my non-Acquia projects. It's more lightweight and flexible, and doesn't require me to run a bunch of other stuff (extra CLI tool to learn, extra binaries, extra routing containers that have to run in background all the time, etc.) just to run a local development environment.

I'm not necessarily saying that's the direction BLT should go, but it seems every month or so, another Drupal agency tosses their own new Docker-based local dev solution out into the ether (most with little community adoption).

My main consideration in terms of _BLT_ choosing a new default is:

**Will the new default tool commit to maintenance, long-term stability, etc., or will it need a lot of hand-holding between releases?**

It seems some of the tools have a Node.js-like mentality of "rebuild everything every version" and that leads to all users having to recreate all their custom commands/integrations, rejigger all their config files, and spend a lot of time having to think about their dev tools (and less time working on their Drupal sites).

**Comment by aweingarten** [comment]
So I realize that docker is a trendy word.  What do people hope to gain from a docker based development system vs a monolith like DrupalVM?

**Comment by mikemadison13** [comment]
elite status points obviously.

**Comment by mikemadison13** [comment]
but seriously... mostly i'm looking at Acquia customers and partners who want to (or regularly do) use a docker based solution. i don't want the answer to be "support BLT yourself if you don't use Drupal VM." and i think to accomplish this, we need to have a slightly tighter coupling of BLT with these other tools. that doesn't necessarily mean we get away from having a standard solution, but it does mean we may need to wade deeper than we have before into other solutions.

Part of the value of BLT is that it should work in most VM solution spaces, and I'd love to see the adoption continue to grow. Being more flexible may be a way to accomplish this (I hope).

**Comment by dpagini** [comment]
I made a similar point in #1793... but I would also throw the option out there that instead of going from Drupal-VM to DDEV, or adding a 2nd tool, what if BLT abandoned a default development stack, and separated that responsibility into a supporting library, `blt-tools-drupal-vm` for example.

The existing Drupal-VM imp could be ported to a new library, suggested by default, or required in the next release and eventually suggested by composer. All the same commands would exist, and it would provide a template for any other dev tool to provide an implementation for BLT. So Docksal could come along and provide `blt-tools-docksal` or something like that. Most of these packages would ultimately be very lightweight, and provide a lot of flexibility, leaving core BLT to be just a little more focused.

**Comment by aweingarten** [comment]
@dpagini, 
What you suggest makes a lot of sense in terms of the recipes and allowing choice.  

To Quoteth @lcatlett 
> Is there a compelling reason to manage this in BLT and not contribute a BLT recipe or plugin to lando as has been done with the [docksal addon](https://github.com/docksal/addons/tree/master/blt)?

That being said there should probably be a default recipe so that we don't fragment too much.

**Comment by danepowell** [comment]
There's no immediate plan to add support for environments other than DrupalVM to the core BLT product, but Acquia may support containerized development environments in some other way. I know many community members have integrated Lando with BLT, and if you want to redistribute a Lando / DDev integration you should be able to do so now using a composer package that provides BLT command plugins.

**Comment by shelane** [comment]
And the docs that are part of this repo but no longer on readthedocs have information on how to use an alternate dev environment. I know it has Docksal and also Lando docs.

**Comment by danepowell** [comment]
The documentation you reference still exists. It hasn't been taken down, just moved: https://docs.acquia.com/blt/install/alt-env/

**Comment by cosmicdreams** [comment]
Now it's this? https://support.acquia.com/hc/en-us/articles/360047166273-Configuring-Acquia-BLT-with-Lando

**Comment by emb03** [comment]
I am using BLT Robo commands (that I didn't author). What work is necessary to move off of DrupalVM to lando, it seems none of the drupalVM images support php 8?

**Comment by mikemadison13** [comment]
it's pretty straight forward, actually. I maintain a BLT Lando plugin - https://github.com/mikemadison13/blt-lando. 

The biggest challenges you'll face are with regards to the VM itself. So, you'll need to make sure that the database settings in the local blt.yml files is correct, check for a VM enabled yaml key in your blt yml files, etc.
