### ISSUE TITLE
Update to Drupal 8.7.x for Testing

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3416]
BLT 9.2.x and BLT 10.x should theoretically both support Drupal 8.7.x when it comes out.

This ticket is for tracking updates of necessary dependencies to accomplish this.

The https://github.com/acquia/lightning team is working hard on Lightning 3.4.0 which will support 8.7.x. BLT will need to align our update with Lightning's, as the current version will likely block updates beyond 8.6.x on the drupal/core package.

**Comment by mikemadison13** [comment]
Initial efforts on my part here:

I am testing on a project using BLT 9.2.4. Here are the steps I've taken to experiment:
- i did try to alter composer.required and composer.suggested json files in my blt directly, but they were overwritten during the blt update process (didn't seem to matter)
- manually ran `composer require acquia/lightning 3.3.0-alpha1 webflo/drupal-core-require-dev 8.7.0-alpha1`

- nuked my composer.lock and vendor folders (was getting massive dependency collisions without redrawing all the dependencies and ran `composer update`
```
  Problem 1
    - Installation request for acquia/lightning 3.3.0-alpha1 -> satisfiable by acquia/lightning[3.3.0-alpha1].
    - Conclusion: remove drupal/core 8.6.11
    - Conclusion: don't install drupal/core 8.6.11
    - acquia/lightning 3.3.0-alpha1 requires drupal/lightning_core ^4.0-alpha1 -> satisfiable by drupal/lightning_core[4.x-dev, 4.0.0-alpha1].
    - drupal/lightning_core 4.0.0-alpha1 requires drupal/core 8.7.0-alpha1 -> satisfiable by drupal/core[8.7.0-alpha1].
    - drupal/lightning_core 4.0.0-alpha1 requires drupal/core 8.7.0-alpha1 -> satisfiable by drupal/core[8.7.0-alpha1].
    - drupal/lightning_core 4.x-dev requires drupal/core 8.7.x-dev -> satisfiable by drupal/core[8.7.x-dev].
    - drupal/lightning_core 4.x-dev requires drupal/core 8.7.x-dev -> satisfiable by drupal/core[8.7.x-dev].
    - Can only install one of: drupal/core[8.7.0-alpha1, 8.6.11].
    - Can only install one of: drupal/core[8.7.x-dev, 8.6.11].
    - Installation request for drupal/core (locked at 8.6.11, required as ^8.6.0) -> satisfiable by drupal/core[8.6.11].
```
- removed some core and module patches that have since been committed
- executed database updates
- exported new configuration (quite a few updates to config)
- ran blt setup

**Comment by danepowell** [comment]
I've already updated BLT 10.x to test with Drupal 8.7 here: https://github.com/acquia/blt/pull/3481

I'm pretty confident BLT 9.2.x will work fine too, I'll backport that after it's merged.

@mikemadison13 it seems like your work here is more focused on updating end-user projects, rather than testing BLT itself with Drupal 8.7. In that case, I think your documentation / upgrade guide would be better suited for a Wiki page than the issue queue.

Other than that, I'm not aware of any other work that needs to happen here.

**Comment by mikemadison13** [comment]
There is an open paragraphs issue related to the above: https://www.drupal.org/project/paragraphs/issues/3007596. It sounds to me like this issue was fixed some time back. However, there is a new version of Paragraphs (1.7) and I'm only running 1.6, so I'm going to give that a whirl and see where we land.

**Comment by mikemadison13** [comment]
Yeah, fair points @danepowell i'll get a wiki page going. If you are satisfied with where we are at on BLT itself, we can close this issue and I'll pick up the update process there.
