### ISSUE TITLE
Apply PHPCS to Behat Tests

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#3431]
This is a feature enhancement request.   

We rely heavily on behat tests on our project.   We discovered that developers were submitting behat code that was not getting scanned at all by BLT.  As a result our behat code follows no coding standards.  

Can we add phpcs scanning of test code using PSR-2?

**Comment by ashabed** [comment]
Seconded. If making this "on" by default is problematic, it would be nice to make this configurable.

**Comment by mikemadison13** [comment]
We talked about this some time back in https://github.com/acquia/blt/issues/1523 but there was some concern at the time that it would cause some issues

**Comment by danepowell** [comment]
@aweingarten @ashabed this should be as easy as removing `<exclude-pattern>*/behat</exclude-pattern>` from phpcs.xml in your root directory. Can you test and let me know how it works, and open a PR?

It worked for me on an out-of-the-box BLT site, but given the concerns expressed by Matt in #1523 I'm not sure that generalizes to more complex test cases.

**Comment by danepowell** [comment]
Closing due to lack of response.
