### ISSUE TITLE
Reduce verbosity / length of tests

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3436]
BLT's automated test output is approaching the limit of what Travis can output in the browser. We should reduce the verbosity of the test output somehow, and ideally reduce the overall time required for tests to run as well.

Might also want to run more tests in parallel. The problem here is that simply creating the BLT project in test environment takes 5 minutes, can we bypass that?

Finally, maybe remove the Drupal tests from the test matrix that we added here: #3351

**Comment by alexxed** [comment]
Can we capture the output and display it only if a test failed ?

**Comment by nileshlohar** [comment]
I have updated to BLT 9.2.8 and Travis is logging all the CSS/JS/Image calls on every behat step.
and at the end travis is failing with error: `This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.`

Any quick fix before this gets resolved?

**Comment by dpagini** [comment]
I've seen this as well @nileshlohar - I haven't confirmed this, but my suspicion is that this changed with a recent update to `$ drush runserver` functionality, maybe? Maybe BLT could call that command with a less verbose output?

**Comment by danepowell** [comment]
Sorry if it wasn't clear from the description, but this issue actually refers to BLT's internal tests, not to the tests that get run on BLT-generated projects.

Let's spin off the Drush discussion to https://github.com/acquia/blt/issues/3650
