### ISSUE TITLE
 BLT vendor Drush ^9 seems to cause 'self::SCOPE_CONTAINER' errors

### ISSUE THREAD

**Issue by mariagwyn** [acquia/blt#344]
Running `drush st` using global Drush 8.1.3 but BLT vendor Drush ^9 causes 'self::SCOPE_CONTAINER' errors. Removing the drush/drush require entirely from BLT composer.json seems to correct the issues.

Likely due to local weirdness with drush and php, but after considerable troubleshooting with @grasmash, no clear path forward toa a solution.

```
<<2016-08-31 11:31:52>> $ drush st
PHP Fatal error:  Undefined class constant 'self::SCOPE_CONTAINER' in /Users/maria.mcdowell/Sites/devdesktop/bolted8/docroot/core/lib/Drupal/Core/DependencyInjection/ContainerBuilder.php on line 204
Drush command terminated abnormally due to an unrecoverable error.                                                                                          [error]
Error: Undefined class constant 'self::SCOPE_CONTAINER' in
/Users/maria.mcdowell/Sites/devdesktop/bolted8/docroot/core/lib/Drupal/Core/DependencyInjection/ContainerBuilder.php, line 204

Fatal error: Undefined class constant 'self::SCOPE_CONTAINER' in /Users/maria.mcdowell/Sites/devdesktop/bolted8/docroot/core/lib/Drupal/Core/DependencyInjection/ContainerBuilder.php on line 204
```

**Comment by grasmash** [comment]
Thanks for posting this so that others can track down the issue.

At present, I do not believe this is a BLT issue. It is likely an issue either with drush or some aspect of your local config. Closing until this can be reproduced on another machine.

**Comment by mariagwyn** [comment]
Turns out this is entirely do to an unrelated drush extension that is breaking vendor-based drush installs.

**Comment by cubytz** [comment]
Late to this party but if you could explain a bit more how to solve this, it would be great!
