### ISSUE TITLE
DT-592: Drush behaves inconsistently depending on where it's called

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3467]
If you run `drush status` from the docroot, it correctly finds local site settings in `local.drush.yml` including the site URI. You can verify by this by checking the following in the output:
```
Site URI       : http://local.foo.com
Drush configs  : docroot/sites/default/local.drush.yml
```

If you run `drush status` from the root directory, it does not find these settings. The local.drush.yml file isn't found, and the wrong site URI is usually returned.

**Comment by danepowell** [comment]
I think we should wait for this upstream issue to be resolved, since it will probably impact how we tackle this problem: https://github.com/drush-ops/drush/issues/3968

My understanding is that once that's done, we could just have a `drush.yml` file in each site directory that includes a `local.drush.yml` in the same directory, and then remove the top-level include of `docroot/sites/default/local.drush.yml`

**Comment by mikemadison13** [comment]
@danepowell just food for thought, i've seen different behavior in different locals. in drupal vm it's what you describe, but in docksal it's actually backwards. without the drush launcher, you HAVE to run fin drush commands from inside docroot (at least you do on the project i'm working on).

**Comment by danepowell** [comment]
Since there hasn't been any movement on the upstream issue, I'm taking this out of the roadmap for now.
