### ISSUE TITLE
BLT sync:refresh Error: no database record could be found.

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#3497]
My system information:
* Operating system type: MacOs
* Operating system version: Mojave 10.14.3
* BLT version: 9.0.5

Output of `blt doctor`:

<img width="706" alt="Screenshot 2019-03-21 at 2 31 45 PM" src="https://user-images.githubusercontent.com/6311767/54905974-422ba500-4f08-11e9-9568-d018bc9e2fa4.png">

When I run this command:
`blt sync:refresh`

I get the following output:

<img width="1217" alt="Screenshot 2019-03-25 at 2 36 20 PM" src="https://user-images.githubusercontent.com/6311767/54907400-6a68d300-4f0b-11e9-8887-2da4a77e6b68.png">

And I expected this to happen:
Sync should happen without any error.

**More information:**
In my drush/sites/discoverboatingapp.site.yml file I've the following local & dev aliases. 

> local:
  host: local.discoverboat.com
  options: {  }
  root: /var/www/discoverboat/docroot
  uri: 'http://local.discoverboat.com'
  user: vagrant
  ssh: { options: '-o PasswordAuthentication=no -i $HOME/.vagrant.d/insecure_private_key' }
dev:
  host: free-7829.devcloud.hosting.acquia.com
  options:
    ac-env: dev
    ac-realm: devcloud
    ac-site: discoverboatingapp
  paths:
    drush-script: drush9
  root: /var/www/html/discoverboat.dev/docroot
  uri: discoverboatingappraawm4dcww.devcloud.acquia-sites.com
  user: discoverboatingapp.dev

In my blt/blt.yml file the drush aliases are used like below.

> drush:
  aliases:
    remote: discoverboatingapp.dev
    local: discoverboatingapp.local
    ci: self
  default_alias: self

Not sure if I am missing something.

**Comment by danepowell** [comment]
Run the command again with the `-vvv` flag, i.e. `blt sync:refresh -vvv`.

That should print the exact SSH command that is failing and the error message. Paste that error message here, and also try running the SSH command it provides directly to confirm that the same problem exists outside of BLT.

**Comment by sandipsmarty** [comment]
When I ran `blt sync:refresh -vvv` from within VM, I see the following.

<img width="1219" alt="Screenshot 2019-03-26 at 10 12 28 AM" src="https://user-images.githubusercontent.com/6311767/54972064-c2591580-4faf-11e9-9d67-6f7999a42480.png">

**Comment by sandipsmarty** [comment]
I did not know that the following keys are important for remote drush aliases.

>   dev.livedev:
    parent: '@discoverboatingapp.dev'
    root: /mnt/gfs/discoverboatingapp.dev/livedev/docroot

After adding the above keys the in dev drush alias it becomes

> dev:
  root: /var/www/html/discoverboatingapp.dev/docroot
  ac-site: discoverboatingapp
  ac-env: dev
  ac-realm: devcloud
  uri: discoverboatingappraawm4dcww.devcloud.acquia-sites.com
  dev.livedev:
    parent: '@discoverboatingapp.dev'
    root: /mnt/gfs/discoverboatingapp.dev/livedev/docroot
  host: discoverboatingappraawm4dcww.ssh.devcloud.acquia-sites.com
  user: discoverboatingapp.dev
  paths:
    drush-script: drush9

Now, when I run `drush @discoverboatingapp.dev status`, it shows the complete status, earlier it was not able to connect Acquia cloud dev DB.

<img width="661" alt="Screenshot 2019-03-26 at 4 51 31 PM" src="https://user-images.githubusercontent.com/6311767/54993362-a7a29300-4fe7-11e9-98ef-33110baf388b.png">

But now I see different error while running `blt sync:refresh -vvv`

<img width="1223" alt="Screenshot 2019-03-26 at 4 55 42 PM" src="https://user-images.githubusercontent.com/6311767/54993584-27306200-4fe8-11e9-8da8-2b8820a238f3.png">

I checked the directory /**.vagrant.d** is not present in /home/vagrant/ inside vm.

**Comment by lcatlett** [comment]
@sandipsmarty your version of drush and BLT are quite old, and in the case of BLT there have been significant changes to config such as drush aliases, vm config, and the defaults in blt.yml. You should update to the latest versions of both because that alone may likely resolve your issues

**Comment by danepowell** [comment]
As Lindsey said, you definitely should update.

If you run the `drush sql-sync` command in that output, you will receive the same error, indicating that this is not a problem with BLT, but with your Drush aliases, DrupalVM, and/or SSH configuration.

The error itself indicates that your SSH key in the VM does not have appropriate permissions to access the remote environment.

Most likely, you have configured something on your host related to SSH that broke key forwarding, or you haven't added your public SSH key to the remote environment.

**Comment by sandipsmarty** [comment]
Thanks @danepowell @lcatlett, for your inputs. Surely I will upgrade BLT & Drush, in-fact I already planned for these along with Drupal core update & which are my next steps to do.

But I was just wondering, without upgrade also things should work. May be there is something wrong with my BLT VM & Drush alias configurations, just wanted to identify & fix that.

If you see my local Drush alias, in SSH part it's pointing to $HOME/.vagrant.d/insecure_private_key. It's trying to access the /.vagrant.d/ directory which actually doesn't exists. I've already uploaded my host machine's public SSH key to Acquia cloud environment. After completing `blt vm`, I checked the ssh keys of the vm are identical to my host machine. 

> local:
     root: /var/www/discoverboat/docroot
     uri: 'http://local.discoverboat.com'
     host: local.discoverboat.com
     user: vagrant
     ssh: { options: '-o PasswordAuthentication=no -i $HOME/.vagrant.d/insecure_private_key' }

Do you have any suggestion to fix this issue? Please let me know if you need more information.

**Comment by sandipsmarty** [comment]
I fixed the issue by modifying drush alias config in my **blt/blt.yml** file. I changed the local drush alias from 

> discoverboatingapp.local

 to 

> self

```
drush:
  aliases:
    remote: discoverboatingapp.dev
    local: self

```
Thanks much for your help. I am closing this issue.
