### ISSUE TITLE
New project creation fails if global Git user is unconfigured

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#3511]
`blt internal:create-project:init-repo` fails with an error in any environment without a global Git user email configured, such as Acquia Pipelines.

To reproduce, ensure the setting is unconfigured in your test environment.

    git config --global --unset user.email

Then create a BLT project:

    composer create-project --no-interaction acquia/blt-project:10.x-dev

At the end of the process, the following results:

    > blt internal:create-project:init-repo
    [warning] The xDebug extension is loaded. This will significantly decrease performance.
    [ExecStack] git init && git add -A && git commit -m 'Initial commit.'
    [ExecStack]  Initialized empty Git repository in /Users/travis.carden/Projects/Work/test/blt-project/.git/
    [ExecStack]  Exit code 128
    [error]  Could not initialize new git repository.
    Script blt internal:create-project:init-repo handling the post-create-project-cmd event returned with error code 1

I suggest that whenever BLT wants to commit it does the following:

1. Check for the setting, i.e., `git config user.name; git config user.email`
1. If absent...
    1. configure it locally, e.g., `git config user.name BLT; git config user.email no-reply@example.com`
    1. unset it after committing, i.e., `git config --unset user.name; git config --unset user.email`

Related issues:
- https://github.com/acquia/blt/issues/2971
- https://github.com/acquia/blt/issues/2940

**Comment by danepowell** [comment]
I definitely understand why this is frustrating. I'm not sure it's exactly a bug, since having a user.name and user.email is a clear requirement of Git, and BLT is just shelling out to it. But we can probably make the experience better for people who encounter this situation regularly (i.e. with CI tools that don't set Git info)

I'm thinking we should remove the initial project commit entirely and/or set a temporary local user/email (as you suggest, or with `git commit --author "BLT <>"`) when committing initially and for deploys, along with a warning to this effect so no one is surprised when "BLT" shows up in their commit logs.

**Comment by alexxed** [comment]
I think the initial commit is good for several reasons:
- it gives a point in time when the project was generated
- it's clear by the commit what BLT did and what the user did next in future commits
- the first commit is big anyway, it could be hard for some git beginner people to do it on their own

**Comment by TravisCarden** [comment]
That reasoning makes sense, @alexxed. I know it's a little beside the point, but if you choose to keep the initial commit (with a workaround for missing global configuration), I would advocate for a minor change: make an empty commit first that allows for rebasing or otherwise altering history of the big commit. The inability to do that has chaffed me in the past.

```
$ git init
$ git config user.name BLT
$ git commit --allow-empty --author="BLT <no-reply@acquia.com>" -m "Initial commit."
$ git show
commit c8bd1621cd4912f8af3d32e4ab2a22cb2e6ed121 (HEAD -> master)
Author: BLT <no-reply@acquia.com>
Date:   Mon Apr 8 10:55:35 2019 -0400

    Initial commit.
```

**Comment by danepowell** [comment]
Feel free to provide feedback on https://github.com/acquia/blt/pull/3541
