### ISSUE TITLE
Upgrading Drupal core from 8.5.x to 8.6.13

### ISSUE THREAD

**Issue by neeraj-cog** [acquia/blt#3514]
I have updagraded Acquia lightening using the below command:
`composer require acquia/lightning:~3.2.7 --no-update `

And then, when I try to update the packages using the below command:
`composer update`

This is failing with the below errors:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove PROJECT/PROJECT_lightning 8.0.4.1-alpha11
    - PROJECT/PROJECT_lightning 8.0.4.1-alpha11 requires acquia/lightning ~3.2.7 -> satisfiable by acquia/lightning[3.2.7].
    - Conclusion: remove acquia/lightning 3.2.7
    - Installation request for PROJECT/PROJECT_lightning 8.0.4.1-alpha11 -> satisfiable by PROJECT/PROJECT_lightning[8.0.4.1-alpha11].
    - Conclusion: don't install webflo/drupal-core-require-dev 8.6.13
    - Installation request for webflo/drupal-core-require-dev ^8.6.0 -> satisfiable by webflo/drupal-core-require-dev[8.6.0, 8.6.0-alpha1, 8.6.0-beta2, 8.6.0-rc1, 8.6.1, 8.6.10, 8.6.11, 8.6.12, 8.6.13, 8.6.2, 8.6.3, 8.6.4, 8.6.5, 8.6.6, 8.6.7, 8.6.8, 8.6.9, 8.6.x-dev, 8.7.0-alpha1, 8.7.0-alpha2, 8.7.0-beta1, 8.7.x-dev, 8.8.x-dev].
    - Conclusion: don't install drupal/core 8.6.13|install webflo/drupal-core-require-dev 8.6.13
    - acquia/lightning 3.2.7 requires drupal/lightning_core ^3.9 -> satisfiable by drupal/lightning_core[3.9.0, 3.x-dev].
    - drupal/lightning_core 3.x-dev requires drupal/core 8.6.x-dev -> satisfiable by drupal/core[8.6.x-dev].
    - drupal/lightning_core 3.x-dev requires drupal/core 8.6.x-dev -> satisfiable by drupal/core[8.6.x-dev].
    - drupal/lightning_core 3.9.0 requires drupal/core ~8.6.13 -> satisfiable by drupal/core[8.6.13, 8.6.x-dev].
    - drupal/lightning_core 3.9.0 requires drupal/core ~8.6.13 -> satisfiable by drupal/core[8.6.13, 8.6.x-dev].
    - drupal/lightning_core 3.9.0 requires drupal/core ~8.6.13 -> satisfiable by drupal/core[8.6.13, 8.6.x-dev].
    - Conclusion: don't install drupal/core 8.6.x-dev|don't install acquia/lightning 3.2.7|keep drupal/core 8.6.13|install drupal/core 8.6.13
    - Conclusion: remove drupal/core 8.6.13|install webflo/drupal-core-require-dev 8.6.13
```

**Comment by mikemadison13** [comment]
It would be helpful to know what version of BLT you are using for this?

As a rule, you shouldn't have to put anything into your project's composer.json file for acquia/lightning or drupal/core, as BLT will do all of that for you.

If you are trying to upgrade to the most current version of Drupal, I would suggest making sure you are able to run BLT 9.2.4, remove the dependencies from your composer.json file for Lightning, Core, etc. and run a `composer update acquia/blt --with-all-dependencies`

If THAT doesn't work, try:
`rm -rf vendor`
`composer update acquia/blt --with-all-dependencies`

**Comment by neeraj-cog** [comment]
BLT version is - 9.2.4

Also, I see that '`behat`', '`bix`' are removed from the `vendor` directory; once try to upgrade lightning to 3.2.7.

**Comment by mikemadison13** [comment]
@neeraj-cog this is a semi-common problem when doing a big update. Sometimes you need to remove the composer.lock file and re-run a broad `composer update` to redraw all the necessary dependencies. 

Having said that, everything we're talking about here is related to composer and composer operations, and it's not really a BLT issue.  I'm happy to continue answering your questions, but there is no action for BLT here.
