### ISSUE TITLE
Settings file include order

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3527]
**Is your feature request related to a problem? Please describe.**
The order that BLT includes settings files get included leaves some room for improvement, in my opinion. I am mainly referring to `blt.settings.php` where all settings files from a projects `docroot/sites/settings/*` get included.

**Describe the solution you'd like**
So we have a situation where we load settings from BLT, then settings from the project, then more BLT settings (in the form of CI files), then the local includes. I am suggesting we reverse the order of the CI to be above the `docroot/sites/settings/*` load. I would think we should load all BLT settings _first_, which gives projects **more** flexibility to override BLT specific things.

I ran into this issue because I just switched over to using the `docroot/sites/settings/*.settings.php` load provided by BLT as opposed to including all my project specific settings from `docroot/sites/$sitedir/settings/includes.settings.php`, which is also loaded by BLT. Previously, I had a global setting file that set my CI database to the site directory name. When I switched the new BLT way, that file was being included before the CI specific BLT files, which were then overwriting my database name to a static name for all sites.

I know this is a specific use case, but it just seems to me like it would make more sense to load ALL library (BLT) settings files first, including CI, and then let the project take-over.

**Describe alternatives you've considered**
N/A

**Comment by danepowell** [comment]
@ba66e77 I think you wrote the setting auto-loading functionality, or at least touched it last. What do you think about this?

**Comment by ba66e77** [comment]
So functionally what you're wanting to do is move the block in blt.settings.php which starts on [Line 259](https://github.com/acquia/blt/blob/10.x/settings/blt.settings.php#L259) down to around line 305 in the same file, if I read you correctly. I don't see any immediate problem with that.

**Comment by danepowell** [comment]
Thanks @ba66e77 ... sorry, I thought this was referring to the other "global" includes that you helped with, but actually @greylabel wrote this particular code that we're now proposing to change.

Here's a permalink to the code block in question, which was added in https://github.com/acquia/blt/pull/2055:

https://github.com/acquia/blt/blob/08221377b4a1e26fc0bb2f469112fb488f3b7dfc/settings/blt.settings.php#L259-L272

The proposal is to move it _below_ the CI includes. I agree that seems reasonable, but I'm just concerned because the code comment specifically says it was placed above the CI block for a reason. @greylabel , do you have any more context on why that was, or potential ramifications of moving it?

**Comment by greylabel** [comment]
I agree should review and align on the the intention of the cascade here. I think the intension was to order by most general to most specific: global settings -> sites settings -> environment settings. 

# [Include](https://github.com/acquia/blt/blob/08221377b4a1e26fc0bb2f469112fb488f3b7dfc/settings/blt.settings.php#L209) settings that are applicable for all environments and sites: `cache.settings.php`, `logging.settings.php`, 
# [Include](https://github.com/acquia/blt/blob/08221377b4a1e26fc0bb2f469112fb488f3b7dfc/settings/blt.settings.php#L268) additional user supplied settings that applicable for all environments and sites
# [Include](https://github.com/acquia/blt/blob/08221377b4a1e26fc0bb2f469112fb488f3b7dfc/settings/blt.settings.php#L279) settings for environment specific overrides or additions
# [Include](https://github.com/acquia/blt/blob/08221377b4a1e26fc0bb2f469112fb488f3b7dfc/settings/blt.settings.php#L279) settings for site specific overrides or additions
# [Include](https://github.com/acquia/blt/blob/08221377b4a1e26fc0bb2f469112fb488f3b7dfc/settings/blt.settings.php#L332) settings for site specific  overrides or additions

I think we should swap 3. and 4. in the above.

**Comment by danepowell** [comment]
Now I see... yeah, I actually agree with @greylabel that environment settings need to come closer to the bottom of the chain. For instance, [ci.settings.php](https://github.com/acquia/blt/blob/10.x/settings/ci.settings.php) sets all kinds of things that might conflict with global or site-specific user settings, and I think ci.settings.php should almost always "win", _unless_ the user is specifically overriding that setting for the CI environment.

So maybe we need to move site-specific includes above environment includes, as @greylabel proposes.

The question is how to accommodate @dpagini in that scenario. It seems like in the same way that we support user-supplied global and site-specific settings, we need to support a user-supplied "environmental settings" include as the last step of environment includes. Not sure exactly where such a file should live or how it should be named.
