### ISSUE TITLE
Suggestion: Remove global.settings.default.php

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3528]
**Is your feature request related to a problem? Please describe.**
This is not really a problem, just a suggestion.

**Describe the solution you'd like**
The `global.settings.default.php` is more of documentation than a usable PHP file. Can this just be a `README.md` file in the `docroot/sites/settings/` folder?

Or why not make it an actual `*.settings.php` file that gets included? Someone has to modify it before it _does_ anything.

**Comment by danepowell** [comment]
It's not supposed to do anything out of the box except act as a place to put global settings (if you want to). Is it hurting anything to have it there, or are you just looking for a cleaner codebase?

**Comment by dpagini** [comment]
But I guess my point is that it's not even a place you can put global settings. If you rename the file, BLT will try to add a new one (I would guess) on upgrades. If you add anything to this file, it won't be loaded b/c of its name. So it's nothing more than directions, but named as a PHP file. It's mostly just confusing to me (bad DX) to look at that file and see a file I know isn't getting loaded, and that does not conform to the naming standard of all the other files there.

**Comment by danepowell** [comment]
Couldn't you make the same arguments about `default.settings.php` provided by Drupal core?

You aren't supposed to edit it directly, you are supposed to copy and rename it in order to use it. And it will keep existing even though it "does" nothing on its own other than to serve as an example.

Do we just need to provide additional direction to that effect via comments in the file? i.e. "This file serves only as a template and does nothing on its own. You must rename it according to the pattern docroot/sites/settings/*.settings.php in order to use."

I agree that the naming is backwards, it seems like it should be default.global.settings.php. I assume the original name was chosen for ease of regex.

**Comment by dpagini** [comment]
> Couldn't you make the same arguments about default.settings.php provided by Drupal core?

Fair point. I'd say the only difference to me is Drupal core gives you a well documented file you can use directly by uncommenting some lines. 

Yeah, I think it's just the naming... If it were named `default.global.settings.php` then it would be picked up and required by the `blt.settings.php` file (any file that matches *.settings.php), which I think is what you're saying. But is that such a bad thing? If it's blank to begin with, no harm, no foul, then let projects add something directly to that file if they'd like. Right now it's a really useless PHP file IMO... which is I guess why I created the issue to begin with. I just found myself adding this useless file to my project, and if I don't add it, BLT will try to create it every time it runs.

**Comment by danepowell** [comment]
Besides the name, I think it's weird that we use slightly different methods to include global settings and site settings. I think we should align on a single method:

https://github.com/acquia/blt/blob/c8ddd7184d8c8ebe64787e0a3bbbabd58fdda8dc/settings/blt.settings.php#L268-L272

https://github.com/acquia/blt/blob/c8ddd7184d8c8ebe64787e0a3bbbabd58fdda8dc/settings/blt.settings.php#L315-L317

So the options are, for both global settings includes in sites/settings/*.settings.php and site settings includes in sites/*/settings/*.settings.php, either:
# Include only a single file, provided via a template, which users can then modify to their heart's content.
# Include (glob) _all_ files in the respective directory.

I think option 1 is better, I'll submit a PR based on that.
