### ISSUE TITLE
Artifact deploy failing with message: fatal: pathspec '.' did not match any files

### ISSUE THREAD

**Issue by jose-oliveira** [acquia/blt#3529]
- [ X ] I have read and understand the [contribution guidelines](../../docs/CONTRIBUTING.md) for new issues.

**Describe the bug**
Running:
`vendor/bin/blt artifact:deploy --commit-msg "Test commit" --ignore-dirty --no-interaction --verbose -Dgit.remotes.1='REMOTE' --branch=BRANCH`

Throws:

`fatal: pathspec '.' did not match any files
[ExecStack]  Exit code 128  Time 0.014s
[error]  Failed to commit deployment artifact! `

**Expected behavior**
Artifact to be deployed.

**Additional context**
This seems to happen because the repo doesn't have any files yet, so the command fails to remove all files as none exists. Adding [`--ignore-unmatch`](https://www.atlassian.com/git/tutorials/undoing-changes/git-rm) fixes it. 

**System information**
* Operating system type: MacOS
* Operating system version: Mojave
* BLT version: 10.0.0-rc-2

**Comment by timcosgrove** [comment]
Just confirming we are seeing this in BLT 9.2.6 also.

It makes sense that this would fail on new branches. The order of operations is:
1. create new directory if it does not exist
2. cd into this empty directory.
3. `git init`
4. (config setting)
5. `git rm -r --cached .`

Which indeed fails if you have a fresh git repo with no files in it.

**Comment by ReleaseTheCode** [comment]
@jose-oliveira i have the same issue since 4/05/2019, and try the same solution (add --ignore-unmatch)
im waiting for the merge #3530 

Regards.

![Captura de Pantalla 2019-04-08 a la(s) 17 36 03](https://user-images.githubusercontent.com/15971354/55758437-ce6bbb00-5a24-11e9-824b-3b8043a43a73.png)

**Comment by mpodorov** [comment]
I suggest to add -q option since the output length can be unacceptable for huge projects.

**Comment by stephencross** [comment]
Having the same problem, when I comment out the recently added `git rm -r --cached .`, the deployment works.

**Comment by camoa** [comment]
The problem is that there is nothing added to the repo at that time, so the rm can't do anything.

@mikemadison13 @danepowell

**Comment by christopher-hopper** [comment]
We're seeing this problem when running `blt deploy --tag` on an existing repository with heaps of stuff in it. I guess it is because a tag is unique and will never have anything in it to remove?

Here's the command.

```
deploy --commit-msg="Automated build by $(git config user.name) of $(git describe --tags --abbrev=0)" --tag="$(git describe --tags --abbrev=0)-build" --no-interaction --ansi --verbose
```

So the solution, I'm guessing by reading above, would be for me to add this additional argument/parameter `--ignore-unmatch`

Can we have `--ignore-unmatch` be the default when creating a tag? I cannot think of a reason why we wouldn't want that. Anyone?

**Comment by danepowell** [comment]
It's in 9.2.x here: https://github.com/acquia/blt/commit/f03b8609ddd8cb52a13c2a07ffa88588eb156e6b

9.2.7 should drop fairly imminently.
