### ISSUE TITLE
Add drupal-check to default CI tests?

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#3546]
**Is your feature request related to a problem? Please describe.**

Dries recently posted on [How to prepare for Drupal 9](https://dri.es/how-to-prepare-for-drupal-9). In the post he mentions:

> If you work on a Drupal site as a developer, run `drupal-check`. Matt Glaman (Centarro) developed a static PHP analysis tool called `drupal-check`, which you can run against your codebase to check for deprecated code. I recommend running drupal-check in an automated fashion as part of your development workflow.

Link: https://github.com/mglaman/drupal-check

**Describe the solution you'd like**

I was going to start working on adding drupal-check to a couple of my D8 sites... but then thought wouldn't it be nice if BLT included it either as an optional add-on, or required? It would be nice to have a way to make sure developers aren't checking in new code with deprecated function usage, making the Drupal 8 to Drupal 9 transition more difficult when the time comes.

**Describe alternatives you've considered**

Not adding it. Crossing my fingers and hoping developers never use deprecated code.

**Additional context**

N/A

**Comment by lcatlett** [comment]
@aweingarten submitted https://github.com/acquia/blt/pull/3386 and put in a lot of the changes required to implement drupal-check in BLT. https://github.com/acquia/blt/issues/3438 doesnt look like it was ever resolved which seems to be a blocker

**Comment by danepowell** [comment]
#3386 was a good start but had a lot of outstanding feedback that needed to be resolved. If someone wants to pick that up and get it across the finish line, I'd be happy to review it. But otherwise implementing that analysis is not on the roadmap right now.

Aquia customers should open a support ticket if they want to see this issue on the roadmap, that's the best channel for advocacy.
