### ISSUE TITLE
Add blt-project 10.x and 10.x-stable branches

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3553]
We should rethink the strategy for folks to get dev releases using blt-project. If that's still something we want to support, and if so how.

I needed it today in order to test that #3541 didn't affect new project creation.

Assuming we want to keep that, we need to adapt the subtree-push script to write 10.x and 10.x-stable branches separately, if such a thing is even possible.

**Comment by nedsbeds** [comment]
Hi @danepowell 
Just a +1 to say this would be really cool, and would help us to keep using and testing BLT 10 on our new ACSF D8.7 build :)
