### ISSUE TITLE
DT-589: Support Behat 3.4+

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3559]
**Is your feature request related to a problem? Please describe.**
I am unable to upgrade the `behat/behat` library.

**Describe the solution you'd like**
Hoping we can remove the restrictions on the behat versions that appear to be put in 1.5 years ago to work with Lightning.
I see the restrictions were introduced in https://github.com/acquia/blt/pull/1993 clearly to address a problem with lightning. As I, like many other BLT users, do not use lightning, this is a tough version contraint to deal with. I also think it's very odd that BLT should be responsible for specifying versions of behat, and that cannot be left up to lightning to handle. Could they use maybe the conflicts section of their composer file? Not sure if that would work...? As I mentioned this was introduced a long time ago, so maybe this does not even exist as a problem any longer...?

**Describe alternatives you've considered**
Leave as is?

**Comment by danepowell** [comment]
Note that https://github.com/acquia/blt/pull/1993 actually made the Behat constraint _more_ permissive, not less so. So I don't think it should really be considered as "introducing restrictions". Nonetheless, if it's possible for folks to upgrade of course we should allow it.

https://github.com/acquia/blt/pull/1993 is lacking in detail, but my _guess_ is that it has to do with [this commit in Lightning](https://github.com/acquia/lightning/commit/abb448b690c502d5c71ce48207b2114a1d19b39c#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780), which effectively restricted Drupal Extension to < 3.3.0.

This in turn [changed Drupal Extension's Behat dependency](https://github.com/jhedstrom/drupalextension/blob/v3.2.3/composer.json) to <3.2.0, which would have conflicted with BLT's constraint of >3.3.1, thus preventing BLT users from upgrading to Lightning 2.1.5 or later.

Lightning later reversed that, so I don't think there's any action required of Lightning here. The only remaining question is whether there's any reason for BLT to continue limiting Behat to <3.4. We'll probably need some testing to determine the answer to that.

**Comment by danepowell** [comment]
Since Behat 3.4 and 3.5 seem pretty broken, any workaround would likely require a breaking change with Behat <3.4, and there doesn't seem to be a broad call for this, I'm deferring this to at least BLT 11. If you need it more urgently for some reason you can submit product feedback via a support ticket and we'll reassess urgency.

**Comment by danepowell** [comment]
Unfortunately this just can't happen until https://github.com/Behat/Gherkin/pull/129 is merged. This is a critical bug with Behat 3.4 and 3.5 that's existed for years, and has nothing to do with BLT. I'm actually not sure how anyone's using the later Behat releases. 😞 

Once that's merged and a new release of Behat / Mink is issued, we should be able to support Behat 3.4+ without any modifications to BLT.
