### ISSUE TITLE
[error]  There are uncommitted changes, commit or stash these changes before deploying. 

### ISSUE THREAD

**Issue by Momodoujobe** [acquia/blt#3561]
**I want to...**
Describe specifically what you are trying to accomplish.
After committing my changes from local to my repo and requesting a new pull request. I keep coming across with this error.

[error] There are uncommitted changes, commit or stash these changes before deploying.

and my composer.json file is up to date after running composer update same with blt update.
**It's not working because...**
What's going wrong?
I am getting this error "[error] There are uncommitted changes, commit or stash these changes before deploying."
**Detailed error output**
If a BLT command is failing, run it again with the `-vvv` argument and post the full output here.

**BLT doctor output**
Post the full output of `blt doctor` in the failing environment here.
+---------------------------+------------------------------------------------+
| Property                  | Value                                          |
+---------------------------+------------------------------------------------+
| %paths.%root              | /var/www/docroot                               |
| %paths.%site              | sites/default                                  |
| %paths.%modules           | sites/all/modules                              |
| %paths.%themes            | sites/all/themes                               |
| %paths.%config-sync       | /var/www/config/default                        |
| %paths.%files             | sites/default/files                            |
| %paths.%temp              | /tmp                                           |
| %paths.%private           | /var/www/files-private                         |
| admin-theme               | adminimal_theme                                |
| alias-searchpaths.0       | /var/www/drush/sites                           |
| blt-version               | 9.2.6                                          |
| bootstrap                 | Successful                                     |
| composer-version          | Composer version 1.6.3 2018-01-31 16:28:17     |
| config-sync               | /var/www/config/default                        |
| db-driver                 | mysql                                          |
| db-hostname               | db                                             |
| db-name                   | default                                        |
| db-password               | user                                           |
| db-port                   | 3306                                           |
| db-status                 | Connected                                      |
| db-username               | user                                           |
| drupal-settings-file      | sites/default/settings.php                     |
| drupal-version            | 8.6.10                                         |
| drush-alias-files.0       | /var/www/drush/sites/collegegoalny.site.yml    |
| drush-cache-directory     | /home/docker/.drush/cache                      |
| drush-conf.0              | /var/www/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/drush/drush.yml                       |
| drush-conf.2              | /var/www/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                           |
| drush-version             | 9.6.2                                          |
| files                     | sites/default/files                            |
| install-profile           | lightning                                      |
| modules                   | sites/all/modules                              |
| php-bin                   | /usr/local/bin/php                             |
| php-conf.1                | false                                          |
| php-os                    | Linux                                          |
| private                   | /var/www/files-private                         |
| root                      | /var/www/docroot                               |
| site                      | sites/default                                  |
| stacks.drupal-vm.inited   | false                                          |
| stacks.dev-desktop.inited | false                                          |
| temp                      | /tmp                                           |
| theme                     | collegegoalny                                  |
| themes                    | sites/all/themes                               |
| uri                       | http://collegegoalny.docksal                   |
+---------------------------+------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+
| Check                                | Problem                                                   |
+--------------------------------------+-----------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri          | base_url in tests/behat/local.yml does not match the site |
|                                      | URI.                                                      |
|                                      |   Behat base_url is set to http://web.                    |
|                                      |   Drush site URI is set to                                |
|                                      | http://collegegoalny.docksal.                             |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |
+--------------------------------------+-----------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
**System information**
* Operating system type: [replace]Mac
* Operating system version: [replace] 2012 Macbook Pro
* BLT version: [replace] 9.2.6

**Comment by mikemadison13** [comment]
this is a dup of https://github.com/acquia/blt/issues/3526

**Comment by mikemadison13** [comment]
potential / easiest work around at the moment is to pin your blt to 9.2.4.

**Comment by Momodoujobe** [comment]
I pin my blt to 9.2.4. but I am still getting the same issues.

**Comment by Momodoujobe** [comment]
After running but setup, it worked! Thanks

**Comment by Momodoujobe** [comment]
9.2.4 works!
