### ISSUE TITLE
Drupal tests fail in Acquia Pipelines

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3568]
If you try to run the standard `blt tests:all` suite in a 10.x project (upgraded from 9.2.x, but I think this would happen for fresh projects too) it will fail because of some sort of jankiness in the new DrupalTest command. I think it has something to do with launching / killing Selenium needlessly.

@greylabel can you comment on what might be going on here? Notice that `tests:drupal:run` has the `@launchWebServer` tag, which will start the server automatically: https://github.com/acquia/blt/blob/10.x/src/Robo/Commands/Tests/DrupalTestCommand.php#L109

But it then goes on to explicitly launch the webserver when the tests are actually run: https://github.com/acquia/blt/blob/10.x/src/Robo/Commands/Tests/DrupalTestCommand.php#L80

It seems like that shouldn't be happening twice. And is Selenium even necessary here?

**Comment by greylabel** [comment]
Thanks, @danepowell. I can look this afternoon.

**Comment by lcatlett** [comment]
the proposed changes in https://github.com/acquia/blt/pull/3525 should likely be reviewed again, as this is one of the issues that PR was intended to resolve

**Comment by greylabel** [comment]
@danepowell Can you provide any additional repro details, error output, and/or sample config to make this error out? Testing quickly on a fresh 10.x I don't see any failures.

Also note that the Behat commands follow a very similar setup WRT `@launchWebServer` and `WebDriver`: https://github.com/acquia/blt/blob/10.x/src/Robo/Commands/Tests/BehatCommand.php#L54

**Comment by danepowell** [comment]
Oh... apparently this is specific to Pipelines. Our error logging was a little inadequate, once I improved that I see this:
```
The following errors were logged:
/mnt/tmp/local.prod/source/vendor/bin/selenium-server-standalone: 11: exec: java: not found
```

So probably something specific to Java on Pipelines. Although I'm wondering if we need to be launching Selenium at all here.

**Comment by greylabel** [comment]
You do if you are trying to run Drupal's functional javascript tests.

https://www.drupal.org/node/2941464

**Comment by danepowell** [comment]
Well, that's unfortunate. Pipelines most definitely doesn't have Java, so we can't run Drupal tests there.

Not sure what the best solution is long-term, but since we're trying to get 10.0.0-rc3 out the door today, I think I'll just skip these tests in environments without Java: #3577
