### ISSUE TITLE
New global.settings.php introduces infinite include loop

### ISSUE THREAD

**Issue by hctom** [acquia/blt#3583]
As of #3528 and #3537 there is a new `docroot/sites/setting/global.settings.php` introduced to use for global settings includes. Unfortunately the `/sites/settings/*.settings.php` glob pattern in that file includes the `global.settings.php` file as well which results in an infinite include loop.

**To Reproduce**
* Initialize BLT-powered Drupal project
* Rename `docroot/sites/setting/default.global.settings.php` to `docroot/sites/setting/global.settings.php`
* After that step the site is gone due to the infinite include loop

**Comment by danepowell** [comment]
Right you are, thanks for the quick catch. Can you please test #3587 and let me know if it works for you? You'll need to regenerate your global.settings.php to use that new include format.

**Comment by hctom** [comment]
I just checked your fix and it works perfectly! With the new code in `global.settings.php` everything works fine again and global settings files are loaded as expected..

**Comment by danepowell** [comment]
Thanks for the quick feedback! I may put out a hotfix release soon for this...
