### ISSUE TITLE
BLT `artifact:` commands break ACSF deploys and updates

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3584]
**Describe the bug**
There have been several incidents where the `artifact:` BLT commands have inadvertently executed Cloud Hooks on the ACSF `[env0n]up/update` update environments.

Acquia docs were recently updates with detailed overview of the ACSF deploy/update process here: https://docs.acquia.com/site-factory/workflow/deployments/process, but in sum, the approach introduced in #3570 and #2552 may need to be re-visited, as cloud hooks can execute outside the context of drupal being bootstrapped or classes being autoloaded. 

I realize that #3565 was filed to report a similar issue and a new approach to environment detection was introduced in #3570 an effort to resolve this bug, but I was unable to successfully update a test customer to BLT 10.x and customers using BLT 9.2.x are still experience issues including:

- Failed config imports and db updates
- Accidentally executing BLT and other scripts on their live environments
- Cron and search indexing running on the incorrect site/environment
- Failed releases due to the update and live environments being out of sync.     

In general, BLT and other scripts should never attempt to iterate through sites and run any command on the $site context, especially on ACSF, which I called out in #2846:

> The artifact:deploy:update and artifact:acsf-hooks:db-update tasks used in previous iterations of the Factory Hooks scripts should not be used as they are currently architected, as the commands are not ACSF multisite and task aware and assume the architecture of a traditional multisite rather than ACSF. In the case of invoking switchSiteContext(), BLT currently assumes that $site_name is equivalent to the --uri or domain value used in Drush 9 commands, however this is problematic on ACSF because logic in sites.php and other settings included via drush acsf-init dynamically map the site names and FQDN passed in --uri to the respective ACSF sites identified by their ACSF database name.

**Comment by danepowell** [comment]
Bug reports require explicit steps to reproduce the problem, as well as expected and actual outcomes. I don't know how to reproduce or remediate this bug based on the information you've provided.

I know that there have been issues with Cloud Hooks running in ACSF in the past, but to my knowledge those issues should be resolved. Anyone running the latest 10.x-dev should have no problems having Cloud Hooks installed in an ACSF context (they should exit gracefully).

If there's something actionable for BLT here please provide a clearer description of the bug, or a clear feature request. Thanks.

**Comment by lcatlett** [comment]
@danepowell - these issues were discussed and linked to explicitly in the BLT channel. Please reference the internal PF-1903 ticket entitled "Ensure Acquia-managed Cloud Hook/scripts are compatible with multisite and other products" as this is currently impacting more than one customer.

As the ACSF product owner, your comment yesterday was the first I learned that BLT is no longer testing against ACSF projects, or asking someone with access to an ACSF environment to do testing or code review. It is disappointing to see that  [dogfooding has taken a backseat](https://github.com/acquia/blt/blob/10.x/docs/CONTRIBUTING.md#submitting-pull-requests) in favor of merging major architecture changes without any manual or automated tests, as BLT has always been a good model to point to of how these sorts of best practices can be scaled and maintained.
