### ISSUE TITLE
Bolt should adhere to verbose options and not hardcode them

### ISSUE THREAD

**Issue by kylebrowning** [acquia/blt#36]
` <drush command="site-install" assume="yes" verbose="TRUE" alias="${drush.aliases.local}">`

Hardcodes verbose to true, It would be preferable if this could be command line based as an option.

phing uses `-v` for version so we can't use that.

options are:
* `-verbose` (include phing verbosity, bolt's, drush, and other tasks)
* `-bv` (just bolt, drush and other task's verbosity)
* `-boltverbose) (same as above)
* `-verbose-all` (all verbosity in bolt (tasks, drush, etc) except phing)
* `-verbose-bolt` (just bolts verbosity)
* `-verbose-drush` (just drush verbosity)
* `-verbose-tasks` (all task's verbosity)

**Comment by danepowell** [comment]
There's a good reason for `site-install` in particular to be verbose... on large projects it can take more than 10 minutes to run, which will cause Travis to timeout and fail the build.
