### ISSUE TITLE
Start webserver when running functional PHPUnit tests

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#3611]
**Is your feature request related to a problem? Please describe.**
Running `blt tests:phpunit:run` does not start/stop Drush runserver. This results in functional PHPUnit tests failing:
```
GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to 127.0.0.1 port 8888: Connection refused
```

**Describe the solution you'd like**
Add the `@launchWebServer` annotation to the `runPhpUnitTests()` method in the PhpUnitCommand class or provide some configuration option to allow this.

**Describe alternatives you've considered**
I've considered trying to hook into or override the command to start/stop the server. 

Thanks!

**Comment by greylabel** [comment]
@richardbporter Are you referring to running Drupal's functional tests?

**Comment by richardbporter** [comment]
I don't want to run Drupal's functional tests but my own tests extending BrowserTestBase.

**Comment by greylabel** [comment]
Sorry, I meant are you leveraging Drupal's provided testing frameworks like `Drupal\Tests\BrowserTestBase` vs another functional testing implementing with PHPUnit? Sounds like you are?

What version of BLT are you using and where are you wanting the to run the tests (which CI system)?

**Comment by richardbporter** [comment]
Yep. I was able to get this working via a Robo hook:
```
/**
   * Start the webserver before running PHPUnit tests.
   *
   * @hook pre-command tests:phpunit:run
   */
  public function prePhpUnitTestRun(CommandData $commandData) {
    if ($this->getConfigValue('tests.run-server')) {
      $this->invokeCommand('tests:server:start');
    }
  }
```

I'm trying to run them in CI (Pipelines). I'm not using Behat (but maybe I should be?). I'm on BLT 10.x.

**Comment by greylabel** [comment]
BLT 10 includes the `tests:drupal:run` which should help with setting-up and running test that use Drupal's testing framework.

This command requires selenium, which is used functional javascript tests. Pipelines doesn't have java available for selenium so this probably won't help you with running tests on Pipelines.

**Comment by richardbporter** [comment]
Gotcha, thanks.

Do you think its worth modifying the command to allow this in some capacity?

**Comment by danepowell** [comment]
Functional tests are typically done with Behat or the Drupal framework, which do spin up a server. AFAIK, most projects use PHPUnit for much lower-level (class / method) testing.

This is the first request I've seen to start a server with PHPUnit tests.This leads me to be believe it's not a very common use case, and running a server automatically would be a needless waste of resources for most projects. Assuming that's true (given the limited data I have), then your solution of using a Robo hook just for your project is the best one.

If you think that requiring a server for PHPUnit tests is a more common use case, let me know, or you can advocate for this feature via a support ticket. @mikemadison13 feel free to validate/reject my assumption here that most people aren't using PHPUnit to do browser-based testing.
