### ISSUE TITLE
BLT Blocking Installation of Upgrade Status Module

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3615]
**Describe the bug**
When trying to add the drupal/upgrade_status module for testing, I am getting the following errors:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nikic/php-parser (locked at v3.1.5) -> satisfiable by nikic/php-parser[v3.1.5].
    - drupal/upgrade_status 1.0.0-alpha2 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - drupal/upgrade_status 1.0.0-alpha1 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - drupal/upgrade_status 1.0.0-alpha2 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - drupal/upgrade_status 1.0.0-alpha1 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - Conclusion: don't install mglaman/phpstan-drupal 0.11.3
    - Installation request for drupal/upgrade_status ^1.0@alpha -> satisfiable by drupal/upgrade_status[1.0.0-alpha2, 1.0.0-alpha1].
```

After digging, it looks like since we have the `sensiolabs-de/deprecation-detector` in blt 9.2 (https://github.com/acquia/blt/blob/9.2.x/composer.required.json#L22), which requires `nikic/php-parser: ~3.0` (https://packagist.org/packages/sensiolabs-de/deprecation-detector) and this is causing significant headaches. I'm not convinced that upgrade_status _can_ be installed with BLT 9.2.x in its current state because of sensiolabs-de/deprecation-detector.

**To Reproduce**
Steps to reproduce the behavior, _ideally_ starting from a fresh install of BLT:
1. Run `composer require drupal/upgrade_status`

**Expected behavior**
Module should be added by composer

**Detailed error output**
```
composer require drupal/upgrade_status 
    1/3:	https://packages.drupal.org/8/drupal/provider-2016-2$c5257985340fad1023080c9b1c04ac467256826931d5fc8120ca92ad557e1779.json
    2/3:	https://packages.drupal.org/8/drupal/provider-2019-2$583115e2b9c06531a9a52df57d78b04c4db50c38ae926e68b106fd583c063793.json
    3/3:	https://packages.drupal.org/8/drupal/provider-2019-1$ef051d04b53cec890c889ed817d18f95c78d64b7b60683461105a602d14558b3.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
    1/1:	https://asset-packagist.org/p/provider-latest/73932407bf9a0d433b3adf568bf12522fd595cb2349c6434cb902e94cb7874c7.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
    1/5:	http://repo.packagist.org/p/provider-latest$83e98cada341e0536ec76a7d439d2cd409b37add307a91fd176efdfbc0d48dc8.json
    2/5:	http://repo.packagist.org/p/provider-2019-04$e1760a35263716e978ecef8506fb56c02e7776d5a0748e6b3b9b8a6488a0b74b.json
    3/5:	http://repo.packagist.org/p/provider-2018-10$eecf4a450d7549eec0af7470144ed85a85d4795293555f430b40bdddb67ad500.json
    4/5:	http://repo.packagist.org/p/provider-2019-01$f5f95240ebfb1318bec1bf8aaaa72452aaa76640164acd018d6dfaa19681cc41.json
    5/5:	http://repo.packagist.org/p/provider-2017$23c86588a1baecd62425bbad7fe994e9787a71b930034735ce7f3c6e85e997c3.json
    Finished: success: 5, skipped: 0, failure: 0, total: 5
Using version ^1.0@alpha for drupal/upgrade_status
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nikic/php-parser (locked at v3.1.5) -> satisfiable by nikic/php-parser[v3.1.5].
    - drupal/upgrade_status 1.0.0-alpha2 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - drupal/upgrade_status 1.0.0-alpha1 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - drupal/upgrade_status 1.0.0-alpha2 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - drupal/upgrade_status 1.0.0-alpha1 requires mglaman/phpstan-drupal 0.11.3 -> satisfiable by mglaman/phpstan-drupal[0.11.3].
    - Conclusion: don't install mglaman/phpstan-drupal 0.11.3
    - Installation request for drupal/upgrade_status ^1.0@alpha -> satisfiable by drupal/upgrade_status[1.0.0-alpha2, 1.0.0-alpha1].


Installation failed, reverting ./composer.json to its original content.
```

**Additional context**
As far as I can tell, BLT 10.x has removed sensiolabs-de/deprecation-detector (see https://github.com/acquia/blt/commit/4fe4cbe8fe608446cd492f7dbdc4a679c9a8fd83#diff-689639047be6809fd5ab243af5990fff). I am continuing to dig here.

@danepowell we should discuss adding this module by default to BLT's Drupal module list, as it is going to be a recommended addition to all projects moving forward to begin preparing for the 2020 release of Drupal 9.

**Comment by mikemadison13** [comment]
I can confirm this isn't a problem with BLT 10.x.

**Comment by goba** [comment]
IMHO proper integration of the command line tools should be added rather than the UI module. The command line tool can run in build/validation, unlike the module. The module is targeted at people who want full site reports to asses complete status of a site grouped by projects. THAT is not provided by the command line tools. I don't understand where https://github.com/acquia/blt/pull/3386 went bad.

**Comment by ShannonVettes** [comment]
I think that what Mike is saying is that the module has value to him if he can export the work to be done into ticketing systems, and drupalcheck allows him to do that. Without this feature, he is unlikely to use the module.

What's the complexity of changing the export ? Seems like a nice win that adds good value to the module if the effort is not too high.

**Comment by goba** [comment]
It is not hard to make the module output ASCII formatted error reports, but we need to decide if that is what we do for each single module export or we have some kind of export format selector, etc. In the meantime drupal-check does what Mike needs and a lot more benefits in the context of BLT.

**Comment by ShannonVettes** [comment]
If I'm thinking to export a list and import it into a ticket system, I probably want multiple projects, so maybe ascii export is most useful for the export of *all* the things and not individual modules.

**Comment by goba** [comment]
I tweeted at https://twitter.com/gaborhojtsy/status/1125767817624731648 to
get more data points from people. Will see if this results in anything.

**Comment by mpodorov** [comment]
Will there be the 9.2.9 release soon?

**Comment by mikemadison13** [comment]
the PR above was merged, i think this issue can probably be closed, don't you think @danepowell ? it also might be nice to cut 9.2.9 even though it's technically in LTS to unblock people on this issue.

**Comment by danepowell** [comment]
The next scheduled release is on June 5, per the support policy (releases are the first Wednesday of each month). This issue should have been closed automatically via that PR, not sure why it wasn't.

The way to take advantage of this (or any other fix) prior to that release is to either update to the 9.2.x-dev version of BLT, or add this to your composer.json:
```json
patches: {
  "acquia/blt": {
    "Allow upgrade status module.": "https://patch-diff.githubusercontent.com/raw/acquia/blt/pull/3621.patch"
  }
}
```
