### ISSUE TITLE
Follow up to #3363: Drush CR 

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3617]
**Describe the bug**
I started using the config strategy 'none' and there were some changes made to make sure that `drush updb` was run when the config strategy was none. These work great.
However, during our production deploys, there is now no longer a `drush cr` performed for our sites since it only gets run in features/config import steps.
I have some small hesitation here, wondering if a `drush cr` is _really_ even needed. I guess if we have new frontend assets, for example, we want those being served up immediately after a deployment, so I think we do want that.

**To Reproduce**
Steps to reproduce the behavior, _ideally_ starting from a fresh install of BLT:
1. From a BLT project...
2. Set config strategy to 'none'
3. When an artifact is deployed on ACE, cloud hooks will run `blt artifact:ac-hooks:post-code-deploy ...` and no drush CR will be performed.

**Expected behavior**
A general cache-clear should take place to ensure the deployment works as promised.

**Comment by mikemadison13** [comment]
so, an interesting thought, i'm 99% sure that `drush updb` runs a `drush cr` automatically once updates are completed. but, if there are no updates, i bet it doesn't do so.

do you think adding a redundant `drush cr` in `blt drupal:update` after the updates run but before we move onto `config-import` makes sense?

**Comment by dpagini** [comment]
I had the exact same thought @mikemadison13 and I believe you are correct... if there is not update I don’t think it runs. 

To test that (very elementary) I tried:
```sh
drush config:set ‘test’ ‘yep’
drush config:get ‘test’
drush updb 
drush config:get ‘test’
```

I was planning on trying that WITH an update hook to see if it clears, but hadn’t gotten around to it yet. 

If we do what you suggested, maybe we just move the one from config:import outside the if statements?
