### ISSUE TITLE
BLT 10.x Rewrites composer.json to 10.x-dev

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3618]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, _ideally_ starting from a fresh install of BLT:
1. Update composer.json to `acquia/blt: ^10.0`
2. Run `composer update acquia/blt --with-all-dependencies`
3. After blt update runs
4. Verify composer.json has now changed

**Expected behavior**
BLT shouldn't change my stable ^10.0 to 10.x-dev

**Detailed error output**
N/A

**BLT doctor output**
N/A

**Comment by danepowell** [comment]
Guess we need to modify that update hook to exclude BLT version when it merges composer templates.
