### ISSUE TITLE
Custom commands via plugins

### ISSUE THREAD

**Issue by lpeabody** [acquia/blt#3628]
**I want to...**
I want to distribute custom commands to multiple projects via Composer packages. It is indicated this is possible in 10.x here https://github.com/acquia/blt/wiki/What's-new-in-BLT-10.x. However, I am unable to find any documentation around this feature on the documentation site. Hoping you can point me in the right direction to get started with this. Thank you for all of the amazing work! I can't live without BLT.

**It's not working because...**
I'm sure it is, I just can't find the documentation on how to use it.

**Comment by danepowell** [comment]
I think this is the documentation you are looking for: https://github.com/acquia/blt/blob/10.x/docs/extending-blt.md#adding-a-custom-robo-command-or-hook

Let me know if that works for you.

**Comment by lpeabody** [comment]
Ah, yeah, I missed this more times than I care to admit:

> You can also provide custom commands in a separate Composer package as long as it exposes them via PSR4.

Thank you for pointing that out.

I'm assuming that the file naming and namespacing requirements also apply to BLT commands included in packages as well as the project's BLT src directory?

**Comment by lpeabody** [comment]
EDIT: Ah, I missed it because I was looking here https://blt.readthedocs.io/en/latest/extending-blt/. I assumed that site was updated automagically during releases. I went back to double check to make sure I hadn't missed it there.

**Comment by danepowell** [comment]
> I'm assuming that the file naming and namespacing requirements also apply to BLT commands included in packages as well as the project's BLT src directory?

Yes the file name restrictions and top-level namespace still apply, but you have some flexibility if you are providing a plugin via Composer, depending on how you define your PS4 namespace / autoloader. Specifically, you'll need to define the `autoload` key in your composer.json so you can put it in some other directory than `blt/src`.

The following link demonstrates for Robo plugins, the same principal (just different namespace) applies to BLT: https://robo.li/extending/#register-command-files-via-psr-4-autoloading

Sorry RTD didn't get updated, I'll see what's going on there.

**Comment by danepowell** [comment]
By the way, if there's anything we can do to make the documentation on that more clear just let me know or open a PR. Thanks.
