### ISSUE TITLE
Add the --copy-links flag to Deploy command's rsync

### ISSUE THREAD

**Issue by jhedstrom** [acquia/blt#3635]
**Is your feature request related to a problem? Please describe.**
Symlinks in the `docroot` folder are currently copied as symlinks, which has the potential for unintended side effects.
**Describe the solution you'd like**
Add the `--copy-links` flag to `DeployCommand`'s `rsync` call.

**Comment by danepowell** [comment]
What exact is the use case for replacing symlinks with hardlinks? I would say that that actually has a higher chance of side effects.

The typical use case for symlinks is to target something else in the project itself (i.e. simplesaml config), which shouldn't be any problem (those symlinks will work equally well in a remote environment once deployed).

The only use case I could see this solving is having a symlink to something outside of your project, i.e. for a development version of a module. But that seems like a bad edge case (for instance that would be really hard to deploy via a CI tool anyway), there are generally better ways to handle development modules (i.e. composer path repositories), and replacing symlinks with hardlinks in those situations could be risky (recursive links could blow up the repo, etc...).

If there's a valid use case here, or alternately if we can improve the documentation for the current behavior some how to prevent unintended side effects, let me know.
