### ISSUE TITLE
Task: review allowed test failures

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3638]
Now that we've integrated with ORCA, we should review the allowed failures (such as deprecation tests) to see if there's anything we need to address.

**Comment by danepowell** [comment]
Most of the failures are not related to BLT. Lightning is incompatible with core 8.8, and there's a ton of deprecated code in contrib modules that we don't control.

However we should figure out why DEPRECATED_CODE_SCAN_SUT is failing, it seems to be related to autoloading.

**Comment by nateacquia** [comment]
https://backlog.acquia.com/browse/DT-482
