### ISSUE TITLE
Cannot run tests without Selenium installed. 

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3644]
**Describe the bug**
I want to run Drupal PHPUnit tests with the `run-tests.sh` method without using selenium. This was introduced in #3577. I'm wondering if there can be a better way to make this work...? I believe Selenium is only required to make the javascript functional tests work, is that accurate? If so, is there anyway we can skip those tests or something if there is no selenium... that would still allow kernel and functional tests to run on a system without selenium. Just seems drastic to say you cant run any tests without `Java` installed...?

**Expected behavior**
I want to be able to run tests without Java installed.

**Comment by greylabel** [comment]
@dpagini Just curious, where are you trying to run these tests that does not have Java? Pipelines?

**Comment by dpagini** [comment]
Locally and on Travis I don't have java. None of our DEVs have java locally as we all started from a shared base box. We could definitely add it, but I don't need it right now (no functional JS tests) and it's blocking me from upgrading to BLT 10 now.

**Comment by greylabel** [comment]
Ok, BLT enables Java on both Travis and DrupalVM by default. I will take a look at adding a flag to skip Java dependent tests.

**Comment by dpagini** [comment]
This is really a minor one to me... don’t mean to inconvenience, just wanted to mention my experience. I’m psyched to start writing and testing JavaScript tests.

**Comment by greylabel** [comment]
I have been meaning find time to add support for Nightwatch.js, which is also supported by Drupal core for JS testing, so it won't be a bother to revisit this in the process.

**Comment by danepowell** [comment]
Thanks, if you're able to spearhead this it would be much appreciated. It would be a big lift for me since I don't work with the core testing framework on a regular basis. I do agree that long-term, it would be good to support environments without Java.

**Comment by danepowell** [comment]
The original request here is in the context of the run-tests.sh script, which we are considering deprecating in BLT 11 (because Simpletest itself is becoming deprecated in Drupal): https://github.com/acquia/blt/issues/3917

In that case, it doesn't seem like there's any action required in this ticket.
