### ISSUE TITLE
Extensible EnvironmentDetector "service".

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3645]
**Is your feature request related to a problem? Please describe.**
BLT "ships" with environment detection for dev, test and prod. In our Acquia account, we have an "Acceptance" environment, and a "Sandbox" environment that we use on a regular basis, and even "RA". In the past, I have included a settings file after `blt.settings.php` that says something along the lines of... `$is_dev_env = ($is_dev_env || $ah_env == 'sandbox');` to make my sandbox environment behave like DEV in all BLT code. However, as of #3570, this method really no longer works, as I have to call `EnvironmentDetector::isAhDev()` for example, and can no longer treat my sandbox environment like dev. For the time being, I'm going to just "re-set" all the variables that went away in 3570, and set them via the `EnvironmentDetector` class, and then include my overrides.

**Describe the solution you'd like**
Unsure?

**Describe alternatives you've considered**
I think I'm going to, and this may be the ultimate solution, but for now I'll `extend` the `EnvironmentDetector` class, and overwrite the methods I want, and then just use MY class to resolve any IF statements I was previously using BLT variables for...
Thoughts?

**Comment by danepowell** [comment]
It sounds like you are doing exactly the right thing by extending the environment detector. This was part of the appeal of moving to a more O-O approach to environment detection. Is there any reason that wouldn't work?

**Comment by dpagini** [comment]
No, I think that's OK... I just got used to Drupal's "services" that I can still call the same service in my code, but override which class it points to. That's probably _too much_ to ask BLT to do.

**Comment by danepowell** [comment]
Hmm... so just to make sure I have this straight, the problem with the workaround is that you can subclass the Environment Detector, but since BLT's internal logic is hardcoded to use the Environment Detector you can't change how BLT's internal settings behave without completely duplicating those settings files?

We can't access the Drupal service container from the settings files because it's not bootstrapped yet. I don't know if we could register a service independently with Symfony and access it, or whether that would be a good idea. It sounds pretty tricky if it's possible at all.

I see how this could be a problem but I'm not sure how else to solve it.

**Comment by danepowell** [comment]
@dpagini or @alexxed can you think of any good way to support this?

The best idea I've had is still kind of ugly IMHO. But here goes.

Developers could subclass EnvironmentDetector in their own projects and expose the subclass via PSR4. Then in specific methods that we want to allow overrides on, such as `isAhDev()`, we query for subclasses implementing this method via the autoloader and call those overridden methods if they exist.

It's a bit magical and hacky, but I _think_ it would work. I'd love either some affirmation or alternative proposals.

**Comment by danepowell** [comment]
D) Use an EnvironmentDetector factory that again looks for subclasses via PSR4. A little cleaner than (a), has the same problem of what to do if there are multiple implementations.

**Comment by dpagini** [comment]
Yeah, definitely a difficult problem... I mean, are the benefits of the recent switch big enough to leave them in place versus the settings variables we had?

**Comment by danepowell** [comment]
I don't see how this was much better with the old method. For instance, `blt.settings.php` sets `$is_dev_env` and then pretty immediately includes a bunch of other settings files that might rely on that variable without giving a project any means of overriding it first. I could see some specific cases where you might be able to work around it, but generally it doesn't seem a whole lot better then the new approach.

We might not need the environment detector for every single settings.php variable, but it is super important in standardizing things like ACSF and site detection, which happens in many different places beyond just settings. So I don't want to dump it so soon.
