### ISSUE TITLE
The option failOnDirty doesn't work as expected 

### ISSUE THREAD

**Issue by dimdiden** [acquia/blt#3647]
**I want to...**
Disable checking uncommitted changes by configuring blt.yml. I've set up the following:
```
deploy:
  git:
    failOnDirty: false
```

**It's not working because...**
If I run `vendor/bin/blt deploy --no-interaction --branch test -vvv`
I'm getting error:
`[error]  There are uncommitted changes, commit or stash these changes before deploying. `

However, if I run the previous command with` --ignore-dirty` option - everything is ok.
I thought that ` failOnDirty: false` in blt.yml is equal to `--ignore-dirty` flag. Is it incorrect?

Could you please help me to understand this? Thanks.

**System information**
* Operating system type: Mac 
* Operating system version: 10.14.2
* BLT version: 10.0.1

**Comment by danepowell** [comment]
As you observed, `--ignore-dirty` is the only valid way to disable this check. The `failOnDirty` config value has not been valid for a couple years, but it looks like there were some stale references to it in comments. I'll remove them in #3659 

If there's some other documentation that led you to try `failOnDirty` please let me know so we can update it as well.

**Comment by dimdiden** [comment]
Thank you for the feedback and quick fix!

**Comment by brooke-heaton** [comment]
How does one implement the `--ignore-dirty` flag? Is this set up in `blt.yml` ? Some level of documentation would be helpful.

**Comment by danepowell** [comment]
Anywhere you run `blt deploy`, add the flag. So `blt deploy --ignore-dirty`.

I asked above and didn't get a reply: where did you look for documentation on this, so we know where best to document it?
