### ISSUE TITLE
DT-581: Drupal JavaScript testing using Nightwatch

### ISSUE THREAD

**Issue by greylabel** [acquia/blt#3673]
[Drupal core supports JavaScript testing using Nightwatch](https://www.drupal.org/docs/8/testing/javascript-testing-using-nightwatch). BLT should support Nightwatch, similar to how it supports Drupal core's other testing frameworks.

**Comment by mikemadison13** [comment]
@greylabel currently the BLT testing for frontend frameworks assumes that you are using gulp (or npm, or whatever other framework) as a test runner from inside a module or theme, and uses the `frontend-test` hook https://github.com/acquia/blt/blob/10.x/src/Robo/Commands/Frontend/FrontendCommand.php#L49.

I'm familiar with Nightwatch, but haven't used it yet. Could you perhaps outline how supporting Nightwatch itself might be different than supporting pa11y, jest, etc. via the frontend hooks I mentioned above?

Thanks!

**Comment by greylabel** [comment]
@mikemadison13 It's very similar. `yarn` is recommended by Drupal core, rather than `npm` and it is really easy to get up and running with Nightwatch testing and BLT/DrupalVM locally: 
1. `cd docroot/core and yarn install` 
2. `cp .env.example .env` and configure
3. `yarn test:nightwatch`

All of this can be done using BLT's front end hooks, as you mentioned. So there are a few of options: 
1. Do nothing and let users manage the above described process on their own
2. Minimally, ensure dependencies are installed for use locally and in CI via `frontend-test` — really just `yarn` and `selenium` or `chromedriver` (the latter already are)
3. Add a `blt tests:` command that wraps the above steps and makes the experience more seamless

I think option 2. is probably sufficient to start.

**Comment by danepowell** [comment]
At the same time that we're deprecating run-tests.sh (#3917) in BLT 11, I'd like to get Nightwatch fully supported. It's not exactly a replacement, but it is complementary to core phpunit tests so I think it deserves its own command.
