### ISSUE TITLE
Site Splits Broken

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#3674]
**Describe the bug**
This is an issue impacting both BLT 9.2.x and 10.x (and perhaps previous versions as well).

Currently, config splits based on a site (or site splits) should be functional when a config split has the exact same name as a site on ACSF. 

After https://github.com/acquia/blt/issues/3362 got fixed (which resolved a site name detection issue) I had hoped we were good, but after extensive troubleshooting, this is still not working. 

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Create a "site split" that properly matches the site name of at least one acsf site
2. Deploy code to acsf
3. Confirm that the site split didn't get activated
4. Using `drush php` print out the global $config array
5. see output:

```
global $config;
>>> print_R($config);
Array
(
    [config_split.config_split.local] => Array
        (
            [status] => 
        )

    [config_split.config_split.dev] => Array
        (
            [status] => 
        )

    [config_split.config_split.stage] => Array
        (
            [status] => 
        )

    [config_split.config_split.prod] => Array
        (
            [status] => 
        )

    [config_split.config_split.ci] => Array
        (
            [status] => 
        )

    [config_split.config_split.ah_other] => Array
        (
            [status] => 1
        )

    [config_split.config_split.g/files/<directory>] => Array
        (
            [status] => 1
        )
```

**Expected behavior**
I would expect an additional item in the config array above that corresponds with the site split. I could understand if the split wasn't getting activated for "some reason" but the fact that it's not in the config object at all is highly suspect given https://github.com/acquia/blt/blob/10.x/settings/config.settings.php#L89 

**Detailed error output**
N/A

**BLT doctor output**
N/A

**System information**
* BLT version: 9.2.3 (but persists across all 9.2.x and 10.x versions)

**Additional context**
This issue fits into a broader issue with config splits and the current landscape. While not directly related, https://github.com/acquia/blt/issues/3575 is a similar set of broken config split detection (but for profiles).

I think environment splits have been fine all along (because BLT can detect that). Site splits should _also_ be fine, once we merge these PRs, as BLT can easily detect the site on ACSF (thanks to the post-sites factory hook). However, as mentioned, profile splits require bootstrapping Drupal (so are a slightly different ball of wax).

**Solution**
We tested this by adding a global $_acsf_site_name, re-deployed, and confirmed that the site splits were actually working.

**Comment by mgamshad** [comment]
Hi,
We have an ACSF BLT application and the site split does not seem to still be working.  In looking at the code in blt.settings.php, it seems that the `$_acsf_site_name` is being set based the local environment's hostname.  Furthermore this comment seems to indicate a pattern for naming local sites:

`
    // The hostname must match the pattern local.[sitename].com, where
    // [sitename] is a value in the multisites array.
`

In our project setup we use a generic `d8.site.com` name, which of course does not match that pattern. So when in config.settings.php the `$_acsf_site_name` is used here:

`
// Set acsf site split if explicit global exists.
if (isset($_acsf_site_name)) {
  $config["$split_filename_prefix.$_acsf_site_name"]['status'] = TRUE;
}
`

The site split won't be applied.  Is that correct or am I reading this wrong?

Thanks,
mohsen

**Comment by mikemadison13** [comment]
What version of BLT?

**Comment by mgamshad** [comment]
> What version of BLT?

9.2.8.

thanks,
mohsen

**Comment by mikemadison13** [comment]
Site splits were fixed after the release of BLT 9.2.8. You either need to manually patch the fix or you need to update to 10.x!

**Comment by mgamshad** [comment]
Perfect, thanks.

**Comment by mgamshad** [comment]
One other question: if we are trying to move a BLT 9.x application off of Features to core CMI and config-split, apart from moving to BLT 10.x (based on your reply), do we need to pull in any other specific version of any other dependencies?

thanks,
mohsen

**Comment by mikemadison13** [comment]
not really, no. mostly it's just making sure config split is enabled and your configuration is moved out of the feature modules.
