### ISSUE TITLE
after_failure is not triggered when travis build fails on behat tests

### ISSUE THREAD

**Issue by longmtran** [acquia/blt#3687]
I'm using blt 10.0.1 with behat running on travis ci. travis.yml is generated by blt with some minor tweaks.

I want to trigger some tasks when behat tests fail on travis build, for example: uploading screenshot and test reports to S3. The tasks are added in `after_failure` step on .travis.yml

Somehow `vendor/acquia/blt/scripts/travis/run_tests` script in `script` step stops the whole build process when `blt tests:all` returns a failed test result. `after_failure` step is never triggered.

Some articles mentions about `set -e` issue on travis script, but doesnt seem to help. I've already tried a few things, including removing `set -e`, handling error code manually, calling `blt tests:all` directly in `after_failure`, but none triggers that `after_failure` step. I have not tried to alter `tests:behat:run` command and take out the `->stopOnFail()` yet, not sure if that has something to do with this issue.

There are 2 articles in the past for this same problem but it doenst seem to have a working solution:
https://github.com/acquia/blt/pull/3043
https://github.com/acquia/blt/pull/2521

Does anyone have similar problem and happen to know how to solve it?

**Comment by dpagini** [comment]
I've opened some of these tickets in the past... it has to do with 2 things, if I remember correctly. The way BLT calls its external scripts, such as `$ source ../vendor/acquia/blt/scripts/travis/run_tests` or `$ ./../vendor/acquia/blt/scripts/travis/run_tests`, which it does this way to ensure the output gets printed to the Travis screen. Then, the `set +/-e` commands in those scripts tell Travis to exit immediately without the `after_failure` code running. There _has to_be some kind of fix to something like this, but I just don't know anything about bash scripts and whatnot to get this to cooperate with the two goals... 1) output script to travis screen, 2) trigger `after_failure` when a behat step fails.

**Comment by danepowell** [comment]
I think you can fix this by modifying your `.travis.yml` to remove _any_ use of `source`, and instead just call the related bash scripts directly. As far as I can tell this has no effect on output, but will prevent `set -e` from "bleeding" into the main script, and thus allow Travis to run after_failure steps.

The only thing is you might need to patch BLT or fork its test scripts to ensure that they are all executable.
 
If you can confirm that that works, I think it makes sense to incorporate it into the BLT template for .travis.yml. But we'd need to do more extensive testing, such as to ensure output isn't affected, and to ensure that tests still fail properly (e.g. the test script doesn't run if Drupal setup fails in an earlier script).

**Comment by danepowell** [comment]
I think this will likely be solved by https://github.com/acquia/blt/pull/3756
