### ISSUE TITLE
Confusion over setting up with Acquia DevDesktop

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#369]
I read over this doc page describing how to setup this project for use with Acquia DevDesktop: https://github.com/acquia/blt/blob/8.x/readme/local-development.md#using-acquia-dev-desktop-for-blt-generated-projects

I just have a couple small questions about this:

1. After adding the site in DevDesktop, it will add a snippet to the bottom of your settings.php file which includes the settings file containing the DB credentials. I think the BLT docs should instruct users to move this snippet into the docroot/sites/default/settings/local.settings.php file right? No need to have this included in the main settings.php file.
2. The [drush support instructions](https://github.com/acquia/blt/blob/8.x/readme/local-development.md#acquia-dev-desktop) are a bit confusing. It says that BLT requires a custom version of drush. Is that true? why? The instructions say to update your PATH in .bash_profile, but the doing so will only give your terminal access to the mysql binaries shipped with DevDesktop, not drush or PHP.

**Comment by grasmash** [comment]
1. This is really up to you. If anything, DevDesktop should be putting the snippet into local.settings.php. You're free to move it, but I'd rather not add a manual instruction that isn't necessary. Also, DD will just add it again to settings.php later.
2. Sure, these could be more clear. In addition to "Ensure that Dev Desktop's PHP binary is being used on the CLI. " we can add an example of what needs to be added to your `~/.bash_profile`, but this will differ depending on the version of PHP selected in DD.

**Comment by bkosborne** [comment]
Cool, thanks. Worth mentioning that if you launch a terminal from DevDesktop, it will set these environment variables for you right away:

```
export PHP_ID=php5_6; export PATH="/Applications/DevDesktop/$PHP_ID/bin:/Applications/DevDesktop/mysql/bin:/Applications/DevDesktop/drush:$PATH"
```
