### ISSUE TITLE
Document how to run tests against multiple sites

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3690]
We have separate documentation on how to set up multisite projects, ACSF projects, CI, and testing for projects in general, but what is lacking is specific guidance on how to construct and run test suites for multisite installations, especially in the context of core CI tools (Travis / Pipelines).

Obviously there are a multitude of strategies for testing multisite projects, so I think we should focus on the simplest scenario to start, which is to run a separate Behat suite per-site.

The documentation should make sure to clarify that this is only one possible strategy (the other main strategy being to only test a single "canary" site or core platform features), and should also make sure to address the whole-stack setup process (including how to configure CI tools to e.g. install multiple sites / dbs).

Also make sure to capture the feedback from #3275, and maybe use my comment there as a basis for the documentation.

**Comment by aweingarten** [comment]
@danepowell, our projects will be planning to implement multi-site behat this week.  If you have any upcoming PRs we'd be happy to help test.  If not, do you have any plans/designs we could try to implement something that conforms with your plans!

**Comment by danepowell** [comment]
We don't have any pending work related to multisite, except to clarify docs (although some recent changes are only in dev and will become stable with the 10.1 release this week)

The only existing docs that I know of is my comment here: https://github.com/acquia/blt/issues/3275#issuecomment-477761674

That proposes just one strategy for multisite sites, there are probably other solutions as well. Anything you want to contribute in terms of guidance / documentation would be appreciated.

**Comment by jedgar1mx** [comment]
The #3275  comments is just what I was looking. It would be helpful it there was a comment on https://docs.acquia.com/blt/developer/testing/ about it. Great work 😁

**Comment by brooke-heaton** [comment]
I'm directly invoking `behat` rather than via BLT. I no longer see utility in Behat for multisites using BLT. Unless I'm missing something.

**Comment by danepowell** [comment]
Seems like this will be fixed by #3803
