### ISSUE TITLE
I like BLT, I don't like the blt/composer.*.json files.

### ISSUE THREAD

**Issue by dgpalmer** [acquia/blt#3693]
This is just some general feedback from someone who has been using BLT for 2 years + now.

I love BLT. I use it with all of my Acquia Cloud projects. I also use it with a few non Acquia projects. It makes building artifacts of composer based projects super easy. It makes integrating testing super easy.

What is really annoying though, is the blt/composer.required.json, blt/composer.suggested.json. These files consistently make updating things such as Drupal core, an absolute pain.

For instance, when attempted to update one of my project to 8.7.2 of core, it kept failing, because the blt/composer.required.json was pinned on 8.6.0.

This required me modifying that file to get the composer update to pull through.

I get that the point of BLT is to try to help people get started, but honestly, stuff like this and the lightning integrations get in the way.

Just my 2 cents. Please don't take offense.

**Comment by mikemadison13** [comment]
these files are gone in 10.x FYI

**Comment by mikemadison13** [comment]
we removed the composer merge plugin see https://github.com/acquia/blt/pull/3120

**Comment by dgpalmer** [comment]
That's great news Mike. Thank you!

**Comment by mikemadison13** [comment]
sure thing! you aren't the only one that disliked them ;)
