### ISSUE TITLE
Add database credential options for RMI

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#3698]
**Is your feature request related to a problem? Please describe.**
It's frustrating that `blt rmi` has to set database credentials interactively.

**Describe the solution you'd like**
Add additional options to `blt rmi` like `--db-name`, `--db-user`, etc. I'm not sure if this could be handled with one option or not. 

**Describe alternatives you've considered**
I've considered writing a wrapper command to handle this but would like to stick with BLT-core as much as possible.

**Additional context**
My assumption would be that `blt rmi` would not prompt for input if _one_ of the database options was specified.

**Comment by danepowell** [comment]
Makes sense, thanks. I'll add this to the backlog.

**Comment by danepowell** [comment]
This is no longer in the roadmap. It might still be a valid request but we need to take it out of the backlog to make space for higher priority issues.
