### ISSUE TITLE
Behat errors on pipelines but not locally

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#3702]
**I want to...**
I want to run test during my pipelines build.

**It's not working because...**
I'm able to run `blt tests:all` locally but when it runs on acquia, it errors out.

**Detailed error output**
`blt tests:all --define drush.alias='${drush.aliases.ci}' --environment=ci -D behat.web-driver=chrome --no-interaction --ansi --verbose

> tests:behat:run

[warning] tests.run-server is enabled, but the server URL does not match Drupal's base URL.

[warning] project.local.uri = http://local.detroitmi.test
[warning] tests.server.url = http://127.0.0.1:8888

[warning] local.extensions.Behat\MinkExtension.base_url = http://local.detroitmi.test

[error]  Behat is not configured properly. Please run `blt doctor` to diagnose the issue. 

[error]  Command `tests:behat:run ` exited with code 1. `

**BLT doctor output**
`
vagrant@local:/var/www/detroitmi$ blt doctor
+---------------------------+-------------------------------------------------------------+

| Property                  | Value                                                       |

+---------------------------+-------------------------------------------------------------+

| %paths.%root              | /var/www/detroitmi/docroot                                  |

| %paths.%site              | sites/default                                               |

| %paths.%modules           | sites/all/modules                                           |

| %paths.%themes            | sites/all/themes                                            |

| %paths.%config-sync       | /var/www/detroitmi/config/default                           |

| %paths.%files             | sites/default/files                                         |

| %paths.%temp              | /tmp                                                        |

| %paths.%private           | /var/www/detroitmi/files-private                            |

| admin-theme               | admin_detroitmi                                             |

| alias-searchpaths.0       | /var/www/detroitmi/drush/sites                              |

| blt-version               | 10.0.1                                                      |

| bootstrap                 | Successful                                                  |

| composer-version          | Composer version 1.8.4 2019-02-11 10:52:10                  |

| config-sync               | /var/www/detroitmi/config/default                           |

| db-driver                 | mysql                                                       |

| db-hostname               | localhost                                                   |

| db-name                   | drupal                                                      |

| db-password               | drupal                                                      |

| db-port                   | 3306                                                        |

| db-status                 | Connected                                                   |

| db-username               | drupal                                                      |

| drupal-settings-file      | sites/default/settings.php                                  |

| drupal-version            | 8.7.2                                                       |

| drush-alias-files.0       | /var/www/detroitmi/drush/sites/default.site.yml             |

| drush-alias-files.1       | /var/www/detroitmi/drush/sites/detroitatwork.site.yml       |

| drush-alias-files.2       | /var/www/detroitmi/drush/sites/detroitmi.localhost.site.yml |

| drush-alias-files.3       | /var/www/detroitmi/drush/sites/detroitmi.site.yml           |

| drush-alias-files.4       | /var/www/detroitmi/drush/sites/intranet.site.yml            |

| drush-alias-files.5       | /var/www/detroitmi/drush/sites/storm.water.site.yml         |

| drush-alias-files.6       | /var/www/detroitmi/drush/sites/the.neighborhoods.site.yml   |

| drush-alias-files.7       | /var/www/detroitmi/drush/sites/training.detroitmi.site.yml  |

| drush-cache-directory     | /home/vagrant/.drush/cache                                  |

| drush-conf.0              | /var/www/detroitmi/vendor/drush/drush/drush.yml             |

| drush-conf.1              | /var/www/detroitmi/drush/drush.yml                          |

| drush-conf.2              | /var/www/detroitmi/docroot/sites/default/local.drush.yml    |

| drush-script              | /var/www/detroitmi/vendor/drush/drush/drush                 |

| drush-temp                | /tmp                                                        |

| drush-version             | 9.7.0                                                       |

| files                     | sites/default/files                                         |

| install-profile           | varbase                                                     |

| modules                   | sites/all/modules                                           |

| php-bin                   | /usr/bin/php7.2                                             |

| php-conf.0                | /etc/php/7.2/cli/php.ini                                    |

| php-os                    | Linux                                                       |

| private                   | /var/www/detroitmi/files-private                            |

| root                      | /var/www/detroitmi/docroot                                  |

| site                      | sites/default                                               |

| stacks.drupal-vm.inited   | true                                                        |

| stacks.dev-desktop.inited | false                                                       |

| temp                      | /tmp                                                        |

| theme                     | detroitmi                                                   |

| themes                    | sites/all/themes                                            |

| uri                       | http://local.detroitmi.test                                 |

+---------------------------+-------------------------------------------------------------+
+--------------------------------------+-----------------------------------------------------------+

| Check                                | Problem                                                   |

+--------------------------------------+-----------------------------------------------------------+

| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root. |

+--------------------------------------+-----------------------------------------------------------+
`

**System information**
* Operating system type: Linux
* Operating system version: Ubuntu 18.04.2 LTS
* BLT version: 10.0.1

**Comment by danepowell** [comment]
What the error is telling you is correct, `project.local.uri` should be `http://127.0.0.1:8888`, not `http://local.detroitmi.test`. Pipelines has no mechanism for managing hosts files, virtualhosts, etc... as you would on your local with e.g. Vagrant, so BLT normally creates the site on localhost port 8888 in CI environments.

The value of `project.local.uri` normally gets set in CI environments in `blt/ci.blt.yml`: https://github.com/acquia/blt/blob/113885f57f325eff4f8931d576694467736665a6/subtree-splits/blt-project/blt/ci.blt.yml#L11

Have you modified or removed that file such that `project.local.uri` isn't getting set to `http://127.0.0.1:8888`?

**Comment by jedgar1mx** [comment]
Here is my `ci.blt.yml` file:

`
# Valid values are:
install - Installs Drupal from scratch.
#   sync - Uses `blt drupal:sync` to pull a remote db from drush.aliases.remote.
#   import - Imports a .sql file from setup.dump-file.
# setup.strategy: import
# Relative to the drupal docroot directory.
# setup.dump-file: /tmp/my-dump-file.sql
tests.run-server: true
tests.drupal.sudo-run-tests: false
# The local.hostname must be set to 127.0.0.1:8888 because we are using drush runserver to test the site.
project.local.hostname: 127.0.0.1:8888
drush.debug: false
`

**Comment by jedgar1mx** [comment]
Here is my example.local.yml 
`# To generate a local.yml file using this the example template, execute:
# `blt tests:behat:init:config` from the project root.
imports:
  - behat.yml

local:
  suites:
    default:
      paths:
        # Set features to repo root so that .feature files belonging to contrib
        # modules, themes, and profiles can be discovered.
        features: ${repo.root}
      contexts:
        - Drupal\FeatureContext:
          parameters:
            environment:
              # absolute path to local directory to store screenshots - do not include trailing slash
              screenshot_dir: ${tests.reports.localDir}
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\ConfigContext
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
      javascript_session: default
      # configure the base url for your site
      base_url: ${project.local.uri}
      # set default command for "Show last response" step.
      show_cmd: "open %s"
      # use the following lines to disable SSL authentication for goutte.
      # goutte:
      #   guzzle_parameters:
      #     redirect.disable: true
      #     ssl.certificate_authority: system
      #     curl.options:
      #       CURLOPT_SSL_VERIFYPEER: false
      #       CURLOPT_SSL_VERIFYHOST: false
      #       CURLOPT_CERTINFO: false
      #       CURLOPT_TIMEOUT: 120
      selenium2:
        wd_host: ${behat.selenium.url}
        browser: chrome
      sessions:
        default:
          chrome:
            api_url: "http://localhost:9222"
    Drupal\DrupalExtension:
      drupal:
        # This must be an absolute path.
        drupal_root: ${docroot}
      drush:
        alias: '@self'
`

**Comment by jedgar1mx** [comment]
my `ci.blt.yml` should be in the right location.
`
project
-blt
--blt.yml
--ci.blt.yml
`

**Comment by jedgar1mx** [comment]
It seems that `ci.blt.yml` was getting overriten by my sites `blt.yml`. I think this is due to the fact that I'm running a multisite setup. But everything seems to work now. Thanks
