### ISSUE TITLE
Add isset check on $_SERVER['PWD'] superglobal in find_repo_root()

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/blt#3715]
**Describe the bug**
On local environments that do not explicitly declare a $_SERVER['PWD'] superglobal variable (I'm not sure how this gets declared - does this original with DevDesktop?), the blt:update (or even the blt --version) method will fail in `find_repo_root()` (vendor/acquia/blt/bin/blt-robo.php:23). This was previously noted and resolved in https://github.com/acquia/blt/issues/3425. I'm not sure why this regressed or why this was overwritten. 

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Running a local Lando environment with BLT 10.0.0-beta2
2. Run `lando blt --version`, `lando blt blt:update` or nearly ANY blt command that runs `find_repo_root()` 
3. See error

**Expected behavior**
BLT should work in environments that don't explicitly declare a $_SERVER['PWD'] superglobal variable. This variable appears to be fairly local setups specific though I'm not clear on where this gets declared. In short, it is overly assuming. 

**Detailed error output**
PHP Notice:  Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23

Notice: Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23

**BLT doctor output**
PHP Notice:  Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23

Notice: Undefined index: PWD in /app/vendor/acquia/blt/bin/blt-robo.php on line 23
+---------------------------+--------------------------------------------------+
| Property                  | Value                                            |
+---------------------------+--------------------------------------------------+
| %paths.%root              | /app/docroot                                     |
| %paths.%site              | sites/default                                    |
| %paths.%modules           | sites/all/modules                                |
| %paths.%themes            | sites/all/themes                                 |
| %paths.%config-sync       | /app/config/default                              |
| alias-searchpaths.0       | /app/drush/sites                                 |
| blt-version               | 10.0.0-beta2                                     |
| composer-version          | Composer version 1.8.4 2019-02-11 10:52:10       |
| config-sync               | /app/config/default                              |
| db-driver                 | mysql                                            |
| db-hostname               | localhost                                        |
| db-name                   | drupal                                           |
| db-password               | drupal                                           |
| db-port                   | 3306                                             |
| db-username               | drupal                                           |
| drupal-settings-file      | sites/default/settings.php                       |
| drupal-version            | 8.7.3                                            |
| drush-alias-files.0       | /app/drush/sites/site-aliases/integrity.site.yml |
| drush-alias-files.1       | /app/drush/sites/site-aliases/naswa.site.yml     |
| drush-cache-directory     | /var/www/.drush/cache                            |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml                |
| drush-conf.1              | /app/drush/drush.yml                             |
| drush-script              | /app/vendor/bin/drush                            |
| drush-temp                | /tmp                                             |
| drush-version             | 9.5.2                                            |
| modules                   | sites/all/modules                                |
| php-bin                   | /usr/local/bin/php                               |
| php-conf.1                | false                                            |
| php-os                    | Linux                                            |
| root                      | /app/docroot                                     |
| site                      | sites/default                                    |
| stacks.drupal-vm.inited   | false                                            |
| stacks.dev-desktop.inited | false                                            |
| themes                    | sites/all/themes                                 |
| uri                       | default                                          |
+---------------------------+--------------------------------------------------+
+----------------------------------------------+--------------------------------------------------------------+
| Check                                        | Problem                                                      |
+----------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkLocalConfig:exists           | tests/behat/local.yml is missing!                            |
|                                              |   Run `blt tests:behat:init:config` to generate it from      |
|                                              | example.local.yml.                                           |
| ComposerCheck:composer.autoload.psr-4        | The Composer configuration for autoload.psr-4 differs from   |
|                                              | BLT's default, recommended values.                           |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| ComposerCheck:composer.extra.installer-paths | The Composer configuration for extra.installer-paths differs |
|                                              | from BLT's default, recommended values.                      |
|                                              |   Change your configuration to match BLT's defaults in       |
|                                              |                                                              |
|                                              | vendor/acquia/blt/subtree-splits/blt-project/composer.json.  |
| DbCheck:checkDbConnection                    | Could not connect to MySQL database.                         |
|                                              |                                                              |
|                                              | Is your *AMP stack running?                                  |
|                                              | Are your database credentials correct?                       |
|                                              |   db-driver: mysql                                           |
|                                              |   db-hostname: localhost                                     |
|                                              |   db-username: drupal                                        |
|                                              |   db-password: drupal                                        |
|                                              |   db-name: drupal                                            |
|                                              |   db-port: 3306                                              |
|                                              |                                                              |
|                                              | To verify your mysql credentials, run `mysql -u drupal -h    |
|                                              | localhost -pdrupal -P 3306`                                  |
|                                              |                                                              |
|                                              | Are you using the correct PHP binary?                        |
|                                              | Is PHP using the correct MySQL socket?                       |
|                                              |   php-os: Linux                                              |
|                                              |   php-bin: /usr/local/bin/php                                |
|                                              |   php-conf:                                                  |
|                                              |                                                              |
|                                              | Are you using the correct site and settings.php file?        |
|                                              |   site: sites/default                                        |
|                                              |   drupal-settings-file: sites/default/settings.php           |
|                                              |                                                              |
|                                              | To verify, run `drush sqlc`                                  |
|                                              |                                                              |
| DrupalCheck:checkDrupalBootstrapped          | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled             | Drupal is not installed.                                     |
|                                              |                                                              |
|                                              | Run `blt drupal:install` to install Drupal locally.          |
| FileSystemCheck:checkFileSystem:%files       | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private     | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp        | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists         | .node-version file exists                                    |
| SimpleSamlPhpCheck:checkSimpleSamlPhp        | /app/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp- |
|                                              | remote.php is missing. Run `blt                              |
|                                              | source:build:simplesamlphp-config`.                          |
| WebUriCheck:checkUri                         | Site URI is not set                                          |
|                                              | Is options.uri set correctly in                              |
|                                              | /app/docroot/sites/default/local.drush.yml?                  |
+----------------------------------------------+-------------------------------------------------------

**System information**
* Operating system type: Ubuntu 
* Operating system version: 18.04.2 LTS
* BLT version: 10.0.0-beta2

**Comment by danepowell** [comment]
Closed via #3717
