### ISSUE TITLE
blt artifact:deploy commit to the remote gets rejected with BLT 9.2.4

### ISSUE THREAD

**Issue by nishantkumar155** [acquia/blt#3732]
same issue as in https://github.com/acquia/blt/issues/3144

But my blt version is BLT 9.2.4 and git version 2.21.0

**Comment by danepowell** [comment]
BLT 9.2.4 is no longer supported and has a number of known issues. You'll need to reproduce this with 9.2.8. Please also follow the issue template and paste the output of `blt doctor` as well as the failing command.
