### ISSUE TITLE
DT-602: Reorganize Robo command directories

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3735]
The files containing BLT's Robo command classes are [organized in a fairly inscrutable and anachronistic folder hierarchy](https://github.com/acquia/blt/tree/10.x/src/Robo/Commands) that has persisted through several reorganizations of the command namespaces themselves.

For instance, the `recipes` namespace contains commands to intialize ACSF projects, CI projects, or multisite projects, but these are currently scattered among the `Acsf`, `Ci`, and `Generate` directories.

Ideally I think the folder hierarchy would match the command namespace hierarchy. Additionally, commands within each file should be namespaced correctly (for instance the `drupal:install` command is confusingly defined in BuildCommand.php rather than DrupalCommand.php).

Bonus points for a PHPCS rule or some other validation that enforces this organization going forward.

**Comment by mikemadison13** [comment]
+1 for this, there are definitely some commands that are impossible to find (and even if you do find them, they don't make a ton of sense where they are).
