### ISSUE TITLE
unable to upgrade from 10.1.0 to 10.2.0

### ISSUE THREAD

**Issue by shelane** [acquia/blt#3741]
**Describe the bug**

**To Reproduce**
1. Run `composer require acquia/blt ^10.2.0`
2. Run `composer update acquia/blt --with-all-dependencies`

**Expected behavior**
BLT should update to 10.2.0

**BLT doctor output**
blt doctor
+---------------------------+------------------------------------------------+
| Property                  | Value                                          |
+---------------------------+------------------------------------------------+
| %paths.%root              | /var/www/docroot                               |
| %paths.%site              | sites/default                                  |
| %paths.%modules           | sites/all/modules                              |
| %paths.%themes            | sites/all/themes                               |
| %paths.%config-sync       | /var/www/config/default                        |
| %paths.%files             | sites/default/files                            |
| %paths.%temp              | /tmp                                           |
| %paths.%private           | /var/www/files-private                         |
| admin-theme               | seven                                          |
| alias-searchpaths.0       | /var/www/drush/sites                           |
| blt-version               | 10.1.0                                         |
| bootstrap                 | Successful                                     |
| composer-version          | Composer version 1.8.0 2018-12-03 10:31:16     |
| config-sync               | /var/www/config/default                        |
| db-driver                 | mysql                                          |
| db-hostname               | db                                             |
| db-name                   | default                                        |
| db-password               | user                                           |
| db-port                   | 3306                                           |
| db-status                 | Connected                                      |
| db-username               | user                                           |
| drupal-settings-file      | sites/default/settings.php                     |
| drupal-version            | 8.7.3                                          |
| drush-alias-files.0       | /var/www/drush/sites/baasic.site.yml           |
| drush-alias-files.1       | /var/www/drush/sites/controlbanding.site.yml   |
| drush-alias-files.2       | /var/www/drush/sites/data_science.site.yml     |
| drush-alias-files.3       | /var/www/drush/sites/default.site.yml          |
| drush-alias-files.4       | /var/www/drush/sites/engineering.site.yml      |
| drush-alias-files.5       | /var/www/drush/sites/heds_center.site.yml      |
| drush-alias-files.6       | /var/www/drush/sites/kwla.site.yml             |
| drush-alias-files.7       | /var/www/drush/sites/ldrd_annual.site.yml      |
| drush-alias-files.8       | /var/www/drush/sites/library.site.yml          |
| drush-alias-files.9       | /var/www/drush/sites/nanoscience.site.yml      |
| drush-alias-files.10      | /var/www/drush/sites/nifuserguide.site.yml     |
| drush-alias-files.11      | /var/www/drush/sites/quantum.site.yml          |
| drush-alias-files.12      | /var/www/drush/sites/returntowork.site.yml     |
| drush-alias-files.13      | /var/www/drush/sites/seaborg.site.yml          |
| drush-alias-files.14      | /var/www/drush/sites/spotlight.site.yml        |
| drush-alias-files.15      | /var/www/drush/sites/supplychain.site.yml      |
| drush-alias-files.16      | /var/www/drush/sites/training.site.yml         |
| drush-alias-files.17      | /var/www/drush/sites/www.site.yml              |
| drush-cache-directory     | /home/docker/.drush/cache                      |
| drush-conf.0              | /var/www/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/drush/drush.yml                       |
| drush-conf.2              | /var/www/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/vendor/bin/drush                      |
| drush-temp                | /tmp                                           |
| drush-version             | 9.5.2                                          |
| files                     | sites/default/files                            |
| install-profile           | llnl_lightning                                 |
| modules                   | sites/all/modules                              |
| php-bin                   | /usr/local/bin/php                             |
| php-conf.1                | false                                          |
| php-os                    | Linux                                          |
| private                   | /var/www/files-private                         |
| root                      | /var/www/docroot                               |
| site                      | sites/default                                  |
| stacks.drupal-vm.inited   | false                                          |
| stacks.dev-desktop.inited | false                                          |
| temp                      | /tmp                                           |
| theme                     | sienna                                         |
| themes                    | sites/all/themes                               |
| uri                       | llnl8.docksal                                  |
+---------------------------+------------------------------------------------+
+--------------------------------------+--------------------------------------------------------------+
| Check                                | Problem                                                      |
+--------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkLocalConfig:exists   | tests/behat/local.yml is missing!                            |
|                                      |   Run `blt tests:behat:init:config` to generate it from      |
|                                      | example.local.yml.                                           |
| ConfigCheck:checkGitConfig           | Git repositories are not defined in blt.yml.                 |
|                                      |   Add values for git.remotes to blt.yml to enabled automated |
|                                      | deployment.                                                  |
| NodeCheck:checkNodeVersionFileExists | Neither .nvmrc nor .node-version file found in repo root.    |
+--------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues. 

**Additional context**
Run `composer why-not acquia/blt:10.2.0`

acquia/blt          10.2.0                  requires          dealerdirect/phpcodesniffer-composer-installer (^0.5.0)                   
acquia/blt-project  dev-feature/blt-update  does not require  dealerdirect/phpcodesniffer-composer-installer (but v0.4.4 is installed)

**Comment by danepowell** [comment]
Where is this coming from? `acquia/blt-project dev-feature/blt-update`

It looks like you've been hacking on your project, and it's depending on a custom branch of blt-project. You should not have any dependency on `acquia/blt-project`, and much less a dependency on a custom development branch.

**Comment by shelane** [comment]
I have not been hacking on anything. The very first version of blt I had was 9.0.3 and I've done updates as per instructions each time. However, I did find this line added to my composer.json file `"acquia/blt-require-dev": "^10.0.0-alpha1",` added on 5/3/19. But even after running `composer remove acquia/blt-require-dev` I have still not been able to update blt.

Attached is my composer.json file (renamed to composer.txt for GitHub's sake).
[composer.txt](https://github.com/acquia/blt/files/3363690/composer.txt)

**Comment by shelane** [comment]
... So I see in my composer.json file that it is named blt-project `"name": "acquia/blt-project",` and my git branch is feature/blt-update. That may explain the naming, but not the result.

**Comment by shelane** [comment]
Attempts to remove the vendor/acquia directory and update failed. I then attempted to do `composer remove acquia/blt` (which was successful) and then `composer require acquia/blt`. The later failed with this message:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install acquia/blt 10.2.0
    - Conclusion: remove doctrine/inflector v1.3.0
    - Installation request for acquia/blt ^10.2 -> satisfiable by acquia/blt[10.2.0, 10.x-dev].
    - Conclusion: don't install doctrine/inflector v1.3.0
    - acquia/blt 10.x-dev requires doctrine/inflector ~1.1.0 -> satisfiable by doctrine/inflector[1.1.x-dev, v1.1.0].
    - Can only install one of: doctrine/inflector[1.1.x-dev, v1.3.0].
    - Can only install one of: doctrine/inflector[v1.1.0, v1.3.0].
    - Installation request for doctrine/inflector (locked at v1.3.0) -> satisfiable by doctrine/inflector[v1.3.0].
```

**Comment by danepowell** [comment]
I'm able to run `composer install` on that composer.json file okay, which would seem to indicate that there's nothing inherently wrong with it, but there is some sort of conflict as part of the update process (maybe some other package needs to be whitelisted).

To get around that, try `composer update` with no other arguments. You shouldn't need to explicitly require BLT 10.2.0 if you are already using `^10.0.0` as your version constraint, but if it makes you feel better you can do `composer require acquia/blt:^10.2.0 --no-update` first.

**Comment by shelane** [comment]
Purely running a composer install on that file, it tries to install Drupal 8.6.17, then fails on patches.

**Comment by mikemadison13** [comment]
i wonder if it makes sense to back up to a stable version, check your composer.json file for the blt project (per Dane's suggestion), and then just `composer update acquia/blt --with-all-dependencies` and see if it runs more smoothly? i've found sometimes that once you get into a funky state it helps to back out and start from a known stable point.

**Comment by shelane** [comment]
So, knowing what that "stable version" is can be tricky. We're talking about a ton of existing config that could have been generated due to specific versions...

I removed the patch and it installed Drupal 8.6.17. I try to update drupal, but I get:
```
drupal/lightning_core  3.12.0       requires          drupal/core (~8.6.0)                               
drupal/core            8.7.4        requires          egulias/email-validator (^2.0)                     
acquia/blt-project     dev-develop  does not require  egulias/email-validator (but 1.2.15 is installed)  
```
Somehow my current version has 8.7.4.

**Comment by danepowell** [comment]
When I put your composer.json file into a completely empty directory (no composer.lock or vendor directory) and ran `composer install`, it gave me Drupal 8.7.4 as expected. Are you saying that when you do that, you get Drupal 8.6.17?

If so, that would indicate to me that there's something wrong with your global Composer installation or network infrastructure (a reverse proxy or border router interfering with Composer updates?). Maybe try clearing the composer cache for starters: `composer clear-cache`

**Comment by shelane** [comment]
> Are you saying that when you do that, you get Drupal 8.6.17?
Yes

**Comment by danepowell** [comment]
Did you try `composer clear-cache`?

I think you should figure out why you aren't getting the latest version of Drupal on a fresh install, that's pretty alarming. The best way to do that is to run `composer why-not drupal/core:8.7.4`

**Comment by shelane** [comment]
On a different computer today, so I started from scratch again. I thought I was making really good progress with packages updating correctly
[json-composer.txt](https://github.com/acquia/blt/files/3374537/json-composer.txt)
[Uploading lock-composer.txt…]()

 until I tried to do a site build. I now get this error:
```
Fatal error: require(): Failed opening required '/var/www/vendor/composer/../justinrainbow/json-schema/src/JsonSchema/Validator.php' (include_path='/var/www/vendor/pear/archive_tar:/var/www/vendor/pear/console_getopt:/var/www/vendor/pear/pear-core-minimal/src:/var/www/vendor/pear/pear_exception:.:/usr/local/lib/php') in /var/www/vendor/symfony/class-loader/ApcClassLoader.php on line 112
```

**Comment by dpagini** [comment]
I am actually having the same problem as the OP. Very strange composer issue.

**Comment by mikemadison13** [comment]
every now and again i see issues like the original issue, where composer "somehow loses track" of a dependency that is nestled somewhere down in the depths of another dependency's tree. i've lost behat this way before, and other "pretty important" packages. 

one work around is to manually include that missing dependency in your own composer.json (not great, but it might help). the other is to nuke both your composer.lock and vendor folders and actually run a `composer update.` Obviously this can have unintended consequences, but it's about the only way to totally redraw the dependency tree.

**Comment by dpagini** [comment]
I did try adding the `dealerdirect/phpcodesniffer-composer-installer` to my composer file with no luck. I'd _really_ like to avoid completely blowing everything up, but I'm getting close to a dead end. I'm actually on `acquia/blt:10.0.1` right now, and it will update fine to `10.1.0` but not to `10.2.0`.

**Comment by mikemadison13** [comment]
wait, what happens once you add `dealerdirect/phpcodesniffer-composer-installer` ??? do you get a different error or the same? it's REALLY fishy if you added that and then its still complaining about it being missing @dpagini

**Comment by dpagini** [comment]
`$ composer update dealerdirect/phpcodesniffer-composer-installer` results in:

<img width="1238" alt="Screen Shot 2019-07-10 at 12 32 27 PM" src="https://user-images.githubusercontent.com/1724163/60987084-e77b5500-a30e-11e9-8008-2c59339384c6.png">

But even BLT `10.0.1` [says ^0.4.0](https://github.com/acquia/blt/blob/8a903c1d930f82f4b9ee657d62d123782dd2ed59/composer.json#L25) - so shouldnt that version constraint INCLUDE 0.5.0? Something really fishy here.

**Comment by dpagini** [comment]
So I added the `dealerdirect` package to my composer at `^0.5.0` and set BLT to `^10.2.0` and then ran the following:
```sh
$ composer update dealerdirect/phpcodesniffer-composer-installer acquia/blt sensiolabs-de/deprecation-detector --with-all-dependencies
```

and somehow that worked for me.

**Comment by shelane** [comment]
Thanks @dpagini! That worked for me too and didn't cause the WSOD that I was getting with the method that I tried yesterday.

**Comment by dpagini** [comment]
Any ideas @mikemadison13 or @danepowell how this would happen? Maybe this workaround is fine if anyone else runs into this, just want to make sure there's not some follow-up task to fix this issue...?

**Comment by dpagini** [comment]
Could this be related to #3621?

**Comment by danepowell** [comment]
I'm a little stumped on what happened here. I was never able to reproduce the issue.

I can't see that anyone in this thread ever tried to run `composer update` without any dependencies. I suspect that would have worked around the issue. In general, I find that to be much more predictable than whitelisting packages, even with `--with-all-dependencies`. Those options are new and have had issues in the past: https://github.com/composer/composer/issues/6661

**Comment by shelane** [comment]
I try to avoid `composer update`. I know there have been packages that have been update that cause failures on my site that I've had to lock to a specific version, but my main reason is really being able to tell what is being updated.

**Comment by mikemadison13** [comment]
you definitely shouldn't run `composer update` in most circumstances, but sometimes you just need a bigger hammer :)

**Comment by dpagini** [comment]
Or keep digging down holes that make no sense until something works, I guess. I am due for a general update, I just like to make sure I know most of the packages that get updated piecemeal along the way.

Thanks for the help guys!

**Comment by danepowell** [comment]
I find running `composer update` regularly (weekly / sprintly) to be easier and healthier than only updating individual modules sporadically ("whitelist" updates). Partly for the reasons you discovered in this issue, and partly because if you are only updating individual modules, there are probably dependencies of dependencies somewhere down the chain that are never getting updated.

Whatever works for you of course, but I think this issue is an example of the complexity introduced by whitelisting.

**Comment by RakeshJamesAccess** [comment]
Finally this worked for me 

`composer update dealerdirect/phpcodesniffer-composer-installer acquia/blt sensiolabs-de/deprecation-detector acquia/blt-require-dev --with-all-dependencies`

**Comment by shamsher327** [comment]
`composer require --dev drupal/coder:^8.2.11
composer update dealerdirect/phpcodesniffer-composer-installer acquia/blt sensiolabs-de/deprecation-detector --with-all-dependencies
vendor/bin/phpcs -i
vendor/bin/phpcs --standard=Drupal,DrupalPractice docroot/modules/contrib/module/**/*
vendor/bin/phpcbf --standard=Drupal,DrupalPractice docroot/modules/contrib/module/**/*`
