### ISSUE TITLE
"composer run-script blt-alias" can't run on newly created project

### ISSUE THREAD

**Issue by zekeweeks** [acquia/blt#3748]
**Describe the bug**
Hello! I am trying to create a new project per docs/creating-new-project.md, but it looks like something may be missing in terms of composer requirements files that prevents me from running the blt-alias script.

The only places the string 'blt-alias' occurs in the directory made by create-project are in these markdown files:
README.md
vendor/acquia/blt/CHANGELOG.md
vendor/acquia/blt/docs/FAQ.md
**vendor/acquia/blt/subtree-splits/blt-project/README-template.md** <- Perhaps something hasn't moved properly to subtree splits?

I noticed in an [old comment on a similar issue](https://github.com/acquia/blt/issues/2337#issuecomment-349749325) that there used to be some references to `vendor/acquia/blt/template/composer.json` and `vendor/acquia/blt/composer.required.json`in generated projects.

And it looks like there were some recent moves happening between the template directory and the subtree-splits directory. Perhaps something has been lost there?

I did eventually track down the way to manually invoke `blt:init:shell-alias`, so my own efforts are no longer blocked. But as far as I can tell, I followed the documents and was unable to successfully set up a new BLT project that way.

**To Reproduce**
1. Run `composer create-project acquia/blt-project --no-interaction exampleproject`
2. Run `cd exampleproject`
3. run `composer run-script blt-alias`
4. Command fails, nothing is added to ~/.bash_profile, I don't know how to execute blt otherwise without learning how that script worked before.

**Expected behavior**
I assume this script adds an alias to run the blt command in ~/.bash_profile .

**Detailed error output**
`[InvalidArgumentException]                         
  Script "blt-alias" is not defined in this package`

**BLT doctor output**
N/A - could not run BLT

**System information**
* Operating system type: macOS
* Operating system version: 10.14.5
* BLT version: 10.2.0
* all dependencies installed before creating the project with composer (git, homebrew, composer, prestissimo, composer-drupal-optimizations )

**Comment by danepowell** [comment]
Where are you seeing an instruction to run `composer run-script blt-alias`? The current version of the `creating-new-project` page that you referred to has no such reference: https://github.com/acquia/blt/blob/10.x/docs/creating-new-project.md

**Comment by zekeweeks** [comment]
Trying to look back to the stuff I was referencing when I opened this issue and now I can't find what led me to try that. Sorry, but thanks for the help and response! :-)
