### ISSUE TITLE
Make BLT settings platform agnostic and pluggable 

### ISSUE THREAD

**Issue by christopher-hopper** [acquia/blt#3749]
**Is your feature request related to a problem? Please describe.**

As a large team, using Acquia BLT across a number of clients,  I want the flexibility to rely on BLT no matter what platforms are the best fit for the client. That could be any mix of the following: 

- Acquia Cloud pro
- Acquia Cloud Site Factory 
- Amazee.io Lagoon
- Azure Devops Pipelines
- Bitbucket  pipelines
- Buildkite
- Circle-CI
- Gitlab Pipelines
- Panetheon
- Platform.sh
- Probo
- Travis-ci  
- Tugboat.QA
- Bespoke or Self-hosted

Currenlty, the environment detection patterns written into BLT rely on some hard-coded assumptions around platforms offered by a handful of platform providers. To use a provider not currently accounted for requires either:

- Overriding settings, config split detections, and other settings values after BLT is done (quick dirty option)
- Try to shoe-horn another platform into various places using the current catch-all  Environment detection class and various settings includes
- Hand-writing your own settings and ignoring BLT settings include altogether (worst option)

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

I'd like to see a Platform Environment detection and settings model that was pluggable, extendable and had a  consistent, predictable interface.

If platforms or individuals could implement a consistent Platform and Environment detection interface we could decouple the detections from each other and the settings  includes. This will allow composer installable packages with their own, plug-ins to do detections.

You perhaps could detect the platform, set the appropriate Platform class to use for Environment detection, and then away you go?

If the Platform cannot be detected, a base implementation could either default to "local" or throw an exception.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

I've  looked  at  how  some other platforms  define their platform specific  settings. Some use environment variables, other use PHP includes written for Drupal. There are many platforms out there and hosting and testing ecosystem that is growing.

**Additional context**
> Add any other context or screenshots about the feature request here.

BLT used to pass around  a lot of GLOBAL state variables for platform/environment detection and use  in various settings includes. The blt.settings.php leave  behind much less GLOBAL state values now, which is great. 

It would be good to see a more  predictable, secure settings include pattern that was more easily extensible going forward.

**Comment by danepowell** [comment]
@christopher-hopper would what you are trying to accomplish be satisfied by https://github.com/acquia/blt/issues/3645 ? There's already PR associated with that, I'd appreciate your review. Once that's finished there will also be some example plugins that will demonstrate how to override settings in the way you've described.

**Comment by christopher-hopper** [comment]
Brilliant. Thanks for the link. I'll watch that

--
Christopher Hopper
