### ISSUE TITLE
Use drupol/phposinfo

### ISSUE THREAD

**Issue by drupol** [acquia/blt#3750]
It seems that tivie/php-os-detector is a dependency and it can produces false results, see the corresponding issue: https://github.com/tivie/php-os-detector/issues/3

Based on this, I've created my own package: [drupol/phposinfo](https://packagist.org/packages/drupol/phposinfo) that fixes the issue.

This issue is to propose the replacement of tivie/php-os-detector with drupol/phposinfo.

**Comment by danepowell** [comment]
I agree this sounds like a bug in php-os-detector, but it's a bit of an edge case. I've never heard of folks using cross-built versions of PHP until now. I'm not saying it doesn't happen, I'm just saying it doesn't seem common.

tivie/php-os-detector has orders of magnitude more installs than drupol/phposinfo and is relatively battle-tested by comparison, so I don't think it makes sense to switch on this basis alone. At the very least we should give tivie a chance to fix their package first.

**Comment by drupol** [comment]
Thanks for the answer I understand. That said, the package I made is tested on Linux, Windows and Mac OS X.

Regarding the maintainer, I've tried to contact him, but got no reply so far and he seems to be pretty inactive on Github.

I let you decide what to do, but count on me if you need some help on using my package in your package.

Thanks.

**Comment by danepowell** [comment]
Even though this is an edge case, I agree it's simply wrong for php-os-detector to be using PHP_OS when a clearly superior alternative exists. Since it seems like that's not going to get fixed upstream, I've opened a PR to switch.
