### ISSUE TITLE
EnvironmentDetector ACE issues on 10.2.x

### ISSUE THREAD

**Issue by rjgwiz** [acquia/blt#3755]
**Describe the bug**

In `EnvironmentDetector`, `isAhStageEnv()` is coming back false on Test and `isAhDevEnv()` is coming back false on Dev.

In #3724 , regexes were updated for example from `/^\d*test$/` to `/^\d+test$/`. On ACE `test` and `dev` no longer match the regex, and it doesn't look like `01dev` or `dev1` would either, because `+` and `*` are not interchangeable

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:

Check the output of `EnvironmentDetector::isAhDevEnv()` on an ACE non-prod environment, or on your local temporarily set `$_ENV['AH_SITE_ENVIRONMENT'] = 'dev';` then debug the result of `isAhDevEnv()`

**Comment by UTCGilligan** [comment]
Would this explain why ACE config splits are not working after upgrade of BLT to 10.2? 

e.g. Environment indicators are all showing as Default in ACE, and config sync 
/admin/config/development/configuration
reports: "You are not using any config split configuration"

**Comment by danepowell** [comment]
I can confirm that this bug exists. We should also add a unit test for the EnvironmentDetector class to prevent this from regressing.
