### ISSUE TITLE
drupal-check forces to use PHP 7.3

### ISSUE THREAD

**Issue by jayakrishnanj** [acquia/blt#3761]
Updated Project Repo to Latest BLT v10.2.0.
![image](https://user-images.githubusercontent.com/19162800/61510939-a66ff880-aa12-11e9-9290-b046628ba923.png)

You can see in the above screenshot, mglaman/drupal-check ^1.0.10 includes `jean85/pretty-package-versions ^1.2` as dependency and ocramius/package-versions ^1.2.0 is added as depedency as a child.

By default ocramius/package-versions package is updating to stable version of '1.5.0' which needs PHP 7.3 [https://packagist.org/packages/ocramius/package-versions#1.5.0]
Due to the above case, BLT is forcing to update project to PHP 7.3 version.

is there any possibility to degrade ocramius/package version to 1.4.0 ?

* BLT version: [10.2.0]

cc: @mikemadison13 Related to https://github.com/acquia/blt/pull/3710

**Comment by jayakrishnanj** [comment]
For now, Resolved using `composer require ocramius/package-versions:1.4.0` Please let me know if this is right way to resolve the issue ?

**Comment by danepowell** [comment]
How did you initially come to have ocramius/package-versions:1.5.x installed? My guess is that you created the project or ran composer update on a machine with PHP 7.3 installed, and then tried to run it on a machine without it.

Always run `composer update` in an environment with your minimum supported PHP version. If that's not possible for some reason, then yes you will need to manually restrict package versions that require higher PHP versions.

**Comment by danepowell** [comment]
Actually instead of pinning that one package, try running `composer config platform.php 7.1 && composer update` and see if that pins downstream packages to a 7.1-compatible version. If so, maybe we should add that to blt-project/composer.json.

https://andy-carter.com/blog/composer-php-platform

**Comment by jayakrishnanj** [comment]
Thank you @danepowell , Awesome as usual :)

That resolved the issue, Kept local environment PHP to 7.3 to stay ahead but sometimes that gives these issues.
Fixed my project repo with the platform.php 7.2 and also setting up my local PHP to 7.2 :)

Created PR https://github.com/acquia/blt/pull/3769 to fix the composer php version
