### ISSUE TITLE
Git commit fails due to yaml linting failure

### ISSUE THREAD

**Issue by philltran** [acquia/blt#3767]
Oh my... my detailed bug ticket was reset to default when I clicked on the pop-up to try the new beta github feature...

**Describe the bug**
Pre-commit validation fails on yaml linting of large number of config changes

**To Reproduce**
1. Add a bunch of yaml files to a commit (like 1000) `git add config/directory`
2. Try to commit the yaml files `git commit -m 'Commit message'`
3.  See error
```
[error]  Executing `'.../vendor/bin/yaml-cli' lint '%s'` against fileset(s) files.yaml returned a non-zero exit code.` 
[CompletionWrapper]  Command `tests:yaml:lint:files 'config/directory/'

```

**Expected behavior**
Either the commit to be successful or the linting tool to return list of files and issues.

**Detailed error output**
```
[error]  Executing `'.../vendor/bin/yaml-cli' lint '%s'` against fileset(s) files.yaml returned a non-zero exit code.` 
[CompletionWrapper]  Command `tests:yaml:lint:files 'config/directory/'
```

**System information**
* Operating system type: Linux
* Operating system version: POP ubuntu 18.04
* BLT version: 10.2.0

**Additional context**
Running yaml linting via `blt tests:yaml:lint:all' returned that the repo's yaml files were valid.

Changing the linting command to run in parallel allowed the validation to pass. I am not sure if that change would cause an validation error to get through linting.
[blt/src/Robo/Commands/Validate/YamlCommand.php:56](https://github.com/acquia/blt/blob/46203b6c9c55ef142c9bd9150c7e6d2a14bfd5a0/src/Robo/Commands/Validate/YamlCommand.php#L56)
`$this->executeCommandAgainstFilesets($filesets, $command, TRUE);`

**Comment by danepowell** [comment]
I can't reproduce this. I tried committing over 1000 yml files and it worked fine, although it took a few seconds. Do you have any theories on why this might be failing, or tips to reproduce?

Try invoking the pre-commit hook directly but with verbose output to see if you can get more information on the error:
```
#!/usr/bin/env bash

ROOT_DIR="$(pwd)/"
LIST=$( git diff --name-only --cached --diff-filter=ACM )
PHPCS_BIN=vendor/bin/phpcs

echo "Executing .git/hooks/pre-commit..."
"${ROOT_DIR}"/vendor/bin/blt internal:git-hook:execute:pre-commit -vvv "${LIST}"

# Return the status of the last run command.
exit $?
```

Also there must be additional logs beyond what you posted, please post the entire command log.

**Comment by philltran** [comment]
@danepowell 

Thanks for looking into this. I ran the code with verbose output. Could this be a limitation of my local machine?

Changing the linting command to run in parallel allowed the validation to pass. I am not sure if that change would cause an validation error anywhere else.
/vendor/blt/src/Robo/Commands/Validate/YamlCommand.php:56

> $this->executeCommandAgainstFilesets($filesets, $command, **TRUE**);

Attached is the last 3000 lines of the pre-commit command run procedurally.
 (It was too long to post inline.)
[pre-commit.txt](https://github.com/acquia/blt/files/3428823/pre-commit.txt)
