### ISSUE TITLE
BLT setup - Mysql is not available

### ISSUE THREAD

**Issue by jancy-vj** [acquia/blt#3776]
When upgraded lightning to 3.2.0 (drupal core 8.6.X), it requires blt to be updated to 9.2.x.
So I have upgraded my BLT to 9.2.8, now when I do BLT setup, I am getting the below error.  

![Mysql_Error](https://user-images.githubusercontent.com/51784963/61948412-6803ac00-afc5-11e9-945e-0438a00284d0.png)

When should I run the BLT update command?
What files should I commit when my BLT is updated, also note my drush got updated from 8 to 9?
Thanks for your feedback. 

**System information**
* BLT version: 9.2.8

**Comment by ramalingam07** [comment]
I am also facing this same issue
```
[error]  MySql is not available. Please run `blt doctor` to diagnose the issue.
[error]  Command `drupal:install ` exited with code 1.
```
I found the below solution. Ref: [https://github.com/acquia/blt/issues/2594](https://github.com/acquia/blt/issues/2594). It's working only after I get the Mysql error.
It's not working If commit earlier.

```
diff --git a/src/Robo/Commands/Setup/DrupalCommand.php b/src/Robo/Commands/Setup/DrupalCommand.php
index d3f6efc..f6e3908 100644
--- a/src/Robo/Commands/Setup/DrupalCommand.php
+++ b/src/Robo/Commands/Setup/DrupalCommand.php
@@ -16,6 +16,7 @@ class DrupalCommand extends BltTasks {
    *
    * @command internal:drupal:install
    *
+   * @executeInDrupalVm
    * @validateMySqlAvailable
    * @validateDrushConfig
    * @hidden
```

**Comment by danepowell** [comment]
BLT 9 no longer supports running BLT commands outside the VM. You must run them in the VM where MySQL is available.

This is documented extensively in the release notes: https://github.com/acquia/blt/releases/tag/9.0.0

You should really read those notes, there are quite a number of additional potentially breaking changes.

**Comment by ramalingam07** [comment]
@danepowell It's working fine to me.
Thanks for your comment.

**Comment by jancy-vj** [comment]
@danepowell Thank you
