### ISSUE TITLE
Multi-site drush site config - root

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3783]
**Describe the bug**
This is not an urgent bug, but it's just enough to bother me, so I want to report it with a suggested path forward.
In #3614 some code was put in to set the "root" drush config value for multisite aliases, and it was set to `'${env.cwd}/docroot'` which allows `$ blt setup` commands for multisite to start working. This is due to (related to) the drush bug drush-ops/drush#4059. This appears to **only** be a problem with the `site-install` command. However, what I found is that the value of this `root` config has no bearing on the site-install command. I am able to set this to blank string, random values, or what BLT is setting it to. 
Since we are setting it to the "current working directory" plus "/docroot" - if you call the drush command from the project root, everything should work fine. If you call drush from your `docroot/sites/default` folder, presumably, your "root" config value would be wrong now. I don't know that it impacts other commands, but we know it's wrong at that point and could break things in the future.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Set up a brand new BLT site.
2. Run `$ blt recipes:multisite:init` with default options.
3. Run `$ blt setup --site=example` and see it succeed.
4. Change the file `drush/sites/example.site.yml` and the config key `local.root` to blank. Re-run BLT setup command and it should pass.
5. Change the file `drush/sites/example.site.yml` and the config key `local.root` to `'anything'`. Re-run BLT setup command and it should pass.

**Expected behavior**
I expect all of these to pass. I cannot come up with a drush command that would use the root that would fail from one directory but pass in another, but I'm _sure_ there is a command that would use that... right?

**Proposed solution**
I personally think we should get rid of this `local.root` value if we know it's wrong. Can BLT not just pass `--root _____` to the `site-install` command as a command line parameter when it calls `site-install`? That's the ONLY reason this config entry is present - right? 

That would allow us to be sure we aren't breaking something in the future, IMO.

**Comment by danepowell** [comment]
Just to make sure I understand, it doesn't seem like this is a bug with BLT, since it's not actually breaking any sort of functionality, right? It's more just cruft that we could refactor out, until/unless it's fixed upstream in Drush.

Assuming that's right, I think it would make the most sense to try to tackle that upstream bug. Passing the root value as a parameter is marginally better, but still effectively cruft right?

**Comment by dpagini** [comment]
I think there _might_ be a bug here, but I haven't dove very deep. I mean, we could probably agree that setting the docroot to the `cwd` will only be accurate when `$ drush` is invoked from the repo root, right? If I call `$ drush` FROM './docroot`, the root option would then be set to an invalid path... right?

**Comment by danepowell** [comment]
I'm not clear on what the action items are for BLT here, so I'm taking this out of the roadmap for now.
