### ISSUE TITLE
DT-657: examples:init command is redundant

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3785]
The examples:init command seems pretty much useless right now, since it automatically gets run when creating a new project. The only reason anyone would need to run it is maybe if they deleted those files from their codebase for some reason.

I see two possible solutions:
- Just remove the command and incorporate those files into the project template.
- Stop running the command automatically, and instead maybe split it up and move it into the recipes namespace. So people could run a recipe to set up an example Behat test, another to set up an example custom Command, etc...

I wish we had metrics on how many people actually use hte example Behat test, command files, and other templates. My guess is probably not many.

**Comment by dpagini** [comment]
Just some $0.02. Love the idea of moving it to the `recipes` namespace, and splitting up. I imagine you could have an example for the EnvironmentDetector in addition to what's there now. I know I found the examples very helpful early on. I know I actually fell into the... deleted the examples files, and then ran them again.
