### ISSUE TITLE
Add drush config per site in BLT

### ISSUE THREAD

**Issue by ndobromirov** [acquia/blt#3789]
**Is your feature request related to a problem? Please describe.**
This is aimed as a workaround for drush limitation / bug / missing feature: 
https://github.com/drush-ops/drush/issues/3968

The idea is to have a set of `drush.yml` config files that will be always added to each drush command as additional configurations.

**Describe the solution you'd like**
There should be a new section in the `blt.yml` for drush that should be a list of files to be included.
As BLT already supports global configuration and per-site one, this list can be extended on per site level and thus work-around the limitation in Drush.

**Describe alternatives you've considered**
Fixing the root cause in Drush.

**Additional context**
Alternative solutions that are currently available are non-practical. I do not have access to a per-site environment variables.
And the other option is to push the include configs through BLT in a greedy manner every time that is provided and that is non-practical as well, unless BLT somehow supports it, as described above or similar.

**Comment by dpagini** [comment]
This is an interesting idea... the only issue I see is that BLT commands will run drush commands _differently_ than just calling drush directly, and it won't be very apparent why. Not saying that's a reason not to do this, but just something that jumped out to me...

**Comment by ndobromirov** [comment]
Updated description to be more clear...

**Comment by ndobromirov** [comment]
With the verbose option you will see what commands are executed and you will see the included configs either way. I do not see this as a blocker.

**Comment by danepowell** [comment]
This seems like a clunky workaround to just fixing this properly in Drush. I think fixing it upstream should be the priority.

Also what specifically are you trying to override on a per-site basis? The only option I've ever seen used is the `uri` as I mentioned in the upstream issue, which could be accomplished other ways (sites.php).

**Comment by ndobromirov** [comment]
I want to overwrite the temporary folder for Drush per site in a shared server.

Whenever I start executing `blt deploy:update` on a single machine multiple times concurrently, it is always starting with `drush cc drush` command. Whenever there is concurrent execution of this command on the same box, it results in errors that are pure race conditions over the temp folder.

The only stable work-around this is to have different temp folder for each site that is running the command. As of the moment in my environment there is no way to have that configured.

I am 100% a +1 on the fix upstream, but I do not have the time to push there... 
I was hoping that either BLT can easily solve it, or at least make it more visible as in issue in the BLT queue as well so a person can fix it upstream.

The only workaround I can think of with custom code is to have a custom command that will do the same things as `deploy:update` except the `drush cc drush` so I will run it only one time and then run the rest in parallel without issues. The thing is I do not like this solution as well, as it's just another ugly work-around.

**Comment by danepowell** [comment]
If the only use case here is to avoid cache collisions, you would be better off setting the DRUSH_PATHS_CACHE_DIRECTORY environment variable prior to running BLT commands, as BLT already does for ACSF: https://github.com/acquia/blt/blob/10.x/scripts/factory-hooks/db-update/db-update.sh#L40

Are you saying you can't do that? I'm curious what sort of hosting environment you are using that allows you to run BLT, but doesn't let you set an environment variable prior to running it.

**Comment by ndobromirov** [comment]
I've tested the exact same syntax before opening the issue, though it did not solve the concurrency problem for me :(...

**Comment by danepowell** [comment]
If you are continuing to have concurrency issues, please open a Support ticket or new BLT ticket specific to that issue. BLT has very little to do with that other than providing the template cloud hooks; the same error would result if you run the Drush commands directly. This issue needs to be addressed in Drush, Symfony, or possibly your implementation of the cloud hooks, but I don't think a new BLT feature would be appropriate here.
