### ISSUE TITLE
drupal:sync:default:site plugin does not exist before sql-sanitise

### ISSUE THREAD

**Issue by leonk** [acquia/blt#3791]
**Describe the bug**
Previously `drupal:sync:default:site` was running fine.  But since installing focal_point module (which contains a new image effect) it now errors just before `sql-sanitise`.  

```
...
 [success] No text fields for users need sanitizing.

In DiscoveryTrait.php line 53:

  The "focal_point_scale_and_crop" plugin does not exist. Valid plugin IDs fo
  r Drupal\image\ImageEffectManager are: crop_crop, image_convert, image_crop
  , image_desaturate, image_resize, image_rotate, image_scale_and_crop, image
  _scale
```
The `focal_point_scale_and_crop` plugin _does_ exists on the source db, I am unsure as to why it is not being picked up at this point.  However, if I run each command from `drupal:sync:default:site` manually, and then run a `drush cr` just before `drush sql-sanitize` is run, it works without any issues.

**To Reproduce**
1. Run `drupal:sync:default:site` on a site with focal_point module installed, (and using the focal_point image effect on at least one image style).

**Detailed error output**
<img width="565" alt="Screenshot 2019-08-02 at 15 34 28" src="https://user-images.githubusercontent.com/436483/62377626-0b5f3e80-b53b-11e9-8353-8ca218f15260.png">

**System information**
* BLT version:  10.2.1

**Comment by danepowell** [comment]
@leonk are you using memcache or APC / zend caching? If so the memory cache is likely out of sync with the database.

**Comment by leonk** [comment]
Hi @danepowell yes we are using memcache on Acquia Cloud Site Factory.  The setup we have is taken from here: https://www.drupal.org/node/2766509
