### ISSUE TITLE
Environment Detector for on prem LAMP environments

### ISSUE THREAD

**Issue by shelane** [acquia/blt#3795]
We have an on prem Linux server that we use to stage content for review (behind our firewall) that will then be published to our production Drupal environment on Acquia CE. However, it seems all BLT commands we try to run believe the server is "local." Since "local" files are not included in the repo, the files that blt is looking for do not exist. We need to specify that the environment is production, but not on ACE. It appears that the EnvironmentDetector class is looking for ACE or Pantheon environments, defined CI environments, and assumes if it's none of those, it must be local. We have our own detection scripts to determine that required settings files are on available and therefore, it is on that environment and those files are included. However, this doesn't stop BLT from wanting to use local drush aliases, wanting to force and include of a local.settings.php file, etc.

How can we specify this is production on environment "onPremStage" or "onPremDev" as we have?

**Comment by danepowell** [comment]
Good question. You would need to create a plugin that overrides EnvironmentDetector::isProdEnv (or isStageEnv or whichever environment you want it to appear as) to return true for your on-prem server.

You can find a reference plugin that does something similar here: https://github.com/acquia/blt-tugboat

Note that you have to explicitly expose your custom detector via PSR4: https://github.com/acquia/blt-tugboat/blob/master/composer.json

Let me know how that works for you. We should probably provide documentation for this in https://github.com/acquia/blt/blob/10.x/docs/extending-blt.md

**Comment by shelane** [comment]
@danepowell I know that it has been month since you first made these changes and I have finally been able to focus my attention on this issue for us. We are using BLT 11.3.0.

I have added this to my composer.json file of my project:
```
    "autoload": {
        "psr-4": {
            "Custom\\": "blt/src/"
        },
        "classmap":["blt/src/Blt/Plugin/EnvironmentDetector/OnPremDetector.php"]
    },
```

I created the file `blt/src/Blt/Plugin/EnvironmentDetector/OnPremDetector.php`
The beginning is set with:
```
namespace Custom\Blt\Plugin\EnvironmentDetector;

use Acquia\Blt\Robo\Common\EnvironmentDetector;

class OnPremDetector extends EnvironmentDetector {
```

I have a custom command in `blt/src/Blt/Plugin/Commands/SiteCommand.php`

It is set with:
```
namespace Custom\Blt\Plugin\Commands;

use Acquia\Blt\Robo\BltTasks;
use Custom\Blt\Plugin\EnvironmentDetector;
use Acquia\Blt\Robo\Exceptions\BltException;
use Symfony\Component\Console\Style\SymfonyStyle;
```
PHPstorm shows all uses of `EnvironmentDetector` as an undefined class. When it tried to run in Acquia Cloud, it gave us this message:
```
PHP Fatal error:  Uncaught Error: Class 'Custom\Blt\Plugin\Commands\EnvironmentDetector' not found in /mnt/www/html/ourappdev/blt/src/Blt/Plugin/Commands/SiteCommand.php:39
```

Is there something obvious that I'm just missing?

**Comment by danepowell** [comment]
What's line 39 of SiteCommand.php? It sounds like just a namespacing issue, i.e. you need to fully qualify which environment detector class you are trying to load there.

**Comment by shelane** [comment]
Line 39 is:
```
if (EnvironmentDetector::isAhEnv()) {
```
It is the first time this is called. As you can see above, my SiteCommand.php file does not have `use Acquia\Blt\Robo\Common\EnvironmentDetector;` because I am trying to include mine which does have that use statement and extends the `EnvironmentDetector` class. However, including `use Custom\Blt\Plugin\EnvironmentDetector;` doesn't seem to be recognizing it.

**Comment by danepowell** [comment]
The class name of your own detector is `OnPremDetector`, not `EnvironmentDetector`. So wouldn't line 39 need to be `if (OnPremDetector::isAhEnv()) {`?

Also I'm surprised you want to call OnPremDetector::isAhEnv() in the first place. I'm not sure exactly what you are trying to accomplish, but I wouldn't expect anyone to have to override isAhEnv(). In which case you could just call BLT's environment detector instead of your own. For supported methods (not isAhEnv() though) it will automatically redispatch to your own detector.

**Comment by shelane** [comment]
I was the actual EnvironmentDetector::isAhEnv and then my own:
```
if (EnvironmentDetector::isAhEnv()) {
      //do these things
}
else(OnPremDetector::isOnPremEnv()) {
   //do these things instead
}
```

I'm not trying to override isAhEnv. I'm am overriding/supplementing  `isLocalEnv`, `isProdEnv`, `isDevEnv`, and `isCiEnv`.

**Comment by danepowell** [comment]
Then you need to either use the fully qualified class name (`\Acquia\Blt\Robo\Common\EnvironmentDetector`, off the top of my head) or correct your use statement (`use Acquia\Blt\Robo\Common\EnvironmentDetector`).

Your current use statement is not valid:
`use Custom\Blt\Plugin\EnvironmentDetector;`

That's not going to point to BLT's detector as you intend, and it's also not going to point to your custom one (which is named `OnPremDetector`).

**Comment by shelane** [comment]
Yes, you are correct in that. Currently, my OnPremDetector class is working in the custom command. It's working locally and on my "on prem" server. However, something is wrong now with it on Acquia. I won't know for several more hours because something happened where this check `if ($this->getInspector()->isDrupalInstalled()) {` is returning false for all of my sites on ACE dev and it's currently reinstalling all 40 multisites. Since that takes 10 minutes each, it's going to be a few hours before I can see the output of the console from the update hook.

**Comment by shelane** [comment]
This is the entire OnPremDetector class:

```
<?php

namespace LLNL\Blt\Plugin\EnvironmentDetector;

use Acquia\Blt\Robo\Common\EnvironmentDetector;

class OnPremDetector extends EnvironmentDetector {

  /**
   * Is OnPrem env.
   */
  public static function isOnPremEnv() {
    return isset($_ENV['ONPREM']);
  }

  /**
   * Is local.
   */
  public static function isLocalEnv() {
    return !self::isAhEnv() && !self::isCiEnv() && !self::isOnPremEnv();
  }

  /**
   * Is dev.
   */
  public static function isDevEnv() {
    return (bool) self::isOnPremDevEnv();
  }

  /**
   * Is prod.
   */
  public static function isProdEnv() {
    return (bool) self::isOnPremProdEnv();
  }

  /**
   * Is onprem dev.
   */
  public static function isOnPremDevEnv() {
    return self::getOnPremEnv() == 'stage_dev';
  }

  /**
   * Is onprem stage.
   */
  public static function isOnPremStageEnv() {
    return self::getOnPremEnv() == 'stage';
  }

  /**
   * Is onprem prod.
   */
  public static function isOnPremProdEnv() {
    return (bool) self::isOnPremStageEnv();
  }

  /**
   * Get OnPrem env.
   */
  public static function getOnPremEnv() {
    if (getenv('ONPREM_ENVIRONMENT')) {
      return getenv('ONPREM_ENVIRONMENT');
    }
    elseif (isset($_ENV['ONPREM_ENVIRONMENT']) && $_ENV['ONPREM_ENVIRONMENT']) {
      return $_ENV['ONPREM_ENVIRONMENT'];
    }
    $current_path = __FILE__;
    if (strpos($current_path, '/opt/www/dev/') !== FALSE) {
      return "stage_dev";
    }
    elseif (strpos($current_path, '/opt/www/stage/') !== FALSE) {
      return "stage";
    }
    return NULL;
  }

}
```

**Comment by danepowell** [comment]
Glad you got it sorted. If you have any specific recommendations for how to improve the user experience or documentation going forward, feel free to comment or open a new issue. In the meantime I'll close this.
