### ISSUE TITLE
DT-676: "Could not scan for classes" notices back in Composer 1.9.0.

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3807]
We took a belt-and-suspenders approach to fixing #3148 by both implementing an immediate workaround, and submitting an upstream fix to Composer.

Apparently with the release of Composer 1.9.0, both of these are failing again (or they are interacting poorly), and the exact same behavior has returned. Nothing obvious (e.g. composer nuke) seems to fix it.

As a temporary workaround, I would recommend downgrading Composer. I don't see anything critical  in 1.9.0 that most people would need.

**Comment by lpeabody** [comment]
In reference to comment https://github.com/acquia/blt/pull/3701#issuecomment-519611711, I am seeing these warnings again for BLT 9.2.x and Composer 1.9.0:

```
[les.peabody@~/Sites/corvette (feature/docksal-composer)]
-> fin exec blt --version
BLT 9.2.8

[les.peabody@~/Sites/corvette (feature/docksal-composer)]
-> fin exec composer --version
Could not scan for classes inside "/var/www/vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/vendor/drupal/core/lib/Drupal/Component/Utility/Timer.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/vendor/drupal/core/lib/Drupal/Component/Utility/Unicode.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/vendor/drupal/core/lib/Drupal/Core/Database/Database.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/vendor/drupal/core/lib/Drupal/Core/DrupalKernel.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/vendor/drupal/core/lib/Drupal/Core/DrupalKernelInterface.php" which does not appear to be a file nor a folder
Could not scan for classes inside "/var/www/vendor/drupal/core/lib/Drupal/Core/Site/Settings.php" which does not appear to be a file nor a folder
Composer version 1.9.0 2019-08-02 20:55:32
```

Seems like a regression on Composer's side.

**Comment by lpeabody** [comment]
Wanted to find some quick comparisons, I did find this:
https://github.com/composer/composer/blob/1.9.0/src/Composer/Plugin/PluginManager.php#L255
vs
https://github.com/composer/composer/blob/1.8.6/src/Composer/Plugin/PluginManager.php#L254

In 1.9 load repository is explicitly invoking `PackageSorter::sortPackages`, where in 1.8.6 this is not being invoked. Yet, we don't see the issue in 1.8.6. I also tested this on Composer 1.6.x versions and 1.7.x versions and did not see any "Could not scan" warnings with any of them, only 1.9.0.

**Comment by jwaskewicz** [comment]
Is this issue back with Composer 1.9.1?

**Comment by danepowell** [comment]
@jwaskewicz not that I've seen. Do you have steps to reproduce the issue? If so please open a new BLT ticket.

Note that there are some deprecation warnings (also yellow) that are unrelated to this issue or BLT.
