### ISSUE TITLE
DT-728: Update docs for alternative environments

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3828]
**Is your feature request related to a problem? Please describe.**
BLT 10 plugins now exist (see https://github.com/docksal/blt-docksal and https://github.com/lcatlett/blt-ddev) which automate and supersede the current manual setup instructions for both [ddev](https://github.com/acquia/blt/blob/10.x/docs/alternative-environment-tips/ddev.md) and [docksal](https://github.com/acquia/blt/blob/10.x/docs/alternative-environment-tips/docksal.md) so the BLT alternative environment docs should be updated as such. Given https://github.com/acquia/blt/issues/3825 it may make sense to replace these docs entirely in favor of creating a BLT plugins directory page

**Comment by danepowell** [comment]
That's awesome, I didn't even realize those plugins existed. I definitely agree, let's pull those out of the core BLT docs, and add a plugin directory.
