### ISSUE TITLE
blt command not found error

### ISSUE THREAD

**Issue by saiprasadmca007** [acquia/blt#3830]
**Describe the bug**
The command "blt vm" is giving error as "blt command not found"

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT in windows 10:
1. Run `composer create-project acquia/blt-project --no-interaction`
2. Run "blt vm"
3. See error

**Expected behavior**
Blt should work

**Detailed error output**
If a BLT command is failing, run it again with the `-vvv` argument and post the full output here.
Getting error "blt command not found"

**BLT doctor output**
Post the full output of `blt doctor` in the failing environment here.
Getting error "blt command not found"

**System information**
* Operating system type: Windows
* Operating system version: 10
* BLT version: 10

**Additional context**
I installed vagrant and virtual box also. but no result.

**Comment by danepowell** [comment]
BLT is only supported on Windows via the Windows Subsystem for Linux (WSL). It sounds like you are not using WSL, can you confirm?

https://github.com/acquia/blt/blob/10.x/docs/windows-install.md
