### ISSUE TITLE
DT-743: Project creation, updates fail due to conflicting dependencies

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3835]
This is not a BLT bug per se, but an upstream problem with Drupal, webflo/drupal-core-require-dev, and Mink:
- https://github.com/minkphp/MinkSelenium2Driver/issues/313
- https://www.drupal.org/project/drupal/issues/3078671

This makes it impossible to create new BLT projects, or to run composer install / update in some circumstances. Errors like this:

```
Problem 1
    - Installation request for webflo/drupal-core-require-dev 8.7.6 -> satisfiable by webflo/drupal-core-require-dev[8.7.6].
    - webflo/drupal-core-require-dev 8.7.6 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
```

The best workaround I see is to add a branch alias as described here: https://github.com/minkphp/MinkSelenium2Driver/issues/313#issuecomment-527165233

I think end users should do this manually for now while we wait to see how the upstream issues are or aren't resolved, and then BLT can do it via an update hook if necessary.

Long term, we should consider removing webflo to decrease the risk of issues like this: https://github.com/acquia/blt/issues/3838

**Comment by josephdpurcell** [comment]
If using Lightning 4, see https://github.com/acquia/blt/issues/3840 for a recommendation on how to work around this issue.

**Comment by danepowell** [comment]
This has been fixed upstream, any users that applied a workaround should remove it.
