### ISSUE TITLE
How to upgrade Acquia Lightning 4 due to #3835

### ISSUE THREAD

**Issue by josephdpurcell** [acquia/blt#3840]
**I want to...**
I want to upgrade Acquia lightning from 4.0.0 to 4.0.4.

**It's not working because...**
Per the Acquia update instructions (see draft https://docs.google.com/document/d/1oTH5T1ZinHJbCBT329lMBpXa2YTB9SHtIOiqBH6JIRY/edit) when running `composer update` the following error occurs:

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - webflo/drupal-core-require-dev 8.8.x-dev requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
```

**Detailed error output**
The BLT command isn't failing. The failure is related to the dependencies of BLT.

**BLT doctor output**
NA

**System information**
* Operating system type: Ubuntu
* Operating system version: 16.04
* BLT version: 9.2.8

# Proposed Solution

Change your composer.json from:

```
     "require-dev": {
         "geerlingguy/drupal-vm": "^4.9",
         "webflo/drupal-core-require-dev": "~8.6"
     },
```

To be:

```
     "require-dev": {
         "geerlingguy/drupal-vm": "^4.9",
         "webflo/drupal-core-require-dev": "~8.6",
         "behat/mink-selenium2-driver": "^1.4@dev as 1.3.x-dev"
     },
```

And then run:

```composer update```

and now it completes the update.

**Comment by josephdpurcell** [comment]
I was able to change my composer.json from:

```
     "require-dev": {
         "geerlingguy/drupal-vm": "^4.9",
         "webflo/drupal-core-require-dev": "~8.6"
     },
```

To be:

```
     "require-dev": {
         "geerlingguy/drupal-vm": "^4.9",
         "webflo/drupal-core-require-dev": "~8.6",
         "behat/mink-selenium2-driver": "1.4.x-dev as 1.3.x-dev"
     },
```

And then run:

```composer update```

and now it completes the update.

**Comment by josephdpurcell** [comment]
Does anyone have thoughts as to whether this poses any significant risk? My assumption is the scope of this change would only affect automated testing that might be using the mink driver.

**Comment by stof** [comment]
please use `^1.4@dev as 1.3.x-dev`, to avoid having your own project suffering from the exact same issue when Mink bumps the branch alias again to 1.5.x-dev.

**Comment by josephdpurcell** [comment]
Thanks! I Updated the description of the ticket to explain how to do that.

**Comment by shelane** [comment]
When attempting to do as described, I get these errors:
```
Problem 1
    - The requested package behat/mink-selenium2-driver ^1.4@dev as 1.3.x-dev exists as behat/mink-selenium2-driver[1.3.x-dev, dev-master, 1.4.x-dev, v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.1.0, v1.1.1, v1.2.0, v1.3.0, v1.3.1] but these are rejected by your constraint.
  Problem 2
    - The requested package behat/mink-selenium2-driver (locked at v1.3.1, required as ^1.4@dev as 1.3.x-dev) is satisfiable by behat/mink-selenium2-driver[v1.3.1] but these conflict with your requirements or minimum-stability.
```

**Comment by danepowell** [comment]
This should be fixed upstream now: https://github.com/minkphp/MinkSelenium2Driver/issues/313#issuecomment-528518054

If you've previously added any workarounds, please remove them.

You may need to run `composer update` several times to get the appropriate new mink branch.
