### ISSUE TITLE
Use dedicated database to store SAML session data on Acquia

### ISSUE THREAD

**Issue by yyss8** [acquia/blt#3841]
We are currently updating the simplesamlphp configuration file on our multisite project based on the refactored config file introduced in https://github.com/acquia/blt/pull/2953 but we are not sure how to use dedicated database to store SAML session data on Acquia.

We used to define our database name in the  variable `$ah_options` but it seems like the variable is now removed.
The comment [here](https://github.com/acquia/blt/pull/2953/files#diff-7447f0d762092abdc1817d7c63d020efR13) is suggesting to use `store.sql.name` to define the database name but I don't think the key is being used in simplesamlphp library based on their [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-maintenance).

After comparing with the old config file, I noticed that it's now using the environment variable `AH_SITE_ENIVORNMENT` to decide which database to use. I wonder if it's ok to replace the variable with our own database name?

![image](https://user-images.githubusercontent.com/13445723/64348326-fdca2800-cfc2-11e9-9a6f-46ab4123f318.png)

**I want to...**
Use dedicated database to store SAML session data for multisite on Acquia.

**It's not working because...**
The comment written [here](https://github.com/acquia/blt/pull/2953/files#diff-7447f0d762092abdc1817d7c63d020efR15) is not very clear about how to use dedicated database to store SAML session data.

**System information**
* BLT version: 10
* Simplesamlphp library version: 1.17.5
* Simplesamlphp auth module version: 3.1.0

**Comment by danepowell** [comment]
Hi @yyss8 , thanks for the detailed issue. Sorry to bounce you to another team, but can you please open a Support issue or ping your Technical Account Manager about this issue? BLT only copies and installs the SAML config file from the [official Acquia SAML documentation](https://docs.acquia.com/resource/using-simplesamlphp-acquia-cloud-site/#storing-session-information-using-the-acquia-cloud-sql-database); we can't support individual SAML implementations.

**Comment by danepowell** [comment]
We'll try to make this support procedure more clear / explicit in https://github.com/acquia/blt/issues/3845
