### ISSUE TITLE
Which Linux OS will be work for Drupal VM and BLT?

### ISSUE THREAD

**Issue by debdatta-sarkar** [acquia/blt#3844]
We need to set up a **Drupal VM along with BLT existing repository on Linux environment** but we have these options:
- RedHat 7.3
- SUSE SAP 12 - SP2
- SUSE12 - SP2

_Which option will be the best? Don't have the option of Ubuntu and Fedora._

**Comment by danepowell** [comment]
BLT should work in any Unix-like environment. The particular distribution shouldn't matter, it's up to your personal preference. Having said that, I have heard no reports (good or bad) from users on any of those environments.

Similarly, DrupalVM should work in any Unix-like environment that supports virtualization. You might have better luck getting specific details by searching or posting in the DrupalVM issue queue: https://github.com/geerlingguy/drupal-vm

**Comment by debdatta-sarkar** [comment]
thanks! :)
