### ISSUE TITLE
Memcache error on Acquia Cloud

### ISSUE THREAD

**Issue by broeker** [acquia/blt#3858]
I want to enable Memcache on an Acquia Cloud instance that is running:

- Drupal 8.7.7
- Memcache 2.0
- PHP 7.2
- Acquia BLT 10.4.1
- Travis CI

Without memcache, all builds and deploys work with no errors. 

When we introduce drupal/memcache into the codebase, the build passes Travis tests, attempts to deploy to Acquia dev server, and fails with this message:

```
[22:37:21] [22:37:21] Started
[22:37:35] [2019-09-19 22:37:22] uwstout.dev: updating web_servers[staging-18629].
Updating uwstout.dev to deploy tags/UWS23
Deploying tags/UWS23 on uwstout.dev
[2019-09-19 22:37:32] Attempting to invalidate Twig cache...
[2019-09-19 22:37:32] Executing: cd /var/www/html/uwstout.dev/docroot && drush9 php:script /var/www/site-scripts/invalidate-twig-cache.php (as uwstout.dev@staging-18629})
Error: Class &#039;Drupal\memcache\Invalidator\MemcacheTimestampInvalidator&#039; not found in Drupal\Component\DependencyInjection\PhpArrayContainer->createService() (line 101 of /mnt/www/html/uwstoutdev/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php).
```
This happens simply when memcache is in the codebase -- the module has not been enabled, and there are zero configuration changes or any other adjustments. 

We have also attempted to follow the "official" Acquia install notes here:

https://docs.acquia.com/acquia-cloud/performance/memcached/enable/ 

as well as the patches and suggestions here:

https://www.drupal.org/project/memcache/issues/3002858

This seems to be a BLT issue, and the Acquia page linked above suggests posting to this issue queue so I'm hoping somebody may have some suggestions. Thanks for any advice, we have already submitted an Acquia support ticket that did lead to any useful results.

**Comment by mikemadison13** [comment]
I wonder, do you have the `acquia/memcache` package in composer? There was a change in BLT in 10.4.0 that migrated all of the memcache config out of BLT itself and into a separate package. This should have been automatically added to your composer file(s) during the BLT update process, but if it didn't get committed / deployed that might explain.

See release notes here https://github.com/acquia/blt/releases/tag/10.4.0

**Comment by broeker** [comment]
thanks @mikemadison13 -- yes, we did have acquia/memcache-settings in composer. This is actually how we ended up revisiting this problem:

Awhile back we ended up removing all references to Memcache completely because we could not get around the error outlined in the d.org thread above. 

Then a couple of days ago after running `blt drupal:sync` we got the [warning] Your BLT schema is out of date message, and when we accepted those changes, it automatically updated our composer.json to include both `acquia/memcache-settings` AND `drupal/memcache` even though we had previously removed them. 

We decided to take that as a sign to re-attempt a memcache install, but as noted, the deploy fails just from having memcache in the codebase.

**Comment by mikemadison13** [comment]
Interesting. I'm curious, have you tried flushing the caches? If you are updating / changing things around, I'm wondering if there is something stuck somewhere that a `drush cr` would knock loose? 

@danepowell do you think this is actually something at the BLT level or should we involve other support resources?

**Comment by broeker** [comment]
@mikemadison13 the issue is that once memcache is in the codebase, we are unable to run any kind of `drush` commands and the site is a WSOD. 

The reason we suspect this is a BLT issue is because the site runs fine on our local instances (Docksal, in our case) and only fails AFTER it has been deployed to Acquia via BLT. 

Other things that may be of note:

This is part of a large refactor that introduced BLT (and a sane local dev environment) to the project for the first time. During the refactor, we discovered that the client was running a very old memcache `alpha-2,` and when we updated, we immediately hit the known errors that occurred after the `alpha-7.` update. At that point, we temporarily removed Memcache from the site to focus on other concerns. 

We made a few additional attempts along the way, and then again when this most recent BLT update  re-introduced to it our composer.json.

**Comment by broeker** [comment]
Sigh, I'm both frustrated and happy to say that this is now suddenly working -- I was making another attempt in order to provide you a better step-by-step of what we were doing, but this time it "just worked" despite not having done anything even slightly differently than our previous 30 or so deploy attempts :)

For now I'll close this out and assume that some cache layer was magically cleared, but man alive. Thanks @mikemadison13

**Comment by mikemadison13** [comment]
FEAR ME MEMCACHE. 

...I hate when things just suddenly work. Glad it's working now though. Please keep us posted. We may want to loop in Acquia support if anything funky starts happening again.

**Comment by justinlevi** [comment]
@mikemadison13 I'm running into this same issue now actually. 

```
Fatal error: Uncaught Error: Class 'Drupal\memcache\Invalidator\MemcacheTimestampInvalidator' not found in /mnt/www/html/webnycoredev/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php:101
Stack trace:
#0 /mnt/www/html/webnycoredev/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'memcache.timest...')
#1 /mnt/www/html/webnycoredev/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(260): Drupal\Component\DependencyInjection\Container->get('memcache.timest...', 1)
#2 /mnt/www/html/webnycoredev/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\Component\DependencyInjection\PhpArrayContainer->resolveServicesAndParameters(Array)
#3 /mnt/www/html/webnycoredev/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\PhpArrayContainer->createService(Array, 'cache.container')
#4 /mnt/www/htm in /mnt/www/html/webnycoredev/docroot/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 101
 [warning] Drush command terminated abnormally. Check for an exit() in your Drupal site.
```

I've got `  "acquia/memcache-settings": "*",` in my composer.json and can't run $ `drush cr`

**Comment by lcatlett** [comment]
I was also getting the same errors as @justinlevi and @broeker. I put in a [pr](https://github.com/acquia/memcache-settings/pull/2) to the acquia/memcache-settings repo with the needed changes to the memcache settings to resolve.

**Comment by andreas-id** [comment]
The error is `Error: Class Drupal\memcache\Invalidator\MemcacheTimestampInvalidator not found`
Looks like you didn’t update memcache to the 2.0 branch.
Please take a look to my comment here https://www.drupal.org/project/memcache/issues/3002858#comment-13354652

@lcatlett @justinlevi Please write the answer so we can close the issue.
