### ISSUE TITLE
Allow Drupal root to be configurable

### ISSUE THREAD

**Issue by jigarius** [acquia/blt#3863]
The problem is that BLT assumes all project's docroot to be `docroot`. However, there are other standards that use `web` as the Drupal root.

The docroot should be configurable using the `blt.yml` file. Say, support for something as follows should suffice:
```yaml
project.docroot: web
```

I've found no alternatives – I cannot rename the docroot to `docroot` because it's not my project. The team already has their norms and proposing such a big change will make the team not want to use BLT.

**Comment by danepowell** [comment]
This should already be possible via the `docroot` variable. Have you tried overriding this?
https://github.com/acquia/blt/blob/10.x/config/build.yml#L60

**Comment by jigarius** [comment]
The documentation on [Adding Acquia BLT to an existing site](https://docs.acquia.com/blt/install/adding-to-project/) suggests that the docroot must be `docroot`.

I'll try what you instructed and reopen this ticket if it doesn't work. Thanks.

**Comment by danepowell** [comment]
Thanks for pointing to those docs, I'll update them to clarify that docroot is configurable: https://github.com/acquia/blt/issues/3873

**Comment by jigarius** [comment]
Things got a bit better after specifying `docroot`, however, I still get an error:

```
> tests:twig:lint:files
Linting twig files...
PHP Warning:  file_get_contents(/path/to/project/docroot/core/lib/Drupal/Core/Template/TwigExtension.php): failed to open stream: No such file or directory in /path/to/project/vendor/acquia/blt/src/Robo/Commands/Validate/TwigCommand.php on line 111
```

The file triggering the error seems to have hard-coded `docroot` in the code.
