### ISSUE TITLE
DT-882: Multisite dbs not scrubbed on dbcopy

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3871]
It seems like if you copy multiple dbs on Acquia Cloud, only the default db gets scrubbed. AcHooksCommand::dbScrub takes the db name as an argument but never actually uses it to set the Drush site context (or perhaps the context should be getting set via the `--site` parameter in the cloud hook).

**Comment by bkosborne** [comment]
Came here to report this myself.

**Comment by andreas-id** [comment]
+1 Yes it true. 
We have the same name for the DB and the site machine name, so we got out of this way.
db-scrub.sh
`blt artifact:ac-hooks:db-scrub $db_name $target_env $db_name $source_env -D drush.ansi=false`

But this is a hack )

**Comment by danepowell** [comment]
This may still be a valid issue but instead of fixing it just in BLT, I'd rather move the db-scrub functionality to Cloud so we can provide it to all customers. I don't have an ETA on that at the moment, but since it's not going to get fixed in BLT I'm going to close this issue.
