### ISSUE TITLE
ACSF/multisite Drush aliases broken on BLT 10.x / ADS

### ISSUE THREAD

**Issue by lcatlett** [acquia/blt#3883]
**Describe the bug**
Filing this issue in BLT since it is a breaking change, but if there is a better place to file an issue on ADS, please advise.

When #3877 was merged, it is now not possible to generate correct ACSF drush aliases since the `ads run drush aliases:sync` command does not support dynamic multisite aliases on ACSF or ACE cloud subscriptions using multisite.

**To Reproduce**
1. Create new BLT / ads project
2. Link to ACSF or ACE multisite project
3. Run `ads run drush aliases:sync`
4. Observe that generated aliases (`ads run drush sa`) are not valid drush multisite aliases

**Comment by danepowell** [comment]
I think the ADS team already has this on their radar, but I'll pass along the feedback just to be sure.

The best way to submit feedback regarding ADS is via the `ads feedback` command or a support ticket as product feedback. Thanks.
