### ISSUE TITLE
I want to implement "Standing up projects in minutes using BLT, Lightning, and DrupalVM"

### ISSUE THREAD

**Issue by carnnia** [acquia/blt#3888]
I am trying to follow the instruction published here:
https://www.youtube.com/watch?v=OyMLX74O1kY
Aiming to have a working composer based d8 dev site with BLT
I started with:
$ composer create-project --no-interaction acquia/blt-project casey
$ cd casey
i did not change or customize anything
$ blt vm

**It's not working because...**
and got this:
 $ blt vm
 Drupal VM is not currently installed. Install it now?  (y/n) y
Adding geerlingguy/drupal-vm:~5.0 to composer.json's require-dev array...
> internal:composer:require
[error]    in task Robo\Task\Composer\Base

  Neither local composer.phar nor global composer installation could be found.
[error]  Command `internal:composer:require 'geerlingguy/drupal-vm' '~5.0' 1` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/faq/

**Detailed error output**
 $ blt vm -vvv
 Drupal VM is not currently installed. Install it now?  (y/n) y
Adding geerlingguy/drupal-vm:~5.0 to composer.json's require-dev array...
> internal:composer:require
[error]    in task Robo\Task\Composer\Base

  Neither local composer.phar nor global composer installation could be found.
[error]  Command `internal:composer:require 'geerlingguy/drupal-vm' '~5.0' 1` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/faq/
2.417s total time elapsed.

**BLT doctor output**
 $ blt doctor
PHP Warning:  file_get_contents(/Users/caseycarnnia/work/casey/docroot/sites/default/settings.php): failed to open stream: No such file or directory in /Users/caseycarnnia/work/casey/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 475

Warning: file_get_contents(/Users/caseycarnnia/work/casey/docroot/sites/default/settings.php): failed to open stream: No such file or directory in /Users/caseycarnnia/work/casey/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 475
+---------------------------+-------------------------------------------------------------+
| Property                  | Value                                                       |
+---------------------------+-------------------------------------------------------------+
| %paths.%root              | /Users/caseycarnnia/work/casey/docroot                      |
| alias-searchpaths.0       | /Users/caseycarnnia/work/casey/drush/sites                  |
| blt-version               | 10.5.0                                                      |
| composer-version          |                                                             |
| drush-cache-directory     | /Users/caseycarnnia/.drush/cache                            |
| drush-conf.0              | /Users/caseycarnnia/work/casey/vendor/drush/drush/drush.yml |
| drush-conf.1              | /Users/caseycarnnia/work/casey/drush/drush.yml              |
| drush-script              | /Users/caseycarnnia/work/casey/vendor/drush/drush/drush     |
| drush-temp                | /tmp                                                        |
| drush-version             | 9.7.1                                                       |
| php-bin                   | /usr/local/Cellar/php@7.2/7.2.23/bin/php                    |
| php-conf.0                | /usr/local/etc/php/7.2/php.ini                              |
| php-os                    | Darwin                                                      |
| root                      | /Users/caseycarnnia/work/casey/docroot                      |
| stacks.drupal-vm.inited   | false                                                       |
| stacks.dev-desktop.inited | false                                                       |
| uri                       | default                                                     |
+---------------------------+-------------------------------------------------------------+
PHP Warning:  file_get_contents(/Users/caseycarnnia/work/casey/docroot/sites/default/settings.php): failed to open stream: No such file or directory in /Users/caseycarnnia/work/casey/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 475

Warning: file_get_contents(/Users/caseycarnnia/work/casey/docroot/sites/default/settings.php): failed to open stream: No such file or directory in /Users/caseycarnnia/work/casey/vendor/acquia/blt/src/Robo/Inspector/Inspector.php on line 475
+------------------------------------------+--------------------------------------------------------------+
| Check                                    | Problem                                                      |
+------------------------------------------+--------------------------------------------------------------+
| BehatCheck:checkBaseUrl:uri              | base_url in tests/behat/local.yml does not match the site    |
|                                          | URI.                                                         |
|                                          |   Behat base_url is set to                                   |
|                                          | http://local.casey.com.                                      |
|                                          |   Drush site URI is set to default.                          |
| ComposerCheck:checkPrestissimo:plugins   | hirak/prestissimo plugin for composer is not installed.      |
|                                          |   Run composer global require                                |
|                                          | hirak/prestissimo to install it.                             |
|                                          |   This will improve composer install/update performance by   |
|                                          | parallelizing the download of dependency information.        |
| ConfigCheck:checkGitConfig               | Git repositories are not defined in blt.yml.                 |
|                                          |   Add values for git.remotes to blt.yml to enabled automated |
|                                          | deployment.                                                  |
| DbCheck:checkRequiredKeys                | drush status is missing the 'db-hostname' key.               |
| DrupalCheck:checkDrupalBootstrapped      | Could not bootstrap Drupal via drush without alias.          |
| DrupalCheck:checkDrupalInstalled         | Drupal is not installed.                                     |
|                                          |                                                              |
|                                          | Run `blt drupal:install` to install Drupal locally.          |
| FileSystemCheck:checkFileSystem:%files   | Public files directory is not set.                           |
| FileSystemCheck:checkFileSystem:%private | Private files directory is not set.                          |
| FileSystemCheck:checkFileSystem:%temp    | Temporary files directory is not set.                        |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.    |
| PhpCheck:checkPhpDateTimezone            | PHP setting for date.timezone is not set.                    |
|                                          |   Define date.timezone in /usr/local/etc/php/7.2/php.ini     |
| SettingsFilesCheck:exists                | Could not find settings.php for this site.                   |
| SettingsFilesCheck:local-settings        | Could not find local settings file.                          |
|                                          | Your local settings file should exist at                     |
|                                          | /Users/caseycarnnia/work/casey/docroot/sites/default/setting |
|                                          | s/local.settings.php.                                        |
| WebUriCheck:checkUri                     | Site URI is not set                                          |
|                                          | Is options.uri set correctly in                              |
|                                          | /Users/caseycarnnia/work/casey/docroot/sites/default/local.d |
|                                          | rush.yml?                                                    |
+------------------------------------------+--------------------------------------------------------------+
[error]  BLT Doctor discovered one or more critical issues.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/faq/

**System information**
* Operating system type: [macOS Catalina V 10.15  ]
* Operating system version: [10.15]
* BLT version: [BLT 10.5.0]

**Comment by carnnia** [comment]
It ended up being a composer issue.
I had downloaded composer.phar into user/local/bin and made an alias for in my .bashrc .
to get blt work i removed composer.phar and reinstalled it via brew:
_xcode-select --install
brew install gcc  
 brew install composer_

now  _blt vm_ workes.
I compared the file permissions between composer.phar i had downloaded and the one brew installed and didn't find a difference. so i don't know why it wasn't working.

**Comment by UTCGilligan** [comment]
You may also want to try [ADS CLI beta](https://docs.acquia.com/dev-studio/cli/install/); it has been under rapid development, and it makes for quick provision and deployment of various profiles/distributions in either Lando/Docker or DrupalVM/Virtualbox. If you set up an Acquia Cloud environment with keys, it is trivial to deploy the project directly into a free/test or paid environment.

**Comment by danepowell** [comment]
It sounds like you were able to resolve this, so I'm going to close this issue for now.

The error message about Composer not being found actually comes from Robo. Here's the logic Robo uses to find Composer, perhaps it will reveal some clues as to why your initial setup wasn't working: https://github.com/consolidation/Robo/blob/1.x/src/Common/ExecCommand.php#L42

If you are able to come up with steps to reproduce the problem, I'm sure the Robo project would appreciate an issue.
