### ISSUE TITLE
DT-941: BLT Tag Deploy Perform Git Checks Earlier

### ISSUE THREAD

**Issue by deeplfo** [acquia/blt#3890]
**Is your feature request related to a problem? Please describe.**
Recently I was going through a deployment and "blt deploy" went through all its tasks, and only at the end did it remind me that the tag was already used.

**Describe the solution you'd like**
During the BLT Tag Deploy command, check whether a tag exists or not way **before** any other tasks are run.  And in fact I'd recommend to get all the "sanity" checks out of the first, before embarking on build deploy execution.

Thanks,
Mohsen

**Comment by danepowell** [comment]
Related (we will be adding a pre-deploy validation step here): https://github.com/acquia/blt/issues/3564

**Comment by danepowell** [comment]
This is no longer in the roadmap. It maybe still be a valid issue, but we need to remove it from the backlog to make space for more pressing issues.
