### ISSUE TITLE
BLT Deploy Frontend Build Artifact Question

### ISSUE THREAD

**Issue by deeplfo** [acquia/blt#3891]
Hi,

It seems that the `blt deploy` is looking at my `local.blt.yml` file during the frontend build task execution.  Has this behavior changed?  I don't recall having to worry about my `local.blt.yml` file before when it came time to do a `blt deploy`.  Can someone clarify if a) the way `blt deploy` builds frontends has changed, and b) what is the replacement procedure?  I had to add all my themes in my `local.blt.yml` file in order to get the themes built and pushed correctly.

Thanks,
Mohsen

**Comment by danepowell** [comment]
Any time that `local.blt.yml` is present, BLT will use it to override configuration values in `blt.yml` and elsewhere. As far as I know, this behavior hasn't changed recently.

Can you describe exactly what you are trying to accomplish in terms of your frontend builds?

**Comment by deeplfo** [comment]
Thanks for confirming.  The missing pieces of understanding was due to processes on our end, so we're good.
