### ISSUE TITLE
Pipelines setup_env script downloads old version of node

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#3897]
The https://github.com/acquia/blt/blob/11.x/scripts/pipelines/setup_env#L15 downloads node v8.1.4 which is outdated. I would imagine applications that need a newer version just download it afterwards in a frontend task or similar. This means two versions of node are downloaded which can slow down builds.

Is the intention for the setup_env script included with BLT to be used as-is and updated once in a while? Or should applications create their own and not use it at all?

If it is the former, I feel like the node version should be kept up to date, like version 10. Removing it is also an option. 

If it is the latter, applications would no longer get upstream changes to it. Is that ok? That should probably be documented somewhere.

For additional context, see Acquia ticket 873186.

Thanks!

**Comment by danepowell** [comment]
The intention is that most projects use BLT's built-in scripts. As you observed, if you override these scripts, then it's up to you to track and merge upstream changes. You can choose whichever approach is best for your project.

I agree we should update the node version, how do you feel about changing those two lines to `nmv install stable --latest-npm`, which at this time will get you Node.js 13?

**Comment by richardbporter** [comment]
Thanks for clarifying. 

I think that proposed change makes sense. It is certainly less maintenance that way.

**Comment by danepowell** [comment]
Sounds good, we'll implement that in https://github.com/acquia/blt/issues/3900
