### ISSUE TITLE
Support project specific local.settings.php files with blt configuration

### ISSUE THREAD

**Issue by jasonawant** [acquia/blt#3898]
**Is your feature request related to a problem? Please describe.**
Support project specific local.settings.php files with blt configuration to allow customizations for local development and on-boarding new project team members.

**Describe the solution you'd like**
Add support for a blt.local_settings_file_path or similar config option. This would allow project maintainers to add this key and file path such as './templates/project.local.settings.php'.

Then, use this config option if set in SettingsCommand::generateSiteConfigFiles(). If not set, fallback to current logic, `$blt_local_settings_file = $this->getConfigValue('blt.root') . '/settings/default.local.settings.php';`

Update relevant docs, possibly
- https://docs.acquia.com/blt/install/creating-new-project/
- https://docs.acquia.com/blt/extending-blt/#modifying-your-acquia-blt-configuration

**Describe alternatives you've considered**
- replace blt command with custom, https://docs.acquia.com/blt/extending-blt/
- use a composer post-install-cmd script to replace blt setup's local.settings.php.

**Additional context**
- https://github.com/acquia/blt/issues/1610

**Comment by danepowell** [comment]
If I understand the request correctly, I think this feature already exists. You should have the following file in your project repo: `docroot/sites/default/settings/default.local.settings.php`

You can modify and commit any changes to that, and it'll be used as the template whenever local.settings.php is recreated.

If that's what you're looking for, is there some way we could make it more visible? Was there someplace specific that you looked for documentation on this, or expected to find it?

**Comment by jasonawant** [comment]
Hi @danepowell! I must have overlooked it. This is exactly how it works.

Step 7 [here](https://docs.acquia.com/blt/install/creating-new-project/) could include a statement and link to customizing local settings

That information link could go to a new page within the [Using Acquia BLT as a technical architect](https://docs.acquia.com/blt/tech-architect/) or [Local development with Acquia BLT](https://docs.acquia.com/blt/install/local-development/).

Perhaps less relevant is [Extending and overriding Acquia BLT](https://docs.acquia.com/blt/extending-blt/), but I could see myself go there to customize what BLT provides, which is the template [default.local.settings.php](https://github.com/acquia/blt/blob/11.x/settings/default.local.settings.php) file.

**Comment by danepowell** [comment]
Thanks for the feedback, I'll try to improve those docs as you suggest: https://github.com/acquia/blt/issues/3915
