### ISSUE TITLE
Broken link in 10.0.0 release notes

### ISSUE THREAD

**Issue by wizonesolutions** [acquia/blt#3903]
**Describe the bug**
https://github.com/acquia/blt/releases/tag/10.0.0 mentions a wiki entry for "What's new in BLT 10.x." The wiki entry does not exist. Google brings me to https://support.acquia.com/hc/en-us/articles/360035202373-Upgrading-from-BLT-9-2-x-to-BLT-10-x, which hopefully contains the same content.

**To Reproduce**
Read the release notes at https://github.com/acquia/blt/releases/tag/10.0.0

**Expected behavior**
Link to upgrade docs works.

**Detailed error output**
N/A

**BLT doctor output**
N/A

**System information**
N/A

**Additional context**
N/A

**Comment by danepowell** [comment]
Sorry about that, we indeed migrated the wiki to the Acquia KB as part of https://github.com/acquia/blt/issues/3810. I've updated the release notes with the correct link. Thanks for catching this.
