### ISSUE TITLE
Project creation: RoboFile ignores php memory limit

### ISSUE THREAD

**Issue by viktor-silakov** [acquia/blt#3910]
**I want to...**
Create a new project via BLT using a command:
`composer create-project --no-interaction --ignore-platform-reqs acquia/blt-project test-blt`
and also tried to use:
`COMPOSER_MEMORY_LIMIT=-1 composer create-project --no-interaction --ignore-platform-reqs acquia/blt-project test-blt`
the same result

**It's not working because...**
This throws an error:

> HP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /Users/viktar.silakou/test-blt/vendor/acquia/blt/RoboFile.php on line 394

but in php.ini I have 4 GB memory limit:
`php -r "echo ini_get('memory_limit').PHP_EOL;"`
`4GB`

**Detailed error output**
`COMPOSER_MEMORY_LIMIT=-1 composer create-project --no-interaction acquia/blt-project test-blt
    1/2:	http://repo.packagist.org/p/provider-latest$7859a8e4ddbec6265164b9f131f6bb96781608b98b5992e78092b98f4eb6d871.json
    2/2:	http://repo.packagist.org/p/provider-2019-07$a8147c40473124a8791b8cd3586c370a00593de0d4b9e2b75248c000ead64a87.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/2:	http://repo.packagist.org/p/provider-latest$7859a8e4ddbec6265164b9f131f6bb96781608b98b5992e78092b98f4eb6d871.json
    2/2:	http://repo.packagist.org/p/provider-2019-07$a8147c40473124a8791b8cd3586c370a00593de0d4b9e2b75248c000ead64a87.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Installing acquia/blt-project (10.5.0)
  - Installing acquia/blt-project (10.5.0): Loading from cache
Created project in test-blt
    1/1:	https://asset-packagist.org/p/provider-latest/8337077fba5e3097de3c9712cf2973ae50e6efa3fcc4a3af9f4644ecc5bc76e4.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
    1/1:	http://repo.packagist.org/p/provider-latest$13bee1f8cdf96769d6b53ab6764de16ff394b869e20a08b3ecdcb8ab20f592ae.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 264 installs, 0 updates, 0 removals
  - Installing zaporylie/composer-drupal-optimizations (1.1.1): Loading from cache
  - Installing composer/installers (v1.7.0): Loading from cache
  - Installing ocramius/package-versions (1.4.0): Loading from cache
  - Installing grasmash/drupal-security-warning (1.1.1): Loading from cache
  - Installing cweagans/composer-patches (1.6.7): Loading from cache
Gathering patches for root package.
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing zendframework/zend-diactoros (1.8.7): Loading from cache
  - Installing pear/pear_exception (v1.0.0): Loading from cache
  - Installing pear/console_getopt (v1.4.2): Loading from cache
  - Installing pear/pear-core-minimal (v1.10.9): Loading from cache
  - Installing pear/archive_tar (1.4.8): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing symfony/polyfill-ctype (v1.12.0): Loading from cache
  - Installing symfony/debug (v3.4.33): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.12.0): Loading from cache
  - Installing symfony/polyfill-php72 (v1.12.0): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing symfony/polyfill-php70 (v1.12.0): Loading from cache
  - Installing symfony/http-foundation (v3.4.33): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.33): Loading from cache
  - Installing symfony/http-kernel (v3.4.33): Loading from cache
  - Installing asm89/stack-cors (1.2.0): Loading from cache
  - Installing composer/semver (1.5.0): Loading from cache
  - Installing symfony/psr-http-message-bridge (v1.2.0): Loading from cache
  - Installing masterminds/html5 (2.7.0): Loading from cache
  - Installing doctrine/lexer (1.1.0): Loading from cache
  - Installing egulias/email-validator (2.1.11): Loading from cache
  - Installing stack/builder (v1.0.5): Loading from cache
  - Installing zendframework/zend-stdlib (3.2.1): Loading from cache
  - Installing zendframework/zend-escaper (2.6.1): Loading from cache
  - Installing zendframework/zend-feed (2.12.0): Loading from cache
  - Installing easyrdf/easyrdf (0.9.1): Loading from cache
  - Installing symfony/routing (v3.4.33): Loading from cache
  - Installing symfony-cmf/routing (1.4.1): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.4.1): Loading from cache
  - Installing doctrine/annotations (v1.8.0): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/event-manager (v1.0.0): Loading from cache
  - Installing doctrine/collections (v1.6.2): Loading from cache
  - Installing doctrine/cache (v1.8.1): Loading from cache
  - Installing doctrine/persistence (1.1.1): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing doctrine/common (v2.11.0): Loading from cache
  - Installing twig/twig (v1.42.3): Loading from cache
  - Installing symfony/yaml (v3.4.33): Loading from cache
  - Installing symfony/polyfill-iconv (v1.12.0): Loading from cache
  - Installing symfony/process (v3.4.33): Loading from cache
  - Installing symfony/translation (v3.4.33): Loading from cache
  - Installing symfony/validator (v3.4.33): Loading from cache
  - Installing symfony/serializer (v3.4.33): Loading from cache
  - Installing symfony/dependency-injection (v3.4.33): Loading from cache
  - Installing symfony/console (v3.4.33): Loading from cache
  - Installing symfony/class-loader (v3.4.33): Loading from cache
  - Installing brumann/polyfill-unserialize (v1.0.4): Loading from cache
  - Installing typo3/phar-stream-wrapper (v2.1.3): Loading from cache
  - Installing drupal/core (8.7.8): Loading from cache
  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2869592-remove-update-warning-7.patch (2869592 - Disabled update module shouldn't produce a status report warning)
    https://www.drupal.org/files/issues/2019-03-05/2815221-116.patch (2815221 - Add quickedit to the latest-revision route)
    https://www.drupal.org/files/issues/2018-10-12/1356276-531.patch (1356276 - Allow profiles to define a base/parent profile and load them in the correct order)
    https://www.drupal.org/files/issues/2018-07-09/2914389-8-do-not-test.patch (2914389 - Allow profiles to exclude dependencies of their parent)

  - Installing sarciszewski/php-future (0.4.2): Loading from cache
  - Installing acquia/http-hmac-php (3.4.0): Loading from cache
  - Installing typhonius/acquia-php-sdk-v2 (1.0.4): Loading from cache
  - Installing symfony/twig-bridge (v3.4.33): Loading from cache
  - Installing symfony/filesystem (v3.4.33): Loading from cache
  - Installing symfony/config (v3.4.33): Loading from cache
  - Installing composer/ca-bundle (1.2.4): Loading from cache
  - Installing sensiolabs/security-checker (v5.0.3): Loading from cache
  - Installing oomphinc/composer-installers-extender (v1.1.2): Loading from cache
  - Installing webflo/drupal-finder (1.2.0): Loading from cache
  - Installing nette/neon (v3.0.0): Loading from cache
  - Installing nikic/php-parser (v4.2.5): Loading from cache
  - Installing symfony/finder (v4.3.6): Loading from cache
  - Installing phpstan/phpdoc-parser (0.3.5): Loading from cache
  - Installing nette/utils (v3.0.2): Loading from cache
  - Installing nette/schema (v1.0.1): Loading from cache
  - Installing nette/finder (v2.5.1): Loading from cache
  - Installing nette/robot-loader (v3.2.0): Loading from cache
  - Installing nette/php-generator (v3.2.3): Loading from cache
  - Installing nette/di (v3.0.1): Loading from cache
  - Installing nette/bootstrap (v3.0.1): Loading from cache
  - Installing jean85/pretty-package-versions (1.2): Loading from cache
  - Installing composer/xdebug-handler (1.3.3): Loading from cache
  - Installing phpstan/phpstan (0.11.19): Loading from cache
  - Installing phpstan/phpstan-deprecation-rules (0.11.2): Loading from cache
  - Installing mglaman/phpstan-junit (0.11.2): Loading from cache
  - Installing mglaman/phpstan-drupal (0.11.12): Loading from cache
  - Installing mglaman/drupal-check (1.0.14): Loading from cache
  - Installing dflydev/dot-access-data (v1.1.0): Loading from cache
  - Installing grasmash/yaml-expander (1.4.0): Loading from cache
  - Installing grasmash/yaml-cli (1.0.4): Loading from cache
  - Installing webmozart/assert (1.5.0): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing symfony/var-dumper (v4.3.6): Loading from cache
  - Installing jakub-onderka/php-console-color (v0.2): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.4): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing psy/psysh (v0.9.9): Loading from cache
  - Installing container-interop/container-interop (1.2.0): Loading from cache
  - Installing league/container (2.4.1): Loading from cache
  - Installing grasmash/expander (1.0.0): Loading from cache
  - Installing consolidation/config (1.2.1): Loading from cache
  - Installing consolidation/site-alias (3.0.0): Loading from cache
  - Installing consolidation/site-process (2.1.0): Loading from cache
  - Installing consolidation/output-formatters (3.5.0): Loading from cache
  - Installing consolidation/annotated-command (2.12.0): Loading from cache
  - Installing consolidation/self-update (1.1.5): Loading from cache
  - Installing consolidation/log (1.1.1): Loading from cache
  - Installing consolidation/robo (1.4.11): Loading from cache
  - Installing consolidation/filter-via-dot-access-data (1.0.0): Loading from cache
  - Installing chi-teck/drupal-code-generator (1.30.5): Loading from cache
  - Installing drush/drush (9.7.1): Loading from cache
  - Installing drupol/phposinfo (1.6.2): Loading from cache
  - Installing squizlabs/php_codesniffer (3.5.2): Loading from cache
  - Installing drupal/coder (8.3.6): Cloning 4337ddf58d from cache
  - Installing drupal-composer/drupal-scaffold (2.6.1): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.5.0): Loading from cache
  - Installing consolidation/comments (1.0.2): Loading from cache
  - Installing acquia/blt (10.5.0): Loading from cache
  - Installing drupal/memcache (2.0.0): Loading from cache
  - Installing acquia/memcache-settings (dev-master 828d762): Cloning 828d76212b from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing behat/gherkin (v4.6.0): Loading from cache
  - Installing traviscarden/behat-table-comparison (v0.2.2): Loading from cache
  - Installing drupal/drupal-driver (v1.4.0): Loading from cache
  - Installing instaclick/php-webdriver (1.4.6): Loading from cache
  - Installing symfony/css-selector (v3.4.33): Loading from cache
  - Installing behat/mink (dev-master a534fe7): Cloning a534fe7dac from cache
  - Installing behat/mink-selenium2-driver (1.3.x-dev 0a09c43): Cloning 0a09c43416 from cache
  - Installing symfony/dom-crawler (v3.4.33): Loading from cache
  - Installing symfony/browser-kit (v4.3.6): Loading from cache
  - Installing fabpot/goutte (v3.2.3): Loading from cache
  - Installing behat/mink-browserkit-driver (1.3.3): Loading from cache
  - Installing behat/mink-goutte-driver (v1.2.1): Loading from cache
  - Installing behat/transliterator (v1.2.0): Loading from cache
  - Installing behat/behat (v3.3.1): Loading from cache
  - Installing behat/mink-extension (2.3.1): Loading from cache
  - Installing drupal/drupal-extension (v3.4.1): Loading from cache
  - Installing acquia/drupal-spec-tool (v2.0.0): Loading from cache
  - Installing drupal/moderation_sidebar (1.2.0): Loading from cache
  - Installing drupal/ctools (3.0.0): Loading from cache
  - Installing drupal/page_manager (4.0.0-beta3): Loading from cache
  - Installing drupal/panels (4.4.0): Loading from cache
  - Applying patches for drupal/panels
    https://www.drupal.org/files/issues/2019-02-06/initial.patch (3030976 - Panels should check if there is an icon map before setting the no preview icon)
    https://www.drupal.org/files/issues/panels-ipe-2878684-3.patch (2878684 - Use String.match to correlate regions when switching Layouts in Panels IPE)

  - Installing drupal/moderation_dashboard (1.0.0-beta1): Loading from cache
  - Installing kub-at/php-simple-html-dom-parser (1.9.1): Loading from cache
  - Installing ezyang/htmlpurifier (v4.12.0): Loading from cache
  - Installing caxy/php-htmldiff (v0.1.9): Loading from cache
  - Installing mkalkbrenner/php-htmldiff-advanced (0.0.8): Loading from cache
  - Installing drupal/diff (1.0.0-rc2): Loading from cache
  - Installing phpdocumentor/reflection-common (2.0.0): Loading from cache
  - Installing phpdocumentor/type-resolver (1.0.1): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.3.2): Loading from cache
  - Installing drupal/token (1.5.0): Loading from cache
  - Installing drupal/search_api (1.14.0): Loading from cache
  - Installing drupal/pathauto (1.5.0): Loading from cache
  - Installing drupal/metatag (1.10.0): Loading from cache
  - Installing drupal/contact_storage (1.0.0-beta10): Loading from cache
  - Installing solarium/solarium (3.8.1): Loading from cache
  - Installing drupal/search_api_solr (1.2.0): Loading from cache
  - Installing drupal/acquia_connector (1.16.0): Loading from cache
  - Installing drupal/redirect (1.4.0): Loading from cache
  - Installing drupal/lightning_core (4.7.0): Loading from cache
  - Installing drupal/conflict (2.0.0-alpha1): Loading from cache
  - Installing drupal/autosave_form (1.0.0): Loading from cache
  - Installing drupal/lightning_workflow (3.10.0): Loading from cache
  - Installing vardot/blazy (1.8.2.1): Loading from cache
  - Installing drupal/video_embed_field (2.2.0): Loading from cache
  - Installing drupal/blazy (1.0.0-rc4): Loading from cache
  - Installing drupal/slick (1.1.0): Loading from cache
  - Installing drupal/slick_entityreference (1.1.0): Loading from cache
  - Installing j7mbo/twitter-api-php (1.0.6): Loading from cache
  - Installing drupal/media_entity_twitter (2.0.0-alpha3): Loading from cache
  - Installing drupal/media_entity_instagram (2.0.0-alpha2): Loading from cache
  - Installing drupal/libraries (3.0.0-alpha1): Loading from cache
  - Applying patches for drupal/libraries
    https://www.drupal.org/files/issues/2882709-2-interface-libraryidaccessorinterface-misnamed.patch (2882709 - Misnamed interface causes "Fatal error: Cannot declare interface Drupal\libraries\ExternalLibrary\Utility\LibraryAccessorIdInterface")

  - Installing drupal/crop (2.0.0-rc1): Loading from cache
  - Installing drupal/image_widget_crop (2.2.0): Loading from cache
  - Installing drupal/embed (1.0.0): Loading from cache
  - Installing drupal/dropzonejs (2.0.0-alpha4): Loading from cache
  - Installing bower-asset/jquery (3.4.1): Loading from cache
  - Installing bower-asset/slick-carousel (v1.8.1): Loading from cache
  - Installing bower-asset/dropzone (v5.5.0): Loading from cache
  - Installing bower-asset/cropper (v2.3.4): Loading from cache
  - Installing drupal/views_infinite_scroll (1.6.0): Loading from cache
  - Installing drupal/inline_entity_form (1.0.0-rc2): Loading from cache
  - Installing drupal/entity_embed (1.0.0): Loading from cache
  - Installing drupal/entity_browser (2.1.0): Loading from cache
  - Applying patches for drupal/entity_browser
    https://www.drupal.org/files/issues/entity-browser-view-context-2865928-14.patch (2865928 - The View widget should filter based on field settings)
    https://www.drupal.org/files/issues/2877751-27-8.x-2.x.patch (2877751 - Inform users how many items they can add to a field that uses an entity browser)

  - Installing drupal/lightning_media (3.12.0): Loading from cache
  - Installing drupal/simple_gmap (1.4.0): Loading from cache
  - Installing drupal/panels_ipe (4.4.0)
  - Installing drupal/ctools_block (3.0.0)
  - Installing drupal/panelizer (4.1.0): Loading from cache
  - Applying patches for drupal/panelizer
    https://www.drupal.org/files/issues/2018-08-13/panelizer-multilingual-2778565-38.patch (2778565 - Multilingual support for Panelizer)

  - Installing drupal/entity_browser_block (1.0.0): Loading from cache
  - Installing drupal/entity_block (1.0.0-beta1): Loading from cache
  - Installing drupal/bg_image_formatter (1.11.0): Loading from cache
  - Installing drupal/layout_library (1.0.0-beta1): Loading from cache
  - Installing drupal/layout_builder_st (1.0.0-alpha1): Loading from cache
  - Installing drupal/layout_builder_restrictions (2.2.0): Loading from cache
  - Installing drupal/lightning_layout (2.1.0): Loading from cache
  - Installing defuse/php-encryption (v2.2.1): Loading from cache
  - Installing lcobucci/jwt (3.3.1): Loading from cache
  - Installing league/event (2.2.0): Loading from cache
  - Installing drupal/consumers (1.9.0): Loading from cache
  - Applying patches for drupal/consumers
    https://www.drupal.org/files/issues/2019-05-17/3052959-12.patch (3052959 - Update 8103 does not work with Drupal 8.7)

  - Installing league/oauth2-server (7.4.0): Loading from cache
  - Installing drupal/simple_oauth (3.16.0): Loading from cache
  - Installing drupal/simple_oauth_extras (3.16.0)
  - Installing drupal/openapi_ui (1.0.0-rc2): Loading from cache
  - Installing swagger-api/swagger-ui (v3.24.2): Loading from cache
  - Installing drupal/openapi_ui_swagger (1.0.0-rc3): Loading from cache
  - Installing drupal/openapi_ui_redoc (1.0.0-rc2): Loading from cache
  - Installing drupal/schemata (1.0.0-beta1): Loading from cache
  - Installing drupal/schemata_json_schema (1.0.0-beta1)
  - Installing drupal/openapi (1.0.0-beta6): Loading from cache
  - Installing drupal/lightning_api (4.2.0): Loading from cache
  - Installing drupal/claro (1.0.0-beta1): Loading from cache
  - Installing acquia/lightning (4.0.4): Loading from cache
  - Installing drupal/purge (3.0.0-beta9): Loading from cache
  - Installing drupal/purge_drush (3.0.0-beta9)
  - Installing drupal/acquia_purge (1.0.0): Loading from cache
  - Installing drupal/cog (1.13.0): Loading from cache
  - Installing drupal/config_filter (1.5.0): Loading from cache
  - Installing drupal/config_split (1.4.0): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.2): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing doctrine/instantiator (1.2.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.3): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing phpspec/prophecy (1.9.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.9.3): Loading from cache
  - Installing phpunit/phpunit (6.5.14): Loading from cache
  - Installing mikey179/vfsstream (v1.6.8): Loading from cache
  - Installing justinrainbow/json-schema (5.2.9): Loading from cache
  - Installing symfony/phpunit-bridge (v3.4.33): Loading from cache
  - Installing jcalderonzumba/gastonjs (v1.2.0): Loading from cache
  - Installing jcalderonzumba/mink-phantomjs-driver (v0.3.3): Loading from cache
  - Installing webflo/drupal-core-require-dev (8.7.8)
  - Installing textalk/websocket (1.2.0): Loading from cache
  - Installing dmore/chrome-mink-driver (2.7.0): Loading from cache
  - Installing dmore/behat-chrome-extension (1.3.0): Loading from cache
  - Installing se/selenium-server-standalone (v2.53.1): Loading from cache
  - Installing jarnaiz/behat-junit-formatter (v1.3.2): Loading from cache
  - Installing bex/behat-extension-driver-locator (1.0.2): Loading from cache
  - Installing bex/behat-screenshot (1.2.8): Loading from cache
  - Installing acquia/blt-require-dev (10.0.0-beta1)
  - Installing drupal/devel (2.1.0): Loading from cache
  - Installing drupal/config_update (1.6.0): Loading from cache
  - Installing drupal/features (3.8.0): Loading from cache
  - Installing drupal/qa_accounts (1.0.0-alpha1): Loading from cache
  - Installing drupal/seckit (1.2.0): Loading from cache
  - Installing drupal/shield (1.2.0): Loading from cache
pear/archive_tar suggests installing ext-xz (Lzma2 compression support.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/psr-http-message-bridge suggests installing nyholm/psr7 (For a super lightweight PSR-7/17 implementation)
zendframework/zend-feed suggests installing zendframework/zend-cache (Zend\Cache component, for optionally caching feeds between requests)
zendframework/zend-feed suggests installing zendframework/zend-db (Zend\Db component, for use with PubSubHubbub)
zendframework/zend-feed suggests installing zendframework/zend-http (Zend\Http for PubSubHubbub, and optionally for use with Zend\Feed\Reader)
zendframework/zend-feed suggests installing zendframework/zend-servicemanager (Zend\ServiceManager component, for easily extending ExtensionManager implementations)
zendframework/zend-feed suggests installing zendframework/zend-validator (Zend\Validator component, for validating email addresses used in Atom feeds and entries when using the Writer subcomponent)
easyrdf/easyrdf suggests installing ml/json-ld (~1.0)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
symfony/validator suggests installing psr/cache-implementation (For using the metadata cache.)
symfony/validator suggests installing symfony/intl
symfony/validator suggests installing symfony/property-access (For accessing properties within comparison constraints)
symfony/validator suggests installing symfony/expression-language (For using the Expression validator)
symfony/serializer suggests installing psr/cache-implementation (For using the metadata cache.)
symfony/serializer suggests installing symfony/property-info (To deserialize relations.)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/console suggests installing symfony/lock
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
acquia/http-hmac-php suggests installing silex/silex (~1.3.0)
acquia/http-hmac-php suggests installing symfony/security (~3.0.0)
symfony/twig-bridge suggests installing symfony/asset (For using the AssetExtension)
symfony/twig-bridge suggests installing symfony/form (For using the FormExtension)
symfony/twig-bridge suggests installing symfony/templating (For using the TwigEngine)
symfony/twig-bridge suggests installing symfony/security (For using the SecurityExtension)
symfony/twig-bridge suggests installing symfony/stopwatch (For using the StopwatchExtension)
symfony/twig-bridge suggests installing symfony/expression-language (For using the ExpressionExtension)
symfony/twig-bridge suggests installing symfony/web-link (For using the WebLinkExtension)
nette/bootstrap suggests installing tracy/tracy (to use Configurator::enableTracy())
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
acquia/blt suggests installing davereid/drush-acquia-hook-invoke (dev-master)
acquia/blt suggests installing hirak/prestissimo (^0.3)
acquia/blt suggests installing typhonius/acquia_cli (^1.0)
behat/mink suggests installing behat/mink-zombie-driver (fast and JS-enabled headless driver for any app (requires node.js))
behat/behat suggests installing behat/symfony2-extension (for integration with Symfony2 web framework)
behat/behat suggests installing behat/yii-extension (for integration with Yii web framework)
drupal/search_api suggests installing drupal/facets (Adds the ability to create faceted searches.)
drupal/search_api suggests installing drupal/search_api_autocomplete (Allows adding autocomplete suggestions to search fields.)
solarium/solarium suggests installing minimalcode/search (Query builder compatible with Solarium, allows simplified solr-query handling)
drupal/search_api_solr suggests installing drupal/facets (Provides facetted search.)
drupal/search_api_solr suggests installing drupal/search_api_solr_multilingual (Highly recommended if installation is multilingual or uses a language different than English.)
drupal/dropzonejs suggests installing enyo/dropzone (Required to user drupal/dropzonejs. Dropzone is an easy to use drag'n'drop library.)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
bex/behat-screenshot suggests installing bex/behat-screenshot-image-driver-uploadpie (Allows to upload the screenshot to uploadpie.com)
bex/behat-screenshot suggests installing bex/behat-screenshot-image-driver-img42 (Allows to upload the screenshot to img42.com)
bex/behat-screenshot suggests installing bex/behat-screenshot-image-driver-unsee (Allows to upload the screenshot to unsee.cc)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
You are using Drupal packages that are not supported by the Drupal Security Team!
  - drupal/page_manager:4.0.0.0-beta3: Project has not opted into security advisory coverage!
  - drupal/moderation_dashboard:1.0.0.0-beta1: Beta releases are not covered by Drupal security advisories.
  - drupal/diff:1.0.0.0-RC2: RC releases are not covered by Drupal security advisories.
  - drupal/contact_storage:1.0.0.0-beta10: Beta releases are not covered by Drupal security advisories.
  - drupal/conflict:2.0.0.0-alpha1: Alpha releases are not covered by Drupal security advisories.
  - drupal/blazy:1.0.0.0-RC4: RC releases are not covered by Drupal security advisories.
  - drupal/media_entity_twitter:2.0.0.0-alpha3: Alpha releases are not covered by Drupal security advisories.
  - drupal/media_entity_instagram:2.0.0.0-alpha2: Alpha releases are not covered by Drupal security advisories.
  - drupal/libraries:3.0.0.0-alpha1: Alpha releases are not covered by Drupal security advisories.
  - drupal/crop:2.0.0.0-RC1: RC releases are not covered by Drupal security advisories.
  - drupal/dropzonejs:2.0.0.0-alpha4: Project has not opted into security advisory coverage!
  - drupal/inline_entity_form:1.0.0.0-RC2: RC releases are not covered by Drupal security advisories.
  - drupal/entity_block:1.0.0.0-beta1: Beta releases are not covered by Drupal security advisories.
  - drupal/layout_library:1.0.0.0-beta1: Beta releases are not covered by Drupal security advisories.
  - drupal/layout_builder_st:1.0.0.0-alpha1: Project has not opted into security advisory coverage!
  - drupal/openapi_ui:1.0.0.0-RC2: RC releases are not covered by Drupal security advisories.
  - drupal/openapi_ui_swagger:1.0.0.0-RC3: RC releases are not covered by Drupal security advisories.
  - drupal/openapi_ui_redoc:1.0.0.0-RC2: RC releases are not covered by Drupal security advisories.
  - drupal/schemata:1.0.0.0-beta1: Beta releases are not covered by Drupal security advisories.
  - drupal/schemata_json_schema:1.0.0.0-beta1: Beta releases are not covered by Drupal security advisories.
  - drupal/openapi:1.0.0.0-beta6: Project has not opted into security advisory coverage!
  - drupal/claro:1.0.0.0-beta1: Beta releases are not covered by Drupal security advisories.
  - drupal/purge:3.0.0.0-beta9: Beta releases are not covered by Drupal security advisories.
  - drupal/purge_drush:3.0.0.0-beta9: Beta releases are not covered by Drupal security advisories.
  - drupal/qa_accounts:1.0.0.0-alpha1: Project has not opted into security advisory coverage!
See https://www.drupal.org/security-advisory-policy for more information.
PHP CodeSniffer Config installed_paths set to ../../drupal/coder/coder_sniffer
Creating BLT templated files...
 > /Users/viktar.silakou/test-blt/vendor/acquia/blt/bin/blt internal:create-project --ansi
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /Users/viktar.silakou/test-blt/vendor/acquia/blt/RoboFile.php on line 394

Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /Users/viktar.silakou/test-blt/vendor/acquia/blt/RoboFile.php on line 394
BLT installation failed! Please execute /Users/viktar.silakou/test-blt/vendor/acquia/blt/bin/blt internal:create-project --ansi --verbose to debug the issue.

  [Exception]
  Installation aborted due to error`
**BLT doctor output**

BLT doctor fails with the same error

**System information**
* Operating system type: macOS
* Operating system version: Mojave 10.14.16
* BLT version: 10.5.0

**Comment by danepowell** [comment]
BLT doesn't do anything to change the PHP memory limit. It certainly wouldn't make the memory limit _lower_ than what's set by default. Something in your PHP configuration must be making it so low (only 2M?) Are you sure you don't have multiple PHP versions installed with different memory limits, or perhaps an override in a setting file for your Drupal site, or in a php.ini file specific to a particular CLI?

**Comment by viktor-silakov** [comment]
hi @danepowell, I didn't found other PHP versions on my laptop. I paste a bit code in `vendor/composer/autoload_real.php` -in this file, the requiring of `RoboFile.php` is occurring, this code: `exit(ini_get('memory_limit'));`  and this tells me that have limit: `4GB`

**Comment by viktor-silakov** [comment]
> or perhaps an override in a setting file for your Drupal site

What did you mean? I create a new project here.

**Comment by viktor-silakov** [comment]
Also, I have tried running such a way: `php -d memory_limit=-1 composer.phar create-project`, unfortunately, the same result.

**Comment by viktor-silakov** [comment]
Сurrent information about the problem at the moment:
1. I have two versions of PHP on my laptop, one of them I can't remove because it is system files:
the first one:
![image](https://user-images.githubusercontent.com/23633060/68297847-01ecf180-00a9-11ea-86c1-23e112047131.png)
the second one:
![image](https://user-images.githubusercontent.com/23633060/68297981-555f3f80-00a9-11ea-807e-a0b50e5bb77b.png)
2. I start to create the BLT project via command:
`composer create-project --no-interaction --ignore-platform-reqs acquia/blt-project test-blt7`
and get an error:
`PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223
`
because 1.5GB is [internal](https://getcomposer.org/doc/articles/troubleshooting.md) value for composer 

I decide to disable memory limit for composer and run the command:
`COMPOSER_MEMORY_LIMIT=-1 composer create-project --no-interaction --ignore-platform-reqs acquia/blt-project test-blt8`
the previous stage pass OK but then I get an error:
`Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /Users/viktar.silakou/test-blt8/vendor/acquia/blt/RoboFile.php on line 394`
looks like RoboFile.php don't take memory limits from composer. %(

**Comment by viktor-silakov** [comment]
Finally, I found out the reason. There is a mistake in my PHP.INI file, the thing is  PHP doesn't understand 'GB' notation, I changed `memory_limit = 4GB` to `memory_limit = 4G` and all works fine.
