### ISSUE TITLE
DT-985: Deprecation scanning broken

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3924]
**Describe the bug**
It seems that deprecation scanning is broken, likely due to an upstream issue with PHPStan or some other component. Scans throw a fatal error and never print any results for many common modules, such as ctools, lightning, views: https://travis-ci.com/acquia/lightning_media/jobs/258305587#L2177

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project --no-interaction`
2. Modify the deprecation command to scan the contrib directory

**Comment by danepowell** [comment]
Maybe memory issue?

**Comment by ondrejmirtes** [comment]
What kind of message is printed out during the fatal error? Can your run PHPStan directly? Does it work if you increase memory limit?

**Comment by danepowell** [comment]
@ondrejmirtes thanks for the offer of assistance. This seems to be a couple of related but separate problems with the modules being scanned, not a problem with the scanner itself. However, there is one odd thing... even though the below errors pretty clearly point to problems with the code being scanned, PHPStan outputs `PHPStan crashed in the previous run probably because of excessive memory consumption...` the next time it's run. I think that's a red herring.

1. **media_acquiadam module**: The deprecation scanner was [throwing a fatal error](https://travis-ci.com/acquia/lightning_media/jobs/258305587#L2177) when scanning the media_acquiadam module. It turns out this was because the module [didn't properly declare a dependency](https://git.drupalcode.org/project/media_acquiadam/commit/fd2965b).
2. **devel module**: A possibly related error (stacktrace pasted below) when scanning the devel module. I suspect the devel module is using a class from webprofiler or Drupal Console without correctly declaring a dependency, but I haven't been able to figure out exactly what.

```
PHP Fatal error:  During class fetch: Uncaught PHPStan\Broker\ClassAutoloadingException: Class Drupal\Console\Core\Command\Shared\ContainerAwareCommandTrait not found and could not be autoloaded. in /Users/dane/scratch/dt985/vendor/phpstan/phpstan/src/Broker/Broker.php:360
Stack trace:
#0 [internal function]: PHPStan\Broker\Broker->PHPStan\Broker\{closure}('Drupal\\Console\\...')
#1 /Users/dane/scratch/dt985/docroot/modules/contrib/devel/webprofiler/src/Command/ExportCommand.php(24): spl_autoload_call('Drupal\\Console\\...')
#2 /Users/dane/scratch/dt985/vendor/composer/ClassLoader.php(444): include('/Users/dane/scr...')
#3 /Users/dane/scratch/dt985/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/dane/scr...')
#4 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\webprofi...')
#5 [internal function]: spl_autoload_call('Drupal\\webprofi...')
#6 /Users/dane/scratch/dt985/vendor/phpstan/phpstan/src/Broker/Broker.php(365): class_exists('Drupal\\webprofi...')
#7 /Users/dane/scratch/dt9 in /Users/dane/scratch/dt985/docroot/modules/contrib/devel/webprofiler/src/Command/ExportCommand.php on line 24
```

**Comment by ondrejmirtes** [comment]
Looks like the code in /Users/dane/scratch/dt985/docroot/modules/contrib/devel/webprofiler/src/Command/ExportCommand.php uses PHPStan in a wrong way. Is that code open-source?

**Comment by danepowell** [comment]
Yep I think this is the file you are looking for: https://git.drupalcode.org/project/devel/blob/8.x-2.x/webprofiler/src/Command/ExportCommand.php

**Comment by ondrejmirtes** [comment]
I see the error. PHPStan tries to load this ExportCommand class, but it cannot find this trait: ContainerAwareCommandTrait

Make sure it's in the autoload and it should be fine.

**Comment by danepowell** [comment]
Thanks. All of the errors seem to be problems with the upstream modules so I'll take it up with them. No further action required here.
