### ISSUE TITLE
DT-1034: Move Behat testing to plugin

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3928]
I'd like to have an open discussion around the strengths and weaknesses of different tools for behavior-driven testing, and specifically around the question of removing Behat support from core BLT, and maybe moving it to a plugin.

Behat is often touted as a preferred BDD tool because of its use of Gherkin, a friendlier testing language than PHP. But that approachability comes at a cost, especially when it comes to custom step definitions (which are written in PHP anyway) and the overhead of an additional layer of abstraction when writing and debugging tests. The value of Gherkin syntax varies from project to project, but I've generally found it to be slim. Mostly the only people looking at tests are developers anyway.

It's also telling that neither Drupal core nor Lightning use Behat or Gherkin anywhere (that I'm aware of). Core only supports tests written with PHPUnit and Nightwatch (which BLT will soon support: #3573), and Lightning just uses PHPUnit. As a rule, I think it's wise to align with Lightning and Drupal core.

Maintenance of Behat integration is significant, both for BLT and individual projects. Behat tests often fail in cryptic and arcane ways that are difficult to debug, and BLT spends a significant amount of time responding to Behat-related support requests as well as managing the complex infrastructure (so many yaml files and config options...) necessary to support Behat tests.

Finally, I worry about the long-term stability of Behat. BLT currently locks users to a version of Behat that is several years old, because of a critical outstanding upstream bug that has been open for years and even has a PR with several approving community reviews, but no word on when or if it will be fixed. See #3559 

What I would propose as a resolution to all of these issues is to move Behat integration to a community-supported plugin, so that individual projects can still use it if they find value in it, but as a standard practice we recommend alternatives such as PHPUnit and Nightwatch. Optionally, we could even recommend something like https://github.com/MikkelPaulson/phpunit-gherkin if people really want to hang on to Gherkin, but with PHPUnit.

**Comment by ba66e77** [comment]
I can get on-board with moving to PHPUnit Functional tests instead of Behat. My concern is that BLT sets up a lot more of the Behat settings for you with `blt setup:behat` but there isn't a parallel command to simplify setting up PHPUnit testing. 

There is some [documentation of what to add to blt.yml ](https://docs.acquia.com/blt/developer/testing/) but the setup, especially for folks unfamiliar with PHPUnit, is still non-trivial. With the goal of promoting automated testing as part of best practices, I'd like to see BLT ease the setup for people to get started with PHPUnit testing if it's moving away from Behat.

**Comment by lpeabody** [comment]
I would be on board with moving Behat out of BLT core. The way it's currently implemented doesn't really jive seamlessly with our multisite setups.

I think Moshe's Drupal Test Traits deserves a shoutout https://gitlab.com/weitzman/drupal-test-traits. I've used it in place of Behat in several instances when I just don't feel like dealing with the Gherkin layer of things. On top of that, it has active support.

**Comment by mikemadison13** [comment]
I think it makes a ton of sense for Drupal Core and Lightning (and other modules) NOT to use Behat. However, I think Project based testing (which is where the BDD part really comes to play) makes a ton of sense in Behat. There's a lot of stuff you can do with Behat in terms of custom feature contexts and execution that to me, doesn't feel like PHPunit should be the thing that will own it. It's not "unit testing."

From a PS perspective I really think we will continue to recommend Behat. I guess I don't care if it's "in BLT" or "in a Plugin" but I would think that plugin should be there by default when I spin up a new project...

**Comment by ba66e77** [comment]
> However, I think Project based testing (which is where the BDD part really comes to play) makes a ton of sense in Behat. There's a lot of stuff you can do with Behat in terms of custom feature contexts and execution that to me, doesn't feel like PHPunit should be the thing that will own it. It's not "unit testing."

I don't disagree, but core is taking the perspective that [all the tests are PHPUnit of one flavor or another](https://www.drupal.org/docs/8/testing/types-of-tests-in-drupal-8). Is the recommendation here that PHPUnit be used for Unit and Kernel tests (as defined on that core page) but Behat should be used for Functional and Javascript tests?

**Comment by danepowell** [comment]
Note that at least theoretically, you can use Gherkin with PHPUnit, which would be the best of all worlds, no? https://github.com/MikkelPaulson/phpunit-gherkin

**Comment by ejanus** [comment]
How can I disable Behat tests on my BLT project? I am getting weird issues when I disable the page_cache module (in order to use the acquia analytics redirects module: https://www.drupal.org/project/acquia_analytics_redirects/releases/8.x-1.0-beta2). 

I can't find any documentation on how to disable behat tests on BLT?

**Comment by danepowell** [comment]
#4115
