### ISSUE TITLE
How to develop/sync individual ACSF sites locally?

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3932]
**I want to...**
Sync down production data (database and files) for individual ACSF sites locally so that I can develop them individually in a local environment. I'm migrating a ACE multisite into ACSF, and trying to maintain our current workflow where this was supported really well.

Multisite worked really well actually, and I was hoping it would work just as well with site factory. Our team loves that we can have have multiple sites set up in our local environment simultaneously.

**It's not working because...**
Well, for this to work correctly, BLT needs to know what drush alias to use when performing the sync, and it needs to know where to put the files, which would normally go in the multisite folder.

Running `blt --site=[multisite_name] drupal:sync` does not work. In our previous multisite setup, we had individual site folders for each multisite. In those folders, there would be a BLT file provided the following:

```
drush:
  aliases:
    remote: '[multisite_name].prod'
    local: '[multisite_name].local'
```

So when we raun the sync command, BLT would load this overrides file and know to use the correct aliases.

I wonder how other Acquia customers that use ACSF are dealing with this? Do they just not use local environment at all for individual sites?

**System information**
* Operating system type: OSX
* Operating system version: 10.14.6
* BLT version: 10.5

**Comment by lpeabody** [comment]
Ha, I wrote a command to help with this not too long ago, it does the following:

1) Generates a new site directory named "acsf_[sitename]" (e.g. acsf_myacsfsitename) from a pre-existing template.
2) Adds a Drush entry automatically to drush/sites/local-acsf.site.yml.
3) Adds a sites.php entry for the new site:
```
<?php

$sites['myacsfsitename.edelman.docksal'] = 'acsf_myacsfsitename';
```

The following files are git ignored:

- drush/sites/local-acsf.site.yml
- factory-hooks/pre-sites-php/local-acsf.php
- docroot/sites/acsf_*

I'm a pretty big fan of this approach since it allows me to bring down individual sites that run off of the same distribution, and I can prove to myself that updates I apply to one apply cleanly to the other all while on my local system.

I'm in the process of updating this codebase to BLT 10 right now, and with it comes the new BLT plugin system for commands, so I should be able to share it. I can't really give a timeline for that the moment though :\

**Comment by bkosborne** [comment]
Thanks, that would be great to share!

I think the approach you took was the same one I was thinking. Basically to create a true multisite setup in the local environment.

I found that there has been some effort to make this process better in #1816 but the issue was ultimately closed after half of it was completed.

**Comment by bkosborne** [comment]
I made my own command that does pretty much what @lpeabody said:

```
<?php

namespace PrincetonBlt\Blt\Plugin\Commands;

use Acquia\Blt\Robo\BltTasks;
use Consolidation\AnnotatedCommand\CommandData;
use Symfony\Component\Filesystem\Filesystem;

/**
 * Replace the BLT command
 */
class PrepareMultisiteCommand extends BltTasks {

  /**
   * Verify multisite is setup before performing actions on it.
   *
   * When running commands for a specific multisite, the --site=[sitename]
   * option can be passed. Before we allow a user to do that, check first
   * that the multisite folder exists for the specified site. Users must
   * first run a separate command to create this multisite folder and other
   * files for the site.
   *
   * @hook pre-command *
   */
  public function checkMultisiteIsPrepared(CommandData $commandData) {
    // Do nothing if the command being run is our custom multisite prep
    // command.
    $cmdAnnotationData = $commandData->annotationData();
    if (isset($cmdAnnotationData['command']) && $cmdAnnotationData['command'] === 'ps:prepare-site') {
      return;
    }

    // If this command is operating in an individual site, then check
    // that the multisite foldere for that site exists.
    $site = $this->getConfigValue('site');
    if (!empty($site)) {
      $fs = new Filesystem();
      if (!$fs->exists($this->getConfigValue('repo.root') . '/docroot/sites/' . $site)) {
        throw new \RuntimeException('You need to run `blt --site=' . $site . ' ps:prepare-site` command first to prepare your local environment for the site.');
      }
    }
  }

  /**
   * Prepare config/data for commands that operate on a multisite.
   *
   * BLT can handle multisites locally and assumes that the multisite folder
   * will exist for each site. ACSF is multisite, but doesn't use traditional
   * multisite folders.
   *
   * To allow our staff to work on individual ACSF sites locally, this command
   * can be used to create the multisite files in the local env that are
   * required. Gitignore files are used to prevent them from being committed.
   *
   * A staff member should use this command before trying to sync down a
   * specific production ACSF to local env.
   *
   * This command should be run with the --site=[sitename] option passed.
   *
   * This command will:
   * 1) Create the multisite folder for the site and add the appropriate files.
   * 2) Create the drush aliases file for the site.
   * 3) Add an entry to sites.php.
   *
   * @command ps:prepare-site
   */
  public function prepareMultisiteData() {
    $site = $this->getConfigValue('site');
    if (!empty($site)) {
      if ($site === 'default') {
        throw new \RuntimeException('You cannot run this command for the default site.');
      }

      $fs = new Filesystem();
      // Create the multisite directory if it does not already exist.
      $siteDir = $this->getConfigValue('repo.root') . '/docroot/sites/' . $site;
      $this->say($siteDir);
      if (!$fs->exists($siteDir)) {
        $this->say('Creating multisite directory for ' . $site);
        $this->taskFilesystemStack()
          ->mkdir($siteDir)
          ->stopOnFail()
          ->run();
      }

      // Create BLT config override file for the site.
      $bltOverridesFile = $siteDir . '/blt.yml';
      $contents = "project.machine_name: $site
drupal.db.database: $site";
      $this
        ->taskFilesystemStack()
        ->stopOnFail()
        ->dumpFile($bltOverridesFile, $contents)
        ->run();

      // Create settings file from template.
      $settingsFile = $siteDir . '/settings.php';
      $contents = '<?php
$blt_override_config_directories = FALSE;
require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";
';
      $this
        ->taskFilesystemStack()
        ->stopOnFail()
        ->dumpFile($settingsFile, $contents)
        ->run();

      // Create local settings file from template.
      $localSettingsFileSource = $this->getConfigValue('repo.root') . '/docroot/sites/default/settings/default.local.settings.php';
      $localSettingsFile = $siteDir . '/settings/local.settings.php';
      $this
        ->taskFilesystemStack()
        ->stopOnFail()
        ->copy($localSettingsFileSource, $localSettingsFile)
        ->run();
      $this->getConfig()->expandFileProperties($localSettingsFile);

      // Create the public and private files directories.
      $this
        ->taskFilesystemStack()
        ->stopOnFail()
        ->mkdir($siteDir . '/files')
        ->mkdir($this->getConfigValue('repo.root') . '/files-private/' . $site)
        ->run();

      // Create drush alias file.
      $template = '
local:
    uri: {{SITE}}
01live:
    uri: {{SITE}}.[redacted].acsitefactory.com
    host: [redacted]01live.ssh.enterprise-g1.acquia-sites.com
    paths: { dump-dir: /mnt/tmp }
    root: /var/www/html/[redacted].01live/docroot
    user: [redacted].01live
01test:
    uri: {{SITE}}.test-[redacted].acsitefactory.com
    host: [redacted]01test.ssh.enterprise-g1.acquia-sites.com
    paths: { dump-dir: /mnt/tmp }
    root: /var/www/html/[redacted].01test/docroot
    user: [redacted].01test
01dev:
    uri: {{SITE}}.dev-[redacted].acsitefactory.com
    host: [redacted]01dev.ssh.enterprise-g1.acquia-sites.com
    paths: { dump-dir: /mnt/tmp }
    root: /var/www/html/[redacted].01dev/docroot
    user: [redacted].01dev
      ';
      $drushFileContents = str_replace('{{SITE}}', $site, $template);
      $drushAliasFile = $this->getConfigValue('repo.root') . '/drush/sites/' . $site . '.site.yml';
      $this
        ->taskFilesystemStack()
        ->stopOnFail()
        ->dumpFile($drushAliasFile, $drushFileContents)
        ->run();

      // Create the initial sites file if it does not already exist.
      $sitesFile = $this->getConfigValue('repo.root') . '/factory-hooks/pre-sites-php/local-acsf.php';
      if (!$fs->exists($sitesFile)) {
        $sitesFileContents = '<?php
// This file is automatically managed by Princeton\'s custom BLT integration.
// Do not modify the contents of this file directly.
// See PrepareMultisiteCommand.php' . "\n\n";
        $this
          ->taskFilesystemStack()
          ->stopOnFail()
          ->dumpFile($sitesFile, $sitesFileContents)
          ->run();
      }

      // Add an entry to the multisite file for the requested site if it's not
      // already there.
      $fileContents = file_get_contents($sitesFile);
      if (strpos($fileContents, "'" . $site . "'") === FALSE) {
        $this
          ->taskFilesystemStack()
          ->stopOnFail()
          ->appendToFile($sitesFile, "\$sites['$site.localhost.princeton.edu'] = '$site';\n")
          ->run();
      }

      $this->say("The site \"$site\" has been setup and you can now run commands like `blt --site=$site drupal:sync`.");
      $this->say("Note that before you can visit the site in your browser, you need to run the `scripts/add-hosts` from your computer.");
    }
  }

}
```

**Comment by pixlkat** [comment]
I managed to get a multisite set up for an ACSF project locally by running the `blt recipes:multisite:init` command for each multisite I wanted to use locally. I got rid of some of the changes to `default.local.settings.php` first -- basically, get rid of anything that references `$_acsf_site_name` as that doesn't work at all, and set your file paths appropriately to use the `$site_dir` variable. In the local site directory that blt creates, add your db info to the blt.yml file inside the site directory. 

```
drupal:
  db:
    database: drupal_acsfsitename
```
 You will need to regenerate your local settings file after the multisite command completes so it gets the database name set correctly.

I did something slightly more hacky than your pre-sites-php file. I created a `local.sites.php` file in the same directory as the ACSF decorated sites.php file, and made the following change to that file so my local sites.php file got loaded when i was on the local environment.

```
// Check that we are on an Acquia server so we do not run this code for local
// development.
if (!is_acquia_host()) {
  if (file_exists(dirname(__FILE__) . '/local.sites.php')) {
    include dirname(__FILE__) . '/local.sites.php';
  }
  return;
}
```

We are using site-based splits and those work based on the `$site_dir` variable in BLT's `config.settings.php` file.

**Comment by bkosborne** [comment]
Thanks for sharing! I totally forgot about that multisite command in BLT. I should have looked down that path first, but sounds like you needed to do some custom work in addition to it anyway

**Comment by lpeabody** [comment]
Doesn't ACSF complain if you modify sites.php? All pre/post-sites-php factory hooks are invoked even locally, which is why I put my local acsf sites file in the pre-sites-php factory hooks directory, gitignored it, and ensured it's excluded from BLT deployments. Given the rules ACSF puts before us, it's probably best to use the pre/post-sites-php hooks.

**Comment by bkosborne** [comment]
Note the [post-sites-php is not invoked locally](https://www.drupal.org/project/acsf/issues/2924959). Just the pre-sites-php hooks.

**Comment by lpeabody** [comment]
My mistake! That would probably be why I have it in pre-sites-php then :)

**Comment by danepowell** [comment]
It sounds like this was resolved. Most of the suggestions I've seen make sense in terms of using recipes:multisite:init and the pre-sites-php factory hook. Let me know if there's a specific feature request for BLT here.

**Comment by bkosborne** [comment]
Thanks @danepowell 

I think the problem is that support for local development of ACSF sites is not really supported by BLT out of the box, whereas it is for multisite. I think at the very least, some documentation needs to be updated to indicate that, and at the very best, first class support for local dev of the sites is added. #1816 attempted that but it didn't get far enough.

I'm in the middle of a big migration project into ACSF, so perhaps I can contribute the changes. Stay tuned.

**Comment by lpeabody** [comment]
This is probably best served in the BLT contrib space for now. There isn't really a tried and true method of handling local representation of sites in ACSF environments. Everyone I've talked to handles it differently. I think if folks who have solved this problem for their own teams turn their solutions into BLT plugins, and documented those solutions, that would be a good first step in maybe helping out the BLT maintainers know what should or shouldn't be included in core BLT.

**Comment by danepowell** [comment]
Thanks. I think the observation by @lpeabody is spot in that there isn't a single best practice around this. There might not ever be, I'm not sure. If we can at least arrive at a few established workflows, I would love to document them, but this might need to come from the contrib space in the short term.

I'm going to close this for now, but if anyone wants to recommend a specific workflow, documentation update, or plugin to add to our [plugin directory](https://docs.acquia.com/blt/plugins/), please open a new issue or PR. I'll also try to think about how we can better document this in the absence of a clear consensus.
