### ISSUE TITLE
DT-1128: Contributed Drush commands deployed as subprojects

### ISSUE THREAD

**Issue by malcolmp** [acquia/blt#3952]
**Issue Summary**
I am trying to pull a custom drush command library into a blt project for Acquia Cloud Sitefactory. This drush library is installed in `{root}/drush/Commands/custom/` in line with https://docs.drush.org/en/master/commands/#site-wide-drush-commands . However, blt doesn't sanitize the `./drush` directory, only `./docroot` and `./vendor` and as a result the drush commands aren't added to the build artifact.

**Expected behavior**
The simple change to support site wide drush commands is to add the .`/drush` directory to sanitization.

```
diff --git a/src/Robo/Commands/Deploy/DeployCommand.php b/src/Robo/Commands/Deploy/DeployCommand.php
index 7ff8ec56..18248660 100644
--- a/src/Robo/Commands/Deploy/DeployCommand.php
+++ b/src/Robo/Commands/Deploy/DeployCommand.php
@@ -433,7 +433,7 @@ protected function sanitize() {
       ->ignoreDotFiles(FALSE)
       ->ignoreVCS(FALSE)
       ->directories()
-      ->in(["{$this->deployDir}/docroot", "{$this->deployDir}/vendor"])
+      ->in(["{$this->deployDir}/docroot", "{$this->deployDir}/drush", "{$this->deployDir}/vendor"])
       ->name('.git');
     if ($vcsFinder->hasResults()) {
       $sanitizeFinder->append($vcsFinder);
```

**Comment by danepowell** [comment]
Thanks for the report. I think I understand what you are trying to accomplish (deploying custom drush commands), but I'm not sure this makes sense as a solution.

BLT specifically excludes `drush/Commands` when it builds the deploy artifact: https://github.com/acquia/blt/blob/11.x/scripts/blt/deploy/deploy-exclude.txt#L20

I don't understand how your solution would change that and cause the commands to be deployed. Additionally, if you have a custom Drush command, I don't understand why it would have a `.git` directory associated with it. Generally, libraries should either be custom and committed to the project-level Git repo, or contributed (can be "contributed" from a private repo) and managed via Composer.

**Comment by malcolmp** [comment]
We are in fact pulling in custom drush commands from a private repository into `drush/Commands/custom`, but without this change the blt artifact built in `/deploy` does not include the files from our drush command repository (despite them being installed by composer). Instead, it is committed as a submodule and thus isn't deployed to the server. Removing the `.git` directory is needed to commit the files from the command library to the artifact repo.

**Comment by danepowell** [comment]
I think you are right that the drush directory needs to be sanitized. An example of where this might cause problems is in BLT core, when acsf-tools is added to ACSF projects. It goes in `drush/Commands` and I just realized it is being committed as some sort of subproject, which is notoriously unstable.

I guess I was a little thrown by your use of the "custom" directory, when I would expect that to be "contrib" if you are adding the commands via Composer (even though it's technically a private repo and not "contrib", it's still important to treat it as contributed as far as Composer is concerned.)

Note that deploying truly custom Drush commands (committed to Git, not managed by Composer) I don't think is supported at the moment. That would need to be a separate feature request.
