### ISSUE TITLE
BLT commands to integrate cohesion.

### ISSUE THREAD

**Issue by saurabhtripathics** [acquia/blt#3955]
**Is your feature request related to a problem? Please describe.**
There are no commands, where we can integrate cohesion into drupal8, for example:
Perform cohesion tasks like asset import, sync and rebuild. (dx8:import, sync:import, dx8:rebuild).

**Describe the solution you'd like**
Create custom commands where we can do initialization of cohesion, import, export, and rebuld. 

**Describe alternatives you've considered**
Alternative solutions is always, manually running individual commands, but we cannot integrate blt with cohesion, unless we create these custom commands, and steer them from blt.yml

**Additional context**
<img width="789" alt="Screenshot 2019-12-18 at 3 02 18 PM" src="https://user-images.githubusercontent.com/50393153/71073989-75554900-21a7-11ea-8c87-80ec447e4ed0.png">

**Comment by danepowell** [comment]
BLT provides many methods to override or supplement its built-in commands: https://docs.acquia.com/blt/extending-blt/#modifying-your-acquia-blt-configuration

In this case, it sounds like you'd either want to implement [pre/post command events](https://github.com/consolidation/annotated-command#hooks) or completely override the commands in question.

You can do that on just your individual projects if you want, or you could easily package that functionality into a plugin.

One of these solutions should definitely work for you, you shouldn't need to run anything manually. As to whether this should be a feature in BLT core, I think that's a little premature. A plugin would be better to start until we can gauge demand for the feature.

**Comment by gauravgoyal** [comment]
@danepowell - Sounds good to me as well. We've already extended our project to support additional cohesion build during BLT setup. 

A plugin seems a great idea for now so that other projects can take benefit of the commands. and based on the usage or actual requirements, a decision to implement it in BLT core can be taken.

**Comment by danepowell** [comment]
Sounds good!
