### ISSUE TITLE
BltException message outputs broken link to Acquia docs

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#3956]
**Describe the bug**
The BltException message outputs a broken link to a non-existent FAQ: https://docs.acquia.com/blt/faq/

https://github.com/acquia/blt/blob/15f2ae7d007770364f137bfb5baf43f26fb30447/src/Robo/Exceptions/BltException.php#L21

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project --no-interaction`
2. Run any BLT command that throws an exception.

**Expected behavior**
I'm not sure where that FAQ page in the Acquia docs is or if these exceptions should point users at something else entirely.

**Detailed error output**
```
[error]  Aborted.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/faq/ 
```

**Comment by danepowell** [comment]
Thanks, you are right, that link is no longer valid. The correct link now should be https://docs.acquia.com/blt/support/
