### ISSUE TITLE
Automated Deprecated Module breaks build

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#3961]
**Describe the bug**
The new deprecated module checks are breaking the build process.

**Expected behavior**
Still run build successfully while alerting of existing Drupal 9 issues.

**Detailed error output**
`[ExecStack]  Exit code 1  Time 5.212s
[notice] Review Deprecation warnings and re-run.
[error]  Drupal Check in docroot/modules/custom failed.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
[error]  Command `tests:deprecated:modules ` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
`

**BLT doctor output**
Post the full output of `blt doctor` in the failing environment here.

**System information**
* Operating system type: Linux
* Operating system version: Ubuntu 18.04.3
* BLT version: 11.0.1
**Additional context**
Is there a way to stash alerts temporarily?

**Comment by jedgar1mx** [comment]
I was able to deploy my build by rolling back to version `10.0.0-rc1`. I will have to wait to upgrade until this is fixed.

**Comment by jedgar1mx** [comment]
missed configuration of `blt.yml` file, thanks to @danepowell for the pointer.

**Comment by danepowell** [comment]
For future Googlers, I think this is the reference that helped to fix this: https://support.acquia.com/hc/en-us/articles/360039081454#d9deprecatedcodescanningenabledbydefault
