### ISSUE TITLE
DT-1134: drupal:sync:files command copies files to the wrong directory if the public files path is set to something other than the Drupal default.

### ISSUE THREAD

**Issue by patrickcate** [acquia/blt#3966]
**Describe the bug**
The `drupal:sync:files` command copies files to the wrong directory if the public files path is set to something other than the Drupal default.

**To Reproduce**
1. In a drupal settings file such as `settings.php`, set the `$settings['file_public_path']` to a path other than the Drupal default `sites/default/files`
2. Run `blt drupal:sync:files`
3. Navigate to the `sites/default/files` and you will see the synced remote files.
4. Navigate to the `$settings['file_public_path']` defined path and you will not see the synced remote files.

**Expected behavior**
The remote files to be copied to the custom public files path of the site.

**System information**
* Operating system type: OSX
* Operating system version: 10.14.1
* BLT version: 10.x

**Additional context**
From what I can tell the issue is that the `syncFiles` function in `acquia/blt/src/Robo/Commands/Sync/SyncCommand.php` is hardcoded to `$this->getConfigValue('docroot') . "/sites/$site_dir/files"`

**Comment by danepowell** [comment]
Thanks for reporting. The issue makes sense as such, but I'm a little curious about the use case. Why would you relocate the public files directory? This is likely to cause problems in other places as well, since BLT manages that setting internally and expects that directory to be used.

We could try using the Drush local alias and `%files` key here, but it just seems like an awfully risky change for a behavior that's been in place since the beginning of BLT.

**Comment by patrickcate** [comment]
> Why would you relocate the public files directory? 

I know sometimes it was for migration/legacy reasons. When migrating sites with older versions of Drupal (6 & 7) which had the public directory customized, it was easier to keep migrated file paths correct by sticking to the customized public directory location.

I'm sure there is a myriad of other reasons this may be necessary for a site, hence the reason it can be customized in Drupal in the first place, but sysops is out of my skill range. I just have to deal with the changes :)

> This is likely to cause problems in other places as well, since BLT manages that setting internally and expects that directory to be used.

I've not run into any other issues except with the files sync, but if point me to others you think could be affected, I can test them.

**Comment by danepowell** [comment]
I'll have to test if using the local Drush alias + `%files` key works reliably and in the same way as hardcoding the directory, especially for multisites. I think that's the only reasonable way to fix this.

**Comment by danepowell** [comment]
I'm taking this out of the roadmap for now. It might still be a valid issue, but we need to make room for other priorities.

I suspect it's rare to override the public files path, and I'm not sure it's even supported on cloud, so it's not a use case I want to support at this time.

If you'd like to see this issue prioritized, feel free to submit product feedback via your TAM or a support ticket.
