### ISSUE TITLE
DT-1129: Cannot run core tests for Drupal 8.8.0 and PHP 7.3 due to PHPUnit version conflict

### ISSUE THREAD

**Issue by scottreese** [acquia/blt#3967]
**Is your feature request related to a problem? Please describe.**
Just updated a project to BLT 10.7.0 and Drupal 8.8.1 and now receive the following error when running `blt tests:drupal:run`:

```
ERROR: PHPUnit testing framework version 7 or greater is required when running on PHP 7.3 or greater. Run the command 'composer run-script drupal-phpunit-upgrade' in order to fix this.
```

Upon investigating this error, it appears this was introduced with Drupal 8.8.0: https://www.drupal.org/project/drupal/issues/3099061

More info also available here: https://www.drupal.org/node/2950132

Currently unable to install PHPUnit 7 due to the following constraint imposed by acquia/blt-require-dev:

```
$  composer why phpunit/phpunit
acquia/blt-require-dev          10.0.0-beta1  requires  phpunit/phpunit (^4.8|^6.5)
webflo/drupal-core-require-dev  8.8.1         requires  phpunit/phpunit (^6.5 || ^7)
```

**Describe the solution you'd like**
I would propose updating the phpunit requirements in acquia/blt-require-dev to include phpunit 7.

**Comment by mikemadison13** [comment]
@scottreese ^6.5 should allow for 7. That isn't a major version constraint. You may have to manually set your composer to be ^7 to force it up, but I don't see anything in what you posted that would prevent. Can you do a `composer why not phpunit/phpunit ^7` and see if anything jumps out? You _may_ need to nuke out your vendor directory or composer.lock files to get rid of circular dependencies.

**Comment by scottreese** [comment]
It was my understanding from reading the [composer docs](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) that using the caret means that only non-breaking (i.e. non major version) updates would be allowed which is in line with semantic versioning requirements. So in effect `^6.5` means `>=6.5.0 <7.0.0`.

Output of `composer why-not`:

```
$ composer why-not phpunit/phpunit:^7
acquia/blt-require-dev  10.0.0-beta1  requires          phpunit/phpunit (^4.8|^6.5)
phpunit/phpunit         7.0.0         requires          phpunit/php-code-coverage (^6.0)
acquia/blt-project      dev-master    does not require  phpunit/php-code-coverage (but 5.3.2 is installed)
phpunit/phpunit         7.0.0         requires          phpunit/php-timer (^2.0)
acquia/blt-project      dev-master    does not require  phpunit/php-timer (but 1.0.9 is installed)
phpunit/phpunit         7.0.0         requires          phpunit/phpunit-mock-objects (^6.0)
acquia/blt-project      dev-master    does not require  phpunit/phpunit-mock-objects (but 5.0.10 is installed)
phpunit/phpunit         7.0.0         requires          sebastian/diff (^3.0)
acquia/blt-project      dev-master    does not require  sebastian/diff (but 2.0.1 is installed)
```
Attempt to require phpunit 7:
```
$ composer require phpunit/phpunit:^7
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update

Installation failed, reverting ./composer.json to its original content.


  [Composer\DependencyResolver\SolverProblemsException]
  Problem 1
      - The requested package phpunit/phpunit ^7 exists as phpunit/phpunit[6.5.14] but these are rejected by your con
  straint.
```

Attempt to `require --no-update` while nuking vendor and composer.lock ultimately fails with:
```
  [Composer\DependencyResolver\SolverProblemsException]
  Problem 1
      - The requested package phpunit/phpunit ^7 exists as phpunit/phpunit[6.5.14] but these are rejected by your con
  straint.
```

I also tried running the update commands found [here](https://www.drupal.org/project/drupal/issues/3099061#comment-13380529) but nothing was updated, presumably due to the version constraints.

**Comment by mikemadison13** [comment]
I'm currently using `"drupal/core": "^8.7.0",` to run Drupal core 8.8.1 so it will do a major version update, but to your point there may be other dependencies that are breaking so it isn't happening. i do wonder if you update to BLT 11 first if you'll have an easier time (looking at it though nothing jumps out at me as being noticeably different). I think you'll need to nuke out the vendor folder and/or composer.lock to require 7, as I mentioned above, you'll likely need to redraw a ton of dependencies.

**Comment by scottreese** [comment]
Ah, but `8.7.0` to `8.8.1` is _not_ a major version update. That is a minor version update according to [semantic versioning](https://semver.org/) which is the standard composer attempts to adhere to. However, updating from `6.5.0` to `7.0.0` _is_ a major version update. 😄 

I don't think it will be possible to update to phpunit 7 in this project without updating the constraints for `acquia/blt-require-dev` to something more like `^4.8|^6.5|^7`.

**Comment by mikemadison13** [comment]
ah, that could be it.

**Comment by danepowell** [comment]
I think in the 10.x branch, we should just remove the phpunit requirement entirely from blt-require-dev. blt-require-dev 10.x already depends on webflo/drupal-core-require-dev, which will pull in the correct phpunit version.

In the 11.x branch, maybe we leave the phpunit requirement but remove the version constraint. PHPUnit only exists as a dependency in blt-require-dev 11.x to support end-user PHPUnit testing, it's not meant to support Drupal core tests. Users should install drupal/core-dev to support core testing, which will pull a more constrained version of PHPUnit only if necessary.

**Comment by danepowell** [comment]
As a bonus, this would also solve the phpunit-mock-objects deprecation warning: https://github.com/acquia/blt/issues/3405
