### ISSUE TITLE
DT-1135: Document SSH setup for sync command on Pipelines

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#3970]
**I want to...**
Enable "db sync" on pipelines build to test that existing content still works with new code.

**It's not working because...**
I am getting an SSH permission denied (public key) error when the command tries to do a `$ drush sql-sync` command. 

**Detailed error output**
> If a BLT command is failing, run it again with the `-vvv` argument and post the full output here.

This is difficult to do b/c it's only Pipelines. This works locally b/c it's clearly a KEY issue.

I am using the default `acquia-pipelines.yml` file, with the following uncommented:
https://github.com/acquia/blt/blob/c689efde97895b7b8f6b43d552440e2a6fa7f6d4/scripts/pipelines/acquia-pipelines.yml#L27-L31

It seems like the PIPELINES container (?) does not have permission to call my drush alias. So the command failing is: `$ drush sql-sync @myapp.dev @self `.
How does PIPELINES connect to the Acquia environments via drush SSH to get the database?

**System information**
* Operating system type: Pipelines?
* Operating system version: Pipelines?
* BLT version: 10.7.0

**Comment by dpagini** [comment]
So I _sort of_ figured this out... I had to encrypt a key and add it to the bottom of the `acquia-pipelines.yml` file via the `ssh-keys` property. I saw a comment about this in the PR that added the "blt sync" comment in the pipelines file, but other than that, it was actually pretty hard to figure out what was supposed to be done. May be an opportunity for better documentation here?

**Comment by danepowell** [comment]
Yeah we should probably self-document that code snippet better with instructions for setting up SSH perms, and link to external documentation if necessary.

Pipelines containers don't have SSH access to other Cloud environments out of the box for security reasons, since Pipelines can run untrusted code (from PRs). This is something we'd want to call out pretty clear in any documentation.
