### ISSUE TITLE
DT-1151: Make multisite database include statement configurable.

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#3973]
**Is your feature request related to a problem? Please describe.**
Its frustrating that blt.settings.php includes the multisite database settings based on the `$site_dir` variable:
https://github.com/acquia/blt/blob/ae080e597f305137a0a6ad9b53e7853f14eaba68/settings/blt.settings.php#L117-L138

A site directory is not always a valid Acquia Cloud database name, nor is that always desired.

**Describe the solution you'd like**
It would be nice if the database include magic in blt.settings.php could be disconnected from the `$site_dir` variable. Using the `drupal.db.database` value set in the BLT configuration seems logical to me but maybe accessing BLT config is not possible that early in the bootstrap process.

**Describe alternatives you've considered**
Manually adding the database include before the blt.settings.php file like the docs state works fine but is a little tedious for a large number of multisites.

**Additional context**
We have tried some global.settings.php code which works to include database statements dynamically but I'm not sure that is advised given it is one of the last settings files included in the chain.

**Comment by danepowell** [comment]
You are correct that BLT expects that each site directory has an identically-named database in Cloud. Help me understand, what's a scenario where you'd have a site directory that's deployed to Acquia Cloud but not linked to an Acquia Cloud database?

Also, as near as I can tell, it shouldn't cause any harm if a corresponding database doesn't exist. BLT only tries to require the settings file if it actually exists. Are you getting some sort of error?

**Comment by richardbporter** [comment]
It is fairly common to use the production URI host as the name of a multisite directory. For example, `docroot/sites/foo.bar.com/`. Doing so allows additional subdomains to route automatically without sites.php aliases, like `dev.foo.bar.com` or `test.foo.bar.com`. I also think its a bit more readable than `foobarcom` or something similar.

As far as I know however, Acquia Cloud does not allow periods in a database name, only underscores. This means `blt.settings.php` will attempt to include a `foo.bar.com-settings.inc` file which does not exist. This is not a problem necessarily but it would be nice if BLT could allow for the use of a different value for determining the name of the database include file instead of the `$site_dir` variable. Otherwise, multisites have to manually add the database include as outlined in the docs: https://docs.acquia.com/blt/tech-architect/multisite/#acquia-cloud-configuration  Again, not a problem but it would be nice to leverage the database include already built into `blt.settings.php`.

Hopefully this makes more sense. Let me know otherwise. Thanks.

**Comment by danepowell** [comment]
We are removing this from the roadmap for now. It may still be a valid issue but we need to close it to keep the queue manageable. Folks can submit product feedback via support tickets if they'd like to see it reprioritized, thanks.

**Comment by dpagini** [comment]
Sorry I'm seeing this after it's closed, but I've faced this problem too. 

As a SHORT TERM fix, could we `strreplace` dots to underscores in the `$site_dir` variable before trying to load that Acquia database settings file? That would give users at least a feasible workaround.

**Comment by danepowell** [comment]
@dpagini fixing the more limited issue of cloud dbs not supporting periods makes sense. Does this work? https://github.com/acquia/blt/pull/4135
