### ISSUE TITLE
Recipes for acquia drush aliases is missing in BLT 11.x.x

### ISSUE THREAD

**Issue by RoyaRRateshtari** [acquia/blt#3974]
I created my first project with BLT 10.x.x and I was able to run the 
`blt recipes:aliases:init:acquia` or `blt raia` to generates new acquia site aliases for Drush. It would save a **site.yml** file under **blt/drush/sites**

```
[project]
    |
   [ blt]
        |
        [drush]
               |
            [sites]
                    |
                project.site.yml

```
the command `blt list` on my terminal shows the blt recipe is available. See attached photo for more info.

![blt-10](https://user-images.githubusercontent.com/42613543/71868257-68a77f00-30db-11ea-8eb9-cb3da119753d.jpg)

I created another project a few days ago with BLT 11.x.x. Suprisingly, running `blt recipes:aliases:init:acquia` errored out with the message the recipe was not available.

I ran the 'blt list' command on my shell and checked the available recipes. I noticed the d**rush aliases recipe** was missing. I can not generate the drush aliases file for my new project.

See attached photo for more info.

![blt-11](https://user-images.githubusercontent.com/42613543/71868486-4b26e500-30dc-11ea-9ded-0e24efff57fd.jpg)

**Describe the solution you'd like**
Is it possible to add the recipe for acquia drush aliases back to the BLT 11.x.x?

Is there any reason why it is missing?

How can i generate the site drush aliases?

**Comment by richardbporter** [comment]
I believe it was removed in favor of using ADS as outlined in the upgrade docs: https://support.acquia.com/hc/en-us/articles/360039081454-Upgrading-from-BLT-10-x-to-11-x

The upgrade docs are linked from the initial 11.x release: https://github.com/acquia/blt/releases/tag/11.0.1

**Comment by RoyaRRateshtari** [comment]
Thanks Richard !
 I still believe the "drush aliases" great to have! Anyways, I will close the issue. :(
