### ISSUE TITLE
CI environment BLT commands kill process waiting for response with BLT 11

### ISSUE THREAD

**Issue by shelane** [acquia/blt#3976]
**Describe the bug**
Running deployments in a CI (Jenkins) environment even with the --no-interaction flag still gets the question:

We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) 

The process is then aborted when there is no response.

This started happening since upgrading BLT to 11. There is a response requested when there was none before and the --no-interaction flag is ignored for this question.

**To Reproduce**
Running deployments in a CI (Jenkins) environment even with the --no-interaction flag. This was the BLT command running in Jenkins:

sh ./vendor/bin/blt artifact:deploy --commit-msg 'Creating release 1.0.11' --tag 8-1.0.11

**Expected behavior**
As with previous versions of BLT, I expect the deployment to occur.

**Detailed error output**
[Pipeline] sh
+ ./vendor/bin/blt artifact:deploy --commit-msg 'Creating release 1.0.11' --tag 8-1.0.11
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) 
            
  Aborted.  

**System information**
* BLT version: 11.0.1

**Comment by danepowell** [comment]
I'm a little confused. You said this occurred with the `--no-interaction` flag, but the command you posted does not contain that flag.

If I run the exact command you posted (without the flag). If I add the `--no-interaction` flag, the prompt does not appear. These are both expected behavior.

**Comment by shelane** [comment]
Sorry. This is the actual line of code in the Jenkins script:
`sh "./vendor/bin/blt artifact:deploy --no-interaction --commit-msg \"Creating release ${params.releaseVersion}\" --tag \"8-${params.releaseVersion}\""`

When I copy from the console output by Jenkins, it said:
```
[Pipeline] sh
+ ./vendor/bin/blt artifact:deploy --commit-msg 'Creating release 1.0.11' --tag 8-1.0.11
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) 
            
  Aborted.  
            

artifact:deploy [--branch BRANCH] [--tag TAG] [--commit-msg COMMIT-MSG] [--ignore-dirty] [--dry-run] [--ignore-platform-reqs] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-D|--define DEFINE] [--environment ENVIRONMENT] [--site SITE] [--] <command>
```

**Comment by danepowell** [comment]
The console output does not include the `--no-interaction` parameter, any idea why that might be? It seems like either Jenkins is not running the build script that you think it is, or it's dropping that parameter for some reason.

**Comment by andrewchapman-lpg** [comment]
I had the same issue with Travis but found a workaround by disabling telemetry with:

    blt blt:telemetry:disable --no-interaction

**Comment by shelane** [comment]
@danepowell I have no idea why that would be the case. The script worked fine prior to the update to BLT 11. There are only two places where the artifact:deploy command is used. The other place is on our dev build and no "tags" are used in that case. The output of the console commands prior to this issue shows that it happens exactly where I'm expecting.

@andrewchapman-lpg Thanks! I have added that to our Jenkins file prior to my command and I will give that a try on the next run.

**Comment by danepowell** [comment]
@andrewchapman-lpg are you saying that you also have a Travis CI job that's stripping or ignore the `--no-interaction` parameter? If so can you provide a copy of your `.travis.yml`?

It's just hard to imagine how this could be caused by BLT when the output of Jenkins itself shows that it's not being passed the `--no-interaction` flag. In that case, BLT is behaving exactly as expected. The reason this only appeared in BLT 11 is because that command just started prompting for interactive input, but I suspect if you check the logs from BLT 10 you will see that Jenkins wasn't passing the `--no-interaction` flag there either.

**Comment by shelane** [comment]
That is working. Thanks!

**Comment by RakeshJamesAccess** [comment]
Well. I am still seeing this 

```
if ([ $TRAVIS_PULL_REQUEST == "false" ])
then
  echo "No need to run validations."
else
  blt validate:all
  ${BLT_DIR}/scripts/blt/ci/tick-tock.sh blt setup --define drush.alias='${drush.aliases.ci}' --define environment=ci --no-interaction --yes -v
  blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --define environment=ci --no-interaction --yes -v -D behat.tags='@smoke'
fi
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.
 Do you want to help us make this tool even better? (y/n) 
```

**Comment by RakeshJamesAccess** [comment]
Thanks, everyone, 

I have added the `blt blt:telemetry:disable --no-interaction`
inside the `run_tests` file

`#!/usr/bin/env bash

set -ev

if ([ $TRAVIS_PULL_REQUEST == "false" ])
then
  echo "No need to run validations."
else
  blt blt:telemetry:disable --no-interaction
  blt validate:all
  ${BLT_DIR}/scripts/blt/ci/tick-tock.sh blt setup --define drush.alias='${drush.aliases.ci}' --define environment=ci --no-interaction --yes -v
  blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --define environment=ci --yes -v -D behat.tags='@smoke'
fi

set +v`

or even you can add in your `.travis.yml ` under  `script:`
`script:
  - blt blt:telemetry:disable --no-interaction
  # We don't install Drupal or run Behat for deployment builds.
  - source ${BUILD_DIR}/scripts/travis/run_tests`
