### ISSUE TITLE
DT-1150: Better location for individual site secrets.settings.php file for ACSF

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#3983]
BLT check if a secrets.settings.php file exists for all sites and for individual sites, and loads it if it's found. For individual sites, it [checks for the file in the $site_dir folder](https://github.com/acquia/blt/blob/11.1.0/settings/blt.settings.php#L137). For ACSF sites, the $site_dir variable will look like "g/files/[sitename]", and for ACE multisites it will look like "[sitename]".

I think for ACSF, the "g/files" should be stripped away. It's quite strange to reproduce that folder structure in the files dir for secret settings files.

**Comment by danepowell** [comment]
I think you are right, although just to be clear, the "files" directory we're talking about here isn't the public files directory, but rather `/mnt/files`, which is not publicly accessible.

Anyway, I think that makes sense. It's probably best to fix this by setting `$site_dir` in blt.settings.php. The only thing I'm not sure about is that we already calculate `$_acsf_site_name` by examining the URL and matching it to a site directory. I'm not sure what the overlap would be between that and stripping `g/files` as you propose. We probably want to standardize on one approach or the other.

**Comment by lpeabody** [comment]
There are BC considerations here also, for those already just using the g/files path included with the site name variable *cough* me *cough*. But yes at the time I wish this is what I had. Would this just be a release note in the next major version?

**Comment by danepowell** [comment]
Yeah I think it'd have to go into the next major release as a breaking change.

**Comment by dpagini** [comment]
Found this issue while troubleshooting my own ACSF settings stuff...
I definitely would agree with stripping `g/files` off that `$site_dir` path, but if what @danepowell is saying that there's already logic that matches the domain to a `sites/*` directory, I personally think that would be even better.
Just to be clear, so we're saying `$sites_dir == 'abc12345'` and `$_acsf_site_name == 'example.com'`?

The issue that helped me stumble upon this issue...  I'm not sure this can be addressed, but it was definitely a cause of some frustration.

On ACE, we load the Acquia settings (which includes the database connection array) right before the secrets, so I can use `secrets.settings.php` to set a second `$databases` array key, for a migration, for example.
On ACSF, the Acquia settings are loaded via some ACSF magic (_I think?_). Therefore, you can use the secrets file to load all the config and settings you need, but you cant do anything with that databases array. You have to use that post-settings ACSF hook for that. It's just an odd inconsistency, and I'm not sure how it _could_ be addressed, but thought I would drop a comment on my findings in case anyone has any ideas...

**Comment by bkosborne** [comment]
Yea, so by default when using BLT + ACSF, *all* of the BLT config files are loaded before the Acquia config files. This is because BLT installs a pre-settings-php factory hook that loads the BLT config file. So the secrets.settings.php file would not be able to add to or overwrite anything that Acquia sets in its config files.

You could get around that by instead having BLT load its config file via a post-settings-php factory hook, which would then load all the BLT (and secrets file) *after* the acquia configs.

**Comment by danepowell** [comment]
I can't recall off the top of my head the specifics, but I think there was a good reason we use pre-settings-php instead of post-settings-php. If you change that, you may want to test quite carefully for regressions.
