### ISSUE TITLE
DT-1161: Acquia Pipelines deployment failure

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#3992]
**Describe the bug**
After upgrading to `11.1.1` it seems that acquia pipelines is unable to deploy branch.
`Failed while running the build script; no build progress detected in 600 seconds.`

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Upgrade to `11.1.1`
2. Edit branch
3. Push changes
4. Wait for acquia to start job
5. See error.

**Expected behavior**
Change should be able to be deploy to a new branch in Acquia cloud.

**Detailed error output**
`Failed while running the build script; no build progress detected in 600 seconds.`

**Additional context**
I was able to fix the issue by rolling back to `11.1.0`

**Comment by danepowell** [comment]
I can reproduce this. It doesn't seem to be a problem with BLT per se since all of the BLT scripts run to completion, and yet Pipelines seems to be waiting on something.

**Comment by jedgar1mx** [comment]
Yes, everything runs successfully. However, it just waits until it times out.

**Comment by dpagini** [comment]
Thinking this is maybe related to #3971. We've seen this as well.

**Comment by danepowell** [comment]
My initial hunch is also that #3971 is a contributing factor. I'm looking into it. It should be fairly easy to confirm by reverting that change via a patch on 11.1.1. My guess is that BLT is killing some sort of Pipelines monitoring process, preventing it from recognizing that the script has finished.

**Comment by danepowell** [comment]
I've published a hotfix release 11.1.2 that reverts #3971 and I've confirmed fixes the issue: https://github.com/acquia/blt/releases/tag/11.1.2

**Comment by danepowell** [comment]
We found the cause of the regression: headless chrome was no longer getting killed, and was keeping the Pipelines container alive until it timed out.
