### ISSUE TITLE
DT-1165: PHP 7.4 incompatibility

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#3998]
Running any BLT commands under PHP 7.4 will result in an error. This is due to an upstream incompatibility: https://github.com/consolidation/Robo/issues/922

**Comment by mikemadison13** [comment]
I've also seen issues in CI with PHP 7.4 like:

`Trying to access array offset on value of type null DocParser.php:969`

`Trying to access array offset on value of type null PathPluginBase.php:104`
