### ISSUE TITLE
DT-1193: Use getenv instead of $_ENV

### ISSUE THREAD

**Issue by jhedstrom** [acquia/blt#4005]
The `$_ENV` variable values are dependent on how `variables_order` is [configured](https://www.php.net/manual/en/ini.core.php#ini.variables-order) in php. If the `E` option isn't present, normal environment variables don't appear. The `getenv` function always returns environment variables that are present, so switching to that throughout would be more stable. 

I encountered this issue with the code in `EnvironmentDetector::isCiEnv()` but a search of the codebase reveals many usages of `$_ENV`.

**Comment by danepowell** [comment]
Thanks, I agree. We should have an automated test to prevent future usage of `$_ENV` as well: https://github.com/acquia/coding-standards-php/issues/9

My only concern is that getenv/putenv use entirely different data stores from `$_ENV`. While we can replace our internal usages, I fear that this might break integrations with any external code that sets or reads from `$_ENV`.

**Comment by danepowell** [comment]
Oh man, yeah this definitely breaks things, including all of our own ORCA tests :smile: 

Apparently `variables_order` has not been set in many CI environments, and until now we unknowingly worked around it by treating them as local. That will break things when we start properly recognizing them as CI. I think we should still make this change, but drop a big warning in the release notes.

**Comment by danepowell** [comment]
We've asked for an automated sniff for this here: https://github.com/slevomat/coding-standard/issues/911
