### ISSUE TITLE
Autoloading RoboFile.php includes 35 files

### ISSUE THREAD

**Issue by mpodorov** [acquia/blt#4006]
RoboFile.php has been added to auto-loading list in [#3694], but actually 35 files are loaded (mostly from consolidation/robo project). They are not required for a site operations, so it's better not to include them for every HTTP request. Is there any other solution for [#3638]?

**Comment by danepowell** [comment]
The BLT / Robo container may be invoked during page requests (such as to get BLT configuration in settings files), in which case I think Robo needs to be autoloaded. That will be resolved in #3823

In the meantime, I agree it's not ideal to load more files than strictly necessary, but is this having any practical performance impact that you can measure?
