### ISSUE TITLE
Artifact build executes composer with unideal parameters

### ISSUE THREAD

**Issue by grahl** [acquia/blt#4007]
**Bug description**
Currently the build executes `composer install --no-dev --no-interaction --optimize-autoloader`. This works fine in most cases but has a noteworthy shortcoming: In some cases the source is fetched even though a tagged version is available (we saw this with an RC) and thus versioning information is not available in the info.yml.

This can break Drupal's dependency checks.

Example:
```
 [error]  CRM Core Activity requires this module and version. Currently using Name Field version  (Currently using Unresolved dependency Name Field (Version &gt;=8.x-1.0-rc2 required)) 
```

**System information**
* BLT version: 11

The PR adds the `--prefer-dist` argument to avoid this issue.

**Comment by danepowell** [comment]
I appreciate that there's _some_ undesirable behavior here, but I'm not convinced it's BLT's problem to solve. It seems like a bug in Composer if it's downloading Git versions when stable packages are available. As to the specific suggestion of using `--prefer-dist` as a solution, see my comments in the PR.

**Comment by grahl** [comment]
Thank you for the feedback and pointing me towards that issue, that's really unfortunate behavior there with the commit refs.
