### ISSUE TITLE
"Do you want to help us make this tool even better? (y/n) " makes builds fail.

### ISSUE THREAD

**Issue by sodacrackers** [acquia/blt#4019]
**Describe the bug**
We recently upgraded from BLT 9 to 11.2.0.  

Our travis-ci builds now seem to die with the message `Do you want to help us make this tool even better? (y/n) ` 

Is there a way this message be disabled, or for a wait timeout be added to the BLT source?  

```blt frontend --site=default
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

**System information**
* Operating system type: [BLT default Travis-CI dist: xenial]
* BLT version:  [BLT 11.2.0]

**Additional context**

**Comment by sodacrackers** [comment]
Related: https://github.com/acquia/blt/issues/3922

**Comment by sodacrackers** [comment]
Related: https://github.com/acquia/blt/issues/3976

**Comment by sodacrackers** [comment]
Resolved by adding 
```
vendor/bin/blt blt:telemetry:disable --no-interaction
```
to `blt/custom-scripts/travis/setup_project`

Thanks

**Comment by mayelaatf** [comment]
This is still an issue....
Operating system type: [BLT default Travis-CI dist: xenial]
BLT 12.7.0.0

#sodacrackers , I tried your workaround but it does not work with this BLT version

Any ideas how to fix this?

**Comment by cballenar** [comment]
@mayelaatf were you able to sort this out?
@sodacrackers, do you have additional information on the change performed? I couldn't figure out how to implement this from the [documentation](https://docs.acquia.com/blt/extending-blt/). I tried adding as described with no luck. The custom-script directory doesn't seem to have been picked up by travis at all. Is this something previous to BLT 12 maybe?

What seems even weirder to me is that we can see BLT calling the validate commands with the --no-interaction flag. See code below which includes a few extra lines.

```
$ source ${BLT_DIR}/scripts/travis/setup_project
set +ev

$ source ${BLT_DIR}/scripts/travis/run_tests
blt validate --no-interaction || { set +v && return 1; }

> validate:twig
Validating twig syntax for all custom modules and themes...
Iterating over fileset files.twig...
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Do you want to help us make this tool even better? (y/n) 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by mayelaatf** [comment]
@cballenar  I added to the scripts/travis/run_tests  this:
`blt blt:telemetry:disable --no-interaction`

That worked for me

**Comment by cballenar** [comment]
Thanks for feebdack @mayelaatf ! I was about to write an update. I ended up adding the command directly to my `.travis.yml` file as this it didn't have seem to make any references to the scripts folder in my `./blt` directory. I see it's accomplishing the same but I'll probably end up moving it for cleanliness.

Have a good one!
