### ISSUE TITLE
Generate aliases using Acquia developer studio

### ISSUE THREAD

**Issue by manerkargaurav** [acquia/blt#4022]
I would like to know how to generate blt aliases using Acquia developer studio. What is the correct command  that works same as "blt aliases" ?

I have tried running "ads run drush  aliases:sync" command, but it doesn't generate aliases properly.
I want to get same output as "blt aliases" command in BLT 10.7.2

**System information**
* Operating system type:  Mac
* Operating system version: 10.14.6
* BLT version: 11.2.0

**Comment by mpodorov** [comment]
composer require lcatlett/blt-drush-alias
can be the proper solution

**Comment by danepowell** [comment]
ADS will automatically create the necessary aliases any time you run a command that requires them, such as `ads init`. There is not a dedicated command to just create aliases though. I've passed this feedback on to the ADS team.

As others have mentioned another solution would be to use a third-party plugin to generate aliases.

**Comment by danepowell** [comment]
Sorry I should have mentioned that `ads run drush aliases:sync` should work. Can you be more specific about how that's not generating aliases properly?

**Comment by Elaine-dev** [comment]
> composer require lcatlett/blt-drush-alias
> can be the proper solution

Does anyone know if this plugin work with free accounts? It didn't write the alias files for me.
