### ISSUE TITLE
Documentation link update

### ISSUE THREAD

**Issue by riteshgurung** [acquia/blt#4041]
**Describe the bug**
Acquia pipeline link under features in README.md is giving error 
`The website that you're trying to reach is having technical difficulties and is currently unavailable.`

**To Reproduce**
1. Open the repository link in browser https://github.com/acquia/blt
2. Scroll to Features section
3. Click on Acquia Pipelines link [https://dev.acquia.com/request-invite-acquia-pipelines]

**Expected behavior**
A request form for the pipeline.

**System information**
* Operating system type: [Mac Osx Mojave]
* Operating system version: [Mojave]
* BLT version: [12.x branch]

**Comment by danepowell** [comment]
Thanks for the catch, I've updated the README.
