### ISSUE TITLE
A config value for deployment docroot

### ISSUE THREAD

**Issue by b-sharpe** [acquia/blt#4042]
Creating a new issue to get eyes on this as since the original PR #3975 was merged it can no longer be open.

See https://github.com/acquia/blt/pull/3975#issuecomment-592601225

**SUMMARY**
Due to some hosts not using `docroot` as their web root, a way to deploy to an alternate folder is needed. PR #3975 was merged, and then reverted due to CLI restrictions, but this needs a way forward.

**Comment by danepowell** [comment]
@b-sharpe #3975 was only reverted in the 10.x branch because it turned out to be a breaking change. It should still be present in the later (11.x/12.x) branches. What additional action is required here?

**Comment by b-sharpe** [comment]
@danepowell Oh wow, I'm sorry, I assumed it was reverted for all due to the same behaviour and the majority of our project's are still on 10. We will continue to patch 10 and upgrade where possible. Thank you for the response!
