### ISSUE TITLE
The drupal:install command fails on Acquia Cloud.

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#4054]
Somewhat related to #2067, the drupal:install command throws an exception when it tries to set permissions on the site and files directory on Acquia Cloud. I feel like a warning would be more appropriate here, especially considering the Drush tasks could succeed and the site is "installed" anyway. I guess it makes sense from a CI perspective but I don't know if AC changes permissions when code is deployed.

Could EnvironmentDetector be leveraged to log a warning if being run on an AC environment?
https://github.com/acquia/blt/blob/81ca1cade4eb4b5c5ab8a36a6c668c5d128bee9e/src/Robo/Commands/Drupal/InstallCommand.php#L75-L77

**Comment by danepowell** [comment]
Downgrading to a warning seems fair, would you mind testing #4071?

Note that this error, while alarming, should be innocuous since it occurs as the final step in the command. The rest of the install should have completed fine.

**Comment by richardbporter** [comment]
That works. However, is that a concern for CI if permission cannot be set and the build does not fail?

**Comment by danepowell** [comment]
This is primarily a helper function to prevent permissions-related issues later in the build process. If it fails, the process might succeed anyway or it might fail and then you have a warning to point you in the right direction. But I can't imagine a scenario where failing to set permissions in CI would cause an unexpected failure _outside_ of CI, can you?

**Comment by richardbporter** [comment]
Ah, gotcha. I thought it was to remove write access from site directories, settings files, etc. in the build artifact. 

👍 to #4071.
