### ISSUE TITLE
Setting up working multisite on Travis CI built environment 

### ISSUE THREAD

**Issue by sodacrackers** [acquia/blt#4055]
We've been using Travis CI for continuous integration for more than a year. It successfully creates a travis environment, builds the frontend assets, and pushes the build product to our Acquia git remote.  

Where can I find details on having Travis CI create a working drupal multisite, with current databases loaded into the current virtual?  Our Travis build is `dist: xenial`.  

We'd like to test the config-import and then run our end-to-end web tests (using our NightWatch, nodejs ChromeDriver) both of which require a working URL.  

Are others using Apache configurations to create drupal sites on Travis? As an alternative, are others pushing the build product to a sandbox environment for testing?

**Comment by danepowell** [comment]
BLT has no built-in ability to run multiple sites simultaneously (with multiple databases) in a CI environment such as Travis CI. To make this work, you'd probably need to copy BLT's Travis scripts into your own project and modify them to create the necessary databases, and populate them as part of the install step, and possibly modify the test step as well to run against multiple sites.

I'll leave this open for a bit to collect ideas from the community. If you get this working maybe share it in a blog post or drop a comment here.
