### ISSUE TITLE
drupal/core-dev Not Properly Required

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4062]
**Describe the bug**
BLT has a number of dependencies in require-dev. In this case, I care mostly about the `drupal/core-dev` package, but this will apply to others as well.

While attempting to setup PHPUnit testing, a number of us have hit issues with the `symfony/phpunit-bridge` package and it missing. See https://github.com/acquia/blt/issues/3341 for historical context.

The interesting thing, is that `drupal/core-dev` requires this package (see https://github.com/drupal/core-dev/blob/8.8.x/composer.json#L27) and BLT requires core-dev (see https://github.com/acquia/blt/blob/11.x/composer.json#L55). HOWEVER in my local project, when I do a composer show on the package I get:

```
show drupal/core-dev
                                   
  [InvalidArgumentException]         
  Package drupal/core-dev not found  
```

So, I'm wondering if maybe BLT should be adding drupal/core-dev as a require-dev into the project level composer.json (and not just in BLT's require-dev). From my discussion with @wu-edward it seems like a dependency's require-dev doesn't get pulled into your project. And I think we'll want to make sore core-dev is part of the project level require-dev.

**Comment by wu-edward** [comment]
Reference on dependencies' require-dev not loaded:
https://stackoverflow.com/a/36347991

**Comment by mikemadison13** [comment]
I think this is all happening because the `acquia/blt-require-dev` doesn't have `drupal/core-dev`

I'm working on a PR.

**Comment by mikemadison13** [comment]
See https://github.com/acquia/blt-require-dev/pull/4

**Comment by mikemadison13** [comment]
This should likely be ported forward to BLT 12 as well.

**Comment by danepowell** [comment]
I think everything you've described is by design. BLT no longer relies on core dev dependencies anywhere (webflo/drupal-core-require-dev in D8, drupal/core-dev in D9) because they caused so many conflicts with other packages and when running composer updates (you can't update core without explicitly whitelisting the dev packages too).

Plus most people don't use them. You only need them if you are actually running core tests. If you use your own phpunit.xml they aren't necessary. The intention is that if you are running core tests, you should use the dedicated `tests:drupal:run` command which will warn you about these missing dependencies, as opposed to the more general `tests:phpunit:run` which expects you to know what dependencies are necessary for your own tests.

**Comment by mikemadison13** [comment]
i'm ok closing this as won't fix so that we've documented the problem, and allow people to add the package if they run into a similar issue on their own. we talked about this issue in the linked ticket, but never really talked about why it happened or how to fix it the proper way (just including that one library is a bit of a hack).

**Comment by gambry** [comment]
>BLT no longer relies on core dev dependencies anywhere (webflo/drupal-core-require-dev in D8, drupal/core-dev in D9) because they caused so many conflicts with other packages and when running composer updates.

[...]

>Plus most people don't use them

But what about adding this to `acquia/blt-require-dev`? I presume the devs requiring `acquia/blt-require-dev` expects to be able to run custom Drupal tests. And currently this is not possible.

> You only need them if you are actually running core tests.

No, that is for core, contrib and custom Drupal tests. It does ensure you have all the requirements to run them. One example for all is the missing `symfony/phpunit-bridge` which is required if you follow the Drupal.org instruction of how to run phpunit tests: "[Configure PHPUnit: PHPUnit stores configuration in the phpunit.xml file. Drupal comes with a sample version of this, core/phpunit.xml.dist, which you should copy to get started.](https://www.drupal.org/docs/8/testing/phpunit-in-drupal-8/running-phpunit-tests#configure-phpunit)".

Today is `symfony/phpunit-bridge`, tomorrow there may be more.

So would be good to find a way to either include `drupal/core-dev` on `acquia/blt-require-dev` or making sure its packages are included. In the meanwhile `acquia/blt-require-dev` can at least suggest  `symfony/phpunit-bridge` so developers know this is missing. Thanks!

**Comment by danepowell** [comment]
Check the BLT 12 upgrade guide linked from the release notes. blt-require-dev no longer exists. Testing functionality is encapsulated in plugins in BLT 12 and core-dev is a dependency of the relevant plugins.

**Comment by gambry** [comment]
Sorry @danepowell , I didn't check BLT12 yet. Just upgraded from 9 to 11, and will check 12 soon. Thanks.
