### ISSUE TITLE
No security warning for drupal/core < 8.8.4.

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#4065]
**I want to...**
See my build fail for Drupal security notifications.

**It's not working because...**
I noticed that today that none of my builds are failing after Drupal 8.8.4 came out yesterday with a security vulnerability.
I had a hard time tracking down the history, but I think this project used to use `drupal-composer/drupal-security-advisories` (which has been updated) to check for vulnerabilities. I think that's no longer the case. Is there another library used? I see there is a `FriendsOfPhp/security-advisories` service used via `sensiolabs/security-checker` but it appears that repo is pretty far out of date when it comes to Drupal.

Thoughts?

**Comment by mikemadison13** [comment]
I just downgraded the GovCon site locally to 8.8.2 and ran the security test, and I got a fail. So it's still working in BLT 11.2 as far as I can tell. Is it possible that you have a disable-target in blt.yml to turn off the security check?

```
blt  tests:security:check:updates
[warning] Your BLT schema is out of date.
 Would you like to run outstanding updates? (y/n) n
[Acquia\Blt\Robo\Tasks\DrushTask] Running /Users/mike.madison/git/d4g/Drupal-GovCon-2017/vendor/bin/drush @self pm:security --no-interaction --ansi in /Users/mike.madison/git/d4g/Drupal-GovCon-2017/docroot
 [warning] One or more of your dependencies has an outstanding security update.
 [notice] Try running: composer require drupal/core --update-with-dependencies
 [notice] If that fails due to a conflict then you must update one or more root dependencies.
+-------------+-------------------+
| Name        | Installed Version |
+-------------+-------------------+
| drupal/core | 8.8.2             |
+-------------+-------------------+
```

**Comment by dpagini** [comment]
Thanks for the reply @mikemadison13. I am actually seeing a fail now. It happened late this morning, but builds before that were not failing. I realized the fail is coming from running `$ drush pm:security` and not the packages I was pointing to in the original description. Not sure if maybe it took a while for that source to reflect the release...?
I'll close though b/c I do see it's still in place, and if it was just a time lag issue, that's probably OK and not something BLT can handle anyways.
