### ISSUE TITLE
DT-1427: 12.x branch update hooks (blt:update fails)

### ISSUE THREAD

**Issue by japerry** [acquia/blt#4069]
**Describe the bug**
Was the intention to break blt updates with PR #4057 ? rsyncTemplate is used in the update command and now breaks when you try to update blt.
You'll either need to refactor this or fix UpdateCommand to remove this code.

**To Reproduce**
Make sure you're updated to recent version of blt 12.x
1. Run `blt blt:update`
2. Error!

**Expected behavior**
1. Run `blt blt:update`
2. Profit!

**Detailed error output**
```
Fatal error: Uncaught Error: Call to undefined method Acquia\Blt\Robo\Commands\Blt\UpdateCommand::rsyncTemplate() in /var/www/vendor/acquia/blt/src/Robo/Commands/Blt/UpdateCommand.php:142
Stack trace:
#0 [internal function]: Acquia\Blt\Robo\Commands\Blt\UpdateCommand->update(Array)
#1 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#4 /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(302): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Ob in /var/www/vendor/acquia/blt/src/Robo/Commands/Blt/UpdateCommand.php on line 142
```

**Comment by danepowell** [comment]
No the intention was not to break updates :smile: 

However 12.x is still very much unstable, and (re)writing update hooks is still something that needs to be done.

**Comment by danepowell** [comment]
Actually the particular error you mentioned may have been fixed in this PR: https://github.com/acquia/blt/pull/4077

But we still need update hooks.

**Comment by danepowell** [comment]
Actually, not sure we need update hooks at the moment, but I have drafted an upgrade guide that covers all of the manual steps necessary for the upgrade. I don't think much of this can be automated since it involves modifications to composer.json: https://support.acquia.com/hc/en-us/articles/360045796154-Upgrading-from-BLT-11-to-BLT-12
