### ISSUE TITLE
DT-1356: Bump drupal-check version

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#4072]
https://github.com/mglaman/drupal-check/releases/tag/1.1.1

Need to test this extensively, especially on Pipelines, given all of the previous issues with this package.

**Comment by aweingarten** [comment]
Just want to bump the priority of this given that D9 is officially coming out in early June.  drupal-check/upgrade_status is the recommended tool from Acquia for D9 readiness and has even been funded by Acquia.  Getting BLT to be compatible with the recommended Acquia tool for D9 is kind of important.

http://hojtsy.hu/blog/2019-apr-29/estimate-your-sites-drupal-9-compatibility-easily-upgrade-status
https://twitter.com/Dries/status/1136968043979005953
https://dev.acquia.com/drupal9

**Comment by mikemadison13** [comment]
It looks like trying to add drupal/upgrade_status to a BLT 11.x project hits a lot of composer issues right now. Even though Upgrade Status itself doesn't require drupal-check, they do cross-contaminate a lot of the underlying phpstan dependencies. Obviously we need to make sure that BLT continues to be stable (so i dunno that we want to go back to ^ definitions for Drupal Check) but I do agree if we can unblock upgrade status ASAP that would be ideal!

```
composer require drupal/upgrade_status
Using version ^2.0 for drupal/upgrade_status
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install drupal/upgrade_status 2.0.0
    - Conclusion: don't install drupal/upgrade_status 2.0.0-beta1
    - Conclusion: don't install drupal/upgrade_status 2.0.0-alpha1
    - Conclusion: remove mglaman/phpstan-drupal 0.11.14
    - Installation request for drupal/upgrade_status ^2.0 -> satisfiable by drupal/upgrade_status[2.x-dev, 2.0.0, 2.0.0-beta1, 2.0.0-alpha1].
    - Conclusion: don't install mglaman/phpstan-drupal 0.11.14
    - drupal/upgrade_status 2.x-dev requires phpstan/phpstan-deprecation-rules ^0.12.0 -> satisfiable by phpstan/phpstan-deprecation-rules[0.12.0, 0.12.1, 0.12.2, 0.12.x-dev].
    - phpstan/phpstan-deprecation-rules 0.12.0 conflicts with mglaman/phpstan-drupal[0.11.14].
    - phpstan/phpstan-deprecation-rules 0.12.1 conflicts with mglaman/phpstan-drupal[0.11.14].
    - phpstan/phpstan-deprecation-rules 0.12.2 conflicts with mglaman/phpstan-drupal[0.11.14].
    - phpstan/phpstan-deprecation-rules 0.12.x-dev conflicts with mglaman/phpstan-drupal[0.11.14].
    - Installation request for mglaman/phpstan-drupal (locked at 0.11.14) -> satisfiable by mglaman/phpstan-drupal[0.11.14].
``

**Comment by danepowell** [comment]
Have you tried using [Composer version aliases](https://getcomposer.org/doc/articles/aliases.md#require-inline-alias)? That's the normal workaround when you want to use a different version of a dependency pinned by an upstream package.

Also just for context here... every time that we bump the drupal-check version (or allow users to upgrade it), it breaks in some major and unforeseen way (even during "patch" upgrades). While I appreciate the priority of this issue, that's why we can't rush into supporting the new version or allow users to update unconstrained, until we are sure it is stable. See https://github.com/acquia/blt/issues/3996

**Comment by danepowell** [comment]
Specifically, I'd recommend anyone thinking they are blocked by this to try something like:
`composer require mglaman/drupal-check:"1.1.1 as 1.0.14" --no-update && composer update`
