### ISSUE TITLE
Creating custom BLT command to invoke from command and command line

### ISSUE THREAD

**Issue by shelane** [acquia/blt#4081]
**I want to...**
I want to create a command that will both be called internally and called directly. It needs to take in --site just like the drupal:install commands so that it can execute for a specific site in a multisite environment. I'm not quite sure what the params for that look like as I don't see that in the actual drupal:install command. My custom command runs drush commands, so I need to make sure it's executed against the correct site, but it is also called from another custom command with:

```
$this->invokeCommand('custom:site:content', [
              '--site' => $multisite,
              '--environment' => $environment ?: $_ENV['environment'],
            ]);
```

And I should be able to call it in the command line like:
```
blt custom:site:content --site=mysite --environment=stage
```

Ideally I would have just had this has a hook on a post install. However, it requires that the config sync run first. But I can't make it a hook to a post sync because it should only run on a new installation (installing default content). 

**System information**
* Operating system type: RHEL 7
* BLT version: 11.3.0

**Comment by danepowell** [comment]
The site and environment contexts are globally managed by BLT, so you don't need to worry about passing them around during command invocations. If all you want to do is get configuration related to the current site, you don't need to do anything at all--BLT sets the site context automatically, i.e. commands will only get config for the currently active site by default.

"Currently active" in this case means whatever BLT detects the current DB to be (usually based on hostname), or whatever you pass via `--site`.

If you need to get the site name or change the active site within a command for some reason, you can do so with `$this->getConfigValue('site')` and `$this->switchSiteContext($multisite);`. You can grep the codebase for examples of this, I think the sync and settings commands both juggle site context like this.

**Comment by shelane** [comment]
Got this part working!
