### ISSUE TITLE
Update older versions of BLT to use newer version of typhonius/acquia-php-sdk-v2

### ISSUE THREAD

**Issue by typhonius** [acquia/blt#4093]
**Is your feature request related to a problem? Please describe.**
On https://docs.acquia.com/acquia-cloud/develop/api/auth/ we can see that HMAC authentication is going to be removed on April 15th. Newer versions of typhonius/acquia-php-sdk-v2 do not use this authentication and instead use the up-to-date auth.

**Describe the solution you'd like**
Update the reference to the underlying library so we use a more up-to-date version and get rid of HMAC.

**Describe alternatives you've considered**
Updating BLT is not a viable option for a us or a lot of other people as there are larger changes that can't be completed in good time.

**Additional context**
Found this as a result of Acquia emailing about using API v1.

**Comment by typhonius** [comment]
On looking through the BLT codebase, I can see that 10.x has updated to `1.1.1` which is the newest version of the 1.x branch and has the updated authentication.

Would the task be for individual sites to do an update to this directly using composer on a site-by-site basis?

**Comment by danepowell** [comment]
The version constraint in BLT 10.x is `"typhonius/acquia-php-sdk-v2": "^1.0.4",`, which should support 1.1.0, which has OAuth. Yes, individual projects just need to upgrade in their own time. Note that BLT 10 is only receiving security updates.

BLT 11 and 12 don't have any dependency on acquia-php-sdk-v2 at all.

I don't think any action is required for BLT here, if I'm mistaken please reopen.
