### ISSUE TITLE
Help aligning dependencies for 12.x

### ISSUE THREAD

**Issue by typhonius** [acquia/blt#4094]
**I want to...**
I want to ensure that the tools I am building align to BLT 12.x into the future. This will allow people who consume other command line tools can use them alongside BLT e.g. https://github.com/typhonius/acquia_cli/issues/59

Ultimately, my question is relating to the current bounds within the `composer.json` for `12.x` and whether they will change going into the future (or if dependencies are bound to major version). This will allow me to align tooling without running the risk of incompatible versions which is really common when dealing with Symfony/Robo apps.

**Comment by danepowell** [comment]
BLT 12 is trying to minimize external dependencies. What you currently see in composer.json should be roughly what goes into the stable release in a few months. If anything, we may continue to remove dependencies.

Is there something in particular you are concerned about?

**Comment by typhonius** [comment]
Thanks Dane, no concerns with any of this. I wanted to align my project bounds to BLT so myself and other users can always be compatible :)
