### ISSUE TITLE
Optionally start headless chrome before running PHPUnit tests

### ISSUE THREAD

**Issue by lpeabody** [acquia/blt#4112]
I use Drupal Test Traits for a few PHPUnit tests, and these require a web server to run. I was previously on BLT 9 and I was able to run these tests through headless chrome. Unfortunately with BLT 11+, it seems like starting a headless chrome server before running my PHPUnit tests is no longer supported.

Are there any reasons why support was dropped for this? Can support be added back? Am I just missing something with my configuration?

**Comment by danepowell** [comment]
See a previous discussion of this issue: https://github.com/acquia/blt/issues/3611

Is there a reason you are using the phpunit test command instead of Drupal core test framework (which would spin up the server)?

**Comment by lpeabody** [comment]
Hm, that might work. I do know that DTT uses it's own bootstrap, and not Drupal's. I'll have to look into this.

**Comment by danepowell** [comment]
I know the distinction between the PHPunit/Drupal core testing commands is a bit muddy. If you have suggestions on how to improve the architecture I'm definitely open to feedback. Just starting the test server seems like a bandaid (and there are many people that wouldn't want it for unit tests).
