### ISSUE TITLE
Details needed on where/how to execute commands in blt.yml

### ISSUE THREAD

**Issue by loopy3025** [acquia/blt#4118]
**I want to...**
Execute a custom command prior to Drupal installation.

**It's not working because...**
There is no documentation on where/how to do that in blt.yml. There seems to be very little documentation regarding blt.yml and the settings therein in general. See issue #2765

BLT is running fine on this site

**System information**
* Operating system type: Mac OSX
* Operating system version: 10.15.4
* BLT version: 10.7.2

**Comment by danepowell** [comment]
Have you seen https://docs.acquia.com/blt/extending-blt/ ?

As documented on that page, a few BLT commands that are frequently overridden have dedicated "hooks" that you can extend via configuration (typically in blt.yml). These include post-deploy-build, post-setup-build, and pre/post-config-import.

If those aren't sufficient, you can create a Robo command hook as documented on that page to run your own Robo command before, after, or in place of any BLT command.

**Comment by loopy3025** [comment]
Thanks, dane. That page does talk about overriding with hooks, but it does not list the available hooks or how to include any parameters. Configuring BLT still tends to be a whole lot of guesswork and investigating issue queues in lieu of comprehensive documentation.

**Comment by loopy3025** [comment]
On a similar note, there doesn't seem to be any central location that tells users where the settings from BLT Doctor come from and how to change them. 

For example, BLT Doctor reports a property called `%paths.%modules` is set to `sites/all/modules` and the property `%paths.%themes` is set to `sites/all/themes`. This is extremely wrong on our site and probably every Drupal 8 or 9 site. The modules are in `modules` relative to docroot and the themes are in `themes`. 

Where is BLT getting this setting from?

What affect could this be having on our site? 

How do I change it?

As usual, the [Extending BLT](https://docs.acquia.com/blt/extending-blt/) "documentation" is quite silent on the matter.

**Comment by mikemadison13** [comment]
@loopy3025 I usually refer to https://github.com/acquia/blt/blob/main/config/build.yml to chase down "anything" that BLT makes configurable. I'm not sure there's "great" documentation on this, but the build file essentially has a bunch of stuff that can be overridden in a blt.yml file.

Does this help? Sorry for the very slow reply!
