### ISSUE TITLE
BLT Validate Fails: 12.x Drupal Check issues

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4122]
**Describe the bug**
Running `blt validate` fails in 12.x with Drupal 9 Beta 2. It's unclear why this is failing for me, it's happening in Gitlab CI (but not locally). Specifically, I'm getting the error with drupal-check.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Create a BLT 12 project with Drupal 9 Beta 2
2. Run blt validate
 
**Expected behavior**
The command runs successfully.

**Detailed error output**
```
Running /builds/mikemadison13/d9canary/vendor/bin/drupal-check -d /builds/mikemadison13/d9canary/docroot/modules/custom in /builds/mikemadison13/d9canary
 Warning: require(/builds/mikemadison13/d9canary/docroot/core/tests/../../autoload.php): failed to open stream: No such file or directory in /builds/mikemadison13/d9canary/docroot/core/tests/bootstrap.php on line 127
 Fatal error: require(): Failed opening required '/builds/mikemadison13/d9canary/docroot/core/tests/../../autoload.php' (include_path='/builds/mikemadison13/d9canary/vendor/pear/archive_tar:/builds/mikemadison13/d9canary/vendor/pear/console_getopt:/builds/mikemadison13/d9canary/vendor/pear/pear-core-minimal/src:/builds/mikemadison13/d9canary/vendor/pear/pear_exception:.:/usr/local/lib/php') in /builds/mikemadison13/d9canary/docroot/core/tests/bootstrap.php on line 127
 [ExecStack]  Exit code 255  Time 0.462s
 [notice] Review Deprecation warnings and re-run.
 [error]  Drupal Check in docroot/modules/custom failed.
 For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
 The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
 [error]  Command `tests:deprecated:modules ` exited with code 1.
 For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
```

**System information**
* Operating system type: ADS Lando Image
* Operating system type: Ubuntu
* BLT version: 12.x-dev #

**Comment by danepowell** [comment]
I can't reproduce this locally. I'm not sure there's enough to go on here to troubleshoot. What happens when you run the drupal-check command on its own? BLT does nothing besides running that command (I don't think there's even any configuration around drupal-check calls), so if it fails that's a problem with drupal-check.

**Comment by mikemadison13** [comment]
i do think it's an issue with drupal-check, it just concerns me that it seems to require phpunit. maybe i should crosspost over there that it should include phpunit as a composer dependency?

**Comment by danepowell** [comment]
Since Drupal Check is being moved to a plugin we'd need to support that there anyway, but I added phpunit to the plugin.

**Comment by alejo-moreno** [comment]
@mikemadison13 Did you find a solution for this, I also experience this problem in Gitlab CI when buildind the artifact.

`Fatal error: require(): Failed opening required '/builds/my/vendor/composer/../../docroot/core/includes/bootstrap.inc' (include_path='/builds/my/vendor/pear/archive_tar:/builds/my/vendor/pear/console_getopt:/builds/my/vendor/pear/pear-core-minimal/src:/builds/my/vendor/pear/pear_exception:.:/usr/local/lib/php') in /builds/my/vendor/composer/autoload_real.php on `

**Comment by mikemadison13** [comment]
no @alejo-moreno once Dane removed Drupal Check it stopped happening for me. I haven't had any issues in blt 12 / d9 since.

**Comment by alejo-moreno** [comment]
@mikemadison13 might have something to do with the .gitlab-ci.yml file? I've done and search everything from updating the acquia/ads-local image, removing gitlab runners cache, revert php versions, but nothing works. Everything run normal in my local lando blt but the erros keeps the same in Gitab :(
