### ISSUE TITLE
Remove Gitlab CI Commands / Move to Plugin

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4132]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a plugin to support the necessary components for Gitlab Pipelines (see https://github.com/mikemadison13/blt-gitlab-pipelines). We should remove the command from BLT since what we have isn't a fully fledged example.

**Describe the solution you'd like**
Move all gitlab features into plugin.

**Open Questions**
- Should the BLT environment indicator auto detect gitlab or should this be subclassed in the plugin?
- Should the settings file be moved to the plugin?

**Comment by mikemadison13** [comment]
note that the plugin is still in development, so this should perhaps wait? or not, not sure how many folks are using this (since what's in BLT isn't fully fledged / functional).

**Comment by mikemadison13** [comment]
After some experimenting I did add an environment detector to pull in the settings file for gitlab. This is similar to the tugboat implementation as well.

**Comment by mikemadison13** [comment]
I'm having issues currently with the deploy step, so I haven't even touched the necessary ssh keys. But the other steps are working fine at this point.

**Comment by danepowell** [comment]
We should go ahead and merge it to the 12.x branch, that's still unstable at this point. But we should make sure it's working before an alpha release in early May.
