### ISSUE TITLE
MySQL 5.6 support within BLT 12.x

### ISSUE THREAD

**Issue by japerry** [acquia/blt#4141]
** Acquia (and some other platforms) require MySQL 5.6 **
Drupal 9 requires MySQL 5.7, but some platforms aren't quite ready for that change. 
Right now we have a package that simply adds the mysql 5.6 library to Drupal for those using the dev.acquia downloads or use D9 when installing directly to cloud.

Temporarily this shim works because Drupal 9.0 doesn't include any MySQL 5.7 specific calls. Therefore, each customer should have this package regardless of the MySQL version they're on. 

**Describe the solution you'd like**
BLT should include the drupal/mysql56 package and have some code around settings.php that allows it to function correctly locally.

Eventually when there is a version of BLT for Drupal 9.1, it will remove this package and the corresponding settings file.

**Comment by danepowell** [comment]
So I think there's two domains where this is relevant, in Cloud and locally. I think this is/should be managed in Cloud for all customers, not just BLT users.

BLT 12 is no longer in the business of managing local environments. Users needing development environments should use one of:
1. Remote IDEs
2. ADS CLI and Lando
3. The BLT Drupal VM community-supported plugin

This should be handled there.

However, I'll concede that we should add drupal/mysql56 to blt-project and the Acquia recommended-project template that may replace it shortly. I'll take care of that.
