### ISSUE TITLE
Drupal Coder 8.3.9 Breaks BLT Validate (test failure)

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4145]
**Describe the bug**
After running a `composer update` my drupal/coder package updated to version 8.3.9 and `blt validate` started failing. There is an open drupal/core issue for this, and it appears to be fixed for core 9.x and core 8.9.x but the patch does't apply to 8.8.x. I have personally pinned to `drupal/coder: 8.3.8` to work around this issue.

Note, this is not a true BLT bug but wanted to report it here since other folks will likely run into it.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Update drupal/coder to 8.3.9
2. Run blt validate 

**Expected behavior**
Coder works!

**Detailed error output**
```
blt validate
> tests:composer:validate
Validating composer.json and composer.lock...
[ExecStack] composer validate --no-check-all --ansi
[ExecStack] Running composer validate --no-check-all --ansi in /Users/mike.madison/git/d4g/drupal4gov.us
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
[ExecStack] Done in 0.866s
> tests:php:lint
Linting PHP files...
Iterating over fileset files.php.custom.modules...
> tests:phpcs:sniff:all
[ExecStack] '/Users/mike.madison/git/d4g/drupal4gov.us/vendor/bin/phpcs'
ERROR: Referenced sniff "Drupal" does not exist

Run "phpcs --help" for usage information

[ExecStack]  Exit code 3 
```

**Comment by mikemadison13** [comment]
@danepowell happy to just close this if you don't want to clutter up the issue queue. mostly wanted it there for the search history.

**Comment by greylabel** [comment]
Pointer for reference: https://www.drupal.org/project/coder/issues/3134853

**Comment by danepowell** [comment]
@mikemadison13 thanks for reporting, I don't think BLT can/should take any action here, but we should track this internally. A customer communication and/or knowledge base article might be appropriate.

**Comment by danepowell** [comment]
Turns out this breaks BLT's internal tests, so it is something we need to address, even if that just means an internal workaround and/or waiting for an upstream fix.

**Comment by greylabel** [comment]
As @mikemadison13 mentioned, pinning https://github.com/acquia/blt/blob/12.x/composer.json#L29 to `"drupal/coder": "^8.3.8",` unbreaks BLT.

**Comment by loopy3025** [comment]
I've created an issue on Drupal.org to help folks out searching for a solution. https://www.drupal.org/project/coder/issues/3135500

**Comment by jedgar1mx** [comment]
This fixed if for me.
`"conflict": {
        "drupal/coder": ">8.3.8"
    }`

**Comment by mikemadison13** [comment]
See a KB article here: https://support.acquia.com/hc/en-us/articles/360047559014-Drupal-Coder-8-3-9-Breaks-BLT-Validate

**Comment by justin-schroeder** [comment]
@mikemadison13 thanks for the KB article! I've lost hours on this pernicious little issue. On a small note is you mention manually setting the version to `5.3.8` instead of `8.3.8`.

**Comment by mikemadison13** [comment]
fixed that, thank you! sorry about that.

**Comment by danepowell** [comment]
It seems like end users have two options to work around this, either pin to Coder 8.3.8 (via a direct version constraint or the "conflict" configuration mentioned above), or [add the Coder repo as a custom repository](https://www.drupal.org/project/coder/issues/3134853#comment-13605604), which allows you to use Coder 8.3.9.

Given that it _is_ possible to use Coder 8.3.9 with a workaround, I don't see what BLT can do to help downstream users here. If we pin to Coder 8.3.8, we'll get just as many people complaining that they can't use 8.3.9. If anyone has ideas let me know.

In order to fix BLT tests, I'll probably add one of the above workarounds to BLT Project. This will help new users, but not existing ones.

**Comment by danepowell** [comment]
This was fixed upstream, so the workarounds should no longer be necessary.
