### ISSUE TITLE
Disable a single instance of deprecation notice.

### ISSUE THREAD

**Issue by justin-schroeder** [acquia/blt#4147]
**Is your feature request related to a problem? Please describe.**
I really appreciate all the BLT validation — especially as we near Drupal 9 its nice to keep tabs on custom modules to ensure they're up to snuff. One issue I've run into is custom modules that have contrib module dependencies that are still using deprecated interfaces in their event systems. For example the `redirect` module still uses `Drupal\Core\Path\AliasManagerInterface` instead of the newer `Drupal\path_alias\AliasManagerInterface` (this is literally what interfaces are intended to prevent!...I digress), so event subscribers are required to implement a deprecated interface. However (afaik) I have to entirely disable deprecation checking in order to pass validation.

**Describe the solution you'd like**
Ideally, we could disable a deprecation check in-context, much like eslint:

```php
...
/* disable-deprecation-warning */
use Symfony\Component\Routing\RequestContext;
/* enable-deprecation-warning */
...
```
This would allow us keep deprecation validation on, while also giving an easy-to-find way to located deprecated code.

**Describe alternatives you've considered**
Disabling all deprecation validation.

**Comment by danepowell** [comment]
Deprecation scanning is provided by [mglaman/drupal-check](https://github.com/mglaman/drupal-check), which is based on PHPStan.

PHPStan gives you [a few options for ignoring errors](https://phpstan.org/user-guide/ignoring-errors).

You can see an example of [how to use a config file for this in ORCA](https://github.com/acquia/orca/blob/v2.2.2/resources/phpstan.neon#L35).

This is not something that can be controlled or assisted by BLT, you will need to use the features of the upstream libraries.
