### ISSUE TITLE
BLT 11.4.1 Settings Overriding Config Directory PHP Setting to Default

### ISSUE THREAD

**Issue by dkowalec** [acquia/blt#4155]
**Describe the bug**
The latest version of BLT 11.4.1 doesn't work with Drupal 8.8.6 config directory setting because of blt settings.

# settings.php
`require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";`

**To Reproduce**
1. Install latest BLT 11.4.1
2. Add `$settings['config_sync_directory'] = '../config/sync'` anywhere above `blt.settings.php` require
3. `var_dump($settings['config_sync_directory']);`
4. See file path output is `../config/default`
5. Move step 2 below `blt.settings.php` as in code snippet below
6. Repeat step 3 and the correct directory output to see proper path which works w/ Acquia CI/CD & Local VM on `drush cex`

# Move config sync directory to settings.php below blt settings
`require DRUPAL_ROOT . "/../vendor/acquia/blt/settings/blt.settings.php";`

`
/*
BLT is hijacking the default sync directory
 // since this defined as default by Drupal core
 // @override required here or update of BLT version
 // then remove the below setting
*/
`
`$settings['config_sync_directory'] = '../config/sync';`

**Expected behavior**
`drush cex` should be using `config/sync` and not defaulting `config/default'

**Detailed error output**
blt doctor
> config-sync: `/var/www/site-name/config/default`

**Expected output**
blt doctor
> config-sync: `../config/sync`

**Additional context**
https://insight.acquia.com/support/tickets/1010011

**Comment by dkowalec** [comment]
Do note this will let the application find the ../config/sync directory but then overrides do not work and config split breaks

**Comment by dkowalec** [comment]
## You Help Would Be Appreciated for the Drupal 8.8.x Syntax Requirement
##### `$settings['config_sync_directory'] = '..config/sync'`

### WORK AROUND FIXES SYNC DIRECTORY BUT NOT CONFIG SPLIT OVERRIDES
**File**: `vendor/acquia/blt/settings/config.settings.php` (Line 32)
**Remove**: `$settings['config_sync_directory'] = $repo_root . "/config/default";`
**Add**: `$settings['config_sync_directory'] = $repo_root . "/config/sync";`

#### OR

**File**: `docroot/sites/default/settings.php` (Line must be after blt.settings require)
**Remove**: `#$settings['config_sync_directory'] = '../config/sync';`
**Add**: `$settings['config_sync_directory'] = '../config/sync';`

### REMAINING ISSUE
- [ ] Config Split for `envs/*` not detected when using BLT therefore `drush updb` fails without `hook` or `script` workaround as part of the pipeline build because overrides not working.
- [ ] Then, would I have to implement `drush config-split:export split` or `drush config-split:import split` to get the proper split?

### WHAT PURPOSE DOES THIS SERVE?
**File**: `blt.yml`
`
cm:
  strategy: config-split
  allow-overrides: true
  core:
    path: ../config
    key: sync
    dirs:
      sync:
        path: '${cm.core.path}/sync'
`

---

References:
> https://github.com/acquia/blt/issues/3940
> https://github.com/acquia/blt/blob/11.4.1/config/build.yml
> https://github.com/acquia/blt/blob/11.4.1/settings/config.settings.php
> https://docs.acquia.com/blt/extending-blt/
> https://www.drupal.org/node/3018145

**Comment by dkowalec** [comment]
@danepowell have you got a chance to look at my issue?

**Comment by danepowell** [comment]
As a prerequisite for using BLT, you must manage configuration via VCS. In Drupal 8, this means that configuration should be stored in `<repo-root>/config/default` for the default site. Thus, BLT overrides the config sync directory to use this location.

I'd suggest reviewing BLT's docs on Configuration management:
- https://docs.acquia.com/blt/developer/config-split/
- https://support.acquia.com/hc/en-us/articles/360024009393

Additionally, even if you choose not to use BLT, Acquia Cloud recommends using `config/default` when synchronizing config from a local dev environment via VCS: https://docs.acquia.com/acquia-cloud/develop/config-d8/

Using any other location besides `config/default` to store configuration is not supported by BLT. It _might_ be technically feasible but as it seems you encountered, it's likely to cause problems with config split and other features.

You mention you encountered this with BLT 11.4.1 and Drupal 8.8.6, are you implying that this _wasn't_ an issue in previous versions of either? Note that BLT has had this policy in place since its inception, however [D8 recently changed how the config sync directory](https://www.drupal.org/node/3018145) was defined and BLT changed to match, it's possible that something in your settings conflict with that.

**Comment by dkowalec** [comment]
@danepowell thanks for your feedback.
So I did go through a lot of BLT documentation and codebase to find out BLT is overriding the path to `default`. I did not find however in any documentation that there is a hard requirement to have to use `config/default` anywhere and that it could be customized.

Acquia PS team awesome @AllieRays  implemented BLT about 6 months ago and I don't remember this being a hard requirement or issue coming up. I achieved a workaround as mentioned using Acquia Cloud hooks but not ideal. If you look at the mentioned support ticket and discuss it with @jacov our TAM we can come to a happy path. I am disappointed that I had to go through this level of effort to get it working when the issue all came down to BLT.

We also have to implement our own version of BLT for our `stage` environment as we don't use `test` or `stage` splits. It would be great if people at Acquia can look at our `settings.php` and tell me if I renamed the directory to `default` if I need any logic retained in the `settings.php` file anymore? I want to ensure the split functionality will continue without having to do a tremendous amount of my own testing again to debug.

**Comment by malikkotob** [comment]
@dkowalec I have this working on a BLT 11.4.2 build currently where I've overridden BLT to use `config/sync` instead of `config/default`. My `settings.php` has the following:
```
$blt_override_config_directories = FALSE;
$config_directories['sync'] = '../config/sync';
$settings['config_sync_directory'] = '../config/sync';
```

The key there is the `$blt_override_config_directories = FALSE;` That tells BLT not to override my choice of config directory. Separately, I also had to do this in my `blt.yml` file, otherwise BLT refused to import config:

```
cm:
  core:
    dirs:
      # Corresponding value is defined in settings.php.
      sync:
        path: ../config/sync
```

**Comment by dkowalec** [comment]
@malikkotob thanks for the feedback. The response I got from Acquia was `default` is the standard practice config directory and not to use `sync` or a custom one on Acquia Cloud, even though there are ways to customize. I have all the configurations you mentioned in the past as well but simplify renaming the sync directory was the easiest but most disappointing solution. The issue though I still see is with `drush cim` doesn’t honor the config_split & I have to in addition run `drush csim $split` per environment via the pipeline build or local.

I am not sure if it was the previous version of BLT or before Drupal changing the implementation of $config settings in 8.8.5+. Since this change the blt artifact process after a tag release does not automatically sync the configuration properly. It does only a standard cim and I had to add post deploy hooks (one which doesn’t work - known issue) to run `csim $split` after the `cim`. It feels like a bunch of work around a for something that should simply work and import the configuration per environment. 

Any suggestions?

With Drupal 8.9.1+ are you experiencing the same or simply adding `$blt_override_config_directories = FALSE` and the other settings you defined also solves the problem I mentioned?

CC: @danepowell

**Comment by mikemadison13** [comment]
is this issue now moot given that 8.8.x has ended security coverage and 8.9 is on LTS until it goes EOL later this year?

**Comment by danepowell** [comment]
Thanks for the input Mike. I'm not sure I totally understand all of the issues at play here, but it sounds like given the following factors this can be closed:
1. BLT only officially supports `config/default`
2. Overriding the directory to be something like `config/sync` is not supported but may work following Malik's advice above (`$blt_override_config_directories = FALSE;`)
3. Drupal 8.8 is EOL and BLT explicitly does not support EOL packages in any branch
