### ISSUE TITLE
Detailed error output

### ISSUE THREAD

**Issue by kthrone28** [acquia/blt#4158]
The command "/var/www/vendor/drush/drush/drush sql-create --create-db --tar
  get-dump=/tmp/tmp.target.sql.gz --ansi --no-interaction --structure-tables-
  key=lightweight --strict=0 --uri=northwell.edu --root=/var/www/docroot" fai
  led.

  Exit Code: 1(General error)

  Working directory:

  Output:
  ================
  Creating database drupal_edu. Any existing database will be dropped!

  Error Output:
  ================

 In SqlCommands.php line 103:
    Unable to create database. Rerun with --debug to see any error me
  ssage.

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 32.174s
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
[error]  Command `drupal:sync:db ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/

  Command config:set was not found. Drush was unable to query the database. A
  s a result, many commands are unavailable. Re-run your command with --debug
   to see relevant log messages.

**Comment by kthrone28** [comment]
I am using Virtual Box 6.0 and running docksal on linux 2.6. Issue is that win I run a command to sync to acquia to a database it can't connect. any trouble help is accepted. 

thanks,

**Comment by sourabhbhaleraoinfosys** [comment]
I am also getting same error. Any suggestion ?
