### ISSUE TITLE
Update docs with BLT plugin for secrets management

### ISSUE THREAD

**Issue by nedsbeds** [acquia/blt#4159]
I have been working on a solution for better management of secrets in Acquia cloud using ansible-vault and wrote a BLT plugin wrapping that functionality as well as integrating it with Drush aliases.
https://github.com/nedsbeds/blt-secrets-management

Would this be suitable for addition to the list of plugins? https://support.acquia.com/hc/en-us/articles/360046918614-Acquia-BLT-Plugins

**Comment by danepowell** [comment]
Thank for the tip, I've added it to the list of plugins. It may take a few minutes to propagate through caches and such.
