### ISSUE TITLE
BLT DrupalVM Solr config should match Acquia search Solr 7.x configs in local.

### ISSUE THREAD

**Issue by sandipsmarty** [acquia/blt#4160]
Currently in BLT VM we are using Solr 4.5.1 (defined `solr_version: "4.5.1"` in box/config.yml). Tried to change the solr version to `solr_version: "7.7.1"` and ran `vagrant reload --provision` but it's throwing error saying there no solr 7.x library available.

Acquia will be launching soon Solr 7.x in fact they have provisioned Solr 7.7.1 on one of our staging environments. But until we get the solr 7.x installed in our local dev environment it's difficult to explore and implement new features or fix any solr search related bug for our application. So is there any plan to provide Solr 7.x support in BLT DrupalVM or how we can get Solr 7.x installed in the VM?

**System information**
* Operating system type: MacOS Catalina
* Operating system version: 10.15.4
* BLT version: 11.4.1

**Comment by mikemadison13** [comment]
Some of this ticket may be better posted over on the DrupalVM forums, since BLT is just pulling in DrupalVM recipes for Solr - https://docs.drupalvm.com/en/latest/extras/solr.

**Comment by danepowell** [comment]
Like Mike mentioned, this is ultimately a question for Drupal VM. If it doesn't support Solr 7, neither can we. I would recommend requesting support with Drupal VM: https://github.com/geerlingguy/drupal-vm

You might also consider switching from Drupal VM to a tool such as Lando. ADS CLI provides an out-of-the-box Lando experience and can provision Solr. It's 4.x as well, but might be easier to upgrade to 7.x: https://docs.acquia.com/dev-studio/cli/explore/
