### ISSUE TITLE
Aren't pre-commit hooks preventing usage of forks and intermediate backup of work-in-progress?

### ISSUE THREAD

**Issue by ericmorand** [acquia/blt#4161]
I've been reading the README of your tool-chain and I have concerns about the git pre-commit hooks. If I understand well their purpose, they would prevent users to commit their work if the sources dont' match the coding standard of BLT.

As such, they prevent pushing to a Git remote (a personal fork for example) - since the users can't commit - and this prevent the users from saving their work before it is perfectly written.

It looks very dangerous to me. Any big feature that spans multiple days is at risk of being lost if the computer of the contributors fails or is lost or stolen, except if he codes to the standard 100% of the time - which we all know is not happening, you would not have provided a git pre-commit hook if it was the case.

Wouldn't a pre-merge-request hook be more appropriate? It would not prevent contributors to commit and then push their intermediary work while preventing non-acceptable codes to be merged back to the main repository.

**Comment by mikemadison13** [comment]
@ericmorand you CAN disable the pre-commit hooks if you so desire. See the docs in the build.yml file included with BLT. Basically, copy these keys into your project's blt.yml and change as needed.

https://github.com/acquia/blt/blob/12.x/config/build.yml#L81

**Comment by mikemadison13** [comment]
Personally, I prefer to stop commits that don't align with standards altogether. It keeps cleanup (later) small. But I understand the points you've made (which is why BLT allows you to disable the hooks).

**Comment by danepowell** [comment]
This behavior is by design. Developers should receive feedback early and often, so that they don't accumulate a ton of changes over the course of days or weeks and then push them only to find out all at once that they are not passing lint or style standards.

If you want to commit a work-in-progress that knowingly violates standards, you can bypass commit hooks with the `-n` flag (`git commit -n -m "Danger! Danger!"`). This isn't a BLT feature, this is common to all Git commit hooks.

**Comment by danepowell** [comment]
If there's somewhere we can document this better (not sure if you looked through the docs) please let me know.

The one place I kind of _don't_ want to document it is on the Git hook itself. I've seen too many junior devs should themselves in the foot by bypassing validation.
