### ISSUE TITLE
Validating a large config folder causes 

### ISSUE THREAD

**Issue by dmgig** [acquia/blt#4162]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project --no-interaction`

**Expected behavior**

**Detailed error output**
If a BLT command is failing, run it again with the `-vvv` argument and post the full output here.

**BLT doctor output**
Post the full output of `blt doctor` in the failing environment here.

**System information**
* Operating system type: [replace]
* Operating system version: [replace]
* BLT version: [replace]

**Additional context**

**Comment by ba66e77** [comment]
@dmgig, is there more detail to this ticket you meant to provide or is it is mistakenly created ticket?

**Comment by mikemadison13** [comment]
i think this is a dup of https://github.com/acquia/blt/issues/4163
