### ISSUE TITLE
Gracefully handle non-existant `custom` directories when running validate

### ISSUE THREAD

**Issue by ba66e77** [acquia/blt#4169]
**Is your feature request related to a problem? Please describe.**
When running `blt validate` on a codebase which does not have both `docroot/themes/custom` and `docroot/modules/custom` directories, the command errors out even though the directories are not hard requirements.

```
% blt validate
> validate:php
Linting PHP files...
[error]  The "/Users/barrett.smith/Desktop/drupal-recommended-project/docroot/modules/custom" directory does not exist.
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
[error]  Command `validate:php ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/
```

**Describe the solution you'd like**
In some fashion or another, I'd like BLT to handle this more gracefully. The option I'd personally prefer is for BLT to raise a warning message that there's not a custom dir and we recommend using one but not error out.

**Describe alternatives you've considered**
An alternative would be for BLT to create the directory (and necessary README file) if it does not exist.

**Additional context**
This was raised from a codebase created with the acquia/drupal-recommended-project composer command, which does not currently create the custom directories BLT expects.

**Comment by danepowell** [comment]
I don't think we have a precedent for warnings, things either error or they don't. Given that, I think I'd prefer this to continue throwing an error, since we do consider it best practice to have `custom` directories, and they are trivial to create by hand if they are missing. I've already ensured that they are created in the project template.
