### ISSUE TITLE
Unable to upgrade to 11.4 due to mkdir() Permission denied in src/Robo/Common/UserConfig.php

### ISSUE THREAD

**Issue by D41078817** [acquia/blt#4184]
**Describe the bug**
I am on BLT 9.2.8. I upgrade to BLT 11.4.1. I run blt update and see this output:
<details>
<summary>Click for output</summary>
<pre>
string(13) "/home/vagrant"
string(13) "/home/vagrant"
Copying files from BLT's template into your project...
The following BLT updates are outstanding:
 - update_10000000: 10.x Updates.
 - update_10000001: Move Drupal modules to project composer.json.
 - update_10000002: Regenerate cloud hooks if necessary.
 - update_10001000: Remove composer autoload optimizations.
 - update_10003000: Regenerate acquia-pipelines.yml.
 - update_10004000: Migrate to acquia/memcache-settings.
 - update_11000000: Update blt-require-dev version.
 - update_11000001: Move Drupal Scaffold to project composer.json.
 - update_11000020: Update phpcs.xml.dist.
 - update_11002000: Update .gitignore with travis_wait.
 - update_11004000: Regenerate factory hooks from updated templates.

Executing updates...
-> update_10000000: 10.x Updates.

 Your composer.json file has been modified to remove the Composer merge plugin.
 You must execute `composer update --lock` to update your lock file.

 BLT 10 includes many changes to configuration and settings files. These will now be regenerated.
 Factory Hooks (/factory-hooks) have been regenerated. Review the resulting file(s) and re-add any customizations.
 Cloud Hooks (/hooks) have been regenerated. Review the resulting file(s) and re-add any customizations.
 .travis.yml has been regenerated. Review the resulting file and re-add any customizations..
 Local settings files have been regenerated. Review the resulting file(s) and re-add any customizations..

-> update_10000001: Move Drupal modules to project composer.json.
-> update_10000002: Regenerate cloud hooks if necessary.
-> update_10001000: Remove composer autoload optimizations.
-> update_10003000: Regenerate acquia-pipelines.yml.
-> update_10004000: Migrate to acquia/memcache-settings.
Memcache settings have moved from acquia/blt to acquia/memcache-settings, a separate Composer package, and additionally have been updated to use the stable Memcache 2.0 release. Your composer.json has been updated to depend on acquia/memcache-settings.

You must run `composer update acquia/memcache-settings drupal/memcache` and commit the resulting changes to composer.json and composer.lock if you wish to use these updated settings. Otherwise, you will need to provide your own Memcache settings in docroot/sites/settings. See the release notes for additional details.

-> update_11000000: Update blt-require-dev version.
acquia/blt-require-dev version has been updated in composer.json. You must run `composer update` and commit both composer.json and composer.lock to apply the changes.
-> update_11000001: Move Drupal Scaffold to project composer.json.
-> update_11000020: Update phpcs.xml.dist.
phpcs.xml.dist has been updated to accommodate changes in Coder 8.3.7. You should review and commit the changes.
-> update_11002000: Update .gitignore with travis_wait.
-> update_11004000: Regenerate factory hooks from updated templates.
bool(false)
PHP Warning:  mkdir(): Permission denied in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 41

Warning: mkdir(): Permission denied in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 41
PHP Warning:  file_put_contents(/.config/blt/user.json): failed to open stream: No such file or directory in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 116

Warning: file_put_contents(/.config/blt/user.json): failed to open stream: No such file or directory in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 116
bool(false)
PHP Warning:  mkdir(): Permission denied in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 41

Warning: mkdir(): Permission denied in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 41
PHP Warning:  file_put_contents(/.config/blt/user.json): failed to open stream: No such file or directory in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 116

Warning: file_put_contents(/.config/blt/user.json): failed to open stream: No such file or directory in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 116
New "factory-hooks/" directory created in repo root. Please commit this to your project.
bool(false)
PHP Warning:  mkdir(): Permission denied in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 41

Warning: mkdir(): Permission denied in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 41
PHP Warning:  file_put_contents(/.config/blt/user.json): failed to open stream: No such file or directory in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 116

Warning: file_put_contents(/.config/blt/user.json): failed to open stream: No such file or directory in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 116

 Factory Hooks have been regenerated in your existing /factory-hooks directory.
 Review the resulting file(s) and re-add any customizations.

Removing deprecated files and directories...
&gt; blt:init:shell-alias
string(13) "/home/vagrant"
The BLT alias is already installed and up to date.
</pre>
</details>

You can see it's trying to write to `/.config/blt/user.json` which doesn't exist. It should be writing to `/home/vagrant/.config/blt/user.json`.

In the above output you'll notice some debug info I added. This is printed by putting `var_dump(getenv('HOME'))` in Acquia\Blt\Robo\Blt::configDir(). You can see sometimes it prints `string(13) "/home/vagrant"` as expected, but sometimes it prints `bool(false)`. I assume the cases where its false is what is causing BLT to attempt to write to `/.config/blt/user.json`.

**To Reproduce**
This should be reproducible by:
1. Installing BLT 9.2.8
2. composer require acquia/blt:~11.4.0
3. composer update acquia/blt --with-dependencies
4. blt update

**Expected behavior**
I would expect it to write to `/home/vagrant/.config/blt/user.json` instead of `/.config/blt/user.json`.

**Detailed error output**
See above.

**BLT doctor output**
NA

**System information**
* Operating system type: Ubuntu
* Operating system version: 16.04
* BLT version: 11.4.1

**Additional context**
NA

**Comment by danepowell** [comment]
You said you are trying to upgrade to 11.4.0, but 11.4.1 is the latest release, and I believe this was fixed in 11.4.1: https://github.com/acquia/blt/pull/4109

Have you tried 11.4.1?

**Comment by D41078817** [comment]
This was when upgrading to 11.4.1. Sorry for the confusion.

**Comment by danepowell** [comment]
I'm pretty sure you are not actually getting 11.4.1, despite what you expect.

> PHP Warning:  mkdir(): Permission denied in /var/www/mysite/vendor/acquia/blt/src/Robo/Common/UserConfig.php on line 41

UserConfig#41 does not contain a call to mkdir in either 11.4.0 or 11.4.1. It _does_ however in 11.3.0. So I expect you are actually getting some earlier version of BLT such as 11.3.0.

What's especially odd though is that the update output you posted also contains an 11.4.0 update hook, despite the line numbers indicating you are using 11.3.0.

Can you post the full output of your upgrade attempts, including the `composer require` line, and also include the output of `composer show acquia/blt` after the require step?
