### ISSUE TITLE
Change order of running updates and config imports

### ISSUE THREAD

**Issue by vaibhavjain-in** [acquia/blt#419]
In setup:update, setup.xml, we should Import configs first and then execute DB updates.
As @grasmash stated, this may cause issue, we can add another piece of code to import config before executing updates. So, the new process can be
Config Import -> Execute updates -> Config Import

**Comment by vaibhavjain-in** [comment]
PR -> https://github.com/acquia/blt/pull/420

**Comment by grasmash** [comment]
Fixed by #420
