### ISSUE TITLE
Pipelines Build fails to Complete on frontend-reqs step

### ISSUE THREAD

**Issue by jmgala** [acquia/blt#4195]
During the execution of the default build-artifact step, the command source:build:frontend-reqs is executed to install the tools required for the front-end build process.

Pipelines is failing during that step, this is the error message I get:
`[error]  TTY mode requires /dev/tty to be read/writable. `

I have seen other tickets referencing the same error, related to the "drupal-check" version but they have been tagged as solved. Has this issue been introduced again with BLT 12.X / D9?

**Comment by danepowell** [comment]
The `source:build:frontend-reqs` command is extremely lightweight, it [basically just shells out](https://github.com/acquia/blt/blob/12.x/src/Robo/Commands/Source/FrontendCommand.php#L41) to whatever command you've defined for that hook.

Thus, it seems more likely that there's a problem with whatever command you've defined for that hook.

Things you should check to troubleshoot:
- What frontend-reqs command are you running? What's the contents of blt.yml?
- Does the same error occur if you define the frontend-reqs hook to be a noop command?
- Does the same error occur if you run the frontend-reqs command outside of BLT (i.e. directly via acquia-pipelines.yml)?

**Comment by LibrarianGeek** [comment]
We're running into the same issue in the build-artifact step, running D9.0.2, BLT 12.1.0
The same error displays: [error] TTY mode requires /dev/tty to be read/writable.

Our blt.yml file is running the following:
1. command-hooks:frontend-reqs:command: 'npm ci' (alternated with 'npm install' to see if that would make a difference) in our custom theme directory, which is dir: ${docroot}/themes/custom/[theme_name]
2. command-hooks:frontend-assets:command: 'npm run build', in the same custom theme directory; the build script is "gulp sass:prod", which just compiles our sass files to a single css file, minified with no comments.

**Comment by mikemadison13** [comment]
@danepowell i understand that the command is pretty lightweight but I'm running into this as well with BLT 12.3.0. I think that we at least need to document a work around. Some consistent notes between the issues here are that: 

- it's happening during the artifact build step (and isn't happening earlier in the build)
- it is happening when you run `npm ci` (i'm not sure if `npm install` is a valid work around, although note we specifically recommended swapping to `npm ci` in https://github.com/acquia/blt/issues/3564

**Comment by mikemadison13** [comment]
i opened a new issue for this to try and chase down the issue.
