### ISSUE TITLE
Warning on blt validate command

### ISSUE THREAD

**Issue by manerkargaurav** [acquia/blt#4196]
I am using
Drupal 8.8.8
BLT v 11.4.2

Run command "blt validate"

Following warning is shown 

![image](https://user-images.githubusercontent.com/54015848/85828449-1439ae00-b7a6-11ea-9f57-74738db2182d.png)

**Comment by danepowell** [comment]
Thanks for reporting, this is an upstream issue and not something BLT can control: https://github.com/mglaman/drupal-check/issues/178

**Comment by manerkargaurav** [comment]
closing this issue as it is not related to BLT.
