### ISSUE TITLE
Improve developer experience for custom filesets by providing trait for predefined Finder objects

### ISSUE THREAD

**Issue by hctom** [acquia/blt#4198]
**Is your feature request related to a problem? Please describe.**
The built-in `Acquia\Blt\Robo\Filesets\Filesets` class has some protected helper methods to initialize Symfony Finder objects with sensible defaults for specific file types. These helper methods should also be available if you want to create a custom fileset, so you do not have to initialize them on your own. This would drastically improve the developer experience for custom file sets and reduce a lot of duplicate code that has to be maintained.

**Describe the solution you'd like**
A trait (e.g. `Acquia\Blt\Robo\Filesets\FilesetsTrait`) should be provided, that contains the following helper methods (currently only available in `Acquia\Blt\Robo\Filesets\Filesets` class) as protected methods:
* `getPhpFilesetFinder()`
* `getFrontendFilesetFinder()`
* `getYamlFilesetFinder()`
* `getTwigFilesetFinder()`

After moving these methods to a trait, the `Acquia\Blt\Robo\Filesets\Filesets` class has to use this trait as well.

**Comment by danepowell** [comment]
Makes sense I think, we're always interested in making the developer experience easier. It sounds like you are pretty familiar with the implementation, if you'd like to submit a pull request to get this done sooner I'd be happy to review.

**Comment by hctom** [comment]
@danepowell good to hear that this is an enhancement that makes sense to you ;) I will give it a try this evening!

**Comment by hctom** [comment]
@danepowell There you go. I'd appreciate your feedback.
