### ISSUE TITLE
Memcache settings not loaded properly on ACSF

### ISSUE THREAD

**Issue by nikunjkotecha** [acquia/blt#4209]
**Describe the bug**
memcache.settings.php is included before memcache prefix and server are set (which is done later)

memcache included in https://git.drupalcode.org/project/acsf/-/blob/8.x-2.x-release/acsf_init/lib/sites/g/settings.php#L25
memcache defaults set in https://git.drupalcode.org/project/acsf/-/blob/8.x-2.x-release/acsf_init/lib/sites/g/settings.php#L113

So the condition in https://github.com/acquia/memcache-settings/blob/master/memcache.settings.php#L21 is never true and hence settings don't work

**To Reproduce / Context**
This is reproducible only on ACSF ENV with code using BLT

**Expected behavior**
Sequence of code include should be proper, memcache / cache settings should be included in post-settings-php instead of pre-settings-php

**Comment by danepowell** [comment]
@nikunjkotecha it saves time if you can follow the issue template when filing issues, including providing your BLT version.

In BLT 11 and 12 (the currently-supported releases), memcache settings are included in post-settings-php, which as you describe should be the correct behavior.

I assume you are using an older version of BLT. If you can reproduce this on BLT 11 or 12 (make sure you are using the latest factory hooks, linked below), feel free to reopen.

- https://github.com/acquia/blt/blob/11.x/scripts/factory-hooks/post-settings-php/memcache.php
- https://github.com/acquia/blt-acsf/blob/master/factory-hooks/post-settings-php/memcache.php (plugin for BLT 12)

**Comment by nikunjkotecha** [comment]
Hi @danepowell 

Apologies for missing the required information and thanks for the explanation.

Version details:
* acquia/blt version used 11.x-dev (commit hash: 3928d6c0598185753a6852a3932039e3abc63fc0)
* acquia/memcache-settings version used dev-master (commit hash: c381d911d84fdfeac34ca3c6f56254be5ade6840)

File is included for us as part of https://github.com/acquia/blt/blob/11.x/settings/cache.settings.php (verified using XDEBUG on cloud).

I see the file was created in factory-hooks/post-settings-php but we modified it to support memcache in local and introduced a bug.

Question: From what we understood memcache settings should be included out of the box without any additional file (as we can see it is done as part of cache.settings.php in the BLT flow and it seems we include it again in post-settings-php, is this required to include it twice?

cc @vbouchet

**Comment by danepowell** [comment]
I see, I think that explains the whole situation, thanks for clarifying.

I believe what you are seeing is intended behavior, and if you restore your post-settings-php include it should work fine. Let me know if it doesn't.

> Question: From what we understood memcache settings should be included out of the box without any additional file (as we can see it is done as part of cache.settings.php in the BLT flow and it seems we include it again in post-settings-php) is this required to include it twice?

I know this seems strange, but functionally it should be fine, the second time you include it it will just rewrite any settings that changed.

On ACSF some settings need to be included prior to settings.php, others after, and others still it doesn't matter. BLT's settings includes aren't split up according to those categories, and it would be a lot of overhead to manage settings at that level of granularity. As long as it doesn't hurt anything, the easiest solution is to just include them twice :)

**Comment by nikunjkotecha** [comment]
I confirm it works and I agree it makes sense to keep it simple and ensure it works all the time for all environments by including twice. It was just the confusion because of the expectation of it to be done OOTB (which in the end it is as file in post-factory-hooks is created by default when we setup).

Thanks again for the explanation :)
