### ISSUE TITLE
Update README and docs to reflect BLT 12.x state

### ISSUE THREAD

**Issue by vstanchev** [acquia/blt#4210]
I see that there are several stable releases of 12.x but in the version table in [README.md](https://github.com/acquia/blt/blob/12.x/docs/README.md) and the [official docs](https://docs.acquia.com/blt/) it still says that BLT 12 is unsupported and unstable. So what's the current state? Also, it doesn't say which version of BLT supports Drupal 8.9 but I assume that will be BLT 11 only. Is that right?

**Comment by danepowell** [comment]
Please see https://github.com/acquia/blt/pull/4172 , the docs are outdated and being updated today. Thanks.
