### ISSUE TITLE
Settings are overridden by composer install script

### ISSUE THREAD

**Issue by benjifisher** [acquia/blt#4212]
**Describe the bug**

I have customized `blt/blt.yml` and committed it to my repository. Running `composer install` from a clean copy of the repository modifies the file.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. `mkdir blt-test`
1. `cd blt-test`
1. `composer require acquia/blt`
1. `sed -i 's/machine_name: blt-test/machine_name: my-blt-project/' blt/blt.yml`
1. `git init`
1. `git add blt/blt.yml composer.json composer.lock`
1. `git commit -m 'initial commit'`
1. `git clean -dfx .`
1. `composer install`
1. `git diff`

**Expected behavior**

I expect no changes to the git repository. The above steps simulate checking out a clean version of the repository and running `composer install`.

**Detailed error output**

```
$ git diff
diff --git a/blt/blt.yml b/blt/blt.yml
index 718f9b8..1d3a87b 100644
--- a/blt/blt.yml
+++ b/blt/blt.yml
@@ -1,2 +1,2 @@
 project:
-  machine_name: my-blt-project
+  machine_name: blt-test
```

**BLT doctor output**

This is not really relevant, but since you asked:

```
$ vendor/bin/blt doctor
[error]  The provided cwd "/tmp/blt-test/docroot" does not exist.
```

**System information**
* Operating system type: Linux
* Operating system version: Ubuntu 20.04 (actually PopOS, but pretty close)
* BLT version: 12.1.0

**Additional context**

In my actual project, `composer install` makes several unwanted changes to the file. It removes comments and reformats strings. I could just commit those changes, but I think that changing `machine_name` is likely to cause problems. IMO, the file should not be touched if it already exists, or at least that should be an option.

It seems to be using the directory name. If I run `composer install` from a Docker container, that is likely to be `app`. If I run it from the host, then it is likely to be something different.

**Comment by danepowell** [comment]
This occurs because you are deleting `blt/.schema_version`. That file must be committed to your repository. If you delete it, BLT has no way of knowing whether you've previously initialized BLT, and if so, what "schema" it's on.

We can add this to the install docs, and print a line after the initial `composer install` advising you to commit it. Would that have prevented this in your case? Where else would you have looked for this information?
