### ISSUE TITLE
BLT throwing errors for security checks

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#4223]
**Describe the bug**
BLT is throwing a security check error even though the version of the module is not affected. I could disable to security check but i would prefer to keep it on. Is there a way to get around just this?

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Install `group` module version `1.0.0-rc5`
2. Run build on Travis-CI
3. See error

**Expected behavior**
A successful build

**Detailed error output**
[Acquia\Blt\Robo\Tasks\DrushTask] Running /mnt/tmp/local.prod/source/vendor/bin/drush @self pm:security --no-interaction -v --ansi in /mnt/tmp/local.prod/source/docroot

 [warning] One or more of your dependencies has an outstanding security update.
 [notice] Try running: composer require drupal/group --update-with-dependencies
 [notice] If that fails due to a conflict then you must update one or more root dependencies.

+--------------+-------------------+
 Name          Installed Version 
+--------------+-------------------+
 drupal/group  1.0.0-rc5         
+--------------+-------------------+

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 0.312s
[notice] To disable security checks, set disable-targets.tests.security.check.updates to true in blt.yml.
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.

**Comment by jedgar1mx** [comment]
According to the security issue `1.0.0-rc5` is not affected.
https://www.drupal.org/sa-contrib-2020-033

**Comment by mikemadison13** [comment]
FYI BLT just runs the Drush command, there isn't really any BLT specific functionality here. So if Drush is reporting an issue, it's really something with Drush not BLT.

**Comment by jedgar1mx** [comment]
Ahhh got it. Thanks for the clarification Mike

**Comment by mikemadison13** [comment]
You betcha. Sorry for the confusion, this comes up every now and again!

**Comment by mikemadison13** [comment]
see https://github.com/acquia/blt/blob/12.x/src/Robo/Commands/Tests/SecurityUpdatesCommand.php#L19
