### ISSUE TITLE
blt setup shows, Access denied for user 'drupal'@'localhost'

### ISSUE THREAD

**Issue by Dharmend** [acquia/blt#4234]
**Unable to install drupal 8 with BLT**
When I run the blt setup command outside vm then it shows error,  I am very confused where to run this command , terminal shows the message run this command on VM, But when I try to run it on VM , It says Blt not found.

When Run the blt setup from outside vm, The error is as below:
Failed to drop or create the database. Do it yourself before installing. ERROR 1045 (28000): Access denied for user 'drupal'@'localhost' (using password: YES)

**It's not working because...**
I am running the blt setup command inside the VM also, the error are as below,

vagrant@local:/var/www/second-vm$ ​​​​​​​blt setup
WARNING:root:could not open file '/etc/apt/sources.list.d/ppa_ondrej_php_bionic.list'

WARNING:root:could not open file '/etc/apt/sources.list.d/packagecloud_io_varnishcache_varnish64_ubuntu.list'

blt: command not found

**Detailed error output**
When run blt setup -vvv from outside vm

`<pre> <span style="background-color:#C4A000"><font color="#555753"><b>[warning]</b></font></span> Failed to drop or create the database. Do it yourself before installing. ERROR 1045 (28000): Access denied for user &apos;drupal&apos;@&apos;localhost&apos; (using password: YES)
 [3.51 sec, 10.4 MB]
 <span style="background-color:#06989A"><font color="#EEEEEC"><b>[notice]</b></font></span> Starting Drupal installation. This takes a while. [3.51 sec, 10.41 MB]
 <span style="background-color:#06989A"><font color="#EEEEEC"><b>[debug]</b></font></span> Calling <font color="#4E9A06">install_drupal</font>(<font color="#4E9A06">Composer\Autoload\ClassLoader, array, array</font>) [3.56 sec, 11.27 MB]
 <span style="background-color:#06989A"><font color="#EEEEEC"><b>[notice]</b></font></span> Performed install task: <font color="#4E9A06">install_select_language</font> [8.84 sec, 23.11 MB]
 <span style="background-color:#06989A"><font color="#EEEEEC"><b>[notice]</b></font></span> Performed install task: <font color="#4E9A06">install_select_profile</font> [8.85 sec, 23.11 MB]
 <span style="background-color:#06989A"><font color="#EEEEEC"><b>[notice]</b></font></span> Performed install task: <font color="#4E9A06">install_load_profile</font> [8.85 sec, 23.11 MB]
 <span style="background-color:#06989A"><font color="#EEEEEC"><b>[info]</b></font></span> Undefined index: value install.core.inc:2303 [9.37 sec, 23.95 MB]
 <span style="background-color:#06989A"><font color="#EEEEEC"><b>[info]</b></font></span> Array to string conversion install.core.inc:2303 [9.37 sec, 23.95 MB]

<font color="#C4A000">In install.core.inc line 2307:</font>
<span style="background-color:#CC0000"><font color="#D3D7CF">                                                        </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  [Drupal\Core\Installer\Exception\InstallerException]  </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  Database settings:                                    </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">                                                        </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">  Array                                                 </font></span>
<span style="background-color:#CC0000"><font color="#D3D7CF">       </font></span></pre>`
**BLT doctor output**
 `<pre><span style="background-color:#C4A000"><font color="#555753"><b>[warning]</b></font></span> Drupal VM is locally initialized, but you are not inside the VM.
<span style="background-color:#C4A000"><font color="#555753"><b>[warning]</b></font></span> You should execute all BLT commands from within Drupal VM.
<span style="background-color:#C4A000"><font color="#555753"><b>[warning]</b></font></span> Use <font color="#C4A000">vagrant ssh</font> to enter the VM.
<span style="background-color:#06989A"><font color="#2E3436"> Do you want to continue and execute this command on the host machine? (y/n)</font></span> y
+---------------------------+--------------------------------------------------------------+
|<font color="#4E9A06"> Property                  </font>|<font color="#4E9A06"> Value                                                        </font>|
+---------------------------+--------------------------------------------------------------+
| %paths.%root              | /var/www/html/Lando-BLT/second-vm/docroot                    |
| %paths.%site              | sites/default                                                |
| %paths.%modules           | sites/all/modules                                            |
| %paths.%themes            | sites/all/themes                                             |
| %paths.%config-sync       | /var/www/html/Lando-BLT/second-vm/config/default             |
| alias-searchpaths.0       | /var/www/html/Lando-BLT/second-vm/drush/sites                |
| blt-version               | 11.4.2                                                       |
| composer-version          | Composer 1.6.3 2018-01-31 16:28:17                           |
| config-sync               | /var/www/html/Lando-BLT/second-vm/config/default             |
| db-driver                 | mysql                                                        |
| db-hostname               | localhost                                                    |
| db-name                   | drupal                                                       |
| db-password               | drupal                                                       |
| db-port                   | 3306                                                         |
| db-username               | drupal                                                       |
| drupal-settings-file      | sites/default/settings.php                                   |
| drupal-version            | 8.9.3                                                        |
| drush-alias-files.0       | /var/www/html/Lando-BLT/second-vm/drush/sites/second-vm.site |
|                           | .yml                                                         |
| drush-cache-directory     | /home/raj/.drush/cache                                       |
| drush-conf.0              | /var/www/html/Lando-BLT/second-vm/vendor/drush/drush/drush.y |
|                           | ml                                                           |
| drush-conf.1              | /var/www/html/Lando-BLT/second-vm/drush/drush.yml            |
| drush-conf.2              | /var/www/html/Lando-BLT/second-vm/docroot/sites/default/loca |
|                           | l.drush.yml                                                  |
| drush-script              | /var/www/html/Lando-BLT/second-vm/vendor/drush/drush/drush   |
| drush-temp                | /tmp                                                         |
| drush-version             | 10.3.4                                                       |
| modules                   | sites/all/modules                                            |
| php-bin                   | /usr/bin/php7.4                                              |
| php-conf.0                | /etc/php/7.4/cli/php.ini                                     |
| php-os                    | Linux                                                        |
| root                      | /var/www/html/Lando-BLT/second-vm/docroot                    |
| site                      | sites/default                                                |
| stacks.drupal-vm.inited   | true                                                         |
| stacks.dev-desktop.inited | false                                                        |
| themes                    | sites/all/themes                                             |
| uri                       | http://local.blted10.com                                     |
+---------------------------+--------------------------------------------------------------+
+------------------------------------------+--------------------------------------------------------------+
|<font color="#4E9A06"> Check                                    </font>|<font color="#4E9A06"> Problem                                                      </font>|
+------------------------------------------+--------------------------------------------------------------+
| <font color="#C4A000">ConfigCheck:checkGitConfig</font>               | Git repositories are not defined in blt.yml.                 |
|                                          |   Add values for git.remotes to blt.yml to enabled automated |
|                                          | deployment.                                                  |
| <span style="background-color:#CC0000"><font color="#D3D7CF">DbCheck:checkDbConnection</font></span>                | Could not connect to MySQL database.                         |
|                                          |                                                              |
|                                          | Is your *AMP stack running?                                  |
|                                          | Are your database credentials correct?                       |
|                                          |   db-driver: mysql                                           |
|                                          |   db-hostname: localhost                                     |
|                                          |   db-username: drupal                                        |
|                                          |   db-password: drupal                                        |
|                                          |   db-name: drupal                                            |
|                                          |   db-port: 3306                                              |
|                                          |                                                              |
|                                          | To verify your mysql credentials, run `mysql -u drupal -h    |
|                                          | localhost -pdrupal -P 3306`                                  |
|                                          |                                                              |
|                                          | Are you using the correct PHP binary?                        |
|                                          | Is PHP using the correct MySQL socket?                       |
|                                          |   php-os: Linux                                              |
|                                          |   php-bin: /usr/bin/php7.4                                   |
|                                          |   php-conf: /etc/php/7.4/cli/php.ini                         |
|                                          |                                                              |
|                                          | Are you using the correct site and settings.php file?        |
|                                          |   site: sites/default                                        |
|                                          |   drupal-settings-file: sites/default/settings.php           |
|                                          |                                                              |
|                                          | To verify, run `drush sqlc`                                  |
|                                          |                                                              |
| <font color="#C4A000">DrupalCheck:checkDrupalBootstrapped</font>      | Could not bootstrap Drupal via drush without alias.          |
| <span style="background-color:#CC0000"><font color="#D3D7CF">DrupalCheck:checkDrupalInstalled</font></span>         | Drupal is not installed.                                     |
|                                          |                                                              |
|                                          | Run `blt drupal:install` to install Drupal locally.          |
| <span style="background-color:#CC0000"><font color="#D3D7CF">FileSystemCheck:checkFileSystem:%files</font></span>   | Public files directory is not set.                           |
| <span style="background-color:#CC0000"><font color="#D3D7CF">FileSystemCheck:checkFileSystem:%private</font></span> | Private files directory is not set.                          |
| <span style="background-color:#CC0000"><font color="#D3D7CF">FileSystemCheck:checkFileSystem:%temp</font></span>    | Temporary files directory is not set.                        |
| <font color="#C4A000">NodeCheck:checkNodeVersionFileExists</font>     | Neither .nvmrc nor .node-version file found in repo root.    |
| <span style="background-color:#CC0000"><font color="#D3D7CF">PhpCheck:checkPhpDateTimezone</font></span>            | PHP setting for date.timezone is not set.                    |
|                                          |   Define date.timezone in /etc/php/7.4/cli/php.ini           |
| <span style="background-color:#CC0000"><font color="#D3D7CF">WebUriCheck:checkUriResponse</font></span>             | Did not get a response from http://local.blted10.com         |
|                                          | Is your *AMP stack running?                                  |
|                                          | Is your /etc/hosts file correctly configured?                |
|                                          | Is your web server configured to serve this URI from         |
|                                          | /var/www/html/Lando-BLT/second-vm/docroot?                   |
|                                          | Is options.uri set correctly in                              |
|                                          | /var/www/html/Lando-BLT/second-vm/docroot/sites/default/loca |
|                                          | l.drush.yml?                                                </pre>`

**System information**
* Operating system type: Ubuntu
* Operating system version: 18.04.4
* BLT version: 11.4.2

**Comment by danepowell** [comment]
> [warning] You should execute all BLT commands from within Drupal VM.

As this warning message says, you should execute all BLT commands inside the VM.

So you just need to create the BLT alias inside the VM: `./vendor/bin/blt alias`

This is also mentioned here (should still be valid for 11.x): https://docs.acquia.com/blt/install/creating-new-project/#troubleshooting

Without output / logs from the VM creation, it's impossible to say why this alias wasn't created in the first place, normally it is if you create the VM with `blt vm`.

**Comment by Dharmend** [comment]
It Works thanks @danepowell

I have create the new setup, this time i choose the geerlingguy/ubuntu1604 when executing the blt vm
And run the below commands to create the alias

composer clear-cache
export COMPOSER_PROCESS_TIMEOUT=2000

./vendor/bin/blt blt:init:shell-alias
source ~/.bash_profile

Now I can use the BLT, I am sure the issue was unable to create the alias for VM,
Thanks Again !
