### ISSUE TITLE
New project - change profile

### ISSUE THREAD

**Issue by justclint** [acquia/blt#4240]
**I want to...**
Setup a new project with the standard profile.

Im setting up a new project and want to use the standard profile. Im following the steps here: https://github.com/acquia/blt/blob/12.x/docs/install/creating-new-project.rst#id1

**Questions:**

1. It says to `composer require acquia/headless_lightning:~1.1.0` but my instinct was to `composer remove acquia/lightning`. 

I guess Id think I would just want to remove lighting instances vs adding more so just wanted to get confirmation on these steps.

2. If I try to add `composer require acquia/headless_lightning:~1.1.0` I get a version incompatibility error.

```
  Problem 1
    - acquia/headless_lightning 1.1.0-alpha3 requires acquia/lightning 2.2.5 -> satisfiable by acquia/lightning[2.2.5] but these conflict with your requirements or minimum-stability.
    - acquia/headless_lightning 1.1.0-alpha2 requires acquia/lightning 2.2.3 -> satisfiable by acquia/lightning[2.2.3] but these conflict with your requirements or minimum-stability.
    - acquia/headless_lightning 1.1.0-alpha1 requires acquia/lightning ~2.2.0 -> satisfiable by acquia/lightning[2.2.0, 2.2.0-alpha1, 2.2.0-rc1, 2.2.0-rc2, 2.2.1, 2.2.1-alpha1, 2.2.1-alpha2, 2.2.10, 2.2.2, 2.2.2-alpha1, 2.2.2-alpha2, 2.2.3, 2.2.4, 2.2.4-alpha1, 2.2.4-alpha2, 2.2.4-alpha3, 2.2.4-alpha4, 2.2.4-beta1, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9] but these conflict with your requirements or minimum-stability.
    - Installation request for acquia/headless_lightning ~1.1.0 -> satisfiable by acquia/headless_lightning[1.1.0-alpha1, 1.1.0-alpha2, 1.1.0-alpha3].
```

The initial composer blt create project added `"acquia/lightning": "dev-8.x-4.x",`. I tried composer requiring headless_lightning:~2, 3, 4 but none seem to be available.

Thanks!

**Comment by benjifisher** [comment]
My reading of those docs is that `acquia/headless_lightning` is provided as an example, not a recommendation. I have a new Drupal 9/BLT 12 project, and I never considered using that profile.

You might also compare with https://github.com/acquia/drupal-recommended-project.

**Comment by danepowell** [comment]
Yeah headless_lightning is just a suggestion, you should substitute whatever profile you want to include. If you want to use a core profile, there's no need to `composer require` anything at all.

Can you suggest a change to the docs to make that more explicit?

**Comment by justclint** [comment]
Thanks! @danepowell I think now that you pointed that out It says `Download the profile of your choice` just above that command which I must of missed. Reading again now makes sense.
