### ISSUE TITLE
BLT VM Package not Available in Packagist

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4243]
The BLT VM package (https://github.com/acquia/blt-vm) is not currently available to `composer require acquia/blt-vm` and I can't find it in packagist.

Can we get that added please?

**Comment by jayakrishnanj** [comment]
I tried `composer require acquia/blt-drupal-vm` and it got added into the project.

**Comment by mikemadison13** [comment]
ah, that's my bad. i must have typed the wrong package name. thanks @jayakrishnanj !
