### ISSUE TITLE
BLT 12 Issues w/ Default Local Alias

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4247]
This is a rewrite of #4242 in which I articulated a problem but wrongly identified the root cause. So I'm starting over clean here so we have something sensible (and not as backwards). 

**Describe the bug**
After spinning up a new BLT 12 project and spinning up Drupal VM, I can run blt setup:drupal:install w/o config, but as soon as I add config and the re-run, the config import fails because of BLT's default config for local drush alias.

In the past, we have defaulted to self as the default but now we have local.${project.machine_name}.com.

This appears to be "properly" configured in BLT's config, but the stock drush file is wrong. see https://github.com/acquia/blt/blob/12.x/settings/default.local.drush.yml

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run composer create-project acquia/drupal-recommended-project --no-interaction
2. Add drupal vm and setup a box
3. SSH into the container
4. Run blt setup:drupal:install -n
5. export configuration w/ drush cex -y
6. re-run blt setup:drupal:install -n

**Expected behavior**

**Detailed error output**
```
blt drupal:update
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/scenario/vendor/bin/drush @self updb --no-interaction --ansi in /var/www/scenario/docroot

In Request.php line 1183:
                                                     
  Invalid Host "local.${project.machine_name}.com".  
                                                     

updatedb [--cache-clear [CACHE-CLEAR]] [--entity-updates] [--post-updates [POST-UPDATES]] [--no-cache-clear] [--no-post-updates] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command>

[Acquia\Blt\Robo\Tasks\DrushTask]  Exit code 1  Time 0.256s
[error]  Failed to execute database updates!
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
```

**System information**
* Operating system type: Drupal VM / Ubuntu
* BLT version: 12.3

**Comment by danepowell** [comment]
@mikemadison13 what if you set `project.machine_name` in blt.yml? That should get substituted into the generated `local.drush.yml`.

`self` is not a valid URI (by the very definition of a URI), I don't know if Drush makes some exception to support it but it seems like using a real URI is better practice.

**Comment by mikemadison13** [comment]
i'm up for whatever you like, i just know that what is getting spit out isn't valid :)
