### ISSUE TITLE
Composer 2 Support in 11.x

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#4250]
**Is your feature request related to a problem? Please describe.**

Composer2 RC1 was released on September 10, 2020. 
https://github.com/composer/composer/releases/tag/2.0.0-RC1

There are major performance benefits to it:
http://hojtsy.hu/blog/2020-sep-28/testing-composer-2-rc1-drupal-9-huge-memory-and-time-savings-and-what-does-it-mean

**Describe the solution you'd like**
Update the version constraint here:
https://github.com/acquia/blt/blob/11.x/composer.json#L21

To match
https://github.com/acquia/blt/blob/12.x/composer.json#L22

Evaluate other parts of this PR for backport.
https://github.com/acquia/blt/pull/4088/files

**Additional context**
Support in 11.x is important since:
1: BLT 12.x does not support Drupal 8.
2: Most blt sites rely on Solr
3: Acquia Search is constrained to the 1.x branch of search_api_solr: https://docs.acquia.com/acquia-search/modules/
4: search_api_solr 1.x does not support D9

Therefore Acquia hosted sites using solr cannot upgrade to Drupal 9/BLT 12 till Acquia-Search/Solr-7 reaches GA in Q4/Q1.

**Comment by danepowell** [comment]
I agree this is necessary, hopefully the backport is straightforward.

**Comment by mikemadison13** [comment]
A few notes:

- https://github.com/grasmash/drupal-security-warning/pull/11 (or something similar) will be required to unblock this update as that package doesn't support composer 2.x
- we need to update dealerdirect/phpcodesniffer-composer-installer to at least ^0.7.0 to support composer 2.x
- we need to update the root composer.json file to support "composer-plugin-api": "^1.1.0 || ^2.0",
- we need to add the two new composer plugins (as was done in BLT 12.x)

i did a quick test locally and am blocked by the drupal-security-warning plugin from going farther. @grasmash I dunno if you're willing to merge my PR? it looks smaller / simpler than the one you had opened back in March but based on my experience in the BLT PHPCS plugin what I did there should be both simple and functional.

**Comment by danepowell** [comment]
Might also want to update Travis CI to use Composer 2 if that's compatible with ORCA. I don't think ORCA directly manages Composer versions, but it might conflict with other Acquia packages. And somewhere a self-update is getting run.

**Comment by mikemadison13** [comment]
FYI from: https://github.com/composer/composer/releases

```
The current plan is to release a 2.0 final before end of October. It is almost 100% compatible with Composer 1 with the exception of plugins, so please do try it ASAP and report any regression you find. The lock files from v1 can be used by v2 and vice-versa, so don't worry about that.
```

**Comment by danepowell** [comment]
Should be fixed: https://github.com/acquia/blt/pull/4260

**Comment by greylabel** [comment]
@danepowell 👋  - any chance you can cut a new 11.x tag with this included?

**Comment by danepowell** [comment]
Yep should be included in https://github.com/acquia/blt/releases/tag/11.6.0
