### ISSUE TITLE
Replace blt drupal:update with drush deploy

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#4252]
**Is your feature request related to a problem? Please describe.**
The blt drupal:update command is a bit of a complicated mess that does lots of things, with lots of possible configuration, and isn't fun to maintain.

**Describe the solution you'd like**
Drush recently added a "deploy" command that is very similar: https://github.com/drush-ops/drush/pull/4359

Can we replace (at least part of) blt drupal:update with drush deploy? Drush deploy looks to have far less configurability so we'd either need to sacrifice some of that flexibility, or get Drush to add it.

**Comment by mikemadison13** [comment]
seems logical to me!

**Comment by danepowell** [comment]
I think this is more effort than it's worth at this point.
