### ISSUE TITLE
Remove zaporylie/composer-drupal-optimizations

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#4256]
**Is your feature request related to a problem? Please describe.**
The zaporylie/composer-drupal-optimizations package is required by BLT 11. It's become progressively more unstable lately, and will be unnecessary with Composer 2. Maybe it's time to remove it as a BLT dependency.

**Describe the solution you'd like**
Remove zaporylie/composer-drupal-optimizations from composer.json.

Also remove it from docs, possibly prestissimo as well: https://docs.acquia.com/blt/install/

**Additional context**
https://github.com/zaporylie/composer-drupal-optimizations/issues/18

**Comment by zaporylie** [comment]
Hi @danepowell. I stopped by to ask what makes you feel that `zaporylie/composer-drupal-optimizations` become _progressively more unstable lately_?

**Comment by danepowell** [comment]
@zaporylie sorry I was in a rush and wrote without thinking. I've been having a lot of problems with Composer lately and haven't had time to pin them to specific packages, I just know vaguely that they are due to the ecosystem of global plugins. It's unfair of me to point fingers without evidence :smile: 

Thanks for checking in.

**Comment by danepowell** [comment]
Removed from composer.json in https://github.com/acquia/blt/pull/4260

**Comment by gaards** [comment]
> Removed from composer.json in #4260

This issue can now be closed?
