### ISSUE TITLE
Errors and warnings on git push command

### ISSUE THREAD

**Issue by manerkargaurav** [acquia/blt#4267]
**Describe the bug**
Sometimes i get below errors and warnings after running git push  branch command :
![image](https://user-images.githubusercontent.com/54015848/97005524-311b9d80-155c-11eb-86c2-0fe827d12742.png)

I am using BLT 11.6.0 (Issue was present on v 11.5.0 as well).

**To Reproduce**
Push git branch to repository.

**Detailed error output**
See log:
`gaurav.manerkar@AMAFVFRJ1WKLE dep % git push  origin test/CMS-3464
Executing .git/hooks/pre-push...
[warning] Drupal VM is locally initialized, but is not running.
> validate
> tests:composer:validate
Validating composer.json and composer.lock...
[ExecStack] composer validate --no-check-all --ansi
[ExecStack] Running composer validate --no-check-all --ansi in /Users/gaurav.manerkar/Desktop/dep
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
[ExecStack] Done in 3.387s
> tests:php:lint
Linting PHP files...
Iterating over fileset files.php.custom.modules...
Iterating over fileset files.php.custom.themes...
Iterating over fileset files.php.tests...
> tests:phpcs:sniff:all
[ExecStack] '/Users/gaurav.manerkar/Desktop/dep/vendor/bin/phpcs'
............................................................   60 / 1713 (4%)
............................................................  120 / 1713 (7%)
............................................................  180 / 1713 (11%)
............................................................  240 / 1713 (14%)
............................................................  300 / 1713 (18%)
............................................................  360 / 1713 (21%)
............................................................  420 / 1713 (25%)
............................................................  480 / 1713 (28%)
............................................................  540 / 1713 (32%)
............................................................  600 / 1713 (35%)
............................................................  660 / 1713 (39%)
............................................................  720 / 1713 (42%)
............................................................  780 / 1713 (46%)
............................................................  840 / 1713 (49%)
............................................................  900 / 1713 (53%)
............................................................  960 / 1713 (56%)
............................................................ 1020 / 1713 (60%)
............................................................ 1080 / 1713 (63%)
............................................................ 1140 / 1713 (67%)
............................................................ 1200 / 1713 (70%)
............................................................ 1260 / 1713 (74%)
............................................................ 1320 / 1713 (77%)
............................................................ 1380 / 1713 (81%)
............................................................ 1440 / 1713 (84%)
............................................................ 1500 / 1713 (88%)
............................................................ 1560 / 1713 (91%)
............................................................ 1620 / 1713 (95%)
............................................................ 1680 / 1713 (98%)
.................................                            1713 / 1713 (100%)

Time: 51.57 secs; Memory: 38MB

> tests:yaml:lint:all
Validating yaml syntax for all custom modules and exported config...
Iterating over fileset files.yaml...
PHP Warning:  include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/process/Exception/RuntimeException.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/process/Exception/RuntimeException.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/process/Exception/RuntimeException.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/process/Exception/RuntimeException.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Event/ConsoleErrorEvent.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Event/ConsoleErrorEvent.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/console/Event/ConsoleErrorEvent.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/console/Event/ConsoleErrorEvent.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Event/ConsoleErrorEvent.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Event/ConsoleErrorEvent.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/console/Event/ConsoleErrorEvent.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/console/Event/ConsoleErrorEvent.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Event/ConsoleErrorEvent.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(/Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Event/ConsoleErrorEvent.php): failed to open stream: Too many open files in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/console/Event/ConsoleErrorEvent.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening '/Users/gaurav.manerkar/Desktop/dep/vendor/composer/../symfony/console/Event/ConsoleErrorEvent.php' for inclusion (include_path='/Users/gaurav.manerkar/Desktop/dep/vendor/pear/archive_tar:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/console_getopt:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear-core-minimal/src:/Users/gaurav.manerkar/Desktop/dep/vendor/pear/pear_exception:.:/usr/local/Cellar/php@7.3/7.3.21/share/php@7.3/pear') in /Users/gaurav.manerkar/Desktop/dep/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Event\ConsoleErrorEvent' not found in /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php:1027
Stack trace:
#0 /Users/gaurav.manerkar/Desktop/dep/vendor/acquia/blt/src/Robo/Application.php(31): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php(255): Acquia\Blt\Robo\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/gaurav.ma in /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php on line 1027

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Event\ConsoleErrorEvent' not found in /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php:1027
Stack trace:
#0 /Users/gaurav.manerkar/Desktop/dep/vendor/acquia/blt/src/Robo/Application.php(31): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php(255): Acquia\Blt\Robo\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/gaurav.ma in /Users/gaurav.manerkar/Desktop/dep/vendor/symfony/console/Application.php on line 1027
error: failed to push some refs to 'github.com:ixdep/dep.git'
`

**Expected behavior**
Errors and warnings should not be thrown.

**System information**
* Operating system version: Drupal 8.9.7
* BLT version: 11.6.0

**Comment by danepowell** [comment]
You need to increase your system file limit. Does this help? https://support.acquia.com/hc/en-us/articles/360058226793--Too-many-open-files-OS-error

**Comment by manerkargaurav** [comment]
Thanks

**Comment by danepowell** [comment]
Sounds like this is fixed, let me know if you have any other feedback.
