### ISSUE TITLE
[error]  Command "tests:drupal" is not defined with BLT 12.3.0

### ISSUE THREAD

**Issue by ashishdalvi** [acquia/blt#4268]
`blt tests` return command not found error on `blt tests:drupal`. 
- File: `/scripts/travis/run_tests`
- Line no: 10

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project:12.x-dev --no-interaction`
2. execute `blt tests`
3. 
```
vagrant@local:/var/www/aaa$ blt tests
> tests:frontend
> tests:server
> tests:security-drupal
[Acquia\Blt\Robo\Tasks\DrushTask] Running /var/www/aaa/vendor/bin/drush @self pm:security --no-interaction --ansi in /var/www/aaa/docroot
 [success] There are no outstanding security updates for Drupal projects.
[Acquia\Blt\Robo\Tasks\DrushTask] Done in 0.991s
There are no outstanding security updates for Drupal projects.
> tests:security-composer
[ExecStack] /var/www/aaa/vendor/bin/security-checker security:check composer.lock
[ExecStack] Running /var/www/aaa/vendor/bin/security-checker security:check composer.lock in /var/www/aaa
Symfony Security Check Report
=============================

No packages have known vulnerabilities.


[ExecStack] Done in 1.364s
There are no outstanding security updates for your composer packages.
[error]  Command "tests:drupal" is not defined.

Did you mean one of these?
    deploy:drupal:install
    recipes:drupalvm:destroy
    recipes:drupalvm:init
    setup:drupal:install
    tests
    tests:deprecated:modules
    tests:deprecated:themes
    tests:drupal:run
    tests:frontend
    tests:frontend:run
    tests:phpunit
    tests:phpunit:run
    tests:security-composer
    tests:security-drupal
    tests:server:kill
    tests:server:start 
```

**Expected behavior**
blt test command should execute without any errors.

**BLT doctor output**
vagrant@local:/var/www/aaa$ blt doctor
+---------------------------+----------------------------------------------------+
| Property                  | Value                                              |
+---------------------------+----------------------------------------------------+
| %paths.%root              | /var/www/aaa/docroot                               |
| %paths.%site              | sites/default                                      |
| %paths.%modules           | sites/all/modules                                  |
| %paths.%themes            | sites/all/themes                                   |
| %paths.%config-dx8_sync   | /var/www/aaa/config/default                        |
| %paths.%config-sync       | /var/www/aaa/config/default                        |
| %paths.%files             | sites/default/files                                |
| %paths.%temp              | /tmp                                               |
| %paths.%private           | /var/www/aaa/files-private/default                 |
| admin-theme               | seven                                              |
| alias-searchpaths.0       | /var/www/aaa/drush/sites                           |
| base-profile              | lightning                                          |
| blt-version               | 12.3.0                                             |
| bootstrap                 | Successful                                         |
| composer-version          | Composer version 1.10.15 2020-10-13 15:59:09       |
| config-sync               | /var/www/aaa/config/default                        |
| db-driver                 | mysql                                              |
| db-hostname               | localhost                                          |
| db-name                   | drupal                                             |
| db-password               | drupal                                             |
| db-port                   | 3306                                               |
| db-status                 | Connected                                          |
| db-username               | drupal                                             |
| drupal-settings-file      | sites/default/settings.php                         |
| drupal-version            | 9.0.7                                              |
| drush-alias-files.0       | /var/www/aaa/drush/sites/madewithnestle.site.yml   |
| drush-cache-directory     | /home/vagrant/.drush/cache                         |
| drush-conf.0              | /var/www/aaa/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/aaa/drush/drush.yml                       |
| drush-conf.2              | /var/www/aaa/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/aaa/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                               |
| drush-version             | 10.3.5                                             |
| files                     | sites/default/files                                |
| install-profile           | custom_lightning                                          |
| modules                   | sites/all/modules                                  |
| php-bin                   | /usr/bin/php7.3                                    |
| php-conf.0                | /etc/php/7.3/cli/php.ini                           |
| php-os                    | Linux                                              |
| private                   | /var/www/aaa/files-private/default                 |
| root                      | /var/www/aaa/docroot                               |
| site                      | sites/default                                      |
| stacks.drupal-vm.inited   | true                                               |
| stacks.dev-desktop.inited | false                                              |
| temp                      | /tmp                                               |
| theme                     | cohesion_theme                                     |
| themes                    | sites/all/themes                                   |
| uri                       | http://local.blted10.com  

**System information**
* Operating system type: Ubuntu
* Operating system version: 16.04.6 LTS
* BLT version: 12.3.0

**Comment by yyss8** [comment]
I'm seeing this error as well.

**Comment by yyss8** [comment]
PR created 
https://github.com/acquia/blt-drupal-test/pull/1

If you use `cweagans/composer-patches`, you can apply the PR as patch by adding 
```
"acquia/blt-drupal-test": {
                "Command \"tests:drupal\" is not defined with BLT 12.3.0": "https://github.com/acquia/blt-drupal-test/pull/1.patch"
}
```
to your `composer.json` file

**Comment by ashishdalvi** [comment]
Thank you so much for quick support. But it seems `blt tests:deprecated` command is not available in BLT 12. I will raise a new ticket for the same.

**Comment by danepowell** [comment]
Please don't raise a ticket, it will be closed. Removing the deprecation command was intentional due to the instability of the underlying packages, and the fact that BLT 12 is only for Drupal 9 so it doesn't really make sense to test for deprecations (at least until the next major release).
