### ISSUE TITLE
Use bionic dist for travis  11.x blt version

### ISSUE THREAD

**Issue by manerkargaurav** [acquia/blt#4282]
Currently the default php version in .travis.yml is php7.2
Php7.2 is already EOL.

Update .travis.yml file with php7.3 and. change dist from xenial to bionic.

**System information**
* Operating system version: Drupal 8.9.8
* BLT version: 11.6.0

**Comment by manerkargaurav** [comment]
Hi @danepowell 
Please do apply this change to 11.x branch as well.
Thanks

**Comment by danepowell** [comment]
It's already been backported: https://github.com/acquia/blt/pull/4284
