### ISSUE TITLE
New cweagans/composer-patches breaks build during CI

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#4286]
**Describe the bug**
I started to get error builds during the build process on both `travis` and `acquia-pipelines`. After further investigation it seems to be related to the new release `cweagans/composer-patches` which seems to have some `composer 2` related changes. I fixed it by downgrading to `1.7.4`

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Upgrade `cweagans/composer-patches` to `1.7.5`
2. commit changes
3. run build

**Expected behavior**
New build should finish without errors.

**Detailed error output**
`[Acquia\Blt\Robo\Tasks\DrushTask] Exit code 1 Time 03:44 [error] Failed to install Drupal!`

**System information**
* Operating system type: linux
* Operating system version: [replace]
* BLT version: 11.6.0

**Additional context**

**Comment by danepowell** [comment]
I think this will depend on your project dependencies and whether they are compatible with Composer 2. I'm able to build projects with BLT 11 and 12 in Travis CI and Pipelines without issue.

Can you provide more comprehensive logs? The error you posted isn't very revealing. I'm guessing if you poke through your build logs, you'll find deprecation errors from Composer.

As an immediate workaround, you could switch back to Composer 1 in your builds.

**Comment by danepowell** [comment]
Also I'm not really sure what you're referring to in regards to the Composer Patches version, the latest version is 1.7.0. There's no such thing as 1.7.5: https://github.com/cweagans/composer-patches/releases

**Comment by jedgar1mx** [comment]
I agree that this probably is cause by some other dependencies within my project. Not really sure where I got the release version. 🤔

**Comment by danepowell** [comment]
> Which is confusing since the github repo only shows 1.7.0. No issues with the new version but just found it interesting

I don't see how that's possible. Not only are those versions not in Github, [they aren't in Packagist](https://packagist.org/packages/cweagans/composer-patches). You can't download a package version that doesn't exist in Packagist 😄 

Are you sure you aren't using a custom repo, version alias, or fork?

**Comment by jedgar1mx** [comment]
I'm pretty sure i'm not but no I don't know what to believe 🙃
