### ISSUE TITLE
Command "tests:deprecated" is not defined with BLT 12.3.0

### ISSUE THREAD

**Issue by ashishdalvi** [acquia/blt#4288]
`blt tests` return command not found an error on `blt tests:deprecated`. 
- File: `/scripts/travis/run_tests`
- Line no: 10

**To Reproduce**
Steps to reproduce the behaviour, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project:12.x-dev --no-interaction`
2. execute `blt tests`

```
vagrant@local:/var/www/aaa$ blt tests     
> tests:frontend
> tests:server
[warning] The tests:security-drupal command is disabled.
[warning] The tests:security-composer command is disabled.
>>> tests:drupal
> tests:drupal:phpunit:run
[Robo\Common\ProcessExecutor] Running 'google-chrome' --headless --disable-web-security --remote-debugging-port=9222  http://localhost in /var/www/aaa
>>> tests:phpunit
[error]  Command "tests:deprecated" is not defined.
```

**Expected behaviour**
blt test command should execute without any errors.

**BLT doctor output**
vagrant@local:/var/www/aaa$ blt doctor
+---------------------------+----------------------------------------------------+
| Property                  | Value                                              |
+---------------------------+----------------------------------------------------+
| %paths.%root              | /var/www/aaa/docroot                               |
| %paths.%site              | sites/default                                      |
| %paths.%modules           | sites/all/modules                                  |
| %paths.%themes            | sites/all/themes                                   |
| %paths.%config-dx8_sync   | /var/www/aaa/config/default                        |
| %paths.%config-sync       | /var/www/aaa/config/default                        |
| %paths.%files             | sites/default/files                                |
| %paths.%temp              | /tmp                                               |
| %paths.%private           | /var/www/aaa/files-private/default                 |
| admin-theme               | seven                                              |
| alias-searchpaths.0       | /var/www/aaa/drush/sites                           |
| base-profile              | lightning                                          |
| blt-version               | 12.3.0                                             |
| bootstrap                 | Successful                                         |
| composer-version          | Composer version 1.10.15 2020-10-13 15:59:09       |
| config-sync               | /var/www/aaa/config/default                        |
| db-driver                 | mysql                                              |
| db-hostname               | localhost                                          |
| db-name                   | drupal                                             |
| db-password               | drupal                                             |
| db-port                   | 3306                                               |
| db-status                 | Connected                                          |
| db-username               | drupal                                             |
| drupal-settings-file      | sites/default/settings.php                         |
| drupal-version            | 9.0.7                                              |
| drush-alias-files.0       | /var/www/aaa/drush/sites/aaa.site.yml   |
| drush-cache-directory     | /home/vagrant/.drush/cache                         |
| drush-conf.0              | /var/www/aaa/vendor/drush/drush/drush.yml          |
| drush-conf.1              | /var/www/aaa/drush/drush.yml                       |
| drush-conf.2              | /var/www/aaa/docroot/sites/default/local.drush.yml |
| drush-script              | /var/www/aaa/vendor/drush/drush/drush              |
| drush-temp                | /tmp                                               |
| drush-version             | 10.3.5                                             |
| files                     | sites/default/files                                |
| install-profile           | custom_lightning                                          |
| modules                   | sites/all/modules                                  |
| php-bin                   | /usr/bin/php7.3                                    |
| php-conf.0                | /etc/php/7.3/cli/php.ini                           |
| php-os                    | Linux                                              |
| private                   | /var/www/aaa/files-private/default                 |
| root                      | /var/www/aaa/docroot                               |
| site                      | sites/default                                      |
| stacks.drupal-vm.inited   | true                                               |
| stacks.dev-desktop.inited | false                                              |
| temp                      | /tmp                                               |
| theme                     | cohesion_theme                                     |
| themes                    | sites/all/themes                                   |
| uri                       | http://local.blted10.com  

**System information**
* Operating system type: Ubuntu
* Operating system version: 16.04.6 LTS
* BLT version: 12.3.0

**Comment by danepowell** [comment]
BLT Project is deprecated in BLT 12. You should be using the acquia/drupal-recommended-project template instead, as documented in the links at the [bottom of the install docs](https://docs.acquia.com/blt/install/).

I deleted the BLT Project 12.x releases to try to prevent further confusion. Where were you instructed to use BLT Project? Perhaps documentation needs to be fixed somewhere?

I suspect this will fix the issue. I don't see how you could get this behavior otherwise, since there's no reference to `tests:deprecated` anywhere in the BLT 12 codebase.

**Comment by wilfi** [comment]
So I had trouble running `tests:deprecated:modules` and `tests:deprecated:themes` on 11.x specially on versions >11.4 (11.6 and 11.7) , but then I realised BLT had removed drupal-check integration #4253 
But somehow this PR - https://github.com/acquia/blt/pull/4254/files missed out to remove 
`deprecation:`
    `modules: true`
    `themes: true`
from config.yml
