### ISSUE TITLE
[Blt-12] Issue on deploying artifact to cloud as deploy directory contains .git file

### ISSUE THREAD

**Issue by joshirohit100** [acquia/blt#4304]
I am using vanilla https://github.com/acquia/drupal-recommended-project.
My app has fresh blt-12 and Drupal-9

I am trying to deploy artifact to cloud via travis and got the error -
```
Branch is set to develop-build.
Preparing artifact directory...
[error]  Failed to remove directory "/tmp/blt-deploy/.git": rmdir(/tmp/blt-deploy/.git): Directory not empty 
2.026s total time elapsed.
```

While checking, it seems because of `DeployCommand::sanitize()` -
```
$this->logger->info('Find VCS directories...');
    $vcsFinder = Finder::create()
      ->ignoreDotFiles(FALSE)
      ->ignoreVCS(FALSE)
      ->directories()
      ->in([$this->deployDocroot,
        "{$this->deployDir}/vendor",
      ])
      ->name('.git');
```
and here we don;t considering the deploy directory VCS

**Comment by danepowell** [comment]
I cannot reproduce this using a stock .travis.yml. What is your .travis.yml?

I don't think the error is coming from the sanitize function, it's coming from https://github.com/acquia/blt/blob/66c296b7afed563789af91d08d37edfae06e863c/src/Robo/Commands/Artifact/DeployCommand.php#L325

This doesn't make sense for two reasons though:
- Nothing should have created /tmp/blt-deploy/.git before BLT runs, unless you are caching it in Travis?
- Even if the directory exists, Symfony FS should be able to delete it unless you've created a race condition, such as by running two deploys simultaneously

**Comment by joshirohit100** [comment]
You are correct. It could be race conditions as now it's working fine after multiple attempts without any change. So closing this.
