### ISSUE TITLE
Command parameters that start with config values interpreted as set parameters

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#4325]
**Describe the bug**
When specifying command parameters, if the parameter starts with a BLT config value, that config value is interpreted as being set.

**To Reproduce**
1. Run `blt sync --site siteone.com`
2. See that the `--uri` option used in Drush is set to one.com instead of siteone.com
3. This would error if that site did not exist or sync the wrong site if it did.

This specific example can be worked around by using an equals sign (`--site=siteone.com`) or by wrapping it in quotes (`--site "siteone.com"`). However, in other situations this doesn't work. For example, say you have a custom BLT command that takes an argument. Passing an argument like `blt my:command environmentalsciences.edu` will set the `environment` option in ConfigInitializer and I'm not sure how to escape it.

**Expected behavior**
I would expect BLT config values to only be set when only that config value is passed via a parameter and not when it is included as part of another word.

**System information**
DrupalVM

* Operating system type: Ubuntu
* Operating system version: 18.04
* BLT version: 11.6.0

**Additional context**
Maybe this is expected behavior and just a documentation issue on clearly stating how to escape arguments/options. Apologies if I missed such documentation.

**Comment by danepowell** [comment]
Alright, I think I nailed this, would you mind helping to test? https://github.com/acquia/blt/pull/4340

I'm pretty nervous because this modifies bootstrap code that's pretty complex and already caused some grief lately. But a fair amount of hammering hasn't revealed any regressions.

**Comment by richardbporter** [comment]
Sorry for not getting back to this sooner - we were not on BLT 12 yet. I just tested this with 12.8.0 and it works great. 👍🏻
