### ISSUE TITLE
Issues with disable-targets security updates

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#4335]
**Describe the bug**
I started getting errors related to security-updates during build.
`[error]  Command `tests:security:check:composer ` exited with code 1.`

It seems that the command changed from:
`disable-targets.tests.security.check.updates` to `disable-targets.tests.security.check.composer`

Hope this helps someone 👍.

**Comment by baikho** [comment]
We also got this with the following output:

```
The web service failed for an unknown reason (HTTP 403).
```

But rather than disabling security checks, we updated to release 11.7.0 and ran `rm -rf vendor` to get the executable refreshed.

**Comment by mikemadison13** [comment]
Yeah I think this is fixed as of 12.7 and 11.7 releases. If you are still on an older version of BLT and/or unable to upgrade, then you'll likely have to disable the security tests as outlined in this issue until you're able to upgrade.

**Comment by mikemadison13** [comment]
see 
11.x https://github.com/acquia/blt/pull/4332
12.x https://github.com/acquia/blt/pull/4329
