### ISSUE TITLE
Uncommitted changes on the source repository 

### ISSUE THREAD

**Issue by jedgar1mx** [acquia/blt#4345]
**I want to...**
I'm trying to deploy my latest changes using `pipelines` and I'm getting this error
`[error]  There are uncommitted changes on the source repository (listed above). Commit, stash, or remove these changes before deploying, or use the --ignore-dirty flag. `

I double check the repo and there is not uncommitted changes on the repo 

It mentions `--ignore-dirty` tag, where would I apply that for using it on acquia-pipelines?

**BLT doctor output**
| Property                  | Value                                         |
+---------------------------+-----------------------------------------------+
| %paths.%root              | /app/docroot                                  |
| %paths.%site              | sites/default                                 |
| %paths.%modules           | sites/all/modules                             |
| %paths.%themes            | sites/all/themes                              |
| %paths.%config-sync       | /app/config/default                           |
| %paths.%files             | sites/default/files                           |
| %paths.%temp              | /tmp                                          |
| %paths.%private           | /app/files-private                            |
| admin-theme               | admin_detroitmi                               |
| alias-searchpaths.0       | /app/drush/sites                              |
| blt-version               | 11.7.0                                        |
| bootstrap                 | Successful                                    |
| composer-version          | Composer version 2.0.9 2021-01-27 16:09:27    |
| config-sync               | /app/config/default                           |
| db-driver                 | mysql                                         |
| db-hostname               | database                                      |
| db-name                   | drupal8                                       |
| db-password               | drupal8                                       |
| db-port                   | 3306                                          |
| db-status                 | Connected                                     |
| db-username               | drupal8                                       |
| drupal-settings-file      | sites/default/settings.php                    |
| drupal-version            | 8.9.13                                        |
| drush-alias-files.0       | /app/drush/sites/default.site.yml             |
| drush-alias-files.1       | /app/drush/sites/detroitatwork.site.yml       |
| drush-alias-files.2       | /app/drush/sites/detroitmi.localhost.site.yml |
| drush-alias-files.3       | /app/drush/sites/detroitmi.site.yml           |
| drush-alias-files.4       | /app/drush/sites/intranet.site.yml            |
| drush-alias-files.5       | /app/drush/sites/stormwater.site.yml          |
| drush-alias-files.6       | /app/drush/sites/the-neighborhoods.site.yml   |
| drush-alias-files.7       | /app/drush/sites/training.detroitmi.site.yml  |
| drush-cache-directory     | /var/www/.drush/cache                         |
| drush-conf.0              | /app/vendor/drush/drush/drush.yml             |
| drush-conf.1              | /app/drush/drush.yml                          |
| drush-script              | /app/vendor/drush/drush/drush                 |
| drush-temp                | /tmp                                          |
| drush-version             | 10.3.6                                        |
| files                     | sites/default/files                           |
| install-profile           | varbase                                       |
| modules                   | sites/all/modules                             |
| php-bin                   | /usr/local/bin/php                            |
| php-conf.1                | false                                         |
| php-os                    | Linux                                         |
| private                   | /app/files-private                            |
| root                      | /app/docroot                                  |
| site                      | sites/default                                 |
| stacks.drupal-vm.inited   | false                                         |
| stacks.dev-desktop.inited | false                                         |
| temp                      | /tmp                                          |
| theme                     | detroitmi                                     |
| themes                    | sites/all/themes                              |
| uri                       | http://default                                |

**System information**
* Operating system type: Mac
* Operating system version: 11.2
* BLT version: 11.7.0

**Comment by danepowell** [comment]
Something in your build and test script is modifying the files in your Git repo, which is a bad sign. Usually it's something benign like log output from the tests (in which case you should gitignore them) but it could be something more dangerous, which would lead to untested code getting deployed, which is why this check exists.

Can you post the log output leading up to this error? IIRC BLT attempts to print a list of the changed files so you can see what they are. Otherwise you could add your own `git diff` and/or `git status` to acquia-pipelines.yml between the `tests` and `build-artifact` steps.

**Comment by jedgar1mx** [comment]
I think I found the culprit. It seems to be related to `wikimedia/composer-merge-plugin` which is used by `webform` to load libraries. If I remove it from the `composer` file the build successfully deploys.

**Comment by jedgar1mx** [comment]
It seems this recent merge is the cause https://github.com/wikimedia/composer-merge-plugin/pull/189

**Comment by danepowell** [comment]
Interesting, glad you found a cause. I recommend against using composer-merge-plugin unless you have a super specific need for it, not because it's a bad project or anything but just because it can lead to so many unexpected edge cases like this. Composer wasn't built to have dependencies "sideloaded" like this, and weird things happen as a result. BLT used composer-merge-plugin up to version 10, and then removed it for these reasons.

**Comment by jedgar1mx** [comment]
Yeah, I think I will remove it completely and just handle the webform libraries manually on my composer file. Thanks
