### ISSUE TITLE
"Do you want to help us make this tool even better? (y/n) " makes builds to stop waiting for an answer. BLT 12.7.0.0

### ISSUE THREAD

**Issue by mayelaatf** [acquia/blt#4349]
**Describe the bug**
Travis-ci builds stop with the message Do you want to help us make this tool even better? (y/n) 

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Push code to github repo, Travis starts creating the build

**Expected behavior**
Build pass

**System information**
* Operating system type:  [BLT default Travis-CI dist: xenial]
* BLT version: BLT 12.7.0.0

**Additional context**

**Comment by shelane** [comment]
I had the same issue #3976 

Various approaches were discussed there.

**Comment by mayelaatf** [comment]
Thanks @shelane, I did the following steps: 
- Make a copy of the run_tests file and save it in your project /scripts/travis/ directory
- Add `blt blt:telemetry:disable --no-interaction`  to the run_tests file 
- Change the path to the run_tests file  in travis.yml ` - source ${TRAVIS_BUILD_DIR}/scripts/travis/run_tests`
The above steps fixed the issue for me

**Comment by mikemadison13** [comment]
is this still an issue?
