### ISSUE TITLE
schema version

### ISSUE THREAD

**Issue by shelane** [acquia/blt#4350]
**Describe the bug**
This is not a "functional" bug but something that is occurring that should not be.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project --no-interaction`
2. Run `blt setup`
4. See `blt/.schema_version` file created with value `11004000`

**Expected behavior**
If this file is not necessary any more, it shouldn't be created. If it is necessary or there for informational purposes, it should have the correct version number. As this is done at the time of 12.7.0, I would expect the value to be `12007000`.

**Comment by danepowell** [comment]
There have not been any schema updates since 11.4.0, hence this is the "current" schema version. I don't think there's any bug here.

https://github.com/acquia/blt/blob/main/src/Update/Updates.php

**Comment by shelane** [comment]
Gotcha. I mistook what that file was supposed to be then.
