### ISSUE TITLE
Enable hooks support all stacks on site install

### ISSUE THREAD

**Issue by shashwatpurav-qed42** [acquia/blt#4352]
Environments with multiple stacks e.g. 01dev, 02dev......08dev should have a common configurations for enabling and uninstalling the modules while installation.

Rewrite toggleModules method from ToggleModulesCommand class to have a common environments for multiple stacks to enable and uninstall modules while installation. E.g. for multiple stacks such as 01dev, 02dev......08dev should have common environment such as dev under modules key in blt.yml
1. This will save lines of code
2. Easier to maintain
3. Fallback mechanism wherein if any specific stack isn't mentioned in the blt.yml file, default environment can be used

**Comment by danepowell** [comment]
Thanks for the PR. Unfortunately the Toggle Modules command was removed in BLT 13, so I don't think this PR or issue is relevant any longer. The community has contributed a toggle-modules plugin you might want to try: https://github.com/shelane/toggle-modules
