### ISSUE TITLE
Support for composer1 on Cloud IDE

### ISSUE THREAD

**Issue by fiasco** [acquia/blt#4354]
**Is your feature request related to a problem? Please describe.**
Cloud IDE comes with composer 2 by default but still has composer 1 accessible by calling composer1 (instead of composer). This means customers tied to composer1 can't use BLT to run a composer install.

**Describe the solution you'd like**
Perhaps build.yml should have a config for the location to composer so users can override that in blt.yml?

**Describe alternatives you've considered**
Patched BLT locally

**Comment by mikemadison13** [comment]
I think that having a way to configure the composer binary location makes a ton of sense (or at least the composer binary name) given how varied some systems are (composer1, composer2, composer, etc.). This is particularly challenging on cloud managed systems (like Cloud IDEs and CI tools) that you don't have control over.

**Comment by joz-d7** [comment]
The workaround is to the following:
1) Move up one directory before the "project" folder and create a folder like `custom-bin`
2) Download and install composer as stated here https://getcomposer.org/download/
3) Rename composer.phar to composer
4) Run "export PATH=/home/ide/custom-bin:$PATH"
5) If this needs to be more permanent change, add the command in step 4 into the ".bash_profile"

**Comment by danepowell** [comment]
Sorry, Composer 1 is EOL and there shouldn't be any reason at this point not to upgrade to Composer 2. I don't think it's worth the additional complexity to support it.

BLT uses the global version of every binary it relies on (except Drush), it would set a bad precedent to start supporting custom locations for every one.

Rather, this should be handled at the Shell level by setting an alias or adjusting the PATH prior to calling BLT.
