### ISSUE TITLE
Is there a post "blt sync" hook or way to hook on local only?

### ISSUE THREAD

**Issue by justclint** [acquia/blt#4356]
**I want to...**
I want to update a users password on local after `blt sync` completes. Use case is since the db user data gets scrubbed, I specifically want to update a "Consumer" user with a generic password so dev's can use same postman config for local api testing.

Im familiar with the command hooks https://docs.acquia.com/blt/extending-blt/#pre-and-post-command-hooks and `post-config-import` would work but I only want to run this on local, not on any remote envs. 

If no such hook exist, what would be the best approach?

**System information**
* Operating system type: os x
* Operating system version: 11.2.2
* BLT version: 11.7

Thanks!

**Comment by mikemadison13** [comment]
you could do a post-command hook, and then use the environment detector to confirm that you're local before you actually execute. that would be my recommendation, probably something like:

```
@hook post-command <whatever hook>
```

i've used drupal:config:import to run at the end of `blt sync` in the past.

**Comment by justclint** [comment]
Thanks @mikemadison13 ! That just pointed me in the right direction. Dont now why I didnt realize sooner but was just able to add the command-hooks to local.blt.yml
