### ISSUE TITLE
Acquia Pipeline - HTTP Status 400: Failed to sync databases

### ISSUE THREAD

**Issue by dhinakaran60** [acquia/blt#4367]
On acquia pipeline we are trying sync dev db to pipeline but we are getting the below error.

Can you please help on this ? are we missing any configuration or code

pipelines-sync-dbs catportaldev drupal
SyncDbs error: Unexpected HTTP Status 400: Failed to sync databases for app 4427b2a0-2ad6-476d-9aab-9cc438737870: Error message: {"database"=>"The database does not exist in this environment."}
Debug code: v-2940ddf8-857a-11eb-b3dd-22000b2996e0, v-2940ddf8-857a-11eb-b3dd-22000b2996e0

version: 1.2.0
services:
  - mysql
  - php:
      version: 7.4

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    #BLT_DIR: $SOURCE_DIR/vendor/acquia/blt
cde-databases:
  - dev
  - drupal
events:

  post-deploy:
    steps:
      - deploy:
          script:
            - pipelines-deploy
            # Uncomment this line and replace DB_NAME to sync a db on deploys.
            # @see https://docs.acquia.com/acquia-cloud/develop/pipelines/databases/
            - pipelines-sync-dbs sitedev drupal

**Comment by kevin-johne** [comment]
hi @dhinakaran60 I have the same problem and cant find a clear answer what keys to use for cde-databases. What was your solution?
