### ISSUE TITLE
Run Acquia BLT Behat tests on Acquia dev/stg/prod environments

### ISSUE THREAD

**Issue by bsuttis** [acquia/blt#4368]
**I want to...**
Run Acquia BLT Behat tests on Acquia dev/stg/prod environments

**It's not working because...**
@javascript scenarios require ChromeDriver or Selenium2Driver

**System information**
* Operating system type: MacOS
* Operating system version: 10.15.1
* BLT version: 12.8.2.0

**More details...**
I've got Acquia BLT set up and working locally within Docksal but I'm curious as to how Behat tests are supposed to work when deployed to Acquia Cloud dev, staging, and production environments.

I've chosen to use the DMore extension (DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension) instead of Selenium for @javascript scenarios. Locally it works via a Docksal service (when the project is using Docksal) or running headless Google Chrome on port 9222 (when the project is not using Docksal) but how is this supposed to be configured on the web server?

Say I ssh into dev, `cd` to the `tests/behat` directory and run `bin/behat features/myfeature.feature`, any @javascript scenario fails with:
"Could not fetch version information from http://127.0.0.1:9222/json/version. Please check if Chrome is running. Please see docs/troubleshooting.md if Chrome crashed unexpected. (RuntimeException)"

The error makes sense because Chrome isn't running on the web server like I have it running locally. What am I misunderstanding here? Is it considered bad practice to run these tests on the actual hosting environment?

**Comment by mikemadison13** [comment]
Typically, the goal would be to run the Behat (and other tests) during a CI run (e.g. Acquia Pipelines). Tests run during CI. If they pass, then you can do a deployment of that code into the Acquia Cloud. At that point, you wouldn't "need" to run tests in the cloud because the code going to the cloud has already passed all of your testing. 

I honestly am not sure you'd be able to run Behat in the cloud given that, to your point, you'd have to install the Chrome Driver (and potentially other things) to make it work. I would recommend local (as you're doing) and CI environments as the most appropriate places to run any/all automated tests!

**Comment by bsuttis** [comment]
Thanks for the clarification. 

My current project has CI implemented via Bitbucket where:
- push commit to Bitbucket repo
- pipeline builds
- deploys code to Acquia repo
- updates run, config imports, cache rebuilds

Trying to run Behat in the pipeline causes a `Driver not specified for this database connection: default` error which I think makes sense since there's no database involved at this point. I just started looking at Acquia Pipelines and am wondering if it's something to leverage in addition to Bitbucket Pipelines... wondering if Acquia Pipelines would be the better place for tests to run.

**Comment by mikemadison13** [comment]
I haven't messed w/ Bitbucket Pipelines a ton, but I will say each CI tool has its own oddities when it comes to running servers and doing additional tasks during CI (I flailed pretty bad with Gitlab last year). I will say BLT more or less "just works" with Acquia Pipelines out of the box, although if you want to test content you may need to get a little fancy with a database sync (supported) or through use of a CI config split and the default content module (my personal recommendation). 

I think you'll find that tuning Bitbucket or Pipelines to do testing and automation drastically simpler than trying to do it in a hosting environment, and a hosting environment isn't really the right place to do that testing anyways.

Good luck!
