### ISSUE TITLE
local config values are not "read" after the file is generated and local.settings.php files created with default values

### ISSUE THREAD

**Issue by shelane** [acquia/blt#4369]
**Describe the bug**
With an existing `example.local.blt.yml` file, the config values are not

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project acquia/blt-project --no-interaction`
2. Create or edit the `blt/example.local.blt.yml` file with configuration for database settings. 
```
project:
  machine_name: BLTed
  human_name: 'BLTed 12'
  local:
    hostname: '${env.VIRTUAL_HOST}'
drupal:
  db:
    database: default
    username: user
    password: user
    host: db
    port: 3306
```
3. Ensure that the `sites/default/local.settings.php` file does not exist
4. The `sites/default/settings/default.local.settings.php` should have a database array that looks like:
```
$db_name = '${drupal.db.database}';
/**
 * Database configuration.
 */
$databases['default']['default'] = [
  'database' => $db_name,
  'username' => '${drupal.db.username}',
  'password' => '${drupal.db.password}',
  'host' => '${drupal.db.host}',
  'port' => '${drupal.db.port}',
  'driver' => 'mysql',
  'prefix' => '',
];
```
4. Run command `source:build:settings`

**Expected behavior**

**Detailed error output**
For a little extra debugging, add the following to the `SettingsCommand.php` file after line 58:
```
    $db = $this->getConfigValue('drupal.db');
    $this->logger->debug("Drupal database values are: ". implode(', ', $db));
``` 
Run command `source:build:settings`
Results:
```
blt blt:init:settings -vvv
[debug] Drupal VM is not initialized.
Hash salt already exists.
[debug] Multisites found: default
[debug] Initial site: default
[debug] Drupal database values are: default, user, user, db, 3306
[Filesystem\FilesystemStack] _chmod ["/var/www/docroot/sites/default",511]
[Filesystem\FilesystemStack] _chmod ["/var/www/docroot/sites/default/settings.php",511]
[File\Write] Writing to /var/www/docroot/sites/default/settings.php.
[Filesystem\FilesystemStack] _chmod ["/var/www/docroot/sites/default/settings.php",420]
0.506s total time elapsed.
```

If you re-run the command, the config values will be correct, but the local.settings.php file will already have the incorrect values in them. So it seems that the config values should be "re-read" after the call to `$this->generateLocalConfigFile();` or from within that function.

**System information**
* Operating system type: Linux
* Operating system version: (Docksal latest)
* BLT version: 12.8.2

**Comment by lpeabody** [comment]
I think the ask here is that, in the special event of `local.settings.php` being generated at the same time as `local.blt.yml` then BLT should re-read configuration from `local.blt.yml` _before_ generating `local.settings.php`?

@danepowell thoughts?

**Comment by danepowell** [comment]
Thanks for the PR, I was able to reproduce this following the steps you provided.
