### ISSUE TITLE
BLT is overriding reverse_proxy_addresses 

### ISSUE THREAD

**Issue by awm086** [acquia/blt#4384]
The `reverse_proxy_addresses` is being reset blt.settings.php. 
This in turns break breaks the ability to properly retrieve client ip by using `request_stack->getClientIP`.  
https://github.com/acquia/blt/blob/main/settings/blt.settings.php#L41

Maybe we should check if it's already set.

**Comment by awm086** [comment]
I wonder if this is a bug or there is another blt specific settings using `$trusted_reverse_proxy_ips`. 
@danepowell, do you have any insight?

**Comment by danepowell** [comment]
I think those settings were added in https://github.com/acquia/blt/pull/3172

It's going to take some investigation to figure out why they were added, it's not clear from the PR. I do recall that there was an issue with how IPs were listed in the x-forwarded-for header at one point, I don't know if this code was intended to fix that.
