### ISSUE TITLE
Deploy script failing

### ISSUE THREAD

**Issue by manerkargaurav** [acquia/blt#4389]
**Describe the bug**
Hello, 

Simulate deploy script is creating issue for me. Its getting terminated. Please look at the error message.
![Screenshot 2021-08-12 at 5 35 49 PM](https://user-images.githubusercontent.com/54015848/129194102-0ceb0137-cf6a-4967-87d3-d980926ca985.png)

**To Reproduce**
Trigger build on travis

**Expected behaviour**
Build should pass without any errors

**Detailed error output**
![Screenshot 2021-08-12 at 5 35 49 PM](https://user-images.githubusercontent.com/54015848/129194188-db203349-c9f3-448f-b23d-340305449ffc.png)

**System information**
* Operating system type: Travis
* Operating system version: Drupal 8.9.17
* BLT version: 11.7.0

**Comment by justclint** [comment]
@manerkargaurav If I recall correctly, we were experiencing this as well. We run this now after `simulate_deploy` which solved for us.

```
  - source ${BLT_TRAVIS_DIR}/scripts/simulate_deploy
  - rm -rf /home/travis/build/org/repo/deploy
 ```

**Comment by mikemadison13** [comment]
Is this still an issue?
