### ISSUE TITLE
The following BLT updates failed

### ISSUE THREAD

**Issue by cobenash** [acquia/blt#4391]
**I want to...**
Describe specifically what you are trying to accomplish.

I want to upgrade the blt project from 11 to 13 and drupal core from D8 to D9.2.

**It's not working because...**
What's going wrong?

update process is failed.

>  - update_10000000: 10.x Updates.
> - update_10000001: Move Drupal modules to project composer.json.
> - update_10000002: Regenerate cloud hooks if necessary.
> - update_10001000: Remove composer autoload optimizations.
> - update_10003000: Regenerate acquia-pipelines.yml.
> - update_10004000: Migrate to acquia/memcache-settings.
> - update_11000000: Update blt-require-dev version.
> - update_11000001: Move Drupal Scaffold to project composer.json.
> - update_11000020: Update phpcs.xml.dist.
> - update_11002000: Update .gitignore with travis_wait.
> - update_11004000: Regenerate factory hooks from updated templates.
> Executing updates...
> -> update_10000000: 10.x Updates.

**Detailed error output**
If a BLT command is failing, run it again with the `-vvv` argument and post the full output here.

```
Warning: file_get_contents(/app/vendor/acquia/blt/subtree-splits/blt-project/composer.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Update/Updater.php on line 450
        PHP Warning:  file_get_contents(/app/vendor/acquia/blt/subtree-splits/blt-project/composer.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Update/Updater.php on line 450

        Warning: file_get_contents(/app/vendor/acquia/blt/subtree-splits/blt-require-dev/composer.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Update/Updates.php on line 47

        Notice: Trying to access array offset on value of type null in /app/vendor/acquia/blt/src/Update/Updates.php on line 48

        Warning: Invalid argument supplied for foreach() in /app/vendor/acquia/blt/src/Update/Updates.php on line 48
        PHP Warning:  file_get_contents(/app/vendor/acquia/blt/subtree-splits/blt-require-dev/composer.json): failed to open stream: No such file or directory in /app/vendor/acquia/blt/src/Update/Updates.php on line 47
        PHP Notice:  Trying to access array offset on value of type null in /app/vendor/acquia/blt/src/Update/Updates.php on line 48
        PHP Warning:  Invalid argument supplied for foreach() in /app/vendor/acquia/blt/src/Update/Updates.php on line 48

        Fatal error: Uncaught TypeError: Argument 2 passed to Acquia\Blt\Robo\Common\ArrayManipulator::arrayMergeRecursiveDistinct() must be of the type array, null given, called in /app/vendor/acquia/blt/src/Update/Updates.php on line 84 and defined in /app/vendor/acquia/blt/src/Robo/Common/ArrayManipulator.php:25

```

**BLT doctor output**
Post the full output of `blt doctor` in the failing environment here.

**System information**
* Operating system type: Ubuntu Linux
* Operating system version: 18.04
* BLT version: 13.0.1.0

**Comment by cobenash** [comment]
I've found the answer. Close the ticket.

**Comment by bhojwanipankaj05** [comment]
Hi @cobenash,
I am facing the same issue on Blt 12 and Drupal 8 to 9 update. Can you please share how you resolve this?

**Comment by bhojwanipankaj05** [comment]
> I've found the answer. Close the ticket.

Please share the answer.

**Comment by cobenash** [comment]
@bhojwanipankaj05 

I don't think it's the right way for you. 

I modified the file `blt/.schema_version` to prevent command to execute a bunch of codebase update.

Because I usually use composer to maintain my codebase directly.

Hope this could help you though.
