### ISSUE TITLE
Not Getting phpunit tests command under tests namespace of blt

### ISSUE THREAD

**Issue by kuntal15** [acquia/blt#4394]
**Describe the bug**
I have used acquia/drupal-recommended-project template to create a project.
Performed this on Acquia Cloud IDE.
When I am running blt, it is giving me the below commands under tests namespace:
tests:frontend:run                  
tests:security-composer             
tests:security-drupal               
tests:server:kill   

I can't see any commands available for phpunit or behat.
              

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer create-project --no-interaction acquia/drupal-recommended-project . `
2. Run blt

**Expected behavior**
I should get command related to phpunit.

**BLT doctor output**
+------------------------------------------+--------------------------------------------------------------+
| Check                                                                  | Problem                                                      |
+------------------------------------------+--------------------------------------------------------------+
| ConfigCheck:checkGitConfig                             | Git repositories are not defined in blt.yml.                 |
|                                                                            |   Add values for git.remotes to blt.yml to enabled automated |
|                                                                            | deployment.                                                  |
| FileSystemCheck:checkFileSystem:%private       | Private files directory does not exist.                      |
|                                                                            |                                                              |
|                                                                            | Create /mnt/files/.ide/sites/default/files-private.          |
|                                                                           | Installing Drupal will create this directory for you.        |
|                                                                           | Run `blt drupal:install` to install Drupal, or run `blt      |
|                                                                           | setup` to run the entire setup process.                      |
|                                                                           | Otherwise, run `mkdir -p                                     |
|                                                                           | /mnt/files/.ide/sites/default/files-private`.                |
|                                                                           |                                                              |
| NodeCheck:checkNodeVersionFileExists     | Neither .nvmrc nor .node-version file found in repo root.    |
| WebUriCheck:checkUriResponse                 | Did not get a response from http://local.my_blt_site.com     |
|                                                                      | Is your *AMP stack running?                                  |
|                                                                      | Is your /etc/hosts file correctly configured?                |
|                                                                      | Is your web server configured to serve this URI from         |
|                                                                      | /home/ide/project/docroot?                                   |
|                                                                      | Is options.uri set correctly in                              |
|                                                                      | /home/ide/project/docroot/sites/default/local.drush.yml?     |
+------------------------------------------+--------------------------------------------------------------+
**System information**
Acquia Cloud IDE
* BLT version: 12.8.2.0

**Comment by mikemadison13** [comment]
These have been split off into separate BLT plugins as of BLT 12. 

https://github.com/acquia/blt-behat for behat
https://github.com/acquia/blt-drupal-test for the drupal core phpunit tests

If you want stand alone phpunit, that feature has been removed as far as I know, but it should be pretty easy for you to re-add if needed (see https://github.com/acquia/blt/pull/4035 where it came out)

**Comment by lems3** [comment]
> These have been split off into separate BLT plugins as of BLT 12.
> 
> https://github.com/acquia/blt-behat for behat https://github.com/acquia/blt-drupal-test for the drupal core phpunit tests
> 
> If you want stand alone phpunit, that feature has been removed as far as I know, but it should be pretty easy for you to re-add if needed (see #4035 where it came out)

Should the recipe for phpunit be updated to reflect that change ?
