### ISSUE TITLE
Add default memory limits

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#440]
As most codebases mature they hit memory limits for admin users.  We should default the memory for admin paths and drush to 256/512mb and add this to one of the blt settings.php

https://docs.acquia.com/article/conditionally-increasing-memory-limits

**Comment by grasmash** [comment]
This seems good for D8 admin paths, but what about drush?

`if (isset($_SERVER['REQUEST_URI']) && strpos($_SERVER['REQUEST_URI'], '/admin/') === 0 ) { ini_set('memory_limit', '512M'); }`

**Comment by aweingarten** [comment]
This should do it
````
// Test if we are using drush (command-line interface)
  $cli = PHP_SAPI === 'cli';
````

**Comment by aweingarten** [comment]
Might even consider moving the cli clause in base settings so that is something we can reuse?

**Comment by steveworley** [comment]
I think we should think more about this requirement. Why are we setting Memory limit at the application? 

PHP (at least on Cloud) has a separate ini file for CLI usage which increases the memory available for Drush. Drush isn't the only tool that runs against the code base in CLI there are other things to consider like PHPUnit and PHPCS, so by making this readily available we could promote poor practices which could result in failing tests and other difficulties.

Another thing to note; when memory limit is overridden like that it sets the memory limit for the process pool so additional requests will use the memory limit override until the process respawns. Pretty sure this is a PHP-FPM thing, so we might wanna confirm with OPs. It could mean that the application has more allowed memory for places other than admin which could allow the application to behave unexpectedly.

I think memory tweaking needs more thinking about your applications state then a blanket provided as a default. Possibly a documentation task to outline how memory limits should be approached.

**Comment by aweingarten** [comment]
@steveworley: should this article then be removed or updated.  It's the guidance we have been giving for a while.
https://docs.acquia.com/article/conditionally-increasing-memory-limits

Anecdotally I have seen us use this sort of logic on all PS projects I've been on without issue.

**Comment by steveworley** [comment]
There are use cases where I can see that the ability to do this should be documented, namely these would come in the idea of cost saving as the way you should do it would typically incur additional hosting costs, you just need to be aware of the risks that it imposes.

There is a good article on [Drupal.org](https://www.drupal.org/docs/7/managing-site-performance-and-scalability/changing-php-memory-limits) that talks about scalability. Namely the correlation between memory and available processes, the more memory assigned to a single process reduces the concurrency of the web node which can lead to things like [skip-spawning](https://forums.acquia.com/acquia-products-and-services/acquia-cloud/troubleshooting-performance-issues).

I would argue that setting memory limits at run-time is a stop over until proper resource planning and performance analysis of the application can be done.

**Comment by grasmash** [comment]
I've been convinced by @steveworley. This does seem like a change that should be considered and implemented on a per-project basis.
