### ISSUE TITLE
Improved DX with DrupalVM

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#441]
The current BLT integration with DrupalVM presents a few challenges for developers, especially on projects with heterogeneous development environments (DrupalVM + DD + LAMP). For instance, running `vm:init` generates a drush alias that is specific to DrupalVM and when committed will break the local environment for any developers not using DrupalVM.

Generally, it seems like what we need is actually a unified dev environment manager, where you can basically tell BLT "use one of (a) DrupalVM, (b) DD, (c) LAMP" and it goes off and sets everything up for you.

To that end, I propose the following:

1. Have specific aliases for each of DrupalVM/DD/LAMP, and allow users to choose between them by simply setting the default alias in local.project.yml.
2. Split the`vm:init` target into two targets, one to be run once when a repository is first created (to create the common Vagrantfile and box directory and add DrupalVM as a dev dependency), and one to be run by each developer that actually wants to use DrupalVM locally (to configure the drush alias, set it as the default local alias, and check that various plugins such as hostsupdater are installed)
3. Find a way to integrate `vagrant up` into the setup targets if a local install is using DrupalVM. Right now you have to manually run `vagrant up` before running almost any other BLT command, and it's getting annoying.
4. At some point in the future, extend this for development stacks beyond DrupalVM.

**Comment by grasmash** [comment]
I like this proposal.

Having had to assist with a few local environment set ups today, there are a few manual steps that are still a little cumbersome:

1. Install VirtualBox
1. Install Vagrant
1. Install Composer

Though, I hesitate to automate these.

**Comment by danepowell** [comment]
Yeah, automating prerequisite installation may be tough. But at least checking for the prerequisites (like we do for composer, or the DrupalVM hostsupdater plugin) would be smart.

**Comment by danepowell** [comment]
Just saw your commits, those definitely seem to be in the right direction. I'll try to find some time to test them.
