### ISSUE TITLE
BLT config files in multisite directories not working

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#4428]
**Describe the bug**
It seems like `blt.yml` files in site directories are no longer working. The docs at https://docs.acquia.com/blt/extending-blt/#overriding-a-variable-value suggest that a blt.yml file in a site directory should override previous values.

**To Reproduce**
I tried to write steps to reproduce here but the issue template suggests creating a new project with `acquia/blt-project` which installs BLT 11. Getting that updated to BLT 13 is not clear. It is probably easier to reproduce in an existing project. If you have another site directory, say `foo`, which has a `drush.aliases.remote` setting of `foo.prod`, commands like `blt sync --site foo` don't seem to use that. 

**Expected behavior**
I would expect BLT config loading to work as outlined in https://docs.acquia.com/blt/extending-blt/#overriding-a-variable-value.

**Detailed error output**
No errors.

**BLT doctor output**
Again, creating a stock, BLT 13 project isn't clear. Happy to set one up if I can be pointed in the right direction.

**System information**
* Operating system type: NA
* Operating system version: NA
* BLT version: 13.2.0

**Comment by richardbporter** [comment]
I _think_ this stopped working between https://github.com/acquia/blt/compare/13.1.0...13.1.1.

**Comment by richardbporter** [comment]
Yes, specifically https://github.com/acquia/blt/pull/4370.

**Comment by richardbporter** [comment]
Seems like a temporary workaround is to remove `blt:init:settings` from `sync.commands`.

**Comment by mikemadison13** [comment]
I think this may be the same issue I flagged in https://github.com/acquia/blt/issues/4439. @richardbporter can you test  https://github.com/acquia/blt/pull/4440 ?

**Comment by richardbporter** [comment]
> I think this may be the related to the issue I flagged in #4439. @richardbporter can you test #4440 ?

Yes, that PR seems to fix this issue as well. 👍🏻

**Comment by mikemadison13** [comment]
closing via https://github.com/acquia/blt/issues/4439 and #4440
