### ISSUE TITLE
Composer conflict between acquia/blt and simplesamlphp/simplesamlphp 1.19 or higher

### ISSUE THREAD

**Issue by UnderwoodJM** [acquia/blt#4434]
**Describe the bug**
We have an existing Drupal project that we recently upgraded to Drupal 9. At the same time, we upgraded `simplesamlphp/simplesamlphp` from 1.18.7 to 1.19.1 through Composer. Prior to the Simplesamlphp upgrade, we started testing BLT in a local Lando-based environment by installing it via Composer. At that time we had an old version of Simplesamlphp and it installed successfully. However, a few weeks later we could not install `acquia/blt` via Composer due to a package conflict. `acquia/blt` requires `symfony/twig-bridge: ^3.3` and `simplesamlphp/simplesamlphp` 1.19.0 and higher require a newer version of that same package.

Composer says:
``` 
	BLT cannot be installed; can't resolve a set of installable packages.
	.....
    - Conclusion: don't install one of symfony/framework-bundle[v4.4.0-BETA1], acquia/blt[dev-main] | install one of symfony/twig-bridge[v3.4.8, ..., v3.4.47] (conflict analysis result)
    - Conclusion: don't install symfony/twig-bridge[v3.4.8] | install one of symfony/framework-bundle[v4.4.0-BETA2, ..., v4.4.34, v5.0.0-BETA1, ..., 5.4.x-dev] (conflict analysis result)
```

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Have a Drupal 9-based project (we run 9.2.7 currently)
2. Have `simplesamlphp/simplesamlphp` version 1.19.0 or higher as a project requirement via Composer
3. Attempt to require `acquia/blt` according to the instructions at https://docs.acquia.com/blt/install/adding-to-project/
4. Note the failure at the Composer level
5. Downgrade `simplesamlphp/simplesamlphp` to version 1.18.8
6. Attempt to install `acquia/blt`
7. Note the success.

**Expected behavior**
We would like to be able to use Acquia BLT alongside newer versions of simplesamlphp. If possible, can the project update its dependency on symfony/twig-bridge?

**Detailed error output**
(No BLT output possible)

**BLT doctor output**
(no BLT doctor output possible)

**System information**
* Operating system type: Windows 10 + WSL2 in a Lando Environment
* Operating system version: Windows 10 Enterprise 21H1 + Ubuntu 20.04 LTS
* BLT version: dev-main

**Additional context**
(no additional context)

**Comment by danepowell** [comment]
Can you try https://github.com/acquia/blt/pull/4435 and tell me if that solves it for you?

**Comment by UnderwoodJM** [comment]
I can confirm that I can _install_ BLT now. However I cannot say whether or not it truly works until I have reconfigured our multisite environment, run a test deployment, and so on.

Thank you for the incredibly quick turnaround.
