### ISSUE TITLE
Drupal VM post-provison script not to be found in 13.2.x

### ISSUE THREAD

**Issue by atul4drupal** [acquia/blt#4450]
I am updating my drupal site fomr 8.x to 9.3.x and for this I also updated Acquia/BLT but the mentioned post-provion.php script for drupal-vm is missing and I am just wondering if this will break any underlying functionality or not.
Suggestions will be appreciated.

**Comment by mikemadison13** [comment]
The Drupal VM functionality got moved into a separate plugin. Did you add https://github.com/acquia/blt-vm? And, due to it being there and not in BLT itself, you may also need to update the location of the script.

**Comment by atul4drupal** [comment]
Thanks @mikemadison13  for the clarification

**Comment by mikemadison13** [comment]
most welcome! common issue.
