### ISSUE TITLE
./vendor/acquia/blt/blt.sh blt:init:shell-alias Failing in 13.x version

### ISSUE THREAD

**Issue by atul4drupal** [acquia/blt#4452]
Alias not found/exists error is thrown

Any assistance will be appreciated

**Comment by manerkargaurav** [comment]
Hi,

You will need to use BLT launcher

**Comment by danepowell** [comment]
> You will need to use BLT launcher

Indeed, this was called out in the [BLT 13 release notes](https://github.com/acquia/blt/releases/tag/13.0.0). The BLT Launcher is located here: https://github.com/acquia/blt-launcher
