### ISSUE TITLE
BLT database sync command stuck on MacOs BigSur

### ISSUE THREAD

**Issue by manerkargaurav** [acquia/blt#4453]
**Describe the bug**
BLT database sync command is getting stuck on MacOs big sur
`blt drupal:sync:db --site=site_alias`

**To Reproduce**
Setup BLT with Drupal VM and vagrant on MacOs bigsur
Under vagrant ssh try to sync database from Acquia cloud
Sync process is stuck at "Copying dump file from source to target." step

**Expected behavior**
Database sync process should be completed within minutes.

**System information**
* Operating system type: Mac
* Operating system version: Big Sur
* BLT version: 13.2.1

**Comment by mikemadison13** [comment]
@manerkargaurav apologies for the slow reply, i'm curious if you run the sql-sync command manually with drush, does it also get stuck? i'm curious if this is something to do with the blt task itself or the underlying drush tasks.
