### ISSUE TITLE
BLT 13 Pipelines Documentation or core-composer-scaffold dependency request

### ISSUE THREAD

**Issue by loopy3025** [acquia/blt#4462]
We are in the process of upgrading our site to BLT 13 and we came across an issue with Pipelines running on Acquia. All of our local builds worked fine. Moreover, when we pushed the code to github and the pipelines build ran, it did so without error. However, there was no build artefact in the pipelines-build branch. 

While playing "perform this unrelated task for me" tennis with the Acquia Platform helpdesk, we hunted for a solution on our own. 

As it turns out, there are requirements for running BLT 13 on Acquia Pipelines which are not indicated in the documentation. Even though pipelines is kind of assumed to be used with BLT, and it includes lots of scripts and files for Pipelines, there is no actual Pipelines specific package with its own set of requirements.

Our composer.json had the following:
 - "acquia/blt": "^13.0"
 - "drupal/core": "^9.2"
 - "drupal/core-composer-scaffold": "^9.2"
 - "drupal/core-recommended": "^9.2"

Our composer.lock had the following installed: 
 - acquia/blt: 13.2.1
 - drupal/core: 9.3.0
 - drupal/core-composer-scaffold: 9.2.19
 - drupal/core-recommended: 9.3.0

Which caused the artefact build to silently fail in Acquia Cloud.

Today, we adjusted the composer.json requirements and got the following installed at composer.lock:
 - acquia/blt: 13.2.2
 - drupal/core: 9.3.3
 - drupal/core-composer-scaffold: 9.3.3
 - drupal/core-recommended: 9.3.3

With these requirements fixed, the build artefact now successfully builds.

Oddly, we had a different site which was already running BLT 13 and building artefacts with no issues whatsoever...
 - acquia/blt: 13.2.1
 - drupal/core: 9.3.0
 - drupal/core-composer-scaffold: 9.3.0
 - drupal/core-recommended: 9.3.0

This leads me to believe that these core versions need to remain in sync with each other in order to operate effiiciently. Simply running composer update for core and core-recommended isn't also going to update the scaffold which seems to be what caused pipelines to whimper and die.

**Steps to reproduce**

``` 
composer require acquia/blt:^13.0 drupal/core:9.2 drupal/core-composer-scaffold:9.2 drupal/core-recommended:9.2
composer require acquia/blt:^13.0 drupal/core:^9.2 drupal/core-composer-scaffold:^9.2 drupal/core-recommended:^9.2 --no-update
composer update acquia/blt drupal/core drupal/core-recommended
```
- Push the code to your repo and wait for pipelines to build
- Deploy the pipelines-build branch to an environment
- ssh into the environment and see that there is no code, only symlinks to the files folders

**Describe the solution you'd like**

- Certainly the build should have reported as failed if no build artefact was created.  Since there is no repo to report Pipelines issues to, I guess this is as good a place as any to say this.
- Also if core, core-composer-scaffold, and core-recommended need to have matching versions, then core-composer-scaffold should have a core requirement set. Right now, it just requires composer-plugin-api and php.

**Comment by mikemadison13** [comment]
@loopy3025 i've run into similar issues, and pretty consistently need to update all 3 when i do a drupal/core update. i'm not sure how blt could help here, without explicitly pinning the versions (which would then make blt a blocker to updating which we don't want). 

would improved documentation somewhere, help?
