### ISSUE TITLE
Acquia BLT 13 will not allow projects to upgrade to Drush 11

### ISSUE THREAD

**Issue by kmonty** [acquia/blt#4464]
**Background**
On January 11th, [Drush 11 was released](https://github.com/drush-ops/drush/releases/tag/11.0.0). With that release, support for Drush 10 was officially dropped.

Projects running the latest release of Acquia BLT are now forced to use an EOL version of Drush, as BLT mandates projects run Drush 10.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer require acquia/blt:^13.2.2 drush/drush:^11 -W`
2. See error `acquia/blt[13.2.2, ..., 13.x-dev] require drush/drush ^10.2.2 -> found drush/drush[10.2.2, ..., 10.x-dev] but it conflicts with your root composer.json require (^11)`

**Comment by smustgrave** [comment]
+1 for this.  Drush 10 has stopped and it would be nice to be able to update.

**Comment by richardbporter** [comment]
> Also with Drush 11 not works command `blt deploy:update`. It fails on command `drush @self config-import sync --no-interaction --ansi` with error: `Too many arguments, expected arguments "command". `

Looks like `drush config:import` no longer takes a label argument, i.e. sync.

**Comment by richardbporter** [comment]
> > Also with Drush 11 not works command `blt deploy:update`. It fails on command `drush @self config-import sync --no-interaction --ansi` with error: `Too many arguments, expected arguments "command". `
> 
> Looks like `drush config:import` no longer takes a label argument, i.e. sync.
> 
> [drush-ops/drush#4848](https://github.com/drush-ops/drush/pull/4848)

I don't see a way around that error by changing BLT config - looks to be set in: 
https://github.com/acquia/blt/blob/0ac0e0e6930fd4163ca464bd8bbcbd8ff5ee8109/src/Robo/Commands/Drupal/ConfigCommand.php#L71

I think the only option to upgrade to Drush 11 right now, would be to [alias Drush 11 as Drush 10](https://github.com/acquia/blt/pull/4465#issuecomment-1044703426) in composer.json (ex. `"drush/drush": "11.0.5 as 10.3.6"`) and completely override the `drupal:config:import` command to not pass the `$cm_core_key` argument to the `importCoreOnly` and/or `importConfigSplit` method(s).

**Comment by mikemadison13** [comment]
I've taken a stab at refactoring out the argument for the config commands. See https://github.com/acquia/blt/pull/4465/commits/65325c4c9302277a614ab0b0d176b68f5e04fd00

**Comment by danepowell** [comment]
This fix is now in main 13.x-dev if folks could please test and report any issues. We'll cut a new stable release shortly.

**Comment by mikemadison13** [comment]
i updated https://github.com/Drupal4Gov/Drupal-GovCon-2017/pull/991 and confirmed the basic commands all work between my local, CI/CD, and deployments including:

- sync
- setup
- tests
- validate
- source:build
- drupal:update
- sync:db
- deploy / update drupal, etc.

no super obvious issues from local => ci/cd => dev

**Comment by danepowell** [comment]
Per BLT's policy of not supporting EOL packages, we may be dropping support for Drush 10 in the next release as part of the fix for #4490
