### ISSUE TITLE
DX-5109: Ask permission before installing the shell alias

### ISSUE THREAD

**Issue by pfrenssen** [acquia/blt#4506]
**Is your feature request related to a problem? Please describe.**
When installing/updating a project that uses BLT using composer, a shell alias is secretly added to `~/.bash_profile` (or alternative shell config files) without asking the user for permission. Apart from the fact that it is a bit rude to change the user's personal configuration without informing them, this can in some cases cause problems.

I have an existing Python script named `blt` which unexpectedly stopped working after I rebooted my system. Changes made to `~/.bash_profile` only take effect after rebooting or relogging.

**Describe the solution you'd like**
It would be great if we would ask the user permission before creating the shell alias when they install a project using Composer that includes BLT. In addition to this, we could provide clear information about which files will be changed, and inform the user that they might need to reboot their system before the shell alias takes effect.

I wonder also if it is still relevant in 2022 to "force" users to install this shell alias. The alias is intended for projects that run on a local PHP installation and doesn't work in modern container based development workflows which I think most developers are using nowadays (e.g. projects using docker-compose, vagrant, Lando or Drupal VM).

So maybe an alternative solution could be to NOT auto-install the alias? We could document that the user can run `./vendor/bin/blt blt:init:shell-alias` if they want to have this convenient alias available and are working on a project which is not container based.

**Comment by mikemadison13** [comment]
i THINK that this is not a factor in BLT 13.x anymore... see https://github.com/acquia/blt/pull/4364 and the 13.x release notes: https://github.com/acquia/blt/releases/tag/13.0.0. 

What version of BLT are you running @pfrenssen ?

**Comment by pfrenssen** [comment]
Thanks @mikemadison13, this is indeed already fixed in BLT 13.x.

Closing as a duplicate of #4364
