### ISSUE TITLE
DX-5113: `BltDetector::isDrupalInstalled` returns FALSE if Drush reports that a site cannot bootstrap.

### ISSUE THREAD

**Issue by richardbporter** [acquia/blt#4517]
**Describe the bug**
`BltDetector::isDrupalInstalled` returns FALSE if Drush reports that a site cannot bootstrap. This is misleading because a failure to bootstrap could be caused by other things like the service container needing a rebuild, update hook, etc. This can be problematic if you're relying on this check to determine whether or not to install a site.

**To Reproduce**
This is difficult to reproduce but can crop up when updating a dependency if a class signature changes or an update hook needs to run for certain conditions to be met. You could temporarily change the arguments in a class constructor or throw an `exit` in an installed site's settings.php file and then run `blt doctor`.

**Expected behavior**
I would expect a method called `isDrupalInstalled` to return TRUE even in situations where an installed site cannot bootstrap. 

**Detailed error output**
None.

**BLT doctor output**
NA

**System information**
* BLT version: 13.3.0

**Additional context**
This change seems to have been introduced in https://github.com/acquia/blt/pull/4049. Checking for the existence of tables like config probably wasn't perfect either. I don't know what the ideal criteria is for determining if a site is installed or not. Maybe this method should be renamed if the current criteria is preferred.

**Comment by mikemadison13** [comment]
Can you check a more recent version of BLT? I had to refactor this logic a bit in https://github.com/acquia/blt/pull/4514 and https://github.com/acquia/blt/pull/4516

**Comment by richardbporter** [comment]
Thanks! Unfortunately, I don't know when I'll have time to test this out. Someone from @uiowa might be able to though. :)

**Comment by mikemadison13** [comment]
closing this for now, if it is still an issue with BLT 13.5.x please re-open or submit a new bug!
