### ISSUE TITLE
DX-5114: How to start Acquia pipeline jobs for tags?

### ISSUE THREAD

**Issue by sivakarthik2291** [acquia/blt#4520]
**I want to...**
I want to start Acquia pipeline job for tags as well. I was able to start jobs automatically for branches and complete them without any errors.

**It's not working because...**
I am getting below error after starting job for tags:

"**The specified deploy VCS path (pipelines-build-tags&#47;test-pipeline) identifies a tag, which is unsupported. Tags are only supported for the source VCS path.**"

**System information**
* BLT version: 12.8.2
I am using the default scripts provided by BLT, no custom script is used in our code.

Can someone please help me, how to start Acquia pipeline job for tags?

**Comment by mikemadison13** [comment]
This is likely a limitation with the webhook connection between Acquia PIpelines and Github, and not actually a BLT issue.
