### ISSUE TITLE
DX-5122: BLT with Cloud Next

### ISSUE THREAD

**Issue by broeker** [acquia/blt#4532]
**Overview**

We are spinning up a new project using the newly released Acquia Cloud Next. Our client will also be using Acquia Piplines, with Github as their project repository.  In the past, we've leveraged BLT by default for this setup, but it has been awhile since we have set up a greenfield project. 

**The issue**

At the top of the BLT documentation there is this statement:

> **Important**
> 
> This product may not function as expected on applications powered by Acquia Cloud Next technologies, depending on its configuration.

I can't seem to find any further documentation or even discussions in the issue queue on this, what exactly might not function as expected, and what configuration is required to work with BLT+Cloud Next. 

**The questions**

- Is there any further documentation/discussion that I am missing? 
- Is BLT still the recommended tool for this workflow? (Github+Pipelines+Cloud Next)? Are there better options/alternatives?
- Members of their team also plan on using Acquia Cloud IDE -- does that impact this situation?

**Comment by mikemadison13** [comment]
I have a project on Cloud next using BLT 13.x, PHP 8.x, Drush 11.x, etc. and have not faced any issues. This may just be a documentation issue and/or a "we haven't extensively tested this yet" warning. 

But as far as I'm concerned things seem ok.

**Comment by mikemadison13** [comment]
And yes, I believe currently BLT is the best option for Github + Pipelines + cloud next. If you're using Cloud IDES you may want to check out @pavlosdan's plugin https://github.com/pavlosdan/blt-ide-local
