### ISSUE TITLE
DX-5126: Process Tasks in Executor Throwing Deprecated Warnings

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4541]
**Describe the bug**
After updating our calls to use the array syntax instead of strings, it looks like we missed a few related to test execution as there are a number of exec calls that pass strings and the results are throwing:

```
Deprecation Warning: this command is passing a command string and should pass a command arary.
 [error]  You must have Google Chrome version 59+ to execute headless tests.
```

...I also can't apparently spell the word array.

See:
* https://github.com/acquia/blt/blob/main/src/Robo/Common/Executor.php#L137
* https://github.com/acquia/blt/blob/main/src/Robo/Common/Executor.php#L153

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. run `blt tests:behat` and get the error

**Expected behavior**
Test execution works!

**Comment by bmartinez287** [comment]
I also got the error with any test, even the standard drupal test.
`blt tests:drupal `failed too.

**Comment by mikemadison13** [comment]
I added some debugging and it looks like it is reporting the version as "0." So maybe this is a problem with the command even locating it?

**Comment by bmartinez287** [comment]
Probably, 0 does not sounds like a default value. Most likely the default you get if you are forcing null value to be an integer.

**Comment by bmartinez287** [comment]
```
if ($version == 0) {
      throw new BltException("The Chromedriver can't be found, rollback to a BLT minor release");
}
if ($version < 59) {
      throw new BltException("You must have Google Chrome version 59+ to execute headless tests.");
 }

```
