### ISSUE TITLE
DX-5129: How many times after_failure will called by travis. How to control to one time it should call.?

### ISSUE THREAD

**Issue by suryagunturi** [acquia/blt#4547]
I am working as Android App Developer. I am using Travis for CI/CL. I send a message to Microsoft Teams when my build is failed using after_failure block

But the problem is after_failure  block is executing morethan one time. I would like to run it only once when my script failes

**Comment by danepowell** [comment]
This is a project for users of BLT, an Acquia product. We are not affiliated with Travis CI. It doesn't sound like you are using BLT.

I'd suggest posting your question at https://travis-ci.community/ . Make sure to include a copy of your .travis.yml.

To answer your question directly, take a look at the following docs, I suspect you have multiple deploy providers: https://docs.travis-ci.com/user/job-lifecycle/#deploying-your-code

> Note that before_deploy and after_deploy are run before and after every deploy provider, so they will run multiple times, if there are multiple providers.
