### ISSUE TITLE
DX-5130: How to ignore file extensions on sync?

### ISSUE THREAD

**Issue by D41196829** [acquia/blt#4550]
Hello everyone, im trying to make my file sync ignore some larger files like PDF and vídeos, with no success, i placed the following on my blt.yml:

```
sync:
  # Paths to exclude during file syncing operations.
  exclude-paths:
    - styles
    - css
    - js
    - pdf
    - mp4
```
    
But this isn't work, anyone know what can i do to achieve this? Thanks.

**Comment by danepowell** [comment]
Try wildcards, e.g. `'*.pdf`.

BLT just passes these options to the Drush rsync command, which in turn passes them to rsync:
- https://github.com/acquia/blt/blob/ff52e5ec430173fede88747c89676e0608b27bf2/src/Robo/Commands/Drupal/SyncCommand.php#L83
- https://www.drush.org/latest/commands/core_rsync/
- https://phoenixnap.com/kb/rsync-exclude-files-and-directories
