### ISSUE TITLE
Behat: First test tagged @javascript in a feature fails, subsequent pass

### ISSUE THREAD

**Issue by jrbeeman** [acquia/blt#456]
When attempting to run `blt tests:behat:execute` against a Behat feature file, the first scenario tagged @javascript is failing, while subsequent scenarios in that feature file pass.

Example I have tested:
- https://github.com/acquia/lightning/blob/8.x-1.x/tests/features/content_type.feature

The result is that the first scenario, e.g. `Scenario: Ensure that the WYSIWYG editor is present.` fails, but the next scenario, e.g. `Scenario: Ensure that meta tag fields are present.` passes.

The output from running the test is consistent between the two example feature files:

```
  @javascript
  Scenario: Ensure that the WYSIWYG editor is present.         # /Users/jeff.beeman/Projects/watercooler/docroot/profiles/contrib/lightning/tests/features/content_type.feature:12
    Given I am logged in as a user with the administrator role # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
      Form field with id|name|label|value|placeholder "Username" not found.

      +--[  | Selenium2Driver ]
      |
      |
      |
    When I visit "node/add/page"                               # Drupal\DrupalExtension\Context\MinkContext::assertAtPath()
    Then CKEditor "edit-body-0-value" should exist
```

My naive guess is that it's failing to login. Perhaps a race condition with loading the page via the Selenium driver?

**Comment by grasmash** [comment]
@jrbeeman Is this still an issue in more recent versions of BLT? I have been unable to reproduce. Testing tools for Behat have changed significantly since this issue was filed.

**Comment by jrbeeman** [comment]
Following the changes to the testing infrastructure (use of Selenium, Drupal VM improvements, etc.) this is no longer an issue.
