### ISSUE TITLE
DX-5149: Failed to patch during deployment

### ISSUE THREAD

**Issue by nirojghale-iheartmedia** [acquia/blt#4574]
**Describe the bug**
I am upgrading from blt 11 to 13.5 and trying to patch one of the module. Composer patch works locally but whenever I deploy the code using blt deploy command it doesn't pickup the composer patch and just deploy the module without patch.

**To Reproduce**
Steps to reproduce the behavior, ideally starting from a fresh install of BLT:
1. Run `composer update` with this comoser.json file.
2. Read your local file 'docroot/modules/contrib/entity_reference_revisions/src/Normalizer/EntityReferenceRevisionItemNormalizer.php'
3. Run `blt deploy` and deploy the tag to remote cloud
4. Read your remote file 'docroot/modules/contrib/entity_reference_revisions/src/Normalizer/EntityReferenceRevisionItemNormalizer.php'

**Expected behavior**
Your remote patch file should look same like your local patched file.

**Composer and screenshots**
[Composer.json file and screenshots](https://drive.google.com/drive/u/0/folders/1yjkINgmOoXLKj3tH8X9Vy052DCoCtHWT)

**System information**
* Operating system type: Mac
* Operating system version: 12.5
* BLT version: 13.5

**Additional context**
There may be an issue while deploying code using blt please let me know if there is a way to debug.

**Comment by mikemadison13** [comment]
I believe this one was handled by Acquia support. So, closing. However, just to quickly document the issue:

in this case, the composer-patches plugin was added as a dependency (good) but as a dev dependency. When BLT executes a blt deploy, it excludes all dev dependencies. Which means that the blt deploy execution did not actually do any composer patching at all. Hence the silent failure. In this case, the solution was to move the composer patches into require and not require-dev. I've written a blog post on this here: https://mikemadison.net/blog/2022/8/9/composer-patches-not-applying.
