### ISSUE TITLE
DX-5150: Notice: Undefined variable: argv in Acquia\Blt\Robo\Common\EnvironmentDetector::getSiteName()

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#4577]
**Describe the bug**
I get a warning in my local install after updating to BLT 13.5.1:

```
Notice: Undefined variable: argv in Acquia\Blt\Robo\Common\EnvironmentDetector::getSiteName() (line 246 of /var/www/html/princeton/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php).

Acquia\Blt\Robo\Common\EnvironmentDetector::getSiteName('sites/default') (Line: 189)
require('/var/www/html/princeton/docroot/sites/default/settings/local.settings.php') (Line: 142)
require('/var/www/html/princeton/vendor/acquia/blt/settings/blt.settings.php') (Line: 16)
require('/var/www/html/princeton/docroot/sites/default/settings.php') (Line: 157)
Drupal\Core\Site\Settings::initialize('/var/www/html/princeton/docroot', 'sites/default', Object) (Line: 1065)
Drupal\Core\DrupalKernel->initializeSettings(Object) (Line: 699)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

The line that getSiteName is called on is here:

`$settings['file_public_path'] = 'sites/' . EnvironmentDetector::getSiteName($site_path) . '/files';`

This looks like its due to [this PR that was merged, which removed usages of super-globals](https://github.com/acquia/blt/pull/4523/files#diff-da4db5d78e93095cb66e19a12ef185565c317720d574ae00f0218399f4cd1973)

The method previously had this line:
`$input = new ArgvInput(!empty($_SERVER['argv']) ? $_SERVER['argv'] : ['']);`

And was replaced with this line:
`$input = new ArgvInput($argv);`

But [PHP does not set `$argv` unless it's configured to do so](https://www.php.net/manual/en/ini.core.php#ini.register-argc-argv). To confirm it's not just my local env that has this turned off, Acquia's PHP config also has this turned off.

**To Reproduce**

Have a ACSF codebase locally, with BLT integration.

**Expected behavior**
No warning message

**BLT doctor output**
```
+------------------+---------------------------------------------+
| Property         | Value                                       |
+------------------+---------------------------------------------+
| blt-version      | 13.5.1.0                                    |
| composer-version | Composer version 2.3.10 2022-07-13 15:48:23 |
| root             | /var/www/html/princeton/docroot             |
| uri              | default                                     |
+------------------+---------------------------------------------+
```

**System information**
* Operating system type: Docker debian image
* BLT version: 13.5.1

**Comment by mikemadison13** [comment]
@bkosborne do you mind trying the patch in my PR?

**Comment by bkosborne** [comment]
@mikemadison13 Yes, that fixes it. Thanks for the quick reply!
