### ISSUE TITLE
DX-5155: Terminal BLT 12 release

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#4587]
BLT 12 has been officially EOL for 18 months but is still widely used. It's starting to break due to conflicts with other packages (#4583). We should add a warning message encouraging people to upgrade and fix that fatal error so that, you know, people actually see the warning message 😄

**Comment by mikemadison13** [comment]
👍

**Comment by danepowell** [comment]
![Screen Shot 2022-08-24 at 8 36 55 AM](https://user-images.githubusercontent.com/1984514/186461138-3fe87a95-045b-46a1-94bf-a07527d38a3a.png)

https://github.com/acquia/blt/releases/tag/12.8.4
