### ISSUE TITLE
DX-5800: Acquia\Blt\Robo\Common\EnvironmentDetector::getSiteName($site_path) must be compatible with Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector::getSiteName(string $site_path): ?string in /app/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php

### ISSUE THREAD

**Issue by bmartinez287** [acquia/blt#4597]
Changes made to https://github.com/acquia/drupal-environment-detector require for this to be updated:

- Acquia\Blt\Robo\Common\EnvironmentDetector::getSiteName($site_path) 
- Acquia\Blt\Robo\Common\EnvironmentDetector::isLocalEnv()

PHP Fatal error:  Declaration of Acquia\Blt\Robo\Common\EnvironmentDetector::getSiteName($site_path) must be compatible with Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector::getSiteName(string $site_path): ?string in /app/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php on line 236

Fatal error: Declaration of Acquia\Blt\Robo\Common\EnvironmentDetector::getSiteName($site_path) must be compatible with Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector::getSiteName(string $site_path): ?string in /app/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php on line 236
 [warning] Drush command terminated abnormally.

PHP Fatal error:  Declaration of Acquia\Blt\Robo\Common\EnvironmentDetector::isLocalEnv() must be compatible with Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector::isLocalEnv(): bool in /app/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php on line 105

Fatal error: Declaration of Acquia\Blt\Robo\Common\EnvironmentDetector::isLocalEnv() must be compatible with Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector::isLocalEnv(): bool in /app/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php on line 105
 [warning] Drush command terminated abnormally.

**Comment by mikemadison13** [comment]
Hi @bmartinez287 what version of BLT are you running?

**Comment by joejoseph00** [comment]
https://github.com/acquia/blt/issues/4674
