### ISSUE TITLE
DX-5177: drush runserver problem

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#4609]
**Describe the bug**
I just updated from `13.4.0` to `13.5.2` and I'm having trouble with my tests command in CI, where I'm using `drush runserver` functionality to test my site. In my BLT update, I'm also upgrading drush from `11.0.5` to `11.2.1`. 
I can't find where I think the problem is in the diff of either of those, but I do think I see the problem.

BLT is basically calling:
`$ drush runserver --uri=http://127.0.0.1:8888`

but, [according to the docs](https://www.drush.org/latest/commands/runserver/), there is no `--uri` option. The URI is supposed to be passed in as the primary argument, not a flag... so:
`$ drush runserver http://127.0.0.1:8888`

**To Reproduce**
Given the above software versions, if I run (note the port numbers)...

```sh
$ vendor/bin/drush @self runserver --uri=http://127.0.0.1:59477
 [notice] HTTP server listening on 127.0.0.1, port 8888 (see http://127.0.0.1:8888/), serving site, sites/default
[Tue Oct 11 09:49:10 2022] PHP 7.4.32 Development Server (http://127.0.0.1:8888) started

$ vendor/bin/drush @self runserver http://127.0.0.1:59477
 [notice] HTTP server listening on 127.0.0.1, port 59477 (see http://127.0.0.1:59477/), serving site, sites/default
[Tue Oct 11 09:49:22 2022] PHP 7.4.32 Development Server (http://127.0.0.1:59477) started
```

**Expected behavior**
When I run `$ blt tss -Dtests.server.url=http://127.0.0.1:59478 -v` I want it to work.

**Actual behavior**
It times out.

**Workaround**
None.

**System information**
* Operating system type: Ubuntu
* Operating system version: 18
* BLT version: 13.5.2

**Comment by mikemadison13** [comment]
@dpagini do you have a ci.blt.yml file in your blt directory? this runserver stuff has been problematic on other projects and i think in many cases it's because of that config. see https://github.com/Drupal4Gov/Drupal-GovCon-2017/blob/develop/blt/ci.blt.yml as a working example. i haven't had issues with runserver "not" working on the govcon repo

**Comment by ayalon** [comment]
This is obviously a bug in BLT. The ci.blt.yml File has nothing to do with it.

**src/Robo/Commands/Tests/ServerCommand.php**
```
    /** @var \Acquia\Blt\Robo\Common\Executor $executor */
    $executor = $this->getContainer()->get('executor');
    $result = $executor
      ->drush("runserver --quiet --uri=$this->serverUrl > $log_file 2>&1")
      ->background(TRUE)
      ->printOutput(TRUE)
      ->run();
```

This is how run server is called. But it is wrong, it does not work with the latest drush version. It should be:

```
    /** @var \Acquia\Blt\Robo\Common\Executor $executor */
    $executor = $this->getContainer()->get('executor');
    $result = $executor
      ->drush("runserver --quiet $this->serverUrl > $log_file 2>&1")
      ->background(TRUE)
      ->printOutput(TRUE)
      ->run();
```

**Comment by mikemadison13** [comment]
i opened a PR to test this, could you give it a shot, please?

**Comment by ayalon** [comment]
Tested and works on BLT 13.6.0 and Drush 11

**Comment by dpagini** [comment]
Thanks all!  Sorry I hadn't seen the replies back to me until now... =/
