### ISSUE TITLE
DX-5179: Cannot instantiate abstract class Drupal\Core\Database\Schema

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#4611]
**Describe the bug**
After updating to drupal/core 9.4.8 sites on the Acquia platform throw:
```
Cannot instantiate abstract class Drupal\Core\Database\Schema in
 Drupal\Core\Database\Connection->schema()
```

See https://support-acquia.force.com/s/article/add-workaround-for-Drupal-9-4-7-or-9-4-8 

This likely will interfere with both 12.x and 13.x BLT (anyone that could be running Drupal 9.4.x). I was able to run 9.4.7 without issue. 9.4.8 bootstraps and runs for me, but drush doesn't (which is bad).

**Comment by iamsophiesk** [comment]
Noticing this on Drupal 9.4.8 as well. Weirdly this only started being an issue this afternoon: I updated to the latest BLT (13.5.2), Drush (11.2.1) and Drupal (9.4.8) this morning. The pre-merge build worked fine; the merge build worked fine; a subsequent merge build failed, and all Drush commands have failed since.

**Comment by shelane** [comment]
The problem showed up for me also on my on-prem server. The fix from the article did work for me however. If Acquia does put a fix on the platform, I would like to know the best path to also fixing it on my platform. Strangely, this only affected one Drupal site I have while another using the same version had no problem.

**Comment by bkosborne** [comment]
We have ACE and ACSF applications, both on 9.4.7, both using BLT, and neither have this problem. I wonder what causes it to happen on some sites and not others?

**Comment by shelane** [comment]
My site was fine on 9.4.7. It was when I updated to 9.4.8 that the problem showed up for me.

**Comment by iamsophiesk** [comment]
My site is fine on 9.4.7, but had problems on 9.4.8. 

Acquia seem to think this is an issue for both versions though. They performed some maintenance overnight that took our site (updated to 9.4.7 yesterday) down for a few hours 🙈

**Comment by bkosborne** [comment]
Yeah, we were also down.

**Comment by mikemadison13** [comment]
I believe the platform fix for this has been deployed. My 9.4.8 site is now functioning normally.
