### ISSUE TITLE
BLT-5206: Remove cache.php, no longer needed for drush

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#4664]
**Is your feature request related to a problem? Please describe.**
BLT includes this [cache.php](https://github.com/acquia/blt/blob/13.7.0/scripts/blt/drush/cache.php) file which can be used to generate a temporary directory path for drush to use when running drush commands. This was done to work around issues with code deployments in Acquia where another drush command may run at the same time (and thus use the same cache dir, causing issues). See https://github.com/acquia/blt/issues/2867

However, Drush 11 removed its own internal caching entirely:

- https://github.com/drush-ops/drush/releases/tag/11.0.0
- https://github.com/drush-ops/drush/pull/4965
- https://github.com/drush-ops/drush/pull/4971

This file shouldn't be required anymore. BLT 13.x requires at least Drush 11 so should be safe to remove. From what I can tell, this file isn't used within BLT at all, but is used within the split-off ACSF plugin. I created an issue there to remove its usage there as well: https://github.com/acquia/blt-acsf/issues/12

To be clear, the file isn't causing any problems that I can think of, but it's just old code that's not needed.

**Describe the solution you'd like**
Remove this file

**Additional context**
I've been debugging why we have cache clear issues in ACSF deploys and I went down a rabbit hole and this drush cache stuff was found along the way.

**Comment by danepowell** [comment]
Thanks. I haven't thought about this file in a while but if it's no longer needed I'm happy to remove it: #4665 

I couldn't find it referenced anywhere else, do you know if it's part of an `include` or `require` anywhere?

**Comment by bkosborne** [comment]
Could be used by BLT plugins. The one for sure that's using it is the ACSF plugin

**Comment by danepowell** [comment]
@bkosborne could you please open a PR for blt-acsf? Otherwise I'll need to revert this. I don't use, maintain, or test that plugin. I can only review community PRs.

**Comment by anairamzap-mobomo** [comment]
Hi, just a note to say that indeed removing the cache.php file breaks acsf deployments using a db-update script as provided by the Acquia docs: https://docs.acquia.com/site-factory/extend/hooks/post-site-update/

I can see the code itself in the repo https://github.com/acquia/blt-acsf/blob/master/factory-hooks/db-update/db-update.sh was updated, but it would be great to also update the documentation.

Just posting this comment here in case it helps someone else.
