### ISSUE TITLE
BLT-5211: acquia blt documentation is outdated, causing crashes and installation issues

### ISSUE THREAD

**Issue by joejoseph00** [acquia/blt#4674]
@bmartinez287  I just hit this https://github.com/acquia/blt/issues/4597 because the acquia documentation is outdated

https://docs.acquia.com/blt/install/adding-to-project/

Could you please update the acquia documentation to read **^13** instead of **^13.0** ?

see link ^^^

**Describe the bug**
Exactly as described here:
https://github.com/acquia/blt/issues/4597

**To Reproduce**
Follow acquia blt installation instructions
composer require "acquia/blt":"^13.0"

**Expected behavior**
composer require "acquia/blt":"^13"

**Detailed error output**
`Fatal error: Declaration of Acquia\Blt\Robo\Common\EnvironmentDetector::isLocalEnv() must be compatible with Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector::isLocalEnv(): bool in /home/ide/project/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php on line 105
`
**BLT doctor output**
`Fatal error: Declaration of Acquia\Blt\Robo\Common\EnvironmentDetector::isLocalEnv() must be compatible with Acquia\DrupalEnvironmentDetector\AcquiaDrupalEnvironmentDetector::isLocalEnv(): bool in /home/ide/project/vendor/acquia/blt/src/Robo/Common/EnvironmentDetector.php on line 105`

**System information**
* Operating system type: acquia cloud
* Operating system version: acquia cloud
* BLT version: 13.0

**Additional context**
please update the acquia blt documentation installation instructions!

**Comment by bmartinez287** [comment]
Unfortunately, I don't have access to that page. That probably has to be done by an Acquia employee. It be nice to get it updated but it may not be their highest priority. Every now and then someone comes to checkout open issues so they might do it eventually.

**Comment by joejoseph00** [comment]
ya I tried to install this about 6 months ago, hit this and abandonned, now I came back, spent more time, figured it out. basically it will help a lot to have the documentation fixed.

**Comment by danepowell** [comment]
The docs have been updated internally and should be published momentarily.

**Comment by joegl** [comment]
I know this is closed, but the Acquia docs are listing version 13.5.2 from August 2022 as the latest release as well: https://docs.acquia.com/blt/release-notes/

**Comment by joejoseph00** [comment]
@joelgl , composer up acquia/blt should get you the latest version  (currently 13.7.1) and the installation instructions are now valid.

The issue above was because the previous v12 installation instructions were no longer working.  the instructions were updated and it now works.  However ya someone might want to keep those version notes in sync with releases.
