### ISSUE TITLE
Add support for SimpleSAMLphp

### ISSUE THREAD

**Issue by dooleymatt** [acquia/blt#481]
Currently, installing SimpleSAMLphp in a BLT project is a difficult process that involves importing custom tasks or overriding existing tasks. There are 2 main issues that I have found:

1. The default location for configuration files used by the SimpleSAMLphp library is inside the library itself. This creates a problem because the configuration files get reset to their default values every time composer update or composer install is run. 
2. The simplesamlphp_auth module has a composer.json file that lists an outdated version of the library, which conflicts with the security related packages in BLT.

**Comment by grasmash** [comment]
Merged in https://github.com/acquia/blt/pull/478.
