### ISSUE TITLE
Local patches not working

### ISSUE THREAD

**Issue by dalibor-matura** [acquia/blt#483]
It seems that the **Simple patches plugin for Composer** https://github.com/cweagans/composer-patches **do not support local patches**.

In its documenatation is mentioned only this: https://github.com/cweagans/composer-patches#using-an-external-patch-file, but it only explains how to separate patches from composer.json into composer.patches.json, so their definition is in separated file. That file contains patches urls and not local (relative) paths.

I believe that **BLT Patches documentation incorectly claims that local patches work and links that info http://blt.readthedocs.io/en/stable/template/patches/README/ under the text "See instructions for using a local patch.".

I needed to change a panelizer patch from the issue https://www.drupal.org/node/2760051 to be available for stable version and not just dev version of panelizer. But I was unable to make the local patch work and had to move the patch into that drupal.org issue.

I've checked the cweagans/composer-patches code to find out what is wrong. The patch is being applied by the Patches::getAndApplyPatch() method and uses cmd execution like: `cd [module-folder] && GIT_DIR=. git apply --check -p1 [patch-path]` (to check if the patch can be applied) and `cd [module-folder] && GIT_DIR=. git apply -p1 [patch-path]` (to apply the patch). So obviously the local patch's pathc can't start by the "/" as discribed in http://blt.readthedocs.io/en/stable/template/patches/README/. I tried to find out the right relative pathc that should be probably somthing like: "../../../../patches/panelizer/my-modified-patch.patch", but with no success. The composer result was "Could not apply patch! Skipping." all the time.

I tried to run the `GIT_DIR=. git apply --check -p1 ../../../../patches/panelizer/my-modified-patch.patch` and `GIT_DIR=. git apply -p1 ../../../../patches/panelizer/my-modified-patch.patch` in the panelizer module folder and it works for fine.

*I assume that the main problem is in the Simple patches plugin for Composer that is not intended to be used with local patches.* Would be nice to help this composer plugin for patches to support the local patches too, maybe starting by discussing it with the owner.

**Comment by grasmash** [comment]
It is possible to use local patches with composer-patches, we have successfully done it on multiple projects, though I have not personally attempted it.

I believe that the patch path must be relative to the repository root, where the composer.json file is stored.

Here is a snippet from one of our projects that successfully employs local patches:

```
"drupal/search_api_solr": {
                "2790249-5-search_api_solr_autocomplete-alpha6": "patches/search_api_solr/2790249-5-search_api_solr_autocomplete-alpha6.patch"
            }
```

The patches dir is in the repository root.

**Comment by arunavak111** [comment]
I have added a patch in my composer.json like below
```
"patches": {
            "drupal/core": {
                "Allow a profile to be installed from existing config": "https://www.drupal.org/files/issues/2788777-91.patch",
                "My Patch": "patches/drupal/backwards_variables_in_message-2867834-myproject.0.1"
            }
        }
```

and my patch resides on following folder 
patches/drupal/backwards_variables_in_message-2867834-myproject.0.1

but while ran composer install getting this error:

```
- Applying patches for drupal/core
    https://www.drupal.org/files/issues/2752961-130.patch (Clear Twig caches on deploys)
    https://www.drupal.org/files/issues/2788777-91.patch (Allow a profile to be installed from existing config)
    patches/drupal/backwards_variables_in_message-2867834-myproject.0.1 (My Patch)
   Could not apply patch! Skipping. The error was: The "patches/drupal/backwards_variables_in_message-2867834-myproject.0.1" file could not be downloaded: failed to open stream: No such file or directory

                                                                                                    
  [Exception]                                                                                       
  Cannot apply patch My Patch (patches/drupal/backwards_variables_in_message-2867834-myproject.0.1)!  
                                      
```
