### ISSUE TITLE
Permission denied for ./vendor/acquia/blt/blt.sh

### ISSUE THREAD

**Issue by dalibor-matura** [acquia/blt#484]
After I run `composer install --prefer-dist` and the whole vendor folder is removed and composed again, I uaually receive the error: `./vendor/bin/blt: line 10: ./vendor/acquia/blt/blt.sh: Permission denied`
and I need to run: `chmod u+x ./vendor/acquia/blt/blt.sh` to fix it.
./vendor/acquia/blt/blt.sh: Permission denied`
and I need to run: `chmod u+x ./vendor/acquia/blt/blt.sh` to fix it.

**Comment by dalibor-matura** [comment]
I've noticed more permission denied during my work with BLT. I'm going to collect them when I see them again and provide them here.

**Comment by dalibor-matura** [comment]
This issue should be maybe moved somewhere else, please advice me on that :)

**Comment by grasmash** [comment]
Hm,`composer install --prefer-dist` should not remove vendor, it should only add missing dependencies.

Can you check file ownership? Are the files owned by you or by some other user?

**Comment by grasmash** [comment]
Pinging @dalibor-matura.

**Comment by grasmash** [comment]
Closing issue due to no response.
