### ISSUE TITLE
[Documentation] "composer blt-alias" instruction is incorrect

### ISSUE THREAD

**Issue by aangelinsf** [acquia/blt#486]
the composer file shows:  
```
"scripts": {
    "install-blt-alias": "blt install-alias -Dcreate_alias=true"
  }

```
and the documentation needs to be updated to read "composer install-blt-alias" (in creating-new-project.md).

**Comment by grasmash** [comment]
What version of BLT are you using? The composer.json file is here: https://github.com/acquia/blt/blob/8.x/template/composer.json#L63

It contains `   "blt-alias": "blt install-alias -Dcreate_alias=true",`.

Can you update BLT and verify that this is resolved?

**Comment by aangelinsf** [comment]
Cloned from the code page not more than a few minutes ago. 

Using:
DevDesktop 2 (Version: 2
Built: Mar 18 2016 07:15:45
Control panel rev: c50f65d
Stack rev: 27214be 

== Steps ==
1. Opened terminal via DevDesktop.
2. cd ~/Sites
3. git clone https://github.com/acquia/blt.git

Now following instructions in creating-new-project.md

4. composer clear-cache
5. export COMPOSER_PROCESS_TIMEOUT=2000
6. composer create-project acquia/blt-project blt_test --no-interaction

Finished with:
```
Writing lock file
Generating autoload files
Updating BLT templated files
This may have modified your composer.json and require a subsequent `composer update`
> rm -f .travis.yml
> rm -f README.md
> rm -f LICENSE.txt
> blt create-project
You must run this command from within a BLT-generated project repository.
```

But I continue because the folder blt_test now exists. 

7. cd blt_test
8. composer blt-alias

This returns:                                                              
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "blt-alias" is not defined.
```
9. cd ..
10. composer blt-alias

== Result ==
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "blt-alias" is not defined.                             
  Did you mean this?                                              
      install-blt-alias

This is all on macOS 10.12

**Comment by grasmash** [comment]
To determine the version of BLT that is being used, `cd` into `blt_test` and execute `composer info acquia/blt`.

**Comment by grasmash** [comment]
Ah, you also got `You must run this command from within a BLT-generated project repository` I see. Can share the output of `type blt`? You may have an outdated alias.

**Comment by aangelinsf** [comment]
```
$ composer info acquia/blt
name     : acquia/blt
descrip. : BLT
keywords : automation, deployment, drupal, template, testing
versions : * 8.4.6
type     : composer-plugin
license  : GNU General Public License v2.0 only (GPL-2.0) (OSI approved) https://spdx.org/licenses/GPL-2.0.html#licenseText
source   : [git] https://github.com/acquia/blt.git 2f6a78a6a1869b8a4d29d0f87c07b1c98f8292c6
dist     : [zip] https://api.github.com/repos/acquia/blt/zipball/2f6a78a6a1869b8a4d29d0f87c07b1c98f8292c6 2f6a78a6a1869b8a4d29d0f87c07b1c98f8292c6
names    : acquia/blt

autoload
psr-4
Acquia\Blt\ => src/
Acquia\Blt\Tests\ => tests/phpunit/src/

requires
composer-plugin-api ^1.0.0
dflydev/dot-access-data ^1.0
drupal/coder ~8.2
drupal/console 1.0.0-beta5
phing/phing ~2
php >=5.6
phpunit/phpunit ~5.4
squizlabs/php_codesniffer ^2.4
symfony/console ~2
symfony/twig-bridge ~2
symfony/yaml ~2.7

suggests
hirak/prestissimo ^0.3

conflicts
drupal/core 7.*

```

Andres-Mac-Pro:blt_test andreangelantoni$ type blt
-bash: type: blt: not found
Andres-Mac-Pro:blt_test andreangelantoni$ cd ..
Andres-Mac-Pro:blt andreangelantoni$ type blt
-bash: type: blt: not found

A fundamental step appears not to be executing.

**Comment by grasmash** [comment]
Can you share the entire log output from running `create-project`, and also the contents of composer.json?

Also, do you have php errors set to display to screen?

**Comment by aangelinsf** [comment]
I am not running `create-project`.

The error came from the end of running `composer create-project acquia/blt-project blt_test --no-interaction`:

```
<snip>
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.4.0)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
phing/phing suggests installing phpdocumentor/phpdocumentor (Documentation Generator for PHP)
phing/phing suggests installing sebastian/phpcpd (Copy/Paste Detector (CPD) for PHP code)
phing/phing suggests installing phpmd/phpmd (PHP version of PMD tool)
phing/phing suggests installing pdepend/pdepend (PHP version of JDepend)
phing/phing suggests installing phploc/phploc (A tool for quickly measuring the size of a PHP project)
phing/phing suggests installing pear/versioncontrol_svn (A simple OO-style interface for Subversion, the free/open-source version control system)
phing/phing suggests installing pear/versioncontrol_git (A library that provides OO interface to handle Git repository)
phing/phing suggests installing pear/archive_tar (Tar file management class)
phing/phing suggests installing siad007/versioncontrol_hg (A library for interfacing with Mercurial repositories.)
phing/phing suggests installing tedivm/jshrink (Javascript Minifier built in PHP)
symfony/event-dispatcher suggests installing symfony/http-kernel ()
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
alchemy/zippy suggests installing guzzle/guzzle (To use the GuzzleTeleporter)
acquia/blt suggests installing hirak/prestissimo (^0.3)
Writing lock file
Generating autoload files
Updating BLT templated files
This may have modified your composer.json and require a subsequent `composer update`
> rm -f .travis.yml
> rm -f README.md
> rm -f LICENSE.txt
> blt create-project
You must run this command from within a BLT-generated project repository. 
```

All of the above came from composer; I did not type any of it. So it appears likely that there is an error in the post command scripts that contain the `rm`s and `blt create-project`.

composer.json in the blt root looks like this:

```
{
  "name": "acquia/blt",
  "description": "BLT",
  "keywords": [ "drupal", "testing", "deployment", "automation", "template" ],
  "authors": [
    {
      "name": "Matthew Grasmick"
    }
  ],
  "support": {
    "issues": "https://github.com/acquia/blt/issues",
    "docs": "http://blt.readthedocs.io/en/stable"
  },
  "type": "composer-plugin",
  "license": "GPL-2.0",
  "require": {
    "drupal/console":                   "1.0.0-beta5",
    "phing/phing":                      "~2",
    "phpunit/phpunit":                  "~5.4",
    "squizlabs/php_codesniffer":        "^2.4",
    "symfony/yaml":                     "~2.7",
    "drupal/coder":                     "~8.2",
    "symfony/console":                  "~2",
    "symfony/twig-bridge": "~2",
    "php": ">=5.6",
    "composer-plugin-api": "^1.0.0",
    "dflydev/dot-access-data": "^1.0"
  },
  "autoload": {
    "psr-4": {
      "Acquia\\Blt\\": "src/",
      "Acquia\\Blt\\Tests\\": "tests/phpunit/src/"
    }
  },
  "extra": {
    "class": "Acquia\\Blt\\Composer\\Plugin"
  },
  "bin": [
    "bin/blt",
    "bin/blt-console"
  ],
  "conflict": {
    "drupal/core": "7.*"
  },
  "suggest": {
    "hirak/prestissimo": "^0.3"
  },
  "minimum-stability": "beta",
  "prefer-stable": true,
  "scripts": {
    "install-blt-alias": "blt install-alias -Dcreate_alias=true"
  }
}

```

**Comment by grasmash** [comment]
Yes, the fundamental `blt create-project` is not executing successfully. Oddly, it's outputting `You must run this command from within a BLT-generated project repository.` which means that `-f "$GIT_ROOT/vendor/acquia/blt/blt.sh"` is evaluating as false.

Can you please:
1. Update composer with `composer self-update`
1. Update to the latest version of git
1. Verify that `vendor/acquia/blt/blt.sh` does exist
1. Execute `echo $(git rev-parse --show-cdup)` from repo and share the output
1. Try running this in a normal terminal session rather than a DevDesktop terminal session.

**Comment by grasmash** [comment]
The composer.json file that you shared is the composer.json file belonging to BLT. You should not clone BLT onto your machine at all.

By `create-project` I was referring to composer's `create project` command which you are running in the form of `composer create-project acquia/blt-project blt_test --no-interaction`.

Are you perhaps running this command inside of the BLT repo? You should not be in a git repository when you run this command, as that would cause the creation of a git submodule and wreak havoc with git's ability to find the root repository's directory.

**Comment by aangelinsf** [comment]
That was the issue. I was following: 
https://www.youtube.com/watch?v=BrsZAyfj2tE

You might want to take that down. The first thing is says to do is clone the repo.

**Comment by ykokcha** [comment]
when I run the composer bit-alias I get the below error: 
[InvalidArgumentException]           
 Command "blt-alias" is not defined.

Did anyone figure out what this might be? I am following the latest instructions for BLT. Thank you in advance.

**Comment by geerlingguy** [comment]
We hit this on a project recently, after a developer had inadvertently updated to the latest version of BLT (8.6.11), then needed to revert back to 8.6.6 until the project was upgraded.

We had to run `composer install` to get the right version of BLT again, and then the BLT script should start working normally.
