### ISSUE TITLE
Document a typical update process, including BLT and a major dependency

### ISSUE THREAD

**Issue by jrbeeman** [acquia/blt#493]
I had an "a ha!" moment today as I updated my project to Drupal core 8.2.0 and Lightning 8.1.06: BLT needs to be updated in a separate step because updating BLT may result in changes to your project's composer.json. e.g. today's 8.4.7 update included a patch to Features as a resolution to #479.

As a developer, I would like this typical update workflow to be documented.

Steps that worked for me today:

```
composer update acquia/blt
composer update
```

**Comment by grasmash** [comment]
This is buried in the command line output after you update acquia/blt:

```
Updating BLT templated files
This may have modified your composer.json and require a subsequent `composer update`
```

The docs may be a better place for it :)

**Comment by steveworley** [comment]
Could it be an idea to add a `post-package-update` script that ran `@composer update`?

**Comment by grasmash** [comment]
`composer update` doesn't always need to be run after updating acquia/blt--only when the update has caused a change to composer.json. For that reason, I'd like to run it only conditionally.

We may be able to actually detect a change and then call `composer update`, but I'm concerned about the potential for an infinite loop.

We would do a comparison before/after this line:
https://github.com/acquia/blt/blob/8.x/src/Composer/Plugin.php#L122
