### ISSUE TITLE
Update Documentation for BLT under WSL

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#509]
Running BLT under the Windows Subsystem for Linux (Ubuntu Bash) is a little more complicated than is currently stated in the documentation—though there are some parts that I think we can consolidate and make simpler.

I'm working on rebuilding BLT + Drupal VM a few times on my old Lenovo running Windows 10, and I found a few extra tips and tricks to help get everything working correctly.

I'll submit a PR with proposed changes/additions, and I'll also add a few notes to this issue for posterity/background.

**Comment by geerlingguy** [comment]
Eh... one weird thing—I'm getting the following error message whenever Drupal VM hits the `Run drush to finish setting it up` task:

```
Drush was not found in this project's vendor/bin directory.
```

And it tries to install _all_ the project dependencies (including phantomjs-installer and a zillion other things) instead of just... running `/usr/local/bin/drush`.

The only place on the internet I've seen that message is in here: https://github.com/mariagwyn/mariagwynBLT/blob/master/drush.wrapper — what's this used for?

Also, how is it that if I `vagrant ssh` into the VM and literally run `/usr/local/bin/drush`, Drush seems to work just fine, printing out it's built-in help?

**Comment by geerlingguy** [comment]
Ah, that's just a fork... it's in https://github.com/acquia/blt/blob/8.x/template/drush.wrapper

**Comment by geerlingguy** [comment]
So I guess @grasmash how is this thing supposed to work, and how is it possible that running the command `/usr/local/bin/drush` during Vagrant provisioning is getting wrapped by this wrapper?

**Comment by grasmash** [comment]
@geerlingguy When the `drush` command is run from within the repository, it looks for and runs drush.wrapper. The wrapper script tells the global install of drush to use the repo's vendor/bin/drush as its binary. It essentially overrides global drush. However, we need to make sure that composer dependencies have actually been built before attempting to execute vendor/bin/drush, hence the call to `composer install`. We might be able to change this to`composer install drush/drush`.

**Comment by geerlingguy** [comment]
I'm trying to pull down the latest dev:

```
composer create-project acquia/blt-project test --stability dev --no-interaction
```

But that doesn't seem to work :/

**Comment by geerlingguy** [comment]
Ah, just realized blt-project is not BLT... https://github.com/acquia/blt-project/blob/8.x/composer.json

To get the latest commit, I have to clone BLT manually and run the commands separately.

**Comment by geerlingguy** [comment]
@grasmash - I'm going to putz around with it on the windows environment/VM today and see if I can get it working.

Note that if we are able to get rid of the dependency on phantomjs, this problem (like many others) would go away :)

**Comment by geerlingguy** [comment]
On latest master the build fails with:

"PhantomJS v1.9.8 is already installed. Skipping the installation." :P

**Comment by geerlingguy** [comment]
Testing with `composer require drush/drush` inside the drush wrapper...

**Comment by geerlingguy** [comment]
Ah, so the reason why `drush.wrapper` seems to be failing is that the symbolic link—which is created during BLT setup in the Ubuntu Bash environment—is not working inside the VM.

If I ssh into the VM, then run `ls -lah /vagrant/vendor/bin`, I get:

```
[...]
ls: cannot read symbolic link drush: Protocol error
[...]
lrwxrwxrwx 1 vagrant vagrant   20 Oct  7 16:06 drush
```

**Comment by geerlingguy** [comment]
Fun times...

```
Symlinks are supported within the Linux filesystem, but not on `/mnt/`…

We’re looking into fixing this in the future.
```

Found here: https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/#yhiOMwz0h3iI2FQt.97

**Comment by geerlingguy** [comment]
https://github.com/acquia/blt/pull/515 to fix the above issue.

**Comment by geerlingguy** [comment]
So a few more notes (just to keep myself up to date):

  1. Required to get Drupal VM default box config working after PHP 5.6 change: https://github.com/acquia/blt/pull/503
  2. Required to get Drupal VM running on Windows (at least under Ubuntu bash, didn't have time to test with Cygwin or Cmder yet): https://github.com/acquia/blt/pull/515

**Comment by grasmash** [comment]
All relevant pull requests merged.
