### ISSUE TITLE
Space in project directory path causes initial composer create-project to fail. 

### ISSUE THREAD

**Issue by guitarte** [acquia/blt#514]
When following the steps for creating a new project:

- http://blt.readthedocs.io/en/latest/readme/creating-new-project/

If your directory path to the project contains a space, it will fail with the following error:

```
> rm -f .travis.yml
> rm -f README.md
> rm -f LICENSE.txt
> blt create-project
./vendor/acquia/blt/blt.sh: line 4: cd: /Users/christopher.guitarte/space: No such file or directory
./vendor/acquia/blt/blt.sh: line 8: /phing: No such file or directory
Script blt create-project handling the post-create-project-cmd event returned with error code 127
```

For more details on the variables that were being called for the directories that were identified missing, I added a `set -x` in the blt.sh script that gets called during the create-project process and attached my full bash output here:

- http://pastebin.com/zirWFq6V

**Comment by nhoag** [comment]
Might want to consider running `shellcheck` on the `*.sh` files in this repo to catch other occurrences:

```
# Full report
find . -type f -name '*.sh' | xargs -I {} shellcheck {} >> ./shellcheck-report.txt
# Number of locations where word-splitting can introduce bugs
find . -type f -name '*.sh' | xargs -I {} shellcheck {} | grep -c 'word splitting'
56
```

* https://www.shellcheck.net/
