### ISSUE TITLE
Distinction needed between 'CI' environment and 'local' environment

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#52]
Currently, there are some things, like the `setup` tasks (specifically, `setup:drupal:settings` and `setup:drupal:install`), which are used both for local environment builds and for Travis CI (and other CI) builds.

This makes trying to have a different configuration for CI and local environments difficult (and close to impossible, if you don't know where to adjust drush aliases, drush overrides for phing, mysql settings, etc.).

We need to be able to have Phing use CI environment targets (and maybe a `ci` Drush alias instead of `local`/`remote`) that are able to be different than local targets. The main things that are different in my case:

  - I had to set `drush.root` to `''` in my `build/phing/custom/phing/build.yml` override file, so I could control the docroot via Drush aliases.
  - I added two drush aliases to `drush/aliases/aliases.drushrc.php`: `[subname].ci` (for Travis environment), and `[subname].local` (for Local env).
  - I also had to include some travis-ci environment overrides so I could have different MySQL database connection settings for Drupal (thanks to @aweingarten for this suggestion!).

Added `travis.settings.php` file:

```php
<?php

if (getenv('TRAVIS')) {
  $databases = array(
    'default' => array(
      'default' => array(
        'database' => 'subname',
        'username' => 'root',
        'password' => '',
        'host' => 'localhost',
        'port' => '3306',
        'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
        'driver' => 'mysql',
        'prefix' => '',
      ),
    ),
  );

  $base_url = 'http://127.0.0.1:8888';
}
```

(Loaded by adding the following to `default.local.settings.php`):

```php
<?php
/**
 * Load Travis CI overrides.
 */
if (file_exists(DRUPAL_ROOT . '/sites/default/settings/travis.settings.php')) {
  require DRUPAL_ROOT . '/sites/default/settings/travis.settings.php';
}
```

Updated Drush alias file that's checked in and shared with the team:

```php
<?php
$aliases['subname.ci'] = array(
  'root' => '/home/travis/build/organization/repo/docroot',
  'uri' => 'http://127.0.0.1:8888',
);

$aliases['subname.local'] = array(
  'root' => '/var/www/organization/docroot',
  'uri' => 'local.repo.com',
  'remote-host' => 'local.repo.com',
  'remote-user' => 'vagrant',
  'ssh-options' => '-i ~/.vagrant.d/insecure_private_key',
);
```

**Comment by geerlingguy** [comment]
I also had to update the `site-install` drush command to point to the `ci` drush alias instead of the local one:

```xml
<drush command="site-install" assume="yes" verbose="TRUE" alias="${drush.aliases.ci}">
```

**Comment by grasmash** [comment]
Agreed, this would be an improvement.

**Comment by danepowell** [comment]
Does this still need work, or is it resolved by the linked commits?

**Comment by grasmash** [comment]
I think it's resolved.
