### ISSUE TITLE
DrupalVM init fails due to missing package php-bz2

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#521]
The php-bz2 package defined in [config.yml](https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/config.yml#L85) doesn't exist for Ubuntu Trusty, causing Vagrant provisioning to fail.

This only became a problem yesterday when the DrupalVM box was downgraded from Xenial to Trusty. See #501 and #502.

**Comment by geerlingguy** [comment]
@danepowell - see my note on #502: https://github.com/acquia/blt/pull/502#issuecomment-252392802

**Comment by geerlingguy** [comment]
To fix in the interim, make the following changes to your `config.yml`:

  - `installed_extras`: remove this variable entirely (unless, of course, you need `subversion` for some reason)
  - Add the variable: `php_pecl_extensions: ['bz2']`

**Comment by geerlingguy** [comment]
(That should _hopefully_ keep things working with PhantomJS, since the PECL install will get `bz2`, and the `bcmath` extension _seems_ like it should be part of PHP-FPM, which is installed by default.)

**Comment by danepowell** [comment]
Thanks, we can work around it locally in the meantime but I do think it would be good to have it build cleanly before the next release, whichever route that implies.

**Comment by grasmash** [comment]
@danepowell Can you share your workaround? @geerlingguy's changes alone do not seem to be enough.

**Comment by danepowell** [comment]
I'm sorry to say that our "workaround" was just to remove the bz2 package from the configuration altogether, since we don't run Behat tests within the VM.

I don't know of any workaround that would allow you to provision the VM and run PhantomJS in it, other than what @geerlingguy proposed.

**Comment by grasmash** [comment]
PhantomJS has been replaced with Selenium. I'm still working out Drupal VM integration issues. Will be in next released.

**Comment by geerlingguy** [comment]
FYI, Alex's Selenium role is almost to a point where it can get a new tagged release, and the new default will be Chrome instead of Firefox. I'll get Drupal VM updated ASAP after that.
