### ISSUE TITLE
Error after deploying artifact branch build with blt deploy. 

### ISSUE THREAD

**Issue by szipfel** [acquia/blt#533]
After updating from BLT version 8.4.5 to 8.4.8 the deploy branch created caused an error after it was deployed. 

Fatal error: require(): Failed opening required '/mnt/www/html/site-home/docroot/../vendor/acquia/blt/settings/blt.settings.php' (include_path='.:/usr/local/php5.6/lib/php') in /mnt/www/html/site-home/docroot/sites/default/settings.php on line 748

**Comment by grasmash** [comment]
Hm. That looks like the right include path. There should be a file there. Can you verify that it works locally by running `blt deploy:build` and bootstrapping the artifact in `deploy` dir? If so, I'd take a look at the .gitignore file in the artifact and make sure you're not excluding the settings file.

**Comment by szipfel** [comment]
Thanks for the reply. In the meantime I worked around it by removing the reference to that file (this is a 4 month old version of blt that we have been updating as we go) That seems to have worked. 

I will try your suggestion and update this thread.
