### ISSUE TITLE
OpenSSL Prevents Prestissimo Installation (and other composer requests)

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#536]
During the installation process on MacOS I ran into composer errors at the step (see http://blt.readthedocs.io/en/8.x/readme/creating-new-project):

`$ composer global require "hirak/prestissimo:^0.3"`

The error was:
`[Composer\Downloader\TransportException]                                     
  The "https://packagist.org/packages.json" file could not be downloaded: SSL  
   operation failed with code 1. OpenSSL Error messages:                       
  error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify   
  failed                                                                       
  Failed to enable crypto                                                      
  failed to open stream: operation failed`

I attempted to run a composer self-update and got a similar error. 

Ultimately, this ended up being an issue with the OpenSSL installation. During my original composer installation using Homebrew, the OpenSSL installation got corrupted / caused the process to lock up at the "Using the sandbox" stage, and it didn't recover. 

To correct the issue, I just used homebrew...

`$ brew uninstall openssl`
`$ brew install openssl`

After doing this, composer commands once again executed properly and SSL requests were able to be completed.

**Comment by grasmash** [comment]
Thanks for documenting this here in an issue. Closing since there's no action to take.
