### ISSUE TITLE
Doctor doesn't recognize Dev Desktop sites

### ISSUE THREAD

**Issue by aangelinsf** [acquia/blt#558]
OS: macOS 10.12
Dev Desktop Version: 2
Built: Sep  5 2016 04:24:06

== Steps ==
1. Use composer to make a new site, edit project.yml, add to Dev Desktop, run "blt local:setup."
2. Run "blt doctor"

== Result ==
"Did not get a response from http://rh-d8.localhost
  Is your *AMP stack running?
  Is your web server configured to serve this URI from /Users/andreangelantoni/Sites/rh-d8/docroot?
  Is $options['uri'] set correctly in /Users/andreangelantoni/Sites/rh-d8/docroot/sites/default/local.drushrc.php?
To generate settings files and install Drupal, run `blt local:setup`"

== Expected result ==
"blt doctor" seems to look for site in a VM (".localhost") but not those in Dev Desktop.
Could teach the good doctor how to distinguish between the two types of installation.

**Comment by grasmash** [comment]
Have you set the project.hostname in project.yml to be the hostname of your dev desktop site?

**Comment by grasmash** [comment]
Closing due to no response. I believe an improperly set project.hostname is the cause.

**Comment by aangelinsf** [comment]
My apologies for the delay. Moving lots of pieces for a new project forward.

Error still outstanding. Will create a new issue.

**Comment by aangelinsf** [comment]
Actually, changing the project.yml file then re-generating doesn't work. Had to start from the beginning.

Changing hostname to ${project.machine_name}.dd:8083 worked.
