### ISSUE TITLE
Doctor doesn't recognize DEVDESKTOP_DRUPAL_SETTINGS_DIR on Dev Desktop

### ISSUE THREAD

**Issue by aangelinsf** [acquia/blt#559]
OS: macOS 10.12
Dev Desktop Version: 2
Built: Sep  5 2016 04:24:06

== Steps ==
1. Use composer to make a new site, edit project.yml, add to Dev Desktop, run "blt local:setup."
2. Add the following to the end of .bash_profile:
export PATH="/Applications/DevDesktop/mysql/bin:$PATH"
export DEVDESKTOP_DRUPAL_SETTINGS_DIR="$HOME/.acquia/DevDesktop/DrupalSettings"
3. Open new terminal
4. Run "blt doctor"

== Result ==
DevDesktop usage is enabled, but $DEVDESKTOP_DRUPAL_SETTINGS_DIR is not set in your environmental variables.                                                            [error]
  Add `export DEVDESKTOP_DRUPAL_SETTINGS_DIR="$HOME/.acquia/DevDesktop/DrupalSettings"` to ~/.bash_profile or equivalent for your system.`

$ echo $DEVDESKTOP_DRUPAL_SETTINGS_DIR
/Users/andreangelantoni/.acquia/DevDesktop/DrupalSettings

== Expected result ==
The good doctor isn't recognizing the variable for some reason but should be since it is confirmed as being set.

**Comment by grasmash** [comment]
I believe this was addressed in https://github.com/acquia/blt/pull/546.
