### ISSUE TITLE
local-sync.xml tasks should use drush instead of exec and aliases

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#56]
This will definitely need a bit of ironing out, but basically, I wanted to use the shipped `local-sync.xml` tasks (`local:sync` and `local:update`) with a VM (Drupal VM), but none of them used aliases, and the fact that `exec` was used instead of `drush` for the commands meant that aliases wouldn't load correctly.

Therefore, it would be helpful if we switched to `drush` and also used a `@subname.[env]` alias for each command.

Finally, a few of the tasks don't work at all out of the box, like `fra` (unless the project is using Features) and `config-import`, which requires a `partial` directory to already be present (not necessarily the case).

Here's what I have working currently with Drupal VM (though this is by not means what I think we should end up with):

```xml
<project name="local" default="local:refresh">

  <target name="local:refresh" description="Refreshes local environment from upstream testing database." depends="setup:build:all, local:sync, local:update"/>

  <target name="local:sync" description="Synchronize remote environment with local environment."
          depends="setup:drupal:settings">
    <drush command="sql-drop" assume="yes" verbose="FALSE" alias="${drush.aliases.local}" />
    <drush command="sql-sync @${drush.aliases.remote} @${drush.aliases.local}" assume="yes" verbose="FALSE">
      <option name="create-db"></option>
      <option name="structure-tables-key">lightweight</option>
    </drush>
    <drush command="cc" assume="yes" verbose="FALSE" alias="${drush.aliases.local}">
      <param>drush</param>
    </drush>
    <drush command="cr" assume="yes" verbose="FALSE" alias="${drush.aliases.local}" />
  </target>

  <target name="local:update" description="Update current database to reflect the state of the Drupal file system.">
    <drush command="updb" assume="yes" verbose="FALSE" alias="${drush.aliases.local}">
      <option name="entity-updates"></option>
    </drush>
    <!-- <drush command="config-import" assume="yes" verbose="FALSE" alias="${drush.aliases.local}">
      <param>partial</param>
    </drush> -->
    <drush command="cc" assume="yes" verbose="FALSE" alias="${drush.aliases.local}">
      <param>drush</param>
    </drush>
    <!-- <drush command="fra" assume="yes" verbose="FALSE" alias="${drush.aliases.local}" /> -->
    <!-- <exec dir="${docroot}" command="../hooks/dev/post-db-copy/dev-mode.sh" logoutput="true"/> -->
  </target>

</project>
```

**Comment by danepowell** [comment]
Agreed that not all projects might use features and/or config imports... however I think we need a more sustainable solution than just commenting them out. Maybe the local targets should only exist in `build/custom`

**Comment by grasmash** [comment]
@geerlingguy Given the <exec> tasks use `${drush.cmd}` which is expanded to `${drush.bin} @${drush.aliases.local} -r ${docroot} -l ${multisite.name}`. I'd be happy to switch to using <drush>, but I don't understand what would be different about how it called drush. Can you explain?

Usage of `drush fra` is fairly innocuous given that it won't cause the command to fail if features is not present. The `config-import` call, however, does cause failure. Perhaps we can check for the existence of the partial directory prior to running it? Where exactly is the partial dir supposed to be? In `$conf['config_directory'] . '/partial';` ?

**Comment by danepowell** [comment]
I'm not familiar with a "partial" directory. `config-import` does require that the directory `config/default` be present, which it is in Bolt (it's empty except for a README file). It should be harmless as-is.

**Comment by malikkotob** [comment]
@grasmash, @geerlingguy, also ran into the same issue where using the `<drush>` syntax worked for me, and `<exec>` failed:
```
project > local:sync:

     [exec]  [error]  Unable to load class Drush\Sql\Sql
     [exec]  [error]  exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.' in /usr/local/share/drush/commands/sql/sql.drush.inc:588
     [exec] Stack trace:
     [exec] #0 /usr/local/share/drush/commands/sql/sql.drush.inc(441): drush_sql_get_class()
     [exec] #1 [internal function]: drush_sql_drop()
     [exec] #2 /usr/local/share/drush/includes/command.inc(366): call_user_func_array('drush_sql_drop', Array)
     [exec] #3 /usr/local/share/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
     [exec] #4 [internal function]: drush_command()
     [exec] #5 /usr/local/share/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
     [exec] #6 /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php(73): drush_dispatch(Array)
     [exec] #7 /usr/local/share/drush/includes/preflight.inc(88): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
     [exec] #8 /usr/local/share/drush/drush.php(12): drush_main()
     [exec] #9 {main}
     [exec]  [error]  Error: no alias record could be found for source @.test
     [exec]  [notice] 'drush' cache was cleared.
     [exec]  [error]  Command cache-rebuild needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.
     [exec]  [error]  Command cache-rebuild requires Drupal core version 8+ to run.
     [exec]  [error]  The drush command 'cache-rebuild' could not be executed.
```

**Comment by damontgomery** [comment]
I'm actually encountering the opposite issue. I can use the exec commands once I set build.yml drush:cmd to remove -r.

When running BLT on the drush commands, since it doesn't support a directory option, all the commands run outside of docroot and drush cannot find anything. Solution seems to be to either use exec where we can specify the directory or extend the DrushTask to support the directory option.

**Comment by grasmash** [comment]
#276 may have resolved the drush.root issues.

**Comment by grasmash** [comment]
@geerlingguy Is this still an issue? There have been a number of changes to BLT that may have resolved this.

**Comment by geerlingguy** [comment]
@grasmash - https://github.com/acquia/blt/blob/8.x/phing/tasks/local-sync.xml still uses `exec`/`command` instead of `drush`/`command`, so the original issue still stands. It's not a functional problem, just a 'it seems like it would be cleaner to use `drush` in phing instead of `exec`' kind of thing.
