### ISSUE TITLE
Doctor fails on new install in Dev Desktop

### ISSUE THREAD

**Issue by aangelinsf** [acquia/blt#560]
OS: macOS 10.12
Dev Desktop Version: 2
Built: Sep 5 2016 04:24:06

== Steps ==
1. Use composer to make a new site, edit project.yml, add to Dev Desktop, run "blt local:setup."
2. Add the following to the end of .bash_profile:
export PATH="/Applications/DevDesktop/mysql/bin:$PATH"
export DEVDESKTOP_DRUPAL_SETTINGS_DIR="$HOME/.acquia/DevDesktop/DrupalSettings"
3. Open new terminal
4. Run "blt doctor"

== Result ==
See previous issues for other problems. This happens at the very end:

"Changed current directory to /Users/andreangelantoni/.composer
    [drush] Changing working directory back to /Users/andreangelantoni/Sites/rh-d8/vendor/acquia/blt/phing.

BUILD FAILED
/Users/andreangelantoni/Sites/rh-d8/vendor/acquia/blt/phing/tasks/blt.xml:12:4: Drush exited with code 1

Total time: 0.9926 seconds"

== Expected result ==
Not expecting to see "build failed" — not sure what a successful complete looks like.

**Comment by grasmash** [comment]
I cannot reproduce this. Please share the following: 

* Your version of BLT, composer info acquia/blt
* Your operating system
* The **full** log output of your BLT command, wrapped in a codeblock.

**Comment by grasmash** [comment]
Closing due to no response.

**Comment by aangelinsf** [comment]
This may have been related to #558 because after fixing that this is no longer occurring.
