### ISSUE TITLE
Behat tests fail on Dev Desktop

### ISSUE THREAD

**Issue by aangelinsf** [acquia/blt#561]
OS: macOS 10.12
Dev Desktop Version: 2
Built: Sep 5 2016 04:24:06

== Steps ==
1. Use composer to make a new site, edit project.yml, add to Dev Desktop, run "blt local:setup."
2. Add the following to the end of .bash_profile:
export PATH="/Applications/DevDesktop/mysql/bin:$PATH"
export DEVDESKTOP_DRUPAL_SETTINGS_DIR="$HOME/.acquia/DevDesktop/DrupalSettings"
3. Open new terminal
4. Run "blt doctor"

== Result ==
" [echo] Waiting 10 seconds for PhantomJS (http://127.0.0.1:4444) to become available.
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444
Possible malformed URL: http://127.0.0.1:4444"

blt > tests:behat:

    [mkdir] Created dir: /Users/andreangelantoni/Sites/rh-d8/reports/behat

blt > tests:behat:execute:

     [exec] /Users/andreangelantoni/Sites/rh-d8/tests/behat/features/Examples.feature
    [behat] Running '/Users/andreangelantoni/Sites/rh-d8/vendor/bin/behat /Users/andreangelantoni/Sites/rh-d8/tests/behat --config=/Users/andreangelantoni/Sites/rh-d8/tests/behat/local.yml --tags="~ajax" --format=pretty --format=junit  --out=std --out=/Users/andreangelantoni/Sites/rh-d8/reports  --profile=local --strict --verbose --colors'
@javascript
Feature: Selenium Test
  In order to test if Selenium is working
  As a user
  I need to be able to load the homepage

  Scenario: Load a page                 # features/Examples.feature:7
    Given I am on "/"                   # Drupal\DrupalExtension\Context\MinkContext::visit()
      WebDriver\Exception\CurlExec: Curl error thrown for http POST to http://127.0.0.1:4444/wd/hub/session with params: {"desiredCapabilities":{"tags":["Andres-Mac-Pro.local","PHP 7.0.8"],"browser":"firefox","ignoreZoomSetting":false,"name":"Behat feature suite","browserName":"chrome"}}
      
      Failed to connect to 127.0.0.1 port 4444: Connection refused in /Users/andreangelantoni/Sites/rh-d8/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155

<snipped stack trace}

     Next Behat\Mink\Exception\DriverException: Could not open connection: Curl error thrown for http POST to http://127.0.0.1:4444/wd/hub/session with params: {"desiredCapabilities":{"tags":["Andres-Mac-Pro.local","PHP 7.0.8"],"browser":"firefox","ignoreZoomSetting":false,"name":"Behat feature suite","browserName":"chrome"}}
      
      Failed to connect to 127.0.0.1 port 4444: Connection refused in /Users/andreangelantoni/Sites/rh-d8/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php:290

blt > tests:phantomjs:kill:

     [exec] Executing command: pgrep phantomjs | xargs kill
  [foreach] /Users/andreangelantoni/Sites/rh-d8/vendor/acquia/blt/phing/tasks/tests.xml:27:4: /Users/andreangelantoni/Sites/rh-d8/vendor/acquia/blt/phing/tasks/tests.xml:43:8: /Users/andreangelantoni/Sites/rh-d8/vendor/acquia/blt/phing/tasks/tests.xml:48:12: One ore more Behat tests failed.

BUILD FAILED
/Users/andreangelantoni/Sites/rh-d8/vendor/acquia/blt/phing/tasks/tests.xml:13:4: Execution of the target buildfile failed. Aborting.

Total time: 10.9698 seconds

**Comment by grasmash** [comment]
This is almost certainly the same issue as https://github.com/acquia/blt/issues/558. I suspect that you do not have your project.hostname set correctly in project.yml, and subsequently do not have base_url set correctly in test/behat/local.yml.

**Comment by grasmash** [comment]
Closing due to no response. I believe the issue is diagnosed in #558.
