### ISSUE TITLE
Provide an option to create a tag with the deploy task

### ISSUE THREAD

**Issue by seanhamlin** [acquia/blt#583]
At the moment the deploy task will create and push a commit, I would love to also have a tag in a standardized format. Tags are best practice to be released to Acquia Cloud and Site Factory.

e.g.

```
git tag YYYY-MM-DD.[INCREMENT]
```

e.g. the first tag today would be `2016-10-18.1`.

**Comment by grasmash** [comment]
Duplicate of https://github.com/acquia/blt/issues/17
