### ISSUE TITLE
Add blt target for use in cloud-hooks

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#594]
Currently most projects are reinventing the wheel by creating their own cloudhooks to deploy CMI, updb and features.  Ideally we would have an "acquia:setup:update" task that we can call via cloudhook. 

1: Create new phing task "acquia:setup:update"
2: Update cloudhook directory with commented out template files that call "acquia:setup:update"
3: Document ^^

**Comment by danepowell** [comment]
This seems very closely aligned with #589 

If we're talking about the same thing, I actually don't think we want a completely separate command for this. What I'd like to see is a way to way to run the same "update" command (i.e. `local:update`) both locally and on ACE.

**Comment by danepowell** [comment]
I guess a dedicated deploy target would be helpful, for a few reasons. Mainly because the drush alias on ACE is generally going to be different

**Comment by danepowell** [comment]
I think I will create a `deploy:update` target that just calls `setup:update` with `drush.alias = self`. @grasmash or @aweingarten any objections or suggestions?

**Comment by grasmash** [comment]
#589 addresses this.
