### ISSUE TITLE
Automated builds - Passing parameter to blt install-alias?

### ISSUE THREAD

**Issue by justinlevi** [acquia/blt#595]
I'm trying to create a build script and I'm trying to automatically send "y" to the following command:

`blt install-alias`

I've tried: 

`./vendor/bin/blt install-alias -Dy`
`./vendor/bin/blt install-alias -y`

I feel like this is probably super simple and I'm just not thinking right now...

**Comment by grasmash** [comment]
Try `blt install-alias -Dcreate_alias=true` and if that doesn't work, `yes | blt install-alias`

**Comment by grasmash** [comment]
Though on an automated build I actually wouldn't install the alias. I'd use `blt ci:build:validate:test -Dcreate_alias=false` and just add `vendor/bin` to `$PATH`. I'd suggest looking at .travis.yml:

* Modifying $PATH: https://github.com/acquia/blt/blob/8.x/.travis.yml#L57
* Building and testing: https://github.com/acquia/blt/blob/8.x/.travis.yml#L99

**Comment by justinlevi** [comment]
@grasmash Thanks for the quick response!

I should have been more clear about what I meant as far as "automated" as this it's not for Travis but rather just to speed up getting setup on a local dev environment.
