### ISSUE TITLE
Add patch for .htaccess for SSL Only on Acquia Cloud

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#598]
On most projects I add the following snippet to HTACCESS:

```
  # Redirect HTTP to HTTPS on cloud
  RewriteCond %{ENV:AH_SITE_ENVIRONMENT} !^$
  RewriteCond %{HTTPS} off
  RewriteCond %{HTTP:X-Forwarded-Proto} !https
  RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

This snippet will redirect all traffic from HTTP to HTTPS but only on Acquia Cloud.  It leaves a dev's local environment untouched!  That this might be a good baseline for other projects.  Thoughts?  Or too proscriptive?

**Comment by danepowell** [comment]
It would be nice to have some sort of configuration in BLT that adds this automatically if set, and prevents it from being clobbered on updates. Same for the simplesaml .htaccess alias. Right now any time you run composer update, .htaccess gets overwritten.

**Comment by grasmash** [comment]
Why not just make it a patch against core?

**Comment by aweingarten** [comment]
@grasmash exactly! Does this feel like a sane default core patch?

**Comment by greylabel** [comment]
I think it would be great to include this patch and maybe a note in the docs, even if it is not applied by default.

**Comment by grasmash** [comment]
I agree. Include somehow but do not apply by default. Maybe a target that adds this to composer.json would work.

**Comment by danepowell** [comment]
I can try creating a patch for this and for SAML (to make sure they don't conflict).

If we're patching .htaccess, should we just take it out of the repo entirely? I thought the only reason it exists in docroot is because it's "meant" to be overridden.

**Comment by aweingarten** [comment]
I was thinking maybe we add it as a default patch in composer.json?

**Comment by danepowell** [comment]
I'm not sure about making it a default. Even if we assume every project uses SSL (which would be awesome, but not necessarily true), it's usually not set up from day 1.

I was just wondering if the .htaccess file itself still needs to exist in docroot, or if composer would copy it there automatically.

**Comment by danepowell** [comment]
I added the patches as #602. There are ways we'd both like to improve this, but I'm not sure how much more we can do right now...

**Comment by danepowell** [comment]
Good to close this?

**Comment by grasmash** [comment]
Yeah I think this is good for now. Fairly simple for someone to add these to their composer.json.

**Comment by danepowell** [comment]
Note that these patches can't in fact be added to composer.json. See https://github.com/acquia/blt/issues/608
