### ISSUE TITLE
Clean up repo root--move top-level BLT files into their own directory

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#604]
There are a lot of BLT-specific files in the repository root for a "blted" project that aren't required by technological constraint to be there and which probably are not the subject of daily work for most project team members. Since there's already a precedent for a top level `blt` directory, I propose moving as many such files as possible in there--for example, the following:
- `example.project.local.yml`
- `project.local.yml`
- `project.yml`
- `salt.txt`

This has the benefit of decluttering the repo root as well as of adding context to these files that clarifies their role in the application without having to open them.

**Comment by grasmash** [comment]
I agree. Though, I don't love moving them since it's obviously not backwards compatible. Once I merge #601 and we have a mechanism for one time updates, I think this will be more feasible.
