### ISSUE TITLE
Automate / allow overrides of .htaccess for SSL and SAML

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#608]
As part of #602 we added sample patches to add SSL and SAML support to .htaccess. I thought these worked at the time, but now it seems like they aren't working. I suspect it's because drupal-scaffold doesn't support patching these files: https://github.com/drupal-composer/drupal-scaffold/issues/45

I think we should remove the sample patches, and somehow work with drupal-scaffold to patch .htaccess and keep it from being clobbered on updates.

**Comment by danepowell** [comment]
cc @aweingarten

**Comment by grasmash** [comment]
You can instruct [Drupal Scaffold](https://github.com/drupal-composer/drupal-scaffold) to ignore certain files:

```
{
  "extra": {
    "drupal-scaffold": {
      "excludes": [
        ".htaccess",
        "robots.txt"
      ]
    }
  }
}
```

**Comment by danepowell** [comment]
It sounds like we'd have to add that ignore and then patch the file somehow outside of Composer. The challenge would be keeping it in sync with whatever Drupal core version is in use on the project.

**Comment by mike-potter** [comment]
I recommend updating the README file to reflect the fact that this is not working.  As mentioned in #483 the instructions and link for using external patch files in the README is wrong anyway and doesn't actually explain how to add files in ./patches to composer.json.

**Comment by danepowell** [comment]
@grasmash @mike-potter thanks for the feedback, please review the changes in #1157 and let me know what you think.

**Comment by grasmash** [comment]
@mike-potter Thanks for your feedback.
