### ISSUE TITLE
Broken link to next-steps.md from creating-new-project.md

### ISSUE THREAD

**Issue by tashbaugh** [acquia/blt#612]
In the https://github.com/acquia/blt/blob/8.x/readme/creating-new-project.md page there is a broken link to next-steps.md. A quick search on the repo shows next-steps.md doesn't exist, what page should it link to? Or was this page accidentally omitted from the repo?

**Comment by kevinquillen** [comment]
Was just coming here to report this.

**Comment by grasmash** [comment]
Thank you. Resolved in #614
