### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#622]
I see that the current TravisCI build is failing and I am also seeing builds failing locally with the same error. 

The error is related to applying the patch from [this issue](https://www.drupal.org/node/2818031).

**Comment by danepowell** [comment]
This is not actually a problem with BLT, but with Lightning, which includes this core patch.

This is fixed in https://github.com/acquia/lightning/commit/dd2a4d6a2bf97be127acbc2f5ad1d93c8755a66e

**Comment by grasmash** [comment]
Since BLT currently uses Lightning 8.1.x-dev, this change is already in BLT. We will pin to the next stable release when it is available.

**Comment by grasmash** [comment]
And it actually looks like a new Lightning release came out yesterday! Updating...

**Comment by grasmash** [comment]
Builds are now passing and Lightning has been updated to 8.1.12 in #631
