### ISSUE TITLE
Automatically populate machine name for new projects

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#624]
When you spin up a new project with a command like:

> composer create-project acquia/blt-project MY_PROJECT --no-interaction

It would be nice if the machine name in project.yml was automatically set to MY_PROJECT.

It's not a big deal, but it would be a nice convenience for folks like me spinning up projects for testing pretty frequently.

**Comment by grasmash** [comment]
@danepowell Have you tried using https://github.com/acquia/club ?
