### ISSUE TITLE
Plans for compatibility with Drupal 7? 

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#636]
Thanks for putting this tool together, it's very impressive and looks to be a great starting point for getting Drupal 8 projects off the ground.

That said, are there any plans to make it compatible with Drupal 7? Or, at the very least can you suggest what changes you think would be necessary in order to accommodate new and existing Drupal 7 projects?

**Comment by grasmash** [comment]
I'm sorry, there are no plans for this. We actually began BLT on D7 and ported it to D8. It's simply too much work to upkeep both branches, and they are significantly different.

**Comment by bobbygryzynger** [comment]
@grasmash - thanks for your response. I figured as much but thought I'd ask anyway. Any chance you'd be willing to share the work done pre-port if it still exists anywhere?

**Comment by grasmash** [comment]
Well, I can't publish anything new, but I can tell you that an early incarnation of BLT was used on this already open-sourced repo: https://github.com/CityOfBoston/boston.gov

Note that at this point, BLT was not a composer package. All tasks were run through `./task.sh [target]`. CoB has also modified the underlying logic to suit some project-specific requirements. They've posted some instructions for setup here: https://github.com/CityOfBoston/boston.gov/blob/develop/guides/02-setting-up-development.md#setting-up-your-local-environment
 
Best I can do for you!

**Comment by bobbygryzynger** [comment]
Thanks @grasmash - much appreciated!
