### ISSUE TITLE
Installation script fails when using VM and configuration directory exists

### ISSUE THREAD

**Issue by malikkotob** [acquia/blt#64]
As part of setup:drupal:install, it checks to see if configuration exists at /config/default. If it does, it attempts to perform the site installation with the config-dir option, and sets its value equal to `${repo.root}/config/default` in the setup.xml (`<option name="config-dir">"${repo.root}/config/default"</option>`). The {repo.root} value points to the path on the host machine, but because the site installation technically takes place within the VM, it is unable to locate the config source directory:

```
 [drush] The config source directory does not exist.                                                                  [error]
 [drush] Command dispatch complete                                                                                   [notice]
```

**Comment by grasmash** [comment]
Hm. In general, some operations will be run on the host machine, and some will be run on the VM. We'll need different paths depending on where the specific command should run.

The options as I see it are:
1. Use a relative path
2. Introduce a new variable, containing the VM path, which is used for specific targets. 

Is it possible to simply use `../config/default` ?

**Comment by grasmash** [comment]
config-dir is no longer used for the config-import task. DRUPAL_ROOT relative value is now used via settings.php.
