### ISSUE TITLE
development.services.yml gets clobbered on updates

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#641]
When you run `composer update` on a BLT project, it clobbers the customizations we made to development.services.yml in #482. I think the reason is that drupal-scaffold treats this as a 'core' file that exists outside of the drupal/core package (like .htaccess), and that should be dynamically copied on every composer install.

We can stop this behavior using the new "initial" hash: https://github.com/drupal-composer/drupal-scaffold/pull/44/files#diff-04c6e90faac2675aa89e2176d2eec7d8R41

**Comment by grasmash** [comment]
#642

**Comment by danepowell** [comment]
I behavior of the initial hash isn't entirely intuitive, but I'm pretty sure that should work, thanks!
