### ISSUE TITLE
Moving drush to require dependencies interferes with Acquia-provided drush commands on ACE

### ISSUE THREAD

**Issue by timcosgrove** [acquia/blt#647]
With https://github.com/acquia/blt/pull/589/files#diff-ea9cb71454501def51e47bec554a6ff1R25, BLT moved drush into required packages rather than require-dev, so that BLT could make use of drush on ACE.

I think one side effect of this is, Drush as executed by BLT, or via a site-alias, no longer finds the Acquia-provided drush commands that are available at `/usr/local/drush8/commands`. This means in particular that the ACE API drush commands are not available.

I'm not sure of the most appropriate way to make Drush aware of these commands in this setup. Thoughts?

**Comment by grasmash** [comment]
I'm not sure whether drush.wrapper in the repo root is called on ACE, but I'd check it out. We may be able to specify an additional "includes" path for drush commands. I assume that ACE has drush 8, so do we really need to deliver it? We might be able to simply have BLT fallback to global drush if vendor/bin/drush doesn't exist.

**Comment by danepowell** [comment]
I can't remember exactly why I decided to ship our own Drush. I think it just seemed like the easiest way to guarantee that Phing could call it. Matt's idea of changing the drush wrapper to fall back to ACE Drush should make everything hunky dory.

Although I'm curious as to _why_ we can't use our own Drush binary. I thought this was actually best practice in D8.

**Comment by grasmash** [comment]
I suspect it might be due to drush.wrapper specifying an --include option. That option can be an array, and we can actually define it in drushrc.php if we'd prefer. That would let us more easily make it conditional.

**Comment by grasmash** [comment]
@timcosgrove Any chance you can test whether this change resolves your issue? #696

**Comment by grasmash** [comment]
Couple of things... firstly drush.wrapper actually isn't deployed so that's not at play. The submitted PR would work, if we actually loaded `drush/drushrc.php` when running `blt` on ACE. Simply adding `drush.wrapper` might work but it might also cause other complications.

**Comment by timcosgrove** [comment]
@grasmash sorry for not seeing this notification. It's been merged, but I will test it. Thank you for the work!
