### ISSUE TITLE
Is adding BLT to an existing project still a viable option?

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#650]
I have a D8 project based on lightning that is hosted with Acquia. We do local development with DevDesktop at the moment, using a repo separate from the Acquia repo. To "deploy" the code I'm currently rsyncing files to the Acquia repo.

I'd like to add BLT into the mix as a code deployment tool. Essentially my expectation is to run a BLT command that will create a build artifact that is then pushed to my Acquia repo, so I don't have to do the deployments manually like I am now.

I followed the guide here: http://blt.readthedocs.io/en/8.x/readme/adding-to-project/

* Added `"acquia/blt": "^8.5"` to my project.
* Went to step 2 here: http://blt.readthedocs.io/en/8.x/readme/creating-new-project/, which says to install the BLT alias. However this doesn't work because it relies on having a composer script added to your composer file (which is part of the blt template). I found this and added it manually, then it worked.
* Step 3 says to customize the project.yml file, but I don't have that file. It's not clear how to get that file? Running `blt setup` fails as well because it expects that file to be there.

Is there some setup step I'm missing that would bring in these BLT "scaffold" files?

**Comment by grasmash** [comment]
Did you run composer update after adding BLT to composer.json?  That should add the scaffold files automatically.  I did not, you can also run a 'blt update' to do this.

**Comment by bkosborne** [comment]
Thanks. Running `composer update` doesn't appear to copy the files in, but running `blt update` did.

I see that BLT modifies the composer.json file of my project and adds quite a bit. I assume I can rip all of that out? For instance it added "drupal/core" but I already include "drupal/lightning" which itself has a requirement for Drupal core. And it added a few modules I won't use.

**Comment by grasmash** [comment]
Yes, see "Modifying update behavior" on http://blt.readthedocs.io/en/8.x/readme/updating-blt/
