### ISSUE TITLE
Remove $config_directories setting from default.local.settings.php

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#653]
The default settings file includes this snippet:

```
// Configuration directories.
$dir = dirname(DRUPAL_ROOT);
$config_directories['sync'] = $dir . "/config/$site_dir";
```

Doesn't it make more sense to keep this project specific and not local environment specific? The directories where configuration files are stored shouldn't really change per user's local environment.

**Comment by grasmash** [comment]
Are you referring to the value in `default.local.settings.php`? That file is used to generate `local.settings.php` which is only used locally. You're free to create and commit your own `default.local.settings.php` in `sites/default`. BLT will use it for generating `local.settings.php` and will not overwrite it.

**Comment by bkosborne** [comment]
Right, but what I mean is that it doesn't seem to make sense to place it in the `local.settings.php` file (and therefore in the `default.local.settings.php` file) because the config directories are not something that would typically change for each developer, right? Instead it makes sense to place the config directories stuff in the main project `settings.php` file that all environments use.
