### ISSUE TITLE
Travis and D8 CMI

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#657]
It seems odd to me that the default travis behavior doesn't sync configuration beyond the blt setup:drupal:install command. On several projects now I've had to override this default behavior to also then run blt local:update so that stored configuration is imported (particularly so that Behat tests will pass). Does it make sense to include local:update as part of the default Travis / build process so that it doesn't have to be overwritten?

**Comment by grasmash** [comment]
I don't quite understand. I had thought that setup:drupal:install did import all local config. Why would it need to be done again?

**Comment by mikemadison13** [comment]
it def. loads "something" but not everything.

if you take a look at https://travis-ci.org/Drupal4Gov/Drupal-GovCon-2017/builds/175178452 this build failed and then look at https://travis-ci.org/Drupal4Gov/Drupal-GovCon-2017/builds/175198787 this one passed. Literally the only thing that changed was adding blt local:update into the build process.

On my local when I did a clean install, I saw it "load" the configuration, but it didn't actually seem to do anything with it...

I see "create" actions being taken all throughout the config as part of the blt > setup:config-import: step, but still the end result isn't the desired one (the config doesn't make it into active configuration)

**Comment by mikemadison13** [comment]
BTW:

When I do a clean install and it runs the setup:config-import step, then I immediately run blt local:update, this happens:

$ blt > setup:update:

There are no changes to import.                                                                                       [ok]
The following updates are pending:

user entity type : 
  The user.field_company_organization field needs to be installed.
  The user.field_first_name field needs to be installed.
  The user.field_industry field needs to be installed.
  The user.field_last_name field needs to be installed.
  The user.field_motivation field needs to be installed.
  The user.field_number_of_cons field needs to be installed.
  The user.field_role field needs to be installed.
Do you wish to run all pending updates? (y/n): y
Cache rebuild complete.                                                                                               [ok]
Finished performing updates.                                                                                          [ok]
There are no changes to import.                                                                                       [ok]
Cache rebuild complete.                                                                                               [ok]

which leads me to believe that the CMI is somehow staged but not actually fully imported.

**Comment by grasmash** [comment]
Can you experiment a bit with modifying setup:Drupal:install to make it work alone?

**Comment by mikemadison13** [comment]
Yeah, it looks like we should be able to modify setup.xml to include a blt setup:update directly after blt setup:install so that the process just includes the update hook. It's already IN the setup.xml file as a matter of fact, it just isn't called from anywhere (which is odd). 

`<target name="setup:update" description="Update current database to reflect the state of the Drupal file system.">
    
    <drush command="config-import" assume="yes" alias="${drush.alias}">
      <option name="partial"></option>
    </drush>
    
    <drush command="updb" assume="yes" alias="${drush.alias}">
      <option name="entity-updates"></option>
    </drush>
    
    <drush command="config-import" assume="yes" alias="${drush.alias}">
      <option name="partial"></option>
    </drush>
    <if>
      <isset property="cm.features.bundle"/>
      <then>
        
        <drush command="en" assume="yes" alias="${drush.alias}">
          <param>features</param>
        </drush>
        
        <drush command="cc" assume="yes" alias="${drush.alias}">
          <param>drush</param>
        </drush>
        
        <drush command="fra" assume="yes" alias="${drush.alias}">
          <option name="bundle">${cm.features.bundle}</option>
        </drush>
      </then>
    </if>
    
    <drush command="cr" alias="${drush.alias}"/>
  </target>`

**Comment by grasmash** [comment]
Actually, we already do this. See https://github.com/acquia/blt/blob/8.x/phing/tasks/setup.xml#L170.

**Comment by mikemadison13** [comment]
After experimenting a bit, I think what is missing is a drush cr between the setup:config-import and setup:update. In a way, that makes sense, given that the last thing setup:update does is flush the cache. If I put a drush cr into the setup:drupal:install process between those two, everything actually reverts. The issue I'm running into now though is that by doing this, the order of the update script seems slightly out of whack... now when it starts trying to get the proper configuration and import it, I'm getting fatal errors because the toggle modules portion of the script is tripping over something "in" the configuration that hasn't actually been added to the database yet.

`blt > setup:update:

     [echo] You are running BLT with xdebug enabled. This has a major impact on runtime performance.

blt > setup:toggle-modules:

Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'drupal.user__field_company_organization' doesn't exist: SELECT t.*      [error]
FROM 
{user__field_company_organization} t
WHERE  (entity_id IN  (:db_condition_placeholder_0)) AND (deleted = :db_condition_placeholder_1) AND (langcode IN  (:db_condition_placeholder_2, :db_condition_placeholder_3,
:db_condition_placeholder_4)) 
ORDER BY delta ASC; Array
(
    [:db_condition_placeholder_0] => 0
    [:db_condition_placeholder_1] => 0
    [:db_condition_placeholder_2] => en
    [:db_condition_placeholder_3] => und
    [:db_condition_placeholder_4] => zxx
)
 in Drupal\Core\Entity\Sql\SqlContentEntityStorage->loadFromDedicatedTables() (line 1130 of
/var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php) #0 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Database/Connection.php(635):
Drupal\Core\Database\Connection->handleQueryException(Object(PDOException), 'SELECT t.*\nFROM...', Array, Array)
#1 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(81): Drupal\Core\Database\Connection->query('SELECT t.*\nFROM...', Array, Array)
#2 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Database/Query/Select.php(493): Drupal\Core\Database\Driver\mysql\Connection->query('SELECT t.*\nFROM...', Array, Array)
#3 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1130): Drupal\Core\Database\Query\Select->execute()
#4 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(482):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->loadFromDedicatedTables(Array, false)
#5 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(433): Drupal\Core\Entity\Sql\SqlContentEntityStorage->mapFromStorageRecords(Array)
#6 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(399): Drupal\Core\Entity\Sql\SqlContentEntityStorage->getFromStorage(Array)
#7 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(242): Drupal\Core\Entity\Sql\SqlContentEntityStorage->doLoadMultiple(Array)
#8 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php(212): Drupal\Core\Entity\EntityStorageBase->loadMultiple(Array)
#9 /var/www/capitalcamp/docroot/core/lib/Drupal/Core/Entity/Entity.php(499): Drupal\Core\Entity\EntityStorageBase->load(0)
#10 /var/www/capitalcamp/vendor/drush/drush/lib/Drush/User/User8.php(26): Drupal\Core\Entity\Entity::load(0)
#11 /var/www/capitalcamp/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php(556): Drush\User\User8->load_by_uid(0)
#12 /var/www/capitalcamp/vendor/drush/drush/includes/bootstrap.inc(221): Drush\Boot\DrupalBoot->bootstrap_drupal_login()
#13 /var/www/capitalcamp/vendor/drush/drush/includes/bootstrap.inc(340): drush_bootstrap(6, 6)
#14 /var/www/capitalcamp/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_bootstrap_to_phase(6)
#15 /var/www/capitalcamp/vendor/drush/drush/includes/preflight.inc(68): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#16 /var/www/capitalcamp/vendor/drush/drush/drush.php(12): drush_main()
#17 {main}.
`

**Comment by grasmash** [comment]
I've merged #674 to address this. Please let me know if it is not resolved.
