### ISSUE TITLE
blt function (alias) for fish

### ISSUE THREAD

**Issue by ElijahLynn** [acquia/blt#662]
Here is a `blt` function for fish, that closely emulates the bash function. I don't have time to put this in the composer blt-alias script but it is here for the taking!

```
function blt --description "BLT function for the fish shell"
    if test -n (git rev-parse --show-cdup)
        set --global GIT_ROOT (git rev-parse --show-cdup)
    else
        set --global GIT_ROOT "."
    end

    if test -f $GIT_ROOT/vendor/bin/blt
        eval $GIT_ROOT/vendor/bin/blt $argv
    else
        echo "You must run this command from within a BLT-generated project repository."
    end
end
```

**Comment by kylebrowning** [comment]
Get this man a beer🍻🍺🍻🍺🍻

**Comment by kevinquillen** [comment]
Thumbs up, first thing I Google'd and it brought me here.

**Comment by kevinquillen** [comment]
One thing extra I had to do, after saving the alias:

`funcsave blt`

The alias was then available in other terminal windows I had open.

**Comment by ElijahLynn** [comment]
Great to hear it is useful!

Cross linking #284

**Comment by grasmash** [comment]
I don't think that fish support will be added to BLT, but I'm glad to have this documented here. Thanks.

**Comment by devert** [comment]
@ElijahLynn Thanks for providing this helpful function for fish. I went ahead and added it as a plugin that can easily be installed with [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish). You should now be able to just `omf install blt` and be good to go.

**Comment by kylebrowning** [comment]
You may want to change it to 'omf install blt-alias' to avoid confusion with actually installing BLT.

**Comment by kylebrowning** [comment]
You may want to change it to `omf install blt-alias` to avoid confusion with actually installing BLT.
@devert ^

**Comment by janoka** [comment]
Many thanks!

**Comment by ElijahLynn** [comment]
@kevinquillen Thanks, went ahead and added to the example.
