### ISSUE TITLE
Support decryption of variables in settings.php

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#663]
## The problem
Currently the key/encrypt modules work great if a module has been written to use them. If not then you have no way of securely storing sensitive API credentials inside Drupal. Since these are loaded as part of the Drupal container they aren't available early enough in the bootstrap to be used in settings.php

Some examples of API keys stored in DB/repo:
- Acquia Solr
- Acquia Lift
- Acquia Connector
- CloudFlare
- Akamai
- Mailchimp

## Possible Solution
We need a way to store an encryption key outside the git repo. Then use that key to decrypt encrypted settings in settings.php.  

1. we can create an encryption key, with blt target, it's git-ignored by default.  Users would upload them to their web-servers in the home directory.
1. We could in theory create /settings/settings.encryption.php file.
1. This file would contain a decrypt and encrypt function
1. To encrypt you could do a `drush ev "blt_settings_encrypt($mykey)"`
1. To decrypt we could do a `$conf['akamai'] = blt_settings_encrypt($akamai_key)"`

## Bonus
This can be combined with [Issue 659 (https://github.com/acquia/blt/issues/659) to provide a framework to secure a DB and source so that if the db or source is compromised the damage is somewhat contained.  In theory we should be able to make a repo public with nearly 0 impact to the security of the site.

Due to the bootstrap issues it seems like this is the right place to solve this problem.

@CashWilliams ^^

**Comment by grasmash** [comment]
For now, the recommended approach for managing keys on Acquia servers is using this: https://github.com/acquia/blt/blob/8.x/settings/sample-secrets.settings.php

**Comment by grasmash** [comment]
I'm closing this because I do not believe it's within the scope of BLT. This seems like it would best be served by a key management service or a contributed module. If such a thing is developed, I'd be happy to integrate it with BLT.
