### ISSUE TITLE
How to handle D8 config with local/deploy modules

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#670]
The `local:refresh` task will invoke `setup:update` and pass along a list of modules to uninstall from the project.yml file. This is great, except it doesn't really work properly since immediately after the modules are disabled, the config is imported via drush. This basically performs an "undo" operation since the imported config has those modules enabled.

This is sort of a generic problem I'm facing with D8 but something that's readily apparent in my usage of BLT.

Anyone have this problem and a workaround?

**Comment by grasmash** [comment]
Yeah I think we need to change toggle-modules to happen last in order to avoid this.
