### ISSUE TITLE
Project.YML behat.tags : Local Vs. Travis Syntax/Logic

### ISSUE THREAD

**Issue by justinlevi** [acquia/blt#688]
How can I setup my `project.yml` and `project.local.yml` so that I can disable specific behat subcontexts locally but enable them again when running on travis and also commit this in a way the entire team gets this setup?

[From the readme/extending-blt.md](https://github.com/acquia/blt/blob/f0d02496371462c7fc0e64909789b10ded9c0cd5/readme/extending-blt.md)

I see the following: 

```
You can override the value of any Phing variable used by BLT by either:
28	
29	1. Adding the variable to your project.yml file:
30	
31	        behat.tags: @mytags
32	
33	2. Specifying the variable value in your `blt` command using [Phing](https://www.phing.info/docs/stable/hlhtml/index.html#d5e792) argument syntax `-D[key]=[value]`, e.g.,
34	
35	        blt tests:behat -Dbehat.tags='@mytags'
```

I'm looking for some direction for dealing with multiple tags on local development vs travis. 
(Tangent - This feels like a state machine logic problem to me...)

Here's what I know about the syntax: 
* You can link multiple tags in `project.yml` via `&&`
* We can ignore the feature subcontexts by adding the `~`(tilda) in `project.yml` or `project.local.yml`

Here's what I'm trying to accomplish: 

- Locally : I want to run the `@development` behat tests and NOT run the `@varnish` behat tests
- Travis : I want to run the  `@varnish` behat tests and NOT run the `@development` behat tests
- Also commit this in a way that the entire team can just pull the repo and not have to configure anything

I believe the following should ignore the `@varnish` feature behat tests locally and ignore the `@development` features on Travis, Correct?

---

`project.local.yml`
```
behat:
  tags: '~@varnish'
```

`project.yml`
```
behat:
  tags: '~@development'

```

By default, the `project.local.yml` files are not under version control (added to .gitignore) and created on `Travis` from the `example.project.local.yml` file. Is this a situation where you would modify `example.project.local.yml` to look like :

`project.local.yml`
```
behat:
  tags: '~@varnish'
```

Or is there a better way to handle this? Perhaps overriding the phing task instead? 
`blt tests:behat -Dbehat.tags='@mytags'`

How would you recommend adding this setup to our project repo in a way that our team would automatically get this setup? Hope this questions makes sense.

**Comment by grasmash** [comment]
I think I'd try the following:

example.project.local.yml:
```
behat:
  tags: '~@varnish'
```

project.yml:
```
behat:
  tags: '~@development'
```

Modify your .travis.yml file by adding `- touch project.local.yml` before `blt ci:build:validate:test` is called. This will prevent `example.project.local.yml` from being copied to `project.local.yml` on Travis CI by making a blank `project.local.yml`. Travis should then use the ` '~@development'` value.

**Comment by justinlevi** [comment]
Will give this a shot - thanks!

**Comment by grasmash** [comment]
You might actually run into some complaints with our PHPUnit test if `project.local.yml` is completely empty. Maybe try `  - echo 'example: value' > project.local.yml`.

**Comment by grasmash** [comment]
@justinlevi how'd that work for you?

**Comment by grasmash** [comment]
Closing. No response for more than two weeks.
