### ISSUE TITLE
Avoiding Github rate limiting

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#70]
Despite all of Github's promises that anonymous API calls are no longer rate limited, we still see Travis tests fail from time to time because of throttling. Not sure who's at fault, but I do know that simply adding a personal oauth token following [this guide](http://blog.simplytestable.com/creating-and-using-a-github-oauth-token-with-travis-and-composer/) prevents the issue.

Ideally Bolt would prompt for an oauth token on initial setup, and then automatically create .travis.composer.config.json and modify .travis.yml to accept it.

**Comment by geerlingguy** [comment]
Note that if you use 2FA, it's slightly more annoying, as you have to make a normal request that fails, which triggers a text message, then a 2nd request that has:

```
curl -u 'username' -d '{"note":"Travis Composer 2"}' --header "X-GitHub-OTP: TOKENHERE" https://api.github.com/authorizations
```

(Inserting your token where it says TOKENHERE).

**Comment by danepowell** [comment]
A github rep just replied to me and said that the remaining throttling was accidentally left in place on an upstream balancer or something. It should be fixed now, which means this is no longer necessary. We can re-open if people are still getting throttled.
