### ISSUE TITLE
Should deploy:composer:install wipe out Drupal core and contrib?

### ISSUE THREAD

**Issue by bkosborne** [acquia/blt#701]
The current deploy task will invoke `deploy:composer:install` which firsts removes the vendor directory and then runs `composer install` to get a "fresh" copy of dependencies. Vendor is not the only directory with dependencies though - there will be the docroot/core, docroot/modules/contrib, etc. I wonder if it makes sense to remove those as well? Though I guess that's more difficult since a project could add even more of these "custom" dependency locations.

This mostly boils down to an issue where I'm not doing continuous deployment yet. I'm deploying to Acquia by running `deploy` from my dev machine, and since that process *copies* my working code into the deploy folder, if I accidentally made any modifications to contrib modules or something, they'd be deployed as well.

**Comment by grasmash** [comment]
Each time that you run "deploy" the entire deploy directory is wiped out. When files are then copied into the artifact, the contributed directories are excluded. So, it shouldn't be possible to have remnants of your development in your artifact. Are you seeing this behavior?

**Comment by bkosborne** [comment]
Ugh, sorry about that. I missed the reference to the deploy-exclude file (which has the contrib folders listed) in the rsync command! Thanks

**Comment by grasmash** [comment]
Yeah I've considered *not* destroying the whole deploy directory each time in the interest of speeding things up. But, I found that it actually made things a little slower for some reason. 90% of the time is spent executing `composer install` with `--no-dev` which rebuilds the dependencies from cache, and I don't think there's any way around that.
