### ISSUE TITLE
post-code-update cloud hook fails to enable non-existant Shield module using default composer.json and project.yml

### ISSUE THREAD

**Issue by ba66e77** [acquia/blt#710]
My system information:
* BLT version: 8.5.2

Deploying to the Acquia Cloud environment, the post-code-update hook errors out at the `setup:toggle-modules` phase when trying to enable the Shield module.  This module is included in the modules:deploy:enable section of project.yml (https://github.com/acquia/blt/blob/8.5.2/template/project.yml#L84) but is not included in the composer.json.

On Acquia Cloud, the post-code-update hook then tries to download the module but does not have write access to the modules/contrib directory.

```
[20:22:52] [20:22:52] Started [20:26:47] [2016-11-25 20:23:48] Starting hook: post-code-update 
[2016-11-25 20:23:48] Executing: /mnt/users/----/dev.shell /var/www/html/http://ift.tt/2gllKnz --- dev develop develop ---@s----.prod.hosting.acquia.com:eebsmith.git git < /dev/null (as ----.dev@----}) 
Running updates for environment: dev 
Buildfile: /var/www/html/http://ift.tt/2g80T9z 
blt > deploy:update: 
blt > setup:update: 
blt > setup:toggle-modules: shield was not found. 
[warning] The following projects provide some or all of the extensions not [ok] found: shield 
Would you like to download them? (y/n): y 
Directory /mnt/www/html/----/docroot/modules/contrib exists, [error] but is not writable. Please check directory permissions. 
Project shield (8.x-1.0) could not be downloaded to [error] /mnt/www/html/----/docroot//modules/contrib/shield. shield was not found. [warning] 
The following projects provide some or all of the extensions not [ok] found: shield
```

**Comment by grasmash** [comment]
I think we should probably ship the shield module by default since we have it in the project.yml settings.

**Comment by grasmash** [comment]
Resolved in https://github.com/acquia/blt/pull/729
