### ISSUE TITLE
Using the Drupal console

### ISSUE THREAD

**Issue by bobbygryzynger** [acquia/blt#714]
What is the recommended way to run Drupal console commands against sites created with BLT?

**Comment by grasmash** [comment]
BLT doesn't really have a role in Drupal console beyond including it via Composer. We do currently have beta5 because the newer versions have some [blocking issues](https://github.com/hechoendrupal/DrupalConsole/issues/2905).

I typically just run something like:
```
cd docroot
../vendor/bin/drupal list
```

**Comment by bobbygryzynger** [comment]
I thought that was probably it, but strangely I get this:
```sh
172-16-243-180:docroot rg173$ pwd
/Users/rg173/Sites/octagon/docroot
172-16-243-180:docroot rg173$ ../vendor/bin/drupal list

                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

172-16-243-180:docroot rg173$ 

```

**Comment by grasmash** [comment]
That's a sql issue, are you able to connect to the DB?

**Comment by bobbygryzynger** [comment]
Yeah, it's funny. The local site is up and running otherwise.
