### ISSUE TITLE
Error with adding Drupal BLT to my current project

### ISSUE THREAD

**Issue by ghost** [acquia/blt#738]
My system information:
* Operating system type: [Ubuntu]
* Operating system version: [16.04]
* Current Drupal Version: [8.2.2]
* BLT version: [replace]

```
I am trying to add BLT to my current project. Under my project name I have a docroot directory with my current Drupal 8.2.2 installation. When I try to install BLT using Composer, it fails and gives me the below errors. If anyone can help me that that would be great. Thank you everyone in advance. 
```

When I run this command:
```
[composer require acquia/blt:^8.3]
```

I get the following output:
```
[./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acquia/blt 8.5.2 requires drupal/console 1.0.0-beta5 -> satisfiable by drupal/console[1.0.0-beta5] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.5.1 requires drupal/console 1.0.0-beta5 -> satisfiable by drupal/console[1.0.0-beta5] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.5.0 requires drupal/console 1.0.0-beta5 -> satisfiable by drupal/console[1.0.0-beta5] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.9 requires drupal/console 1.0.0-beta5 -> satisfiable by drupal/console[1.0.0-beta5] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.8 requires drupal/console 1.0.0-beta5 -> satisfiable by drupal/console[1.0.0-beta5] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.7 requires drupal/console 1.0.0-beta5 -> satisfiable by drupal/console[1.0.0-beta5] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.6 requires drupal/console 1.0.0-beta5 -> satisfiable by drupal/console[1.0.0-beta5] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.5 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.4 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.3 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.2 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.1 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.4.0 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.3.4 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.3.3 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.3.2 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.3.1 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - acquia/blt 8.3.0 requires drupal/console ~1 -> satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.
    - Installation request for acquia/blt ^8.3 -> satisfiable by acquia/blt[8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.4.4, 8.4.5, 8.4.6, 8.4.7, 8.4.8, 8.4.9, 8.5.0, 8.5.1, 8.5.2].]
```

And I expected this to happen:
I expect BLT to be added to be installed on my current site.

**Comment by grasmash** [comment]
Composer is informing you that there's a version conflict between BLT and Drupal Console. BLT requires the beta5 version of Drupal console, and cannot upgrade until the following issue is resolved: https://github.com/hechoendrupal/DrupalConsole/issues/2905

**Comment by skokcha** [comment]
Thank you @grasmash . I resolved this dependency by opening up my composer.json file that is located within my docroot directory and changed the value of  "drupal/console": "~1.0" to  "drupal/console": "1.0.0-beta5".
However I am getting other errors. I tried resolving the phpunit error and install phpunit 4.8.30, but I was not able to do it. phpunit only exists within my "vendor" directory and I do not know how to change it. This error is also telling me not install a list of BLT versions.

Below is my error:

[ Problem 1
    - Conclusion: don't install acquia/blt 8.5.2
    - Conclusion: don't install acquia/blt 8.5.1
    - Conclusion: don't install acquia/blt 8.5.0
    - Conclusion: don't install acquia/blt 8.4.9
    - Conclusion: don't install acquia/blt 8.4.8
    - Conclusion: don't install acquia/blt 8.4.7
    - Conclusion: don't install acquia/blt 8.4.6
    - Conclusion: don't install acquia/blt 8.4.5
    - Conclusion: don't install acquia/blt 8.4.4
    - Conclusion: don't install acquia/blt 8.4.3
    - Conclusion: don't install acquia/blt 8.4.2
    - Conclusion: don't install acquia/blt 8.4.1
    - Conclusion: don't install acquia/blt 8.4.0
    - Conclusion: don't install acquia/blt 8.3.4
    - Conclusion: don't install acquia/blt 8.3.3
    - Conclusion: don't install acquia/blt 8.3.2
    - Conclusion: don't install acquia/blt 8.3.1
    - Conclusion: don't install acquia/blt 8.3.0
    - Conclusion: don't install acquia/blt 8.6.0-beta1
    - Conclusion: don't install acquia/blt 8.5.0-beta1
    - Conclusion: remove phpunit/phpunit 4.8.30
    - Installation request for acquia/blt ^8.3 -> satisfiable by acquia/blt[8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.4.4, 8.4.5, 8.4.6, 8.4.7, 8.4.8, 8.4.9, 8.5.0, 8.5.0-beta1, 8.5.1, 8.5.2, 8.6.0-beta1, 8.x-dev].
    - Conclusion: don't install phpunit/phpunit 4.8.30
    - acquia/blt 8.x-dev requires phpunit/phpunit ^5.5.4 -> satisfiable by phpunit/phpunit[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: phpunit/phpunit[5.5.x-dev, 4.8.30].
    - Can only install one of: phpunit/phpunit[5.6.x-dev, 4.8.30].
    - Can only install one of: phpunit/phpunit[5.7.x-dev, 4.8.30].
    - Installation request for phpunit/phpunit (locked at 4.8.30, required as ~4.8) -> satisfiable by phpunit/phpunit[4.8.30].
]

Thank you in advance.

**Comment by grasmash** [comment]
In this case, you have a new conflict. Your project requires an incompatible version of phpunit. If your root composer.json does not define this, then it is a dependency of one of your dependencies.

Try using `composer why phpunit/phpunit` to see which dependency depends on it.

**Comment by ykokcha** [comment]
output:
[There is no installed package depending on "phpunit/phpunit".]

**Comment by grasmash** [comment]
Hm. The line "Installation request for phpunit/phpunit (locked at 4.8.30, required as ~4.8)" indicates that something in your composer.json is indeed defining phpunit/phpunit as a dependency. If you run `composer info phpunit/phpunit` does it list the package information?

**Comment by grasmash** [comment]
You might find it by running `grep '~4.8' .` in your project dir. Presumably that line is somewhere.

**Comment by skokcha** [comment]
One of the below I guess.

Binary file .git/objects/pack/pack-da46d25b380be4cc76b067ed3826662585d4c6a1.pack matches
Binary file .git/objects/14/b4cf43cc03c9b887825f3cb87e1cc2211fad43 matches
profiles/lightning/composer.lock:                "phpunit/phpunit": "~4.8|~5.0",
profiles/lightning/composer.lock:                "phpunit/phpunit": "~4.8",
profiles/lightning/composer.lock:                "phpunit/phpunit": "~4.8"
profiles/lightning/composer.json:        "phpunit/phpunit": "~4.8",
core/composer.lock:                "phpunit/phpunit": "~4.8|~5.0",
core/composer.lock:                "phpunit/phpunit": "~4.8"
core/composer.json:        "phpunit/phpunit": "~4.8",
composer.lock:                "phpunit/phpunit": "~4.8|~5.0",
composer.lock:                "phpunit/phpunit": "~4.8|~5.0",
composer.lock:                "phpunit/phpunit": "~4.8"
vendor/doctrine/cache/composer.json:        "phpunit/phpunit":         "~4.8|~5.0",
vendor/sebastian/diff/composer.json:        "phpunit/phpunit": "~4.8"
vendor/zendframework/zend-diactoros/composer.lock:                "phpunit/phpunit": "~4.8"
vendor/wikimedia/composer-merge-plugin/composer.json:        "phpunit/phpunit": "~4.8|~5.0",
vendor/composer/installed.json:            "phpunit/phpunit": "~4.8|~5.0",
vendor/composer/installed.json:            "phpunit/phpunit": "~4.8"
vendor/composer/installed.json:            "phpunit/phpunit": "~4.8|~5.0",
vendor/phpseclib/phpseclib/composer.lock:                "phpunit/phpunit": "~4.8"

**Comment by grasmash** [comment]
If phpunit is in the require-dev array for one of these packages, we can ignore it. Those are not built recursively. It looks to me that you're not running into an issue with constraints. Rather, there's merely a conflict with locked versions.

Try the following:
```
composer require acquia/blt:^8.3 --no-update
composer update
```

This will update _all_ of your dependencies, but may find a compatible set of versions.

**Comment by skokcha** [comment]
I guess same kind of thing:

Problem 1
    - Conclusion: don't install acquia/blt 8.5.2
    - Conclusion: don't install acquia/blt 8.5.1
    - Conclusion: don't install acquia/blt 8.5.0
    - Conclusion: don't install acquia/blt 8.4.9
    - Conclusion: don't install acquia/blt 8.4.8
    - Conclusion: don't install acquia/blt 8.4.7
    - Conclusion: don't install acquia/blt 8.4.6
    - Conclusion: don't install acquia/blt 8.4.5
    - Conclusion: don't install acquia/blt 8.4.4
    - Conclusion: don't install acquia/blt 8.4.3
    - Conclusion: don't install acquia/blt 8.4.2
    - Conclusion: don't install acquia/blt 8.4.1
    - Conclusion: don't install acquia/blt 8.4.0
    - Conclusion: don't install acquia/blt 8.3.4
    - Conclusion: don't install acquia/blt 8.3.3
    - Conclusion: don't install acquia/blt 8.3.2
    - Conclusion: don't install acquia/blt 8.3.1
    - Conclusion: don't install acquia/blt 8.3.0
    - Conclusion: don't install acquia/blt 8.6.0-beta1
    - Conclusion: don't install acquia/blt 8.5.0-beta1
    - Conclusion: remove phpunit/phpunit 4.8.30
    - Conclusion: don't install phpunit/phpunit 4.8.30
    - Conclusion: don't install phpunit/phpunit 4.8.29
    - Conclusion: don't install phpunit/phpunit 4.8.28
    - Conclusion: don't install phpunit/phpunit 4.8.27
    - Conclusion: don't install phpunit/phpunit 4.8.26
    - Conclusion: don't install phpunit/phpunit 4.8.25
    - Conclusion: don't install phpunit/phpunit 4.8.24
    - Conclusion: don't install phpunit/phpunit 4.8.23
    - Conclusion: don't install phpunit/phpunit 4.8.22
    - Conclusion: don't install phpunit/phpunit 4.8.21
    - Conclusion: don't install phpunit/phpunit 4.8.20
    - Conclusion: don't install phpunit/phpunit 4.8.19
    - Conclusion: don't install phpunit/phpunit 4.8.18
    - Conclusion: don't install phpunit/phpunit 4.8.17
    - Conclusion: don't install phpunit/phpunit 4.8.16
    - Conclusion: don't install phpunit/phpunit 4.8.15
    - Conclusion: don't install phpunit/phpunit 4.8.14
    - Conclusion: don't install phpunit/phpunit 4.8.13
    - Conclusion: don't install phpunit/phpunit 4.8.12
    - Conclusion: don't install phpunit/phpunit 4.8.11
    - Conclusion: don't install phpunit/phpunit 4.8.10
    - Conclusion: don't install phpunit/phpunit 4.8.9
    - Conclusion: don't install phpunit/phpunit 4.8.8
    - Conclusion: don't install phpunit/phpunit 4.8.7
    - Conclusion: don't install phpunit/phpunit 4.8.6
    - Conclusion: don't install phpunit/phpunit 4.8.5
    - Conclusion: don't install phpunit/phpunit 4.8.4
    - Conclusion: don't install phpunit/phpunit 4.8.3
    - Conclusion: don't install phpunit/phpunit 4.8.2
    - Conclusion: don't install phpunit/phpunit 4.8.1
    - Installation request for acquia/blt ^8.3 -> satisfiable by acquia/blt[8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.3.4, 8.4.0, 8.4.1, 8.4.2, 8.4.3, 8.4.4, 8.4.5, 8.4.6, 8.4.7, 8.4.8, 8.4.9, 8.5.0, 8.5.0-beta1, 8.5.1, 8.5.2, 8.6.0-beta1, 8.x-dev].
    - Conclusion: don't install phpunit/phpunit 4.8.0
    - acquia/blt 8.x-dev requires phpunit/phpunit ^5.5.4 -> satisfiable by phpunit/phpunit[5.5.x-dev, 5.6.x-dev, 5.7.x-dev].
    - Can only install one of: phpunit/phpunit[5.5.x-dev, 4.8.x-dev].
    - Can only install one of: phpunit/phpunit[5.6.x-dev, 4.8.x-dev].
    - Can only install one of: phpunit/phpunit[5.7.x-dev, 4.8.x-dev].
    - Installation request for phpunit/phpunit ~4.8 -> satisfiable by phpunit/phpunit[4.8.0, 4.8.1, 4.8.10, 4.8.11, 4.8.12, 4.8.13, 4.8.14, 4.8.15, 4.8.16, 4.8.17, 4.8.18, 4.8.19, 4.8.2, 4.8.20, 4.8.21, 4.8.22, 4.8.23, 4.8.24, 4.8.25, 4.8.26, 4.8.27, 4.8.28, 4.8.29, 4.8.3, 4.8.30, 4.8.4, 4.8.5, 4.8.6, 4.8.7, 4.8.8, 4.8.9, 4.8.x-dev].

**Comment by grasmash** [comment]
Can you share your entire composer.json file?

**Comment by skokcha** [comment]
Sure. The below is the composer.json file under the docroot directory.

{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "composer/installers": "^1.0.21",
        "wikimedia/composer-merge-plugin": "~1.3",
        "drupal/console": "1.0.0-beta5",
        "acquia/blt": "^8.3"
    },
    "replace": {
        "drupal/core": "~8.2"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php."
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": "Drupal\\Core\\Composer\\Composer::ensureHtaccess",
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    }
}

**Comment by grasmash** [comment]
A few questions:
- Did you take Drupal core's composer.json file and modify it? 
- Are you already using composer to successfully manage your site's dependencies?
- Did you follow the instruction to "Ensure that your project directory structure is Acquia-cloud compatible by asserting that the Drupal root is in a top-level folder called docroot." ?
- What directory is this composer.json file in?

**Comment by grasmash** [comment]
Closing after 2 weeks inactivity.
