### ISSUE TITLE
Apply BLT in another way?

### ISSUE THREAD

**Issue by skokcha** [acquia/blt#749]
I am not sure if a question is correct to post on here or not and if it is not please delete it and show me where to post it. 

So is there another way to integrate BLT with my current Drupal site?

Can I do a clean installation of BLT and basically replace the site directory to make it work? Does anyone know if this will work?

Thank you in advance.

**Comment by grasmash** [comment]
When you say "another way", which initial way are you referring to? There are a few ways to use BLT. For instance, you can add it to an existing site following these instructions:
http://blt.readthedocs.io/en/8.x/readme/adding-to-project/

You do need to install system requirements first.

**Comment by ykokcha** [comment]
I tried those instructions. They don't work for me. When I fix one thing another thing goes wrong.

**Comment by grasmash** [comment]
You could do that, yes, though I'm sure you'd have a different set of issues.

**Comment by ykokcha** [comment]
lol ok. Thank you. I am guessing BLT is pretty new at this point to get a clean install with another code. Maybe I will visit it back in a few months to see where it is. Thank you for all your help!

**Comment by grasmash** [comment]
Unfortunately I don't think this is the type of thing that's going to be resolved in time. A large part of BLT is an opinionated architecture. If you're project doesn't already have a very similar architecture, you'll need to spend some time in an adaptation process.

The version conflicts that you're encountering in #738 are typical of a project that uses dependency management. You'll need to work through the conflicts to find inter-operable versions of your dependencies. I can help you troubleshoot to a degree. Admittedly, Composer has some very cryptic errors messages and that often makes conflict resolution confusing.

**Comment by skokcha** [comment]
Thank you. I will still give it a shot with the installation. I agree 100% with your composer assessment. I thought it was just me that thought composer was cryptic. Again, thanks and I will continue and see what happens in the other thread.

**Comment by grasmash** [comment]
Ok, in that case I'll close this issue.
