### ISSUE TITLE
How can I enable, by default,  Xdebug when creating a new project?

### ISSUE THREAD

**Issue by mghinea** [acquia/blt#753]

**Comment by grasmash** [comment]
Xdebug is not project specific. It is a PHP extension that is installed for your local version of PHP which could be provided by Drupal VM, MAMP, or OSX itself. If you'd like to enable Xdebug for a Drupal VM machine on a new project, please post a question for that project: https://github.com/geerlingguy/drupal-vm/issues

**Comment by kevinquillen** [comment]
To add, if you do go with Drupal VM, the config.yml file that is generated by BLT does not account for those extras. In this case, you would need to add xdebug as an installed extra, and enable it with some xdebug flags in config.yml and re-provision the machine (vagrant reload --provision). For first timers to DrupalVM, it can be easy to miss.

Here is an example of what I am talking about in a config.yml that enables xdebug:

```
# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, make set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  - drupalconsole
  - mailhog
  - memcached
  - nodejs
  - pimpmylog
  - solr
  - xdebug
```

Note xdebug at the bottom.

You also need to add this:

```
# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "9000"
```

Then in your IDE of choice, follow the instructions to setup/trigger xdebug.

**Comment by grasmash** [comment]
@geerlingguy should this be made default config?

**Comment by geerlingguy** [comment]
@grasmash - Yeah, probably... Though I'd argue against PHPSTORM, since I don't use it much :P

As long as it's overridable in `local.config.yml` though, no problem.

**Comment by kevinquillen** [comment]
VS Code also works, but has an extra step of setting some vars in a json settings file.

**Comment by grasmash** [comment]
Although, it would really slow things down to enable this by default.
