### ISSUE TITLE
BLT Doctor checkNvmExists() on Drupal-VM

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#764]
`$ blt doctor` checks for NVM on the system, but with Drupal-VM enabled, it looks for NVM on the guest system.
It's my understanding that the accepted approach for using Drupal-VM is to run all BLT commands from the host, with the exception of the behat testing suite. Is that accurate? If that is the case, should not the `checkNvmExists()` function check for NVM on the host then?

**Comment by grasmash** [comment]
The NVM check has been removed. It doesn't really make sense for Drupal VM, since the VM can just ship with the project-specific version of node that is required. #1417
