### ISSUE TITLE
blt acsf:init should be able to increase its memory usage

### ISSUE THREAD

**Issue by nikgregory** [acquia/blt#777]
It we add the following to the acsf:init task
`    <echo>Increasing memory allocation to 2G</echo>
    <php expression="ini_set('memory_limit', '2G');"/>
`
or even better use a property which we default to some reasonable value
`    <echo>Increasing memory allocation to ${php.mem_limit}</echo>
    <php expression="ini_set('memory_limit', '${php.mem_limit}');"/>
`
users will not need to modify their php.ini for acsf:init to work.

This is especially useful in a pipeline build where there is no access to the php.ini

**Comment by nikgregory** [comment]
PR: https://github.com/acquia/blt/pull/780

**Comment by grasmash** [comment]
Closed #780
