### ISSUE TITLE
blt acsf:init should be able to pull from dev repo

### ISSUE THREAD

**Issue by nikgregory** [acquia/blt#778]
lets pretend that you are an acsf community developer and want to confirm that your acsf changes will be compatible with the code you are working on.

as it stands now, blt acsf:init will only require a released version of acsf
`    <exec dir="${repo.root}" command="composer require drupal/acsf:^8" logoutput="true" checkreturn="true" passthru="true" level="${blt.exec_level}"/>
`
if we allow this to be changed, then blt acsf:init can pick up dev branches and still run through the
drush commands
`    <exec dir="${repo.root}" command="composer require ${acsf.branch}" logoutput="true" checkreturn="true" passthru="true" level="${blt.exec_level}"/>
`

**Comment by nikgregory** [comment]
PR https://github.com/acquia/blt/pull/781

**Comment by grasmash** [comment]
#781 was merged.
