### ISSUE TITLE
Acquia Cloud Account Creation + CI Instructions

### ISSUE THREAD

**Issue by mikemadison13** [acquia/blt#794]
The current instructions on https://github.com/acquia/blt/blob/8.x/readme/ci.md#setting-up-travis-ci-for-automated-deployments are currently not accurate, as the Acquia Cloud no longer allows you to register an account using an email address with a + in it.

**Comment by mikemadison13** [comment]
see https://github.com/acquia/blt/pull/795

**Comment by grasmash** [comment]
Merged #795
