### ISSUE TITLE
composer install is run twice on initial setup

### ISSUE THREAD

**Issue by CashWilliams** [acquia/blt#8]
Following the readme, steps are `bolt.sh create`, cd into project and then `bolt.sh setup`.

Both `create` and `setup` run `composer install` on the created project directory.

Is there a reason why we need to run composer install twice?

**Comment by CashWilliams** [comment]
I think https://github.com/acquia/bolt/blob/8.x/build/phing/build.xml#L135 could be removed?

**Comment by CashWilliams** [comment]
Well, `./bolt.sh setup` won't run in the project directory because phing isn't available. However, it seems like overkill to install 50+ libraries just to get phing, to then run `composer install` again.

**Comment by danepowell** [comment]
This should be resolved by #125. Are you okay with closing this?

**Comment by grasmash** [comment]
Yup!
