### ISSUE TITLE
Clear Twig caches on deployment

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#813]
We hit a bug after making a change to a Twig template and deploying to production where page requests would randomly pick up the new or old template, depending on which web head served the request. It turns out that `drupal_flush_all_caches` and its ilk (`drush cr`) does not clear the Twig template cache across multiple web servers.

This issue is described here https://docs.acquia.com/article/drupal-8-cache-backend

Until this is fixed in Drupal core, BLT seems like the best place to fix this, maybe via a custom function in a post-code-deploy / post-code-update cloud hook.

**Comment by grasmash** [comment]
@danepowell Do you have an example of the "mix of Cloud Hooks and Cloud API's" that's suggested here?

Is the idea that you'd use the Cloud API to get an array of all servers for a subscription, and then SSH into each one and run `drush ev` to execute a cache clear? That sounds pretty heavy duty.

**Comment by danepowell** [comment]
I don't have any additional information beyond what's on that support page. I agree that SSHing into each server and running a Drush command seems very heavy, but I don't know of any better solution until the issue is fixed in core. Doing it via a cloud hook (not as part of the regular Phing update task) makes sense to me. Although we could also do it as part of deploy:update.

Honestly... I'd prefer to just get this fixed in core, it seems like it might be close: https://www.drupal.org/node/2752961

**Comment by danepowell** [comment]
This is becoming fairly urgent as we keep getting bitten by it on multiple projects, and it doesn't look like it's going to be fixed in core any time soon.

One option is to apply [this core patch](https://www.drupal.org/files/issues/no_reliable_method-2752961-29.patch) and then overwrite the deployment identifier on each release with a commit hash. This sounds ugly, but the deployment identifier is actually something that already exists in (default.settings.php)[http://cgit.drupalcode.org/drupal/tree/sites/default/default.settings.php#n291], and might solve other cache-related issues on deployments.

I'm guessing we'd just want to set this as part of the deploy target, so it would get set in the deploy artifact but not in the source repo.

**Comment by rgristroph** [comment]
Maybe the deploy identifier for the source repo could be "development-only-do-not-deploy" or something like that.

**Comment by danepowell** [comment]
I'm about to open a PR. For Acquians, note that a more extensive fix can be tracked at CL-13461

**Comment by danepowell** [comment]
I opened a PR that uses the `deploy.tag` as the deployment identifier. This means that ordinary commits (to develop or master branches) won't be updated, but that shouldn't be an issue since those typically only go to single-server development environments. Anything being deployed to production should have a tag.

Ideally I think the deployment identifier would be a commit hash, but that seemed like it would be a lot harder to get from within the deploy script.

**Comment by rgristroph** [comment]
I'll see if I can find a way to test this.

**Comment by bkosborne** [comment]
For what it's worth, I came upon a similar solution to this problem before having seen this issue and it's been working well for us so far (no complains of old twig files being used).

Instead of basing my deployment ID on tag, I instead based on on the current timestamp of the deploy, because we don't deploy with tags from BLT. I did this with a small post-deploy-build command for BLT. We deploy continuously to a dev environment and then create tags from that manually and deploy those.

**Comment by wimleers** [comment]
I don't know what the `deploy.tag` is, but using the git commit hash is the far safer approach. Tags can be revoked and reused: there's a possibility of duplicates. Commit hashes are always unique.

Same concern when using timestamps: although the chance is very small, there's a possibility of collision. Whereas the git commit hash is effectively a hash of the content, thus changes whenever Twig templates change.

**Comment by danepowell** [comment]
The only problem with using the commit hash is that you don't know what it is until after the commit... By which point it's obviously too late to set the deploy id. So you'd have to use the parent hash. Which means that two commits sharing the same parent would also have a deploy id collision.
