### ISSUE TITLE
GitTasksTest::testGitPreCommitHook() is destructive

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#819]
Unit tests should be absolutely idempotent and non-destructive. But currently `\Acquia\Blt\Tests\BltProject\GitTasksTest::testGitPreCommitHook()` rewrites Git history. This isn't a problem in a CI context, but if you ever run your unit tests locally during development, you'll be surprised when your `HEAD` commit disappears.

**Comment by grasmash** [comment]
Yes.

**Comment by grasmash** [comment]
@TravisCarden I may just remove the test. I'm not aware of any way to simulate this behavior. https://github.com/acquia/blt/blob/8.x/tests/phpunit/BltProject/GitTest.php#L74
