### ISSUE TITLE
After Blt Update to 8.6.4 - array merge issue inside blt/project.yml file

### ISSUE THREAD

**Issue by jayakrishnanj** [acquia/blt#821]
My system information:
* Operating system type: MAC
* Operating system version: 10.12.1
* BLT version: 8.6.4

When I run this command:
```
composer update
composer nuke
```

BLT version upgraded to 8.6.4, all files are updated. Able to see shield is added twice inside ci uninstall.
Inside blt/project.yml file i could see the following difference
```
--- a/blt/project.yml
+++ b/blt/project.yml
@@ -37,9 +37,9 @@ modules:
     uninstall: [acsf, dblog, shield]
   ci:
     enable: {  }
-    uninstall: [shield]
+    uninstall: [shield, shield]
   dev:
```

**Comment by grasmash** [comment]
I'm not 100% sure, but I think this was likely resolved by #891.
