### ISSUE TITLE
Improve Git commit hooks

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#825]
Git hooks could use some improvement. Consider this output:

![git-hook-output](https://cloud.githubusercontent.com/assets/959246/21367800/2f0e1c46-c6c5-11e6-81b2-1f457c076a07.png)

That's a lot of visual noise. A couple ofthings stand out to me:
1. Do I really need seven lines of Phing build info every time I commit? Can we either suppress some of that output or run phpcs directly? (Of all actions, I would like Git commits to be fast and lightweight.)
1. The commit message error gets completely lost. It doesn't look like an error, because it neither says "error" nor uses color (e.g., red) to get my attention. I usually subconsciously filter it out the first two times I encounter it. Could we color it red and actually say "ERROR:"?

**Comment by grasmash** [comment]
@TravisCarden What would your ideal output be in this scenario?

**Comment by grasmash** [comment]
Also, what is your version of BLT?

**Comment by grasmash** [comment]
I believe this has already been addressed. Current output is:
```
$ git commit -m 'Disabling lightning tests.'
Sniffing staged files via PHP Code Sniffer...
Linting custom twig files...
Validating composer.json...
Ok!
[blt-update a64b4b228] Disabling lightning tests.
 1 file changed, 3 insertions(+), 1 deletion(-)
```
