### ISSUE TITLE
Tagging integration with Travis CI / Pipelines?

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#830]
This is a feature request:

One thing that is currently done manually on most projects is the tagging process. The current tagging workflow (at least the one I use) is:

  1. `git tag 1.0.1` on local BLT repo.
  2. `git push --tags upstream` to push it up to the project repo on GitHub.
  3. Wait for Travis CI build to complete and push latest code to Acquia Cloud git repo.
  4. Pull down the latest changes in the Acquia Cloud git repo.
  5. `git tag 1.0.1` in the Acquia Cloud git repo.
  6. `git push --tags` to push the artifact tag to the Acquia Cloud git repo.

At this point, I can deploy that tag to stage and/or production if needed.

It would be great if Travis/Pipelines could detect a tag build (vs a branch commit or PR build), then create a tag in the deploy artifact repository and push the tag up to the artifact repository.

I did this automatically through Jenkins on an older project, but that was with a way older BLT version and I don't have access to that Jenkins instance anymore.

**Comment by arknoll** [comment]
This is what I've used on a prior project:

in .travis.yml:
`
after_success:
  # Sync upstream to acquia.
  - if [ $TRAVIS_TAG ]; then tasks/drop project:publish $TRAVIS_TAG acquia $TRAVIS_BRANCH --process-tag; fi;`

project:publish would commit the code, push, make a tag and push the tag.

**Comment by geerlingguy** [comment]
@arknoll - Awesome, makes sense! I'll see if I can get that adapted to Pipelines too, and also on Travis.

**Comment by grasmash** [comment]
Todos:

- [ ] Create a new `deploy:tag` target that will create a tag on both the source branch and the build branch. E.g., tag source "master" branch with `1.0.0` tag and build branch with `1.0.0-build`. 
- [ ] Push source tag to source repo and build tag to build repo.

@geerlingguy when should this target be executed? Should it be done manually, or after every `deploy:build` in acqiua-pipelines.yml?

**Comment by arknoll** [comment]
I am taking a look at this. Should have a starting PR today.
