### ISSUE TITLE
Documentation: More comprehensive CM docs

### ISSUE THREAD

**Issue by jasonharc** [acquia/blt#846]
As a Drupal Developer who uses BLT I want more comprehensive configuration management (CM) documentation so that I can learn best practices.

**Comment by geerlingguy** [comment]
Related to/duplicate of #854 ?

**Comment by grasmash** [comment]
I'm going to consider this closed. The existing CM approach is well documented. Although, we may be introducing new CM approaches in #854. Documentation would accompany the PR for such a change.
