### ISSUE TITLE
Enable local Twig Debugging

### ISSUE THREAD

**Issue by dpagini** [acquia/blt#85]
It seems like by default, local twig debugging is not turned on due to an invalid path to _development.services.yml_ file.

https://github.com/acquia/bolt/blob/8.x/template/docroot/sites/default/settings/default.local.settings.php#L33

I think this file should read:
`$settings['container_yamls'][] = $dir . '/docroot/sites/development.services.yml';`
_Note the additional "/docroot" which is not part of the $dir variable._

**Comment by damontgomery** [comment]
Thanks @dpagini! Since the PR was merged, @grasmash, do you want to close this issue?
