### ISSUE TITLE
Remove console dependency, upgrade drush 8

### ISSUE THREAD

**Issue by jasonharc** [acquia/blt#851]
Remove console dependency, upgrade drush 8.

**Comment by geerlingguy** [comment]
See:

  - [Fixes #513: Updating Console to rc8.](https://github.com/acquia/blt/pull/646) (https://github.com/acquia/blt/pull/646)
  - [Downgrading to Drush 8.](https://github.com/acquia/blt/pull/728)

**Comment by grasmash** [comment]
Close as duplicate.
