### ISSUE TITLE
Tagging. Auto create tag for source and artifact on all remotes.

### ISSUE THREAD

**Issue by jasonharc** [acquia/blt#852]
Tagging. Auto create tag for source and artifact on all remotes.

**Comment by grasmash** [comment]
More specifically:

- [ ] Create a new `deploy:tag` target that will create a tag on both the source branch and the build branch. E.g., tag source "master" branch with `1.0.0` tag and build branch with `1.0.0-build`. 
- [ ] Push source tag to source repo and build tag to build repo.

@geerlingguy when should this target be executed? Should it be done manually, or after every `deploy:build` in acqiua-pipelines.yml?

**Comment by grasmash** [comment]
Closing in favor of #830.
