### ISSUE TITLE
Cloud hooks for ACSF

### ISSUE THREAD

**Issue by jasonharc** [acquia/blt#853]
I want Cloud hooks for ACSF

**Comment by grasmash** [comment]
Presumably, these cloud hooks should do the same thing that our ACE/ACP/ACF cloud hooks do. 

@danepowell I seem to recall you being involved in disabling these hooks for ACSF. Was this due to lack of support for cloud hooks in ACSF?

**Comment by danepowell** [comment]
There isn't native support for multi-site cloud hooks on ACSF, you'd need to write a script that cycles through each site and runs hooks against specific site aliases. I've never attempted this, but I believe @lcatlett has
