### ISSUE TITLE
Add YAML validation

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#857]
Since syntax errors in YAML syntax errors can be just as serious as in PHP, we should have a validation command for them (e.g., `validate:yaml`) and include it in `validate:all`.

**Comment by grasmash** [comment]
Symfony's Yaml component provides a validation command that is available in 3.x. However, we are blocked on upgrading in #646 by https://github.com/hechoendrupal/drupal-console/issues/2905

**Comment by jmolivas** [comment]
@grasmash I am currently working on fixing this DrupalConsole issue.

**Comment by grasmash** [comment]
@jmolivas Thanks so much for your help!
