### ISSUE TITLE
Improve the Mac installation instructions so that it will be easier to onboard new users

### ISSUE THREAD

**Issue by markf3lton** [acquia/blt#865]
I wish for reliable "quick start" instructions that can be used to onboard newcomers to BLT. 

The [Mac installation instructions](http://blt.readthedocs.io/en/latest/INSTALL/#mac-osx) seem likely to leave new users frustrated. I believe Gulp is required for most BLT projects, but it is not included in the installation instructions. Many Macs will run out of memory running `composer install` and this problem can be easily avoided by first checking for a proper PHP configuration and setting the `memory_limit` to `-1`. A new Sierra user could not get `composer blt-alias` to work (and their .bash_profile did not exist) so that is addressed here as well.

I have worked with Drupal developers that are new to using Mac, new to using Drupal VM, new to Composer, new to Drupal 8, or new to all-of-the-above.

The sequence below *should* work on new (or newly formatted) Macs running macOS Sierra, El Capitan, or Yosemite. (Volunteers are needed to test this.)

Easy cut-and-paste Terminal commands are provided:

### Make sure the Apple dev tools are installed
```
xcodebuild -license
xcode-select --install
```

### Install the Homebrew package manager
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

### Tap the Homebrew repositories that will be needed
_Is all of this necessary? Maybe just homebrew-php?_
```
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
```

### Use Homebrew to install commonly used CLI tools
```
brew install wget
brew install git
brew install php56
```

### Install the Composer PHP package manager
```
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
```

### Install Drush using Composer
```
composer require global drush/drush:8.*
```

### Install prestissimo using Composer
This will make Composer faster.
```
composer global require "hirak/prestissimo:^0.3"
```

### Install the Node package manager (npm), and the Node version manager (nvm)
```
brew install npm
brew install nvm 
```

### Set up nvm
```
mkdir ~/.nvm
```

### Paste the following into .bash_profile using your plaintext editor of choice
_Important:_ Mac users will need to check for the existence of ~/.bash_profile (and this file needs to be created if it doesn't exist). 
```
function blt() {
  if [ "`git rev-parse --show-cdup 2> /dev/null`" != "" ]; then
    GIT_ROOT=$(git rev-parse --show-cdup)
  else
    GIT_ROOT="."
  fi
  if [ -f "$GIT_ROOT/vendor/bin/blt" ]; then
    $GIT_ROOT/vendor/bin/blt "$@"
  else
    echo "You must run this command from within a BLT-generated project repository."
    exit 1
  fi
}

export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```

Whenever changes are made to .bash_profile, quit the Terminal and relaunch it before continuing (or run `touch ~/.bash_profile`)

### Install Gulp using npm
_Not having gulp cost me hours. Including instructions for nvm/npm/gulp seems really important._
```
npm install -g gulp
```

### You can easily install VirtualBox by grabbing the download from virtualbox.org. 
If you don't care about getting the VirtualBox GUI, you can use Homebrew to install virtualbox.
```
brew cask install virtualbox
```

### Install Vagrant
_Not sure why `brew cask install` and not just `brew install` is needed, but it is._ 
```
brew cask install vagrant
```

### Verify that PHP 5.6 (or greater) is installed on your Mac
```
php --ini
```

To ensure you don't run out of memory running Composer, edit `php.ini`  using your plaintext editor of choice (see "Loaded Configuration File"). Change the default `memory_limit` (usually 128M) to `-1`

You've done it. You should now have all the requirements to run BLT successfully. Use Git to clone a BLT project, then run `composer install` in the project's directory.

**Comment by geerlingguy** [comment]
A few quick notes (I just ran a few setups on brand new Macs with nothing besides system software installed).

For the alias, we should probably just fix the blt alias command so it creates the file if it doesn't exist.

VirtualBox GUI should be installed regardless, if you're using cask.

I agree we should cater towards front end setup better; right now BLT is fairly front end agnostic; it should probably either assume Cog is the basis for the site theme or at least have a 'common front end tool setup' section.

Note also that many devs seem to like doing all their work inside Drupal VM (I don't, but many do)—the advantage being that, besides initial clone, every piece of software needed is already preinsyalled inside!

**Comment by grasmash** [comment]
@markf3lton Just curious, are you suggesting this as an improvement to http://blt.readthedocs.io/en/8.x/INSTALL/ ?

We do already have instructions for installing apple dev tools, homebrew, php, etc. 

I'm translating this issue as a request for the following:

- [ ] 
- [ ] 
- [ ]

**Comment by grasmash** [comment]
Issues addressed. Please re-open if this does not meet intended issue(s).
