### ISSUE TITLE
Local & CI Tests Fail with Git Hooks Disabled

### ISSUE THREAD

**Issue by epfremmer** [acquia/blt#885]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.2
* BLT version: 8.6.5

When I run this command with git hooks disabled:
```
blt tests:phpunit
```

I get the following output both locally and in Travis-CI:
```
  [phpunit] Testsuite: Acquia\Blt\Tests\BltProject\GitTasksTest::testGitHookCommitMsg
  [phpunit] Tests run: 9, Failures: 2, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.04021 s
  [phpunit] testGitHookCommitMsg with data set #7 FAILED
  [phpunit] Good commit.
  [phpunit] Failed asserting that true is not equal to true.
  [phpunit] testGitHookCommitMsg with data set #8 FAILED
  [phpunit] Long good commit.
  [phpunit] Failed asserting that true is not equal to true.
  [phpunit] Testsuite: Acquia\Blt\Tests\BltProject\GitTasksTest
  [phpunit] Tests run: 11, Failures: 4, Errors: 0, Incomplete: 0, Skipped: 0, Time elapsed: 0.05950 s
  [phpunit] testGitHookCommitMsg with data set #7 FAILED
  [phpunit] Good commit.
  [phpunit] Failed asserting that true is not equal to true.
  [phpunit] testGitHookCommitMsg with data set #8 FAILED
  [phpunit] Long good commit.
  [phpunit] Failed asserting that true is not equal to true.
  [phpunit] testGitPreCommitHook FAILED
  [phpunit] Failed asserting that '[detached HEAD 4ea5a98] BLT-123: This is a good commit.
  [phpunit]  Author: Edward Pfremmer <epfremme@nerdery.com>
  [phpunit]  Date: Wed Dec 28 16:37:10 2016 -0600
  [phpunit]  1 file changed, 3 insertions(+)
  [phpunit] ' contains "Sniffing staged files via PHP Code Sniffer.".
```

And I expected this to happen: All tests pass

It looks like the tests:phpunit phing task is hard coded to run PHPUnit tests from the '${blt.root}/tests/phpunit/BltProject' directory which in turn executes all BLT unit tests including `Acquia\Blt\Tests\BltProject`. The problem occurs because the BltProject is testing assuming that git-hooks are enabled. 

Possible solutions:

* Test if git hooks are not disable in the project config prior to testing them from the .git directory directly
* Make <batchtest> filesets configurable from project.yml to allow additional control over what tests get executed by `blt tests:phpunit` and `ci:build:validate:test`

**Comment by grasmash** [comment]
I think I'd may like to go with a third solution, which is to stop running these tests outside the context of the BLT repo itself. This would require:

- [ ] Remove BltProject tests from the tests:phpunit target, https://github.com/acquia/blt/blob/8.x/phing/tasks/tests.xml#L249
- [ ] Modify .travis.yml. Manually execute `phpunit tests/phpunit --group blt-project` after ci:build:validate:test [here](https://github.com/acquia/blt/blob/8.x/.travis.yml#L96)
