### ISSUE TITLE
Ansible needs to be at least 2.2

### ISSUE THREAD

**Issue by jakubsuchy** [acquia/blt#889]
Installation mentions Ansible but default brew installs Ansible 2.0 and 2.2 is required. Update install.md to require a minimal Ansible version.

**Comment by geerlingguy** [comment]
@jakubsuchy - It looks like 2.2.0 is the current version available in Homebrew:

```
$ brew info ansible
ansible: stable 2.2.0.0 (bottled), HEAD
```

**Comment by grasmash** [comment]
Closing due to @geerlingguy's comment:

> Ansible isn't technically required at all—if not installed locally, it will be installed at the right version inside the VM (and this is preferable on non-unixy environments). I'd rather not add it as a requirement in the BLT docs.
