### ISSUE TITLE
Investigate Parallelizing Behat tests

### ISSUE THREAD

**Issue by aweingarten** [acquia/blt#900]
Investigate running Behat tests in parallel.  Travis containers have 2 cores. In theory we could run some tests in parallel.

1: Investigate if this is possible
2: See if there are real world performance benefits.

**Comment by grasmash** [comment]
This seems like something that should be done per project, as needed. This is possible using Travis CI matrixes. 

For example, add the following to .travis.yml:

```
env:
  - BEHAT_TAGS='javascript'
  - BEHAT_TAGS='~javascript'

script:
...
  - blt ci:build:validate:test -Dcreate_alias=false -Dbehat.run-server=true -Dbehat.launch-phantom=true -Dblt.verbose=true -Dbehat.tags="$BEHAT_TAGS"
```

This would execute two parallel builds on Travis CI, one for each value of $BEHAT_TAGS.
