### ISSUE TITLE
Schema updates get run on new installs

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#909]
BLT assumes that if a schema_version file does not exist, then you must be updating from a pre-versioned BLT install: https://github.com/acquia/blt/blob/8.x/phing/tasks/properties.xml#L30

But new installs also have no schema_version file, so all available schema updates also run on new installs. I'm not sure if this is necessarily harmful, but it is definitely unnecessary.

I think the easiest solution would be for the install process to automatically generate a "fresh" schema_version file so updates don't get run... @grasmash thoughts?

**Comment by grasmash** [comment]
This will be resolved by #907

**Comment by grasmash** [comment]
Addressed in #913
