### ISSUE TITLE
Allow local database sanitization to be disabled

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#953]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.2
* BLT version: 8.6.6

When I run this command:
```
blt local:refresh
```

I get the following result:

The database is always sanitized locally, meaning users can't login with their prod username/password combos (everyone is forced to use `drush @site.local uli username` to log in).

And I _wanted_ this to happen:

I would like a way to disable the local database sanitization, so if we deem it secure enough to not sanitize local database copies, we can choose that option.

**Comment by brooke-heaton** [comment]
Can sanitization be turned off globally?
