### ISSUE TITLE
Travis and xvfb

### ISSUE THREAD

**Issue by danepowell** [acquia/blt#967]
It seems that #897 attempted to switch from installing xvfb via apt-get to installing it via the Travis add-on key. But don't think it's working--if that was the intent, the correct syntax is:

    addons:
      apt:
        packages:
          - xvfb

Note "packages" instead of "sources". Docs: https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages

However I'm honestly not even sure what xvfb is used for, so I'm not sure how to test that this works.

@aweingarten I think you initially worked on this, can you weigh in?

**Comment by grasmash** [comment]
It's intended to create a display buffer for Selenium tests. But if our tests work without it, let's remove.
