### ISSUE TITLE
Force MySQL TCP connections inside Travis container to fix subtle errors

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#991]
Two recent issues (#990, #720) I encountered _both_ seemed to be related to connecting to MySQL via `localhost` instead of via `127.0.0.1`. By default, the MySQL client tries to connect to a UNIX socket when you connect via `localhost`.

But a recent Travis CI infrastructure update seems to have reconfigured MySQL to only listen via TCP, therefore users who have `localhost` in their database `host` settings may encounter issues.

It looks like we may be able to force MySQL to send all connections to TCP by setting the client protocol explicitly, like so:

```
[client]
protocol=tcp
```

Thanks to [this ServerFault answer](http://serverfault.com/a/337928) for the suggestion/solution.

**Comment by geerlingguy** [comment]
One-liner in `.travis.yml` may fix this:

```yaml
  - printf '%s\n%s\n' '[client]' 'protocol=tcp' >> ~/.my.cnf
```

**Comment by geerlingguy** [comment]
Nope, that didn't work...

Leaving this open for now, but I can't burn any more time on this issue currently—it could be that we need to set the protocol at a higher level in MySQL config (not sure if .my.cnf is read for Drush commands), or that this doesn't actually work like I presume it would.

**Comment by grasmash** [comment]
@geerlingguy Did this fix the issue? #1053

**Comment by geerlingguy** [comment]
@grasmash - It seems to go deeper than that. See:

  - https://github.com/travis-ci/travis-ci/issues/6842#issuecomment-278671414
  - https://github.com/travis-ci/travis-ci/issues/6461

Note that it seems there's something deeper that's sporadically causing the failures on Travis CI. And it's so difficult to reliably reproduce the behavior, because you can run three builds on one PR, and one fails, then run five more and it never fails again.

**Comment by geerlingguy** [comment]
I've been hitting the connection issue about 70% of the time today, finally went with the painful workaround of setting `sudo: required` in the .travis.yml file, just because that's a guaranteed fix.

**Comment by grasmash** [comment]
@geerlingguy Is this still an active issue?

**Comment by geerlingguy** [comment]
@grasmash - It's still happening, yes... but I've temporarily made the problem go away by using the non-container instances (using `sudo: required`). It seems like the containers have issues with MySQL sometimes.

**Comment by grasmash** [comment]
I am going to consider this a Travis bug. Workaround is to use  `sudo: required`.
