### ISSUE TITLE
PHP notice on every command execution after upgrading to PHP 7 CLI

### ISSUE THREAD

**Issue by TravisCarden** [acquia/blt#995]
My system information:
* Operating system type: macOS
* Operating system version: Sierra 10.12.2
* BLT version: 8.6.10
* PHP CLI version: PHP 7.1.0

Starting with a fresh BLT site, created today according to the documentation, I get the following before the output from every `blt` command:
```
PHP Notice:  A non well formed numeric value encountered in /Users/travis.carden/Sites/d8/vendor/phing/phing/classes/phing/Phing.php on line 1636

Notice: A non well formed numeric value encountered in /Users/travis.carden/Sites/d8/vendor/phing/phing/classes/phing/Phing.php on line 1636
```

The notice occurs in `\Phing::convertShorthand()`, where the value of the `$val` argument it's getting is `string(4) "128M"`.

I recently updated my PHP CLI version to 7.1, which may account for the issue, since it's also happening on an older codebase that wasn't having the problem when I touched it last a month ago.

**Comment by grasmash** [comment]
Yeah this looks like an issue with Phing itself, and is likely specific to PHP 7.1.

**Comment by TravisCarden** [comment]
Hmm... Maybe you should consider gradually phasing out Phing. ;)

**Comment by grasmash** [comment]
Yeah.

I'm going to close this. Please open a Phing issue if you find this to be problematic.
